"use client";

import { useEffect, useState } from "react";
import type { Expense, ExpenseCategory, Payable, Vendor, VendorPayment } from "@zyteron/contracts";
import { BadgeCheck, Banknote, Building2, FilePlus2, Plus, Send } from "lucide-react";
import { useAccess } from "@/components/access-context";
import { financeApi, type UploadedFile } from "@/lib/finance-api";
import { canFinance, day, label, moment, money, todayIso } from "@/lib/finance-format";
import { AgingBar, Amount, DateInput, Drawer, Feedback, Field, FileInput, KeyValue, LoadError, Loading, Pill, ReasonDialog, Register, Section, Stamp, useAction, useLoad } from "./fx-ui";
import type { ViewProps } from "./finance-workspace";

type Paged<T>={items:T[];total:number;page:number;totalPages:number};
const validRut=(value:string)=>{const m=/^(\d{1,8})-?([\dkK])$/.exec(value.replace(/\./g,"").trim());if(!m)return false;let s=0,f=2;for(const d of m[1]!.split("").reverse()){s+=Number(d)*f;f=f===7?2:f+1;}const r=11-(s%11);return(r===11?"0":r===10?"K":String(r))===m[2]!.toUpperCase();};

export function Payables({tick}:ViewProps){
  const{role}=useAccess();const[q,setQ]=useState({status:"",overdue:false});const list=useLoad(()=>financeApi.get<Paged<Payable&{vendorName:string|null}>>(role,`/payables?pageSize=100${q.status?`&status=${q.status}`:""}${q.overdue?"&overdue=true":""}`),[role,q,tick]);const aging=useLoad(()=>financeApi.get<any>(role,"/payables/aging"),[role,tick]);
  const payments=useLoad(()=>financeApi.get<Paged<VendorPayment&{vendorName:string|null}>>(role,"/vendor-payments?pageSize=50"),[role,tick]);const banks=useLoad(()=>financeApi.get<any[]>(role,"/bank-accounts").catch(()=>[]),[role]);const action=useAction(async()=>{await list.reload();await aging.reload();await payments.reload();});
  const[selected,setSelected]=useState<Record<string,string>>({});const[dialog,setDialog]=useState<null|{id:string;action:"dispute"|"cancel"}>(null);const[schedule,setSchedule]=useState<{id:string;date:string}|null>(null);const[execute,setExecute]=useState<{id:string;evidence:UploadedFile|null;reference:string;paymentDate:string}|null>(null);const[bankAccountId,setBankAccountId]=useState("");
  const chosen=Object.entries(selected).filter(([,v])=>Number(v)>0);const vendorIds=new Set(chosen.map(([id])=>list.data?.items.find((p)=>p.id===id)?.vendorId));
  return <div className="fx-stack"><div className="fx-two"><Section eyebrow="ANTIGÜEDAD CXP" title={money(aging.data?.total)}>{aging.data?<AgingBar buckets={aging.data.buckets}/>:<Loading/>}</Section>
    <Section eyebrow="FLUJO DE PAGO" title="Solicitud → aprobación → registro con comprobante" description="Zyteron no transfiere dinero: registra transferencias ya realizadas con evidencia o con el cargo de la cartola. Quien solicita no aprueba."><ul className="fx-queue">{payments.data?.items.slice(0,8).map((p)=><li key={p.id}><div><strong>{p.paymentNumber} · {p.vendorName}</strong><small>{p.paymentDate?day(p.paymentDate):"Sin fecha"} · {label(p.method)}</small></div><Amount value={p.amount}/><Pill value={p.status}/>{p.status==="REQUESTED"&&canFinance(role,"payable.approve")?<button className="fx-btn small" onClick={()=>void action.run(()=>financeApi.post(role,`/vendor-payments/${p.id}/approve`),"Pago aprobado.")}>Aprobar</button>:p.status==="APPROVED"&&canFinance(role,"payable.pay")?<button className="fx-btn small" onClick={()=>setExecute({id:p.id,evidence:null,reference:"",paymentDate:todayIso()})}>Registrar pago</button>:null}</li>)}{!payments.data?.items.length?<li className="muted">Sin pagos a proveedores.</li>:null}</ul></Section></div>
    <Section eyebrow="OBLIGACIONES" title={`${list.data?.total??0} cuentas por pagar`} actions={<><label className="fx-check"><input type="checkbox" checked={q.overdue} onChange={(e)=>setQ({...q,overdue:e.target.checked})}/>Sólo vencidas</label><select value={q.status} onChange={(e)=>setQ({...q,status:e.target.value})}><option value="">Todos</option>{["PENDING_REVIEW","APPROVED","SCHEDULED","PARTIALLY_PAID","PAID","DISPUTED","CANCELLED"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select></>}>
      <Feedback error={action.error} notice={action.notice}/>
      {chosen.length?<div className="fx-callout"><strong>Solicitud de pago: {money(chosen.reduce((t,[,v])=>t+Number(v),0))}</strong>{vendorIds.size>1?<small className="bad">Selecciona obligaciones de un solo proveedor.</small>:null}<select value={bankAccountId} onChange={(e)=>setBankAccountId(e.target.value)}><option value="">Cuenta de origen…</option>{banks.data?.map((b)=><option key={b.id} value={b.id}>{b.bankName} ····{b.accountNumberLast4}</option>)}</select><button className="fx-btn primary" disabled={vendorIds.size!==1||action.busy} onClick={async()=>{const vendorId=[...vendorIds][0];const r=await action.run(()=>financeApi.post(role,"/vendor-payments",{vendorId,bankAccountId:bankAccountId||undefined,allocations:chosen.map(([payableId,amount])=>({payableId,amount:Number(amount)}))}),"Pago solicitado; requiere aprobación de otro usuario.");if(r)setSelected({});}}><Send size={14}/>Solicitar pago</button></div>:null}
      {list.data?<Register rows={list.data.items} rowKey={(p)=>p.id} columns={[{key:"sel",label:"",render:(p)=>canFinance(role,"payable.pay")&&["APPROVED","SCHEDULED","PARTIALLY_PAID"].includes(p.status)?<input className="fx-mini" inputMode="numeric" placeholder="Monto" value={selected[p.id]??""} onChange={(e)=>setSelected({...selected,[p.id]:e.target.value.replace(/\D/g,"")})} onFocus={()=>!selected[p.id]&&setSelected({...selected,[p.id]:String(p.balance)})} aria-label="Monto a pagar"/>:null},{key:"v",label:"Proveedor",render:(p)=><><strong>{p.vendorName}</strong><small className="block">{p.documentNumber??label(p.sourceType)}</small></>},{key:"d",label:"Detalle",render:(p)=>p.description.slice(0,60)},{key:"due",label:"Vence",render:(p)=>day(p.scheduledFor??p.dueDate)},{key:"a",label:"Monto",align:"right",render:(p)=><Amount value={p.amount}/>},{key:"b",label:"Saldo",align:"right",render:(p)=><Amount value={p.balance} strong/>},{key:"s",label:"Estado",render:(p)=><Pill value={p.effectiveStatus}/>},{key:"x",label:"",render:(p)=>canFinance(role,"payable.approve")?<div className="fx-row-actions">{p.status==="PENDING_REVIEW"?<button className="fx-btn small" onClick={()=>void action.run(()=>financeApi.post(role,`/payables/${p.id}/approve`),"Obligación aprobada.")}>Aprobar</button>:null}{["APPROVED","SCHEDULED","PARTIALLY_PAID"].includes(p.status)?<button className="fx-btn small ghost" onClick={()=>setSchedule({id:p.id,date:p.dueDate})}>Programar</button>:null}{!["PAID","CANCELLED","DISPUTED"].includes(p.status)?<button className="fx-btn small ghost" onClick={()=>setDialog({id:p.id,action:"dispute"})}>Disputar</button>:null}{p.status==="DISPUTED"?<button className="fx-btn small ghost" onClick={()=>void action.run(()=>financeApi.post(role,`/payables/${p.id}/resolve`),"Disputa resuelta.")}>Resolver</button>:null}</div>:null}]} empty="Sin obligaciones"/>:list.error?<LoadError error={list.error} retry={()=>void list.reload()}/>:<Loading/>}
    </Section>
    <ReasonDialog open={dialog!==null} title={dialog?.action==="dispute"?"Disputar obligación":"Anular obligación"} onCancel={()=>setDialog(null)} onConfirm={(reason)=>{const d=dialog!;setDialog(null);void action.run(()=>financeApi.post(role,`/payables/${d.id}/${d.action}`,{reason}),"Obligación actualizada.");}}/>
    <Drawer open={Boolean(schedule)} title="Programar pago" onClose={()=>setSchedule(null)}>{schedule?<><Field label="Fecha programada"><DateInput value={schedule.date} onChange={(v)=>setSchedule({...schedule,date:v})}/></Field><div className="fx-actions end"><button className="fx-btn primary" onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/payables/${schedule.id}/schedule`,{scheduledFor:schedule.date}),"Pago programado.");if(r)setSchedule(null);}}>Programar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(execute)} title="Registrar pago realizado" subtitle="Adjunta el comprobante de la transferencia efectuada en el banco." onClose={()=>setExecute(null)}>{execute?<><div className="fx-form"><Field label="Fecha de pago"><DateInput value={execute.paymentDate} onChange={(v)=>setExecute({...execute,paymentDate:v})}/></Field><Field label="N° de operación" span={2}><input value={execute.reference} onChange={(e)=>setExecute({...execute,reference:e.target.value})}/></Field><Field label="Comprobante" span={3}><FileInput accept=".pdf,.png,.jpg" file={execute.evidence} onFile={(f)=>setExecute({...execute,evidence:f})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!execute.evidence||action.busy} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/vendor-payments/${execute.id}/execute`,{paymentDate:execute.paymentDate,reference:execute.reference,evidence:execute.evidence}),"Pago registrado con evidencia.");if(r)setExecute(null);}}><Banknote size={14}/>Registrar</button></div></>:null}</Drawer>
  </div>;
}

export function Vendors({tick}:ViewProps){
  const{role}=useAccess();const[search,setSearch]=useState("");const list=useLoad(()=>financeApi.get<Paged<Vendor>>(role,`/vendors?pageSize=100${search?`&search=${encodeURIComponent(search)}`:""}`),[role,search,tick]);const[open,setOpen]=useState<string|null>(null);const detail=useLoad(()=>open?financeApi.get<any>(role,`/vendors/${open}`):Promise.resolve(null),[role,open]);
  const[form,setForm]=useState<any>(null);const action=useAction(async()=>{await list.reload();await detail.reload();});const editable=canFinance(role,"expense.create")||canFinance(role,"payable.approve");
  return <div className="fx-stack"><Section eyebrow="PROVEEDORES" title={`${list.data?.total??0} proveedores`} actions={<><input className="fx-search-input" placeholder="Razón social o RUT" value={search} onChange={(e)=>setSearch(e.target.value)}/>{editable?<button className="fx-btn primary" onClick={()=>setForm({rut:"",legalName:"",paymentTermsDays:"30",bankName:"",bankAccountType:"",bankAccountNumber:""})}><Plus size={14}/>Proveedor</button>:null}</>}>
    {list.data?<Register rows={list.data.items} rowKey={(v)=>v.id} onRow={(v)=>setOpen(v.id)} selected={open} columns={[{key:"n",label:"Proveedor",render:(v)=><><strong>{v.tradeName??v.legalName}</strong><small className="block">{v.rut}</small></>},{key:"c",label:"Contacto",render:(v)=>v.email??v.contactName??"—"},{key:"t",label:"Plazo",render:(v)=>`${v.paymentTermsDays} días`},{key:"b",label:"Banco",render:(v)=>v.bankName?`${v.bankName} ····${v.bankAccountLast4??"—"}`:"Sin datos"},{key:"s",label:"Estado",render:(v)=><Pill value={v.status}/>}]} empty="Sin proveedores"/>:list.error?<LoadError error={list.error} retry={()=>void list.reload()}/>:<Loading/>}</Section>
    <Drawer open={Boolean(open)} title="Proveedor 360" onClose={()=>setOpen(null)} wide>{detail.data?<><KeyValue items={[["Razón social",detail.data.vendor.legalName],["RUT",detail.data.vendor.rut],["Giro",detail.data.vendor.businessActivity??"—"],["Cuenta bancaria",detail.data.vendor.bankName?`${detail.data.vendor.bankName} ····${detail.data.vendor.bankAccountLast4}${detail.data.vendor.hasEncryptedBankAccount?" (completo cifrado)":""}`:"—"],["Saldo por pagar",money(detail.data.totals.outstanding)],["Compras aprobadas del año",money(detail.data.totals.purchasedYtd)]]}/>
      <Section eyebrow="DOCUMENTOS RECIBIDOS" title={`${detail.data.documents.length}`}><Register rows={detail.data.documents} rowKey={(d:any)=>d.id} columns={[{key:"f",label:"Folio",render:(d:any)=>`${d.documentTypeCode} · ${d.folio}`},{key:"d",label:"Fecha",render:(d:any)=>day(d.issueDate)},{key:"t",label:"Total",align:"right",render:(d:any)=><Amount value={d.totalAmount}/>},{key:"c",label:"Crédito",render:(d:any)=><Pill value={d.taxCreditClassification==="PENDING_REVIEW"?"PENDING_REVIEW":"OK"} text={label(d.taxCreditClassification)}/>}]} empty="Sin DTE recibidos"/></Section>
      <Section eyebrow="CUENTAS POR PAGAR" title={`${detail.data.payables.length}`}><Register rows={detail.data.payables} rowKey={(p:any)=>p.id} columns={[{key:"d",label:"Detalle",render:(p:any)=>p.description.slice(0,50)},{key:"v",label:"Vence",render:(p:any)=>day(p.dueDate)},{key:"b",label:"Saldo",align:"right",render:(p:any)=><Amount value={p.balance}/>},{key:"s",label:"Estado",render:(p:any)=><Pill value={p.effectiveStatus}/>}]} empty="Sin obligaciones"/></Section></>:<Loading/>}</Drawer>
    <Drawer open={Boolean(form)} title="Nuevo proveedor" subtitle="El número de cuenta completo sólo se guarda cifrado en el servidor; en pantalla se ven los últimos 4 dígitos." onClose={()=>setForm(null)}>{form?<><div className="fx-form"><Field label="RUT"><input value={form.rut} aria-invalid={form.rut!==""&&!validRut(form.rut)} onChange={(e)=>setForm({...form,rut:e.target.value})}/></Field><Field label="Razón social" span={2}><input value={form.legalName} onChange={(e)=>setForm({...form,legalName:e.target.value})}/></Field><Field label="Nombre de fantasía"><input value={form.tradeName??""} onChange={(e)=>setForm({...form,tradeName:e.target.value})}/></Field><Field label="Email"><input type="email" value={form.email??""} onChange={(e)=>setForm({...form,email:e.target.value})}/></Field><Field label="Plazo (días)"><input inputMode="numeric" value={form.paymentTermsDays} onChange={(e)=>setForm({...form,paymentTermsDays:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Banco"><input value={form.bankName} onChange={(e)=>setForm({...form,bankName:e.target.value})}/></Field><Field label="Tipo de cuenta"><input value={form.bankAccountType} onChange={(e)=>setForm({...form,bankAccountType:e.target.value})}/></Field><Field label="N° de cuenta"><input autoComplete="off" value={form.bankAccountNumber} onChange={(e)=>setForm({...form,bankAccountNumber:e.target.value.replace(/\D/g,"")})}/></Field></div>
      <Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!validRut(form.rut)||!form.legalName||action.busy} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/vendors",{...form,paymentTermsDays:Number(form.paymentTermsDays||30),bankAccountNumber:form.bankAccountNumber||undefined}),"Proveedor creado.");if(r)setForm(null);}}><Building2 size={14}/>Crear</button></div></>:null}</Drawer></div>;
}

export function Expenses({tick}:ViewProps){
  const{role}=useAccess();const[status,setStatus]=useState("");const list=useLoad(()=>financeApi.get<Paged<Expense&{vendorName:string|null}>>(role,`/expenses?pageSize=100${status?`&status=${status}`:""}`),[role,status,tick]);const inbox=useLoad(()=>financeApi.get<any[]>(role,"/approvals/inbox"),[role,tick]);
  const categories=useLoad(()=>financeApi.get<ExpenseCategory[]>(role,"/expense-categories"),[role]);const vendors=useLoad(()=>financeApi.get<Paged<Vendor>>(role,"/vendors?pageSize=100").catch(()=>({items:[],total:0,page:1,totalPages:1})),[role]);const centers=useLoad(()=>financeApi.get<any[]>(role,"/cost-centers"),[role]);
  const action=useAction(async()=>{await list.reload();await inbox.reload();});const[form,setForm]=useState<any>(null);const[open,setOpen]=useState<string|null>(null);const detail=useLoad(()=>open?financeApi.get<any>(role,`/expenses/${open}`):Promise.resolve(null),[role,open,action.notice]);const[classify,setClassify]=useState<any>(null);const[dialog,setDialog]=useState<null|"reject"|"cancel">(null);
  useEffect(()=>{const fromReceived=new URLSearchParams(window.location.search).get("fromReceived");if(fromReceived)setForm({fromReceived,categoryId:""});},[]);
  const total=(f:any)=>Number(f.netAmount||0)+Number(f.exemptAmount||0)+Number(f.taxAmount||0);
  return <div className="fx-stack">{inbox.data?.length?<Section eyebrow="TU BANDEJA" title={`${inbox.data.length} aprobaciones pendientes`}><ul className="fx-queue">{inbox.data.map((r)=><li key={r.id}><div><strong>{label(r.entityType)} · nivel {r.level}</strong><small>Requiere {r.requiredRole==="ANY_APPROVER"?"rol con permiso de aprobación":r.requiredRole}</small></div>{r.entityType==="EXPENSE"?<button className="fx-btn small" onClick={()=>setOpen(r.entityId)}>Revisar</button>:null}</li>)}</ul></Section>:null}
    <Section eyebrow="GASTOS" title={`${list.data?.total??0} gastos`} description="Respaldo obligatorio, aprobación por políticas configurables (sin límites fijos en código) y clasificación explícita del IVA." actions={<><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos</option>{["DRAFT","PENDING_APPROVAL","APPROVED","REJECTED","CANCELLED"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select>{canFinance(role,"expense.create")?<button className="fx-btn primary" onClick={()=>setForm({categoryId:"",vendorId:"",expenseDate:todayIso(),description:"",netAmount:"",exemptAmount:"",taxAmount:"",costCenterId:"",paymentMethod:"TRANSFER",evidence:null})}><FilePlus2 size={14}/>Registrar gasto</button>:null}</>}>
      <Feedback error={action.error} notice={action.notice}/>
      {list.data?<Register rows={list.data.items} rowKey={(e)=>e.id} onRow={(e)=>setOpen(e.id)} selected={open} columns={[{key:"n",label:"Gasto",render:(e)=><><strong>{e.expenseNumber}</strong><small className="block">{e.description.slice(0,50)}</small></>},{key:"v",label:"Proveedor",render:(e)=>e.vendorName??"—"},{key:"d",label:"Fecha",render:(e)=>day(e.expenseDate)},{key:"t",label:"Total",align:"right",render:(e)=><Amount value={e.totalAmount}/>},{key:"c",label:"Crédito fiscal",render:(e)=>e.taxAmount?<Pill value={e.taxCreditClassification==="PENDING_REVIEW"?"PENDING_REVIEW":"OK"} text={e.taxCreditClassification==="PENDING_REVIEW"?"Por clasificar":`${label(e.taxCreditClassification)} · ${money(e.eligibleTaxAmount)}`}/>:<small>Sin IVA</small>},{key:"s",label:"Estado",render:(e)=><Pill value={e.status}/>}]} empty="Sin gastos"/>:list.error?<LoadError error={list.error} retry={()=>void list.reload()}/>:<Loading/>}
    </Section>
    <Drawer open={Boolean(form)} title={form?.fromReceived?"Gasto desde DTE recibido":"Registrar gasto"} onClose={()=>setForm(null)} wide>{form?<><div className="fx-form"><Field label="Categoría"><select value={form.categoryId} onChange={(e)=>setForm({...form,categoryId:e.target.value})}><option value="">Selecciona…</option>{categories.data?.filter((c)=>c.active).map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
      {form.fromReceived?<p className="fx-hint">Montos, proveedor y folio se toman del XML recibido (no se editan).</p>:<><Field label="Proveedor"><select value={form.vendorId} onChange={(e)=>setForm({...form,vendorId:e.target.value})}><option value="">Sin proveedor (rendición)</option>{vendors.data?.items.map((v)=><option key={v.id} value={v.id}>{v.legalName}</option>)}</select></Field><Field label="Fecha"><DateInput value={form.expenseDate} onChange={(v)=>setForm({...form,expenseDate:v})}/></Field><Field label="Descripción" span={3}><input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></Field><Field label="Neto"><input inputMode="numeric" value={form.netAmount} onChange={(e)=>setForm({...form,netAmount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Exento"><input inputMode="numeric" value={form.exemptAmount} onChange={(e)=>setForm({...form,exemptAmount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="IVA del documento" hint="No se asume recuperable"><input inputMode="numeric" value={form.taxAmount} onChange={(e)=>setForm({...form,taxAmount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Total"><strong className="fx-amount strong">{money(total(form))}</strong></Field><Field label="Medio de pago"><select value={form.paymentMethod} onChange={(e)=>setForm({...form,paymentMethod:e.target.value})}>{["TRANSFER","CARD","CASH","CHECK","OTHER"].map((m)=><option key={m} value={m}>{label(m)}</option>)}</select></Field><Field label="Respaldo" span={2}><FileInput accept=".pdf,.png,.jpg,.xml" file={form.evidence} onFile={(f)=>setForm({...form,evidence:f})}/></Field></>}
      <Field label="Centro de costo"><select value={form.costCenterId??""} onChange={(e)=>setForm({...form,costCenterId:e.target.value})}><option value="">Por defecto de la categoría</option>{centers.data?.map((c)=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></Field></div>
      <Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!form.categoryId||action.busy||(!form.fromReceived&&(!form.description||!total(form)||!form.evidence))} onClick={async()=>{const r=await action.run<any>(()=>form.fromReceived?financeApi.post(role,`/received-documents/${form.fromReceived}/expense`,{categoryId:form.categoryId,costCenterId:form.costCenterId||undefined}):financeApi.post(role,"/expenses",{...form,netAmount:Number(form.netAmount||0),exemptAmount:Number(form.exemptAmount||0),taxAmount:Number(form.taxAmount||0),vendorId:form.vendorId||undefined,costCenterId:form.costCenterId||undefined}),"Gasto registrado en borrador.");if(r){setForm(null);setOpen(r.id);}}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(open)} title={`Gasto ${detail.data?.expenseNumber??""}`} subtitle={detail.data?<Pill value={detail.data.status}/>:undefined} onClose={()=>setOpen(null)} wide>{detail.data?<><KeyValue items={[["Descripción",detail.data.description],["Proveedor",detail.data.vendorName??"—"],["Fecha",day(detail.data.expenseDate)],["Neto / exento / IVA",`${money(detail.data.netAmount)} / ${money(detail.data.exemptAmount)} / ${money(detail.data.taxAmount)}`],["Total",money(detail.data.totalAmount)],["Crédito fiscal",detail.data.taxCreditClassification==="PENDING_REVIEW"?"Por clasificar":`${label(detail.data.taxCreditClassification)} · ${money(detail.data.eligibleTaxAmount)} · ${detail.data.classificationReason}`],["Respaldo",detail.data.evidencePath||detail.data.receivedTaxDocumentId?"Adjunto":"Falta respaldo"]]}/>
      <Feedback error={action.error} notice={action.notice}/>
      <div className="fx-actions">{detail.data.status==="DRAFT"&&canFinance(role,"expense.create")?<button className="fx-btn primary" onClick={()=>void action.run(()=>financeApi.post(role,`/expenses/${open}/submit`),"Enviado a aprobación.")}><Send size={14}/>Enviar a aprobación</button>:null}{["DRAFT","PENDING_APPROVAL"].includes(detail.data.status)&&detail.data.taxAmount>0&&(canFinance(role,"tax.review")||canFinance(role,"expense.approve"))?<button className="fx-btn" onClick={()=>setClassify({classification:"DEL_GIRO",eligible:true,eligibleAmount:"",reason:""})}>Clasificar IVA</button>:null}{detail.data.status==="PENDING_APPROVAL"&&canFinance(role,"expense.approve")?<><button className="fx-btn primary" onClick={()=>void action.run(()=>financeApi.post(role,`/expenses/${open}/decide`,{decision:"APPROVED"}),"Decisión registrada.")}><BadgeCheck size={14}/>Aprobar</button><button className="fx-btn ghost" onClick={()=>setDialog("reject")}>Rechazar</button></>:null}{["DRAFT","PENDING_APPROVAL"].includes(detail.data.status)&&canFinance(role,"expense.create")?<button className="fx-btn ghost" onClick={()=>setDialog("cancel")}>Anular</button>:null}</div>
      <Section eyebrow="APROBACIONES" title="Niveles"><ol className="fx-timeline">{detail.data.approvals.map((a:any)=><li key={a.id}><time>Nivel {a.level}</time><span><Pill value={a.status}/> {a.requiredRole==="ANY_APPROVER"?"Aprobador con permiso":a.requiredRole}{a.decidedAt?` · ${moment(a.decidedAt)}`:""}{a.comment?` · ${a.comment}`:""}</span></li>)}{!detail.data.approvals.length?<li className="muted">Aún no se solicita aprobación.</li>:null}</ol></Section>
      {classify?<div className="fx-form boxed"><Field label="Clasificación" span={2}><select value={classify.classification} onChange={(e)=>setClassify({...classify,classification:e.target.value})}>{["DEL_GIRO","ACTIVO_FIJO","USO_COMUN","SUPERMERCADO","BIENES_RAICES","NO_RECUPERABLE","NO_CORRESPONDE"].map((c)=><option key={c} value={c}>{label(c)}</option>)}</select></Field><Field label="¿Crédito fiscal?"><select value={String(classify.eligible)} onChange={(e)=>setClassify({...classify,eligible:e.target.value==="true"})}><option value="true">Sí</option><option value="false">No</option></select></Field>{classify.eligible?<Field label="Monto de crédito" hint="Vacío = 100% del IVA"><input inputMode="numeric" value={classify.eligibleAmount} onChange={(e)=>setClassify({...classify,eligibleAmount:e.target.value.replace(/\D/g,"")})}/></Field>:null}<Field label="Fundamento" span={3}><input value={classify.reason} onChange={(e)=>setClassify({...classify,reason:e.target.value})}/></Field><div className="fx-actions"><button className="fx-btn primary" disabled={!classify.reason} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/expenses/${open}/classify`,{...classify,eligibleAmount:classify.eligibleAmount===""?undefined:Number(classify.eligibleAmount)}),"Clasificación registrada.");if(r)setClassify(null);}}>Guardar clasificación</button></div></div>:null}</>:<Loading/>}</Drawer>
    <ReasonDialog open={dialog!==null} title={dialog==="reject"?"Rechazar gasto":"Anular gasto"} onCancel={()=>setDialog(null)} onConfirm={(reason)=>{const d=dialog;setDialog(null);void action.run(()=>d==="reject"?financeApi.post(role,`/expenses/${open}/decide`,{decision:"REJECTED",comment:reason}):financeApi.post(role,`/expenses/${open}/cancel`,{reason}),"Gasto actualizado.");}}/>
    <Stamp kind="info">Pagos con tarjeta o efectivo no generan cuenta por pagar.</Stamp>
  </div>;
}
