"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { AccountingPeriod, AccountingRule, Budget, JournalEntry, LedgerAccount } from "@zyteron/contracts";
import { BookCheck, Download, FilePlus2, Lock, Plus, RefreshCw, RotateCcw, Scale, Send, Trash2, Unlock } from "lucide-react";
import { useAccess } from "@/components/access-context";
import { financeApi } from "@/lib/finance-api";
import { canFinance, day, label, moment, money, monthKey, period, todayIso } from "@/lib/finance-format";
import { Amount, DateInput, Drawer, Empty, Feedback, Field, LoadError, Loading, Pill, ReasonDialog, Register, Section, Stamp, useAction, useLoad, useQueryParams } from "./fx-ui";
import type { ViewProps } from "./finance-workspace";

type Paged<T>={items:T[];total:number;page:number;totalPages:number};
const useAccounts=(role:Parameters<typeof financeApi.get>[0],withBalances=false)=>useLoad(()=>financeApi.get<Array<LedgerAccount&{balance?:number}>>(role,`/accounts${withBalances?"?balances=true":""}`),[role,withBalances]);
export function AccountSelect({accounts,value,onChange,postingOnly=true}:{accounts:LedgerAccount[];value:string;onChange:(id:string)=>void;postingOnly?:boolean}){return <select value={value} onChange={(e)=>onChange(e.target.value)} aria-label="Cuenta contable"><option value="">Cuenta…</option>{accounts.filter((a)=>a.active&&(!postingOnly||a.allowsPosting)).map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select>;}

export function AccountingHome({tick}:ViewProps){
  const{role}=useAccess();const[tab,setTab]=useState<"events"|"rules"|"periods">("events");useQueryParams((p)=>{const t=p.get("tab");if(t==="rules"||t==="periods")setTab(t);});
  const events=useLoad(()=>tab==="events"?financeApi.get<Paged<any>>(role,"/accounting-events?pageSize=100"):Promise.resolve(null),[role,tab,tick]);const rules=useLoad(()=>tab==="rules"?financeApi.get<AccountingRule[]>(role,"/rules"):Promise.resolve(null),[role,tab,tick]);const periods=useLoad(()=>tab==="periods"?financeApi.get<AccountingPeriod[]>(role,"/periods"):Promise.resolve(null),[role,tab,tick]);
  const action=useAction(async()=>{await events.reload();await rules.reload();await periods.reload();});const[reopen,setReopen]=useState<string|null>(null);const manageRules=canFinance(role,"journal.review")||canFinance(role,"finance.settings.manage");
  return <div className="fx-stack"><div className="fx-toolbar"><div className="fx-tabs" role="tablist">{([["events","Hechos económicos"],["rules","Reglas contables"],["periods","Períodos"]] as const).map(([k,t])=><button key={k} role="tab" aria-selected={tab===k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</div><Stamp kind="info">La automatización crea borradores · la contabilización es humana</Stamp></div>
    <Feedback error={action.error} notice={action.notice}/>
    {tab==="events"?<Section eyebrow="ORIGEN DE ASIENTOS" title="Hechos económicos" description="Cada factura emitida, cobro, aplicación, gasto o pago genera un evento idempotente. Sin regla activa queda «Sin regla» (nada se inventa)." actions={canFinance(role,"journal.create")?<button className="fx-btn" disabled={action.busy} onClick={()=>void action.run<any>(()=>financeApi.post(role,"/accounting-events/reprocess")).then((r)=>r&&action.setNotice(`${r.processed} procesados · ${r.created} borradores · ${r.unmapped} sin regla · ${r.errors} con error`))}><RefreshCw size={14}/>Reprocesar pendientes</button>:null}>
      {events.data?<Register rows={events.data.items} rowKey={(e)=>e.id} columns={[{key:"d",label:"Fecha",render:(e)=>day(e.occurredOn)},{key:"t",label:"Evento",render:(e)=><><strong>{e.eventType}</strong><small className="block">{e.sourceType}</small></>},{key:"a",label:"Montos",render:(e)=><small>{Object.entries(e.amounts as Record<string,number>).filter(([,v])=>v).map(([k,v])=>`${k} ${money(v)}`).join(" · ")}</small>},{key:"s",label:"Estado",render:(e)=><><Pill value={e.status}/>{e.message?<small className="block">{e.message}</small>:null}</>},{key:"j",label:"Asiento",render:(e)=>e.journalEntryId?<Link href={`/finance/journal?entry=${e.journalEntryId}`}>Ver</Link>:"—"}]} empty="Sin hechos económicos registrados"/>:events.error?<LoadError error={events.error} retry={()=>void events.reload()}/>:<Loading/>}</Section>:null}
    {tab==="rules"?<Section eyebrow="ACCOUNTING RULE ENGINE" title="Reglas versionadas" description="Las reglas base nacen en borrador: contabilidad revisa cuentas y activa. Una versión activa es inmutable; los cambios crean una nueva versión.">
      {rules.data?<div className="fx-rules">{rules.data.map((r)=>{const active=r.versions?.find((v)=>v.status==="ACTIVE");const draft=r.versions?.find((v)=>v.status==="DRAFT");const shown=active??draft;return <article key={r.id} className={r.active?"on":""}><header><div><strong>{r.name}</strong><small>{r.code} · evento {r.eventType}{Object.keys(r.filters??{}).length?` · ${Object.entries(r.filters).map(([k,v])=>`${k}=${v}`).join(", ")}`:""}</small></div><Pill value={r.active?"ACTIVE":"INACTIVE"}/></header>
        {shown?<table><thead><tr><th>Lado</th><th>Cuenta</th><th>Monto</th><th>Dimensiones</th></tr></thead><tbody>{shown.lines.map((l,i)=><tr key={i}><td>{l.side==="DEBIT"?"Debe":"Haber"}</td><td>{l.account.code??`${l.account.context} → ${l.account.fallbackCode}`}</td><td>{l.amount.join(" + ")}</td><td>{l.dimensions.join(", ")||"—"}</td></tr>)}</tbody></table>:null}
        <footer><small>Versión {shown?.version} · {label(shown?.status)}{active?.activatedAt?` · activada ${moment(active.activatedAt)}`:""}</small>{manageRules?<div className="fx-row-actions">{draft&&!active?<button className="fx-btn small primary" onClick={()=>void action.run(()=>financeApi.post(role,`/rule-versions/${draft.id}/activate`),`Regla ${r.code} activada.`)}>Revisar y activar</button>:null}{r.active?<button className="fx-btn small ghost" onClick={()=>void action.run(()=>financeApi.post(role,`/rules/${r.id}/deactivate`),"Regla desactivada.")}>Desactivar</button>:null}</div>:null}</footer></article>;})}</div>:<Loading/>}</Section>:null}
    {tab==="periods"?<Section eyebrow="PERÍODOS CONTABLES" title="Estado de los meses" description="Cerrado o bloqueado: la base rechaza contabilizar. Reabrir exige permiso y motivo, y queda auditado.">
      {periods.data?<Register rows={periods.data} rowKey={(p)=>p.id} columns={[{key:"k",label:"Período",render:(p)=><strong>{period(p.periodKey)}</strong>},{key:"s",label:"Estado",render:(p)=><Pill value={p.status}/>},{key:"c",label:"Cerrado",render:(p)=>p.closedAt?moment(p.closedAt):"—"},{key:"r",label:"Reaperturas",render:(p)=>p.reopenCount?`${p.reopenCount} · ${p.reopenReason}`:"—"},{key:"x",label:"",render:(p)=><div className="fx-row-actions"><Link className="fx-btn small ghost" href={`/finance/closing?period=${p.periodKey}`}>Cierre</Link>{p.status==="CLOSED"&&canFinance(role,"period.close")?<button className="fx-btn small ghost" onClick={()=>void action.run(()=>financeApi.post(role,`/periods/${p.id}/lock`),"Período bloqueado.")}><Lock size={12}/>Bloquear</button>:null}{["CLOSED","LOCKED"].includes(p.status)&&canFinance(role,"period.reopen")?<button className="fx-btn small ghost" onClick={()=>setReopen(p.id)}><Unlock size={12}/>Reabrir</button>:null}</div>}]} empty="Sin períodos aún"/>:<Loading/>}</Section>:null}
    <ReasonDialog open={Boolean(reopen)} title="Reabrir período" description="Sólo Finanzas, Contabilidad o Gerencia. Un período bloqueado sólo lo reabre Gerencia." onCancel={()=>setReopen(null)} onConfirm={(reason)=>{const id=reopen;setReopen(null);void action.run(()=>financeApi.post(role,`/periods/${id}/reopen`,{reason}),"Período reabierto.");}}/>
  </div>;
}

type DraftLine={accountId:string;debit:string;credit:string;description:string;costCenterId:string};
function EntryComposer({accounts,centers,onClose,onSaved,initial}:{accounts:LedgerAccount[];centers:any[];onClose:()=>void;onSaved:(id:string)=>void;initial?:JournalEntry|null}){
  const{role}=useAccess();const[date,setDate]=useState(initial?.entryDate??todayIso());const[description,setDescription]=useState(initial?.description??"");const[lines,setLines]=useState<DraftLine[]>(initial?.lines?.map((l)=>({accountId:l.accountId,debit:l.debit?String(l.debit):"",credit:l.credit?String(l.credit):"",description:l.description??"",costCenterId:l.costCenterId??""}))??[{accountId:"",debit:"",credit:"",description:"",costCenterId:""},{accountId:"",debit:"",credit:"",description:"",costCenterId:""}]);const action=useAction();
  const debit=lines.reduce((t,l)=>t+Number(l.debit||0),0),credit=lines.reduce((t,l)=>t+Number(l.credit||0),0);const balanced=Math.round(debit*100)===Math.round(credit*100)&&debit>0;const set=(i:number,patch:Partial<DraftLine>)=>setLines(lines.map((l,n)=>n===i?{...l,...patch}:l));
  const save=async(submit:boolean)=>{const body={entryDate:date,description,submit,lines:lines.filter((l)=>l.accountId).map((l)=>({accountId:l.accountId,debit:Number(l.debit||0),credit:Number(l.credit||0),description:l.description||undefined,costCenterId:l.costCenterId||undefined}))};const r=await action.run(()=>initial?financeApi.patch<JournalEntry>(role,`/journal/${initial.id}`,body):financeApi.post<JournalEntry>(role,"/journal",body));if(r)onSaved(r.id);};
  return <Drawer open title={initial?"Editar borrador":"Nuevo asiento"} subtitle="Partida doble: el asiento sólo se contabiliza si TOTAL DEBE = TOTAL HABER." onClose={onClose} wide>
    <div className="fx-form"><Field label="Fecha"><DateInput value={date} onChange={setDate}/></Field><Field label="Glosa" span={2}><input value={description} onChange={(e)=>setDescription(e.target.value)}/></Field></div>
    <div className="fx-lines journal"><table><thead><tr><th>Cuenta</th><th>Centro de costo</th><th>Detalle</th><th className="r">Debe</th><th className="r">Haber</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={i}><td><AccountSelect accounts={accounts} value={l.accountId} onChange={(id)=>set(i,{accountId:id})}/></td><td><select value={l.costCenterId} onChange={(e)=>set(i,{costCenterId:e.target.value})}><option value="">—</option>{centers.map((c)=><option key={c.id} value={c.id}>{c.code}</option>)}</select></td><td><input value={l.description} onChange={(e)=>set(i,{description:e.target.value})}/></td><td><input inputMode="decimal" value={l.debit} disabled={Boolean(l.credit)} onChange={(e)=>set(i,{debit:e.target.value.replace(/[^\d.]/g,"")})}/></td><td><input inputMode="decimal" value={l.credit} disabled={Boolean(l.debit)} onChange={(e)=>set(i,{credit:e.target.value.replace(/[^\d.]/g,"")})}/></td><td>{lines.length>2?<button className="fx-icon" onClick={()=>setLines(lines.filter((_,n)=>n!==i))} aria-label="Quitar">×</button>:null}</td></tr>)}</tbody>
      <tfoot><tr className="total"><td colSpan={3}><button className="fx-btn ghost small" onClick={()=>setLines([...lines,{accountId:"",debit:"",credit:"",description:"",costCenterId:""}])}><Plus size={12}/>Línea</button></td><td className="r">{money(debit)}</td><td className="r">{money(credit)}</td><td/></tr></tfoot></table></div>
    <div className={`fx-balance-meter ${balanced?"ok":debit+credit===0?"idle":"off"}`} role="status"><Scale size={16}/><span>{balanced?"Cuadrado: Debe = Haber":debit+credit===0?"Ingresa montos en Debe y Haber":`Descuadre ${money(Math.abs(debit-credit))} — no se podrá contabilizar`}</span><div><i style={{width:`${debit+credit?Math.min(100,(debit/(Math.max(debit,credit)))*100):0}%`}}/><i className="credit" style={{width:`${debit+credit?Math.min(100,(credit/(Math.max(debit,credit)))*100):0}%`}}/></div></div>
    <Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn ghost" onClick={onClose}>Cancelar</button><button className="fx-btn" disabled={action.busy||!description} onClick={()=>void save(false)}>Guardar borrador</button>{!initial?<button className="fx-btn primary" disabled={action.busy||!description||!balanced} onClick={()=>void save(true)}><Send size={14}/>Enviar a revisión</button>:null}</div>
  </Drawer>;
}

export function Journal({tick}:ViewProps){
  const{role}=useAccess();const[status,setStatus]=useState("");const[page,setPage]=useState(1);const list=useLoad(()=>financeApi.get<Paged<JournalEntry>>(role,`/journal?page=${page}&pageSize=30${status?`&status=${status}`:""}`),[role,status,page,tick]);
  const accounts=useAccounts(role);const centers=useLoad(()=>financeApi.get<any[]>(role,"/cost-centers"),[role]);const[open,setOpen]=useState<string|null>(null);useQueryParams((p)=>{if(p.get("status"))setStatus(p.get("status")!);if(p.get("entry"))setOpen(p.get("entry"));});const entry=useLoad(()=>open?financeApi.get<JournalEntry>(role,`/journal/${open}`):Promise.resolve(null),[role,open]);
  const[composer,setComposer]=useState<null|"new"|"edit">(null);const action=useAction(async()=>{await list.reload();await entry.reload();});const[reverse,setReverse]=useState(false);const[reverseDate,setReverseDate]=useState(todayIso());
  return <div className="fx-stack"><Section eyebrow="LIBRO DIARIO" title={`${list.data?.total??0} asientos`} actions={<><select value={status} onChange={(e)=>{setStatus(e.target.value);setPage(1);}}><option value="">Todos</option>{["DRAFT","PENDING_REVIEW","POSTED","REVERSED"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select>{canFinance(role,"journal.create")?<button className="fx-btn primary" onClick={()=>setComposer("new")}><FilePlus2 size={14}/>Nuevo asiento</button>:null}</>}>
    {list.data?<Register rows={list.data.items} rowKey={(e)=>e.id} onRow={(e)=>setOpen(e.id)} selected={open} columns={[{key:"n",label:"N°",render:(e)=>e.entryNumber??<em>sin número</em>},{key:"d",label:"Fecha",render:(e)=>day(e.entryDate)},{key:"g",label:"Glosa",render:(e)=>e.description},{key:"o",label:"Origen",render:(e)=>label(e.sourceType)},{key:"t",label:"Total",align:"right",render:(e)=>e.totalDebit?<Amount value={e.totalDebit}/>:"—"},{key:"s",label:"Estado",render:(e)=><Pill value={e.status}/>}]} empty="Sin asientos"/>:list.error?<LoadError error={list.error} retry={()=>void list.reload()}/>:<Loading/>}
    {list.data&&list.data.totalPages>1?<div className="fx-pager"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page} de {list.data.totalPages}</span><button disabled={page>=list.data.totalPages} onClick={()=>setPage(page+1)}>Siguiente</button></div>:null}</Section>
    <Drawer open={Boolean(open)&&composer===null} title={entry.data?.entryNumber?`Asiento ${entry.data.entryNumber}`:"Asiento en borrador"} subtitle={entry.data?<><Pill value={entry.data.status}/> {label(entry.data.sourceType)}</>:undefined} onClose={()=>setOpen(null)} wide>{entry.data?<>
      <div className="fx-voucher"><header><span>{day(entry.data.entryDate)}</span><strong>{entry.data.description}</strong>{entry.data.reversalOfId?<Link href={`/finance/journal?entry=${entry.data.reversalOfId}`}>Revierte asiento original</Link>:null}{entry.data.reversedById?<Link href={`/finance/journal?entry=${entry.data.reversedById}`}>Ver reversa</Link>:null}</header>
        <table><thead><tr><th>Cuenta</th><th>Detalle</th><th>Dimensiones</th><th className="r">Debe</th><th className="r">Haber</th></tr></thead><tbody>{entry.data.lines?.map((l)=><tr key={l.id}><td><Link href={`/finance/general-ledger?accountId=${l.accountId}`}>{l.accountCode}</Link> {l.accountName}</td><td>{l.description}</td><td><small>{[l.clientId&&"cliente",l.projectId&&"proyecto",l.costCenterId&&"centro"].filter(Boolean).join(" · ")||"—"}</small></td><td className="r">{l.debit?money(l.debit):""}</td><td className="r">{l.credit?money(l.credit):""}</td></tr>)}</tbody>
        <tfoot><tr className="total"><td colSpan={3}>Totales</td><td className="r">{money(entry.data.lines?.reduce((t,l)=>t+l.debit,0))}</td><td className="r">{money(entry.data.lines?.reduce((t,l)=>t+l.credit,0))}</td></tr></tfoot></table>
        <footer><small>Creado {moment(entry.data.createdAt)}{entry.data.postedAt?` · contabilizado ${moment(entry.data.postedAt)}`:""}{entry.data.reversalReason?` · motivo: ${entry.data.reversalReason}`:""}</small></footer></div>
      <Feedback error={action.error} notice={action.notice}/>
      <div className="fx-actions">{["DRAFT","PENDING_REVIEW"].includes(entry.data.status)&&canFinance(role,"journal.create")?<button className="fx-btn ghost" onClick={()=>setComposer("edit")}>Editar</button>:null}{entry.data.status==="DRAFT"&&canFinance(role,"journal.create")?<><button className="fx-btn" onClick={()=>void action.run(()=>financeApi.post(role,`/journal/${open}/submit`),"Enviado a revisión.")}><Send size={14}/>Enviar a revisión</button><button className="fx-btn ghost" onClick={()=>void action.run(()=>financeApi.del(role,`/journal/${open}`),"Borrador descartado.").then(()=>setOpen(null))}><Trash2 size={14}/>Descartar</button></>:null}
        {["DRAFT","PENDING_REVIEW"].includes(entry.data.status)&&canFinance(role,"journal.post")?<button className="fx-btn primary" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.post(role,`/journal/${open}/post`),"Asiento contabilizado.")}><BookCheck size={14}/>Contabilizar</button>:null}
        {entry.data.status==="POSTED"&&canFinance(role,"journal.reverse")?<button className="fx-btn ghost" onClick={()=>setReverse(true)}><RotateCcw size={14}/>Revertir</button>:null}</div>
      {entry.data.status==="POSTED"?<p className="fx-hint">Un asiento contabilizado no se edita ni se borra: se corrige con una reversa y un nuevo asiento.</p>:null}</>:<Loading/>}</Drawer>
    {composer&&accounts.data?<EntryComposer accounts={accounts.data} centers={centers.data??[]} initial={composer==="edit"?entry.data:null} onClose={()=>setComposer(null)} onSaved={(id)=>{setComposer(null);setOpen(id);void list.reload();void entry.reload();}}/>:null}
    <ReasonDialog open={reverse} title="Revertir asiento" description="Se crea y contabiliza un asiento inverso; el original queda marcado como revertido." extra={<Field label="Fecha de la reversa"><DateInput value={reverseDate} onChange={setReverseDate}/></Field>} onCancel={()=>setReverse(false)} onConfirm={(reason)=>{setReverse(false);void action.run(()=>financeApi.post(role,`/journal/${open}/reverse`,{reason,date:reverseDate}),"Reversa contabilizada.");}}/>
  </div>;
}

export function GeneralLedger({tick}:ViewProps){
  const{role}=useAccess();const accounts=useAccounts(role);const[accountId,setAccountId]=useState("");useQueryParams((p)=>{if(p.get("accountId"))setAccountId(p.get("accountId")!);});const[from,setFrom]=useState(`${todayIso().slice(0,4)}-01-01`);const[to,setTo]=useState(todayIso());
  const ledger=useLoad(()=>accountId?financeApi.get<any>(role,`/general-ledger?accountId=${accountId}&from=${from}&to=${to}`):Promise.resolve(null),[role,accountId,from,to,tick]);const action=useAction();
  return <Section eyebrow="LIBRO MAYOR" title={ledger.data?`${ledger.data.account.code} · ${ledger.data.account.name}`:"Selecciona una cuenta"} description="Saldo inicial, movimientos contabilizados y saldo acumulado (Debe − Haber). Cada fila abre su asiento de origen." actions={<><AccountSelect accounts={accounts.data??[]} value={accountId} onChange={setAccountId} postingOnly={false}/><DateInput value={from} onChange={setFrom}/><DateInput value={to} onChange={setTo}/>{accountId&&canFinance(role,"report.finance.export")?<button className="fx-btn ghost" onClick={()=>void action.run(()=>financeApi.download(role,`/reports/LEDGER/export?format=xlsx&accountId=${accountId}&from=${from}&to=${to}`))}><Download size={14}/>XLSX</button>:null}</>}>
    <Feedback error={action.error}/>{!accountId?<Empty title="Elige una cuenta del plan"/>:ledger.data?<><div className="fx-chips"><span className="fx-chip">Saldo inicial <strong>{money(ledger.data.opening)}</strong></span><span className="fx-chip">Debe <strong>{money(ledger.data.debit)}</strong></span><span className="fx-chip">Haber <strong>{money(ledger.data.credit)}</strong></span><span className="fx-chip good">Saldo final <strong>{money(ledger.data.closing)}</strong></span></div>
      <Register rows={ledger.data.movements} rowKey={(m:any)=>`${m.entryId}-${m.lineDescription}-${m.balance}`} columns={[{key:"d",label:"Fecha",render:(m:any)=>day(m.entryDate)},{key:"n",label:"Asiento",render:(m:any)=><Link href={`/finance/journal?entry=${m.entryId}`}>{m.entryNumber}</Link>},{key:"g",label:"Glosa",render:(m:any)=>m.lineDescription||m.description},{key:"o",label:"Origen",render:(m:any)=>label(m.sourceType)},{key:"de",label:"Debe",align:"right",render:(m:any)=>m.debit?money(m.debit):""},{key:"h",label:"Haber",align:"right",render:(m:any)=>m.credit?money(m.credit):""},{key:"s",label:"Saldo",align:"right",render:(m:any)=><Amount value={m.balance} signed/>}]} totals={["","","Totales del período","",money(ledger.data.debit),money(ledger.data.credit),<Amount key="c" value={ledger.data.closing} strong signed/>]} empty="Sin movimientos en el rango"/></>:ledger.error?<LoadError error={ledger.error} retry={()=>void ledger.reload()}/>:<Loading/>}
  </Section>;
}

export function ChartOfAccounts({tick}:ViewProps){
  const{role}=useAccess();const[withBalances,setWithBalances]=useState(true);const accounts=useLoad(()=>financeApi.get<Array<LedgerAccount&{balance?:number}>>(role,`/accounts${withBalances?"?balances=true":""}`),[role,withBalances,tick]);const action=useAction(accounts.reload);const[form,setForm]=useState<any>(null);const manage=canFinance(role,"journal.review")||canFinance(role,"finance.settings.manage");
  const rows=useMemo(()=>[...(accounts.data??[])].sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true})),[accounts.data]);
  return <Section eyebrow="PLAN DE CUENTAS" title={`${rows.length} cuentas`} description="Plan base sugerido y editable. Las cuentas con subcuentas son agrupadoras (no imputables). No se cambia el tipo de una cuenta con movimientos." actions={<><label className="fx-check"><input type="checkbox" checked={withBalances} onChange={(e)=>setWithBalances(e.target.checked)}/>Saldos a hoy</label>{manage?<button className="fx-btn primary" onClick={()=>setForm({code:"",name:"",statementSection:"",isCash:false})}><Plus size={14}/>Cuenta</button>:null}</>}>
    <Feedback error={action.error} notice={action.notice}/>{accounts.data?<div className="fx-tree">{rows.map((a)=>{const level=a.code.split(".").length;return <div key={a.id} className={`lvl${Math.min(level,4)}${a.allowsPosting?"":" group"}${a.active?"":" inactive"}`}><code>{a.code}</code><span>{a.name}</span><small>{label(a.accountType)}{a.isCash?" · disponible":""}{a.allowsPosting?"":" · agrupadora"}</small>{withBalances&&a.allowsPosting?<Link href={`/finance/general-ledger?accountId=${a.id}`}><Amount value={a.balance??0} signed/></Link>:<i/>}{manage&&a.allowsPosting?<button className="fx-btn small ghost" onClick={()=>void action.run(()=>financeApi.patch(role,`/accounts/${a.id}`,{active:!a.active}),a.active?"Cuenta desactivada.":"Cuenta activada.")}>{a.active?"Desactivar":"Activar"}</button>:<i/>}</div>;})}</div>:accounts.error?<LoadError error={accounts.error} retry={()=>void accounts.reload()}/>:<Loading/>}
    <Drawer open={Boolean(form)} title="Nueva cuenta" subtitle="El tipo se hereda de la cuenta padre (código sin el último segmento)." onClose={()=>setForm(null)}>{form?<><div className="fx-form"><Field label="Código" hint="Ej. 5.2.05"><input value={form.code} onChange={(e)=>setForm({...form,code:e.target.value.replace(/[^\d.]/g,"")})}/></Field><Field label="Nombre" span={2}><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></Field><Field label="Sección de estados" span={2}><select value={form.statementSection} onChange={(e)=>setForm({...form,statementSection:e.target.value})}><option value="">Heredada</option>{["CURRENT_ASSET","NON_CURRENT_ASSET","CURRENT_LIABILITY","NON_CURRENT_LIABILITY","EQUITY","OPERATING_REVENUE","OTHER_REVENUE","COST_OF_SALES","OPERATING_EXPENSE","FINANCIAL_EXPENSE","OTHER_EXPENSE"].map((s)=><option key={s} value={s}>{s}</option>)}</select></Field><Field label="Cuenta de disponible"><input type="checkbox" checked={form.isCash} onChange={(e)=>setForm({...form,isCash:e.target.checked})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!form.code||!form.name} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/accounts",{...form,statementSection:form.statementSection||undefined}),"Cuenta creada.");if(r)setForm(null);}}>Crear</button></div></>:null}</Drawer>
  </Section>;
}

export function CostCenters({tick}:ViewProps){
  const{role}=useAccess();const list=useLoad(()=>financeApi.get<any[]>(role,"/cost-centers"),[role,tick]);const action=useAction(list.reload);const[form,setForm]=useState<any>(null);const manage=canFinance(role,"journal.review")||canFinance(role,"finance.settings.manage");
  return <Section eyebrow="DIMENSIONES" title="Centros de costo" actions={manage?<button className="fx-btn primary" onClick={()=>setForm({code:"",name:"",description:""})}><Plus size={14}/>Centro</button>:null}><Feedback error={action.error} notice={action.notice}/>
    {list.data?<Register rows={list.data} rowKey={(c)=>c.id} columns={[{key:"c",label:"Código",render:(c)=><code>{c.code}</code>},{key:"n",label:"Nombre",render:(c)=>c.name},{key:"d",label:"Descripción",render:(c)=>c.description??"—"},{key:"s",label:"Estado",render:(c)=><Pill value={c.active?"ACTIVE":"INACTIVE"}/>},{key:"x",label:"",render:(c)=>manage?<button className="fx-btn small ghost" onClick={()=>setForm({...c})}>Editar</button>:null}]}/>:<Loading/>}
    <Drawer open={Boolean(form)} title={form?.id?"Editar centro de costo":"Nuevo centro de costo"} onClose={()=>setForm(null)}>{form?<><div className="fx-form">{!form.id?<Field label="Código"><input value={form.code} onChange={(e)=>setForm({...form,code:e.target.value.toUpperCase()})}/></Field>:null}<Field label="Nombre" span={2}><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></Field><Field label="Descripción" span={3}><input value={form.description??""} onChange={(e)=>setForm({...form,description:e.target.value})}/></Field>{form.id?<Field label="Activo"><input type="checkbox" checked={form.active} onChange={(e)=>setForm({...form,active:e.target.checked})}/></Field>:null}</div><div className="fx-actions end"><button className="fx-btn primary" onClick={async()=>{const r=await action.run(()=>form.id?financeApi.patch(role,`/cost-centers/${form.id}`,form):financeApi.post(role,"/cost-centers",form),"Centro guardado.");if(r)setForm(null);}}>Guardar</button></div></>:null}</Drawer></Section>;
}

export function Budgets({tick}:ViewProps){
  const{role}=useAccess();const list=useLoad(()=>financeApi.get<Budget[]>(role,"/budgets"),[role,tick]);const[open,setOpen]=useState<string|null>(null);const detail=useLoad(()=>open?financeApi.get<Budget>(role,`/budgets/${open}`):Promise.resolve(null),[role,open]);const vs=useLoad(()=>open?financeApi.get<any>(role,`/budgets/${open}/vs-actual`).catch(()=>null):Promise.resolve(null),[role,open,tick]);
  const accounts=useAccounts(role);const action=useAction(async()=>{await list.reload();await detail.reload();await vs.reload();});const manage=canFinance(role,"finance.settings.manage");const[form,setForm]=useState<any>(null);const[lines,setLines]=useState<Array<{accountId:string;periodKey:string;amount:string}>|null>(null);
  const pnl=(accounts.data??[]).filter((a)=>a.allowsPosting&&["REVENUE","EXPENSE"].includes(a.accountType));
  return <div className="fx-two"><Section eyebrow="PRESUPUESTOS" title={`${list.data?.length??0} presupuestos`} actions={manage?<button className="fx-btn primary" onClick={()=>setForm({name:"",fiscalYear:todayIso().slice(0,4),scopeType:"COMPANY"})}><Plus size={14}/>Presupuesto</button>:null}>
    {list.data?<Register rows={list.data} rowKey={(b)=>b.id} onRow={(b)=>{setOpen(b.id);setLines(null);}} selected={open} columns={[{key:"n",label:"Nombre",render:(b)=>b.name},{key:"y",label:"Año",render:(b)=>b.fiscalYear},{key:"s",label:"Alcance",render:(b)=>label(b.scopeType)},{key:"st",label:"Estado",render:(b)=><Pill value={b.status}/>}]} empty="Sin presupuestos"/>:<Loading/>}</Section>
    <Section eyebrow="PRESUPUESTO VS REAL" title={detail.data?.name??"Selecciona un presupuesto"} description="El real proviene sólo de asientos contabilizados (con las dimensiones del presupuesto)." actions={detail.data&&manage&&detail.data.status==="DRAFT"?<><button className="fx-btn ghost" onClick={()=>setLines(detail.data!.lines?.map((l)=>({accountId:l.accountId,periodKey:l.periodKey,amount:String(l.amount)}))??[])}>Editar líneas</button><button className="fx-btn primary" onClick={()=>void action.run(()=>financeApi.post(role,`/budgets/${open}/approve`),"Presupuesto aprobado.")}>Aprobar</button></>:null}>
      <Feedback error={action.error} notice={action.notice}/>
      {lines?<div className="fx-lines"><table><thead><tr><th>Cuenta</th><th>Mes</th><th className="r">Monto</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={i}><td><AccountSelect accounts={pnl} value={l.accountId} onChange={(id)=>setLines(lines.map((x,n)=>n===i?{...x,accountId:id}:x))}/></td><td><input type="month" value={l.periodKey} onChange={(e)=>setLines(lines.map((x,n)=>n===i?{...x,periodKey:e.target.value}:x))}/></td><td><input inputMode="numeric" value={l.amount} onChange={(e)=>setLines(lines.map((x,n)=>n===i?{...x,amount:e.target.value.replace(/\D/g,"")}:x))}/></td><td><button className="fx-icon" onClick={()=>setLines(lines.filter((_,n)=>n!==i))}>×</button></td></tr>)}</tbody></table><div className="fx-actions"><button className="fx-btn ghost small" onClick={()=>setLines([...lines,{accountId:"",periodKey:monthKey(),amount:""}])}><Plus size={12}/>Línea</button><button className="fx-btn primary" onClick={async()=>{const r=await action.run(()=>financeApi.put(role,`/budgets/${open}/lines`,{lines:lines.filter((l)=>l.accountId&&l.amount).map((l)=>({...l,amount:Number(l.amount)}))}),"Líneas guardadas.");if(r)setLines(null);}}>Guardar líneas</button></div></div>
      :vs.data?<Register rows={vs.data.rows} rowKey={(r:any)=>`${r.accountId}-${r.periodKey}`} columns={[{key:"c",label:"Cuenta",render:(r:any)=><>{r.accountCode} {r.accountName}</>},{key:"m",label:"Mes",render:(r:any)=>period(r.periodKey)},{key:"b",label:"Presupuesto",align:"right",render:(r:any)=><Amount value={r.budget}/>},{key:"a",label:"Real",align:"right",render:(r:any)=><Amount value={r.actual}/>},{key:"v",label:"Variación",align:"right",render:(r:any)=><span className={r.variance>0?"bad":"good"}><Amount value={r.variance} signed/>{r.variancePercent!==null?<small className="block">{r.variancePercent}%</small>:null}</span>}]} totals={["Totales","",money(vs.data.totals.budget),money(vs.data.totals.actual),money(vs.data.totals.variance)]} empty="El presupuesto no tiene líneas"/>:open?<Loading/>:<Empty title="Selecciona un presupuesto"/>}
    </Section>
    <Drawer open={Boolean(form)} title="Nuevo presupuesto" onClose={()=>setForm(null)}>{form?<><div className="fx-form"><Field label="Nombre" span={2}><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></Field><Field label="Año fiscal"><input inputMode="numeric" value={form.fiscalYear} onChange={(e)=>setForm({...form,fiscalYear:e.target.value.replace(/\D/g,"").slice(0,4)})}/></Field><Field label="Alcance"><select value={form.scopeType} onChange={(e)=>setForm({...form,scopeType:e.target.value})}>{["COMPANY","DEPARTMENT","COST_CENTER","PROJECT"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select></Field></div><div className="fx-actions end"><button className="fx-btn primary" disabled={!form.name} onClick={async()=>{const r=await action.run<Budget>(()=>financeApi.post(role,"/budgets",{...form,fiscalYear:Number(form.fiscalYear)}),"Presupuesto creado.");if(r){setForm(null);setOpen(r.id);}}}>Crear</button></div></>:null}</Drawer>
  </div>;
}
