"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { CloseRun, CommissionFinanceView, F29Preparation, TaxObligation, VatSummary } from "@zyteron/contracts";
import { ArrowUpRight, BadgeCheck, Download, FileCheck2, Lock, Plus, ShieldCheck } from "lucide-react";
import { useAccess } from "@/components/access-context";
import { financeApi, type UploadedFile } from "@/lib/finance-api";
import { canFinance, day, label, moment, money, period, todayIso } from "@/lib/finance-format";
import { Amount, DateInput, Drawer, Empty, Feedback, Field, FileInput, KeyValue, LoadError, Loading, Pill, Register, Section, Stamp, useAction, useLoad, useQueryParams } from "./fx-ui";
import { FlowChart } from "./views-command";
import { AccountSelect } from "./views-ledger";
import type { ViewProps } from "./finance-workspace";

export function Taxes({periodKey,tick}:ViewProps){
  const{role}=useAccess();const vat=useLoad(()=>financeApi.get<VatSummary>(role,`/tax/vat?period=${periodKey}`),[role,periodKey,tick]);const f29=useLoad(()=>financeApi.get<(F29Preparation&{disclaimer:string})|null>(role,`/tax/f29/${periodKey}`),[role,periodKey,tick]);const obligations=useLoad(()=>financeApi.get<TaxObligation[]>(role,"/tax/obligations"),[role,tick]);const rules=useLoad(()=>financeApi.get<any[]>(role,"/tax/rules"),[role,tick]);
  const action=useAction(async()=>{await vat.reload();await f29.reload();await obligations.reload();await rules.reload();});const[file,setFile]=useState<{action:"file"|"accept";reference:string;evidence:UploadedFile|null}|null>(null);const[obligation,setObligation]=useState<any>(null);const[obligationUpdate,setObligationUpdate]=useState<any>(null);const[version,setVersion]=useState<any>(null);
  const v=vat.data;const p=f29.data;
  return <div className="fx-stack"><div className="fx-two"><Section className="fx-vat" eyebrow={`IVA ${period(periodKey)}`} title={v?money(v.estimatedPayable):"—"} description="IVA estimado a pagar del período" actions={<Stamp kind="warn">ESTIMACIÓN INTERNA</Stamp>}>
      {v?<><table className="fx-statement"><tbody><tr><td>Débito fiscal (facturas)</td><td className="r">{money(v.debit)}</td></tr><tr><td>+ Débito notas de débito</td><td className="r">{money(v.debitNotesDebit)}</td></tr><tr><td>− IVA notas de crédito</td><td className="r">{money(v.creditNotesDebit)}</td></tr><tr className="sub"><td>Débito neto</td><td className="r">{money(v.netDebit)}</td></tr><tr><td>Crédito potencial de compras</td><td className="r">{money(v.creditPotential)}</td></tr><tr><td>− Crédito clasificado recuperable</td><td className="r">{money(v.creditEligible)}</td></tr><tr className="muted"><td>Pendiente de clasificar (no se incluye)</td><td className="r">{money(v.creditPendingReview)}</td></tr><tr className="muted"><td>IVA no recuperable</td><td className="r">{money(v.creditNonRecoverable)}</td></tr><tr><td>− Remanente período anterior</td><td className="r">{money(v.adjustments)}</td></tr><tr className="total"><td>IVA estimado a pagar</td><td className="r">{money(v.estimatedPayable)}</td></tr><tr><td>Remanente estimado</td><td className="r">{money(v.remainder)}</td></tr></tbody></table>
        <div className="fx-sources">{v.sources.map((s)=><Link key={s.label} href={s.href}>{s.label} ({s.count}) · {money(s.amount)}<ArrowUpRight size={12}/></Link>)}</div></>:vat.error?<LoadError error={vat.error} retry={()=>void vat.reload()}/>:<Loading/>}
    </Section>
    <Section eyebrow="PREPARACIÓN F29" title={p?label(p.status):"Sin preparar"} description={p?.disclaimer??"Prepara las líneas desde documentos registrados. Nunca se marca presentado sin evidencia de sii.cl."} actions={canFinance(role,"tax.review")&&(!p||["PREPARATION","REVIEW_REQUIRED"].includes(p.status))?<button className="fx-btn" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.post(role,`/tax/f29/${periodKey}/prepare`),"Preparación recalculada.")}>{p?"Recalcular":"Preparar"}</button>:null}>
      <Feedback error={action.error} notice={action.notice}/>
      {p?<><table className="fx-statement f29"><tbody>{p.lines.map((l)=><tr key={l.key}><td><Link href={l.drillDown}>{l.label}</Link><small className="block">{l.source}{l.officialCode?` · código ${l.officialCode}`:" · código oficial: mapear con formulario vigente"}</small></td><td className="r">{money(l.amount)}</td></tr>)}<tr className="total"><td>Total estimado (IVA + PPM)</td><td className="r">{money(p.totals.totalEstimated)}</td></tr></tbody></table>
        <ol className="fx-stepper">{["PREPARATION","REVIEWED","READY","FILED_EXTERNALLY","ACCEPTED"].map((s,i,all)=><li key={s} className={all.indexOf(p.status==="REVIEW_REQUIRED"?"PREPARATION":p.status)>=i?"done":""}>{label(s)}</li>)}</ol>
        <div className="fx-actions">{p.status==="PREPARATION"&&canFinance(role,"tax.review")?<button className="fx-btn primary" onClick={()=>void action.run(()=>financeApi.post(role,`/tax/f29/${periodKey}/review`,{}),"Marcado como revisado.")}>Marcar revisado</button>:null}{p.status==="REVIEWED"&&canFinance(role,"tax.manage")?<button className="fx-btn primary" onClick={()=>void action.run(()=>financeApi.post(role,`/tax/f29/${periodKey}/ready`,{}),"Listo para presentar.")}>Listo para presentar</button>:null}{p.status==="READY"&&canFinance(role,"tax.manage")?<button className="fx-btn primary" onClick={()=>setFile({action:"file",reference:"",evidence:null})}><FileCheck2 size={14}/>Registrar presentación</button>:null}{["FILED_EXTERNALLY","SUBMITTED"].includes(p.status)&&canFinance(role,"tax.manage")?<button className="fx-btn" onClick={()=>setFile({action:"accept",reference:"",evidence:null})}>Registrar aceptación</button>:null}</div>
        {p.status==="REVIEW_REQUIRED"?<p className="fx-hint">Requiere revisión: clasifica el IVA de compras pendiente o configura la tasa PPM informada por el SII, y recalcula.</p>:null}</>:<Empty title="Sin preparación F29 para el período"/>}
    </Section></div>
    <Section eyebrow="CALENDARIO TRIBUTARIO" title="Obligaciones" description="Sin vencimientos legales supuestos: cada obligación registra su fuente. Presentada/pagada exige evidencia." actions={canFinance(role,"tax.manage")?<button className="fx-btn primary" onClick={()=>setObligation({code:"F29",name:"Declaración mensual F29",taxType:"VAT",periodKey,dueDate:"",sourceReference:""})}><Plus size={14}/>Obligación</button>:null}>
      {obligations.data?<Register rows={obligations.data} rowKey={(o)=>o.id} columns={[{key:"n",label:"Obligación",render:(o)=><><strong>{o.name}</strong><small className="block">{o.code} · {period(o.periodKey)}</small></>},{key:"d",label:"Vence",render:(o)=><>{day(o.dueDate)}<small className={`block ${o.daysToDue<0&&!["FILED_EXTERNALLY","PAID","NOT_APPLICABLE"].includes(o.status)?"bad":""}`}>{o.daysToDue>=0?`en ${o.daysToDue} días`:`hace ${-o.daysToDue} días`}</small></>},{key:"f",label:"Fuente",render:(o)=><small>{o.sourceReference}</small>},{key:"s",label:"Estado",render:(o)=><Pill value={o.status}/>},{key:"x",label:"",render:(o)=>canFinance(role,"tax.manage")&&!["PAID","NOT_APPLICABLE"].includes(o.status)?<button className="fx-btn small ghost" onClick={()=>setObligationUpdate({id:o.id,status:"FILED_EXTERNALLY",filedReference:"",notes:"",evidence:null})}>Actualizar</button>:null}]} empty="Sin obligaciones registradas"/>:<Loading/>}
    </Section>
    <Section eyebrow="REGLAS TRIBUTARIAS VERSIONADAS" title="Tasas vigentes" description="Las tasas no están en el código: cada versión tiene vigencia y fuente legal o del SII. Las vigencias activas no se superponen.">
      {rules.data?<div className="fx-rules">{rules.data.map((r)=><article key={r.id} className={r.versions.some((x:any)=>x.active)?"on":""}><header><div><strong>{r.name}</strong><small>{r.code} · {r.description}</small></div>{canFinance(role,"tax.manage")?<button className="fx-btn small" onClick={()=>setVersion({ruleId:r.id,name:r.name,rate:"",effectiveFrom:todayIso(),effectiveTo:"",sourceReference:""})}>Nueva versión</button>:null}</header><table><tbody>{r.versions.map((x:any)=><tr key={x.id}><td>{(Number(x.rate)*100).toFixed(4).replace(/\.?0+$/,"")}%</td><td>{day(x.effectiveFrom)} → {x.effectiveTo?day(x.effectiveTo):"vigente"}</td><td><small>{x.sourceReference}</small></td><td><Pill value={x.active?"ACTIVE":"INACTIVE"}/></td></tr>)}{!r.versions.length?<tr><td colSpan={4} className="muted">Sin tasa configurada.</td></tr>:null}</tbody></table></article>)}</div>:<Loading/>}
    </Section>
    <Drawer open={Boolean(file)} title={file?.action==="file"?"Registrar presentación del F29":"Registrar aceptación"} subtitle="Adjunta el comprobante descargado de sii.cl." onClose={()=>setFile(null)}>{file?<><div className="fx-form">{file.action==="file"?<Field label="Folio / N° de declaración" span={3}><input value={file.reference} onChange={(e)=>setFile({...file,reference:e.target.value})}/></Field>:null}<Field label="Evidencia" span={3}><FileInput accept=".pdf,.png,.jpg" file={file.evidence} onFile={(f)=>setFile({...file,evidence:f})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!file.evidence||(file.action==="file"&&!file.reference)} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/tax/f29/${periodKey}/${file.action}`,{filedReference:file.reference,evidence:file.evidence}),"Registrado con evidencia.");if(r)setFile(null);}}>Registrar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(obligation)} title="Nueva obligación tributaria" onClose={()=>setObligation(null)}>{obligation?<><div className="fx-form"><Field label="Código"><input value={obligation.code} onChange={(e)=>setObligation({...obligation,code:e.target.value})}/></Field><Field label="Nombre" span={2}><input value={obligation.name} onChange={(e)=>setObligation({...obligation,name:e.target.value})}/></Field><Field label="Tipo"><input value={obligation.taxType} onChange={(e)=>setObligation({...obligation,taxType:e.target.value})}/></Field><Field label="Período"><input type="month" value={obligation.periodKey} onChange={(e)=>setObligation({...obligation,periodKey:e.target.value})}/></Field><Field label="Vencimiento"><DateInput value={obligation.dueDate} onChange={(v)=>setObligation({...obligation,dueDate:v})}/></Field><Field label="Fuente del vencimiento" span={3} hint="Ej. calendario tributario SII publicado para el período"><input value={obligation.sourceReference} onChange={(e)=>setObligation({...obligation,sourceReference:e.target.value})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!obligation.dueDate||!obligation.sourceReference} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/tax/obligations",obligation),"Obligación registrada.");if(r)setObligation(null);}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(obligationUpdate)} title="Actualizar obligación" onClose={()=>setObligationUpdate(null)}>{obligationUpdate?<><div className="fx-form"><Field label="Estado" span={3}><select value={obligationUpdate.status} onChange={(e)=>setObligationUpdate({...obligationUpdate,status:e.target.value})}>{["IN_PREPARATION","READY","FILED_EXTERNALLY","PAID","NOT_APPLICABLE"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select></Field>{["FILED_EXTERNALLY","PAID"].includes(obligationUpdate.status)?<><Field label="Referencia" span={3}><input value={obligationUpdate.filedReference} onChange={(e)=>setObligationUpdate({...obligationUpdate,filedReference:e.target.value})}/></Field><Field label="Evidencia" span={3}><FileInput file={obligationUpdate.evidence} onFile={(f)=>setObligationUpdate({...obligationUpdate,evidence:f})}/></Field></>:null}<Field label="Notas" span={3}><textarea rows={2} value={obligationUpdate.notes} onChange={(e)=>setObligationUpdate({...obligationUpdate,notes:e.target.value})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" onClick={async()=>{const r=await action.run(()=>financeApi.patch(role,`/tax/obligations/${obligationUpdate.id}`,obligationUpdate),"Obligación actualizada.");if(r)setObligationUpdate(null);}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(version)} title={`Nueva versión · ${version?.name??""}`} subtitle="La tasa se expresa en porcentaje y requiere fuente." onClose={()=>setVersion(null)}>{version?<><div className="fx-form"><Field label="Tasa (%)"><input inputMode="decimal" value={version.rate} onChange={(e)=>setVersion({...version,rate:e.target.value.replace(/[^\d.,]/g,"")})}/></Field><Field label="Vigente desde"><DateInput value={version.effectiveFrom} onChange={(v)=>setVersion({...version,effectiveFrom:v})}/></Field><Field label="Hasta (opcional)"><DateInput value={version.effectiveTo} onChange={(v)=>setVersion({...version,effectiveTo:v})}/></Field><Field label="Fuente legal / SII" span={3}><input value={version.sourceReference} onChange={(e)=>setVersion({...version,sourceReference:e.target.value})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!version.rate||!version.sourceReference} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/tax/rules/${version.ruleId}/versions`,{rate:Number(String(version.rate).replace(",","."))/100,effectiveFrom:version.effectiveFrom,effectiveTo:version.effectiveTo||undefined,sourceReference:version.sourceReference}),"Versión creada.");if(r)setVersion(null);}}>Crear versión</button></div></>:null}</Drawer>
  </div>;
}

export function Commissions({tick}:ViewProps){
  const{role}=useAccess();const rows=useLoad(()=>financeApi.get<CommissionFinanceView[]>(role,"/commissions"),[role,tick]);const policies=useLoad(()=>financeApi.get<any[]>(role,"/commissions/policies"),[role,tick]);const action=useAction(async()=>{await rows.reload();await policies.reload();});const[policy,setPolicy]=useState<any>(null);const[pay,setPay]=useState<any>(null);
  return <div className="fx-stack"><Section eyebrow="COMISIONES" title="Elegibilidad financiera" description="Comercial calcula la comisión; Finanzas determina si es pagable según cobro real y la paga con respaldo y asiento." actions={<button className="fx-btn ghost" onClick={()=>setPolicy({name:"",triggerType:"INVOICE_PAID",collectedPercent:""})}><Plus size={14}/>Política</button>}>
    <Feedback error={action.error} notice={action.notice}/>{rows.data?<Register rows={rows.data} rowKey={(r)=>r.commissionId} columns={[{key:"v",label:"Vendedor",render:(r)=><code>{r.userId.slice(0,8)}</code>},{key:"s",label:"Venta",render:(r)=><small>{r.saleId.slice(0,8)} · {label(r.commercialStatus)}</small>},{key:"f",label:"Facturado / cobrado",align:"right",render:(r)=><>{money(r.invoicedAmount)}<small className="block">{money(r.collectedAmount)}{r.collectedPercent!==null?` (${r.collectedPercent}%)`:""}</small></>},{key:"a",label:"Comisión",align:"right",render:(r)=><Amount value={r.amount} strong/>},{key:"st",label:"Estado financiero",render:(r)=><><Pill value={r.financeStatus}/><small className="block">{r.reason}</small></>},{key:"x",label:"",render:(r)=>r.financeStatus==="ELIGIBLE"?<button className="fx-btn small primary" onClick={()=>void action.run(()=>financeApi.post(role,`/commissions/${r.commissionId}/approve`),"Comisión aprobada para pago.")}><BadgeCheck size={12}/>Aprobar</button>:r.financeStatus==="PAYABLE"?<button className="fx-btn small" onClick={()=>setPay({id:r.commissionId,paymentReference:"",paidAt:todayIso(),evidence:null})}>Registrar pago</button>:null}]} empty="Sin comisiones comerciales"/>:rows.error?<LoadError error={rows.error} retry={()=>void rows.reload()}/>:<Loading/>}</Section>
    <Section eyebrow="POLÍTICAS" title="Reglas de elegibilidad">{policies.data?<Register rows={policies.data} rowKey={(p:any)=>p.id} columns={[{key:"n",label:"Nombre",render:(p:any)=>p.name},{key:"t",label:"Disparador",render:(p:any)=>p.triggerType==="COLLECTED_PERCENT"?`Cobrado ≥ ${p.collectedPercent}%`:p.triggerType==="INVOICE_PAID"?"Venta facturada y pagada":"Fin del período de la venta"},{key:"u",label:"Aplica a",render:(p:any)=>p.userId?<code>{p.userId.slice(0,8)}</code>:"Todos"},{key:"s",label:"Estado",render:(p:any)=><Pill value={p.active?"ACTIVE":"INACTIVE"}/>}]} empty="Sin políticas: ninguna comisión es elegible hasta configurarlas"/>:<Loading/>}</Section>
    <Drawer open={Boolean(policy)} title="Política de comisiones" onClose={()=>setPolicy(null)}>{policy?<><div className="fx-form"><Field label="Nombre" span={3}><input value={policy.name} onChange={(e)=>setPolicy({...policy,name:e.target.value})}/></Field><Field label="Disparador" span={2}><select value={policy.triggerType} onChange={(e)=>setPolicy({...policy,triggerType:e.target.value})}><option value="INVOICE_PAID">Facturada y pagada</option><option value="COLLECTED_PERCENT">Porcentaje cobrado</option><option value="PERIOD_END">Fin del período</option></select></Field>{policy.triggerType==="COLLECTED_PERCENT"?<Field label="% cobrado"><input inputMode="numeric" value={policy.collectedPercent} onChange={(e)=>setPolicy({...policy,collectedPercent:e.target.value.replace(/\D/g,"")})}/></Field>:null}</div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!policy.name} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/commissions/policies",{...policy,collectedPercent:policy.collectedPercent?Number(policy.collectedPercent):undefined}),"Política guardada.");if(r)setPolicy(null);}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(pay)} title="Registrar pago de comisión" onClose={()=>setPay(null)}>{pay?<><div className="fx-form"><Field label="Referencia" span={2}><input value={pay.paymentReference} onChange={(e)=>setPay({...pay,paymentReference:e.target.value})}/></Field><Field label="Fecha"><DateInput value={pay.paidAt} onChange={(v)=>setPay({...pay,paidAt:v})}/></Field><Field label="Comprobante" span={3}><FileInput file={pay.evidence} onFile={(f)=>setPay({...pay,evidence:f})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!pay.paymentReference||!pay.evidence} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/commissions/${pay.id}/pay`,pay),"Pago registrado.");if(r)setPay(null);}}>Registrar</button></div></>:null}</Drawer></div>;
}

export function Closing({periodKey:workspacePeriod,tick}:ViewProps){
  const{role}=useAccess();const[periodKey,setPeriodKey]=useState(workspacePeriod);useEffect(()=>{const fromQuery=new URLSearchParams(window.location.search).get("period");setPeriodKey(fromQuery??workspacePeriod);},[workspacePeriod]);
  const run=useLoad(()=>financeApi.get<CloseRun>(role,`/close/${periodKey}`),[role,periodKey,tick]);const action=useAction(run.reload);const[task,setTask]=useState<any>(null);const[snapshot,setSnapshot]=useState<any>(null);
  if(run.error)return <LoadError error={run.error} retry={()=>void run.reload()}/>;if(!run.data)return <Loading/>;const r=run.data;const closed=["CLOSED","LOCKED"].includes(r.period.status);
  return <div className="fx-stack"><Section eyebrow={`CIERRE ${period(periodKey)}`} title={closed?`Período ${label(r.period.status).toLowerCase()}`:r.blockers.length?`${r.blockers.length} bloqueos`:"Listo para cerrar"} description="Controles automáticos con datos reales; los manuales exigen evidencia o nota. Al cerrar se guarda un snapshot inmutable con SHA-256." actions={<><input type="month" value={periodKey} onChange={(e)=>setPeriodKey(e.target.value)}/>{!closed&&canFinance(role,"period.close")?<button className="fx-btn primary" disabled={r.blockers.length>0||action.busy} title={r.blockers.join("\n")} onClick={()=>void action.run(()=>financeApi.post(role,`/close/${periodKey}/close`),"Período cerrado con snapshot inmutable.")}><Lock size={14}/>Cerrar período</button>:null}{closed?<Link className="fx-btn ghost" href="/finance/accounting?tab=periods">Reapertura</Link>:null}</>}>
    <Feedback error={action.error} notice={action.notice}/>
    <ol className="fx-close">{r.tasks.map((t)=><li key={t.id} className={t.status.toLowerCase()}><span className="mark">{t.status==="OK"?"✓":t.status==="BLOCKED"?"✗":t.status==="WAIVED"?"≈":t.status==="NOT_APPLICABLE"?"–":"○"}</span><div><strong>{t.label}</strong><small>{t.checkType==="AUTO"?"Automático":"Manual"}{t.blocking?" · bloqueante":""}{(t.result as any)?.detail?` · ${(t.result as any).detail}`:""}{t.notes?` · ${t.notes}`:""}</small></div><Pill value={t.status}/>{(t.result as any)?.drillDown?<Link className="fx-link" href={(t.result as any).drillDown}>Ver<ArrowUpRight size={12}/></Link>:<i/>}{!closed&&canFinance(role,"period.close")?<button className="fx-btn small ghost" onClick={()=>setTask({id:t.id,label:t.label,checkType:t.checkType,blocking:t.blocking,status:t.checkType==="AUTO"?"WAIVED":"OK",notes:"",evidence:null})}>Registrar</button>:<i/>}</li>)}</ol></Section>
    <Section eyebrow="SNAPSHOTS" title="Versiones de cierre">{r.snapshots.length?<Register rows={r.snapshots} rowKey={(s)=>s.id} columns={[{key:"v",label:"Versión",render:(s)=>`v${s.version}`},{key:"d",label:"Fecha",render:(s)=>moment(s.createdAt)},{key:"h",label:"SHA-256",render:(s)=><code>{s.sha256.slice(0,20)}…</code>},{key:"x",label:"",render:(s)=><button className="fx-btn small ghost" onClick={async()=>{const data=await action.run(()=>financeApi.get<any>(role,`/close/${periodKey}/snapshot?version=${s.version}`));if(data)setSnapshot(data);}}><ShieldCheck size={12}/>Verificar</button>}]}/>:<Empty title="Sin snapshots" text="Se generan al cerrar el período."/>}</Section>
    <Drawer open={Boolean(task)} title={task?.label??""} subtitle={task?.checkType==="AUTO"?"Un control automático sólo pasa a OK cuando el dato cumple; dispensarlo exige justificación (y Gerencia si es bloqueante).":"Registra la revisión con evidencia o nota."} onClose={()=>setTask(null)}>{task?<><div className="fx-form"><Field label="Resultado" span={3}><select value={task.status} onChange={(e)=>setTask({...task,status:e.target.value})}>{(task.checkType==="AUTO"?["WAIVED","NOT_APPLICABLE","PENDING"]:["OK","WAIVED","NOT_APPLICABLE","PENDING"]).map((s)=><option key={s} value={s}>{label(s)}</option>)}</select></Field><Field label="Nota / justificación" span={3}><textarea rows={3} value={task.notes} onChange={(e)=>setTask({...task,notes:e.target.value})}/></Field><Field label="Evidencia" span={3}><FileInput file={task.evidence} onFile={(f)=>setTask({...task,evidence:f})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" onClick={async()=>{const ok=await action.run(()=>financeApi.patch(role,`/close-tasks/${task.id}`,{status:task.status,notes:task.notes||undefined,evidence:task.evidence??undefined}),"Tarea actualizada.");if(ok)setTask(null);}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(snapshot)} title={`Snapshot v${snapshot?.version??""}`} subtitle={snapshot?<Pill value={snapshot.integrity==="VERIFIED"?"OK":"ERROR"} text={snapshot.integrity==="VERIFIED"?"Integridad verificada (SHA-256 coincide)":"El hash no coincide"}/>:undefined} onClose={()=>setSnapshot(null)} wide>{snapshot?<KeyValue items={[["Ingresos",money(snapshot.incomeStatement?.revenue)],["Resultado",money(snapshot.incomeStatement?.netResult)],["Total activos",money(snapshot.balanceSheet?.totalAssets)],["Total pasivos + patrimonio",money((snapshot.balanceSheet?.totalLiabilities??0)+(snapshot.balanceSheet?.totalEquity??0))],["Comprobación",snapshot.trialBalance?.balanced?"Cuadrada":"Descuadrada"],["SHA-256",snapshot.sha256]]}/>:null}</Drawer>
  </div>;
}

const reportList:Array<[string,string,string]>=[["INCOME_STATEMENT","Estado de Resultados","accounting.view"],["BALANCE_SHEET","Balance General","accounting.view"],["TRIAL_BALANCE","Balance de Comprobación","accounting.view"],["JOURNAL","Libro Diario","accounting.view"],["LEDGER","Libro Mayor","accounting.view"],["CASHFLOW","Flujo de Caja","accounting.view"],["AR_AGING","Aging cuentas por cobrar","receivable.view"],["AP_AGING","Aging cuentas por pagar","payable.view"],["SALES","Ventas","invoice.view"],["PURCHASES","Compras","expense.view"],["VAT","IVA","tax.view"],["PROFITABILITY_CLIENT","Rentabilidad por cliente","accounting.view"],["PROFITABILITY_PROJECT","Rentabilidad por proyecto","accounting.view"],["BUDGET_VS_ACTUAL","Presupuesto vs Real","accounting.view"]];
export function Reports({periodKey,tick}:ViewProps){
  const{role}=useAccess();const available=reportList.filter(([,, p])=>canFinance(role,"report.finance.view")&&canFinance(role,p as any));const[type,setType]=useState(available[0]?.[0]??"");
  const[from,setFrom]=useState(`${periodKey}-01`);const[to,setTo]=useState(todayIso());useQueryParams((p)=>{const t=p.get("type");if(t&&available.some(([k])=>k===t))setType(t);if(p.get("from"))setFrom(p.get("from")!);if(p.get("to"))setTo(p.get("to")!);});const[extra,setExtra]=useState<Record<string,string>>({scenario:"BASE"});
  const accounts=useLoad(()=>type==="LEDGER"?financeApi.get<any[]>(role,"/accounts"):Promise.resolve([]),[role,type]);const budgets=useLoad(()=>type==="BUDGET_VS_ACTUAL"?financeApi.get<any[]>(role,"/budgets"):Promise.resolve([]),[role,type]);
  const query=`from=${from}&to=${to}&period=${from.slice(0,7)}${Object.entries(extra).filter(([,v])=>v).map(([k,v])=>`&${k}=${encodeURIComponent(v)}`).join("")}`;const ready=type&&(type!=="LEDGER"||extra.accountId)&&(type!=="BUDGET_VS_ACTUAL"||extra.budgetId);
  const report=useLoad(()=>ready?financeApi.get<any>(role,`/reports/${type}?${query}`):Promise.resolve(null),[role,type,query,tick]);const cash=useLoad(()=>type==="CASHFLOW"?financeApi.get<any>(role,`/cashflow?scenario=${extra.scenario||"BASE"}`):Promise.resolve(null),[role,type,extra.scenario]);const action=useAction();
  if(!available.length)return <Empty title="Sin informes disponibles para tu rol"/>;
  return <div className="fx-reports"><nav className="fx-report-list" aria-label="Informes">{available.map(([key,name])=><button key={key} className={type===key?"active":""} onClick={()=>setType(key)}>{name}</button>)}</nav>
    <Section eyebrow="INFORME" title={report.data?.title??reportList.find(([k])=>k===type)?.[1]??""} description={report.data?`${report.data.period} · Fuente: ${report.data.source}`:undefined} actions={<>{!["BALANCE_SHEET","AR_AGING","AP_AGING","CASHFLOW","BUDGET_VS_ACTUAL"].includes(type)?<><DateInput value={from} onChange={setFrom}/><DateInput value={to} onChange={setTo}/></>:["BALANCE_SHEET","AR_AGING","AP_AGING"].includes(type)?<DateInput value={to} onChange={setTo}/>:null}{type==="LEDGER"?<AccountSelect accounts={accounts.data??[]} value={extra.accountId??""} onChange={(id)=>setExtra({...extra,accountId:id})} postingOnly={false}/>:null}{type==="BUDGET_VS_ACTUAL"?<select value={extra.budgetId??""} onChange={(e)=>setExtra({...extra,budgetId:e.target.value})}><option value="">Presupuesto…</option>{budgets.data?.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select>:null}{type==="CASHFLOW"?<select value={extra.scenario} onChange={(e)=>setExtra({...extra,scenario:e.target.value})}><option value="BASE">Base</option><option value="CONSERVATIVE">Conservador</option><option value="OPTIMISTIC">Optimista</option></select>:null}{ready&&canFinance(role,"report.finance.export")?["csv","xlsx","pdf"].map((f)=><button key={f} className="fx-btn ghost small" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.download(role,`/reports/${type}/export?format=${f}&${query}`),`Exportación ${f.toUpperCase()} registrada en auditoría.`)}><Download size={12}/>{f.toUpperCase()}</button>):null}</>}>
      <Feedback error={action.error||report.error} notice={action.notice}/>
      {type==="CASHFLOW"&&cash.data?<><FlowChart points={[...cash.data.history,...cash.data.projection]}/><div className="fx-chips"><Stamp kind="good">REAL · libro mayor</Stamp><Stamp kind="warn">PROYECCIÓN · {cash.data.scenario}</Stamp></div><ul className="fx-assumptions">{cash.data.assumptions.map((a:string)=><li key={a}>{a}</li>)}</ul></>:null}
      {!ready?<Empty title="Completa los parámetros del informe"/>:report.data?<><Register rows={report.data.rows} rowKey={(r:any)=>JSON.stringify(r)} columns={report.data.columns.map((c:any,i:number)=>({key:String(i),label:c.label,align:c.align==="right"?"right":undefined,render:(r:any)=>typeof r[i]==="number"?<Amount value={r[i]} signed/>:r[i]===""&&i===0?"":<span className={r[0]===""&&String(r[1]).toUpperCase()===r[1]?"fx-heading-cell":""}>{r[i]}</span>}))} empty="Sin datos para el período"/><ul className="fx-summary">{report.data.summary.map((s:string)=><li key={s}>{s}</li>)}</ul><p className="fx-hint">Informe interno de gestión. No constituye documento tributario ni declaración ante el SII.</p></>:<Loading/>}
    </Section></div>;
}

export function FinanceSettings({tick}:ViewProps){
  const{role}=useAccess();const settings=useLoad(()=>financeApi.get<any>(role,"/settings"),[role,tick]);const types=useLoad(()=>financeApi.get<any[]>(role,"/dte/document-types"),[role,tick]);const certs=useLoad(()=>canFinance(role,"dte.view")?financeApi.get<any[]>(role,"/dte/certificates"):Promise.resolve([]),[role,tick]);const folios=useLoad(()=>canFinance(role,"dte.view")?financeApi.get<any[]>(role,"/dte/folios"):Promise.resolve([]),[role,tick]);
  const policies=useLoad(()=>financeApi.get<any[]>(role,"/approval-policies").catch(()=>[]),[role,tick]);const online=useLoad(()=>financeApi.get<any>(role,"/online-payments/config"),[role,tick]);const action=useAction(async()=>{await settings.reload();await types.reload();await certs.reload();await folios.reload();await policies.reload();await online.reload();});
  const[form,setForm]=useState<any>(null);useEffect(()=>{if(settings.data)setForm({...settings.data});},[settings.data]);const manage=canFinance(role,"finance.settings.manage");const dteManage=canFinance(role,"dte.manage");
  const[cert,setCert]=useState({label:"",secretRef:"DTE_CERTIFICATE_PEM",holderRut:""});const[caf,setCaf]=useState<{environment:string;file:UploadedFile|null}>({environment:"CERTIFICATION",file:null});const[policy,setPolicy]=useState<any>(null);
  if(settings.error)return <LoadError error={settings.error} retry={()=>void settings.reload()}/>;if(!form)return <Loading/>;const set=(k:string,v:unknown)=>setForm({...form,[k]:v});const i=form.integrations??{};
  const save=(keys:string[])=>action.run(()=>financeApi.patch(role,"/settings",Object.fromEntries(keys.map((k)=>[k,form[k]]))),"Configuración guardada y auditada.");
  return <div className="fx-stack"><Feedback error={action.error} notice={action.notice}/>
    <Section eyebrow="INTEGRACIONES" title="Estado de configuración del servidor" description="Los secretos viven sólo en el servidor (variables de entorno); aquí sólo se informa si están presentes."><div className="fx-chips">{([["supabase","Supabase"],["encryption","Cifrado (FINANCE_ENCRYPTION_KEY)"],["mercadoPago","Mercado Pago"],["resend","Correo (Resend)"],["externalDte","Proveedor DTE externo"],["xsd","Esquemas XSD SII"]] as const).map(([k,t])=><span key={k} className={`fx-chip ${i[k]?"good":"warn"}`}>{t} <strong>{i[k]?"configurado":"no configurado"}</strong></span>)}</div></Section>
    <div className="fx-two"><Section eyebrow="EMPRESA" title={form.companyLegalName} description="Datos del emisor para DTE e informes.">
      <div className="fx-form"><Field label="Razón social" span={2}><input disabled={!manage} value={form.companyLegalName??""} onChange={(e)=>set("companyLegalName",e.target.value)}/></Field><Field label="RUT"><input disabled={!manage} value={form.companyRut??""} onChange={(e)=>set("companyRut",e.target.value)}/></Field><Field label="Giro" span={2}><input disabled={!manage} value={form.companyBusinessActivity??""} onChange={(e)=>set("companyBusinessActivity",e.target.value)}/></Field><Field label="Acteco"><input disabled={!manage} inputMode="numeric" value={form.companyActivityCode??""} onChange={(e)=>set("companyActivityCode",e.target.value.replace(/\D/g,""))}/></Field><Field label="Dirección" span={2}><input disabled={!manage} value={form.companyAddress??""} onChange={(e)=>set("companyAddress",e.target.value)}/></Field><Field label="Comuna"><input disabled={!manage} value={form.companyCommune??""} onChange={(e)=>set("companyCommune",e.target.value)}/></Field></div>
      {manage?<div className="fx-actions end"><button className="fx-btn primary" onClick={()=>void save(["companyLegalName","companyRut","companyBusinessActivity","companyActivityCode","companyAddress","companyCommune","companyCity","companyEmail"])}>Guardar empresa</button></div>:null}</Section>
    <Section eyebrow="POLÍTICAS" title="Facturación, conciliación y cobranza"><div className="fx-form"><Field label="Facturas requieren aprobación"><input type="checkbox" disabled={!manage} checked={Boolean(form.invoiceRequiresApproval)} onChange={(e)=>set("invoiceRequiresApproval",e.target.checked)}/></Field><Field label="Umbral de aprobación" hint="Vacío: todas"><input disabled={!manage} inputMode="numeric" value={form.invoiceApprovalThreshold??""} onChange={(e)=>set("invoiceApprovalThreshold",e.target.value===""?null:Number(e.target.value.replace(/\D/g,"")))}/></Field><Field label="Plazo de pago por defecto"><input disabled={!manage} inputMode="numeric" value={form.defaultPaymentTermsDays} onChange={(e)=>set("defaultPaymentTermsDays",Number(e.target.value.replace(/\D/g,"")))}/></Field><Field label="Borradores automáticos de recurrentes"><input type="checkbox" disabled={!manage} checked={Boolean(form.autoCreateBillingDrafts)} onChange={(e)=>set("autoCreateBillingDrafts",e.target.checked)}/></Field><Field label="Tolerancia de fecha (días)"><input disabled={!manage} inputMode="numeric" value={form.reconciliationDateToleranceDays} onChange={(e)=>set("reconciliationDateToleranceDays",Number(e.target.value.replace(/\D/g,"")))}/></Field><Field label="Tolerancia de monto"><input disabled={!manage} inputMode="numeric" value={form.reconciliationAmountTolerance} onChange={(e)=>set("reconciliationAmountTolerance",Number(e.target.value.replace(/\D/g,"")))}/></Field><Field label="Auto-conciliación (sólo exactas)"><input type="checkbox" disabled={!manage} checked={Boolean(form.autoMatchEnabled)} onChange={(e)=>set("autoMatchEnabled",e.target.checked)}/></Field><Field label="Recordatorios de cobranza"><input type="checkbox" disabled={!manage} checked={Boolean(form.collectionRemindersEnabled)} onChange={(e)=>set("collectionRemindersEnabled",e.target.checked)}/></Field><Field label="Umbral concentración (%)"><input disabled={!manage} inputMode="numeric" value={form.clientConcentrationThreshold} onChange={(e)=>set("clientConcentrationThreshold",Number(e.target.value.replace(/\D/g,"")))}/></Field></div>
      {manage?<div className="fx-actions end"><button className="fx-btn primary" onClick={()=>void save(["invoiceRequiresApproval","invoiceApprovalThreshold","defaultPaymentTermsDays","autoCreateBillingDrafts","reconciliationDateToleranceDays","reconciliationAmountTolerance","autoMatchEnabled","collectionRemindersEnabled","clientConcentrationThreshold"])}>Guardar políticas</button></div>:null}</Section></div>
    <Section eyebrow="EMISIÓN ELECTRÓNICA" title={`${label(form.dteProvider)} · ${label(form.dteEnvironment)}`} description={<>Integración directa con servicios oficiales del SII o proveedor certificado. Producción requiere completar la certificación (ver <code>docs/SII-DTE-CERTIFICATION.md</code>).</>}>
      <div className="fx-form"><Field label="Proveedor"><select disabled={!manage} value={form.dteProvider} onChange={(e)=>set("dteProvider",e.target.value)}><option value="NONE">Sin proveedor</option><option value="SII_DIRECT">SII directo</option><option value="EXTERNAL">Proveedor certificado</option></select></Field><Field label="Ambiente"><select disabled={!manage} value={form.dteEnvironment} onChange={(e)=>set("dteEnvironment",e.target.value)}><option value="CERTIFICATION">Certificación (maullin)</option><option value="PRODUCTION">Producción (palena)</option></select></Field><Field label="N° resolución"><input disabled={!manage} inputMode="numeric" value={form.dteResolutionNumber??""} onChange={(e)=>set("dteResolutionNumber",e.target.value===""?null:Number(e.target.value.replace(/\D/g,"")))}/></Field><Field label="Fecha resolución"><DateInput value={form.dteResolutionDate??""} onChange={(v)=>set("dteResolutionDate",v||null)}/></Field><Field label="Producción autorizada"><span>{form.dteProductionAuthorized?<Stamp kind="good">Autorizada</Stamp>:<Stamp kind="warn">No autorizada</Stamp>}</span></Field></div>
      {manage?<div className="fx-actions end">{role==="GERENTE_GENERAL"&&!form.dteProductionAuthorized?<button className="fx-btn ghost" onClick={()=>{const evidence=window.prompt("Evidencia de autorización de producción del SII (resolución y fecha):");if(evidence)void action.run(()=>financeApi.patch(role,"/settings",{dteProductionAuthorized:true,productionEvidence:evidence}),"Autorización de producción registrada.");}}>Declarar autorización de producción</button>:null}<button className="fx-btn primary" onClick={()=>void save(["dteProvider","dteEnvironment","dteResolutionNumber","dteResolutionDate"])}>Guardar emisión</button></div>:null}
      <h4 className="fx-subhead">Tipos de documento</h4><Register rows={types.data??[]} rowKey={(t:any)=>String(t.code)} columns={[{key:"c",label:"Código",render:(t:any)=><code>{t.code}</code>},{key:"n",label:"Documento",render:(t:any)=>t.name},{key:"e",label:"Habilitado",render:(t:any)=>dteManage?<button className={`fx-toggle${t.enabledForIssue?" on":""}`} onClick={()=>void action.run(()=>financeApi.patch(role,`/dte/document-types/${t.code}`,{enabledForIssue:!t.enabledForIssue}),"Tipo actualizado.")}>{t.enabledForIssue?"Sí":"No"}</button>:<Pill value={t.enabledForIssue?"ACTIVE":"INACTIVE"}/>},{key:"z",label:"Certificado SII",render:(t:any)=>t.certified?<Pill value="OK" text="Certificado"/>:dteManage?<button className="fx-btn small ghost" onClick={()=>{const notes=window.prompt("Evidencia de certificación SII para este tipo (resolución, fecha):");if(notes)void action.run(()=>financeApi.patch(role,`/dte/document-types/${t.code}`,{certified:true,notes}),"Tipo marcado como certificado.");}}>Marcar certificado</button>:<Pill value="PENDING"/>}]}/>
      <div className="fx-two"><div><h4 className="fx-subhead">Certificado digital</h4><p className="fx-hint">El PEM (llave privada + certificado) se carga como secreto del servidor. Aquí sólo se registran sus metadatos y alertas de vencimiento (60/30/15/7/3/1 días).</p>{(certs.data??[]).map((c:any)=><KeyValue key={c.id} items={[["Certificado",c.label],["Titular",c.subject],["Vence",`${moment(c.expiresAt)} (${c.daysRemaining} días)`],["Huella",`${String(c.fingerprintSha256).slice(0,20)}…`],["Estado",<Pill key="s" value={c.status}/>]]}/>)}
        {dteManage?<div className="fx-form boxed"><Field label="Nombre"><input value={cert.label} onChange={(e)=>setCert({...cert,label:e.target.value})}/></Field><Field label="Variable de entorno del secreto"><input value={cert.secretRef} onChange={(e)=>setCert({...cert,secretRef:e.target.value.toUpperCase()})}/></Field><Field label="RUT titular"><input value={cert.holderRut} onChange={(e)=>setCert({...cert,holderRut:e.target.value})}/></Field><div className="fx-actions"><button className="fx-btn" disabled={!cert.label} onClick={()=>void action.run(()=>financeApi.post(role,"/dte/certificates",cert),"Metadatos del certificado registrados.")}>Registrar metadatos</button></div></div>:null}</div>
      <div><h4 className="fx-subhead">Folios CAF</h4><Register rows={folios.data??[]} rowKey={(f:any)=>f.id} columns={[{key:"t",label:"Tipo",render:(f:any)=>f.documentTypeCode},{key:"r",label:"Rango",render:(f:any)=>`${f.rangeFrom}–${f.rangeTo}`},{key:"e",label:"Ambiente",render:(f:any)=>label(f.environment)},{key:"a",label:"Disponibles",align:"right",render:(f:any)=>f.available},{key:"u",label:"Usados/anulados",align:"right",render:(f:any)=>`${f.used}/${f.voided}`}]} empty="Sin CAF cargados"/>
        {dteManage?<div className="fx-form boxed"><Field label="Ambiente"><select value={caf.environment} onChange={(e)=>setCaf({...caf,environment:e.target.value})}><option value="CERTIFICATION">Certificación</option><option value="PRODUCTION">Producción</option></select></Field><Field label="Archivo CAF (XML del SII)" span={2}><FileInput accept=".xml" file={caf.file} onFile={(f)=>setCaf({...caf,file:f})}/></Field><div className="fx-actions"><button className="fx-btn" disabled={!caf.file} onClick={()=>void action.run(()=>financeApi.post(role,"/dte/caf",caf),"CAF cargado (cifrado en almacenamiento privado).")}>Cargar CAF</button></div></div>:null}</div></div>
    </Section>
    <div className="fx-two"><Section eyebrow="PAGOS EN LÍNEA" title={online.data?.enabled?"Mercado Pago habilitado":"Pagos en línea deshabilitados"} description={online.data?.redirectNotice}><ul className="fx-checks">{(online.data?.missing??[]).map((m:string)=><li key={m} className="missing"><span>✗</span><div><strong>{m}</strong></div></li>)}{online.data?.enabled?<li className="ok"><span>✓</span><div><strong>Payment Brick embebido · webhook con firma · sin PAN/CVV</strong></div></li>:null}</ul>{manage?<div className="fx-actions"><button className={`fx-toggle${form.onlinePaymentsEnabled?" on":""}`} onClick={()=>void action.run(()=>financeApi.patch(role,"/settings",{onlinePaymentsEnabled:!form.onlinePaymentsEnabled}),"Preferencia de pagos en línea actualizada.")}>{form.onlinePaymentsEnabled?"Activado":"Desactivado"}</button></div>:null}</Section>
    <Section eyebrow="APROBACIONES" title="Políticas configurables" description="Sin límites fijos en código: rango de monto, categoría, centro y rol aprobador por nivel." actions={manage?<button className="fx-btn ghost" onClick={()=>setPolicy({entityType:"EXPENSE",name:"",minAmount:"0",maxAmount:"",approverRole:"GERENTE_GENERAL",level:"1"})}><Plus size={14}/>Política</button>:null}><Register rows={policies.data??[]} rowKey={(p:any)=>p.id} columns={[{key:"n",label:"Política",render:(p:any)=><>{p.name}<small className="block">{label(p.entityType)} · nivel {p.level}</small></>},{key:"r",label:"Rango",render:(p:any)=>`${money(p.minAmount)} – ${p.maxAmount===null?"sin tope":money(p.maxAmount)}`},{key:"a",label:"Aprueba",render:(p:any)=>p.approverRole},{key:"s",label:"",render:(p:any)=><Pill value={p.active?"ACTIVE":"INACTIVE"}/>}]} empty="Sin políticas: aprueba cualquier rol con permiso de aprobación"/></Section></div>
    <Drawer open={Boolean(policy)} title="Política de aprobación" onClose={()=>setPolicy(null)}>{policy?<><div className="fx-form"><Field label="Entidad"><select value={policy.entityType} onChange={(e)=>setPolicy({...policy,entityType:e.target.value})}>{["EXPENSE","PAYABLE","VENDOR_PAYMENT"].map((t)=><option key={t} value={t}>{label(t)}</option>)}</select></Field><Field label="Nombre" span={2}><input value={policy.name} onChange={(e)=>setPolicy({...policy,name:e.target.value})}/></Field><Field label="Desde"><input inputMode="numeric" value={policy.minAmount} onChange={(e)=>setPolicy({...policy,minAmount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Hasta (vacío = sin tope)"><input inputMode="numeric" value={policy.maxAmount} onChange={(e)=>setPolicy({...policy,maxAmount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Nivel"><select value={policy.level} onChange={(e)=>setPolicy({...policy,level:e.target.value})}>{["1","2","3"].map((l)=><option key={l}>{l}</option>)}</select></Field><Field label="Rol aprobador" span={3}><select value={policy.approverRole} onChange={(e)=>setPolicy({...policy,approverRole:e.target.value})}>{["GERENTE_GENERAL","FINANZAS","CONTADOR"].map((r)=><option key={r} value={r}>{r}</option>)}</select></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!policy.name} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/approval-policies",{...policy,minAmount:Number(policy.minAmount||0),maxAmount:policy.maxAmount===""?null:Number(policy.maxAmount),level:Number(policy.level)}),"Política creada.");if(r)setPolicy(null);}}>Guardar</button></div></>:null}</Drawer>
  </div>;
}
