"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { BillingSchedule, DteReadiness, Invoice, Payment, PaymentAllocation, TaxDocument } from "@zyteron/contracts";
import { BadgeCheck, CalendarClock, CircleDollarSign, Download, FilePlus2, Link2, Plus, Receipt, RefreshCw, Search, Send, ShieldCheck, Upload, Wand2 } from "lucide-react";
import { useAccess } from "@/components/access-context";
import { financeApi, type UploadedFile } from "@/lib/finance-api";
import { canFinance, day, label, moment, money, todayIso } from "@/lib/finance-format";
import { AgingBar, Amount, DateInput, Drawer, Feedback, Field, FileInput, KeyValue, LoadError, Loading, Pill, ReasonDialog, Register, Section, Stamp, useAction, useLoad, useQueryParams } from "./fx-ui";
import type { ViewProps } from "./finance-workspace";

type Paged<T>={items:T[];total:number;page:number;totalPages:number};
type ClientOption={id:string;name:string;legalName:string;rut:string;dteEmail:string|null;complete:boolean};
const docName=(code:number)=>({33:"Factura",34:"Factura exenta",61:"Nota de crédito",56:"Nota de débito"} as Record<number,string>)[code]??`Tipo ${code}`;

export function ClientPicker({value,onChange}:{value:string;onChange:(id:string,option?:ClientOption)=>void}){
  const{role}=useAccess();const[search,setSearch]=useState("");const{data}=useLoad(()=>financeApi.get<ClientOption[]>(role,`/client-options${search?`?search=${encodeURIComponent(search)}`:""}`),[role,search]);
  return <div className="fx-picker"><Search size={13}/><input placeholder="Buscar por razón social o RUT" value={search} onChange={(e)=>setSearch(e.target.value)} aria-label="Buscar cliente"/><select value={value} onChange={(e)=>onChange(e.target.value,data?.find((c)=>c.id===e.target.value))} aria-label="Cliente"><option value="">Selecciona cliente…</option>{data?.map((c)=><option key={c.id} value={c.id}>{c.name} · {c.rut}{c.complete?"":" (datos tributarios incompletos)"}</option>)}</select></div>;
}
type Line={description:string;quantity:string;unitPrice:string;isExempt:boolean};
export function LinesEditor({lines,onChange,exemptOnly=false}:{lines:Line[];onChange:(lines:Line[])=>void;exemptOnly?:boolean}){
  const set=(i:number,patch:Partial<Line>)=>onChange(lines.map((l,n)=>n===i?{...l,...patch}:l));const net=lines.filter((l)=>!l.isExempt&&!exemptOnly).reduce((t,l)=>t+Math.round(Number(l.quantity||0)*Number(l.unitPrice||0)),0),exempt=lines.filter((l)=>l.isExempt||exemptOnly).reduce((t,l)=>t+Math.round(Number(l.quantity||0)*Number(l.unitPrice||0)),0);
  return <div className="fx-lines"><table><thead><tr><th>Descripción</th><th>Cant.</th><th>Precio unitario</th><th>Exento</th><th className="r">Neto</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={i}><td><input value={l.description} onChange={(e)=>set(i,{description:e.target.value})} placeholder="Detalle del servicio"/></td><td><input inputMode="decimal" value={l.quantity} onChange={(e)=>set(i,{quantity:e.target.value})}/></td><td><input inputMode="numeric" value={l.unitPrice} onChange={(e)=>set(i,{unitPrice:e.target.value.replace(/[^\d.]/g,"")})}/></td><td><input type="checkbox" checked={exemptOnly||l.isExempt} disabled={exemptOnly} onChange={(e)=>set(i,{isExempt:e.target.checked})} aria-label="Línea exenta"/></td><td className="r">{money(Math.round(Number(l.quantity||0)*Number(l.unitPrice||0)))}</td><td>{lines.length>1?<button type="button" className="fx-icon" onClick={()=>onChange(lines.filter((_,n)=>n!==i))} aria-label="Quitar línea">×</button>:null}</td></tr>)}</tbody></table>
    <div className="fx-lines-foot"><button type="button" className="fx-btn ghost" onClick={()=>onChange([...lines,{description:"",quantity:"1",unitPrice:"",isExempt:false}])}><Plus size={13}/>Línea</button><dl><div><dt>Neto afecto</dt><dd>{money(net)}</dd></div><div><dt>Exento</dt><dd>{money(exempt)}</dd></div><div><dt>IVA</dt><dd>Tasa vigente versionada (se calcula en servidor)</dd></div></dl></div></div>;
}
const emptyLine=():Line=>({description:"",quantity:"1",unitPrice:"",isExempt:false});

function InvoiceComposer({open,onClose,onCreated}:{open:boolean;onClose:()=>void;onCreated:(id:string)=>void}){
  const{role}=useAccess();const[clientId,setClientId]=useState("");const[type,setType]=useState("33");const[lines,setLines]=useState<Line[]>([emptyLine()]);const[terms,setTerms]=useState("");const[dueDate,setDueDate]=useState("");const[notes,setNotes]=useState("");const action=useAction();
  const save=async()=>{const created=await action.run(()=>financeApi.post<Invoice>(role,"/invoices",{clientId,documentTypeCode:Number(type),lines:lines.map((l)=>({description:l.description,quantity:Number(l.quantity),unitPrice:Number(l.unitPrice),isExempt:type==="34"||l.isExempt})),paymentTermsDays:terms===""?undefined:Number(terms),dueDate:dueDate||undefined,notes}));if(created){onCreated(created.id);setLines([emptyLine()]);setClientId("");}};
  return <Drawer open={open} onClose={onClose} title="Nuevo borrador de factura" subtitle="Documento interno: no es un DTE hasta su emisión ante el SII." wide>
    <div className="fx-form"><Field label="Cliente" span={3}><ClientPicker value={clientId} onChange={(id)=>setClientId(id)}/></Field><Field label="Tipo de documento"><select value={type} onChange={(e)=>setType(e.target.value)}><option value="33">33 · Factura electrónica</option><option value="34">34 · Factura exenta</option></select></Field><Field label="Plazo de pago (días)" hint="Vacío: días de crédito del cliente"><input inputMode="numeric" value={terms} onChange={(e)=>setTerms(e.target.value.replace(/\D/g,""))}/></Field><Field label="Vencimiento (opcional)"><DateInput value={dueDate} onChange={setDueDate}/></Field></div>
    <LinesEditor lines={lines} onChange={setLines} exemptOnly={type==="34"}/><Field label="Notas internas" span={3}><textarea rows={2} value={notes} onChange={(e)=>setNotes(e.target.value)}/></Field>
    <Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn ghost" onClick={onClose}>Cancelar</button><button className="fx-btn primary" disabled={action.busy||!clientId||lines.some((l)=>!l.description||!l.unitPrice)} onClick={()=>void save()}><FilePlus2 size={14}/>Guardar borrador</button></div>
  </Drawer>;
}

const steps=["DRAFT","PENDING_APPROVAL","READY_TO_ISSUE","ISSUING","ISSUED","PAID"];
function InvoiceDetail({id,onClose,onChanged}:{id:string;onClose:()=>void;onChanged:()=>void}){
  const{role}=useAccess();const{data,error,reload}=useLoad(()=>financeApi.get<any>(role,`/invoices/${id}`),[role,id]);const readiness=useLoad(()=>financeApi.get<DteReadiness>(role,`/invoices/${id}/readiness`),[role,id,data?.status]);
  const action=useAction(async()=>{await reload();await readiness.reload();onChanged();});const[dialog,setDialog]=useState<null|"cancel"|"reject">(null);const[external,setExternal]=useState(false);const[ext,setExt]=useState<{folio:string;issueDate:string;trackId:string;evidence:UploadedFile|null}>({folio:"",issueDate:todayIso(),trackId:"",evidence:null});
  const[note,setNote]=useState<null|"credit"|"debit">(null);const[noteForm,setNoteForm]=useState({reason:"",referenceCode:"3",lines:[emptyLine()]});const[link,setLink]=useState<{url:string;expiresAt:string}|null>(null);
  if(error)return <Drawer open title="Factura" onClose={onClose}><Feedback error={error}/></Drawer>;if(!data)return <Drawer open title="Factura" onClose={onClose}><Loading/></Drawer>;const inv=data as Invoice&{lines:any[];allocations:PaymentAllocation[];taxDocuments:TaxDocument[];relatedNotes:Invoice[];events:any[]};
  const current=inv.taxDocuments.find((d)=>d.id===inv.taxDocumentId);const can=(p:Parameters<typeof canFinance>[1])=>canFinance(role,p);
  return <Drawer open title={`${docName(inv.documentTypeCode)} ${current?.folio?`N° ${current.folio}`:inv.invoiceNumber}`} subtitle={<>{inv.clientName??inv.clientSnapshot.legalName} · <Pill value={inv.effectiveStatus}/></>} onClose={onClose} wide>
    <ol className="fx-stepper">{steps.map((s)=>{const index=steps.indexOf(inv.status==="PARTIALLY_PAID"?"ISSUED":inv.status==="CREDITED"?"PAID":inv.status);return <li key={s} className={steps.indexOf(s)<=index?"done":""}>{label(s)}</li>;})}</ol>
    <div className="fx-doc"><KeyValue items={[["N° interno",inv.invoiceNumber],["Folio SII",current?.folio??"Sin folio (no emitida)"],["Emisión",day(inv.issueDate)],["Vencimiento",day(inv.dueDate)],["Receptor",`${inv.clientSnapshot.legalName??""} · ${inv.clientSnapshot.rut??""}`],["Giro / dirección",`${inv.clientSnapshot.businessActivity??"—"} · ${inv.clientSnapshot.address??"—"}, ${inv.clientSnapshot.commune??""}`]]}/>
      <table className="fx-doc-lines"><thead><tr><th>Detalle</th><th className="r">Cant.</th><th className="r">Precio</th><th className="r">Neto</th></tr></thead><tbody>{inv.lines.map((l)=><tr key={l.id}><td>{l.description}{l.isExempt?<em> · exento</em>:null}</td><td className="r">{l.quantity}</td><td className="r">{money(l.unitPrice)}</td><td className="r">{money(l.netAmount)}</td></tr>)}</tbody>
        <tfoot><tr><td colSpan={3}>Neto</td><td className="r">{money(inv.netAmount)}</td></tr><tr><td colSpan={3}>Exento</td><td className="r">{money(inv.exemptAmount)}</td></tr><tr><td colSpan={3}>IVA {inv.taxRate!==null?`${(inv.taxRate*100).toFixed(0)}% (regla versionada)`:""}</td><td className="r">{money(inv.taxAmount)}</td></tr><tr className="total"><td colSpan={3}>Total</td><td className="r">{money(inv.totalAmount)}</td></tr><tr><td colSpan={3}>Pagado · acreditado</td><td className="r">{money(inv.amountPaid)} · {money(inv.amountCredited)}</td></tr><tr className="total"><td colSpan={3}>Saldo</td><td className="r">{money(inv.balanceDue)}</td></tr></tfoot></table></div>
    <Feedback error={action.error} notice={action.notice}/>
    <div className="fx-actions">
      {inv.status==="DRAFT"&&(can("invoice.edit")||can("invoice.create"))?<button className="fx-btn primary" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.post(role,`/invoices/${id}/submit`),"Enviada según política de aprobación.")}><Send size={14}/>Enviar</button>:null}
      {inv.status==="PENDING_APPROVAL"&&can("invoice.approve")?<><button className="fx-btn primary" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.post(role,`/invoices/${id}/approve`),"Factura aprobada.")}><BadgeCheck size={14}/>Aprobar</button><button className="fx-btn ghost" onClick={()=>setDialog("reject")}>Rechazar</button></>:null}
      {["DRAFT","PENDING_APPROVAL","READY_TO_ISSUE"].includes(inv.status)&&(can("invoice.edit")||can("invoice.approve"))?<button className="fx-btn ghost" onClick={()=>setDialog("cancel")}>Anular borrador</button>:null}
      {["ISSUED","PARTIALLY_PAID","PAID"].includes(inv.status)&&[33,34,56].includes(inv.documentTypeCode)&&can("dte.credit_note")?<button className="fx-btn ghost" onClick={()=>setNote("credit")}>Nota de crédito</button>:null}
      {["ISSUED","PARTIALLY_PAID","PAID","CREDITED"].includes(inv.status)&&can("dte.debit_note")?<button className="fx-btn ghost" onClick={()=>setNote("debit")}>Nota de débito</button>:null}
      {["ISSUED","PARTIALLY_PAID"].includes(inv.status)&&inv.balanceDue>0&&(can("payment.record")||can("collection.manage"))?<button className="fx-btn ghost" disabled={action.busy} onClick={async()=>{const r=await action.run(()=>financeApi.post<{url:string;expiresAt:string}>(role,`/invoices/${id}/payment-links`,{expiresInDays:7}));if(r)setLink(r);}}><Link2 size={14}/>Link de pago</button>:null}
    </div>
    {link?<div className="fx-callout"><strong>Link de pago (se muestra una sola vez)</strong><code>{link.url}</code><small>Vence {moment(link.expiresAt)}. El token se guarda sólo como hash.</small></div>:null}
    {inv.status==="READY_TO_ISSUE"||inv.status==="ISSUING"?<Section eyebrow="EMISIÓN DTE" title={readiness.data?.canIssue?"Requisitos completos":"Emitir DTE deshabilitado"} description="Cada requisito se verifica en el servidor. Ninguna emisión ni aceptación del SII se simula.">
      <ul className="fx-checks">{readiness.data?.requirements.map((r)=><li key={r.key} className={r.satisfied?"ok":"missing"}><span>{r.satisfied?"✓":"✗"}</span><div><strong>{r.label}</strong><small>{r.detail}</small></div></li>)}</ul>
      <div className="fx-actions">{can("dte.issue")||can("invoice.issue")?<button className="fx-btn primary" disabled={!readiness.data?.canIssue||action.busy} title={readiness.data?.canIssue?"":readiness.data?.missing.join("\n")} onClick={()=>void action.run(()=>financeApi.post(role,`/invoices/${id}/issue`),"Documento enviado al SII. El estado final llega con la respuesta oficial.")}><ShieldCheck size={14}/>Emitir DTE</button>:null}{inv.status==="READY_TO_ISSUE"&&(can("dte.issue")||can("invoice.issue"))?<button className="fx-btn ghost" onClick={()=>setExternal((v)=>!v)}><Upload size={14}/>Registrar emisión externa</button>:null}</div>
      {external?<div className="fx-form boxed"><p className="fx-hint">Para DTE emitidos en el portal del SII u otro sistema. Adjunta el XML del DTE (se verifica RUT, tipo, folio, fecha y total) o el PDF. Quedará como «aceptación SII no verificada» hasta registrar la evidencia.</p><Field label="Folio"><input inputMode="numeric" value={ext.folio} onChange={(e)=>setExt({...ext,folio:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Fecha de emisión"><DateInput value={ext.issueDate} onChange={(v)=>setExt({...ext,issueDate:v})}/></Field><Field label="Track ID (opcional)"><input value={ext.trackId} onChange={(e)=>setExt({...ext,trackId:e.target.value})}/></Field><Field label="Evidencia (XML o PDF)" span={3}><FileInput accept=".xml,.pdf" file={ext.evidence} onFile={(f)=>setExt({...ext,evidence:f})}/></Field><div className="fx-actions"><button className="fx-btn primary" disabled={!ext.folio||!ext.evidence||action.busy} onClick={()=>void action.run(()=>financeApi.post(role,`/invoices/${id}/register-external`,{folio:Number(ext.folio),issueDate:ext.issueDate,trackId:ext.trackId||undefined,evidence:ext.evidence}),"Emisión externa registrada con evidencia.")}>Registrar</button></div></div>:null}
    </Section>:null}
    {note?<Section eyebrow={note==="credit"?"NOTA DE CRÉDITO 61":"NOTA DE DÉBITO 56"} title="Documento referenciado" description="Se crea en borrador referenciando este documento; se emite con el mismo flujo de aprobación y DTE.">
      <div className="fx-form">{note==="credit"?<Field label="Código de referencia"><select value={noteForm.referenceCode} onChange={(e)=>setNoteForm({...noteForm,referenceCode:e.target.value})}><option value="1">1 · Anula documento</option><option value="2">2 · Corrige texto</option><option value="3">3 · Corrige montos</option></select></Field>:null}<Field label="Razón (máx. 90)" span={2}><input maxLength={90} value={noteForm.reason} onChange={(e)=>setNoteForm({...noteForm,reason:e.target.value})}/></Field></div>
      {note==="debit"||noteForm.referenceCode==="3"?<LinesEditor lines={noteForm.lines} onChange={(lines)=>setNoteForm({...noteForm,lines})}/>:null}
      <div className="fx-actions"><button className="fx-btn ghost" onClick={()=>setNote(null)}>Cancelar</button><button className="fx-btn primary" disabled={!noteForm.reason||action.busy} onClick={async()=>{const created=await action.run(()=>financeApi.post<Invoice>(role,`/invoices/${id}/${note==="credit"?"credit-note":"debit-note"}`,{reason:noteForm.reason,referenceCode:noteForm.referenceCode,lines:noteForm.lines.map((l)=>({description:l.description,quantity:Number(l.quantity),unitPrice:Number(l.unitPrice),isExempt:l.isExempt}))}),"Nota creada en borrador.");if(created)setNote(null);}}>Crear borrador</button></div></Section>:null}
    {inv.allocations.length?<Section eyebrow="APLICACIONES" title="Pagos aplicados"><Register rows={inv.allocations} rowKey={(a)=>a.id} columns={[{key:"d",label:"Fecha",render:(a)=>moment(a.allocatedAt)},{key:"p",label:"Pago",render:(a)=><Link href={`/finance/payments?payment=${a.paymentId}`}>Ver pago</Link>},{key:"s",label:"Estado",render:(a)=>a.reversedAt?<Pill value="REVERSED"/>:<Pill value="POSTED" text="Vigente"/>},{key:"a",label:"Monto",align:"right",render:(a)=><Amount value={a.amount}/>}]}/></Section>:null}
    {inv.relatedNotes.length?<Section eyebrow="NOTAS" title="Documentos que referencian"><ul className="fx-queue">{inv.relatedNotes.map((n)=><li key={n.id}><div><strong>{docName(n.documentTypeCode)} {n.invoiceNumber}</strong><small>{n.referenceReason}</small></div><Amount value={n.totalAmount}/><Pill value={n.status}/></li>)}</ul></Section>:null}
    <Section eyebrow="TRAZABILIDAD" title="Eventos"><ol className="fx-timeline">{inv.events.map((e:any)=><li key={e.id}><time>{moment(e.occurredAt)}</time><span>{e.title}</span></li>)}{!inv.events.length?<li className="muted">Sin eventos financieros aún.</li>:null}</ol></Section>
    <ReasonDialog open={dialog!==null} title={dialog==="reject"?"Rechazar aprobación":"Anular borrador"} description={dialog==="cancel"?"Sólo borradores no emitidos. Un documento emitido se corrige con nota de crédito.":undefined} onCancel={()=>setDialog(null)} onConfirm={(reason)=>{const kind=dialog;setDialog(null);void action.run(()=>financeApi.post(role,`/invoices/${id}/${kind}`,{reason}),kind==="reject"?"Devuelta a borrador.":"Borrador anulado.");}}/>
  </Drawer>;
}

function Recurring(){
  const{role}=useAccess();const schedules=useLoad(()=>financeApi.get<Array<BillingSchedule&{clientName:string|null}>>(role,"/billing-schedules"),[role]);const suggestions=useLoad(()=>financeApi.get<any[]>(role,"/billing-schedules/suggestions"),[role]);const action=useAction(async()=>{await schedules.reload();await suggestions.reload();});
  const[form,setForm]=useState<any>(null);
  return <><Section eyebrow="FACTURACIÓN RECURRENTE" title="Programaciones activas" description="Generan BORRADORES en su fecha (idempotente por período). Nunca emiten solas." actions={canFinance(role,"invoice.edit")?<><button className="fx-btn ghost" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.post<any>(role,"/billing-schedules/run-due",{}),"Programaciones vencidas procesadas.")}><CalendarClock size={14}/>Generar borradores vencidos</button><button className="fx-btn primary" onClick={()=>setForm({clientId:"",description:"",frequency:"MONTHLY",amount:"",nextBillingDate:todayIso(),isExempt:false})}><Plus size={14}/>Programación</button></>:null}>
    <Feedback error={action.error} notice={action.notice}/>
    {schedules.data?<Register rows={schedules.data} rowKey={(s)=>s.id} columns={[{key:"c",label:"Cliente",render:(s)=>s.clientName??"—"},{key:"d",label:"Descripción",render:(s)=>s.description},{key:"f",label:"Frecuencia",render:(s)=>label(s.frequency)},{key:"n",label:"Próxima",render:(s)=>day(s.nextBillingDate)},{key:"e",label:"Término",render:(s)=>day(s.endDate)},{key:"a",label:"Monto neto",align:"right",render:(s)=><Amount value={s.amount}/>},{key:"x",label:"",render:(s)=>s.active&&canFinance(role,"invoice.edit")?<button className="fx-btn ghost small" onClick={()=>void action.run(()=>financeApi.patch(role,`/billing-schedules/${s.id}`,{active:false}),"Programación desactivada.")}>Desactivar</button>:<Pill value={s.active?"ACTIVE":"INACTIVE"}/>}]} empty="Sin programaciones recurrentes"/>:<Loading/>}
  </Section>
  {suggestions.data?.length?<Section eyebrow="DESDE SERVICIOS DEL CLIENTE" title="Servicios recurrentes sin programación" description="Servicios activos con precio acordado y frecuencia; Finanzas decide crear la programación.">
    <ul className="fx-queue">{suggestions.data.map((s)=><li key={s.clientServiceId}><div><strong>{s.serviceName}</strong><small>{s.clientName} · {label(s.billingFrequency)} · desde {day(s.startDate)}</small></div><Amount value={s.amount}/>{canFinance(role,"invoice.edit")?<button className="fx-btn" onClick={()=>setForm({clientServiceId:s.clientServiceId,frequency:["MONTHLY","QUARTERLY","SEMIANNUAL","ANNUAL"].includes(s.billingFrequency)?s.billingFrequency:"MONTHLY",nextBillingDate:todayIso(),amount:String(s.amount),description:s.serviceName})}>Programar</button>:null}</li>)}</ul></Section>:null}
  <Drawer open={Boolean(form)} title="Programación de facturación" onClose={()=>setForm(null)}>{form?<><div className="fx-form">{!form.clientServiceId?<Field label="Cliente" span={3}><ClientPicker value={form.clientId} onChange={(id)=>setForm({...form,clientId:id})}/></Field>:<p className="fx-hint">Vinculada al servicio del cliente (precio y contrato desde Clientes).</p>}<Field label="Descripción" span={3}><input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></Field><Field label="Frecuencia"><select value={form.frequency} onChange={(e)=>setForm({...form,frequency:e.target.value})}>{["MONTHLY","QUARTERLY","SEMIANNUAL","ANNUAL","CUSTOM_DAYS"].map((f)=><option key={f} value={f}>{label(f)}</option>)}</select></Field>{form.frequency==="CUSTOM_DAYS"?<Field label="Cada (días)"><input value={form.intervalDays??""} onChange={(e)=>setForm({...form,intervalDays:e.target.value})}/></Field>:null}<Field label="Monto neto"><input inputMode="numeric" value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value.replace(/[^\d.]/g,"")})}/></Field><Field label="Primera facturación"><DateInput value={form.nextBillingDate} onChange={(v)=>setForm({...form,nextBillingDate:v})}/></Field><Field label="Término (opcional)"><DateInput value={form.endDate??""} onChange={(v)=>setForm({...form,endDate:v})}/></Field><Field label="Exento"><input type="checkbox" checked={form.isExempt} onChange={(e)=>setForm({...form,isExempt:e.target.checked})}/></Field></div>
    <Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={action.busy} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/billing-schedules",{...form,amount:Number(form.amount)}),"Programación creada.");if(r)setForm(null);}}>Guardar</button></div></>:null}</Drawer></>;
}

export function Invoices({tick}:ViewProps){
  const{role}=useAccess();const[tab,setTab]=useState<"register"|"recurring"|"pending">("register");const[q,setQ]=useState({search:"",status:"",page:1});const[open,setOpen]=useState<string|null>(null);useQueryParams((p)=>{if(p.get("invoice"))setOpen(p.get("invoice"));});const[compose,setCompose]=useState(false);
  const list=useLoad(()=>financeApi.get<Paged<Invoice&{clientName:string|null}>>(role,`/invoices?page=${q.page}&pageSize=25${q.search?`&search=${encodeURIComponent(q.search)}`:""}${q.status==="OVERDUE"?"&overdue=true":q.status?`&status=${q.status}`:""}`),[role,q,tick]);
  const pending=useLoad(()=>tab==="pending"?financeApi.get<any[]>(role,"/pending-to-invoice"):Promise.resolve([]),[role,tab,tick]);const action=useAction(async()=>{await list.reload();await pending.reload();});
  return <div className="fx-stack">
    <div className="fx-toolbar"><div className="fx-tabs" role="tablist">{([["register","Registro"],["recurring","Recurrentes"],["pending","Pendiente de facturar"]] as const).map(([k,t])=><button key={k} role="tab" aria-selected={tab===k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</div>{canFinance(role,"invoice.create")?<button className="fx-btn primary" onClick={()=>setCompose(true)}><FilePlus2 size={14}/>Nueva factura</button>:null}</div>
    {tab==="register"?<Section eyebrow="REGISTRO DE DOCUMENTOS DE VENTA" title={`${list.data?.total??0} documentos`} actions={<><div className="fx-search"><Search size={13}/><input placeholder="N° o descripción" value={q.search} onChange={(e)=>setQ({...q,search:e.target.value,page:1})}/></div><select value={q.status} onChange={(e)=>setQ({...q,status:e.target.value,page:1})} aria-label="Estado"><option value="">Todos los estados</option>{["DRAFT","PENDING_APPROVAL","READY_TO_ISSUE","ISSUING","ISSUED","PARTIALLY_PAID","PAID","OVERDUE","CREDITED","CANCELLED"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select></>}>
      {list.loading&&!list.data?<Loading/>:list.error?<LoadError error={list.error} retry={()=>void list.reload()}/>:<Register rows={list.data?.items??[]} rowKey={(i)=>i.id} onRow={(i)=>setOpen(i.id)} selected={open} columns={[{key:"n",label:"Documento",render:(i)=><><strong>{docName(i.documentTypeCode)}</strong><small className="block">{i.invoiceNumber}</small></>},{key:"c",label:"Cliente",render:(i)=>i.clientName??i.clientSnapshot.legalName},{key:"e",label:"Emisión",render:(i)=>day(i.issueDate)},{key:"v",label:"Vence",render:(i)=><>{day(i.dueDate)}{i.daysOverdue?<small className="block bad">{i.daysOverdue} días vencida</small>:null}</>},{key:"t",label:"Total",align:"right",render:(i)=><Amount value={i.documentTypeCode===61?-i.totalAmount:i.totalAmount} signed/>},{key:"b",label:"Saldo",align:"right",render:(i)=><Amount value={i.balanceDue} strong/>},{key:"s",label:"Estado",render:(i)=><Pill value={i.effectiveStatus}/>}]} empty="Sin documentos para el filtro"/>}
      {list.data&&list.data.totalPages>1?<div className="fx-pager"><button disabled={q.page<=1} onClick={()=>setQ({...q,page:q.page-1})}>Anterior</button><span>Página {q.page} de {list.data.totalPages}</span><button disabled={q.page>=list.data.totalPages} onClick={()=>setQ({...q,page:q.page+1})}>Siguiente</button></div>:null}
    </Section>:tab==="recurring"?<Recurring/>:<Section eyebrow="DESDE COMERCIAL" title="Ventas ganadas pendientes de facturar" description="El borrador se precarga con las líneas de la cotización aceptada y los datos del Cliente 360.">
      <Feedback error={action.error} notice={action.notice}/>{pending.data?<Register rows={pending.data} rowKey={(p)=>p.saleId} columns={[{key:"c",label:"Cliente",render:(p)=>p.clientName??"—"},{key:"d",label:"Cierre",render:(p)=>day(p.closedAt.slice(0,10))},{key:"a",label:"Venta",align:"right",render:(p)=><Amount value={p.amount}/>},{key:"i",label:"Facturado",align:"right",render:(p)=><Amount value={p.invoiced}/>},{key:"p",label:"Pendiente",align:"right",render:(p)=><Amount value={p.pending} strong/>},{key:"x",label:"",render:(p)=>canFinance(role,"invoice.create")?<button className="fx-btn small" disabled={action.busy} onClick={async()=>{const r=await action.run(()=>financeApi.post<Invoice>(role,`/invoices/from-sale/${p.saleId}`),"Borrador creado.");if(r){setOpen(r.id);setTab("register");}}}>Crear borrador</button>:null}]} empty="No hay ventas pendientes de facturar"/>:<Loading/>}</Section>}
    <InvoiceComposer open={compose} onClose={()=>setCompose(false)} onCreated={(id)=>{setCompose(false);setOpen(id);void list.reload();}}/>
    {open?<InvoiceDetail id={open} onClose={()=>setOpen(null)} onChanged={()=>void list.reload()}/>:null}
  </div>;
}

export function TaxDocuments({tick}:ViewProps){
  const{role}=useAccess();const[tab,setTab]=useState<"issued"|"received"|"rcv">("issued");useQueryParams((p)=>{if(p.get("tab")==="received")setTab("received");});
  const issued=useLoad(()=>tab==="issued"?financeApi.get<Paged<TaxDocument>>(role,"/tax-documents?pageSize=50"):Promise.resolve(null),[role,tab,tick]);const received=useLoad(()=>tab==="received"?financeApi.get<Paged<any>>(role,"/received-documents?pageSize=50"):Promise.resolve(null),[role,tab,tick]);
  const[rcvPeriod,setRcvPeriod]=useState(todayIso().slice(0,7));const[register,setRegister]=useState<"COMPRAS"|"VENTAS">("COMPRAS");const rcv=useLoad(()=>tab==="rcv"?financeApi.get<any>(role,`/rcv/compare?registerType=${register}&period=${rcvPeriod}`):Promise.resolve(null),[role,tab,rcvPeriod,register,tick]);
  const action=useAction(async()=>{await issued.reload();await received.reload();await rcv.reload();});const[classify,setClassify]=useState<any>(null);const[detail,setDetail]=useState<string|null>(null);
  const doc=useLoad(()=>detail?financeApi.get<any>(role,`/tax-documents/${detail}`):Promise.resolve(null),[role,detail]);
  return <div className="fx-stack">
    <div className="fx-toolbar"><div className="fx-tabs" role="tablist">{([["issued","Emitidos"],["received","Recibidos"],["rcv","Conciliación RCV"]] as const).map(([k,t])=><button key={k} role="tab" aria-selected={tab===k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</div><Stamp kind="info">Sólo servicios oficiales del SII · sin scraping</Stamp></div>
    <Feedback error={action.error} notice={action.notice}/>
    {tab==="issued"?<Section eyebrow="DTE EMITIDOS" title="Estado tributario" description="DRAFT → VALIDATED → SIGNED → SUBMITTED → RECEIVED_BY_SII → ACCEPTED / REJECTED. Un rechazo nunca deja la factura emitida.">
      {issued.data?<Register rows={issued.data.items} rowKey={(d)=>d.id} onRow={(d)=>setDetail(d.id)} columns={[{key:"t",label:"Tipo",render:(d)=>`${d.documentTypeCode} · ${docName(d.documentTypeCode)}`},{key:"f",label:"Folio",render:(d)=>d.folio??"—"},{key:"r",label:"Receptor",render:(d)=>d.receiverRut??"—"},{key:"e",label:"Emisión",render:(d)=>day(d.issueDate)},{key:"p",label:"Proveedor",render:(d)=><>{label(d.provider)}<small className="block">{label(d.environment)}</small></>},{key:"tr",label:"Track ID",render:(d)=>d.trackId??"—"},{key:"a",label:"Total",align:"right",render:(d)=><Amount value={d.totalAmount}/>},{key:"s",label:"Estado SII",render:(d)=><Pill value={d.status}/>}]} empty="Aún no hay documentos emitidos"/>:<Loading/>}
    </Section>:null}
    {tab==="received"?<Section eyebrow="BANDEJA DE COMPRAS" title="DTE recibidos" description="Importa XML (DTE o EnvioDTE). Se validan totales, receptor y duplicados. El crédito fiscal se clasifica explícitamente; nunca se presume recuperable." actions={canFinance(role,"dte.manage")||canFinance(role,"expense.create")?<FileInput accept=".xml" label="Importar XML" onFile={(f)=>{if(f)void action.run(async()=>{const r=await financeApi.post<any>(role,"/received-documents/import",{file:f});action.setNotice(r.results.map((x:any)=>`Folio ${x.folio}: ${x.result==="CREATED"?"importado":x.result==="DUPLICATE"?"duplicado (ya existía)":"rechazado"}${x.errors?.length?` (${x.errors.join("; ")})`:""}`).join(" · "));return r;});}}/>:null}>
      {received.data?<Register rows={received.data.items} rowKey={(d)=>d.id} columns={[{key:"e",label:"Emisor",render:(d)=><><strong>{d.issuerName}</strong><small className="block">{d.issuerRut}</small></>},{key:"t",label:"Tipo / folio",render:(d)=>`${d.documentTypeCode} · ${d.folio}`},{key:"f",label:"Fecha",render:(d)=>day(d.issueDate)},{key:"n",label:"Neto",align:"right",render:(d)=><Amount value={d.netAmount}/>},{key:"i",label:"IVA",align:"right",render:(d)=><Amount value={d.taxAmount}/>},{key:"c",label:"Crédito fiscal",render:(d)=>d.taxCreditClassification==="PENDING_REVIEW"?<Pill value="PENDING_REVIEW" text="Por clasificar"/>:<><Pill value={d.taxCreditEligible?"OK":"NOT_APPLICABLE"} text={label(d.taxCreditClassification)}/><small className="block">{money(d.taxCreditEligibleAmount)}</small></>},{key:"v",label:"Validación",render:(d)=>d.validationErrors?.length?<Pill value="ATTENTION" text={`${d.validationErrors.length} obs.`}/>:<Pill value="OK" text="Sin obs."/>},{key:"x",label:"",render:(d)=><div className="fx-row-actions">{canFinance(role,"tax.review")?<button className="fx-btn small" onClick={()=>setClassify({id:d.id,taxAmount:d.taxAmount,classification:"DEL_GIRO",eligible:true,eligibleAmount:"",reason:""})}>Clasificar</button>:null}{!d.expenseId&&canFinance(role,"expense.create")?<Link className="fx-btn small ghost" href={`/finance/expenses?fromReceived=${d.id}`}>Crear gasto</Link>:null}</div>}]} empty="Sin documentos recibidos"/>:<Loading/>}
    </Section>:null}
    {tab==="rcv"?<Section eyebrow="REGISTRO DE COMPRAS Y VENTAS" title="Conciliación RCV" description="Importa el CSV oficial descargado desde sii.cl (no se automatiza el portal) y compáralo con Zyteron." actions={<><select value={register} onChange={(e)=>setRegister(e.target.value as "COMPRAS")}><option value="COMPRAS">Compras</option><option value="VENTAS">Ventas</option></select><input type="month" value={rcvPeriod} onChange={(e)=>setRcvPeriod(e.target.value)}/>{canFinance(role,"tax.review")?<FileInput accept=".csv,.xlsx" label="Importar RCV" onFile={(f)=>{if(f)void action.run(()=>financeApi.post(role,"/rcv/import",{registerType:register,periodKey:rcvPeriod,file:f}),"RCV importado y comparado.");}}/>:null}</>}>
      {rcv.data?<>{rcv.data.notice?<p className="fx-hint">{rcv.data.notice}</p>:null}<div className="fx-chips">{Object.entries(rcv.data.summary as Record<string,number>).map(([k,v])=><span key={k} className={`fx-chip ${k==="MATCHED"?"good":v?"warn":""}`}>{label(k)} <strong>{v}</strong></span>)}</div>
        <Register rows={rcv.data.rows} rowKey={(r:any)=>r.key} columns={[{key:"r",label:"Contraparte",render:(r:any)=><>{r.counterpartName??"—"}<small className="block">{r.counterpartRut}</small></>},{key:"d",label:"Tipo / folio",render:(r:any)=>`${r.documentTypeCode} · ${r.folio}`},{key:"s",label:"Total SII",align:"right",render:(r:any)=><Amount value={r.siiTotal}/>},{key:"l",label:"Total Zyteron",align:"right",render:(r:any)=><Amount value={r.localTotal}/>},{key:"st",label:"Resultado",render:(r:any)=><><Pill value={r.status}/><small className="block">{r.detail}</small></>}]} empty="Sin filas para comparar"/></>:<Loading/>}
    </Section>:null}
    <Drawer open={Boolean(classify)} title="Clasificar crédito fiscal" subtitle="Decisión explícita con fundamento; queda auditada." onClose={()=>setClassify(null)}>{classify?<><div className="fx-form"><Field label="Clasificación" span={2}><select value={classify.classification} onChange={(e)=>setClassify({...classify,classification:e.target.value})}>{["DEL_GIRO","ACTIVO_FIJO","USO_COMUN","SUPERMERCADO","BIENES_RAICES","NO_RECUPERABLE","NO_CORRESPONDE"].map((c)=><option key={c} value={c}>{label(c)}</option>)}</select></Field><Field label="¿IVA es crédito fiscal?"><select value={String(classify.eligible)} onChange={(e)=>setClassify({...classify,eligible:e.target.value==="true"})}><option value="true">Sí</option><option value="false">No</option></select></Field>{classify.eligible?<Field label={`Monto de crédito (IVA ${money(classify.taxAmount)})`} hint="Vacío = 100% del IVA; uso común exige monto proporcional"><input inputMode="numeric" value={classify.eligibleAmount} onChange={(e)=>setClassify({...classify,eligibleAmount:e.target.value.replace(/[^\d.]/g,"")})}/></Field>:null}<Field label="Fundamento" span={3}><textarea rows={2} value={classify.reason} onChange={(e)=>setClassify({...classify,reason:e.target.value})}/></Field></div><div className="fx-actions end"><button className="fx-btn primary" disabled={!classify.reason||action.busy} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/received-documents/${classify.id}/classify`,{classification:classify.classification,eligible:classify.eligible,eligibleAmount:classify.eligibleAmount===""?undefined:Number(classify.eligibleAmount),reason:classify.reason}),"Clasificación registrada.");if(r)setClassify(null);}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(detail)} title="Documento tributario" onClose={()=>setDetail(null)} wide>{doc.data?<><KeyValue items={[["Tipo",`${doc.data.documentTypeCode} · ${docName(doc.data.documentTypeCode)}`],["Folio",doc.data.folio??"—"],["Estado",<Pill key="s" value={doc.data.status}/>],["Mensaje",doc.data.statusMessage??"—"],["Track ID",doc.data.trackId??"—"],["XML firmado SHA-256",doc.data.xmlSignedSha256?`${doc.data.xmlSignedSha256.slice(0,24)}…`:"—"]]}/>
      <div className="fx-actions">{["SUBMITTED","RECEIVED_BY_SII"].includes(doc.data.status)&&!String(doc.data.statusMessage).startsWith("Emitido fuera")?<button className="fx-btn" disabled={action.busy} onClick={()=>void action.run(async()=>{await financeApi.post(role,`/tax-documents/${detail}/refresh`);await doc.reload();},"Estado consultado al SII.")}><RefreshCw size={14}/>Consultar estado SII</button>:null}{doc.data.xmlSignedPath?<button className="fx-btn ghost" onClick={()=>void action.run(()=>financeApi.download(role,`/tax-documents/${detail}/xml`))}><Download size={14}/>XML</button>:null}{doc.data.pdfPath?<button className="fx-btn ghost" onClick={()=>void action.run(()=>financeApi.download(role,`/tax-documents/${detail}/pdf`))}><Download size={14}/>PDF</button>:<small className="fx-hint">PDF sólo con folio y timbre real.</small>}</div>
      <ol className="fx-timeline">{doc.data.events.map((e:any)=><li key={e.id}><time>{moment(e.occurredAt)}</time><span><Pill value={e.status}/> {e.message}</span></li>)}</ol></>:<Loading/>}</Drawer>
  </div>;
}

export function Receivables({tick}:ViewProps){
  const{role}=useAccess();const aging=useLoad(()=>financeApi.get<any>(role,"/receivables/aging"),[role,tick]);const open=useLoad(()=>financeApi.get<Array<Invoice&{clientName:string|null}>>(role,"/receivables"),[role,tick]);const credits=useLoad(()=>financeApi.get<Array<Payment&{clientName:string|null}>>(role,"/credit-balances"),[role,tick]);
  if(aging.error)return <LoadError error={aging.error} retry={()=>void aging.reload()}/>;
  return <div className="fx-two"><Section eyebrow="ANTIGÜEDAD DESDE VENCIMIENTO" title={money(aging.data?.total)} description={`Al ${day(aging.data?.asOf)}`}>{aging.data?<><AgingBar buckets={aging.data.buckets}/><Register rows={aging.data.byParty} rowKey={(p:any)=>p.partyId} columns={[{key:"c",label:"Cliente",render:(p:any)=>p.partyName},{key:"o",label:"Mayor atraso",render:(p:any)=>p.oldestDays?`${p.oldestDays} días`:"Al día"},{key:"t",label:"Saldo",align:"right",render:(p:any)=><Amount value={p.total} strong/>}]}/></>:<Loading/>}</Section>
    <Section eyebrow="DOCUMENTOS ABIERTOS" title={`${open.data?.length??0} documentos`}>{open.data?<Register rows={open.data} rowKey={(i)=>i.id} columns={[{key:"c",label:"Cliente",render:(i)=>i.clientName??i.clientSnapshot.legalName},{key:"n",label:"Documento",render:(i)=><Link href={`/finance/invoices?invoice=${i.id}`}>{i.invoiceNumber}</Link>},{key:"v",label:"Vence",render:(i)=>day(i.dueDate)},{key:"s",label:"Estado",render:(i)=><Pill value={i.effectiveStatus}/>},{key:"b",label:"Saldo",align:"right",render:(i)=><Amount value={i.balanceDue}/>}]} totals={["Total","","","",<Amount key="t" value={open.data.reduce((t,i)=>t+i.balanceDue,0)} strong/>]}/>:<Loading/>}</Section>
    <Section eyebrow="SALDOS A FAVOR" title="Pagos sin aplicar" description="Sobrepagos o cobros aún no asignados a documentos.">{credits.data?<Register rows={credits.data} rowKey={(p)=>p.id} columns={[{key:"c",label:"Cliente",render:(p)=>p.clientName??"—"},{key:"r",label:"Pago",render:(p)=><Link href={`/finance/payments?payment=${p.id}`}>{p.paymentReference}</Link>},{key:"d",label:"Recibido",render:(p)=>moment(p.receivedAt)},{key:"u",label:"Sin aplicar",align:"right",render:(p)=><Amount value={p.unappliedAmount} strong/>}]} empty="Sin saldos a favor"/>:<Loading/>}</Section></div>;
}

export function Collections({tick}:ViewProps){
  const{role}=useAccess();const center=useLoad(()=>financeApi.get<any>(role,"/collections"),[role,tick]);const promises=useLoad(()=>financeApi.get<any[]>(role,"/collections/promises?status=OPEN"),[role,tick]);const rules=useLoad(()=>financeApi.get<any[]>(role,"/collections/reminder-rules"),[role]);
  const[client,setClient]=useState<any>(null);const activities=useLoad(()=>client?financeApi.get<any[]>(role,`/collections/activities?clientId=${client.clientId}`):Promise.resolve([]),[role,client?.clientId]);const action=useAction(async()=>{await center.reload();await promises.reload();await activities.reload();await rules.reload();});
  const[activity,setActivity]=useState({activityType:"CALL",outcome:"",notes:""});const[promise,setPromise]=useState({amount:"",promisedDate:"",invoiceId:""});const manage=canFinance(role,"collection.manage");
  if(center.error)return <LoadError error={center.error} retry={()=>void center.reload()}/>;if(!center.data)return <Loading/>;const c=center.data;
  return <div className="fx-stack"><section className="fx-ticker small"><div><small>Saldo</small><strong>{money(c.totals.balance)}</strong></div><div className="tone-warning"><small>Vencido</small><strong>{money(c.totals.overdue)}</strong></div><div><small>Clientes con saldo</small><strong>{c.totals.clients}</strong></div><div><small>Con promesa vigente</small><strong>{c.totals.withPromise}</strong></div></section>
    <div className="fx-two"><Section eyebrow="PRIORIDAD DE COBRANZA" title="Clientes" description="Ordenados por días de atraso y monto vencido.">
      <ul className="fx-collect">{c.clients.map((x:any)=><li key={x.clientId} className={client?.clientId===x.clientId?"selected":""}><button onClick={()=>setClient(x)}><div><strong>{x.clientName}</strong><small>{x.invoices.length} doc. · {x.oldestDays?`${x.oldestDays} días de atraso`:"al día"}{x.openPromise?` · promesa ${day(x.openPromise.promisedDate)}`:""}</small></div><span><Amount value={x.overdue} strong/><small>de {money(x.balance)}</small></span></button></li>)}{!c.clients.length?<li className="muted">Sin saldos por cobrar.</li>:null}</ul></Section>
    <Section eyebrow={client?"GESTIÓN":"PROMESAS VIGENTES"} title={client?client.clientName:`${promises.data?.length??0} promesas`}>
      {client?<><Register rows={client.invoices} rowKey={(i:any)=>i.id} columns={[{key:"n",label:"Documento",render:(i:any)=>i.invoiceNumber},{key:"v",label:"Vence",render:(i:any)=>day(i.dueDate)},{key:"s",label:"Estado",render:(i:any)=><Pill value={i.effectiveStatus}/>},{key:"b",label:"Saldo",align:"right",render:(i:any)=><Amount value={i.balanceDue}/>}]}/>
        {manage?<div className="fx-form boxed"><Field label="Gestión"><select value={activity.activityType} onChange={(e)=>setActivity({...activity,activityType:e.target.value})}>{["CALL","EMAIL","WHATSAPP","MEETING","NOTE"].map((t)=><option key={t} value={t}>{label(t)}</option>)}</select></Field><Field label="Resultado" span={2}><input value={activity.outcome} onChange={(e)=>setActivity({...activity,outcome:e.target.value})}/></Field><Field label="Notas" span={3}><textarea rows={2} value={activity.notes} onChange={(e)=>setActivity({...activity,notes:e.target.value})}/></Field><div className="fx-actions"><button className="fx-btn" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.post(role,"/collections/activities",{clientId:client.clientId,...activity}),"Gestión registrada.")}>Registrar gestión</button></div>
          <Field label="Promesa: monto"><input inputMode="numeric" value={promise.amount} onChange={(e)=>setPromise({...promise,amount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Fecha comprometida"><DateInput value={promise.promisedDate} onChange={(v)=>setPromise({...promise,promisedDate:v})}/></Field><Field label="Documento"><select value={promise.invoiceId} onChange={(e)=>setPromise({...promise,invoiceId:e.target.value})}><option value="">Saldo general</option>{client.invoices.map((i:any)=><option key={i.id} value={i.id}>{i.invoiceNumber}</option>)}</select></Field><div className="fx-actions"><button className="fx-btn primary" disabled={!promise.amount||!promise.promisedDate||action.busy} onClick={()=>void action.run(()=>financeApi.post(role,"/collections/promises",{clientId:client.clientId,amount:Number(promise.amount),promisedDate:promise.promisedDate,invoiceId:promise.invoiceId||undefined}),"Promesa registrada.")}>Registrar promesa</button></div></div>:null}
        <ol className="fx-timeline">{activities.data?.map((a)=><li key={a.id}><time>{moment(a.occurredAt)}</time><span><strong>{label(a.activityType)}</strong> {a.outcome??""} {a.notes?<small className="block">{a.notes}</small>:null}</span></li>)}</ol></>
      :<ul className="fx-queue">{promises.data?.map((p)=><li key={p.id}><div><strong>{p.clientName}</strong><small>Comprometido para el {day(p.promisedDate)}</small></div><Amount value={p.amount}/>{manage?<div className="fx-row-actions"><button className="fx-btn small" onClick={()=>void action.run(()=>financeApi.post(role,`/collections/promises/${p.id}/resolve`,{status:"KEPT"}),"Marcada como cumplida.")}>Cumplida</button><button className="fx-btn small ghost" onClick={()=>void action.run(()=>financeApi.post(role,`/collections/promises/${p.id}/resolve`,{status:"BROKEN"}),"Marcada como incumplida.")}>Incumplida</button></div>:null}</li>)}{!promises.data?.length?<li className="muted">Sin promesas abiertas. Las vencidas se evalúan con pagos aplicados reales.</li>:null}</ul>}
      <Feedback error={action.error} notice={action.notice}/></Section></div>
    <Section eyebrow="RECORDATORIOS" title="Reglas configurables" description="Cada regla envía como máximo un correo por documento, nunca con promesa vigente, y sólo si Resend está configurado. Sin proveedor quedan registrados como «no configurado».">
      <Register rows={rules.data??[]} rowKey={(r:any)=>r.id} columns={[{key:"o",label:"Momento",render:(r:any)=>r.offsetDays===0?"Día de vencimiento":r.offsetDays<0?`${-r.offsetDays} días antes`:`${r.offsetDays} días después`},{key:"s",label:"Asunto",render:(r:any)=>r.subjectTemplate},{key:"a",label:"Estado",render:(r:any)=>manage?<button className={`fx-toggle${r.active?" on":""}`} onClick={()=>void action.run(()=>financeApi.patch(role,`/collections/reminder-rules/${r.id}`,{active:!r.active}),"Regla actualizada.")}>{r.active?"Activa":"Inactiva"}</button>:<Pill value={r.active?"ACTIVE":"INACTIVE"}/>}]}/>
    </Section></div>;
}

export function Payments({tick}:ViewProps){
  const{role}=useAccess();const[q,setQ]=useState({status:"",page:1});const[open,setOpen]=useState<string|null>(null);useQueryParams((p)=>{if(p.get("payment"))setOpen(p.get("payment"));});const[record,setRecord]=useState(false);
  const list=useLoad(()=>financeApi.get<Paged<Payment&{clientName:string|null}>>(role,`/payments?page=${q.page}&pageSize=25${q.status?`&status=${q.status}`:""}`),[role,q,tick]);
  return <div className="fx-stack"><Section eyebrow="COBROS" title={`${list.data?.total??0} pagos`} description="Un pago nace «por verificar» con comprobante o movimiento de cartola; sólo verificado se aplica y contabiliza. La pantalla de éxito del medio de pago no confirma un cobro." actions={<><select value={q.status} onChange={(e)=>setQ({status:e.target.value,page:1})}><option value="">Todos</option>{["PENDING_VERIFICATION","PENDING","CONFIRMED","PARTIALLY_REFUNDED","REFUNDED","FAILED","DISPUTED","CHARGEBACK"].map((s)=><option key={s} value={s}>{label(s)}</option>)}</select>{canFinance(role,"payment.record")?<button className="fx-btn primary" onClick={()=>setRecord(true)}><Receipt size={14}/>Registrar pago</button>:null}</>}>
    {list.data?<Register rows={list.data.items} rowKey={(p)=>p.id} onRow={(p)=>setOpen(p.id)} selected={open} columns={[{key:"r",label:"Referencia",render:(p)=><><strong>{p.paymentReference}</strong><small className="block">{label(p.provider)}</small></>},{key:"c",label:"Cliente",render:(p)=>p.clientName??"—"},{key:"d",label:"Recibido",render:(p)=>moment(p.receivedAt)},{key:"g",label:"Bruto",align:"right",render:(p)=><Amount value={p.grossAmount}/>},{key:"f",label:"Comisión",align:"right",render:(p)=><Amount value={p.feeAmount}/>},{key:"u",label:"Sin aplicar",align:"right",render:(p)=><Amount value={p.unappliedAmount}/>},{key:"s",label:"Estado",render:(p)=><Pill value={p.status}/>}]} empty="Sin pagos registrados"/>:list.error?<LoadError error={list.error} retry={()=>void list.reload()}/>:<Loading/>}</Section>
    <RecordPayment open={record} onClose={()=>setRecord(false)} onDone={(id)=>{setRecord(false);setOpen(id);void list.reload();}}/>{open?<PaymentDetail id={open} onClose={()=>setOpen(null)} onChanged={()=>void list.reload()}/>:null}</div>;
}
function RecordPayment({open,onClose,onDone}:{open:boolean;onClose:()=>void;onDone:(id:string)=>void}){
  const{role}=useAccess();const banks=useLoad(()=>open?financeApi.get<any[]>(role,"/bank-accounts"):Promise.resolve([]),[role,open]);const cash=useLoad(()=>open?financeApi.get<any[]>(role,"/cash-accounts"):Promise.resolve([]),[role,open]);
  const[f,setF]=useState<any>({clientId:"",provider:"BANK_TRANSFER",grossAmount:"",receivedAt:todayIso(),bankAccountId:"",cashAccountId:"",reference:"",notes:"",evidence:null});const action=useAction();const key=useMemo(()=>crypto.randomUUID(),[open]);
  return <Drawer open={open} title="Registrar pago recibido" subtitle="Queda por verificar hasta que otra revisión lo confirme con evidencia." onClose={onClose}><div className="fx-form"><Field label="Cliente" span={3}><ClientPicker value={f.clientId} onChange={(id)=>setF({...f,clientId:id})}/></Field><Field label="Medio"><select value={f.provider} onChange={(e)=>setF({...f,provider:e.target.value})}><option value="BANK_TRANSFER">Transferencia / depósito</option><option value="CASH">Efectivo</option><option value="OTHER">Otro</option></select></Field><Field label="Monto"><input inputMode="numeric" value={f.grossAmount} onChange={(e)=>setF({...f,grossAmount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Fecha de recepción"><DateInput value={f.receivedAt} onChange={(v)=>setF({...f,receivedAt:v})}/></Field>
    {f.provider==="CASH"?<Field label="Caja" span={3}><select value={f.cashAccountId} onChange={(e)=>setF({...f,cashAccountId:e.target.value})}><option value="">Selecciona caja…</option>{cash.data?.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>:<Field label="Cuenta de destino" span={3}><select value={f.bankAccountId} onChange={(e)=>setF({...f,bankAccountId:e.target.value})}><option value="">Selecciona cuenta…</option>{banks.data?.map((b)=><option key={b.id} value={b.id}>{b.bankName} ····{b.accountNumberLast4}</option>)}</select></Field>}
    <Field label="N° de operación"><input value={f.reference} onChange={(e)=>setF({...f,reference:e.target.value})}/></Field><Field label="Comprobante" span={2}><FileInput accept=".pdf,.png,.jpg,.jpeg" file={f.evidence} onFile={(file)=>setF({...f,evidence:file})}/></Field><Field label="Notas" span={3}><textarea rows={2} value={f.notes} onChange={(e)=>setF({...f,notes:e.target.value})}/></Field></div>
    <p className="fx-hint">No se registran números de tarjeta ni CVV. Si el abono ya está en la cartola, regístralo desde Conciliación (el movimiento es la evidencia).</p><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={action.busy||!f.clientId||!f.grossAmount||!f.evidence} onClick={async()=>{const r=await action.run(()=>financeApi.post<Payment>(role,"/payments",{...f,grossAmount:Number(f.grossAmount),bankAccountId:f.bankAccountId||null,cashAccountId:f.cashAccountId||null},{"idempotency-key":key}));if(r)onDone(r.id);}}><CircleDollarSign size={14}/>Registrar</button></div></Drawer>;
}
function PaymentDetail({id,onClose,onChanged}:{id:string;onClose:()=>void;onChanged:()=>void}){
  const{role}=useAccess();const{data,reload,error}=useLoad(()=>financeApi.get<any>(role,`/payments/${id}`),[role,id]);const action=useAction(async()=>{await reload();onChanged();});const[alloc,setAlloc]=useState<Array<{invoiceId:string;invoiceNumber:string;balanceDue:number;amount:string}>>([]);const[dialog,setDialog]=useState<null|"reject"|"refund"|{reverse:string}>(null);const[refundAmount,setRefundAmount]=useState("");const[refundEvidence,setRefundEvidence]=useState<UploadedFile|null>(null);
  if(error)return <Drawer open title="Pago" onClose={onClose}><Feedback error={error}/></Drawer>;if(!data)return <Drawer open title="Pago" onClose={onClose}><Loading/></Drawer>;const p=data;
  return <Drawer open title={`Pago ${p.paymentReference}`} subtitle={<>{p.clientName} · <Pill value={p.status}/></>} onClose={onClose} wide>
    <KeyValue items={[["Medio",`${label(p.provider)} · ${label(p.method)}`],["Recibido",moment(p.receivedAt)],["Bruto / comisión / neto",`${money(p.grossAmount)} / ${money(p.feeAmount)} / ${money(p.netAmount)}`],["Aplicado / devuelto / sin aplicar",`${money(p.allocatedAmount)} / ${money(p.refundedAmount)} / ${money(p.unappliedAmount)}`],["Evidencia",p.evidencePath?"Comprobante adjunto":p.bankTransactionId?"Movimiento de cartola":"—"],["Confirmado",p.confirmedAt?moment(p.confirmedAt):"Pendiente"]]}/>
    <Feedback error={action.error} notice={action.notice}/>
    <div className="fx-actions">{p.status==="PENDING_VERIFICATION"&&canFinance(role,"payment.record")&&p.provider!=="MERCADOPAGO"?<><button className="fx-btn primary" disabled={action.busy} onClick={()=>void action.run(()=>financeApi.post(role,`/payments/${id}/confirm`,{}),"Pago verificado y confirmado.")}><BadgeCheck size={14}/>Verificar y confirmar</button><button className="fx-btn ghost" onClick={()=>setDialog("reject")}>Rechazar</button></>:null}
      {["CONFIRMED","PARTIALLY_REFUNDED"].includes(p.status)&&p.unappliedAmount>0&&canFinance(role,"payment.allocate")?<button className="fx-btn" disabled={action.busy} onClick={async()=>{const s=await action.run(()=>financeApi.get<any>(role,`/payments/${id}/allocation-suggestion`));if(s)setAlloc(s.suggestions.map((x:any)=>({invoiceId:x.invoiceId,invoiceNumber:x.invoiceNumber,balanceDue:x.balanceDue,amount:String(x.amount)})));}}><Wand2 size={14}/>Sugerir aplicación (FIFO)</button>:null}
      {["CONFIRMED","PARTIALLY_REFUNDED"].includes(p.status)&&p.unappliedAmount>0&&canFinance(role,"payment.refund")?<button className="fx-btn ghost" onClick={()=>{setRefundAmount(String(p.unappliedAmount));setDialog("refund");}}>Devolver saldo</button>:null}</div>
    {alloc.length?<div className="fx-form boxed"><p className="fx-hint">Revisa los montos antes de aplicar: nada se aplica sin tu confirmación.</p><table className="fx-doc-lines"><tbody>{alloc.map((a,i)=><tr key={a.invoiceId}><td>{a.invoiceNumber}</td><td className="r">saldo {money(a.balanceDue)}</td><td><input inputMode="numeric" value={a.amount} onChange={(e)=>setAlloc(alloc.map((x,n)=>n===i?{...x,amount:e.target.value.replace(/\D/g,"")}:x))}/></td></tr>)}</tbody></table><div className="fx-actions"><button className="fx-btn primary" disabled={action.busy} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/payments/${id}/allocate`,{allocations:alloc.filter((a)=>Number(a.amount)>0).map((a)=>({invoiceId:a.invoiceId,amount:Number(a.amount)}))}),"Pago aplicado.");if(r)setAlloc([]);}}>Aplicar</button></div></div>:null}
    <Section eyebrow="APLICACIONES" title="Documentos pagados"><Register rows={p.allocations} rowKey={(a:any)=>a.id} columns={[{key:"i",label:"Documento",render:(a:any)=>a.invoice?.invoiceNumber??"—"},{key:"d",label:"Fecha",render:(a:any)=>moment(a.allocatedAt)},{key:"m",label:"Monto",align:"right",render:(a:any)=><Amount value={a.amount}/>},{key:"s",label:"",render:(a:any)=>a.reversedAt?<Pill value="REVERSED"/>:canFinance(role,"payment.allocate")?<button className="fx-btn small ghost" onClick={()=>setDialog({reverse:a.id})}>Revertir</button>:null}]} empty="Sin aplicaciones"/></Section>
    {p.refunds.length?<Section eyebrow="DEVOLUCIONES" title="Solicitudes"><ul className="fx-queue">{p.refunds.map((r:any)=><li key={r.id}><div><strong>{money(r.amount)}</strong><small>{r.reason}</small></div><Pill value={r.status}/>{r.status==="REQUESTED"&&canFinance(role,"payment.refund")?<div className="fx-row-actions"><FileInput label="Comprobante" file={refundEvidence} onFile={setRefundEvidence}/><button className="fx-btn small" disabled={!refundEvidence} onClick={()=>void action.run(()=>financeApi.post(role,`/refunds/${r.id}/complete`,{evidence:refundEvidence}),"Devolución completada.")}>Completar</button></div>:null}</li>)}</ul></Section>:null}
    <ReasonDialog open={dialog!==null} title={dialog==="reject"?"Rechazar pago":dialog==="refund"?"Devolver saldo no aplicado":"Revertir aplicación"} extra={dialog==="refund"?<Field label="Monto a devolver"><input inputMode="numeric" value={refundAmount} onChange={(e)=>setRefundAmount(e.target.value.replace(/\D/g,""))}/></Field>:undefined} onCancel={()=>setDialog(null)} onConfirm={(reason)=>{const d=dialog;setDialog(null);if(d==="reject")void action.run(()=>financeApi.post(role,`/payments/${id}/reject`,{reason}),"Pago rechazado.");else if(d==="refund")void action.run(()=>financeApi.post(role,`/payments/${id}/refund`,{amount:Number(refundAmount),reason}),"Devolución solicitada.");else if(d&&typeof d==="object")void action.run(()=>financeApi.post(role,`/allocations/${d.reverse}/reverse`,{reason}),"Aplicación revertida.");}}/>
  </Drawer>;
}
