"use client";

import { useState } from "react";
import type { BankTransaction, LedgerAccount, ReconciliationSuggestion, StatementPreview } from "@zyteron/contracts";
import { CheckCheck, FileSpreadsheet, GitMerge, Landmark, Plus, Undo2, Wallet } from "lucide-react";
import { useAccess } from "@/components/access-context";
import { financeApi, type UploadedFile } from "@/lib/finance-api";
import { canFinance, day, label, moment, money } from "@/lib/finance-format";
import { Amount, DateInput, Drawer, Empty, Feedback, Field, FileInput, LoadError, Loading, Pill, ReasonDialog, Register, Section, Stamp, useAction, useLoad } from "./fx-ui";
import { ClientPicker } from "./views-revenue";
import type { ViewProps } from "./finance-workspace";

export function Banks({tick}:ViewProps){
  const{role}=useAccess();const banks=useLoad(()=>financeApi.get<any[]>(role,"/bank-accounts"),[role,tick]);const cash=useLoad(()=>financeApi.get<any[]>(role,"/cash-accounts"),[role,tick]);const imports=useLoad(()=>financeApi.get<any[]>(role,"/bank-statements"),[role,tick]);
  const ledger=useLoad(()=>canFinance(role,"accounting.view")?financeApi.get<LedgerAccount[]>(role,"/accounts"):Promise.resolve([]),[role]);const action=useAction(async()=>{await banks.reload();await cash.reload();await imports.reload();});
  const[accountForm,setAccountForm]=useState<any>(null);const[cashForm,setCashForm]=useState<any>(null);const[movement,setMovement]=useState<any>(null);
  const[stmt,setStmt]=useState<{bankAccountId:string;file:UploadedFile|null;mapping:Record<string,string|null>;preview:StatementPreview|null}>({bankAccountId:"",file:null,mapping:{},preview:null});
  const cashLedger=(ledger.data??[]).filter((a)=>a.isCash&&a.allowsPosting&&a.active);
  const preview=async(mapping=stmt.mapping)=>{const p=await action.run(()=>financeApi.post<StatementPreview>(role,"/bank-statements/preview",{bankAccountId:stmt.bankAccountId,file:stmt.file,mapping}));if(p)setStmt((s)=>({...s,preview:p,mapping:p.mapping}));};
  return <div className="fx-stack">
    <div className="fx-two"><Section eyebrow="CUENTAS BANCARIAS" title={`${banks.data?.length??0} cuentas`} description="Sólo se guardan los últimos 4 dígitos; sin credenciales bancarias." actions={canFinance(role,"bank.reconcile")&&cashLedger.length?<button className="fx-btn primary" onClick={()=>setAccountForm({bankName:"",accountType:"CHECKING",accountNumber:"",ledgerAccountId:cashLedger[0]?.id??""})}><Plus size={14}/>Cuenta</button>:null}>
      {banks.data?<ul className="fx-accounts big">{banks.data.map((b)=>{const diff=b.statementBalance===null?null:b.bookBalance-b.statementBalance;return <li key={b.id}><Landmark size={16}/><div><strong>{b.bankName} ····{b.accountNumberLast4}</strong><small>{label(b.accountType)} · {b.pendingTransactions} movimientos por conciliar</small></div><div className="fx-balances"><span>Libro <Amount value={b.bookBalance}/></span><span>Cartola {b.statementBalance===null?"—":<Amount value={b.statementBalance}/>}<small>{b.statementDate?`al ${day(b.statementDate)}`:""}</small></span>{diff!==null&&diff!==0?<Stamp kind="warn">Diferencia {money(diff)}</Stamp>:diff===0?<Stamp kind="good">Cuadra</Stamp>:null}</div></li>;})}{!banks.data.length?<li className="muted">Sin cuentas bancarias registradas.</li>:null}</ul>:banks.error?<LoadError error={banks.error} retry={()=>void banks.reload()}/>:<Loading/>}</Section>
    <Section eyebrow="CAJAS" title={`${cash.data?.length??0} cajas`} actions={canFinance(role,"bank.reconcile")&&cashLedger.length?<button className="fx-btn ghost" onClick={()=>setCashForm({name:"",ledgerAccountId:cashLedger.find((a)=>a.code==="1.1.01")?.id??cashLedger[0]?.id})}><Plus size={14}/>Caja</button>:null}>
      {cash.data?<ul className="fx-accounts big">{cash.data.map((c)=><li key={c.id}><Wallet size={16}/><div><strong>{c.name}</strong><small>Movimientos registrados {money(c.movementsBalance)}</small></div><div className="fx-balances"><span>Libro <Amount value={c.bookBalance}/></span>{canFinance(role,"bank.reconcile")?<button className="fx-btn small" onClick={()=>setMovement({cashAccountId:c.id,direction:"OUT",amount:"",movementDate:"",description:"",evidence:null})}>Movimiento</button>:null}</div></li>)}{!cash.data.length?<li className="muted">Sin cajas.</li>:null}</ul>:<Loading/>}</Section></div>
    {canFinance(role,"bank.import")?<Section eyebrow="IMPORTAR CARTOLA" title="CSV o XLSX del banco" description="Vista previa, mapeo de columnas, validación y detección de duplicados con hash determinístico antes de importar.">
      <div className="fx-form"><Field label="Cuenta"><select value={stmt.bankAccountId} onChange={(e)=>setStmt({...stmt,bankAccountId:e.target.value,preview:null})}><option value="">Selecciona cuenta…</option>{banks.data?.map((b)=><option key={b.id} value={b.id}>{b.bankName} ····{b.accountNumberLast4}</option>)}</select></Field><Field label="Archivo" span={2}><FileInput accept=".csv,.xlsx" file={stmt.file} onFile={(f)=>setStmt({...stmt,file:f,preview:null,mapping:{}})}/></Field></div>
      <div className="fx-actions"><button className="fx-btn" disabled={!stmt.bankAccountId||!stmt.file||action.busy} onClick={()=>void preview()}><FileSpreadsheet size={14}/>Vista previa</button></div><Feedback error={action.error} notice={action.notice}/>
      {stmt.preview?<><div className="fx-chips"><span className="fx-chip good">Válidos <strong>{stmt.preview.valid}</strong></span><span className={`fx-chip ${stmt.preview.duplicates?"warn":""}`}>Duplicados <strong>{stmt.preview.duplicates}</strong></span><span className={`fx-chip ${stmt.preview.invalid?"bad":""}`}>Con errores <strong>{stmt.preview.invalid}</strong></span>{stmt.preview.alreadyImported?<Stamp kind="bad">Archivo ya importado</Stamp>:null}</div>
        <div className="fx-form boxed">{["date","description","debit","credit","amount","balance","reference"].map((k)=><Field key={k} label={({date:"Fecha",description:"Glosa",debit:"Cargos",credit:"Abonos",amount:"Monto (con signo)",balance:"Saldo",reference:"Referencia"} as Record<string,string>)[k]!}><select value={stmt.mapping[k]??""} onChange={(e)=>{const mapping={...stmt.mapping,[k]:e.target.value||null};setStmt({...stmt,mapping});void preview(mapping);}}><option value="">(sin columna)</option>{stmt.preview!.headers.map((h)=><option key={h} value={h}>{h}</option>)}</select></Field>)}</div>
        <Register rows={stmt.preview.rows.slice(0,200)} rowKey={(r)=>String(r.rowNumber)} columns={[{key:"n",label:"Fila",render:(r)=>r.rowNumber},{key:"d",label:"Fecha",render:(r)=>day(r.date)},{key:"g",label:"Glosa",render:(r)=>r.description},{key:"s",label:"Sentido",render:(r)=>r.direction?label(r.direction):"—"},{key:"a",label:"Monto",align:"right",render:(r)=><Amount value={r.amount}/>},{key:"e",label:"Validación",render:(r)=>r.errors.length?<Pill value="ERROR" text={r.errors.join("; ")}/>:r.duplicate?<Pill value="ATTENTION" text="Duplicado"/>:<Pill value="OK" text="Nuevo"/>}]}/>
        <div className="fx-actions end"><button className="fx-btn primary" disabled={!stmt.preview.valid||stmt.preview.alreadyImported||action.busy} onClick={async()=>{const r=await action.run<any>(()=>financeApi.post(role,"/bank-statements/import",{bankAccountId:stmt.bankAccountId,file:stmt.file,mapping:stmt.mapping}));if(r){action.setNotice(`${r.inserted} movimientos importados; ${r.duplicates} duplicados omitidos.`);setStmt({bankAccountId:stmt.bankAccountId,file:null,mapping:{},preview:null});}}}>Importar {stmt.preview.valid} movimientos</button></div></>:null}
    </Section>:null}
    <Section eyebrow="HISTORIAL" title="Cartolas importadas"><Register rows={imports.data??[]} rowKey={(i:any)=>i.id} columns={[{key:"f",label:"Archivo",render:(i:any)=>i.fileName},{key:"d",label:"Importado",render:(i:any)=>moment(i.importedAt)},{key:"v",label:"Nuevos",align:"right",render:(i:any)=>i.rowsValid},{key:"u",label:"Duplicados",align:"right",render:(i:any)=>i.rowsDuplicate},{key:"e",label:"Errores",align:"right",render:(i:any)=>i.rowsInvalid},{key:"h",label:"SHA-256",render:(i:any)=><code>{String(i.fileSha256).slice(0,12)}…</code>}]} empty="Sin cartolas importadas"/></Section>
    <Drawer open={Boolean(accountForm)} title="Cuenta bancaria" onClose={()=>setAccountForm(null)}>{accountForm?<><div className="fx-form"><Field label="Banco" span={2}><input value={accountForm.bankName} onChange={(e)=>setAccountForm({...accountForm,bankName:e.target.value})}/></Field><Field label="Tipo"><select value={accountForm.accountType} onChange={(e)=>setAccountForm({...accountForm,accountType:e.target.value})}>{["CHECKING","SAVINGS","VISTA","OTHER"].map((t)=><option key={t} value={t}>{({CHECKING:"Corriente",SAVINGS:"Ahorro",VISTA:"Vista",OTHER:"Otra"} as Record<string,string>)[t]}</option>)}</select></Field><Field label="N° de cuenta" hint="Sólo se guardan los últimos 4 dígitos"><input autoComplete="off" value={accountForm.accountNumber} onChange={(e)=>setAccountForm({...accountForm,accountNumber:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Cuenta contable" span={2}><select value={accountForm.ledgerAccountId} onChange={(e)=>setAccountForm({...accountForm,ledgerAccountId:e.target.value})}>{cashLedger.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!accountForm.bankName||accountForm.accountNumber.length<4} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/bank-accounts",accountForm),"Cuenta creada.");if(r)setAccountForm(null);}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(cashForm)} title="Caja" onClose={()=>setCashForm(null)}>{cashForm?<><div className="fx-form"><Field label="Nombre" span={2}><input value={cashForm.name} onChange={(e)=>setCashForm({...cashForm,name:e.target.value})}/></Field><Field label="Cuenta contable"><select value={cashForm.ledgerAccountId} onChange={(e)=>setCashForm({...cashForm,ledgerAccountId:e.target.value})}>{cashLedger.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></Field></div><div className="fx-actions end"><button className="fx-btn primary" disabled={!cashForm.name} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/cash-accounts",cashForm),"Caja creada.");if(r)setCashForm(null);}}>Guardar</button></div></>:null}</Drawer>
    <Drawer open={Boolean(movement)} title="Movimiento de caja" subtitle="Queda a nombre del usuario responsable." onClose={()=>setMovement(null)}>{movement?<><div className="fx-form"><Field label="Sentido"><select value={movement.direction} onChange={(e)=>setMovement({...movement,direction:e.target.value})}><option value="IN">Ingreso</option><option value="OUT">Egreso</option></select></Field><Field label="Monto"><input inputMode="numeric" value={movement.amount} onChange={(e)=>setMovement({...movement,amount:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Fecha"><DateInput value={movement.movementDate} onChange={(v)=>setMovement({...movement,movementDate:v})}/></Field><Field label="Descripción" span={3}><input value={movement.description} onChange={(e)=>setMovement({...movement,description:e.target.value})}/></Field><Field label="Respaldo" span={3}><FileInput file={movement.evidence} onFile={(f)=>setMovement({...movement,evidence:f})}/></Field></div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={!movement.amount||!movement.movementDate||!movement.description} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,"/cash-movements",{...movement,amount:Number(movement.amount)}),"Movimiento registrado.");if(r)setMovement(null);}}>Registrar</button></div></>:null}</Drawer>
  </div>;
}

export function Reconciliation({tick}:ViewProps){
  const{role}=useAccess();const banks=useLoad(()=>financeApi.get<any[]>(role,"/bank-accounts"),[role]);const[account,setAccount]=useState("");const[showAll,setShowAll]=useState(false);
  const txs=useLoad(()=>financeApi.get<BankTransaction[]>(role,`/bank-transactions?${account?`bankAccountId=${account}&`:""}${showAll?"":"status=UNRECONCILED,PARTIALLY_RECONCILED"}`),[role,account,showAll,tick]);
  const[selected,setSelected]=useState<string|null>(null);const[checked,setChecked]=useState<string[]>([]);const suggestion=useLoad(()=>selected?financeApi.get<ReconciliationSuggestion>(role,`/bank-transactions/${selected}/suggestions`):Promise.resolve(null),[role,selected,tick]);const matches=useLoad(()=>selected?financeApi.get<any[]>(role,`/bank-transactions/${selected}/matches`):Promise.resolve([]),[role,selected,tick]);
  const action=useAction(async()=>{await txs.reload();await suggestion.reload();await matches.reload();});const[split,setSplit]=useState<Record<string,string>>({});const[dialog,setDialog]=useState<null|"ignore"|{undo:string}>(null);const[create,setCreate]=useState<any>(null);
  const ledger=useLoad(()=>canFinance(role,"accounting.view")?financeApi.get<any[]>(role,"/accounts"):Promise.resolve([]),[role]);const write=canFinance(role,"bank.reconcile");const tx=txs.data?.find((t)=>t.id===selected)??suggestion.data?.bankTransaction;const open=tx?Math.round((tx.amount-tx.reconciledAmount)*100)/100:0;
  const chosen=Object.entries(split).filter(([,v])=>Number(v)>0);const chosenTotal=chosen.reduce((t,[,v])=>t+Number(v),0);
  const submitMatch=()=>{const targets=chosen.map(([key,amount])=>{const[targetType,targetId]=key.split("|");return{targetType,targetId,amount:Number(amount)};});void action.run(()=>financeApi.post(role,`/bank-transactions/${selected}/match`,{targets}),targets.length>1?"Movimiento dividido (SPLIT) y conciliado.":"Movimiento conciliado.").then(()=>setSplit({}));};
  return <div className="fx-recon">
    <Section className="fx-recon-left" eyebrow="CARTOLA" title={`${txs.data?.length??0} movimientos`} actions={<><select value={account} onChange={(e)=>{setAccount(e.target.value);setSelected(null);}}><option value="">Todas las cuentas</option>{banks.data?.map((b)=><option key={b.id} value={b.id}>{b.bankName} ····{b.accountNumberLast4}</option>)}</select><label className="fx-check"><input type="checkbox" checked={showAll} onChange={(e)=>setShowAll(e.target.checked)}/>Incluir conciliados</label></>}>
      {txs.data?<ul className="fx-tx">{txs.data.map((t)=><li key={t.id} className={`${selected===t.id?"selected":""} ${t.direction.toLowerCase()}`}>{write?<input type="checkbox" aria-label="Seleccionar para unir" checked={checked.includes(t.id)} onChange={(e)=>setChecked(e.target.checked?[...checked,t.id]:checked.filter((x)=>x!==t.id))}/>:null}<button onClick={()=>{setSelected(t.id);setSplit({});}}><div><strong>{t.description}</strong><small>{day(t.transactionDate)}{t.reference?` · ${t.reference}`:""}</small></div><span><Amount value={t.direction==="DEBIT"?-t.amount:t.amount} signed strong/><Pill value={t.reconciliationStatus}/></span></button></li>)}{!txs.data.length?<li className="muted">Sin movimientos pendientes. Importa una cartola en Bancos y cajas.</li>:null}</ul>:txs.error?<LoadError error={txs.error} retry={()=>void txs.reload()}/>:<Loading/>}
    </Section>
    <Section className="fx-recon-right" eyebrow={tx?`${label(tx.direction)} · ${day(tx.transactionDate)}`:"CONCILIACIÓN"} title={tx?`${tx.description}`:"Selecciona un movimiento"} description={tx?`Monto ${money(tx.amount)} · disponible para conciliar ${money(open)}`:"Las sugerencias explican su confianza. Los casos ambiguos nunca se concilian solos."}>
      <Feedback error={action.error} notice={action.notice}/>
      {checked.length>1&&suggestion.data?<div className="fx-callout"><GitMerge size={15}/><strong>MERGE: {checked.length} movimientos → un documento</strong><small>Elige un candidato del primer movimiento seleccionado para unirlos.</small></div>:null}
      {!tx?<Empty title="Sin movimiento seleccionado"/>:suggestion.loading&&!suggestion.data?<Loading/>:suggestion.data?<>
        {suggestion.data.ambiguous?<div className="fx-feedback bad"><span>Caso ambiguo: hay candidatos con confianza similar. Revisa referencias antes de conciliar.</span></div>:null}
        <ul className="fx-candidates">{suggestion.data.candidates.map((c)=>{const key=`${c.targetType}|${c.targetId}`;return <li key={key}><label><input type="checkbox" disabled={!write} checked={key in split} onChange={(e)=>{const next={...split};if(e.target.checked)next[key]=String(Math.min(c.amount,open-chosenTotal>0?open-chosenTotal:c.amount));else delete next[key];setSplit(next);}}/><div><strong>{c.label}</strong><small>{label(c.targetType)} · {day(c.date)} · {c.reasons.join(" · ")}</small></div></label><div className="fx-confidence" title={`Confianza ${Math.round(c.confidence*100)}%`}><span style={{width:`${c.confidence*100}%`}}/><em>{Math.round(c.confidence*100)}%</em></div><Amount value={c.amount}/>{key in split&&c.targetType!=="PROVIDER_PAYOUT"?<input className="fx-mini" inputMode="numeric" value={split[key]} onChange={(e)=>setSplit({...split,[key]:e.target.value.replace(/[^\d.]/g,"")})} aria-label="Monto a conciliar"/>:null}{checked.length>1&&write?<button className="fx-btn small" onClick={()=>void action.run(()=>financeApi.post(role,"/reconciliation/merge",{transactionIds:checked,target:{targetType:c.targetType,targetId:c.targetId}}),"Movimientos unidos (MERGE) y conciliados.").then(()=>setChecked([]))}>Unir aquí</button>:null}</li>;})}{!suggestion.data.candidates.length?<li className="muted">Sin candidatos con monto y fecha compatibles.</li>:null}</ul>
        {write&&tx.reconciliationStatus!=="RECONCILED"?<div className="fx-actions"><button className="fx-btn primary" disabled={!chosen.length||chosenTotal>open||action.busy} onClick={submitMatch}><CheckCheck size={14}/>{chosen.length>1?`SPLIT · conciliar ${money(chosenTotal)}`:"Conciliar"}</button><button className="fx-btn ghost" onClick={()=>setCreate({kind:tx.direction==="CREDIT"?"PAYMENT":"JOURNAL",accountId:"",description:tx.description,clientId:""})}>Crear transacción</button>{tx.reconciliationStatus==="IGNORED"?<button className="fx-btn ghost" onClick={()=>void action.run(()=>financeApi.post(role,`/bank-transactions/${tx.id}/unignore`),"Omisión deshecha.")}>Deshacer omisión</button>:<button className="fx-btn ghost" onClick={()=>setDialog("ignore")}>Ignorar</button>}</div>:null}
        <h4 className="fx-subhead">Conciliaciones del movimiento</h4><Register rows={matches.data??[]} rowKey={(m:any)=>m.id} columns={[{key:"k",label:"Tipo",render:(m:any)=>m.matchKind},{key:"t",label:"Destino",render:(m:any)=>label(m.targetType)},{key:"a",label:"Monto",align:"right",render:(m:any)=><Amount value={m.amount}/>},{key:"d",label:"Fecha",render:(m:any)=>moment(m.createdAt)},{key:"s",label:"",render:(m:any)=>m.status==="ACTIVE"&&write?<button className="fx-btn small ghost" onClick={()=>setDialog({undo:m.id})}><Undo2 size={12}/>Deshacer</button>:<Pill value={m.status==="ACTIVE"?"OK":"REVERSED"} text={m.status==="ACTIVE"?"Vigente":`Deshecha: ${m.undoReason??""}`}/>}]} empty="Sin conciliaciones"/>
      </>:null}
    </Section>
    <ReasonDialog open={dialog!==null} title={dialog==="ignore"?"Ignorar movimiento":"Deshacer conciliación"} description={dialog==="ignore"?"Sólo para movimientos que no corresponden a la contabilidad (ej. traspasos ya registrados).":"Se deshace el grupo completo; los pagos confirmados siguen confirmados."} onCancel={()=>setDialog(null)} onConfirm={(reason)=>{const d=dialog;setDialog(null);if(d==="ignore")void action.run(()=>financeApi.post(role,`/bank-transactions/${selected}/ignore`,{reason}),"Movimiento ignorado.");else if(d&&typeof d==="object")void action.run(()=>financeApi.post(role,`/reconciliation-matches/${d.undo}/undo`,{reason}),"Conciliación deshecha.");}}/>
    <Drawer open={Boolean(create)} title="Crear transacción desde la cartola" subtitle="Abono → cobro de cliente (el movimiento es la evidencia). Cargo/abono sin documento → borrador de asiento revisable." onClose={()=>setCreate(null)}>{create?<><div className="fx-form"><Field label="Tipo"><select value={create.kind} onChange={(e)=>setCreate({...create,kind:e.target.value})}>{tx?.direction==="CREDIT"?<option value="PAYMENT">Cobro de cliente</option>:null}<option value="JOURNAL">Asiento (comisión, interés, otro)</option></select></Field>{create.kind==="PAYMENT"?<Field label="Cliente" span={3}><ClientPicker value={create.clientId} onChange={(id)=>setCreate({...create,clientId:id})}/></Field>:<><Field label="Cuenta contrapartida" span={2}><select value={create.accountId} onChange={(e)=>setCreate({...create,accountId:e.target.value})}><option value="">Selecciona…</option>{ledger.data?.filter((a:any)=>a.allowsPosting&&!a.isCash).map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></Field><Field label="Glosa" span={3}><input value={create.description} onChange={(e)=>setCreate({...create,description:e.target.value})}/></Field></>}</div><Feedback error={action.error}/><div className="fx-actions end"><button className="fx-btn primary" disabled={create.kind==="PAYMENT"?!create.clientId:!create.accountId} onClick={async()=>{const r=await action.run(()=>financeApi.post(role,`/bank-transactions/${selected}/create`,create),create.kind==="PAYMENT"?"Cobro registrado y conciliado.":"Borrador de asiento creado y vinculado.");if(r)setCreate(null);}}>Crear</button></div></>:null}</Drawer>
  </div>;
}
