import { ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type {
  ChangeRequest, OperationsEvent, OperationsProject, OperationsSummary, OperationsTask, ProjectDeliverable, ProjectDeployment,
  ProjectEndpoint, ProjectMember, ProjectMilestone, ProjectRisk, TaskDependency, WorkLog, WorkOrder,
} from "@zyteron/contracts";
import { cleanSearch, createServerSupabase, pageBounds } from "../domain/server-supabase.js";

export type OperationsPageInput={page:number;pageSize:number;search?:string;status?:string;projectId?:string;clientId?:string;assignedTo?:string;priority?:string;view?:string;userId?:string};
const now=()=>new Date().toISOString();
const page=<T>(items:T[],q:OperationsPageInput)=>{const start=(q.page-1)*q.pageSize;return{items:items.slice(start,start+q.pageSize),page:q.page,pageSize:q.pageSize,total:items.length,totalPages:Math.ceil(items.length/q.pageSize)};};
const relationName=(value:unknown,key:string)=>{if(Array.isArray(value))return String((value[0]as Record<string,unknown>|undefined)?.[key]??"")||null;if(value&&typeof value==="object")return String((value as Record<string,unknown>)[key]??"")||null;return null;};

@Injectable()
export class OperationsRepository{
  private readonly supabase=createServerSupabase();
  private readonly workOrders=new Map<string,WorkOrder>();
  private readonly projects=new Map<string,OperationsProject>();
  private readonly members=new Map<string,ProjectMember>();
  private readonly milestones=new Map<string,ProjectMilestone>();
  private readonly tasks=new Map<string,OperationsTask>();
  private readonly dependencies=new Map<string,TaskDependency>();
  private readonly worklogs=new Map<string,WorkLog>();
  private readonly deliverables=new Map<string,ProjectDeliverable>();
  private readonly deployments=new Map<string,ProjectDeployment>();
  private readonly endpoints=new Map<string,ProjectEndpoint>();
  private readonly risks=new Map<string,ProjectRisk>();
  private readonly changes=new Map<string,ChangeRequest>();
  private readonly events:OperationsEvent[]=[];
  private workOrderSequence=0;
  private projectSequence=0;

  async listWorkOrders(q:OperationsPageInput){if(!this.supabase){const search=q.search?.toLowerCase();return page([...this.workOrders.values()].filter(i=>(!q.status||i.status===q.status)&&(!q.clientId||i.clientId===q.clientId)&&(!q.assignedTo||i.assignedTo===q.assignedTo)&&(!search||[i.workOrderNumber,i.title,i.scope,i.clientName].some(v=>v?.toLowerCase().includes(search)))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),q);}const{from,to}=pageBounds(q.page,q.pageSize);const search=cleanSearch(q.search);let query=this.supabase.from("work_orders").select("*,clients(legal_name),projects(id)",{count:"exact"});if(search)query=query.or(`work_order_number.ilike.%${search}%,title.ilike.%${search}%,scope.ilike.%${search}%`);if(q.status)query=query.eq("status",q.status);if(q.clientId)query=query.eq("client_id",q.clientId);if(q.assignedTo)query=query.eq("assigned_to",q.assignedTo);const{data,error,count}=await query.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.workOrderFromRow),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async getWorkOrder(id:string){if(!this.supabase)return this.workOrders.get(id);const{data,error}=await this.supabase.from("work_orders").select("*,clients(legal_name),projects(id)").eq("id",id).maybeSingle();if(error)throw error;return data?this.workOrderFromRow(data):undefined;}
  async createWorkOrder(input:Partial<WorkOrder>){const stamp=now();const item:WorkOrder={id:randomUUID(),workOrderNumber:`OT-${new Date().getUTCFullYear()}-${String(++this.workOrderSequence).padStart(6,"0")}`,clientId:input.clientId||null,clientName:input.clientName||null,quoteId:input.quoteId||null,quoteVersionId:input.quoteVersionId||null,saleId:input.saleId||null,contractId:input.contractId||null,handoffId:input.handoffId||null,projectId:null,title:input.title!.trim(),description:input.description||null,scope:input.scope!.trim(),commercialSnapshot:input.commercialSnapshot??{},priority:input.priority||"NORMAL",status:input.status||"DRAFT",commercialOwnerId:input.commercialOwnerId||null,developmentManagerId:input.developmentManagerId||null,assignedTo:input.assignedTo||null,plannedStartDate:input.plannedStartDate||null,targetDate:input.targetDate||null,actualStartDate:null,completedAt:null,estimatedHours:input.estimatedHours??null,budgetReference:input.budgetReference??null,currency:input.currency||"CLP",createdBy:input.createdBy||null,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.workOrders.set(item.id,item);return item;}const{data,error}=await this.supabase.from("work_orders").insert(this.workOrderToRow(item)).select("*,clients(legal_name),projects(id)").single();if(error)throw error;return this.workOrderFromRow(data);}
  async updateWorkOrder(id:string,patch:Partial<WorkOrder>){const current=await this.getWorkOrder(id);if(!current)throw new NotFoundException("Orden de trabajo no encontrada.");if(!this.supabase){const next={...current,...patch,updatedAt:now()};this.workOrders.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={title:"title",description:"description",scope:"scope",priority:"priority",commercialOwnerId:"commercial_owner_id",developmentManagerId:"development_manager_id",assignedTo:"assigned_to",plannedStartDate:"planned_start_date",targetDate:"target_date",estimatedHours:"estimated_hours",budgetReference:"budget_reference",currency:"currency",commercialSnapshot:"commercial_snapshot",handoffId:"handoff_id",contractId:"contract_id"};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;const{data,error}=await this.supabase.from("work_orders").update(row).eq("id",id).select("*,clients(legal_name),projects(id)").single();if(error)throw error;return this.workOrderFromRow(data);}
  async transitionWorkOrder(id:string,status:WorkOrder["status"],actorId:string|null,reason:string|null){if(!this.supabase){const current=await this.getWorkOrder(id);if(!current)throw new NotFoundException("Orden de trabajo no encontrada.");const next={...current,status,actualStartDate:status==="IN_PROGRESS"?(current.actualStartDate??now()):current.actualStartDate,completedAt:["COMPLETED","CLOSED"].includes(status)?now():current.completedAt,updatedAt:now()};this.workOrders.set(id,next);await this.publish("WORK_ORDER",id,"WORK_ORDER_STATUS_CHANGED",actorId,{from:current.status,to:status,reason});return next;}const{error}=await this.supabase.rpc("operations_change_work_order_status",{target_work_order_id:id,target_status:status,actor_user_id:actorId,change_reason:reason});if(error)throw error;return(await this.getWorkOrder(id))!;}

  async listProjects(q:OperationsPageInput){if(!this.supabase){const search=q.search?.toLowerCase();let items=[...this.projects.values()].filter(i=>!i.archivedAt&&(!q.status||i.status===q.status)&&(!q.clientId||i.clientId===q.clientId)&&(!q.assignedTo||i.projectLeadId===q.assignedTo||i.developmentManagerId===q.assignedTo)&&(!search||[i.projectNumber,i.name,i.clientName,i.scope].some(v=>v?.toLowerCase().includes(search))));if(q.userId){const allowed=new Set([...this.members.values()].filter(m=>m.active&&m.userId===q.userId).map(m=>m.projectId));items=items.filter(i=>i.projectLeadId===q.userId||i.developmentManagerId===q.userId||allowed.has(i.id));}return page(items.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),q);}const{from,to}=pageBounds(q.page,q.pageSize);const search=cleanSearch(q.search);let query=this.supabase.from("projects").select("*,clients(legal_name)",{count:"exact"}).is("archived_at",null);if(search)query=query.or(`project_number.ilike.%${search}%,name.ilike.%${search}%,scope.ilike.%${search}%`);if(q.status)query=query.eq("status",q.status);if(q.clientId)query=query.eq("client_id",q.clientId);if(q.assignedTo)query=query.or(`project_lead_id.eq.${q.assignedTo},development_manager_id.eq.${q.assignedTo}`);if(q.userId){const ids=await this.projectIdsForUser(q.userId);if(!ids.length)return{items:[],page:q.page,pageSize:q.pageSize,total:0,totalPages:0};query=query.in("id",ids);}const{data,error,count}=await query.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.projectFromRow),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async getProject(id:string){if(!this.supabase)return this.projects.get(id);const{data,error}=await this.supabase.from("projects").select("*,clients(legal_name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.projectFromRow(data):undefined;}
  async createProject(input:Partial<OperationsProject>){const stamp=now();const item:OperationsProject={id:randomUUID(),projectNumber:`PRJ-${new Date().getUTCFullYear()}-${String(++this.projectSequence).padStart(6,"0")}`,clientId:input.clientId||null,clientName:input.clientName||null,workOrderId:input.workOrderId!,quoteId:input.quoteId||null,contractId:input.contractId||null,name:input.name!.trim(),description:input.description||null,scope:input.scope!.trim(),status:input.status||"PLANNING",priority:input.priority||"NORMAL",health:"ON_TRACK",healthReason:"Sin señales de riesgo operacionales.",progress:0,developmentManagerId:input.developmentManagerId||null,projectLeadId:input.projectLeadId||null,plannedStartDate:input.plannedStartDate||null,actualStartDate:null,targetDate:input.targetDate||null,completedAt:null,estimatedHours:input.estimatedHours??null,budgetedHours:input.budgetedHours??null,stagingUrl:null,productionUrl:null,repositoryUrl:null,clientVisibility:input.clientVisibility||"INTERNAL",createdBy:input.createdBy||null,createdAt:stamp,updatedAt:stamp,archivedAt:null};if(!this.supabase){if([...this.projects.values()].some(i=>i.workOrderId===item.workOrderId))throw new ConflictException("Esta OT ya posee un proyecto.");this.projects.set(item.id,item);const work=await this.getWorkOrder(item.workOrderId);if(work)this.workOrders.set(work.id,{...work,projectId:item.id,status:"IN_PROGRESS",updatedAt:stamp});return item;}const{data,error}=await this.supabase.from("projects").insert(this.projectToRow(item)).select("*,clients(legal_name)").single();if(error?.code==="23505")throw new ConflictException("Esta OT ya posee un proyecto.");if(error)throw error;return this.projectFromRow(data);}
  async createProjectFromWorkOrder(workOrderId:string,input:Partial<OperationsProject>,actorId:string|null,key:string){if(!this.supabase){const existing=[...this.projects.values()].find(i=>i.workOrderId===workOrderId);if(existing)return existing;const work=await this.getWorkOrder(workOrderId);if(!work)throw new NotFoundException("Orden de trabajo no encontrada.");const project=await this.createProject({...input,workOrderId,clientId:work.clientId,quoteId:work.quoteId,contractId:work.contractId,name:input.name||work.title,scope:input.scope||work.scope,priority:work.priority,createdBy:actorId});await this.publish("PROJECT",project.id,"PROJECT_CREATED",actorId,{workOrderId});return project;}const{data,error}=await this.supabase.rpc("operations_create_project_from_work_order",{target_work_order_id:workOrderId,project_payload:{...input,createdBy:actorId},actor_user_id:actorId,idempotency_key:key});if(error)throw error;return(await this.getProject(String(data)))!;}
  async updateProject(id:string,patch:Partial<OperationsProject>){const current=await this.getProject(id);if(!current)throw new NotFoundException("Proyecto no encontrado.");if(!this.supabase){const next={...current,...patch,updatedAt:now()};this.projects.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={name:"name",description:"description",scope:"scope",priority:"priority",developmentManagerId:"development_manager_id",projectLeadId:"project_lead_id",plannedStartDate:"planned_start_date",targetDate:"target_date",estimatedHours:"estimated_hours",budgetedHours:"budgeted_hours",stagingUrl:"staging_url",productionUrl:"production_url",repositoryUrl:"repository_url",clientVisibility:"client_visibility"};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;const{data,error}=await this.supabase.from("projects").update(row).eq("id",id).select("*,clients(legal_name)").single();if(error)throw error;return this.projectFromRow(data);}
  async transitionProject(id:string,status:OperationsProject["status"],actorId:string|null,reason:string|null){if(!this.supabase){const current=await this.getProject(id);if(!current)throw new NotFoundException("Proyecto no encontrado.");const next={...current,status,actualStartDate:status==="IN_PROGRESS"?(current.actualStartDate??now()):current.actualStartDate,completedAt:status==="COMPLETED"?now():current.completedAt,archivedAt:status==="ARCHIVED"?now():current.archivedAt,updatedAt:now()};this.projects.set(id,next);await this.publish("PROJECT",id,"PROJECT_STATUS_CHANGED",actorId,{from:current.status,to:status,reason});return next;}const{error}=await this.supabase.rpc("operations_change_project_status",{target_project_id:id,target_status:status,actor_user_id:actorId,change_reason:reason});if(error)throw error;return(await this.getProject(id))!;}
  async projectIdsForUser(userId:string){if(!this.supabase)return[...new Set([...this.members.values()].filter(i=>i.active&&i.userId===userId).map(i=>i.projectId))];const{data,error}=await this.supabase.from("project_members").select("project_id").eq("user_id",userId).eq("active",true);if(error)throw error;const direct=await this.supabase.from("projects").select("id").or(`project_lead_id.eq.${userId},development_manager_id.eq.${userId}`);if(direct.error)throw direct.error;return[...new Set([...(data??[]).map(i=>i.project_id),...(direct.data??[]).map(i=>i.id)])];}

  async listMembers(projectId:string){if(!this.supabase)return[...this.members.values()].filter(i=>i.projectId===projectId&&i.active);const{data,error}=await this.supabase.from("project_members").select("*").eq("project_id",projectId).eq("active",true).order("assigned_at");if(error)throw error;return(data??[]).map(this.memberFromRow);}
  async addMember(projectId:string,input:Partial<ProjectMember>){const item:ProjectMember={id:randomUUID(),projectId,userId:input.userId!,userName:input.userName||null,projectRole:input.projectRole||"DEVELOPER",allocationPercentage:input.allocationPercentage??null,assignedBy:input.assignedBy||null,assignedAt:now(),removedAt:null,active:true};if(!this.supabase){const existing=[...this.members.values()].find(i=>i.projectId===projectId&&i.userId===item.userId&&i.active);if(existing)return existing;this.members.set(item.id,item);return item;}const{data,error}=await this.supabase.from("project_members").upsert({project_id:projectId,user_id:item.userId,project_role:item.projectRole,allocation_percentage:item.allocationPercentage,assigned_by:item.assignedBy,active:true,removed_at:null},{onConflict:"project_id,user_id"}).select("*").single();if(error)throw error;return this.memberFromRow(data);}
  async updateMember(id:string,patch:Partial<ProjectMember>){if(!this.supabase){const current=this.members.get(id);if(!current)throw new NotFoundException("Miembro no encontrado.");const next={...current,...patch};this.members.set(id,next);return next;}const{data,error}=await this.supabase.from("project_members").update({project_role:patch.projectRole,allocation_percentage:patch.allocationPercentage}).eq("id",id).select("*").single();if(error)throw error;return this.memberFromRow(data);}
  async removeMember(id:string){if(!this.supabase){const current=this.members.get(id);if(!current)throw new NotFoundException("Miembro no encontrado.");const next={...current,active:false,removedAt:now()};this.members.set(id,next);return next;}const{data,error}=await this.supabase.from("project_members").update({active:false,removed_at:now()}).eq("id",id).select("*").single();if(error)throw error;return this.memberFromRow(data);}

  async listMilestones(projectId?:string){if(!this.supabase)return[...this.milestones.values()].filter(i=>!projectId||i.projectId===projectId).sort((a,b)=>a.sortOrder-b.sortOrder);let q=this.supabase.from("project_milestones").select("*").order("sort_order");if(projectId)q=q.eq("project_id",projectId);const{data,error}=await q;if(error)throw error;return(data??[]).map(this.milestoneFromRow);}
  async createMilestone(projectId:string,input:Partial<ProjectMilestone>){const stamp=now();const item:ProjectMilestone={id:randomUUID(),projectId,name:input.name!.trim(),description:input.description||null,status:input.status||"PLANNED",weight:Number(input.weight||0),plannedStartDate:input.plannedStartDate||null,dueDate:input.dueDate||null,completedAt:null,responsibleUserId:input.responsibleUserId||null,clientVisibility:input.clientVisibility||"INTERNAL",sortOrder:input.sortOrder??this.milestones.size,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.milestones.set(item.id,item);return item;}const{data,error}=await this.supabase.from("project_milestones").insert({project_id:projectId,name:item.name,description:item.description,status:item.status,weight:item.weight,planned_start_date:item.plannedStartDate,due_date:item.dueDate,responsible_user_id:item.responsibleUserId,client_visibility:item.clientVisibility,sort_order:item.sortOrder}).select("*").single();if(error)throw error;return this.milestoneFromRow(data);}
  async updateMilestone(id:string,patch:Partial<ProjectMilestone>){const current=[...this.milestones.values()].find(i=>i.id===id);if(!this.supabase){if(!current)throw new NotFoundException("Hito no encontrado.");const next={...current,...patch,updatedAt:now()};this.milestones.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={name:"name",description:"description",status:"status",weight:"weight",plannedStartDate:"planned_start_date",dueDate:"due_date",responsibleUserId:"responsible_user_id",clientVisibility:"client_visibility",sortOrder:"sort_order"};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;const{data,error}=await this.supabase.from("project_milestones").update(row).eq("id",id).select("*").single();if(error)throw error;return this.milestoneFromRow(data);}
  async completeMilestone(id:string,actorId:string|null){if(!this.supabase){const current=this.milestones.get(id);if(!current)throw new NotFoundException("Hito no encontrado.");const next={...current,status:"COMPLETED" as const,completedAt:now(),updatedAt:now()};this.milestones.set(id,next);await this.recalculateMemoryProject(current.projectId);await this.publish("MILESTONE",id,"MILESTONE_COMPLETED",actorId,{projectId:current.projectId});return next;}const{error}=await this.supabase.rpc("operations_complete_milestone",{target_milestone_id:id,actor_user_id:actorId});if(error)throw error;const{data,error:fetchError}=await this.supabase.from("project_milestones").select("*").eq("id",id).single();if(fetchError)throw fetchError;return this.milestoneFromRow(data);}

  async listTasks(q:OperationsPageInput){const decorate=(i:OperationsTask)=>({...i,overdue:Boolean(i.dueDate&&i.dueDate<now()&&!['DONE','CANCELLED'].includes(i.status))});if(!this.supabase){const search=q.search?.toLowerCase(),allowed=q.userId?new Set(await this.projectIdsForUser(q.userId)):null;return page([...this.tasks.values()].map(decorate).filter(i=>(!allowed||allowed.has(i.projectId))&&(!q.projectId||i.projectId===q.projectId)&&(!q.status||i.status===q.status)&&(!q.assignedTo||i.assignedTo===q.assignedTo)&&(!q.priority||i.priority===q.priority)&&(!search||[i.title,i.description,i.projectName].some(v=>v?.toLowerCase().includes(search)))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),q);}const{from,to}=pageBounds(q.page,q.pageSize);const search=cleanSearch(q.search);let query=this.supabase.from("tasks").select("*,projects(name)",{count:"exact"});if(search)query=query.or(`title.ilike.%${search}%,description.ilike.%${search}%`);if(q.userId){const ids=await this.projectIdsForUser(q.userId);if(!ids.length)return{items:[],page:q.page,pageSize:q.pageSize,total:0,totalPages:0};query=query.in("project_id",ids);}if(q.projectId)query=query.eq("project_id",q.projectId);if(q.status)query=query.eq("status",q.status);if(q.assignedTo)query=query.eq("assigned_to",q.assignedTo);if(q.priority)query=query.eq("priority",q.priority);if(q.view==="overdue")query=query.lt("due_date",now()).not("status","in",'(DONE,CANCELLED)');const{data,error,count}=await query.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.taskFromRow).map(decorate),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async getTask(id:string){if(!this.supabase)return this.tasks.get(id);const{data,error}=await this.supabase.from("tasks").select("*,projects(name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.taskFromRow(data):undefined;}
  async createTask(input:Partial<OperationsTask>){const stamp=now();const item:OperationsTask={id:randomUUID(),projectId:input.projectId!,projectName:input.projectName||null,milestoneId:input.milestoneId||null,parentTaskId:input.parentTaskId||null,title:input.title!.trim(),description:input.description||null,status:input.status||"BACKLOG",priority:input.priority||"NORMAL",assignedTo:input.assignedTo||null,createdBy:input.createdBy||null,estimatedMinutes:input.estimatedMinutes??null,actualMinutes:0,startDate:input.startDate||null,dueDate:input.dueDate||null,completedAt:null,blockedReason:null,blockedType:null,clientVisibility:input.clientVisibility||"INTERNAL",overdue:false,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.tasks.set(item.id,item);return item;}const{data,error}=await this.supabase.from("tasks").insert(this.taskToRow(item)).select("*,projects(name)").single();if(error)throw error;return this.taskFromRow(data);}
  async updateTask(id:string,patch:Partial<OperationsTask>){const current=await this.getTask(id);if(!current)throw new NotFoundException("Tarea no encontrada.");if(!this.supabase){const next={...current,...patch,updatedAt:now()};this.tasks.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={title:"title",description:"description",milestoneId:"milestone_id",parentTaskId:"parent_task_id",priority:"priority",assignedTo:"assigned_to",estimatedMinutes:"estimated_minutes",startDate:"start_date",dueDate:"due_date",clientVisibility:"client_visibility"};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;const{data,error}=await this.supabase.from("tasks").update(row).eq("id",id).select("*,projects(name)").single();if(error)throw error;return this.taskFromRow(data);}
  async transitionTask(id:string,status:OperationsTask["status"],actorId:string|null,reason:string|null,type:string|null){if(!this.supabase){const current=await this.getTask(id);if(!current)throw new NotFoundException("Tarea no encontrada.");const next={...current,status,blockedReason:status==="BLOCKED"?reason:null,blockedType:status==="BLOCKED"?type:null,completedAt:status==="DONE"?now():null,updatedAt:now()};this.tasks.set(id,next);await this.recalculateMemoryProject(current.projectId);await this.publish("TASK",id,status==="BLOCKED"?"TASK_BLOCKED":status==="DONE"?"TASK_COMPLETED":"TASK_STATUS_CHANGED",actorId,{projectId:current.projectId,from:current.status,to:status,reason});return next;}const{error}=await this.supabase.rpc("operations_change_task_status",{target_task_id:id,target_status:status,actor_user_id:actorId,change_reason:reason,block_type:type});if(error)throw error;return(await this.getTask(id))!;}
  async listDependencies(taskId?:string){if(!this.supabase)return[...this.dependencies.values()].filter(i=>!taskId||i.taskId===taskId);let q=this.supabase.from("task_dependencies").select("*");if(taskId)q=q.eq("task_id",taskId);const{data,error}=await q;if(error)throw error;return(data??[]).map(this.dependencyFromRow);}
  async addDependency(input:Partial<TaskDependency>){const item:TaskDependency={id:randomUUID(),taskId:input.taskId!,dependsOnTaskId:input.dependsOnTaskId!,dependencyType:input.dependencyType||"REQUIRES",createdAt:now()};if(!this.supabase){this.dependencies.set(item.id,item);return item;}const{data,error}=await this.supabase.from("task_dependencies").insert({task_id:item.taskId,depends_on_task_id:item.dependsOnTaskId,dependency_type:item.dependencyType}).select("*").single();if(error?.code==="23514")throw new ConflictException("La dependencia crea un ciclo.");if(error)throw error;return this.dependencyFromRow(data);}

  async listWorklogs(q:OperationsPageInput){if(!this.supabase)return page([...this.worklogs.values()].filter(i=>(!q.projectId||i.projectId===q.projectId)&&(!q.userId||i.userId===q.userId)).sort((a,b)=>b.workDate.localeCompare(a.workDate)),q);const{from,to}=pageBounds(q.page,q.pageSize);let query=this.supabase.from("work_logs").select("*,projects(name)",{count:"exact"});if(q.projectId)query=query.eq("project_id",q.projectId);if(q.userId)query=query.eq("user_id",q.userId);const{data,error,count}=await query.order("work_date",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.worklogFromRow),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async getWorklog(id:string){if(!this.supabase)return this.worklogs.get(id);const{data,error}=await this.supabase.from("work_logs").select("*,projects(name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.worklogFromRow(data):undefined;}
  async createWorklog(input:Partial<WorkLog>){const stamp=now();const item:WorkLog={id:randomUUID(),projectId:input.projectId!,projectName:input.projectName||null,taskId:input.taskId||null,userId:input.userId!,workDate:input.workDate!,startedAt:input.startedAt||null,durationMinutes:Number(input.durationMinutes),description:input.description!.trim(),publicDescription:input.publicDescription||null,workType:input.workType||"DEVELOPMENT",billable:Boolean(input.billable),clientVisibility:input.clientVisibility||"INTERNAL",commitReference:input.commitReference||null,deploymentId:input.deploymentId||null,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.worklogs.set(item.id,item);if(item.taskId){const task=this.tasks.get(item.taskId);if(task)this.tasks.set(task.id,{...task,actualMinutes:task.actualMinutes+item.durationMinutes,updatedAt:stamp});}return item;}const{data,error}=await this.supabase.from("work_logs").insert(this.worklogToRow(item)).select("*,projects(name)").single();if(error)throw error;return this.worklogFromRow(data);}
  async updateWorklog(id:string,patch:Partial<WorkLog>){if(!this.supabase){const current=this.worklogs.get(id);if(!current)throw new NotFoundException("Worklog no encontrado.");const next={...current,...patch,updatedAt:now()};this.worklogs.set(id,next);return next;}const{data,error}=await this.supabase.from("work_logs").update({duration_minutes:patch.durationMinutes,description:patch.description,public_description:patch.publicDescription,work_type:patch.workType,billable:patch.billable,client_visibility:patch.clientVisibility,updated_at:now()}).eq("id",id).select("*,projects(name)").single();if(error)throw error;return this.worklogFromRow(data);}
  async deleteWorklog(id:string){if(!this.supabase)return this.worklogs.delete(id);const{error}=await this.supabase.from("work_logs").delete().eq("id",id);if(error)throw error;return true;}

  async listDeliverables(q:OperationsPageInput){const allowed=q.userId?new Set(await this.projectIdsForUser(q.userId)):null;if(!this.supabase)return page([...this.deliverables.values()].filter(i=>(!allowed||allowed.has(i.projectId))&&(!q.projectId||i.projectId===q.projectId)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),q);const{from,to}=pageBounds(q.page,q.pageSize);let query=this.supabase.from("project_deliverables").select("*,projects(name)",{count:"exact"});if(allowed){if(!allowed.size)return{items:[],page:q.page,pageSize:q.pageSize,total:0,totalPages:0};query=query.in("project_id",[...allowed]);}if(q.projectId)query=query.eq("project_id",q.projectId);if(q.status)query=query.eq("status",q.status);const{data,error,count}=await query.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.deliverableFromRow),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async createDeliverable(input:Partial<ProjectDeliverable>){const stamp=now();const item:ProjectDeliverable={id:randomUUID(),projectId:input.projectId!,projectName:input.projectName||null,milestoneId:input.milestoneId||null,name:input.name!.trim(),description:input.description||null,type:input.type||"OTHER",status:input.status||"PLANNED",dueDate:input.dueDate||null,ownerId:input.ownerId||null,documentId:input.documentId||null,externalUrl:input.externalUrl||null,version:input.version||1,clientVisibility:input.clientVisibility||"INTERNAL",submittedAt:null,approvedAt:null,approvedBy:null,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.deliverables.set(item.id,item);return item;}const{data,error}=await this.supabase.from("project_deliverables").insert(this.deliverableToRow(item)).select("*,projects(name)").single();if(error)throw error;return this.deliverableFromRow(data);}
  async updateDeliverable(id:string,patch:Partial<ProjectDeliverable>){if(!this.supabase){const current=this.deliverables.get(id);if(!current)throw new NotFoundException("Entregable no encontrado.");const next={...current,...patch,updatedAt:now()};this.deliverables.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={name:"name",description:"description",type:"type",status:"status",dueDate:"due_date",ownerId:"owner_id",documentId:"document_id",externalUrl:"external_url",version:"version",clientVisibility:"client_visibility",submittedAt:"submitted_at",approvedAt:"approved_at",approvedBy:"approved_by"};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;const{data,error}=await this.supabase.from("project_deliverables").update(row).eq("id",id).select("*,projects(name)").single();if(error)throw error;return this.deliverableFromRow(data);}

  async listDeployments(q:OperationsPageInput){const allowed=q.userId?new Set(await this.projectIdsForUser(q.userId)):null;if(!this.supabase)return page([...this.deployments.values()].filter(i=>(!allowed||allowed.has(i.projectId))&&(!q.projectId||i.projectId===q.projectId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),q);const{from,to}=pageBounds(q.page,q.pageSize);let query=this.supabase.from("deployments").select("*,projects(name)",{count:"exact"});if(allowed){if(!allowed.size)return{items:[],page:q.page,pageSize:q.pageSize,total:0,totalPages:0};query=query.in("project_id",[...allowed]);}if(q.projectId)query=query.eq("project_id",q.projectId);if(q.status)query=query.eq("status",q.status);const{data,error,count}=await query.order("created_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.deploymentFromRow),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async getDeployment(id:string){if(!this.supabase)return this.deployments.get(id);const{data,error}=await this.supabase.from("deployments").select("*,projects(name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.deploymentFromRow(data):undefined;}
  async createDeployment(input:Partial<ProjectDeployment>){const stamp=now();const item:ProjectDeployment={id:randomUUID(),projectId:input.projectId!,projectName:input.projectName||null,environment:input.environment||"STAGING",version:input.version!.trim(),commitSha:input.commitSha||null,status:input.status||"PLANNED",recordType:input.recordType||"MANUAL_RECORD",requestedBy:input.requestedBy||null,deployedBy:input.deployedBy||null,startedAt:input.startedAt||null,completedAt:input.completedAt||null,notes:input.notes||null,rollbackOfId:input.rollbackOfId||null,clientVisibility:input.clientVisibility||"INTERNAL",createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.deployments.set(item.id,item);return item;}const{data,error}=await this.supabase.from("deployments").insert(this.deploymentToRow(item)).select("*,projects(name)").single();if(error)throw error;return this.deploymentFromRow(data);}
  async updateDeployment(id:string,patch:Partial<ProjectDeployment>){if(!this.supabase){const current=this.deployments.get(id);if(!current)throw new NotFoundException("Deployment no encontrado.");const next={...current,...patch,updatedAt:now()};this.deployments.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={environment:"environment",version:"version",commitSha:"commit_sha",status:"status",deployedBy:"deployed_by",startedAt:"started_at",completedAt:"completed_at",notes:"notes",rollbackOfId:"rollback_of_id",clientVisibility:"client_visibility"};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;const{data,error}=await this.supabase.from("deployments").update(row).eq("id",id).select("*,projects(name)").single();if(error)throw error;return this.deploymentFromRow(data);}

  async listEndpoints(projectId:string){if(!this.supabase)return[...this.endpoints.values()].filter(i=>i.projectId===projectId&&i.active);const{data,error}=await this.supabase.from("project_endpoints").select("*").eq("project_id",projectId).eq("active",true);if(error)throw error;return(data??[]).map(this.endpointFromRow);}
  async createEndpoint(projectId:string,input:Partial<ProjectEndpoint>){const stamp=now();const item:ProjectEndpoint={id:randomUUID(),projectId,name:input.name!.trim(),url:input.url!,environment:input.environment||"PRODUCTION",endpointType:input.endpointType||"WEB",monitoringEnabled:Boolean(input.monitoringEnabled),responsibleUserId:input.responsibleUserId||null,active:true,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.endpoints.set(item.id,item);return item;}const{data,error}=await this.supabase.from("project_endpoints").insert({project_id:projectId,name:item.name,url:item.url,environment:item.environment,endpoint_type:item.endpointType,monitoring_enabled:item.monitoringEnabled,responsible_user_id:item.responsibleUserId}).select("*").single();if(error)throw error;return this.endpointFromRow(data);}
  async listRisks(projectId:string){if(!this.supabase)return[...this.risks.values()].filter(i=>i.projectId===projectId);const{data,error}=await this.supabase.from("project_risks").select("*").eq("project_id",projectId).order("severity",{ascending:false});if(error)throw error;return(data??[]).map(this.riskFromRow);}
  async createRisk(projectId:string,input:Partial<ProjectRisk>){const item:ProjectRisk={id:randomUUID(),projectId,title:input.title!.trim(),description:input.description||null,probability:Number(input.probability),impact:Number(input.impact),severity:Number(input.probability)*Number(input.impact),ownerId:input.ownerId||null,mitigation:input.mitigation||null,status:input.status||"OPEN",createdAt:now(),resolvedAt:null};if(!this.supabase){this.risks.set(item.id,item);return item;}const{data,error}=await this.supabase.from("project_risks").insert({project_id:projectId,title:item.title,description:item.description,probability:item.probability,impact:item.impact,owner_id:item.ownerId,mitigation:item.mitigation,status:item.status}).select("*").single();if(error)throw error;return this.riskFromRow(data);}
  async listChanges(projectId:string){if(!this.supabase)return[...this.changes.values()].filter(i=>i.projectId===projectId);const{data,error}=await this.supabase.from("change_requests").select("*").eq("project_id",projectId).order("created_at",{ascending:false});if(error)throw error;return(data??[]).map(this.changeFromRow);}
  async createChange(projectId:string,input:Partial<ChangeRequest>){const stamp=now();const item:ChangeRequest={id:randomUUID(),projectId,requestedBy:input.requestedBy||null,source:input.source||"INTERNAL",description:input.description!.trim(),reason:input.reason||null,scopeImpact:input.scopeImpact||null,timeImpact:input.timeImpact||null,costImpact:input.costImpact??null,currency:input.currency||"CLP",status:"REQUESTED",approvedBy:null,approvedAt:null,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.changes.set(item.id,item);return item;}const{data,error}=await this.supabase.from("change_requests").insert({project_id:projectId,requested_by:item.requestedBy,source:item.source,description:item.description,reason:item.reason,scope_impact:item.scopeImpact,time_impact:item.timeImpact,cost_impact:item.costImpact,currency:item.currency,status:item.status}).select("*").single();if(error)throw error;return this.changeFromRow(data);}

  async activity(projectId?:string,limit=80){if(!this.supabase)return this.events.filter(i=>!projectId||i.projectId===projectId).slice(0,limit);let q=this.supabase.from("operations_events").select("*").order("occurred_at",{ascending:false}).limit(limit);if(projectId)q=q.eq("project_id",projectId);const{data,error}=await q;if(error)throw error;return(data??[]).map(this.eventFromRow);}
  async publish(aggregateType:string,aggregateId:string,eventType:string,actorId:string|null,payload:Record<string,unknown>={},projectId:string|null=null,workOrderId:string|null=null){const event:OperationsEvent={id:randomUUID(),projectId,workOrderId,aggregateType,aggregateId,eventType,actorId,payload,occurredAt:now()};if(!this.supabase){this.events.unshift(event);return event;}const{data,error}=await this.supabase.from("operations_events").insert({project_id:projectId,work_order_id:workOrderId,aggregate_type:aggregateType,aggregate_id:aggregateId,event_type:eventType,actor_id:actorId,payload}).select("*").single();if(error)throw error;await this.supabase.from("business_event_outbox").insert({aggregate_type:aggregateType,aggregate_id:aggregateId,event_type:eventType,payload:{...payload,operationsEventId:data.id}});return event;}
  async summary():Promise<OperationsSummary>{if(this.supabase){const{data,error}=await this.supabase.rpc("operations_dashboard_summary");if(error)throw error;return data as OperationsSummary;}const today=now().slice(0,10),projects=[...this.projects.values()],tasks=[...this.tasks.values()],milestones=[...this.milestones.values()],workOrders=[...this.workOrders.values()],deliverables=[...this.deliverables.values()],deployments=[...this.deployments.values()];return{newWorkOrders:workOrders.filter(i=>["DRAFT","READY_FOR_HANDOFF"].includes(i.status)).length,pendingPlanning:workOrders.filter(i=>["PENDING_PLANNING","PLANNING"].includes(i.status)).length,activeProjects:projects.filter(i=>!["COMPLETED","CANCELLED","ARCHIVED"].includes(i.status)).length,atRiskProjects:projects.filter(i=>["AT_RISK","CRITICAL"].includes(i.health)).length,overdueProjects:projects.filter(i=>Boolean(i.targetDate&&i.targetDate<today&&!['COMPLETED','CANCELLED','ARCHIVED'].includes(i.status))).length,overdueTasks:tasks.filter(i=>Boolean(i.dueDate&&i.dueDate<today&&!['DONE','CANCELLED'].includes(i.status))).length,blockedTasks:tasks.filter(i=>i.status==="BLOCKED").length,upcomingMilestones:milestones.filter(i=>Boolean(i.dueDate&&i.dueDate>=today&&i.status!=="COMPLETED")).length,overdueMilestones:milestones.filter(i=>Boolean(i.dueDate&&i.dueDate<today&&!['COMPLETED','CANCELLED'].includes(i.status))).length,pendingDeliverables:deliverables.filter(i=>!["APPROVED","DELIVERED","CANCELLED"].includes(i.status)).length,pendingDeployments:deployments.filter(i=>["PLANNED","QUEUED","IN_PROGRESS"].includes(i.status)).length,minutesToday:[...this.worklogs.values()].filter(i=>i.workDate===today).reduce((sum,i)=>sum+i.durationMinutes,0),unassignedProjects:projects.filter(i=>!i.projectLeadId).length};}

  private async recalculateMemoryProject(projectId:string){const project=this.projects.get(projectId);if(!project)return;const milestones=[...this.milestones.values()].filter(i=>i.projectId===projectId&&i.status!=="CANCELLED"),tasks=[...this.tasks.values()].filter(i=>i.projectId===projectId&&i.status!=="CANCELLED");const milestoneWeight=milestones.reduce((s,i)=>s+i.weight,0);const milestoneProgress=milestoneWeight?milestones.reduce((s,i)=>s+(i.status==="COMPLETED"?i.weight:0),0)/milestoneWeight*100:0;const taskProgress=tasks.length?tasks.filter(i=>i.status==="DONE").length/tasks.length*100:0;const progress=Math.round(milestones.length&&tasks.length?(milestoneProgress*.7+taskProgress*.3):milestones.length?milestoneProgress:taskProgress);this.projects.set(projectId,{...project,progress,updatedAt:now()});}

  private workOrderFromRow=(r:any):WorkOrder=>({id:r.id,workOrderNumber:r.work_order_number,clientId:r.client_id,clientName:relationName(r.clients,"legal_name"),quoteId:r.quote_id,quoteVersionId:r.quote_version_id??null,saleId:r.sale_id??null,contractId:r.contract_id??null,handoffId:r.handoff_id??null,projectId:relationName(r.projects,"id"),title:r.title??`Orden ${r.work_order_number}`,description:r.description??null,scope:r.scope??"",commercialSnapshot:r.commercial_snapshot??{},priority:r.priority,status:r.status,commercialOwnerId:r.commercial_owner_id,developmentManagerId:r.development_manager_id??r.development_owner_id??null,assignedTo:r.assigned_to??null,plannedStartDate:r.planned_start_date??null,targetDate:r.target_date??r.deadline??null,actualStartDate:r.actual_start_date??null,completedAt:r.completed_at??null,estimatedHours:r.estimated_hours===null?null:Number(r.estimated_hours),budgetReference:r.budget_reference===null?null:Number(r.budget_reference),currency:r.currency??"CLP",createdBy:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at});
  private workOrderToRow=(i:WorkOrder)=>({client_id:i.clientId,quote_id:i.quoteId,quote_version_id:i.quoteVersionId,sale_id:i.saleId,contract_id:i.contractId,handoff_id:i.handoffId,title:i.title,description:i.description,scope:i.scope,commercial_snapshot:i.commercialSnapshot,priority:i.priority,status:i.status,commercial_owner_id:i.commercialOwnerId,development_manager_id:i.developmentManagerId,assigned_to:i.assignedTo,planned_start_date:i.plannedStartDate,target_date:i.targetDate,estimated_hours:i.estimatedHours,budget_reference:i.budgetReference,currency:i.currency,created_by:i.createdBy});
  private projectFromRow=(r:any):OperationsProject=>({id:r.id,projectNumber:r.project_number,clientId:r.client_id,clientName:relationName(r.clients,"legal_name"),workOrderId:r.work_order_id,quoteId:r.quote_id,contractId:r.contract_id,name:r.name,description:r.description,scope:r.scope,status:r.status,priority:r.priority,health:r.health,healthReason:r.health_reason??"Sin señales suficientes.",progress:Number(r.progress??0),developmentManagerId:r.development_manager_id,projectLeadId:r.project_lead_id,plannedStartDate:r.planned_start_date,actualStartDate:r.actual_start_date,targetDate:r.target_date,completedAt:r.completed_at,estimatedHours:r.estimated_hours===null?null:Number(r.estimated_hours),budgetedHours:r.budgeted_hours===null?null:Number(r.budgeted_hours),stagingUrl:r.staging_url,productionUrl:r.production_url,repositoryUrl:r.repository_url,clientVisibility:r.client_visibility,createdBy:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at,archivedAt:r.archived_at});
  private projectToRow=(i:OperationsProject)=>({client_id:i.clientId,work_order_id:i.workOrderId,quote_id:i.quoteId,contract_id:i.contractId,name:i.name,description:i.description,scope:i.scope,status:i.status,priority:i.priority,health:i.health,health_reason:i.healthReason,progress:i.progress,development_manager_id:i.developmentManagerId,project_lead_id:i.projectLeadId,planned_start_date:i.plannedStartDate,target_date:i.targetDate,estimated_hours:i.estimatedHours,budgeted_hours:i.budgetedHours,client_visibility:i.clientVisibility,created_by:i.createdBy});
  private memberFromRow=(r:any):ProjectMember=>({id:r.id,projectId:r.project_id,userId:r.user_id,userName:r.user_name??null,projectRole:r.project_role,allocationPercentage:r.allocation_percentage===null?null:Number(r.allocation_percentage),assignedBy:r.assigned_by,assignedAt:r.assigned_at,removedAt:r.removed_at,active:r.active});
  private milestoneFromRow=(r:any):ProjectMilestone=>({id:r.id,projectId:r.project_id,name:r.name,description:r.description,status:r.status,weight:Number(r.weight),plannedStartDate:r.planned_start_date,dueDate:r.due_date,completedAt:r.completed_at,responsibleUserId:r.responsible_user_id,clientVisibility:r.client_visibility,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at});
  private taskFromRow=(r:any):OperationsTask=>({id:r.id,projectId:r.project_id,projectName:relationName(r.projects,"name"),milestoneId:r.milestone_id,parentTaskId:r.parent_task_id,title:r.title,description:r.description,status:r.status,priority:r.priority,assignedTo:r.assigned_to,createdBy:r.created_by,estimatedMinutes:r.estimated_minutes===null?null:r.estimated_minutes,actualMinutes:r.actual_minutes??0,startDate:r.start_date,dueDate:r.due_date,completedAt:r.completed_at,blockedReason:r.blocked_reason,blockedType:r.blocked_type,clientVisibility:r.client_visibility,overdue:Boolean(r.due_date&&r.due_date<now()&&!['DONE','CANCELLED'].includes(r.status)),createdAt:r.created_at,updatedAt:r.updated_at});
  private taskToRow=(i:OperationsTask)=>({project_id:i.projectId,milestone_id:i.milestoneId,parent_task_id:i.parentTaskId,title:i.title,description:i.description,status:i.status,priority:i.priority,assigned_to:i.assignedTo,created_by:i.createdBy,estimated_minutes:i.estimatedMinutes,start_date:i.startDate,due_date:i.dueDate,client_visibility:i.clientVisibility});
  private dependencyFromRow=(r:any):TaskDependency=>({id:r.id,taskId:r.task_id,dependsOnTaskId:r.depends_on_task_id,dependencyType:r.dependency_type,createdAt:r.created_at});
  private worklogFromRow=(r:any):WorkLog=>({id:r.id,projectId:r.project_id,projectName:relationName(r.projects,"name"),taskId:r.task_id,userId:r.user_id,workDate:r.work_date,startedAt:r.started_at,durationMinutes:r.duration_minutes,description:r.description,publicDescription:r.public_description,workType:r.work_type,billable:r.billable,clientVisibility:r.client_visibility,commitReference:r.commit_reference,deploymentId:r.deployment_id,createdAt:r.created_at,updatedAt:r.updated_at});
  private worklogToRow=(i:WorkLog)=>({project_id:i.projectId,task_id:i.taskId,user_id:i.userId,work_date:i.workDate,started_at:i.startedAt,duration_minutes:i.durationMinutes,description:i.description,public_description:i.publicDescription,work_type:i.workType,billable:i.billable,client_visibility:i.clientVisibility,commit_reference:i.commitReference,deployment_id:i.deploymentId});
  private deliverableFromRow=(r:any):ProjectDeliverable=>({id:r.id,projectId:r.project_id,projectName:relationName(r.projects,"name"),milestoneId:r.milestone_id,name:r.name,description:r.description,type:r.type,status:r.status,dueDate:r.due_date,ownerId:r.owner_id,documentId:r.document_id,externalUrl:r.external_url,version:r.version,clientVisibility:r.client_visibility,submittedAt:r.submitted_at,approvedAt:r.approved_at,approvedBy:r.approved_by,createdAt:r.created_at,updatedAt:r.updated_at});
  private deliverableToRow=(i:ProjectDeliverable)=>({project_id:i.projectId,milestone_id:i.milestoneId,name:i.name,description:i.description,type:i.type,status:i.status,due_date:i.dueDate,owner_id:i.ownerId,document_id:i.documentId,external_url:i.externalUrl,version:i.version,client_visibility:i.clientVisibility});
  private deploymentFromRow=(r:any):ProjectDeployment=>({id:r.id,projectId:r.project_id,projectName:relationName(r.projects,"name"),environment:r.environment,version:r.version,commitSha:r.commit_sha,status:r.status,recordType:r.record_type,requestedBy:r.requested_by,deployedBy:r.deployed_by,startedAt:r.started_at,completedAt:r.completed_at,notes:r.notes,rollbackOfId:r.rollback_of_id,clientVisibility:r.client_visibility,createdAt:r.created_at,updatedAt:r.updated_at});
  private deploymentToRow=(i:ProjectDeployment)=>({project_id:i.projectId,environment:i.environment,version:i.version,commit_sha:i.commitSha,status:i.status,record_type:i.recordType,requested_by:i.requestedBy,deployed_by:i.deployedBy,started_at:i.startedAt,completed_at:i.completedAt,notes:i.notes,rollback_of_id:i.rollbackOfId,client_visibility:i.clientVisibility});
  private endpointFromRow=(r:any):ProjectEndpoint=>({id:r.id,projectId:r.project_id,name:r.name,url:r.url,environment:r.environment,endpointType:r.endpoint_type,monitoringEnabled:r.monitoring_enabled,responsibleUserId:r.responsible_user_id,active:r.active,createdAt:r.created_at,updatedAt:r.updated_at});
  private riskFromRow=(r:any):ProjectRisk=>({id:r.id,projectId:r.project_id,title:r.title,description:r.description,probability:r.probability,impact:r.impact,severity:r.severity,ownerId:r.owner_id,mitigation:r.mitigation,status:r.status,createdAt:r.created_at,resolvedAt:r.resolved_at});
  private changeFromRow=(r:any):ChangeRequest=>({id:r.id,projectId:r.project_id,requestedBy:r.requested_by,source:r.source,description:r.description,reason:r.reason,scopeImpact:r.scope_impact,timeImpact:r.time_impact,costImpact:r.cost_impact===null?null:Number(r.cost_impact),currency:r.currency,status:r.status,approvedBy:r.approved_by,approvedAt:r.approved_at,createdAt:r.created_at,updatedAt:r.updated_at});
  private eventFromRow=(r:any):OperationsEvent=>({id:r.id,projectId:r.project_id,workOrderId:r.work_order_id,aggregateType:r.aggregate_type,aggregateId:r.aggregate_id,eventType:r.event_type,actorId:r.actor_id,payload:r.payload??{},occurredAt:r.occurred_at});
}
