import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import type { OperationsProject, OperationsPriorityItem, OperationsTask, ProjectOperationalSummary, Role, WorkOrder } from "@zyteron/contracts";
import { optionalUuid, required } from "../commercial/commercial.validation.js";
import { OperationsRepository, type OperationsPageInput } from "./operations.repository.js";

export interface OperationsActor{userId:string|null;role:string;}
const managerRoles=new Set(["GERENTE_GENERAL","JEFE_DESARROLLO","OPERACIONES"]);
const commercialRoles=new Set(["GERENTE_GENERAL","JEFE_VENTAS","COMERCIAL","EJECUTIVA_VENTAS"]);
const workTransitions:Record<WorkOrder["status"],WorkOrder["status"][]>={DRAFT:["READY_FOR_HANDOFF","CANCELLED"],READY_FOR_HANDOFF:["PENDING_PLANNING","CANCELLED"],PENDING_PLANNING:["PLANNING","CANCELLED"],PLANNING:["PENDING_ASSIGNMENT","ASSIGNED","CANCELLED"],PENDING_ASSIGNMENT:["ASSIGNED","CANCELLED"],ASSIGNED:["IN_PROGRESS","CANCELLED"],IN_PROGRESS:["IN_REVIEW","WAITING_CLIENT","COMPLETED","CANCELLED"],IN_REVIEW:["IN_PROGRESS","WAITING_CLIENT","COMPLETED"],WAITING_CLIENT:["IN_PROGRESS","IN_REVIEW","CANCELLED"],COMPLETED:["CLOSED","IN_REVIEW"],CLOSED:[],CANCELLED:[]};
const projectTransitions:Record<OperationsProject["status"],OperationsProject["status"][]>={PLANNING:["READY","ON_HOLD","CANCELLED"],READY:["IN_PROGRESS","ON_HOLD","CANCELLED"],IN_PROGRESS:["BLOCKED","INTERNAL_REVIEW","QA","WAITING_CLIENT","ON_HOLD","CANCELLED"],BLOCKED:["IN_PROGRESS","ON_HOLD","CANCELLED"],INTERNAL_REVIEW:["IN_PROGRESS","QA","WAITING_CLIENT"],QA:["IN_PROGRESS","READY_FOR_PRODUCTION","WAITING_CLIENT"],WAITING_CLIENT:["IN_PROGRESS","INTERNAL_REVIEW","QA","ON_HOLD"],READY_FOR_PRODUCTION:["PRODUCTION","QA","ON_HOLD"],PRODUCTION:["MAINTENANCE","COMPLETED","IN_PROGRESS"],MAINTENANCE:["COMPLETED","IN_PROGRESS"],COMPLETED:["MAINTENANCE","ARCHIVED"],ON_HOLD:["PLANNING","READY","IN_PROGRESS","CANCELLED"],CANCELLED:["ARCHIVED"],ARCHIVED:[]};
const taskTransitions:Record<OperationsTask["status"],OperationsTask["status"][]>={BACKLOG:["TODO","CANCELLED"],TODO:["BACKLOG","IN_PROGRESS","BLOCKED","CANCELLED"],IN_PROGRESS:["TODO","BLOCKED","REVIEW","QA","DONE","CANCELLED"],BLOCKED:["TODO","IN_PROGRESS","CANCELLED"],REVIEW:["IN_PROGRESS","QA","DONE"],QA:["IN_PROGRESS","REVIEW","DONE"],DONE:["IN_PROGRESS"],CANCELLED:[]};
const asNumber=(value:unknown,label:string,min=0)=>{const number=Number(value);if(!Number.isFinite(number)||number<min)throw new BadRequestException(`${label} inválido.`);return number;};

@Injectable()
export class OperationsService{
  constructor(private readonly repository:OperationsRepository){}
  listWorkOrders(q:OperationsPageInput,actor:OperationsActor){return this.repository.listWorkOrders(this.scope(q,actor));}
  async getWorkOrder(id:string,actor:OperationsActor){const item=await this.repository.getWorkOrder(id);if(!item)throw new NotFoundException("Orden de trabajo no encontrada.");if(!managerRoles.has(actor.role)&&!commercialRoles.has(actor.role)&&actor.userId&&![item.assignedTo,item.developmentManagerId,item.commercialOwnerId].includes(actor.userId))throw new ForbiddenException("No tienes acceso a esta orden de trabajo.");return item;}
  async createWorkOrder(body:any,actor:OperationsActor){if(!managerRoles.has(actor.role)&&!commercialRoles.has(actor.role))throw new ForbiddenException();const item=await this.repository.createWorkOrder({clientId:optionalUuid(body.clientId,"Cliente"),quoteId:optionalUuid(body.quoteId,"Cotización"),saleId:optionalUuid(body.saleId,"Venta"),contractId:optionalUuid(body.contractId,"Contrato"),handoffId:optionalUuid(body.handoffId,"Handoff"),title:required(body.title,"Título"),description:body.description||null,scope:required(body.scope,"Alcance"),commercialSnapshot:body.commercialSnapshot??{},priority:body.priority||"NORMAL",status:body.status||"DRAFT",commercialOwnerId:optionalUuid(body.commercialOwnerId,"Responsable comercial"),developmentManagerId:optionalUuid(body.developmentManagerId,"Jefe de Desarrollo"),assignedTo:optionalUuid(body.assignedTo,"Responsable"),plannedStartDate:body.plannedStartDate||null,targetDate:body.targetDate||null,estimatedHours:body.estimatedHours===null||body.estimatedHours===undefined?null:asNumber(body.estimatedHours,"Horas estimadas"),budgetReference:body.budgetReference===null||body.budgetReference===undefined?null:asNumber(body.budgetReference,"Referencia comercial"),currency:body.currency||"CLP",createdBy:actor.userId});await this.repository.publish("WORK_ORDER",item.id,"WORK_ORDER_CREATED",actor.userId,{clientId:item.clientId,quoteId:item.quoteId},null,item.id);return item;}
  async updateWorkOrder(id:string,body:any,actor:OperationsActor){await this.getWorkOrder(id,actor);const item=await this.repository.updateWorkOrder(id,{title:body.title?.trim(),description:body.description,scope:body.scope?.trim(),priority:body.priority,commercialOwnerId:body.commercialOwnerId===undefined?undefined:optionalUuid(body.commercialOwnerId,"Responsable comercial"),developmentManagerId:body.developmentManagerId===undefined?undefined:optionalUuid(body.developmentManagerId,"Jefe de Desarrollo"),assignedTo:body.assignedTo===undefined?undefined:optionalUuid(body.assignedTo,"Responsable"),plannedStartDate:body.plannedStartDate,targetDate:body.targetDate,estimatedHours:body.estimatedHours===undefined?undefined:asNumber(body.estimatedHours,"Horas estimadas"),commercialSnapshot:body.commercialSnapshot});await this.repository.publish("WORK_ORDER",id,"WORK_ORDER_UPDATED",actor.userId,{},null,id);return item;}
  async workOrderStatus(id:string,status:WorkOrder["status"],reason:string|null,actor:OperationsActor,override=false){const current=await this.getWorkOrder(id,actor);if(!workTransitions[current.status]?.includes(status)){if(!override||actor.role!=="GERENTE_GENERAL")throw new BadRequestException(`Transición ${current.status} → ${status} no permitida.`);required(reason,"Motivo del override");}if(["CANCELLED","CLOSED"].includes(status))required(reason,"Motivo");return this.repository.transitionWorkOrder(id,status,actor.userId,reason);}
  async acceptHandoff(id:string,actor:OperationsActor){return this.workOrderStatus(id,"PENDING_PLANNING","Handoff aceptado",actor);}
  async requestInformation(id:string,reason:string,actor:OperationsActor){required(reason,"Motivo");const item=await this.getWorkOrder(id,actor);await this.repository.publish("WORK_ORDER",id,"HANDOFF_INFORMATION_REQUESTED",actor.userId,{reason,commercialOwnerId:item.commercialOwnerId},null,id);return item;}
  async planWorkOrder(id:string,body:any,actor:OperationsActor){const item=await this.getWorkOrder(id,actor);if(!["PENDING_PLANNING","PLANNING"].includes(item.status))throw new BadRequestException("La OT no está disponible para planificación.");if(!body.plannedStartDate||!body.targetDate)throw new BadRequestException("Inicio y deadline son obligatorios.");await this.repository.updateWorkOrder(id,{plannedStartDate:body.plannedStartDate,targetDate:body.targetDate,estimatedHours:asNumber(body.estimatedHours,"Horas estimadas",1),developmentManagerId:optionalUuid(body.developmentManagerId,"Jefe de Desarrollo")});return this.repository.transitionWorkOrder(id,body.assignedTo?"ASSIGNED":"PENDING_ASSIGNMENT",actor.userId,"Planificación completada");}
  async assignWorkOrder(id:string,userId:string,actor:OperationsActor){const assignee=optionalUuid(userId,"Responsable");if(!assignee)throw new BadRequestException("Responsable obligatorio.");await this.getWorkOrder(id,actor);await this.repository.updateWorkOrder(id,{assignedTo:assignee});const current=await this.repository.getWorkOrder(id);const item=current&&["PLANNING","PENDING_ASSIGNMENT"].includes(current.status)?await this.repository.transitionWorkOrder(id,"ASSIGNED",actor.userId,"Responsable asignado"):current!;await this.repository.publish("WORK_ORDER",id,"WORK_ORDER_ASSIGNED",actor.userId,{assignedTo:assignee},null,id);return item;}
  async convertWorkOrder(id:string,body:any,key:string,actor:OperationsActor){const work=await this.getWorkOrder(id,actor);if(!["ASSIGNED","IN_PROGRESS","PLANNING","PENDING_ASSIGNMENT"].includes(work.status))throw new BadRequestException("La OT debe estar planificada antes de crear el proyecto.");if(!key?.trim())throw new BadRequestException("Idempotency-Key obligatorio.");return this.repository.createProjectFromWorkOrder(id,{name:body.name||work.title,description:body.description||work.description,scope:body.scope||work.scope,projectLeadId:optionalUuid(body.projectLeadId||work.assignedTo,"Líder"),developmentManagerId:optionalUuid(body.developmentManagerId||work.developmentManagerId,"Jefe de Desarrollo"),plannedStartDate:body.plannedStartDate||work.plannedStartDate,targetDate:body.targetDate||work.targetDate,estimatedHours:body.estimatedHours??work.estimatedHours,budgetedHours:body.budgetedHours??work.estimatedHours,clientVisibility:body.clientVisibility||"INTERNAL"},actor.userId,key);}

  listProjects(q:OperationsPageInput,actor:OperationsActor){return this.repository.listProjects(this.projectScope(q,actor));}
  async getProject(id:string,actor:OperationsActor){const item=await this.repository.getProject(id);if(!item)throw new NotFoundException("Proyecto no encontrado.");await this.assertProjectAccess(item,actor);return item;}
  async createProject(body:any,actor:OperationsActor){if(!managerRoles.has(actor.role))throw new ForbiddenException();const workOrderId=optionalUuid(body.workOrderId,"Orden de trabajo");if(!workOrderId)throw new BadRequestException("Orden de trabajo obligatoria.");return this.repository.createProject({workOrderId,clientId:optionalUuid(body.clientId,"Cliente"),name:required(body.name,"Nombre"),description:body.description||null,scope:required(body.scope,"Alcance"),priority:body.priority||"NORMAL",projectLeadId:optionalUuid(body.projectLeadId,"Líder"),developmentManagerId:optionalUuid(body.developmentManagerId,"Jefe de Desarrollo"),plannedStartDate:body.plannedStartDate||null,targetDate:body.targetDate||null,estimatedHours:body.estimatedHours?asNumber(body.estimatedHours,"Horas estimadas"):null,budgetedHours:body.budgetedHours?asNumber(body.budgetedHours,"Horas presupuestadas"):null,createdBy:actor.userId});}
  async updateProject(id:string,body:any,actor:OperationsActor){await this.getProject(id,actor);return this.repository.updateProject(id,{name:body.name?.trim(),description:body.description,scope:body.scope?.trim(),priority:body.priority,projectLeadId:body.projectLeadId===undefined?undefined:optionalUuid(body.projectLeadId,"Líder"),developmentManagerId:body.developmentManagerId===undefined?undefined:optionalUuid(body.developmentManagerId,"Jefe de Desarrollo"),plannedStartDate:body.plannedStartDate,targetDate:body.targetDate,estimatedHours:body.estimatedHours===undefined?undefined:asNumber(body.estimatedHours,"Horas estimadas"),budgetedHours:body.budgetedHours===undefined?undefined:asNumber(body.budgetedHours,"Horas presupuestadas"),stagingUrl:body.stagingUrl,productionUrl:body.productionUrl,repositoryUrl:body.repositoryUrl,clientVisibility:body.clientVisibility});}
  async projectStatus(id:string,status:OperationsProject["status"],reason:string|null,actor:OperationsActor,override=false){const current=await this.getProject(id,actor);if(!projectTransitions[current.status]?.includes(status)){if(!override||actor.role!=="GERENTE_GENERAL")throw new BadRequestException(`Transición ${current.status} → ${status} no permitida.`);required(reason,"Motivo del override");}if(["CANCELLED","ARCHIVED"].includes(status))required(reason,"Motivo");return this.repository.transitionProject(id,status,actor.userId,reason);}
  async projectSummary(id:string,actor:OperationsActor):Promise<ProjectOperationalSummary>{const project=await this.getProject(id,actor);const[milestones,tasks,worklogs,members,deliverables,risks]=await Promise.all([this.repository.listMilestones(id),this.repository.listTasks({page:1,pageSize:100,projectId:id}),this.repository.listWorklogs({page:1,pageSize:100,projectId:id}),this.repository.listMembers(id),this.repository.listDeliverables({page:1,pageSize:100,projectId:id}),this.repository.listRisks(id)]);const today=new Date().toISOString().slice(0,10),usedMinutes=worklogs.items.reduce((s,i)=>s+i.durationMinutes,0),estimated=project.estimatedHours===null?null:project.estimatedHours*60;return{project,nextMilestone:milestones.filter(i=>i.status!=="COMPLETED"&&i.status!=="CANCELLED").sort((a,b)=>(a.dueDate||"9999").localeCompare(b.dueDate||"9999"))[0]??null,openTasks:tasks.items.filter(i=>!["DONE","CANCELLED"].includes(i.status)).length,overdueTasks:tasks.items.filter(i=>Boolean(i.dueDate&&i.dueDate<today&&!['DONE','CANCELLED'].includes(i.status))).length,blockedTasks:tasks.items.filter(i=>i.status==="BLOCKED").length,usedMinutes,remainingMinutes:estimated===null?null:estimated-usedMinutes,members:members.length,pendingDeliverables:deliverables.items.filter(i=>!["APPROVED","DELIVERED","CANCELLED"].includes(i.status)).length,activeRisks:risks.filter(i=>i.status!=="RESOLVED").length};}

  async listMembers(projectId:string,actor:OperationsActor){await this.getProject(projectId,actor);return this.repository.listMembers(projectId);}
  async addMember(projectId:string,body:any,actor:OperationsActor){await this.getProject(projectId,actor);const userId=optionalUuid(body.userId,"Usuario");if(!userId)throw new BadRequestException("Usuario obligatorio.");const item=await this.repository.addMember(projectId,{userId,userName:body.userName?.trim()||null,projectRole:body.projectRole||"DEVELOPER",allocationPercentage:body.allocationPercentage===undefined?null:asNumber(body.allocationPercentage,"Asignación"),assignedBy:actor.userId});await this.repository.publish("PROJECT_MEMBER",item.id,"MEMBER_ADDED",actor.userId,{projectId,userId},projectId);return item;}
  async updateMember(projectId:string,id:string,body:any,actor:OperationsActor){await this.getProject(projectId,actor);return this.repository.updateMember(id,{projectRole:body.projectRole,allocationPercentage:body.allocationPercentage});}
  async removeMember(projectId:string,id:string,actor:OperationsActor){await this.getProject(projectId,actor);const item=await this.repository.removeMember(id);await this.repository.publish("PROJECT_MEMBER",id,"MEMBER_REMOVED",actor.userId,{projectId,userId:item.userId},projectId);return item;}

  async milestones(projectId:string|undefined,actor:OperationsActor){if(projectId)await this.getProject(projectId,actor);return this.repository.listMilestones(projectId);}
  async createMilestone(projectId:string,body:any,actor:OperationsActor){await this.getProject(projectId,actor);const weight=asNumber(body.weight,"Peso");const current=await this.repository.listMilestones(projectId);if(current.filter(i=>i.status!=="CANCELLED").reduce((s,i)=>s+i.weight,0)+weight>100)throw new BadRequestException("La suma de pesos de los hitos no puede superar 100%.");const item=await this.repository.createMilestone(projectId,{name:required(body.name,"Nombre"),description:body.description||null,weight,plannedStartDate:body.plannedStartDate||null,dueDate:body.dueDate||null,responsibleUserId:optionalUuid(body.responsibleUserId,"Responsable"),clientVisibility:body.clientVisibility||"INTERNAL",sortOrder:body.sortOrder});await this.repository.publish("MILESTONE",item.id,"MILESTONE_CREATED",actor.userId,{projectId},projectId);return item;}
  async updateMilestone(id:string,body:any,actor:OperationsActor){const all=await this.repository.listMilestones();const current=all.find(i=>i.id===id);if(!current)throw new NotFoundException("Hito no encontrado.");await this.getProject(current.projectId,actor);return this.repository.updateMilestone(id,body);}
  async completeMilestone(id:string,actor:OperationsActor){const all=await this.repository.listMilestones();const current=all.find(i=>i.id===id);if(!current)throw new NotFoundException("Hito no encontrado.");await this.getProject(current.projectId,actor);return this.repository.completeMilestone(id,actor.userId);}

  listTasks(q:OperationsPageInput,actor:OperationsActor){return this.repository.listTasks(this.scope(q,actor));}
  async getTask(id:string,actor:OperationsActor){const item=await this.repository.getTask(id);if(!item)throw new NotFoundException("Tarea no encontrada.");await this.getProject(item.projectId,actor);return item;}
  async createTask(body:any,actor:OperationsActor){const projectId=optionalUuid(body.projectId,"Proyecto");if(!projectId)throw new BadRequestException("Proyecto obligatorio.");await this.getProject(projectId,actor);if(body.parentTaskId){const parent=await this.repository.getTask(body.parentTaskId);if(!parent||parent.projectId!==projectId)throw new BadRequestException("La subtarea debe pertenecer al mismo proyecto.");}const item=await this.repository.createTask({projectId,milestoneId:optionalUuid(body.milestoneId,"Hito"),parentTaskId:optionalUuid(body.parentTaskId,"Tarea padre"),title:required(body.title,"Título"),description:body.description||null,status:body.status||"BACKLOG",priority:body.priority||"NORMAL",assignedTo:optionalUuid(body.assignedTo,"Responsable"),createdBy:actor.userId,estimatedMinutes:body.estimatedMinutes===undefined?null:asNumber(body.estimatedMinutes,"Estimación"),startDate:body.startDate||null,dueDate:body.dueDate||null,clientVisibility:body.clientVisibility||"INTERNAL"});await this.repository.publish("TASK",item.id,"TASK_CREATED",actor.userId,{projectId,assignedTo:item.assignedTo},projectId);return item;}
  async updateTask(id:string,body:any,actor:OperationsActor){await this.getTask(id,actor);return this.repository.updateTask(id,{title:body.title?.trim(),description:body.description,milestoneId:body.milestoneId===undefined?undefined:optionalUuid(body.milestoneId,"Hito"),parentTaskId:body.parentTaskId===undefined?undefined:optionalUuid(body.parentTaskId,"Tarea padre"),priority:body.priority,assignedTo:body.assignedTo===undefined?undefined:optionalUuid(body.assignedTo,"Responsable"),estimatedMinutes:body.estimatedMinutes===undefined?undefined:asNumber(body.estimatedMinutes,"Estimación"),startDate:body.startDate,dueDate:body.dueDate,clientVisibility:body.clientVisibility});}
  async taskStatus(id:string,status:OperationsTask["status"],reason:string|null,type:string|null,actor:OperationsActor){const current=await this.getTask(id,actor);if(!taskTransitions[current.status]?.includes(status))throw new BadRequestException(`Transición ${current.status} → ${status} no permitida.`);if(status==="BLOCKED")required(reason,"Motivo del bloqueo");return this.repository.transitionTask(id,status,actor.userId,reason,type);}
  async dependency(taskId:string,body:any,actor:OperationsActor){const task=await this.getTask(taskId,actor),dependsOn=await this.getTask(required(body.dependsOnTaskId,"Tarea dependiente"),actor);if(task.projectId!==dependsOn.projectId)throw new BadRequestException("Las dependencias deben pertenecer al mismo proyecto.");if(task.id===dependsOn.id)throw new BadRequestException("Una tarea no puede depender de sí misma.");const existing=await this.repository.listDependencies();const reaches=(from:string,target:string,visited=new Set<string>()):boolean=>{if(from===target)return true;if(visited.has(from))return false;visited.add(from);return existing.filter(i=>i.taskId===from).some(i=>reaches(i.dependsOnTaskId,target,visited));};if(reaches(dependsOn.id,task.id))throw new BadRequestException("La dependencia crea un ciclo.");return this.repository.addDependency({taskId,dependsOnTaskId:dependsOn.id,dependencyType:body.dependencyType||"REQUIRES"});}

  listWorklogs(q:OperationsPageInput,actor:OperationsActor){return this.repository.listWorklogs(this.scope(q,actor));}
  async createWorklog(body:any,actor:OperationsActor){const projectId=optionalUuid(body.projectId,"Proyecto");if(!projectId)throw new BadRequestException("Proyecto obligatorio.");await this.getProject(projectId,actor);const userId=actor.userId||optionalUuid(body.userId,"Usuario");if(!userId)throw new BadRequestException("Usuario obligatorio.");const item=await this.repository.createWorklog({projectId,taskId:optionalUuid(body.taskId,"Tarea"),userId,workDate:body.workDate||new Date().toISOString().slice(0,10),startedAt:body.startedAt||null,durationMinutes:asNumber(body.durationMinutes,"Duración",1),description:required(body.description,"Descripción"),publicDescription:body.publicDescription||null,workType:body.workType||"DEVELOPMENT",billable:Boolean(body.billable),clientVisibility:body.clientVisibility||"INTERNAL",commitReference:body.commitReference||null,deploymentId:optionalUuid(body.deploymentId,"Deployment")});await this.repository.publish("WORKLOG",item.id,"WORKLOG_CREATED",actor.userId,{projectId,durationMinutes:item.durationMinutes},projectId);return item;}
  async updateWorklog(id:string,body:any,actor:OperationsActor){const current=await this.repository.getWorklog(id);if(!current)throw new NotFoundException("Worklog no encontrado.");if(!managerRoles.has(actor.role)&&current.userId!==actor.userId)throw new ForbiddenException("Solo puedes editar tus propios registros de trabajo.");return this.repository.updateWorklog(id,{durationMinutes:body.durationMinutes===undefined?undefined:asNumber(body.durationMinutes,"Duración",1),description:body.description?.trim(),publicDescription:body.publicDescription,workType:body.workType,billable:body.billable,clientVisibility:body.clientVisibility});}
  deleteWorklog(id:string,actor:OperationsActor){if(!managerRoles.has(actor.role))throw new ForbiddenException();return this.repository.deleteWorklog(id);}

  listDeliverables(q:OperationsPageInput,actor:OperationsActor){return this.repository.listDeliverables(this.scope(q,actor));}
  async createDeliverable(body:any,actor:OperationsActor){const projectId=optionalUuid(body.projectId,"Proyecto");if(!projectId)throw new BadRequestException("Proyecto obligatorio.");await this.getProject(projectId,actor);const item=await this.repository.createDeliverable({projectId,milestoneId:optionalUuid(body.milestoneId,"Hito"),name:required(body.name,"Nombre"),description:body.description||null,type:body.type||"OTHER",dueDate:body.dueDate||null,ownerId:optionalUuid(body.ownerId,"Responsable"),documentId:optionalUuid(body.documentId,"Documento"),externalUrl:body.externalUrl||null,clientVisibility:body.clientVisibility||"INTERNAL"});await this.repository.publish("DELIVERABLE",item.id,"DELIVERABLE_CREATED",actor.userId,{projectId},projectId);return item;}
  async deliverableAction(id:string,action:"submit"|"approve"|"changes",body:any,actor:OperationsActor){const status=action==="submit"?"READY_FOR_REVIEW":action==="approve"?"APPROVED":"CHANGES_REQUESTED";if(action==="approve"&&!managerRoles.has(actor.role))throw new ForbiddenException();if(action==="changes")required(body.reason,"Motivo");const item=await this.repository.updateDeliverable(id,{status,submittedAt:action==="submit"?new Date().toISOString():undefined,approvedAt:action==="approve"?new Date().toISOString():undefined,approvedBy:action==="approve"?actor.userId:undefined});await this.repository.publish("DELIVERABLE",id,action==="approve"?"DELIVERABLE_APPROVED":action==="submit"?"DELIVERABLE_READY":"DELIVERABLE_CHANGES_REQUESTED",actor.userId,{projectId:item.projectId,reason:body.reason},item.projectId);return item;}

  listDeployments(q:OperationsPageInput,actor:OperationsActor){return this.repository.listDeployments(this.scope(q,actor));}
  async getDeployment(id:string,actor:OperationsActor){const item=await this.repository.getDeployment(id);if(!item)throw new NotFoundException("Deployment no encontrado.");await this.getProject(item.projectId,actor);return item;}
  async createDeployment(body:any,actor:OperationsActor){const projectId=optionalUuid(body.projectId,"Proyecto");if(!projectId)throw new BadRequestException("Proyecto obligatorio.");await this.getProject(projectId,actor);const item=await this.repository.createDeployment({projectId,environment:body.environment||"STAGING",version:required(body.version,"Versión"),commitSha:body.commitSha||null,status:body.status||"PLANNED",recordType:"MANUAL_RECORD",requestedBy:actor.userId,deployedBy:optionalUuid(body.deployedBy,"Responsable"),startedAt:body.startedAt||null,completedAt:body.completedAt||null,notes:body.notes||null,clientVisibility:body.clientVisibility||"INTERNAL"});await this.repository.publish("DEPLOYMENT",item.id,"DEPLOYMENT_RECORDED",actor.userId,{projectId,manual:true},projectId);return item;}
  async updateDeployment(id:string,body:any,actor:OperationsActor){await this.getDeployment(id,actor);const item=await this.repository.updateDeployment(id,body);if(["SUCCESS","FAILED","ROLLED_BACK"].includes(item.status))await this.repository.publish("DEPLOYMENT",id,item.status==="SUCCESS"?"DEPLOYMENT_COMPLETED":`DEPLOYMENT_${item.status}`,actor.userId,{projectId:item.projectId,manual:item.recordType==="MANUAL_RECORD"},item.projectId);return item;}

  async endpoints(projectId:string,actor:OperationsActor){await this.getProject(projectId,actor);return this.repository.listEndpoints(projectId);}
  async createEndpoint(projectId:string,body:any,actor:OperationsActor){await this.getProject(projectId,actor);try{new URL(required(body.url,"URL"));}catch{throw new BadRequestException("URL inválida.");}return this.repository.createEndpoint(projectId,{name:required(body.name,"Nombre"),url:body.url,environment:body.environment||"PRODUCTION",endpointType:body.endpointType||"WEB",monitoringEnabled:Boolean(body.monitoringEnabled),responsibleUserId:optionalUuid(body.responsibleUserId,"Responsable")});}
  async risks(projectId:string,actor:OperationsActor){await this.getProject(projectId,actor);return this.repository.listRisks(projectId);}
  async createRisk(projectId:string,body:any,actor:OperationsActor){await this.getProject(projectId,actor);const item=await this.repository.createRisk(projectId,{title:required(body.title,"Título"),description:body.description||null,probability:asNumber(body.probability,"Probabilidad",1),impact:asNumber(body.impact,"Impacto",1),ownerId:optionalUuid(body.ownerId,"Responsable"),mitigation:body.mitigation||null});await this.repository.publish("RISK",item.id,"PROJECT_RISK_CREATED",actor.userId,{projectId,severity:item.severity},projectId);return item;}
  async changes(projectId:string,actor:OperationsActor){await this.getProject(projectId,actor);return this.repository.listChanges(projectId);}
  async createChange(projectId:string,body:any,actor:OperationsActor){await this.getProject(projectId,actor);const item=await this.repository.createChange(projectId,{requestedBy:actor.userId,source:body.source||"INTERNAL",description:required(body.description,"Descripción"),reason:body.reason||null,scopeImpact:body.scopeImpact||null,timeImpact:body.timeImpact||null,costImpact:body.costImpact===undefined?null:asNumber(body.costImpact,"Impacto de costo"),currency:body.currency||"CLP"});await this.repository.publish("CHANGE_REQUEST",item.id,"CHANGE_REQUEST_CREATED",actor.userId,{projectId,costImpact:item.costImpact},projectId);return item;}

  summary(){return this.repository.summary();}
  activity(projectId?:string){return this.repository.activity(projectId);}
  async priorities(actor:OperationsActor):Promise<OperationsPriorityItem[]>{const[summary,workOrders,projects,tasks,milestones,deliverables,deployments]=await Promise.all([this.repository.summary(),this.listWorkOrders({page:1,pageSize:100},actor),this.listProjects({page:1,pageSize:100},actor),this.listTasks({page:1,pageSize:100},actor),this.repository.listMilestones(),this.listDeliverables({page:1,pageSize:100},actor),this.listDeployments({page:1,pageSize:100},actor)]);void summary;const today=new Date().toISOString().slice(0,10),items:OperationsPriorityItem[]=[];for(const i of workOrders.items.filter(i=>!i.assignedTo&&!['CLOSED','CANCELLED'].includes(i.status)))items.push({id:i.id,type:"WORK_ORDER",title:i.title,reason:"OT sin responsable",severity:"ATTENTION",href:`/work-orders/${i.id}`,dueAt:i.targetDate});for(const i of projects.items.filter(i=>i.targetDate&&i.targetDate<today&&!['COMPLETED','CANCELLED','ARCHIVED'].includes(i.status)))items.push({id:i.id,type:"PROJECT",title:i.name,reason:"Proyecto atrasado",severity:i.health==="CRITICAL"?"CRITICAL":"AT_RISK",href:`/projects/${i.id}`,dueAt:i.targetDate});for(const i of tasks.items.filter(i=>i.overdue||i.status==="BLOCKED"))items.push({id:i.id,type:"TASK",title:i.title,reason:i.status==="BLOCKED"?`Tarea bloqueada${i.blockedReason?`: ${i.blockedReason}`:""}`:"Tarea vencida",severity:i.priority==="CRITICAL"?"CRITICAL":"AT_RISK",href:`/tasks?taskId=${i.id}`,dueAt:i.dueDate});for(const i of milestones.filter(i=>i.dueDate&&i.dueDate<today&&!['COMPLETED','CANCELLED'].includes(i.status)))items.push({id:i.id,type:"MILESTONE",title:i.name,reason:"Hito atrasado",severity:"AT_RISK",href:`/milestones?projectId=${i.projectId}`,dueAt:i.dueDate});for(const i of deliverables.items.filter(i=>["READY_FOR_REVIEW","INTERNAL_REVIEW"].includes(i.status)))items.push({id:i.id,type:"DELIVERABLE",title:i.name,reason:"Entrega esperando revisión",severity:"ATTENTION",href:"/deliverables",dueAt:i.dueDate});for(const i of deployments.items.filter(i=>i.status==="FAILED"))items.push({id:i.id,type:"DEPLOYMENT",title:`${i.environment} ${i.version}`,reason:"Deployment fallido",severity:"CRITICAL",href:"/deployments",dueAt:i.completedAt});return items.sort((a,b)=>({CRITICAL:0,AT_RISK:1,ATTENTION:2}[a.severity]-{CRITICAL:0,AT_RISK:1,ATTENTION:2}[b.severity])).slice(0,30);}

  async search(query:string,actor:OperationsActor){const[workOrders,projects,tasks]=await Promise.all([this.listWorkOrders({page:1,pageSize:12,search:query},actor),this.listProjects({page:1,pageSize:12,search:query},actor),this.listTasks({page:1,pageSize:12,search:query},actor)]);return{workOrders:workOrders.items,projects:projects.items,tasks:tasks.items};}
  private scope(q:OperationsPageInput,actor:OperationsActor):OperationsPageInput{if(["TECH_LEAD","PROGRAMADOR","QA","SOPORTE_TECNICO","DESARROLLO"].includes(actor.role)&&actor.userId)return{...q,userId:actor.userId,assignedTo:q.assignedTo??actor.userId};return q;}
  private projectScope(q:OperationsPageInput,actor:OperationsActor):OperationsPageInput{if(["TECH_LEAD","PROGRAMADOR","QA","SOPORTE_TECNICO","DESARROLLO"].includes(actor.role)&&actor.userId)return{...q,userId:actor.userId};return q;}
  private async assertProjectAccess(project:OperationsProject,actor:OperationsActor){if(managerRoles.has(actor.role))return;if(commercialRoles.has(actor.role))return;if(!actor.userId) return;const ids=await this.repository.projectIdsForUser(actor.userId);if(!ids.includes(project.id))throw new ForbiddenException("No tienes acceso a este proyecto.");}
}

export function actorFromHeaders(headers:Record<string,string|undefined>):OperationsActor{return{userId:headers["x-zyteron-user-id"]||null,role:headers["x-zyteron-role"]||""};}
export function operationsPage(query:Record<string,string|undefined>):OperationsPageInput{return{...query,page:Math.max(1,Number(query.page)||1),pageSize:Math.min(100,Math.max(1,Number(query.pageSize)||25))};}
export const operationsRoles=["GERENTE_GENERAL","JEFE_DESARROLLO","TECH_LEAD","PROGRAMADOR","QA","SOPORTE_TECNICO","DESARROLLO","OPERACIONES"]as Role[];
