import { BadRequestException,ConflictException,ForbiddenException,Inject,Injectable,ServiceUnavailableException } from "@nestjs/common";
import type { DataAsset,DataSubjectRequest,PrivacyImpactAssessment,ProcessingActivity,RecoveryTest,Role,SecurityAccessGrant,SecurityAccessRequest,SecurityControl,SecurityDevice,SecurityEvent,SecurityGate,SecurityIdentity,SecurityIncident,SecurityIncidentEvent,SecurityPosture,SecurityScan,SecuritySession,SecuritySummary,SecurityVaultAccess,SecurityVaultItem,SecurityVulnerability,SecurityWorkspace,VendorSecurityRecord } from "@zyteron/contracts";
import { roles } from "@zyteron/contracts";
import { SecurityProviderStatus,VaultSecretProvider } from "./security.providers.js";
import { SecurityRepository } from "./security.repository.js";

export interface SecurityActor{userId:string|null;role:string;aal:"aal1"|"aal2";sessionId:string|null;requestId:string|null;}
type Row=Record<string,any>;
const now=()=>new Date().toISOString();
const required=(value:unknown,label:string)=>{const result=String(value??"").trim();if(!result)throw new BadRequestException(`${label} es obligatorio.`);return result;};
const safeMetadata=(value:unknown):Record<string,unknown>=>{
  const blocked=/password|secret|token|authorization|cookie|otp|private.?key|cvv|card.?number|credential/i;
  const walk=(item:unknown):unknown=>Array.isArray(item)?item.slice(0,50).map(walk):item&&typeof item==="object"?Object.fromEntries(Object.entries(item as Record<string,unknown>).filter(([key])=>!blocked.test(key)).map(([key,entry])=>[key,walk(entry)])):typeof item==="string"?item.slice(0,500):item;
  return walk(value)as Record<string,unknown>;
};
const rejectSecretPayload=(value:Record<string,unknown>)=>{const key=Object.keys(value).find(item=>/secret.?value|password|plaintext|private.?key|api.?key|token/i.test(item));if(key)throw new BadRequestException(`El campo ${key} no puede enviarse a esta API.`);};
const securityRoles=["GERENTE_GENERAL","SECURITY_ADMIN"];

@Injectable()
export class SecurityService{
  constructor(private readonly repository:SecurityRepository,@Inject(VaultSecretProvider)private readonly vaultProvider:VaultSecretProvider,private readonly providers:SecurityProviderStatus){}

  private assertAdmin(actor:SecurityActor){if(!securityRoles.includes(actor.role))throw new ForbiddenException("La operación requiere administración de seguridad.");}
  private assertAal2(actor:SecurityActor){if(actor.aal!=="aal2")throw new ForbiddenException("La operación requiere MFA verificado (AAL2).");}
  private async audit(actor:SecurityActor,action:string,resourceType:string,resourceId:string|null,result="SUCCESS",before:unknown=null,after:unknown=null,reason:string|null=null){return this.repository.create("security_audit_events",{actorUserId:actor.userId,actorRole:actor.role,action,resourceType,resourceId,beforeSafe:safeMetadata(before),afterSafe:safeMetadata(after),reason,requestId:actor.requestId,result,occurredAt:now()});}
  private async event(input:Partial<SecurityEvent>&Pick<SecurityEvent,"eventType"|"severity"|"description">,actor?:SecurityActor){return this.repository.create<SecurityEvent>("security_events",{id:"",eventType:input.eventType,severity:input.severity,actorUserId:input.actorUserId??actor?.userId??null,sessionId:input.sessionId??actor?.sessionId??null,ipMasked:null,deviceId:null,resourceType:input.resourceType??null,resourceId:input.resourceId??null,description:input.description,metadataSafe:safeMetadata(input.metadataSafe??{}),detectedAt:now(),status:"OPEN",acknowledgedBy:null,acknowledgedAt:null});}
  private async expireGrants(){const grants=await this.repository.list<SecurityAccessGrant>("access_grants",{status:"ACTIVE"});for(const grant of grants)if(grant.expiresAt<=now())await this.repository.update("access_grants",grant.id,{status:"EXPIRED"});}

  async identities():Promise<SecurityIdentity[]>{
    const supabase=this.repository.supabase;if(!supabase)return[];
    const{data,error}=await supabase.auth.admin.listUsers({page:1,perPage:1000});if(error)throw error;
    return data.users.map((user):SecurityIdentity=>{const rawRole=user.app_metadata.role,role=roles.includes(rawRole as Role)?rawRole as Role:null,factors=(user as any).factors as Array<{status?:string}>|undefined;return{id:user.id,email:user.email??"",name:String(user.user_metadata.full_name??user.user_metadata.name??user.email??"Usuario"),identityType:role==="PORTAL_CLIENT"?"CLIENT_USER":"INTERNAL_USER",role,active:!user.banned_until||new Date(user.banned_until)<=new Date(),mfaStatus:factors?.some(item=>item.status==="verified")?"ENROLLED":factors?"NOT_ENROLLED":"UNKNOWN",lastSignInAt:user.last_sign_in_at??null,createdAt:user.created_at};}).sort((a,b)=>a.name.localeCompare(b.name,"es-CL"));
  }

  async workspace(actor:SecurityActor):Promise<SecurityWorkspace>{
    this.assertAdmin(actor);await this.expireGrants();
    const[identities,sessions,devices,accessRequests,accessGrants,accessReviews,vaultItems,vaultAccesses,events,incidents,incidentEvents,vulnerabilities,controls,scans,dataAssets,processingActivities,subjectRequests,dpias,privacyBreaches,retentionPolicies,dataExports,vendors,backupTargets,recoveryTests,disasterRecoveryPlans,threatModels,gates,settings,permissions,rolePermissions]=await Promise.all([
      this.identities(),this.repository.list<SecuritySession>("security_session_metadata"),this.repository.list<SecurityDevice>("registered_devices"),this.repository.list<SecurityAccessRequest>("access_requests"),this.repository.list<SecurityAccessGrant>("access_grants"),this.repository.list<Row>("access_reviews"),this.repository.list<SecurityVaultItem>("vault_items"),this.repository.list<SecurityVaultAccess>("vault_access_events",{},"occurred_at"),this.repository.list<SecurityEvent>("security_events",{},"detected_at"),this.repository.list<SecurityIncident>("security_incidents",{},"detected_at"),this.repository.list<SecurityIncidentEvent>("security_incident_events",{},"occurred_at"),this.repository.list<SecurityVulnerability>("security_vulnerabilities",{},"detected_at"),this.repository.list<SecurityControl>("security_controls"),this.repository.list<SecurityScan>("security_scans"),this.repository.list<DataAsset>("data_assets"),this.repository.list<ProcessingActivity>("processing_activities"),this.repository.list<DataSubjectRequest>("data_subject_requests"),this.repository.list<PrivacyImpactAssessment>("privacy_impact_assessments"),this.repository.list<Row>("privacy_breach_assessments"),this.repository.list<Row>("retention_policies"),this.repository.list<Row>("data_export_events",{},"occurred_at"),this.repository.list<VendorSecurityRecord>("vendor_security_registry"),this.repository.list<Row>("backup_targets"),this.repository.list<RecoveryTest>("recovery_tests"),this.repository.list<Row>("disaster_recovery_plans"),this.repository.list<Row>("threat_models"),this.repository.list<SecurityGate>("production_security_gates",{},"evaluated_at"),this.repository.list<Row>("security_settings",{},"key",true),this.repository.list<{code:string;description:string}>("app_permissions",{},"code",true),this.repository.list<{role:string;permissionCode:string}>("role_permissions",{},"role",true),
    ]);
    const privileged=await this.repository.setting<string[]>("privileged_roles")??[];
    const rolesView=[...new Set(rolePermissions.map(item=>item.role))].sort().map(role=>({role,permissionCount:rolePermissions.filter(item=>item.role===role).length,classification:(role==="SECURITY_ADMIN"?"SECURITY_CRITICAL":privileged.includes(role)?"PRIVILEGED":"STANDARD")as "STANDARD"|"SENSITIVE"|"PRIVILEGED"|"SECURITY_CRITICAL"}));
    const gate=gates[0],summary=await this.summary({identities,sessions,devices,accessRequests,vaultAccesses,events,incidents,vulnerabilities,controls,scans,backupTargets,recoveryTests,gate,privileged}),posture=this.posture(summary,controls,scans);
    return{summary,posture,identities,sessions,devices,accessRequests,accessGrants,accessReviews,vaultItems:vaultItems.map(item=>({...item,encryptedReference:"[REDACTED]"})),vaultAccesses,events,incidents,incidentEvents,vulnerabilities,controls,scans,dataAssets,processingActivities,subjectRequests,dpias,privacyBreaches,retentionPolicies,dataExports,vendors,backupTargets,recoveryTests,disasterRecoveryPlans,threatModels,gates,settings,roles:rolesView,permissions,providers:this.providers.snapshot(),generatedAt:now()};
  }

  private async summary(input:{identities:SecurityIdentity[];sessions:SecuritySession[];devices:SecurityDevice[];accessRequests:SecurityAccessRequest[];vaultAccesses:SecurityVaultAccess[];events:SecurityEvent[];incidents:SecurityIncident[];vulnerabilities:SecurityVulnerability[];controls:SecurityControl[];scans:SecurityScan[];backupTargets:Row[];recoveryTests:RecoveryTest[];gate?:SecurityGate;privileged:string[]}):Promise<SecuritySummary>{
    const openEvents=input.events.filter(item=>!["FALSE_POSITIVE","CLOSED"].includes(item.status)),privilegedUsers=input.identities.filter(item=>item.role&&input.privileged.includes(item.role)),mfaKnown=privilegedUsers.filter(item=>item.mfaStatus!=="UNKNOWN"),passedRestores=input.recoveryTests.filter(item=>item.result==="PASSED");
    return{criticalEvents:openEvents.filter(item=>item.severity==="CRITICAL").length,highEvents:openEvents.filter(item=>item.severity==="HIGH").length,loginFailures:openEvents.filter(item=>item.eventType==="LOGIN_FAILED").length,newDevices:input.devices.filter(item=>item.trustStatus==="NEW").length,mfaCoverage:mfaKnown.length?Math.round(mfaKnown.filter(item=>item.mfaStatus==="ENROLLED").length/mfaKnown.length*100):null,privilegedAccounts:privilegedUsers.length,activePrivilegedSessions:input.sessions.filter(item=>item.status==="ACTIVE"&&input.privileged.includes(item.role??"")).length,accessRequests:input.accessRequests.filter(item=>["REQUESTED","UNDER_REVIEW"].includes(item.status)).length,vaultAccesses:input.vaultAccesses.filter(item=>item.action==="REVEAL"&&item.result==="ALLOWED").length,rlsFindings:input.controls.filter(item=>item.controlCode.startsWith("RLS-")&&["FAILED","NOT_IMPLEMENTED"].includes(item.status)).length,openVulnerabilities:input.vulnerabilities.filter(item=>!["VERIFIED","FALSE_POSITIVE"].includes(item.status)).length,exposedSecretFindings:openEvents.filter(item=>item.eventType==="SECRET_DETECTED").length,openIncidents:input.incidents.filter(item=>!["CLOSED","RESOLVED"].includes(item.status)).length,backupStatus:input.backupTargets.length?input.backupTargets.every(item=>item.status==="HEALTHY")?"HEALTHY":"AT_RISK":"NOT_CONFIGURED",restoreStatus:passedRestores.length?"VALIDATED":input.recoveryTests.some(item=>item.result==="FAILED")?"FAILED":"NEVER_VALIDATED",gateStatus:input.gate?.status??"NOT_EVALUATED"};
  }
  private posture(summary:SecuritySummary,controls:SecurityControl[],scans:SecurityScan[]):SecurityPosture{
    const reasons:SecurityPosture["reasons"]=[
      {key:"critical-events",label:"Eventos críticos",status:summary.criticalEvents?"CRITICAL":"HEALTHY",explanation:summary.criticalEvents?`${summary.criticalEvents} eventos críticos abiertos.`:"No existen eventos críticos abiertos.",href:"/security/events"},
      {key:"vulnerabilities",label:"Vulnerabilidades",status:summary.openVulnerabilities?"AT_RISK":"HEALTHY",explanation:summary.openVulnerabilities?`${summary.openVulnerabilities} hallazgos requieren tratamiento.`:"No existen vulnerabilidades abiertas registradas.",href:"/security/vulnerabilities"},
      {key:"mfa",label:"Cobertura MFA privilegiada",status:summary.mfaCoverage===100?"HEALTHY":summary.mfaCoverage===null?"UNKNOWN":"AT_RISK",explanation:summary.mfaCoverage===null?"No existe evidencia suficiente para calcular cobertura.":`${summary.mfaCoverage}% de cuentas privilegiadas con factor verificado.`,href:"/security/mfa"},
      {key:"rls",label:"RLS y acceso",status:summary.rlsFindings?"CRITICAL":controls.some(item=>item.controlCode.startsWith("RLS-")&&item.status==="VERIFIED")?"HEALTHY":"UNKNOWN",explanation:summary.rlsFindings?`${summary.rlsFindings} controles RLS fallidos o no implementados.`:"La cobertura solo se considera sana con evidencia verificada.",href:"/security/rls"},
      {key:"backups",label:"Backup y restauración",status:summary.backupStatus==="HEALTHY"&&summary.restoreStatus==="VALIDATED"?"HEALTHY":"AT_RISK",explanation:`Backup: ${summary.backupStatus}. Restauración: ${summary.restoreStatus}.`,href:"/security/backups"},
      {key:"testing",label:"Pruebas de seguridad",status:scans.some(item=>item.status==="FAILED")?"CRITICAL":scans.length&&scans.every(item=>item.status==="PASSED")?"HEALTHY":"UNKNOWN",explanation:scans.length?"Resultado derivado de ejecuciones registradas.":"No existen ejecuciones de seguridad registradas.",href:"/security/testing"},
      {key:"gate",label:"Production Security Gate",status:summary.gateStatus==="PASS"?"HEALTHY":summary.gateStatus==="FAIL"?"CRITICAL":"ATTENTION",explanation:`Última evaluación: ${summary.gateStatus}.`,href:"/security/gate"},
    ];
    const status=reasons.some(item=>item.status==="CRITICAL")?"CRITICAL":reasons.some(item=>item.status==="AT_RISK")?"AT_RISK":reasons.some(item=>["ATTENTION","UNKNOWN"].includes(item.status))?"ATTENTION":"HEALTHY";
    return{status,reasons,evaluatedAt:now()};
  }

  async sessions(actor:SecurityActor){this.assertAdmin(actor);return this.repository.list<SecuritySession>("security_session_metadata");}
  async revokeSession(id:string,actor:SecurityActor,reason:string){this.assertAdmin(actor);this.assertAal2(actor);const current=await this.repository.get<SecuritySession>("security_session_metadata",id),next=await this.repository.update<SecuritySession>("security_session_metadata",id,{status:"REVOKED",revokedAt:now(),revokedBy:actor.userId} as Partial<SecuritySession>);await this.event({eventType:"SESSION_REVOKED",severity:"MEDIUM",resourceType:"SESSION",resourceId:id,description:"Una sesión fue revocada.",metadataSafe:{targetUserId:current.userId,reason:required(reason,"Motivo")}},actor);await this.audit(actor,"SESSION_REVOKED","SESSION",id,"SUCCESS",current,next,reason);return next;}
  async revokeUserSessions(userId:string,actor:SecurityActor,reason:string){this.assertAdmin(actor);this.assertAal2(actor);const items=await this.repository.list<SecuritySession>("security_session_metadata",{userId,status:"ACTIVE"});for(const item of items)await this.revokeSession(item.id,actor,reason);return{revoked:items.length};}
  async lockUser(userId:string,actor:SecurityActor,reason:string){this.assertAdmin(actor);this.assertAal2(actor);const duration=await this.repository.setting<string>("account_lock_duration");if(!duration)throw new ConflictException("Falta configurar account_lock_duration.");if(!this.repository.supabase)throw new ServiceUnavailableException("Supabase Auth Admin no está configurado.");const{error}=await this.repository.supabase.auth.admin.updateUserById(userId,{ban_duration:duration});if(error)throw error;await this.revokeUserSessions(userId,actor,reason);await this.audit(actor,"USER_LOCKED","USER",userId,"SUCCESS",null,{duration},reason);return{userId,status:"LOCKED",duration};}
  async devices(actor:SecurityActor){this.assertAdmin(actor);return this.repository.list<SecurityDevice>("registered_devices");}
  async deviceAction(id:string,status:SecurityDevice["trustStatus"],actor:SecurityActor,reason:string){this.assertAdmin(actor);this.assertAal2(actor);const before=await this.repository.get<SecurityDevice>("registered_devices",id),next=await this.repository.update<SecurityDevice>("registered_devices",id,{trustStatus:status});if(["BLOCKED","REVOKED"].includes(status)){const sessions=await this.repository.list<SecuritySession>("security_session_metadata",{deviceId:before.deviceId,status:"ACTIVE"});for(const session of sessions)await this.revokeSession(session.id,actor,reason);}await this.audit(actor,`DEVICE_${status}`,"DEVICE",id,"SUCCESS",before,next,reason);return next;}

  async createAccessRequest(input:Row,actor:SecurityActor){const max=await this.repository.setting<number>("jit_max_minutes");if(!max)throw new ConflictException("Falta configurar jit_max_minutes.");const minutes=Number(input.requestedMinutes);if(!Number.isFinite(minutes)||minutes<1||minutes>max)throw new BadRequestException(`La duración debe estar entre 1 y ${max} minutos.`);const item=await this.repository.create<SecurityAccessRequest>("access_requests",{id:"",requesterId:actor.userId!,resourceType:required(input.resourceType,"Recurso"),resourceId:required(input.resourceId,"ID de recurso"),permissionCode:required(input.permissionCode,"Permiso"),reason:required(input.reason,"Motivo"),requestedMinutes:minutes,status:"REQUESTED",reviewedBy:null,reviewReason:null,createdAt:"",updatedAt:""});await this.audit(actor,"ACCESS_REQUESTED","ACCESS_REQUEST",item.id,"SUCCESS",null,item,input.reason);return item;}
  async decideAccess(id:string,approved:boolean,input:Row,actor:SecurityActor){this.assertAdmin(actor);this.assertAal2(actor);const request=await this.repository.get<SecurityAccessRequest>("access_requests",id);if(request.requesterId===actor.userId)throw new ForbiddenException("La segregación de funciones impide autoaprobar el acceso.");if(request.status!=="REQUESTED"&&request.status!=="UNDER_REVIEW")throw new ConflictException("La solicitud ya fue resuelta.");const reason=required(input.reason,"Motivo de decisión");const updated=await this.repository.update<SecurityAccessRequest>("access_requests",id,{status:approved?"APPROVED":"REJECTED",reviewedBy:actor.userId,reviewReason:reason});let grant:SecurityAccessGrant|undefined;if(approved){const startsAt=now(),expiresAt=new Date(Date.now()+request.requestedMinutes*60000).toISOString();grant=await this.repository.create<SecurityAccessGrant>("access_grants",{id:"",requestId:id,userId:request.requesterId,resourceType:request.resourceType,resourceId:request.resourceId,permissionCode:request.permissionCode,startsAt,expiresAt,status:"ACTIVE",grantedBy:actor.userId!,revokedBy:null,revokedAt:null,createdAt:"",updatedAt:""});}await this.audit(actor,approved?"ACCESS_APPROVED":"ACCESS_REJECTED","ACCESS_REQUEST",id,"SUCCESS",request,{updated,grant},reason);return{request:updated,grant};}
  async revokeGrant(id:string,actor:SecurityActor,reason:string){this.assertAdmin(actor);this.assertAal2(actor);const before=await this.repository.get<SecurityAccessGrant>("access_grants",id),next=await this.repository.update<SecurityAccessGrant>("access_grants",id,{status:"REVOKED",revokedBy:actor.userId,revokedAt:now()});await this.audit(actor,"ACCESS_REVOKED","ACCESS_GRANT",id,"SUCCESS",before,next,required(reason,"Motivo"));return next;}

  async createVaultItem(input:Row,actor:SecurityActor){this.assertAdmin(actor);this.assertAal2(actor);rejectSecretPayload(input);const reference=required(input.encryptedReference,"Referencia cifrada/externa");if(reference.length<8)throw new BadRequestException("La referencia del proveedor no es válida.");const item=await this.repository.create<SecurityVaultItem>("vault_items",{id:"",name:required(input.name,"Nombre"),secretType:required(input.secretType,"Tipo"),provider:required(input.provider,"Proveedor"),encryptedReference:reference,clientId:input.clientId?String(input.clientId):null,projectId:input.projectId?String(input.projectId):null,environment:input.environment?String(input.environment):null,ownerId:input.ownerId?String(input.ownerId):actor.userId,classification:input.classification==="RESTRICTED"?"RESTRICTED":"CRITICAL",rotationPolicyId:null,rotatedAt:null,expiresAt:input.expiresAt?String(input.expiresAt):null,status:"ACTIVE",createdAt:"",updatedAt:""});await this.audit(actor,"VAULT_ITEM_CREATED","VAULT_ITEM",item.id,"SUCCESS",null,{...item,encryptedReference:"[REDACTED]"},required(input.reason,"Motivo"));return{...item,encryptedReference:"[REDACTED]"};}
  async vaultItem(id:string,actor:SecurityActor){this.assertAdmin(actor);const item=await this.repository.get<SecurityVaultItem>("vault_items",id);return{...item,encryptedReference:"[REDACTED]"};}
  async requestVaultAccess(id:string,input:Row,actor:SecurityActor){await this.repository.get("vault_items",id);return this.createAccessRequest({resourceType:"VAULT_ITEM",resourceId:id,permissionCode:"vault.reveal",reason:input.reason,requestedMinutes:input.requestedMinutes},actor);}
  async revealVaultItem(id:string,input:Row,actor:SecurityActor){this.assertAal2(actor);const reason=required(input.reason,"Motivo"),item=await this.repository.get<SecurityVaultItem>("vault_items",id),grants=await this.repository.list<SecurityAccessGrant>("access_grants",{userId:actor.userId,resourceType:"VAULT_ITEM",resourceId:id,permissionCode:"vault.reveal",status:"ACTIVE"}),grant=grants.find(value=>value.startsAt<=now()&&value.expiresAt>now());if(!grant){await this.repository.create<SecurityVaultAccess>("vault_access_events",{id:"",vaultItemId:id,actorUserId:actor.userId,action:"REVEAL",reason,sessionId:actor.sessionId,result:"DENIED",occurredAt:now()});await this.event({eventType:"VAULT_DENIED",severity:"HIGH",resourceType:"VAULT_ITEM",resourceId:id,description:"Intento de acceso a Vault denegado."},actor);throw new ForbiddenException("No existe un grant temporal activo para este secreto.");}try{const secret=await this.vaultProvider.reveal(item.encryptedReference);await this.repository.create<SecurityVaultAccess>("vault_access_events",{id:"",vaultItemId:id,actorUserId:actor.userId,action:"REVEAL",reason,sessionId:actor.sessionId,result:"ALLOWED",occurredAt:now()});await this.audit(actor,"VAULT_REVEALED","VAULT_ITEM",id,"SUCCESS",null,{grantId:grant.id},reason);return{secret,expiresAt:new Date(Date.now()+60000).toISOString()};}catch(error){await this.repository.create<SecurityVaultAccess>("vault_access_events",{id:"",vaultItemId:id,actorUserId:actor.userId,action:"REVEAL",reason,sessionId:actor.sessionId,result:"PROVIDER_UNAVAILABLE",occurredAt:now()});throw error;}}
  async rotateVaultMetadata(id:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);this.assertAal2(actor);rejectSecretPayload(input);const before=await this.repository.get<SecurityVaultItem>("vault_items",id),next=await this.repository.update<SecurityVaultItem>("vault_items",id,{encryptedReference:required(input.encryptedReference,"Nueva referencia cifrada"),rotatedAt:now(),expiresAt:input.expiresAt?String(input.expiresAt):null,status:"ACTIVE"});await this.audit(actor,"VAULT_ROTATION_RECORDED","VAULT_ITEM",id,"SUCCESS",{...before,encryptedReference:"[REDACTED]"},{...next,encryptedReference:"[REDACTED]"},required(input.reason,"Motivo"));return{...next,encryptedReference:"[REDACTED]"};}

  async acknowledgeEvent(id:string,actor:SecurityActor){this.assertAdmin(actor);const before=await this.repository.get<SecurityEvent>("security_events",id),next=await this.repository.update<SecurityEvent>("security_events",id,{status:"ACKNOWLEDGED",acknowledgedBy:actor.userId,acknowledgedAt:now()});await this.audit(actor,"SECURITY_EVENT_ACKNOWLEDGED","SECURITY_EVENT",id,"SUCCESS",before,next);return next;}
  async escalateEvent(id:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);const source=await this.repository.get<SecurityEvent>("security_events",id);await this.repository.update("security_events",id,{status:"ESCALATED"});return this.createIncident({title:input.title||source.description,description:input.description||source.description,incidentType:input.incidentType||"OTHER",severity:input.severity||"SEV3",sourceEventId:id},actor);}
  async createIncident(input:Row,actor:SecurityActor){this.assertAdmin(actor);const item=await this.repository.create<SecurityIncident>("security_incidents",{id:"",incidentNumber:await this.repository.incidentNumber(),title:required(input.title,"Título"),description:input.description?String(input.description):null,incidentType:required(input.incidentType,"Tipo"),severity:["SEV1","SEV2","SEV3","SEV4"].includes(String(input.severity))?input.severity:"SEV3",status:"DETECTED",commanderId:input.commanderId?String(input.commanderId):null,privacyBreach:Boolean(input.privacyBreach),detectedAt:now(),resolvedAt:null,closedAt:null,createdBy:actor.userId,createdAt:"",updatedAt:""});await this.repository.create<SecurityIncidentEvent>("security_incident_events",{id:"",incidentId:item.id,eventType:"DETECTED",description:"Incidente creado desde el Security Control Plane.",actorId:actor.userId,evidenceDocumentId:null,occurredAt:now()});await this.audit(actor,"SECURITY_INCIDENT_CREATED","SECURITY_INCIDENT",item.id,"SUCCESS",null,item);return item;}
  async incidentStatus(id:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);const status=required(input.status,"Estado"),allowed=["DETECTED","TRIAGE","CONFIRMED","CONTAINING","INVESTIGATING","ERADICATING","RECOVERING","MONITORING","RESOLVED","POSTMORTEM","CLOSED"];if(!allowed.includes(status))throw new BadRequestException("Estado de incidente inválido.");const before=await this.repository.get<SecurityIncident>("security_incidents",id),next=await this.repository.update<SecurityIncident>("security_incidents",id,{status:status as SecurityIncident["status"],resolvedAt:status==="RESOLVED"?now():before.resolvedAt,closedAt:status==="CLOSED"?now():before.closedAt});await this.repository.create<SecurityIncidentEvent>("security_incident_events",{id:"",incidentId:id,eventType:"STATUS_CHANGED",description:required(input.reason,"Motivo"),actorId:actor.userId,evidenceDocumentId:input.evidenceDocumentId?String(input.evidenceDocumentId):null,occurredAt:now()});await this.audit(actor,"INCIDENT_STATUS_CHANGED","SECURITY_INCIDENT",id,"SUCCESS",before,next,input.reason);return next;}
  async addIncidentAction(id:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);await this.repository.get("security_incidents",id);const event=await this.repository.create<SecurityIncidentEvent>("security_incident_events",{id:"",incidentId:id,eventType:required(input.eventType,"Tipo de acción"),description:required(input.description,"Descripción"),actorId:actor.userId,evidenceDocumentId:input.evidenceDocumentId?String(input.evidenceDocumentId):null,occurredAt:now()});await this.audit(actor,"INCIDENT_ACTION_ADDED","SECURITY_INCIDENT",id,"SUCCESS",null,event);return event;}

  async createVulnerability(input:Row,actor:SecurityActor){this.assertAdmin(actor);const item=await this.repository.create<SecurityVulnerability>("security_vulnerabilities",{id:"",source:required(input.source,"Fuente"),externalId:input.externalId?String(input.externalId):null,cve:input.cve?String(input.cve):null,cwe:input.cwe?String(input.cwe):null,title:required(input.title,"Título"),description:input.description?String(input.description):null,severity:["LOW","MEDIUM","HIGH","CRITICAL"].includes(String(input.severity))?input.severity:"MEDIUM",affectedComponent:required(input.affectedComponent,"Componente"),status:"OPEN",ownerId:input.ownerId?String(input.ownerId):null,detectedAt:now(),dueDate:input.dueDate?String(input.dueDate):null,fixedAt:null,verifiedAt:null,acceptedRiskExpiresAt:null,evidenceDocumentId:null,createdAt:"",updatedAt:""});if(item.severity==="CRITICAL")await this.event({eventType:"VULNERABILITY_CRITICAL",severity:"CRITICAL",resourceType:"VULNERABILITY",resourceId:item.id,description:"Se registró una vulnerabilidad crítica."},actor);return item;}
  async updateVulnerability(id:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);const statuses=["OPEN","TRIAGED","MITIGATING","FIX_READY","FIXED","VERIFIED","ACCEPTED_RISK","FALSE_POSITIVE"],severities=["LOW","MEDIUM","HIGH","CRITICAL"];if(input.status!==undefined&&!statuses.includes(String(input.status)))throw new BadRequestException("Estado de vulnerabilidad inválido.");if(input.severity!==undefined&&!severities.includes(String(input.severity)))throw new BadRequestException("Severidad inválida.");if(input.status==="ACCEPTED_RISK"&&(!input.acceptedRiskExpiresAt||!input.reason||!input.approverId))throw new BadRequestException("Aceptar riesgo requiere motivo, aprobador y expiración.");const before=await this.repository.get<SecurityVulnerability>("security_vulnerabilities",id),patch:Row={};for(const key of["source","externalId","cve","cwe","title","description","severity","affectedComponent","status","ownerId","dueDate","acceptedRiskExpiresAt","evidenceDocumentId"])if(input[key]!==undefined)patch[key]=input[key];patch.fixedAt=input.status==="FIXED"?now():before.fixedAt;patch.verifiedAt=input.status==="VERIFIED"?now():before.verifiedAt;const next=await this.repository.update<SecurityVulnerability>("security_vulnerabilities",id,patch as Partial<SecurityVulnerability>);await this.audit(actor,"VULNERABILITY_UPDATED","VULNERABILITY",id,"SUCCESS",before,next,input.reason);return next;}

  async createRecord(table:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);rejectSecretPayload(input);const item=await this.repository.create<Row>(table,{...input,createdBy:actor.userId});await this.audit(actor,"SECURITY_RECORD_CREATED",table,String(item.id),"SUCCESS",null,item);return item;}
  async records<T>(table:string,actor:SecurityActor){this.assertAdmin(actor);return this.repository.list<T>(table);}
  async record<T>(table:string,id:string,actor:SecurityActor){this.assertAdmin(actor);return this.repository.get<T>(table,id);}
  async updateControl(id:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);const statuses=["NOT_IMPLEMENTED","IMPLEMENTED","VERIFIED","FAILED","EXCEPTION"];if(input.status!==undefined&&!statuses.includes(String(input.status)))throw new BadRequestException("Estado de control inválido.");const before=await this.repository.get<SecurityControl>("security_controls",id);if(input.status==="VERIFIED"&&!input.evidenceSummary)throw new BadRequestException("VERIFIED requiere evidencia verificable.");const patch:Row={};for(const key of["framework","title","description","ownerId","status","evidenceSummary","nextTestAt"])if(input[key]!==undefined)patch[key]=input[key];patch.lastTestedAt=input.status==="VERIFIED"||input.status==="FAILED"?now():before.lastTestedAt;const next=await this.repository.update<SecurityControl>("security_controls",id,patch as Partial<SecurityControl>);await this.audit(actor,"SECURITY_CONTROL_UPDATED","SECURITY_CONTROL",id,"SUCCESS",before,next,input.reason);return next;}
  async updateSetting(key:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);this.assertAal2(actor);if(/secret|password|token|key/i.test(key))throw new BadRequestException("Los secretos no pueden almacenarse en security_settings.");const previous=await this.repository.setting(key),value=input.value;if(value===undefined)throw new BadRequestException("value es obligatorio.");const next=await this.repository.setSetting(key,value,required(input.description,"Descripción"),actor.userId);await this.audit(actor,"SECURITY_SETTING_CHANGED","SECURITY_SETTING",key,"SUCCESS",previous,next,required(input.reason,"Motivo"));return next;}
  async evaluateGate(input:Row,actor:SecurityActor){this.assertAdmin(actor);this.assertAal2(actor);const workspace=await this.workspace(actor),blockers:Array<{code:string;severity:"INFO"|"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";reason:string;evidence:string|null}>=[];
    for(const vulnerability of workspace.vulnerabilities.filter(item=>item.severity==="CRITICAL"&&!['VERIFIED','FALSE_POSITIVE'].includes(item.status)))blockers.push({code:"CRITICAL_VULNERABILITY",severity:"CRITICAL",reason:vulnerability.title,evidence:vulnerability.id});
    if(workspace.summary.exposedSecretFindings)blockers.push({code:"EXPOSED_SECRET",severity:"CRITICAL",reason:"Existen hallazgos de secretos sin cierre.",evidence:null});
    if(workspace.summary.rlsFindings)blockers.push({code:"RLS_CONTROL_FAILED",severity:"CRITICAL",reason:"Existen controles RLS fallidos o no implementados.",evidence:null});
    if(workspace.summary.mfaCoverage!==100)blockers.push({code:"PRIVILEGED_MFA_INCOMPLETE",severity:"CRITICAL",reason:"No existe evidencia de MFA completo para cuentas privilegiadas.",evidence:null});
    if(workspace.summary.backupStatus!=="HEALTHY")blockers.push({code:"BACKUP_NOT_HEALTHY",severity:"CRITICAL",reason:`Estado backup: ${workspace.summary.backupStatus}.`,evidence:null});
    if(workspace.summary.restoreStatus!=="VALIDATED")blockers.push({code:"RESTORE_NOT_VALIDATED",severity:"CRITICAL",reason:`Estado restore: ${workspace.summary.restoreStatus}.`,evidence:null});
    for(const scan of workspace.scans.filter(item=>["AUTHORIZATION","RLS","SECRET_SCAN","SAST","SCA"].includes(item.scanType)&&item.status!=="PASSED"))blockers.push({code:`${scan.scanType}_NOT_PASSED`,severity:"CRITICAL",reason:`${scan.scanType}: ${scan.status}.`,evidence:scan.id});
    const exceptions=await this.repository.list<any>("security_exceptions",{status:"ACTIVE"}),validExceptions=exceptions.filter(item=>item.expiresAt>now()),uncovered=blockers.filter(blocker=>!validExceptions.some(item=>item.controlCode===blocker.code)),status=uncovered.length?"FAIL":blockers.length?"PASS_WITH_EXCEPTION":"PASS";
    const gate=await this.repository.create<SecurityGate>("production_security_gates",{id:"",releaseReference:required(input.releaseReference,"Referencia de release"),status,evaluatedAt:now(),evaluatedBy:actor.userId,blockers,warnings:[],evidenceSnapshot:{controlCount:workspace.controls.length,scanCount:workspace.scans.length,exceptionIds:validExceptions.map(item=>item.id)},createdAt:""});if(status==="FAIL")await this.event({eventType:"PRODUCTION_GATE_FAILED",severity:"CRITICAL",resourceType:"SECURITY_GATE",resourceId:gate.id,description:"La release no superó el Production Security Gate.",metadataSafe:{releaseReference:gate.releaseReference,blockerCodes:blockers.map(item=>item.code)}},actor);await this.audit(actor,"PRODUCTION_GATE_EVALUATED","SECURITY_GATE",gate.id,status==="FAIL"?"DENIED":"SUCCESS",null,gate,input.reason);return gate;}

  async changeUserRole(userId:string,input:Row,actor:SecurityActor){this.assertAdmin(actor);this.assertAal2(actor);const role=required(input.role,"Rol");if(!roles.includes(role as Role))throw new BadRequestException("Rol inválido.");const reason=required(input.reason,"Motivo"),configured=await this.repository.setting<string[]>("privileged_roles")??[],privileged=[...new Set(["GERENTE_GENERAL","SECURITY_ADMIN",...configured])],isPrivileged=privileged.includes(role);let approverId:string|null=null;if(isPrivileged){const approvalRequestId=required(input.approvalRequestId,"Solicitud de aprobación");const approval=await this.repository.get<SecurityAccessRequest>("access_requests",approvalRequestId);const valid=approval.status==="APPROVED"&&approval.resourceType==="USER_ROLE"&&approval.resourceId===userId&&approval.permissionCode==="identity.role.manage"&&Boolean(approval.reviewedBy)&&approval.reviewedBy!==actor.userId;if(!valid)throw new ForbiddenException("El rol privilegiado requiere una solicitud USER_ROLE aprobada por un segundo administrador.");approverId=approval.reviewedBy;}if(!this.repository.supabase)throw new ServiceUnavailableException("Supabase Auth Admin no está configurado.");const{data:current,error:readError}=await this.repository.supabase.auth.admin.getUserById(userId);if(readError)throw readError;const before=current.user.app_metadata,{data,error}=await this.repository.supabase.auth.admin.updateUserById(userId,{app_metadata:{...before,role}});if(error)throw error;await this.event({eventType:"ROLE_CHANGED",severity:isPrivileged?"HIGH":"MEDIUM",actorUserId:actor.userId,resourceType:"USER",resourceId:userId,description:"Se modificó el rol de una identidad.",metadataSafe:{beforeRole:before.role,afterRole:role,approverId}},actor);await this.audit(actor,"ROLE_CHANGED","USER",userId,"SUCCESS",{role:before.role},{role,approverId},reason);return{id:data.user.id,role};}
}
