import { BadRequestException,ConflictException,ForbiddenException,ServiceUnavailableException } from "@nestjs/common";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { beforeEach,describe,expect,it } from "vitest";
import { DeferredVaultSecretProvider,SecurityProviderStatus } from "./security.providers.js";
import { SecurityRepository } from "./security.repository.js";
import { SecurityService,type SecurityActor } from "./security.service.js";

const admin:SecurityActor={userId:"10000000-0000-4000-8000-000000000001",role:"SECURITY_ADMIN",aal:"aal2",sessionId:"session-admin",requestId:"request-admin"};
const requester:SecurityActor={userId:"10000000-0000-4000-8000-000000000002",role:"JEFE_DESARROLLO",aal:"aal2",sessionId:"session-requester",requestId:"request-requester"};

describe("Security Control Plane",()=>{
  let repository:SecurityRepository,service:SecurityService;
  beforeEach(()=>{delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;repository=new SecurityRepository();service=new SecurityService(repository,new DeferredVaultSecretProvider(),new SecurityProviderStatus());});

  it("rechaza secretos plaintext en el payload de Vault",async()=>{await expect(service.createVaultItem({name:"QA",secretType:"API_KEY",provider:"EXTERNAL",encryptedReference:"reference-123",secretValue:"never",reason:"QA"},admin)).rejects.toBeInstanceOf(BadRequestException);});
  it("guarda solo una referencia y nunca simula reveal",async()=>{const item=await service.createVaultItem({name:"QA",secretType:"API_KEY",provider:"EXTERNAL",encryptedReference:"reference-123",reason:"QA"},admin);expect(item.encryptedReference).toBe("[REDACTED]");await expect(service.revealVaultItem(item.id,{reason:"QA"},admin)).rejects.toBeInstanceOf(ForbiddenException);});
  it("requiere política JIT configurable",async()=>{await expect(service.createAccessRequest({resourceType:"PROJECT",resourceId:"p1",permissionCode:"deploy.production",reason:"QA",requestedMinutes:30},requester)).rejects.toBeInstanceOf(ConflictException);});
  it("impide autoaprobar acceso temporal",async()=>{await repository.setSetting("jit_max_minutes",60,"QA",admin.userId);const request=await service.createAccessRequest({resourceType:"PROJECT",resourceId:"p1",permissionCode:"deploy.production",reason:"QA",requestedMinutes:30},requester);await expect(service.decideAccess(request.id,true,{reason:"Autorizado"},requester)).rejects.toBeInstanceOf(ForbiddenException);});
  it("crea un grant temporal con expiración",async()=>{await repository.setSetting("jit_max_minutes",60,"QA",admin.userId);const request=await service.createAccessRequest({resourceType:"PROJECT",resourceId:"p1",permissionCode:"deploy.production",reason:"QA",requestedMinutes:30},requester),result=await service.decideAccess(request.id,true,{reason:"Ventana aprobada"},admin);expect(result.grant?.status).toBe("ACTIVE");expect(new Date(result.grant!.expiresAt).getTime()).toBeGreaterThan(Date.now());});
  it("revoca una sesión y conserva evidencia",async()=>{const session=await repository.create<any>("security_session_metadata",{sessionId:"qa-session",userId:requester.userId,role:requester.role,deviceId:null,browser:null,os:null,ipMasked:null,region:null,aal:"aal1",status:"ACTIVE",lastActivityAt:new Date().toISOString(),revokedAt:null,revokedBy:null});expect((await service.revokeSession(session.id,admin,"Actividad sospechosa")).status).toBe("REVOKED");expect(await repository.list("security_audit_events")).toHaveLength(1);});
  it("no permite VERIFIED sin evidencia",async()=>{const control=await repository.create<any>("security_controls",{controlCode:"QA-1",framework:"QA",title:"Control",status:"IMPLEMENTED",evidenceSummary:null,lastTestedAt:null,nextTestAt:null});await expect(service.updateControl(control.id,{status:"VERIFIED"},admin)).rejects.toBeInstanceOf(BadRequestException);});
  it("Security Gate falla sin MFA, backup, restore y scans",async()=>{await repository.setSetting("privileged_roles",["SECURITY_ADMIN"],"QA",admin.userId);const gate=await service.evaluateGate({releaseReference:"qa-build",reason:"QA"},admin);expect(gate.status).toBe("FAIL");expect(gate.blockers.map(item=>item.code)).toContain("BACKUP_NOT_HEALTHY");expect(gate.blockers.map(item=>item.code)).toContain("RESTORE_NOT_VALIDATED");});
  it("el proveedor diferido no devuelve secretos falsos",async()=>{await expect(new DeferredVaultSecretProvider().reveal("reference-123")).rejects.toBeInstanceOf(ServiceUnavailableException);});
  it("la migración activa RLS y no crea una columna secret_value",()=>{const sql=readFileSync(resolve(process.cwd(),"../../supabase/migrations/20261004010000_security_control_plane.sql"),"utf8");expect(sql).toContain("alter table public.%I enable row level security");expect(sql).toContain("private.security_is_admin()");expect(sql).not.toMatch(/secret_value\s+text/i);});
  it("instala Security aunque Projects o Documents todavía no existan",()=>{const sql=readFileSync(resolve(process.cwd(),"../../supabase/migrations/20261004010000_security_control_plane.sql"),"utf8");expect(sql).not.toMatch(/uuid references public\.(projects|documents)\(id\)/i);expect(sql).toContain("to_regclass(format('public.%I',dependency.parent_table))");expect(sql).toContain("vault_items_project_id_fkey");expect(sql).toContain("security_incident_events_evidence_document_id_fkey");});
  it("la autorización productiva valida claims y no confía en user_metadata para el rol",()=>{const guard=readFileSync(resolve(process.cwd(),"src/auth/role.guard.ts"),"utf8");expect(guard).toContain("supabase.auth.getClaims(token)");expect(guard).toContain("const rawRole = appMetadata.role");expect(guard).not.toContain("user_metadata.role");});
  it("no envía placeholders de dominio a tablas append-only",async()=>{let inserted:Record<string,unknown>|undefined;Object.defineProperty(repository,"supabase",{value:{from:()=>({insert:(value:Record<string,unknown>)=>{inserted=value;return{select:()=>({single:async()=>({data:{id:"20000000-0000-4000-8000-000000000001",...value},error:null})})};}})}});await repository.create<any>("vault_access_events",{id:"",vaultItemId:"vault",action:"REVEAL",result:"DENIED",occurredAt:new Date().toISOString(),createdAt:"",updatedAt:""});expect(inserted).not.toHaveProperty("id");expect(inserted).not.toHaveProperty("created_at");expect(inserted).not.toHaveProperty("updated_at");});
  it("filtra campos de workflow antes de actualizar un control",async()=>{const control=await repository.create<any>("security_controls",{controlCode:"QA-2",framework:"QA",title:"Control",status:"IMPLEMENTED",evidenceSummary:null,lastTestedAt:null,nextTestAt:null});const updated=await service.updateControl(control.id,{status:"FAILED",reason:"Prueba controlada"},admin);expect(updated.status).toBe("FAILED");expect(updated).not.toHaveProperty("reason");});
  it("exige aprobación persistida para elevar a un rol privilegiado",async()=>{await expect(service.changeUserRole(requester.userId!,{role:"SECURITY_ADMIN",reason:"Elevación"},admin)).rejects.toBeInstanceOf(BadRequestException);});
});
