import { BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException } from "@nestjs/common";
import type { Employee,EmploymentAnnex,EmploymentContract,EmploymentRelationship } from "@zyteron/contracts";
import { DocumentService,DocumentSignatureService } from "../documents/documents.service.js";
import { HrRepository } from "./hr.repository.js";
import { LaborAuthorityProvider } from "./hr.providers.js";
import type { HrActor } from "./employees.service.js";

const now=()=>new Date().toISOString(),required=(value:unknown,label:string)=>{if(typeof value!=="string"||!value.trim())throw new BadRequestException(`${label} obligatorio.`);return value.trim();},uuid=(value:unknown,label:string,optional=false)=>{if(optional&&(value===null||value===undefined||value===""))return null;if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new BadRequestException(`${label} inválido.`);return value;},date=(value:unknown,label:string,optional=false)=>{if(optional&&(value===null||value===undefined||value===""))return null;if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new BadRequestException(`${label} inválida.`);return value;};
const hr=(actor:HrActor)=>{if(actor.role!=="RRHH")throw new ForbiddenException("Acción reservada para RR.HH.");};

@Injectable() export class EmploymentContractsService{
  constructor(private readonly repository:HrRepository,private readonly documents:DocumentService,private readonly signatures:DocumentSignatureService,private readonly laborAuthority:LaborAuthorityProvider){}
  async list(actor:HrActor){const items=await this.repository.list<EmploymentContract>("employment_contracts",{},"created_at",false);return actor.role==="RRHH"?items:items.map(({baseSalary:_,...item})=>item);}
  async get(id:string,actor:HrActor){const item=await this.repository.get<EmploymentContract>("employment_contracts",uuid(id,"Contrato")!);if(!item)throw new NotFoundException("Contrato laboral no encontrado.");return actor.role==="RRHH"?item:(({baseSalary:_,...safe})=>safe)(item);}
  async create(body:any,actor:HrActor){hr(actor);const employeeId=uuid(body.employeeId,"Colaborador")!,employee=await this.repository.get<Employee>("employees",employeeId);if(!employee)throw new NotFoundException("Colaborador no encontrado.");const relationshipId=uuid(body.employmentRelationshipId,"Relación laboral")!,relationship=await this.repository.get<EmploymentRelationship>("employment_relationships",relationshipId);if(!relationship||relationship.employeeId!==employeeId)throw new BadRequestException("La relación laboral no corresponde al colaborador.");let contract=await this.repository.create<any>("employment_contracts",{employeeId,employmentRelationshipId:relationshipId,contractNumber:await this.repository.nextContractNumber(),contractType:body.contractType||relationship.employmentType,status:"DRAFT",startDate:date(body.startDate,"Inicio")!,endDate:date(body.endDate,"Término",true),positionId:uuid(body.positionId||relationship.jobPositionId,"Cargo",true),departmentId:uuid(body.departmentId||relationship.departmentId,"Departamento",true),workLocation:body.workLocation||relationship.workLocation,weeklyHours:body.weeklyHours===undefined?relationship.weeklyHours:Number(body.weeklyHours),scheduleDefinition:body.scheduleDefinition&&typeof body.scheduleDefinition==="object"?body.scheduleDefinition:{},baseSalary:body.baseSalary===undefined?null:Number(body.baseSalary),currency:body.currency||"CLP",paymentFrequency:body.paymentFrequency||"MONTHLY",documentId:null,signatureStatus:"NOT_REQUESTED",signatureProvider:null,signedAt:null,dtRegistrationStatus:"NOT_READY",dtRegistrationReference:null,dtRegisteredAt:null,dtReceiptDocumentId:null,createdBy:actor.userId,createdAt:now(),updatedAt:now()});const document=await this.documents.create({title:`Contrato laboral ${contract.contractNumber}`,description:`Contrato laboral controlado de ${employee.firstName} ${employee.lastName}`,typeCode:"CONTRACT",classification:"RESTRICTED",links:[{linkType:"HR",linkedId:employee.id,primaryLink:true},{linkType:"CONTRACT",linkedId:contract.id,primaryLink:false}]},actor);contract=await this.repository.update<any>("employment_contracts",contract.id,{documentId:document.id});if(Number.isFinite(contract.baseSalary)&&Number(contract.baseSalary)>0)await this.repository.create<any>("employee_compensation_history",{employeeId,effectiveFrom:contract.startDate,effectiveTo:null,baseSalary:contract.baseSalary,currency:contract.currency,payFrequency:contract.paymentFrequency,contractReference:contract.id,createdBy:actor.userId});await this.repository.publish(employeeId,"EMPLOYMENT_CONTRACT",contract.id,"CONTRACT_CREATED",actor.userId,{contractNumber:contract.contractNumber,documentId:document.id});return contract;}
  async update(id:string,body:any,actor:HrActor){hr(actor);const current=await this.repository.get<EmploymentContract>("employment_contracts",uuid(id,"Contrato")!);if(!current)throw new NotFoundException("Contrato no encontrado.");if(!["DRAFT","IN_REVIEW"].includes(current.status))throw new ConflictException("El contrato ya no admite edición; crea un anexo.");const item=await this.repository.update<any>("employment_contracts",id,{endDate:body.endDate===undefined?undefined:date(body.endDate,"Término",true),positionId:body.positionId===undefined?undefined:uuid(body.positionId,"Cargo",true),departmentId:body.departmentId===undefined?undefined:uuid(body.departmentId,"Departamento",true),workLocation:body.workLocation,weeklyHours:body.weeklyHours===undefined?undefined:Number(body.weeklyHours),scheduleDefinition:body.scheduleDefinition,baseSalary:body.baseSalary===undefined?undefined:Number(body.baseSalary),currency:body.currency,paymentFrequency:body.paymentFrequency});await this.repository.publish(current.employeeId,"EMPLOYMENT_CONTRACT",id,"CONTRACT_UPDATED",actor.userId,{fields:Object.keys(body)});return item;}
  async submitReview(id:string,actor:HrActor){hr(actor);const current=await this.repository.get<EmploymentContract>("employment_contracts",id);if(!current||current.status!=="DRAFT")throw new ConflictException("Solo un borrador puede enviarse a revisión.");const item=await this.repository.update<any>("employment_contracts",id,{status:"IN_REVIEW"});await this.repository.publish(current.employeeId,"EMPLOYMENT_CONTRACT",id,"CONTRACT_REVIEW_REQUESTED",actor.userId);return item;}
  async ready(id:string,actor:HrActor){hr(actor);const current=await this.repository.get<EmploymentContract>("employment_contracts",id);if(!current||current.status!=="IN_REVIEW")throw new ConflictException("El contrato no está en revisión.");return this.repository.update<any>("employment_contracts",id,{status:"READY_FOR_SIGNATURE"});}
  async requestSignature(id:string,body:any,actor:HrActor){hr(actor);const contract=await this.repository.get<EmploymentContract>("employment_contracts",id);if(!contract||contract.status!=="READY_FOR_SIGNATURE"||!contract.documentId)throw new ConflictException("Contrato o documento no listo para firma.");const request=await this.signatures.request(contract.documentId,{signers:body.signers,callbackUrl:body.callbackUrl},actor);const item=await this.repository.update<any>("employment_contracts",id,{status:"SIGNATURE_REQUESTED",signatureStatus:request.status,signatureProvider:request.provider});await this.repository.publish(contract.employeeId,"EMPLOYMENT_CONTRACT",id,"CONTRACT_SIGNATURE_REQUESTED",actor.userId,{documentId:contract.documentId,signatureRequestId:request.id});return item;}
  async prepareRegistration(id:string,actor:HrActor){hr(actor);const contract=await this.repository.get<EmploymentContract>("employment_contracts",id);if(!contract)throw new NotFoundException("Contrato no encontrado.");const validation=await this.laborAuthority.validateRequiredFields({employeeId:contract.employeeId,contractId:id,startDate:contract.startDate});if(!validation.valid)throw new BadRequestException(`Faltan datos: ${validation.missing.join(", ")}`);const preparation=await this.laborAuthority.prepareContractRegistration({employeeId:contract.employeeId,contractId:id,startDate:contract.startDate}),rules=await this.repository.list<any>("compliance_rules",{ruleType:"REGISTER_EMPLOYMENT_CONTRACT",active:true},"effective_from",false),rule=rules.find(item=>item.effectiveFrom<=contract.startDate),dueDate=rule?addDays(contract.startDate,Number(rule.parameters?.daysFromEvent||0)):null;await this.repository.update<any>("employment_contracts",id,{status:"PENDING_DT_REGISTRATION",dtRegistrationStatus:preparation.status});await this.repository.create<any>("labor_compliance_tasks",{employeeId:contract.employeeId,contractId:id,taskType:"REGISTER_EMPLOYMENT_CONTRACT",dueDate,status:rule?"PENDING":"RULE_CONFIGURATION_REQUIRED",responsibleId:actor.userId,evidenceDocumentId:null,sourceReference:rule?.sourceReference||"Regla vigente no configurada",complianceRuleId:rule?.id||null,createdBy:actor.userId});return{...preparation,dueDate,ruleConfigured:Boolean(rule)};}
  async registerExternal(id:string,body:any,actor:HrActor){hr(actor);const contract=await this.repository.get<EmploymentContract>("employment_contracts",id);if(!contract)throw new NotFoundException("Contrato no encontrado.");const reference=required(body.reference,"Referencia oficial"),receipt=uuid(body.receiptDocumentId,"Comprobante")!;const item=await this.repository.update<any>("employment_contracts",id,{status:"REGISTERED",dtRegistrationStatus:"REGISTERED_WITH_EVIDENCE",dtRegistrationReference:reference,dtRegisteredAt:now(),dtReceiptDocumentId:receipt});const tasks=await this.repository.list<any>("labor_compliance_tasks",{contractId:id,taskType:"REGISTER_EMPLOYMENT_CONTRACT"});for(const task of tasks)await this.repository.update<any>("labor_compliance_tasks",task.id,{status:"COMPLETED",evidenceDocumentId:receipt});await this.repository.publish(contract.employeeId,"EMPLOYMENT_CONTRACT",id,"CONTRACT_REGISTERED_EXTERNAL",actor.userId,{reference,receiptDocumentId:receipt});return item;}
  async terminate(id:string,body:any,actor:HrActor){hr(actor);const contract=await this.repository.get<EmploymentContract>("employment_contracts",id);if(!contract)throw new NotFoundException("Contrato no encontrado.");const item=await this.repository.update<any>("employment_contracts",id,{status:"TERMINATED",endDate:date(body.endDate,"Fecha de término")});await this.repository.publish(contract.employeeId,"EMPLOYMENT_CONTRACT",id,"CONTRACT_TERMINATED",actor.userId,{reasonCategory:body.reasonCategory});return item;}
}
const addDays=(source:string,days:number)=>{const value=new Date(`${source}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);};

@Injectable() export class EmploymentAnnexesService{
  constructor(private readonly repository:HrRepository,private readonly documents:DocumentService,private readonly signatures:DocumentSignatureService){}
  async list(actor:HrActor){const items=await this.repository.list<EmploymentAnnex>("employment_annexes",{},"created_at",false);return actor.role==="RRHH"?items:items.map(item=>this.safe(item));}async get(id:string,actor?:HrActor){const item=await this.repository.get<EmploymentAnnex>("employment_annexes",id);if(!item)throw new NotFoundException("Anexo no encontrado.");return actor?.role==="RRHH"||!actor?item:this.safe(item);}
  async create(body:any,actor:HrActor){hr(actor);const contract=await this.repository.get<EmploymentContract>("employment_contracts",uuid(body.employmentContractId,"Contrato")!);if(!contract)throw new NotFoundException("Contrato no encontrado.");let annex=await this.repository.create<any>("employment_annexes",{employmentContractId:contract.id,employeeId:contract.employeeId,documentId:null,annexType:body.annexType||"OTHER",effectiveDate:date(body.effectiveDate,"Vigencia")!,status:"DRAFT",payload:body.payload&&typeof body.payload==="object"?body.payload:{},createdBy:actor.userId,createdAt:now(),updatedAt:now()});const document=await this.documents.create({title:`Anexo ${annex.annexType} · ${contract.contractNumber}`,description:"Anexo laboral controlado",typeCode:"CONTRACT",classification:"RESTRICTED",links:[{linkType:"HR",linkedId:contract.employeeId,primaryLink:true},{linkType:"CONTRACT",linkedId:contract.id,primaryLink:false}]},actor);annex=await this.repository.update<any>("employment_annexes",annex.id,{documentId:document.id});await this.repository.publish(contract.employeeId,"EMPLOYMENT_ANNEX",annex.id,"ANNEX_CREATED",actor.userId,{documentId:document.id});return annex;}
  async requestSignature(id:string,body:any,actor:HrActor){hr(actor);const annex=await this.get(id,actor);if(!annex.documentId||!annex.status.startsWith("READY"))throw new ConflictException("El anexo no está listo para firma.");const request=await this.signatures.request(annex.documentId,{signers:body.signers,callbackUrl:body.callbackUrl},actor);return this.repository.update<any>("employment_annexes",id,{status:"SIGNATURE_REQUESTED",signatureRequestId:request.id});}
  async activate(id:string,actor:HrActor){hr(actor);const annex=await this.get(id,actor);if(annex.status!=="SIGNED")throw new ConflictException("Solo un anexo firmado puede entrar en vigencia.");const relationship=(await this.repository.list<EmploymentRelationship>("employment_relationships",{employeeId:annex.employeeId,status:"ACTIVE"}))[0];if(!relationship)throw new ConflictException("No existe relación laboral activa.");if(annex.annexType==="POSITION_CHANGE"&&annex.payload.positionId){await this.repository.update<any>("employment_relationships",relationship.id,{jobPositionId:annex.payload.positionId});await this.repository.create<any>("employee_position_history",{employeeId:annex.employeeId,valueId:annex.payload.positionId,effectiveFrom:annex.effectiveDate,effectiveTo:null,source:"ANNEX",sourceId:id,createdBy:actor.userId});}if(annex.annexType==="SALARY_CHANGE"&&annex.payload.baseSalary){const current=(await this.repository.list<any>("employee_compensation_history",{employeeId:annex.employeeId},"effective_from",false))[0];if(current)await this.repository.update<any>("employee_compensation_history",current.id,{effectiveTo:annex.effectiveDate});await this.repository.create<any>("employee_compensation_history",{employeeId:annex.employeeId,effectiveFrom:annex.effectiveDate,effectiveTo:null,baseSalary:Number(annex.payload.baseSalary),currency:String(annex.payload.currency||"CLP"),payFrequency:"MONTHLY",contractReference:annex.employmentContractId,annexId:id,createdBy:actor.userId});}const item=await this.repository.update<any>("employment_annexes",id,{status:"ACTIVE"});await this.repository.publish(annex.employeeId,"EMPLOYMENT_ANNEX",id,"ANNEX_ACTIVATED",actor.userId,{annexType:annex.annexType});return item;}
  private safe(item:EmploymentAnnex){return{...item,payload:Object.fromEntries(Object.entries(item.payload||{}).filter(([key])=>!["baseSalary","salary","currency","payFrequency","compensation"].includes(key)))};}
}
