import { BadRequestException,ForbiddenException,Injectable,NotFoundException } from "@nestjs/common";
import type { Employee,EmployeeDetail,EmploymentRelationship,HrDepartment,HrTeam,JobPosition } from "@zyteron/contracts";
import { isValidChileanRut,normalizeRut } from "../clients/rut.js";
import { DocumentReadService } from "../documents/documents.service.js";
import { HrRepository,type HrPage } from "./hr.repository.js";

export interface HrActor{userId:string|null;role:string;}
const now=()=>new Date().toISOString(),uuid=(value:unknown,label:string,optional=false)=>{if(optional&&(value===null||value===undefined||value===""))return null;if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new BadRequestException(`${label} inválido.`);return value;},required=(value:unknown,label:string)=>{if(typeof value!=="string"||!value.trim())throw new BadRequestException(`${label} obligatorio.`);return value.trim();},date=(value:unknown,label:string,optional=false)=>{if(optional&&(value===null||value===undefined||value===""))return null;if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(`${value}T12:00:00Z`)))throw new BadRequestException(`${label} inválida.`);return value;};
const hrRoles=new Set(["RRHH"]),executiveRoles=new Set(["GERENTE_GENERAL"]),managerRoles=new Set(["JEFE_DESARROLLO","TECH_LEAD","OPERACIONES","JEFE_VENTAS"]);
const safeEmployee=(item:Employee):Employee=>({...item,rut:"••••••••-•",personalEmail:null,phone:null,birthDate:null,address:null,region:null,commune:null,emergencyContact:{}});
const safeAnnexPayload=(payload:Record<string,unknown>)=>Object.fromEntries(Object.entries(payload||{}).filter(([key])=>!["baseSalary","salary","currency","payFrequency","compensation"].includes(key)));

@Injectable() export class EmployeeAccessService{
  constructor(private readonly repository:HrRepository){}
  private async self(actor:HrActor){return actor.userId?(await this.repository.list<Employee>("employees",{userId:actor.userId}))[0]:undefined;}
  async assert(employee:Employee,actor:HrActor,scope:"general"|"confidential"|"compensation"|"medical"="general"){
    if(hrRoles.has(actor.role))return;
    if(executiveRoles.has(actor.role)&&scope==="general")return;
    const self=await this.self(actor);if(self?.id===employee.id&&scope!=="medical")return;
    if(managerRoles.has(actor.role)&&scope==="general"&&self){const relationships=await this.repository.list<EmploymentRelationship>("employment_relationships",{employeeId:employee.id,status:"ACTIVE"});if(relationships.some(item=>item.managerId===self.id))return;}
    throw new ForbiddenException(scope==="general"?"Sin acceso a este colaborador.":"Información laboral restringida.");
  }
  compensation(actor:HrActor){return hrRoles.has(actor.role);}
}

@Injectable() export class EmployeesService{
  constructor(private readonly repository:HrRepository,private readonly access:EmployeeAccessService,private readonly documents:DocumentReadService){}
  async list(q:HrPage,actor:HrActor){const result=await this.repository.page<Employee>("employees",q);if(hrRoles.has(actor.role))return result;const self=actor.userId?(await this.repository.list<Employee>("employees",{userId:actor.userId}))[0]:undefined;if(executiveRoles.has(actor.role))return{...result,items:result.items.map(item=>item.id===self?.id?item:safeEmployee(item))};if(!self)return{...result,items:[],total:0,totalPages:0};const relationships=await this.repository.list<EmploymentRelationship>("employment_relationships",{managerId:self.id,status:"ACTIVE"}),allowed=new Set([self.id,...relationships.map(item=>item.employeeId)]);const items=result.items.filter(item=>allowed.has(item.id)).map(item=>item.id===self.id?item:safeEmployee(item));return{...result,items,total:items.length,totalPages:Math.ceil(items.length/q.pageSize)};}
  async get(id:string,actor:HrActor){const item=await this.repository.get<Employee>("employees",uuid(id,"Colaborador")!);if(!item)throw new NotFoundException("Colaborador no encontrado.");await this.access.assert(item,actor);return item;}
  async create(body:any,actor:HrActor){if(!hrRoles.has(actor.role))throw new ForbiddenException("Solo RR.HH. puede crear colaboradores.");const rut=normalizeRut(required(body.rut,"RUT"));if(!isValidChileanRut(rut))throw new BadRequestException("RUT chileno inválido.");const hireDate=date(body.hireDate,"Fecha de ingreso",true),employee=await this.repository.create<any>("employees",{userId:uuid(body.userId,"Usuario",true),employeeNumber:await this.repository.nextEmployeeNumber(),rut,firstName:required(body.firstName,"Nombre"),middleName:body.middleName?.trim()||null,lastName:required(body.lastName,"Apellido"),secondLastName:body.secondLastName?.trim()||null,preferredName:body.preferredName?.trim()||null,personalEmail:body.personalEmail?.trim().toLowerCase()||null,corporateEmail:body.corporateEmail?.trim().toLowerCase()||null,phone:body.phone?.trim()||null,birthDate:date(body.birthDate,"Fecha de nacimiento",true),nationality:body.nationality?.trim()||null,address:body.address?.trim()||null,region:body.region?.trim()||null,commune:body.commune?.trim()||null,emergencyContact:body.emergencyContact&&typeof body.emergencyContact==="object"?body.emergencyContact:{},status:body.status||"PRE_HIRE",hireDate,terminationDate:null,privacyLevel:"HR_CONFIDENTIAL",archivedAt:null,createdAt:now(),updatedAt:now()});if(body.employmentType&&hireDate)await this.relationship(employee.id,{...body,startDate:hireDate},actor);await this.repository.publish(employee.id,"EMPLOYEE",employee.id,"EMPLOYEE_CREATED",actor.userId,{employeeNumber:employee.employeeNumber,status:employee.status});return employee;}
  async update(id:string,body:any,actor:HrActor){const current=await this.get(id,actor);await this.access.assert(current,actor,"confidential");const patch:any={preferredName:body.preferredName===undefined?undefined:body.preferredName?.trim()||null,personalEmail:body.personalEmail===undefined?undefined:body.personalEmail?.trim().toLowerCase()||null,corporateEmail:body.corporateEmail===undefined?undefined:body.corporateEmail?.trim().toLowerCase()||null,phone:body.phone===undefined?undefined:body.phone?.trim()||null,address:body.address===undefined?undefined:body.address?.trim()||null,region:body.region===undefined?undefined:body.region?.trim()||null,commune:body.commune===undefined?undefined:body.commune?.trim()||null,emergencyContact:body.emergencyContact,status:body.status};const item=await this.repository.update<Employee&Record<string,unknown>>("employees",id,patch);await this.repository.publish(id,"EMPLOYEE",id,"EMPLOYEE_UPDATED",actor.userId,{fields:Object.keys(patch).filter(key=>patch[key]!==undefined)});return item;}
  async archive(id:string,actor:HrActor){const current=await this.get(id,actor);await this.access.assert(current,actor,"confidential");if(!["TERMINATED","ARCHIVED"].includes(current.status))throw new BadRequestException("Solo un colaborador terminado puede archivarse.");const item=await this.repository.update<Employee&Record<string,unknown>>("employees",id,{status:"ARCHIVED",archivedAt:now()});await this.repository.publish(id,"EMPLOYEE",id,"EMPLOYEE_ARCHIVED",actor.userId);return item;}
  async relationship(employeeId:string,body:any,actor:HrActor){const employee=await this.get(employeeId,actor);await this.access.assert(employee,actor,"confidential");const current=(await this.repository.list<EmploymentRelationship>("employment_relationships",{employeeId,status:"ACTIVE"}))[0];if(current)await this.repository.update<any>("employment_relationships",current.id,{status:"ENDED",endDate:date(body.startDate,"Inicio")});const item=await this.repository.create<any>("employment_relationships",{employeeId,companyEntityId:uuid(body.companyEntityId,"Entidad",true),employmentType:body.employmentType||"INDEFINITE",startDate:date(body.startDate,"Inicio")!,endDate:date(body.endDate,"Término",true),status:body.status||"ACTIVE",jobPositionId:uuid(body.jobPositionId,"Cargo",true),departmentId:uuid(body.departmentId,"Departamento",true),teamId:uuid(body.teamId,"Equipo",true),managerId:uuid(body.managerId,"Jefatura",true),workLocation:body.workLocation?.trim()||null,costCenterId:uuid(body.costCenterId,"Centro de costo",true),weeklyHours:body.weeklyHours===undefined?null:Number(body.weeklyHours),scheduleType:body.scheduleType||null,createdAt:now(),updatedAt:now()});for(const[table,value]of[["employee_position_history",item.jobPositionId],["employee_department_history",item.departmentId],["employee_manager_history",item.managerId]]as const)if(value)await this.repository.create<any>(table,{employeeId,valueId:value,effectiveFrom:item.startDate,effectiveTo:null,source:"EMPLOYMENT_RELATIONSHIP",createdBy:actor.userId});await this.repository.publish(employeeId,"EMPLOYMENT_RELATIONSHIP",item.id,"EMPLOYMENT_RELATIONSHIP_CREATED",actor.userId);return item;}
  async detail(id:string,actor:HrActor):Promise<EmployeeDetail>{const employee=await this.get(id,actor),compensationVisible=this.access.compensation(actor),own=employee.userId===actor.userId;const[relationships,contracts,annexes,leave,balances,medical,onboarding,offboarding,assets,goals,training,activity,documents,compensation]=await Promise.all([this.repository.list<EmploymentRelationship>("employment_relationships",{employeeId:id},"start_date",false),this.repository.list<any>("employment_contracts",{employeeId:id}),this.repository.list<any>("employment_annexes",{employeeId:id}),this.repository.list<any>("leave_requests",{employeeId:id}),this.repository.list<any>("leave_balances",{employeeId:id}),this.repository.list<any>("medical_leave_records",{employeeId:id}),this.repository.list<any>("onboarding_instances",{employeeId:id}),this.repository.list<any>("offboarding_instances",{employeeId:id}),this.repository.list<any>("asset_assignments",{employeeId:id}),this.repository.list<any>("employee_goals",{employeeId:id}),this.repository.list<any>("training_assignments",{employeeId:id}),this.repository.list<any>("hr_events",{employeeId:id},"occurred_at",false),this.documents.related({linkType:"HR",linkedId:id}),compensationVisible?this.repository.list<any>("employee_compensation_history",{employeeId:id},"effective_from",false):Promise.resolve([])]);return{employee:hrRoles.has(actor.role)||own?employee:safeEmployee(employee),relationship:relationships.find(item=>item.status==="ACTIVE")??relationships[0]??null,contracts:hrRoles.has(actor.role)?contracts:contracts.map(({baseSalary:_,...safe})=>safe),annexes:hrRoles.has(actor.role)?annexes:annexes.map(item=>({...item,payload:safeAnnexPayload(item.payload)})),leave,balance:balances[0]??null,medical:hrRoles.has(actor.role)?medical:[],onboarding,offboarding,assets,goals,training,documents:hrRoles.has(actor.role)||own?documents:{...documents,documents:[]},activity,compensationVisible,...(compensationVisible?{compensation}: {})};}
}

@Injectable() export class OrganizationService{
  constructor(private readonly repository:HrRepository){}
  departments(){return this.repository.list<HrDepartment>("departments",{},"name",true);}teams(){return this.repository.list<HrTeam>("teams",{},"name",true);}positions(){return this.repository.list<JobPosition>("job_positions",{},"name",true);}
  createDepartment(body:any){return this.repository.create<any>("departments",{name:required(body.name,"Nombre"),code:required(body.code,"Código").toUpperCase(),managerId:uuid(body.managerId,"Jefatura",true),parentDepartmentId:uuid(body.parentDepartmentId,"Departamento superior",true),costCenterId:uuid(body.costCenterId,"Centro de costo",true),active:true});}
  createTeam(body:any){return this.repository.create<any>("teams",{departmentId:uuid(body.departmentId,"Departamento")!,name:required(body.name,"Nombre"),teamLeadId:uuid(body.teamLeadId,"Líder",true),active:true});}
  createPosition(body:any){return this.repository.create<any>("job_positions",{name:required(body.name,"Nombre"),code:required(body.code,"Código").toUpperCase(),departmentId:uuid(body.departmentId,"Departamento",true),description:body.description?.trim()||null,level:body.level?.trim()||null,reportsToPositionId:uuid(body.reportsToPositionId,"Cargo superior",true),defaultPermissionsProfile:body.defaultPermissionsProfile?.trim()||null,active:true});}
  async chart(){const[employees,relationships,departments,teams,positions]=await Promise.all([this.repository.list<Employee>("employees",{}),this.repository.list<EmploymentRelationship>("employment_relationships",{status:"ACTIVE"}),this.departments(),this.teams(),this.positions()]);return{departments:departments.map(department=>({...department,teams:teams.filter(team=>team.departmentId===department.id),people:relationships.filter(item=>item.departmentId===department.id).map(item=>{const employee=employees.find(person=>person.id===item.employeeId);return{employee:employee?{id:employee.id,employeeNumber:employee.employeeNumber,firstName:employee.firstName,lastName:employee.lastName,preferredName:employee.preferredName,corporateEmail:employee.corporateEmail,status:employee.status}:null,relationship:item,position:positions.find(position=>position.id===item.jobPositionId)};})}))};}
}
