import { Inject,Injectable } from "@nestjs/common";
import type { Employee,EmploymentAnnex,EmploymentContract,EmploymentRelationship,HrAttentionItem,HrProviderReadiness,HrSummary,HrWorkspace,LeaveRequest,MedicalLeaveRecord,OffboardingInstance,OnboardingInstance,PayrollPeriod } from "@zyteron/contracts";
import { EnterpriseSignatureProvider } from "../documents/documents.providers.js";
import { AttendanceProvider,LaborAuthorityProvider,PayrollSubmissionProvider } from "./hr.providers.js";
import { HrRepository } from "./hr.repository.js";
import type { HrActor } from "./employees.service.js";

const now=()=>new Date().toISOString();
export function buildHrProviderReadiness(providers:HrWorkspace["providers"]):HrProviderReadiness[]{
 const connectedSignature=providers.signature!=="NOT_CONFIGURED",connectedAttendance=providers.attendance!=="NOT_CONFIGURED";
 return[
  {key:"signature",label:"Firma electrónica",status:providers.signature,state:connectedSignature?"READY":"ACTION_REQUIRED",title:connectedSignature?"Proveedor conectado":"Pendiente de configurar",detail:connectedSignature?`Firma gestionada por ${providers.signature}.`:"Los contratos permanecen en borrador hasta conectar un proveedor de firma real.",actionHref:"/settings/integrations?code=ELECTRONIC_SIGNATURE",actionLabel:connectedSignature?"Ver integración":"Configurar firma"},
  {key:"laborAuthority",label:"Mi DT / REL",status:providers.laborAuthority,state:providers.laborAuthority==="EXTERNAL_MANUAL_WITH_EVIDENCE"?"EXTERNAL_STEP":"READY",title:providers.laborAuthority==="EXTERNAL_MANUAL_WITH_EVIDENCE"?"Operativo con trámite externo":"Integración disponible",detail:providers.laborAuthority==="EXTERNAL_MANUAL_WITH_EVIDENCE"?"Zyteron prepara y valida los datos; el trámite se realiza en Mi DT y se cierra adjuntando el comprobante oficial.":"El canal laboral está disponible.",actionHref:"/hr/lre",actionLabel:"Ver flujo LRE"},
  {key:"attendance",label:"Asistencia",status:providers.attendance,state:connectedAttendance?"READY":"ACTION_REQUIRED",title:connectedAttendance?"Proveedor conectado":"Pendiente de configurar",detail:connectedAttendance?"La sincronización de asistencia está habilitada.":"No se importan marcaciones ni se presume cumplimiento hasta conectar un proveedor autorizado.",actionHref:"/hr/attendance",actionLabel:connectedAttendance?"Ver asistencia":"Revisar configuración"},
  {key:"payrollSubmission",label:"Previsional",status:providers.payrollSubmission,state:providers.payrollSubmission==="EXTERNAL_EXPORT_ONLY"?"EXTERNAL_STEP":"READY",title:providers.payrollSubmission==="EXTERNAL_EXPORT_ONLY"?"Exportación controlada":"Integración disponible",detail:providers.payrollSubmission==="EXTERNAL_EXPORT_ONLY"?"Zyteron genera el archivo validado; la presentación se realiza externamente y exige comprobante.":"El canal previsional está disponible.",actionHref:"/hr/lre",actionLabel:"Ver exportaciones"},
 ];
}
@Injectable() export class HrReadService{
 constructor(private readonly repository:HrRepository,@Inject(EnterpriseSignatureProvider)private readonly signature:EnterpriseSignatureProvider,@Inject(LaborAuthorityProvider)private readonly labor:LaborAuthorityProvider,@Inject(AttendanceProvider)private readonly attendance:AttendanceProvider,@Inject(PayrollSubmissionProvider)private readonly submission:PayrollSubmissionProvider){}
 async summary():Promise<HrSummary>{const[employees,onboarding,offboarding,contracts,annexes,leave,payroll,lre,tasks]=await Promise.all([this.repository.list<any>("employees",{}),this.repository.list<OnboardingInstance>("onboarding_instances",{}),this.repository.list<OffboardingInstance>("offboarding_instances",{}),this.repository.list<EmploymentContract>("employment_contracts",{}),this.repository.list<EmploymentAnnex>("employment_annexes",{}),this.repository.list<LeaveRequest>("leave_requests",{}),this.repository.list<PayrollPeriod>("payroll_periods",{}),this.repository.list<any>("lre_exports",{}),this.repository.list<any>("labor_compliance_tasks",{})]),today=now().slice(0,10),month=today.slice(0,7),soon=new Date(Date.now()+45*86400000).toISOString().slice(0,10);return{activeEmployees:employees.filter(item=>item.status==="ACTIVE").length,hiresThisMonth:employees.filter(item=>item.hireDate?.startsWith(month)).length,terminationsThisMonth:employees.filter(item=>item.terminationDate?.startsWith(month)).length,onboardingActive:onboarding.filter(item=>["NOT_STARTED","IN_PROGRESS","BLOCKED"].includes(item.status)).length,vacationsUpcoming:leave.filter(item=>item.leaveType==="VACATION"&&item.status==="APPROVED"&&item.startDate>=today&&item.startDate<=soon).length,absencesToday:leave.filter(item=>item.status==="APPROVED"&&item.startDate<=today&&item.endDate>=today).length,contractsExpiring:contracts.filter(item=>item.endDate&&item.endDate>=today&&item.endDate<=soon&&!['TERMINATED','CANCELLED','SUPERSEDED'].includes(item.status)).length,annexesPendingSignature:annexes.filter(item=>["READY_FOR_SIGNATURE","SIGNATURE_REQUESTED"].includes(item.status)).length,documentsPending:contracts.filter(item=>!item.documentId).length,requestsPending:leave.filter(item=>["PENDING_MANAGER","PENDING_HR"].includes(item.status)).length,lrePending:payroll.filter(item=>["PAID","CLOSED"].includes(item.status)&&!lre.some(exportItem=>exportItem.payrollPeriodId===item.id&&exportItem.status==="DECLARED")).length,offboardingPending:offboarding.filter(item=>!["COMPLETED","CANCELLED"].includes(item.status)).length+tasks.filter(item=>item.status==="RULE_CONFIGURATION_REQUIRED").length};}
 async attention():Promise<HrAttentionItem[]>{const[contracts,onboarding,offboarding,leave,compliance,assets]=await Promise.all([this.repository.list<EmploymentContract>("employment_contracts",{}),this.repository.list<OnboardingInstance>("onboarding_instances",{}),this.repository.list<OffboardingInstance>("offboarding_instances",{}),this.repository.list<LeaveRequest>("leave_requests",{}),this.repository.list<any>("labor_compliance_tasks",{}),this.repository.list<any>("asset_assignments",{})]),today=now().slice(0,10),soon=new Date(Date.now()+45*86400000).toISOString().slice(0,10);return[...contracts.filter(item=>item.endDate&&item.endDate<=soon&&!['TERMINATED','CANCELLED','SUPERSEDED'].includes(item.status)).map(item=>({id:item.id,type:"CONTRACT"as const,title:item.contractNumber,reason:"Contrato próximo a vencer",severity:item.endDate!<today?"CRITICAL"as const:"AT_RISK"as const,href:`/hr/contracts/${item.id}`,dueAt:item.endDate})),...onboarding.filter(item=>item.status==="BLOCKED"||(item.targetDate&&item.targetDate<today&&item.status!=="COMPLETED")).map(item=>({id:item.id,type:"ONBOARDING"as const,title:"Onboarding requiere atención",reason:item.status==="BLOCKED"?"Flujo bloqueado":"Fecha objetivo vencida",severity:"AT_RISK"as const,href:`/hr/onboarding/${item.id}`,dueAt:item.targetDate})),...offboarding.filter(item=>item.status==="BLOCKED").map(item=>({id:item.id,type:"OFFBOARDING"as const,title:"Offboarding bloqueado",reason:`${item.criticalBlockers} controles pendientes`,severity:"CRITICAL"as const,href:`/hr/offboarding/${item.id}`,dueAt:item.effectiveDate})),...leave.filter(item=>["PENDING_MANAGER","PENDING_HR"].includes(item.status)).map(item=>({id:item.id,type:"LEAVE"as const,title:"Solicitud pendiente",reason:"Requiere decisión",severity:"ATTENTION"as const,href:`/hr/vacations/${item.id}`,dueAt:item.startDate})),...compliance.filter(item=>!['COMPLETED','CANCELLED'].includes(item.status)).map(item=>({id:item.id,type:"COMPLIANCE"as const,title:item.taskType,reason:item.status==="RULE_CONFIGURATION_REQUIRED"?"Falta configurar regla vigente":"Obligación laboral pendiente",severity:item.dueDate&&item.dueDate<today?"CRITICAL"as const:"AT_RISK"as const,href:"/hr/expirations",dueAt:item.dueDate})),...assets.filter(item=>!item.returnedAt&&offboarding.some(off=>off.employeeId===item.employeeId&&!['COMPLETED','CANCELLED'].includes(off.status))).map(item=>({id:item.id,type:"ASSET"as const,title:"Activo pendiente de devolución",reason:"Bloquea cierre de offboarding",severity:"CRITICAL"as const,href:"/hr/assets",dueAt:null}))].slice(0,50);}
 async workspace(actor:HrActor):Promise<HrWorkspace>{
  const[globalSummary,globalAttention,allEmployees,allRelationships,departments,teams,positions,allContracts,allAnnexes,allOnboarding,allOffboarding,allLeave,allMedical,payroll,lre,allAssets,allGoals,allTraining,allActivity]=await Promise.all([this.summary(),this.attention(),this.repository.list<Employee>("employees",{}),this.repository.list<EmploymentRelationship>("employment_relationships",{}),this.repository.list<any>("departments",{}),this.repository.list<any>("teams",{}),this.repository.list<any>("job_positions",{}),this.repository.list<EmploymentContract>("employment_contracts",{}),this.repository.list<EmploymentAnnex>("employment_annexes",{}),this.repository.list<OnboardingInstance>("onboarding_instances",{}),this.repository.list<OffboardingInstance>("offboarding_instances",{}),this.repository.list<LeaveRequest>("leave_requests",{}),this.repository.list<MedicalLeaveRecord>("medical_leave_records",{}),this.repository.list<PayrollPeriod>("payroll_periods",{}),this.repository.list<any>("lre_exports",{}),this.repository.list<any>("asset_assignments",{}),this.repository.list<any>("employee_goals",{}),this.repository.list<any>("training_assignments",{}),this.repository.list<any>("hr_events",{},"occurred_at",false)]);
  const isHr=actor.role==="RRHH",isExecutive=actor.role==="GERENTE_GENERAL",fullGeneral=isHr||isExecutive,self=allEmployees.find(item=>item.userId===actor.userId),allowed=new Set<string>();
  if(fullGeneral)for(const employee of allEmployees)allowed.add(employee.id);else if(self){allowed.add(self.id);for(const relationship of allRelationships)if(relationship.status==="ACTIVE"&&relationship.managerId===self.id)allowed.add(relationship.employeeId);}
  const employees=allEmployees.filter(item=>allowed.has(item.id)),relationships=allRelationships.filter(item=>allowed.has(item.employeeId)),contracts=allContracts.filter(item=>allowed.has(item.employeeId)),annexes=allAnnexes.filter(item=>allowed.has(item.employeeId)),onboarding=allOnboarding.filter(item=>allowed.has(item.employeeId)),offboarding=allOffboarding.filter(item=>allowed.has(item.employeeId)),leave=allLeave.filter(item=>allowed.has(item.employeeId)),assets=allAssets.filter(item=>allowed.has(item.employeeId)),goals=allGoals.filter(item=>allowed.has(item.employeeId)),training=allTraining.filter(item=>allowed.has(item.employeeId)),activity=allActivity.filter(item=>item.employeeId&&allowed.has(item.employeeId));
  const scopedIds=new Set([...contracts,...annexes,...onboarding,...offboarding,...leave,...assets].map(item=>item.id)),attention=fullGeneral?globalAttention:globalAttention.filter(item=>scopedIds.has(item.id));
  const month=now().slice(0,7),summary=fullGeneral?globalSummary:{activeEmployees:employees.filter(item=>item.status==="ACTIVE").length,hiresThisMonth:employees.filter(item=>item.hireDate?.startsWith(month)).length,terminationsThisMonth:employees.filter(item=>item.terminationDate?.startsWith(month)).length,onboardingActive:onboarding.filter(item=>["NOT_STARTED","IN_PROGRESS","BLOCKED"].includes(item.status)).length,vacationsUpcoming:leave.filter(item=>item.leaveType==="VACATION"&&item.status==="APPROVED").length,absencesToday:leave.filter(item=>item.status==="APPROVED"&&item.startDate<=now().slice(0,10)&&item.endDate>=now().slice(0,10)).length,contractsExpiring:contracts.filter(item=>Boolean(item.endDate)).length,annexesPendingSignature:annexes.filter(item=>["READY_FOR_SIGNATURE","SIGNATURE_REQUESTED"].includes(item.status)).length,documentsPending:contracts.filter(item=>!item.documentId).length,requestsPending:leave.filter(item=>["PENDING_MANAGER","PENDING_HR"].includes(item.status)).length,lrePending:0,offboardingPending:offboarding.filter(item=>!["COMPLETED","CANCELLED"].includes(item.status)).length};
  const payrollVisible=isHr||actor.role==="FINANZAS";
  const providers={signature:this.signature.configured?this.signature.name:"NOT_CONFIGURED",laborAuthority:this.labor.status,attendance:this.attendance.status,payrollSubmission:this.submission.status};
  return{summary,attention,employees:isHr?employees:employees.map(item=>({...item,rut:"••••••••-•",personalEmail:null,phone:null,birthDate:null,address:null,region:null,commune:null,emergencyContact:{}})),relationships,departments,teams,positions,contracts:isHr?contracts:contracts.map(({baseSalary:_,...safe})=>safe),annexes:isHr?annexes:annexes.map(item=>({...item,payload:Object.fromEntries(Object.entries(item.payload||{}).filter(([key])=>!["baseSalary","salary","currency","payFrequency","compensation"].includes(key)))})),onboarding,offboarding,leave,medical:isHr?allMedical.filter(item=>allowed.has(item.employeeId)):[],payroll:payrollVisible?payroll:[],lre:payrollVisible?lre:[],assets,goals,training,activity:activity.slice(0,100),providers,providerReadiness:buildHrProviderReadiness(providers),generatedAt:now()};
 }
 async reports(){const summary=await this.summary(),employees=await this.repository.list<any>("employees",{}),relationships=await this.repository.list<any>("employment_relationships",{status:"ACTIVE"}),departments=await this.repository.list<any>("departments",{});return{definitions:{headcount:"Colaboradores con estado ACTIVE al momento del corte.",hires:"Personas cuya hire_date cae en el período.",terminations:"Personas cuya termination_date cae en el período.",turnover:"Bajas del período / promedio de headcount del período; no calculable sin serie histórica completa.",absenceRate:"Unidades de ausencia / unidades laborables configuradas; no calculable sin calendario laboral."},summary,byDepartment:departments.map(department=>({departmentId:department.id,name:department.name,headcount:relationships.filter(item=>item.departmentId===department.id).length})),status:employees.reduce((acc,item)=>({...acc,[item.status]:(acc[item.status]||0)+1}),{}as Record<string,number>),turnover:null,absenceRate:null};}
}
