import { Body,Controller,Get,Headers,Param,Patch,Post,Query } from "@nestjs/common";
import { RequireRoles } from "../auth/roles.decorator.js";
import { EmployeesService,OrganizationService,type HrActor } from "./employees.service.js";
import { EmploymentAnnexesService,EmploymentContractsService } from "./contracts.service.js";
import { HrReadService } from "./hr-read.service.js";
import { LreService,PayrollService } from "./payroll.service.js";
import { LeaveService,MedicalLeaveService,OffboardingService,OnboardingService,WorkforceOperationsService } from "./workforce.service.js";

type HeaderMap=Record<string,string|string[]|undefined>;const header=(h:HeaderMap,key:string)=>{const value=h[key];return Array.isArray(value)?value[0]:value;},actor=(h:HeaderMap):HrActor=>({userId:header(h,"x-zyteron-user-id")??null,role:header(h,"x-zyteron-role")??""});
const readers=["GERENTE_GENERAL","RRHH","JEFE_DESARROLLO","TECH_LEAD","OPERACIONES","JEFE_VENTAS","PROGRAMADOR","DESARROLLO","QA","SOPORTE_TECNICO","FINANZAS"]as const,hr=["RRHH"]as const,managers=["GERENTE_GENERAL","RRHH","JEFE_DESARROLLO","TECH_LEAD","OPERACIONES","JEFE_VENTAS"]as const;
const page=(q:Record<string,string|undefined>)=>({page:Math.max(1,Number(q.page)||1),pageSize:Math.min(100,Math.max(1,Number(q.pageSize)||25)),search:q.search,status:q.status,departmentId:q.departmentId,managerId:q.managerId,employeeId:q.employeeId});

@Controller("hr") export class HrController{
 constructor(private readonly read:HrReadService){}
 @Get()@RequireRoles(...readers)index(@Headers()h:HeaderMap){return this.read.workspace(actor(h));}@Get("workspace")@RequireRoles(...readers)workspace(@Headers()h:HeaderMap){return this.read.workspace(actor(h));}@Get("summary")@RequireRoles(...readers)summary(){return this.read.summary();}@Get("attention")@RequireRoles(...readers)attention(){return this.read.attention();}@Get("reports")@RequireRoles("GERENTE_GENERAL","RRHH")reports(){return this.read.reports();}
}

@Controller("hr/employees") export class EmployeesController{
 constructor(private readonly employees:EmployeesService,private readonly leave:LeaveService){}
 @Get()@RequireRoles(...readers)list(@Query()q:Record<string,string|undefined>,@Headers()h:HeaderMap){return this.employees.list(page(q),actor(h));}
 @Post()@RequireRoles(...hr)create(@Body()b:any,@Headers()h:HeaderMap){return this.employees.create(b,actor(h));}
 @Get(":id")@RequireRoles(...readers)get(@Param("id")id:string,@Headers()h:HeaderMap){return this.employees.detail(id,actor(h));}
 @Get(":id/summary")@RequireRoles(...readers)summary(@Param("id")id:string,@Headers()h:HeaderMap){return this.employees.detail(id,actor(h));}
 @Get(":id/activity")@RequireRoles(...readers)async activity(@Param("id")id:string,@Headers()h:HeaderMap){return(await this.employees.detail(id,actor(h))).activity;}
 @Patch(":id")@RequireRoles(...hr)update(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.employees.update(id,b,actor(h));}
 @Post(":id/archive")@RequireRoles(...hr)archive(@Param("id")id:string,@Headers()h:HeaderMap){return this.employees.archive(id,actor(h));}
 @Post(":id/relationships")@RequireRoles(...hr)relationship(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.employees.relationship(id,b,actor(h));}
    @Get(":id/leave-balance")@RequireRoles(...readers)balance(@Param("id")id:string,@Headers()h:HeaderMap){return this.leave.balance(id,actor(h));}
}

@Controller("hr/organization") export class OrganizationController{constructor(private readonly organization:OrganizationService){}@Get("chart")@RequireRoles(...readers)chart(){return this.organization.chart();}@Get("departments")@RequireRoles(...readers)departments(){return this.organization.departments();}@Post("departments")@RequireRoles(...hr)department(@Body()b:any){return this.organization.createDepartment(b);}@Get("teams")@RequireRoles(...readers)teams(){return this.organization.teams();}@Post("teams")@RequireRoles(...hr)team(@Body()b:any){return this.organization.createTeam(b);}@Get("positions")@RequireRoles(...readers)positions(){return this.organization.positions();}@Post("positions")@RequireRoles(...hr)position(@Body()b:any){return this.organization.createPosition(b);}}

@Controller("hr/contracts") export class EmploymentContractsController{constructor(private readonly contracts:EmploymentContractsService){}@Get()@RequireRoles("GERENTE_GENERAL","RRHH")list(@Headers()h:HeaderMap){return this.contracts.list(actor(h));}@Post()@RequireRoles(...hr)create(@Body()b:any,@Headers()h:HeaderMap){return this.contracts.create(b,actor(h));}@Get(":id")@RequireRoles("GERENTE_GENERAL","RRHH")get(@Param("id")id:string,@Headers()h:HeaderMap){return this.contracts.get(id,actor(h));}@Patch(":id")@RequireRoles(...hr)update(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.contracts.update(id,b,actor(h));}@Post(":id/submit-review")@RequireRoles(...hr)review(@Param("id")id:string,@Headers()h:HeaderMap){return this.contracts.submitReview(id,actor(h));}@Post(":id/ready-for-signature")@RequireRoles(...hr)ready(@Param("id")id:string,@Headers()h:HeaderMap){return this.contracts.ready(id,actor(h));}@Post(":id/request-signature")@RequireRoles(...hr)signature(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.contracts.requestSignature(id,b,actor(h));}@Post(":id/prepare-registration")@RequireRoles(...hr)prepare(@Param("id")id:string,@Headers()h:HeaderMap){return this.contracts.prepareRegistration(id,actor(h));}@Post(":id/register-external")@RequireRoles(...hr)register(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.contracts.registerExternal(id,b,actor(h));}@Post(":id/terminate")@RequireRoles(...hr)terminate(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.contracts.terminate(id,b,actor(h));}}

@Controller("hr/annexes") export class EmploymentAnnexesController{constructor(private readonly annexes:EmploymentAnnexesService){}@Get()@RequireRoles("GERENTE_GENERAL","RRHH")list(@Headers()h:HeaderMap){return this.annexes.list(actor(h));}@Post()@RequireRoles(...hr)create(@Body()b:any,@Headers()h:HeaderMap){return this.annexes.create(b,actor(h));}@Get(":id")@RequireRoles("GERENTE_GENERAL","RRHH")get(@Param("id")id:string,@Headers()h:HeaderMap){return this.annexes.get(id,actor(h));}@Post(":id/request-signature")@RequireRoles(...hr)signature(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.annexes.requestSignature(id,b,actor(h));}@Post(":id/activate")@RequireRoles(...hr)activate(@Param("id")id:string,@Headers()h:HeaderMap){return this.annexes.activate(id,actor(h));}}

@Controller("hr/onboarding") export class OnboardingController{constructor(private readonly service:OnboardingService){}@Get()@RequireRoles(...managers)list(){return this.service.list();}@Post()@RequireRoles(...hr)create(@Body()b:any,@Headers()h:HeaderMap){return this.service.create(b,actor(h));}@Get(":id")@RequireRoles(...managers)get(@Param("id")id:string){return this.service.get(id);}@Post(":id/tasks/:taskId/complete")@RequireRoles(...managers)complete(@Param("id")id:string,@Param("taskId")taskId:string,@Headers()h:HeaderMap){return this.service.complete(id,taskId,actor(h));}@Post(":id/activate-employee")@RequireRoles(...hr)activate(@Param("id")id:string,@Headers()h:HeaderMap){return this.service.activate(id,actor(h));}}

@Controller("hr/offboarding") export class OffboardingController{constructor(private readonly service:OffboardingService){}@Get()@RequireRoles(...managers)list(){return this.service.list();}@Post()@RequireRoles(...hr)create(@Body()b:any,@Headers()h:HeaderMap){return this.service.create(b,actor(h));}@Get(":id")@RequireRoles(...managers)get(@Param("id")id:string){return this.service.get(id);}@Post(":id/tasks/:taskId/complete")@RequireRoles(...managers)complete(@Param("id")id:string,@Param("taskId")taskId:string,@Body()b:any,@Headers()h:HeaderMap){return this.service.complete(id,taskId,b,actor(h));}@Post(":id/finalize")@RequireRoles(...hr)finalize(@Param("id")id:string,@Headers()h:HeaderMap){return this.service.finalize(id,actor(h));}}

@Controller("hr/leave") export class LeaveController{constructor(private readonly leave:LeaveService){}@Get()@RequireRoles(...readers)list(@Headers()h:HeaderMap){return this.leave.list(actor(h));}@Post()@RequireRoles(...readers)create(@Body()b:any,@Headers()h:HeaderMap){return this.leave.request(b,actor(h));}@Get(":id")@RequireRoles(...readers)get(@Param("id")id:string,@Headers()h:HeaderMap){return this.leave.get(id,actor(h));}@Post(":id/approve")@RequireRoles(...managers)approve(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.leave.decide(id,true,b,actor(h));}@Post(":id/reject")@RequireRoles(...managers)reject(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.leave.decide(id,false,b,actor(h));}@Get("employee/:employeeId/balance")@RequireRoles(...readers)balance(@Param("employeeId")id:string,@Headers()h:HeaderMap){return this.leave.balance(id,actor(h));}@Post("employee/:employeeId/adjust")@RequireRoles(...hr)adjust(@Param("employeeId")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.leave.adjust(id,Number(b.units),b.reason,actor(h));}}

@Controller("hr/medical-leave") export class MedicalLeaveController{constructor(private readonly service:MedicalLeaveService){}@Get()@RequireRoles(...hr)list(@Headers()h:HeaderMap){return this.service.list(actor(h));}@Post()@RequireRoles(...hr)create(@Body()b:any,@Headers()h:HeaderMap){return this.service.create(b,actor(h));}}

@Controller("hr/payroll") export class PayrollController{constructor(private readonly payroll:PayrollService){}@Get("periods")@RequireRoles("RRHH","FINANZAS")periods(){return this.payroll.periods();}@Post("periods")@RequireRoles(...hr)create(@Body()b:any,@Headers()h:HeaderMap){return this.payroll.create(b,actor(h));}@Get("periods/:id")@RequireRoles("RRHH","FINANZAS")get(@Param("id")id:string,@Headers()h:HeaderMap){return this.payroll.get(id,actor(h));}@Post("periods/:id/calculate")@RequireRoles(...hr)calculate(@Param("id")id:string,@Headers()h:HeaderMap){return this.payroll.calculate(id,actor(h));}@Post("periods/:id/submit-review")@RequireRoles(...hr)review(@Param("id")id:string,@Headers()h:HeaderMap){return this.payroll.submitReview(id,actor(h));}@Post("periods/:id/approve")@RequireRoles(...hr)approve(@Param("id")id:string,@Headers()h:HeaderMap){return this.payroll.approve(id,actor(h));}@Post("periods/:id/mark-paid")@RequireRoles("RRHH","FINANZAS")paid(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.payroll.markPaid(id,b,actor(h));}@Post("periods/:id/close")@RequireRoles(...hr)close(@Param("id")id:string,@Headers()h:HeaderMap){return this.payroll.close(id,actor(h));}@Get("periods/:id/payslips")@RequireRoles(...readers)payslips(@Param("id")id:string,@Headers()h:HeaderMap){return this.payroll.payslips(id,actor(h));}@Post("periods/:id/payslips")@RequireRoles(...hr)generate(@Param("id")id:string,@Headers()h:HeaderMap){return this.payroll.generatePayslips(id,actor(h));}}

@Controller("hr/lre") export class LreController{constructor(private readonly lre:LreService){}@Post(":period/generate")@RequireRoles(...hr)generate(@Param("period")p:string,@Headers()h:HeaderMap){return this.lre.generate(p,actor(h));}@Get(":period")@RequireRoles("RRHH","FINANZAS")get(@Param("period")p:string){return this.lre.get(p);}@Post(":period/validate")@RequireRoles(...hr)validate(@Param("period")p:string,@Headers()h:HeaderMap){return this.lre.validate(p,actor(h));}@Get(":period/download")@RequireRoles("RRHH","FINANZAS")download(@Param("period")p:string,@Headers()h:HeaderMap){return this.lre.download(p,actor(h));}@Post(":period/register-submission")@RequireRoles(...hr)submit(@Param("period")p:string,@Body()b:any,@Headers()h:HeaderMap){return this.lre.registerSubmission(p,b,actor(h));}@Post(":period/register-rectification")@RequireRoles(...hr)rectify(@Param("period")p:string,@Body()b:any,@Headers()h:HeaderMap){return this.lre.rectify(p,b,actor(h));}@Get("schemas/all")@RequireRoles(...hr)schemas(){return this.lre.schemas();}@Post("schemas")@RequireRoles(...hr)schema(@Body()b:any,@Headers()h:HeaderMap){return this.lre.createSchema(b,actor(h));}}

@Controller("hr/workforce") export class WorkforceController{constructor(private readonly service:WorkforceOperationsService){}@Get("attendance")@RequireRoles(...readers)attendance(){return this.service.attendanceStatus();}@Get("schedules")@RequireRoles(...readers)schedules(){return this.service.schedules();}@Post("schedules")@RequireRoles(...hr)schedule(@Body()b:any,@Headers()h:HeaderMap){return this.service.createSchedule(b,actor(h));}@Get("assets")@RequireRoles(...managers)assets(){return this.service.assets();}@Post("assets/assign")@RequireRoles(...hr)asset(@Body()b:any,@Headers()h:HeaderMap){return this.service.assignAsset(b,actor(h));}@Post("assets/:id/return")@RequireRoles(...hr)returnAsset(@Param("id")id:string,@Body()b:any,@Headers()h:HeaderMap){return this.service.returnAsset(id,b,actor(h));}@Get("goals")@RequireRoles(...managers)goals(){return this.service.goals();}@Post("goals")@RequireRoles(...managers)goal(@Body()b:any,@Headers()h:HeaderMap){return this.service.createGoal(b,actor(h));}@Get("training")@RequireRoles(...readers)training(){return this.service.training();}@Post("training/courses")@RequireRoles(...hr)course(@Body()b:any,@Headers()h:HeaderMap){return this.service.createCourse(b,actor(h));}@Post("training/assign")@RequireRoles(...hr)assign(@Body()b:any,@Headers()h:HeaderMap){return this.service.assignTraining(b,actor(h));}@Get("performance")@RequireRoles(...managers)performance(){return this.service.performance();}@Post("requests")@RequireRoles(...readers)request(@Body()b:any,@Headers()h:HeaderMap){return this.service.createRequest(b,actor(h));}}
