import { ConflictException,Injectable,NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { HrEvent } from "@zyteron/contracts";
import { createServerSupabase,pageBounds } from "../domain/server-supabase.js";

type Row=Record<string,any>;type Filters=Record<string,string|number|boolean|null|undefined>;
export interface HrPage{page:number;pageSize:number;search?:string;status?:string;departmentId?:string;managerId?:string;employeeId?:string;}
const now=()=>new Date().toISOString(),snake=(key:string)=>key.replace(/[A-Z]/g,letter=>`_${letter.toLowerCase()}`),camel=(key:string)=>key.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase());
const toRow=(value:Row)=>Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined).map(([key,item])=>[snake(key),item]));
const fromRow=<T>(value:Row):T=>Object.fromEntries(Object.entries(value).map(([key,item])=>[camel(key),item])) as T;
@Injectable() export class HrRepository{
  private readonly supabase=createServerSupabase();private readonly memory=new Map<string,Map<string,Row>>();private employeeSequence=0;private contractSequence=0;
  private store(table:string){let value=this.memory.get(table);if(!value){value=new Map();this.memory.set(table,value);}return value;}
  configured(){return Boolean(this.supabase);}
  async list<T>(table:string,filters:Filters={},order="created_at",ascending=false):Promise<T[]>{if(!this.supabase)return[...this.store(table).values()].filter(row=>Object.entries(filters).every(([key,value])=>value===undefined||row[key]===value)).sort((a,b)=>String(ascending?a[camel(order)]??"":b[camel(order)]??"").localeCompare(String(ascending?b[camel(order)]??"":a[camel(order)]??""))) as T[];let query=(this.supabase.from(table)as any).select("*");for(const[key,value]of Object.entries(filters))if(value!==undefined)query=value===null?query.is(snake(key),null):query.eq(snake(key),value);const{data,error}=await query.order(order,{ascending});if(error)throw error;return(data??[]).map((item:Row)=>fromRow<T>(item));}
  async page<T>(table:string,q:HrPage):Promise<{items:T[];page:number;pageSize:number;total:number;totalPages:number}>{if(!this.supabase){let items=[...this.store(table).values()];const search=q.search?.toLowerCase();items=items.filter(item=>(!q.status||item.status===q.status)&&(!q.departmentId||item.departmentId===q.departmentId)&&(!q.managerId||item.managerId===q.managerId)&&(!q.employeeId||item.employeeId===q.employeeId)&&(!search||Object.values(item).some(value=>typeof value==="string"&&value.toLowerCase().includes(search))));items.sort((a,b)=>String(b.updatedAt??b.createdAt??"").localeCompare(String(a.updatedAt??a.createdAt??"")));const start=(q.page-1)*q.pageSize;return{items:items.slice(start,start+q.pageSize)as T[],page:q.page,pageSize:q.pageSize,total:items.length,totalPages:Math.ceil(items.length/q.pageSize)};}const{from,to}=pageBounds(q.page,q.pageSize);let query=(this.supabase.from(table)as any).select("*",{count:"exact"});if(q.search){const columns=table==="employees"?["employee_number","rut","first_name","last_name","corporate_email"]:["name","code"];query=query.or(columns.map(column=>`${column}.ilike.%${q.search!.replace(/[,()]/g," ")}%`).join(","));}for(const[key,value]of Object.entries({status:q.status,departmentId:q.departmentId,managerId:q.managerId,employeeId:q.employeeId}))if(value)query=query.eq(snake(key),value);const{data,error,count}=await query.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map((item:Row)=>fromRow<T>(item)),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async get<T>(table:string,id:string):Promise<T|undefined>{if(!this.supabase)return this.store(table).get(id)as T|undefined;const{data,error}=await(this.supabase.from(table)as any).select("*").eq("id",id).maybeSingle();if(error)throw error;return data?fromRow<T>(data as Row):undefined;}
  async create<T extends Row>(table:string,input:T):Promise<T>{const stamp=now(),item={id:randomUUID(),...input,createdAt:input.createdAt??stamp,updatedAt:input.updatedAt??stamp}as T;if(!this.supabase){if(table==="employees"&&[...this.store(table).values()].some(row=>row.rut===item.rut))throw new ConflictException("Ya existe un colaborador con ese RUT.");this.store(table).set(String(item.id),item);return item;}const{data,error}=await(this.supabase.from(table)as any).insert(toRow(item)).select("*").single();if(error?.code==="23505")throw new ConflictException("El registro laboral ya existe.");if(error)throw error;return fromRow<T>(data as Row);}
  async update<T extends Row>(table:string,id:string,patch:Partial<T>):Promise<T>{if(!this.supabase){const current=this.store(table).get(id);if(!current)throw new NotFoundException("Registro RR.HH. no encontrado.");const next={...current,...patch,updatedAt:now()}as unknown as T;this.store(table).set(id,next);return next;}const{data,error}=await(this.supabase.from(table)as any).update(toRow({...patch,updatedAt:now()})).eq("id",id).select("*").single();if(error)throw error;return fromRow<T>(data as Row);}
  async nextEmployeeNumber(){if(!this.supabase)return`EMP-${String(++this.employeeSequence).padStart(6,"0")}`;const{data,error}=await this.supabase.rpc("next_employee_number");if(error)throw error;return String(data);}
  async nextContractNumber(){if(!this.supabase)return`CTR-LAB-${new Date().getUTCFullYear()}-${String(++this.contractSequence).padStart(6,"0")}`;const{data,error}=await this.supabase.rpc("next_employment_contract_number");if(error)throw error;return String(data);}
  async publish(employeeId:string|null,aggregateType:string,aggregateId:string,eventType:string,actorId:string|null,payload:Row={}){const event:HrEvent={id:randomUUID(),employeeId,aggregateType,aggregateId,eventType,actorId,payload,occurredAt:now()};if(!this.supabase){this.store("hr_events").set(event.id,event);return event;}const{error}=await this.supabase.from("hr_events").insert(toRow(event));if(error)throw error;return event;}
}
