import { BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException,Optional } from "@nestjs/common";
import type { Employee,HrAssetAssignment,LeaveBalance,LeaveRequest,MedicalLeaveRecord,OffboardingInstance,OnboardingInstance } from "@zyteron/contracts";
import { SupportCatalogService,SupportTicketService } from "../support/support.service.js";
import { AttendanceProvider,LeavePolicyEngine } from "./hr.providers.js";
import { HrRepository } from "./hr.repository.js";
import { EmployeeAccessService,type HrActor } from "./employees.service.js";

const now=()=>new Date().toISOString(),today=()=>now().slice(0,10),uuid=(value:unknown,label:string,optional=false)=>{if(optional&&(value===null||value===undefined||value===""))return null;if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new BadRequestException(`${label} inválido.`);return value;},required=(value:unknown,label:string)=>{if(typeof value!=="string"||!value.trim())throw new BadRequestException(`${label} obligatorio.`);return value.trim();},date=(value:unknown,label:string)=>{if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(`${value}T12:00:00Z`)))throw new BadRequestException(`${label} inválida.`);return value;},hr=(actor:HrActor)=>{if(actor.role!=="RRHH")throw new ForbiddenException("Acción reservada para RR.HH.");};

@Injectable() export class OnboardingService{
 constructor(private readonly repository:HrRepository){}
 list(){return this.repository.list<OnboardingInstance>("onboarding_instances",{},"created_at",false);}async get(id:string){const item=await this.repository.get<OnboardingInstance>("onboarding_instances",id);if(!item)throw new NotFoundException("Onboarding no encontrado.");return{...item,tasks:await this.repository.list<any>("onboarding_tasks",{onboardingId:id},"position",true)};}
 async create(body:any,actor:HrActor){hr(actor);const employee=await this.repository.get<Employee>("employees",uuid(body.employeeId,"Colaborador")!);if(!employee)throw new NotFoundException("Colaborador no encontrado.");const template=body.templateId?await this.repository.get<any>("onboarding_templates",uuid(body.templateId,"Plantilla")!):null,instance=await this.repository.create<any>("onboarding_instances",{employeeId:employee.id,templateId:template?.id??null,status:"IN_PROGRESS",targetDate:body.targetDate?date(body.targetDate,"Fecha objetivo"):employee.hireDate,progress:0,startedAt:now(),completedAt:null,createdBy:actor.userId,createdAt:now(),updatedAt:now()}),definitions=Array.isArray(template?.tasks)?template.tasks:body.tasks??[{title:"Datos laborales validados",ownerType:"HR"},{title:"Contrato y firma",ownerType:"HR"},{title:"Cuenta y accesos",ownerType:"SECURITY"},{title:"Activos asignados",ownerType:"IT"},{title:"Inducción",ownerType:"MANAGER"}];for(const[index,task]of definitions.entries())await this.repository.create<any>("onboarding_tasks",{onboardingId:instance.id,title:required(task.title,"Tarea"),ownerType:task.ownerType||"HR",ownerId:uuid(task.ownerId,"Responsable",true),status:"PENDING",dueDate:task.dueDate||instance.targetDate,critical:task.critical!==false,position:index+1,completedAt:null,completedBy:null});await this.repository.update<any>("employees",employee.id,{status:"ONBOARDING"});await this.repository.publish(employee.id,"ONBOARDING",instance.id,"ONBOARDING_STARTED",actor.userId);return this.get(instance.id);}
 async complete(id:string,taskId:string,actor:HrActor){const instance=await this.get(id),task=(instance.tasks as any[]).find(item=>item.id===taskId);if(!task)throw new NotFoundException("Tarea no encontrada.");if(task.status==="COMPLETED")return task;const updated=await this.repository.update<any>("onboarding_tasks",taskId,{status:"COMPLETED",completedAt:now(),completedBy:actor.userId}),tasks=await this.repository.list<any>("onboarding_tasks",{onboardingId:id}),complete=tasks.filter(item=>item.status==="COMPLETED").length,progress=tasks.length?Math.round(complete/tasks.length*100):0;await this.repository.update<any>("onboarding_instances",id,{progress,status:progress===100?"COMPLETED":"IN_PROGRESS",completedAt:progress===100?now():null});await this.repository.publish(instance.employeeId,"ONBOARDING_TASK",taskId,"ONBOARDING_TASK_COMPLETED",actor.userId,{progress});return updated;}
 async activate(id:string,actor:HrActor){hr(actor);const instance=await this.get(id);if(instance.progress!==100)throw new ConflictException("Completa las tareas críticas antes de activar al colaborador.");await this.repository.update<any>("employees",instance.employeeId,{status:"ACTIVE",hireDate:(await this.repository.get<Employee>("employees",instance.employeeId))?.hireDate||today()});await this.repository.publish(instance.employeeId,"EMPLOYEE",instance.employeeId,"EMPLOYEE_ACTIVATED",actor.userId);return this.repository.get<Employee>("employees",instance.employeeId);}
}

@Injectable() export class OffboardingService{
 constructor(private readonly repository:HrRepository){}
 list(){return this.repository.list<OffboardingInstance>("offboarding_instances",{},"created_at",false);}async get(id:string){const item=await this.repository.get<OffboardingInstance>("offboarding_instances",id);if(!item)throw new NotFoundException("Offboarding no encontrado.");return{...item,tasks:await this.repository.list<any>("offboarding_tasks",{offboardingId:id},"position",true)};}
 async create(body:any,actor:HrActor){hr(actor);const employee=await this.repository.get<Employee>("employees",uuid(body.employeeId,"Colaborador")!);if(!employee||!["ACTIVE","LEAVE","SUSPENDED"].includes(employee.status))throw new ConflictException("El colaborador no tiene una relación activa para iniciar salida.");const item=await this.repository.create<any>("offboarding_instances",{employeeId:employee.id,effectiveDate:date(body.effectiveDate,"Fecha efectiva"),reasonCategory:required(body.reasonCategory,"Motivo"),status:"INITIATED",criticalBlockers:0,startedAt:now(),completedAt:null,createdBy:actor.userId,createdAt:now(),updatedAt:now()}),tasks=[...["Documentación legal","Revocación de accesos","Transferencia de proyectos y tareas","Validación financiera","Cierre documental"].map((title,index)=>({title,ownerType:["HR","SECURITY","MANAGER","FINANCE","HR"][index],critical:true})),{title:"Devolución de activos",ownerType:"IT",critical:true}];for(const[index,task]of tasks.entries())await this.repository.create<any>("offboarding_tasks",{offboardingId:item.id,title:task.title,ownerType:task.ownerType,ownerId:null,status:"PENDING",critical:task.critical,position:index+1,completedAt:null,completedBy:null,evidenceDocumentId:null});await this.repository.update<any>("employees",employee.id,{status:"OFFBOARDING"});await this.repository.publish(employee.id,"OFFBOARDING",item.id,"OFFBOARDING_STARTED",actor.userId,{effectiveDate:item.effectiveDate});await this.repository.publish(employee.id,"ACCESS",item.id,"ACCESS_REVOCATION_REQUIRED",actor.userId,{effectiveDate:item.effectiveDate});await this.repository.publish(employee.id,"ASSET",item.id,"ASSET_RETURN_REQUIRED",actor.userId);return this.get(item.id);}
 async complete(id:string,taskId:string,body:any,actor:HrActor){const instance=await this.get(id),task=(instance.tasks as any[]).find(item=>item.id===taskId);if(!task)throw new NotFoundException("Tarea no encontrada.");const item=await this.repository.update<any>("offboarding_tasks",taskId,{status:"COMPLETED",completedAt:now(),completedBy:actor.userId,evidenceDocumentId:uuid(body.evidenceDocumentId,"Evidencia",true),notes:body.notes||null});return item;}
 async finalize(id:string,actor:HrActor){hr(actor);const instance=await this.get(id),tasks=instance.tasks as any[],assets=(await this.repository.list<HrAssetAssignment>("asset_assignments",{employeeId:instance.employeeId})).filter(item=>!item.returnedAt),critical=tasks.filter(item=>item.critical&&item.status!=="COMPLETED");if(critical.length||assets.length){await this.repository.update<any>("offboarding_instances",id,{status:"BLOCKED",criticalBlockers:critical.length+assets.length});throw new ConflictException(`Salida bloqueada: ${critical.length} tareas críticas y ${assets.length} activos pendientes.`);}await this.repository.update<any>("offboarding_instances",id,{status:"COMPLETED",criticalBlockers:0,completedAt:now()});await this.repository.update<any>("employees",instance.employeeId,{status:"TERMINATED",terminationDate:instance.effectiveDate});const relationships=await this.repository.list<any>("employment_relationships",{employeeId:instance.employeeId,status:"ACTIVE"});for(const relationship of relationships)await this.repository.update<any>("employment_relationships",relationship.id,{status:"ENDED",endDate:instance.effectiveDate});await this.repository.publish(instance.employeeId,"EMPLOYEE",instance.employeeId,"EMPLOYEE_TERMINATED",actor.userId,{effectiveDate:instance.effectiveDate});return this.repository.get<Employee>("employees",instance.employeeId);}
}

@Injectable() export class LeaveService{
 constructor(private readonly repository:HrRepository,private readonly policy:LeavePolicyEngine,private readonly access:EmployeeAccessService){}
 async list(actor?:HrActor){const items=await this.repository.list<LeaveRequest>("leave_requests",{},"start_date",false);if(!actor)return items;const visible=await Promise.all(items.map(async item=>{const employee=await this.repository.get<Employee>("employees",item.employeeId);if(!employee)return false;try{await this.access.assert(employee,actor);return true;}catch{return false;}}));return items.filter((_,index)=>visible[index]);}async get(id:string,actor?:HrActor){const item=await this.repository.get<LeaveRequest>("leave_requests",id);if(!item)throw new NotFoundException("Solicitud de ausencia no encontrada.");if(actor){const employee=await this.repository.get<Employee>("employees",item.employeeId);if(!employee)throw new NotFoundException("Colaborador no encontrado.");await this.access.assert(employee,actor);}return item;}
 async request(body:any,actor:HrActor){const employeeId=uuid(body.employeeId,"Colaborador")!,employee=await this.repository.get<Employee>("employees",employeeId);if(!employee)throw new NotFoundException("Colaborador no encontrado.");if(actor.role!=="RRHH"&&employee.userId!==actor.userId)throw new ForbiddenException("Solo puedes solicitar ausencias propias.");const startDate=date(body.startDate,"Inicio"),endDate=date(body.endDate,"Término"),overlaps=(await this.repository.list<LeaveRequest>("leave_requests",{employeeId})).some(item=>!["REJECTED","CANCELLED"].includes(item.status)&&item.startDate<=endDate&&item.endDate>=startDate);if(overlaps)throw new ConflictException("Existe una ausencia superpuesta.");const requestedUnits=body.requestedUnits===undefined?this.policy.requestedUnits(startDate,endDate):Number(body.requestedUnits),item=await this.repository.create<any>("leave_requests",{employeeId,leaveType:body.leaveType||"VACATION",startDate,endDate,requestedUnits,unit:body.unit||"DAYS",status:"PENDING_MANAGER",approverId:uuid(body.approverId,"Aprobador",true),submittedAt:now(),approvedAt:null,reasonCategory:body.reasonCategory||null,documentId:uuid(body.documentId,"Documento",true),createdBy:actor.userId,createdAt:now(),updatedAt:now()});await this.repository.publish(employeeId,"LEAVE_REQUEST",item.id,"VACATION_REQUESTED",actor.userId,{leaveType:item.leaveType,startDate,endDate,requestedUnits});return item;}
 async decide(id:string,approved:boolean,body:any,actor:HrActor){const item=await this.get(id,actor);if(!["RRHH","GERENTE_GENERAL","JEFE_DESARROLLO","TECH_LEAD","OPERACIONES","JEFE_VENTAS"].includes(actor.role))throw new ForbiddenException("Sin permiso para aprobar ausencias.");if(!["PENDING_MANAGER","PENDING_HR"].includes(item.status))throw new ConflictException("La solicitud ya fue resuelta.");if(!approved){const rejected=await this.repository.update<any>("leave_requests",id,{status:"REJECTED",approverId:actor.userId,decisionReason:required(body.reason,"Motivo")});await this.repository.publish(item.employeeId,"LEAVE_REQUEST",id,"LEAVE_REJECTED",actor.userId);return rejected;}if(item.leaveType==="VACATION"){const balance=await this.balance(item.employeeId);if(balance.available<item.requestedUnits&&!body.overrideReason)throw new ConflictException("Saldo insuficiente; un override requiere motivo.");await this.ledger(item.employeeId,-item.requestedUnits,"USED",`Solicitud ${id}`,actor,id);}const updated=await this.repository.update<any>("leave_requests",id,{status:"APPROVED",approverId:actor.userId,approvedAt:now(),decisionReason:body.overrideReason||null});await this.repository.publish(item.employeeId,"LEAVE_REQUEST",id,"LEAVE_APPROVED",actor.userId,{startDate:item.startDate,endDate:item.endDate});return updated;}
 async balance(employeeId:string,actor?:HrActor):Promise<LeaveBalance>{const employee=await this.repository.get<Employee>("employees",employeeId);if(!employee)throw new NotFoundException("Colaborador no encontrado.");if(actor)await this.access.assert(employee,actor);const entries=await this.repository.list<any>("leave_ledger",{employeeId}),accrued=entries.filter(item=>["ACCRUAL","CARRYOVER"].includes(item.entryType)).reduce((sum,item)=>sum+Number(item.units),0),used=Math.abs(entries.filter(item=>item.entryType==="USED").reduce((sum,item)=>sum+Number(item.units),0)),adjusted=entries.filter(item=>item.entryType==="ADJUSTMENT").reduce((sum,item)=>sum+Number(item.units),0),available=entries.reduce((sum,item)=>sum+Number(item.units),0),existing=(await this.repository.list<LeaveBalance>("leave_balances",{employeeId}))[0];if(existing)return this.repository.update<any>("leave_balances",existing.id,{accrued,used,adjusted,available});return this.repository.create<any>("leave_balances",{employeeId,policyId:null,period:new Date().getUTCFullYear().toString(),accrued,used,adjusted,available});}
 async adjust(employeeId:string,units:number,reason:string,actor:HrActor){hr(actor);if(!Number.isFinite(units)||units===0)throw new BadRequestException("Unidades de ajuste inválidas.");const before=(await this.balance(employeeId)).available,entry=await this.ledger(employeeId,units,"ADJUSTMENT",required(reason,"Motivo"),actor,null),after=(await this.balance(employeeId)).available;await this.repository.publish(employeeId,"LEAVE_BALANCE",entry.id,"LEAVE_BALANCE_ADJUSTED",actor.userId,{before,after,units,reason});return{entry,balance:await this.balance(employeeId)};}
 private ledger(employeeId:string,units:number,entryType:string,reason:string,actor:HrActor,requestId:string|null){return this.repository.create<any>("leave_ledger",{employeeId,leaveRequestId:requestId,entryType,units,entryDate:today(),reason,actorId:actor.userId,balanceAfter:null});}
}

@Injectable() export class MedicalLeaveService{
 constructor(private readonly repository:HrRepository){}list(actor:HrActor){hr(actor);return this.repository.list<MedicalLeaveRecord>("medical_leave_records",{},"start_date",false);}async create(body:any,actor:HrActor){hr(actor);const startDate=date(body.startDate,"Inicio"),endDate=date(body.endDate,"Término"),days=Math.floor((Date.parse(`${endDate}T12:00:00Z`)-Date.parse(`${startDate}T12:00:00Z`))/86400000)+1,item=await this.repository.create<any>("medical_leave_records",{employeeId:uuid(body.employeeId,"Colaborador")!,startDate,endDate,days,status:"RECEIVED",issuerReference:body.issuerReference?.trim()||null,documentId:uuid(body.documentId,"Documento",true),receivedAt:now(),createdAt:now(),updatedAt:now()});await this.repository.publish(item.employeeId,"MEDICAL_LEAVE",item.id,"LEAVE_STARTED",actor.userId,{startDate,endDate});return item;}}

@Injectable() export class WorkforceOperationsService{
 constructor(private readonly repository:HrRepository,private readonly attendance:AttendanceProvider,@Optional()private readonly supportTickets?:SupportTicketService,@Optional()private readonly supportCatalog?:SupportCatalogService){}
 attendanceStatus(){return{provider:this.attendance.status};}schedules(){return this.repository.list<any>("work_schedules",{},"name",true);}assets(){return this.repository.list<any>("asset_assignments",{},"assigned_at",false);}goals(){return this.repository.list<any>("employee_goals",{},"created_at",false);}training(){return this.repository.list<any>("training_assignments",{},"assigned_at",false);}performance(){return this.repository.list<any>("performance_reviews",{},"created_at",false);}
 createSchedule(body:any,actor:HrActor){hr(actor);return this.repository.create<any>("work_schedules",{name:required(body.name,"Nombre"),weeklyHours:Number(body.weeklyHours),timezone:body.timezone||"America/Santiago",scheduleType:body.scheduleType||"FIXED",rules:body.rules||{},active:true,createdBy:actor.userId});}
 assignAsset(body:any,actor:HrActor){hr(actor);return this.repository.create<any>("asset_assignments",{assetId:uuid(body.assetId,"Activo")!,employeeId:uuid(body.employeeId,"Colaborador")!,assignedAt:body.assignedAt||now(),conditionOut:body.conditionOut||null,evidenceDocumentId:uuid(body.evidenceDocumentId,"Evidencia",true),returnedAt:null,conditionReturn:null,createdBy:actor.userId});}
 async returnAsset(id:string,body:any,actor:HrActor){hr(actor);return this.repository.update<any>("asset_assignments",id,{returnedAt:now(),conditionReturn:required(body.conditionReturn,"Condición de devolución"),returnEvidenceDocumentId:uuid(body.evidenceDocumentId,"Evidencia",true)});}
 createGoal(body:any,actor:HrActor){return this.repository.create<any>("employee_goals",{employeeId:uuid(body.employeeId,"Colaborador")!,title:required(body.title,"Título"),description:body.description||null,period:required(body.period,"Período"),ownerId:uuid(body.ownerId||actor.userId,"Responsable",true),status:"ACTIVE",progress:0,evidence:{},createdBy:actor.userId});}
 createCourse(body:any,actor:HrActor){hr(actor);return this.repository.create<any>("training_courses",{code:required(body.code,"Código").toUpperCase(),name:required(body.name,"Nombre"),description:body.description||null,requiredForRole:body.requiredForRole||null,validityDays:body.validityDays||null,active:true,createdBy:actor.userId});}
 async assignTraining(body:any,actor:HrActor){hr(actor);const item=await this.repository.create<any>("training_assignments",{courseId:uuid(body.courseId,"Curso")!,employeeId:uuid(body.employeeId,"Colaborador")!,status:"ASSIGNED",assignedAt:now(),dueDate:body.dueDate?date(body.dueDate,"Vencimiento"):null,completedAt:null,certificateDocumentId:null,createdAt:now(),updatedAt:now()});return item;}
 async createRequest(body:any,actor:HrActor){if(!this.supportTickets||!this.supportCatalog)throw new ConflictException("Service Desk no disponible.");const queues=await this.supportCatalog.queues(),queue=queues.find(item=>item.code==="HR");if(!queue)throw new ConflictException("Cola RR.HH. no configurada.");return this.supportTickets.create({requesterType:"INTERNAL_USER",requesterUserId:actor.userId,subject:`RR.HH. · ${body.category||"OTHER"} · ${required(body.subject,"Asunto")}`,description:required(body.description,"Descripción"),ticketType:body.category==="DOCUMENT_REQUEST"?"DOCUMENT_REQUEST":"OTHER",channel:"INTERNAL",queueId:queue.id,privacy:"RESTRICTED",clientVisibility:"INTERNAL_ONLY"},{...actor});}
}
