import { BadRequestException, ConflictException, Injectable, UnprocessableEntityException } from "@nestjs/common";
import type { BankAccount, BankTransaction, CashAccount, Payment, ReconciliationCandidate, ReconciliationMatch, StatementPreview, StatementPreviewRow, VendorPayment } from "@zyteron/contracts";
import { randomUUID } from "node:crypto";
import { FinanceContext } from "./finance.core.js";
import { decodeUpload, parseAmount, parseFlexibleDate } from "./finance.dte.js";
import { parseCsv, readXlsx } from "./finance.formats.js";
import { AccountingRuleEngine, LedgerService } from "./finance.ledger.js";
import { PaymentService } from "./finance.payments.js";
import { daysBetween, type FinanceActor, guarded, isoDate, last4, money, nowIso, oneOf, optionalText, optionalUuid, positiveAmount, r2, requiredText, requiredUuid, type Row, sha256, sum, todayCl } from "./finance.util.js";

/** Palabras societarias o genéricas que no identifican a una contraparte en la glosa bancaria. */
const genericWords=new Set(["spa","ltda","limitada","sociedad","cliente","clientes","servicios","comercial","empresa","empresas","chile","eirl","transferencia","transf","pago","abono","deposito","proveedor","inversiones","group","grupo"]);
const normalize=(value:string)=>value.normalize("NFD").replace(/[̀-ͯ]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const headerNames:Record<string,string[]>={date:["fecha","fecha operacion","fecha contable","fecha movimiento","date"],description:["descripcion","glosa","detalle","concepto","movimiento","descripcion movimiento"],amount:["monto","importe","amount"],debit:["cargo","cargos","debito","debitos","retiro","giros","cargos clp"],credit:["abono","abonos","credito","creditos","deposito","depositos","abonos clp"],balance:["saldo","saldo disponible","saldo contable"],reference:["n documento","nro documento","documento","referencia","nro operacion","n operacion","numero documento"]};
export function detectMapping(headers:string[]){const normalized=headers.map(normalize);const find=(names:string[])=>{const index=normalized.findIndex((h)=>names.includes(h));return index>=0?headers[index]!:normalized.findIndex((h)=>names.some((n)=>h.startsWith(n)))>=0?headers[normalized.findIndex((h)=>names.some((n)=>h.startsWith(n)))]!:null;};return Object.fromEntries(Object.entries(headerNames).map(([key,names])=>[key,find(names)])) as Record<string,string|null>;}
/** Hash determinístico del movimiento (cuenta|fecha|sentido|monto|glosa|referencia|saldo|ocurrencia) para no duplicar entre cartolas. */
export const transactionHash=(accountId:string,row:{date:string;direction:string;amount:number;description:string;reference:string|null;balance:number|null},occurrence:number)=>sha256([accountId,row.date,row.direction,row.amount.toFixed(2),normalize(row.description),row.reference??"",row.balance===null?"":row.balance.toFixed(2),occurrence].join("|"));

// =========================================================================================== Cuentas bancarias y cajas
@Injectable()
export class BankService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  async accounts(actor:FinanceActor){this.ctx.require(actor,"bank.view");const accounts=await this.repo.list<BankAccount>("bank_accounts",{},{order:"bankName",ascending:true});const balances=new Map((await this.repo.accountBalances("1900-01-01",todayCl())).map((b)=>[b.accountId,r2(b.opening+b.debit-b.credit)]));
    return Promise.all(accounts.map(async(account)=>{const last=(await this.repo.list<BankTransaction>("bank_transactions",{bankAccountId:account.id,balance:{neq:null}},{order:"transactionDate",limit:1}))[0];const pending=await this.repo.count("bank_transactions",{bankAccountId:account.id,reconciliationStatus:["UNRECONCILED","PARTIALLY_RECONCILED"]});return{...account,bookBalance:balances.get(account.ledgerAccountId)??0,statementBalance:last?.balance??null,statementDate:last?.transactionDate??null,pendingTransactions:pending};}));}
  async saveAccount(id:string|null,body:Row,actor:FinanceActor){
    this.ctx.requireAny(actor,"finance.settings.manage","bank.reconcile");const ledger=await this.ctx.must<Row>("chart_of_accounts",requiredUuid(body.ledgerAccountId,"Cuenta contable"),"Cuenta contable");if(ledger.accountType!=="ASSET"||!ledger.allowsPosting||!ledger.isCash)throw new UnprocessableEntityException("La cuenta contable debe ser de activo, imputable y marcada como disponible (caja/banco).");
    const data:Row={bankName:requiredText(body.bankName,"Banco",80),accountType:oneOf(body.accountType,["CHECKING","SAVINGS","VISTA","OTHER"] as const,"Tipo de cuenta"),holderName:optionalText(body.holderName,160),currency:body.currency??"CLP",ledgerAccountId:ledger.id,openingBalance:r2(body.openingBalance??0),openingBalanceDate:body.openingBalanceDate?isoDate(body.openingBalanceDate,"Fecha saldo inicial"):null,active:body.active!==false};
    if(body.accountNumber!==undefined){const masked=last4(body.accountNumber);if(!masked)throw new BadRequestException("Número de cuenta inválido.");data.accountNumberLast4=masked;}else if(!id)throw new BadRequestException("Número de cuenta obligatorio (sólo se guardan los últimos 4 dígitos).");
    const saved=id?await this.repo.update<BankAccount>("bank_accounts",id,data):await this.repo.create<BankAccount>("bank_accounts",data);await this.repo.audit(actor,id?"BANK_ACCOUNT_UPDATED":"BANK_ACCOUNT_CREATED","BANK_ACCOUNT",saved.id,`${saved.bankName} ····${saved.accountNumberLast4}`);return saved;
  }
  async cashAccounts(actor:FinanceActor){this.ctx.require(actor,"bank.view");const accounts=await this.repo.list<CashAccount>("cash_accounts",{},{order:"name",ascending:true});const balances=new Map((await this.repo.accountBalances("1900-01-01",todayCl())).map((b)=>[b.accountId,r2(b.opening+b.debit-b.credit)]));return Promise.all(accounts.map(async(a)=>{const movements=await this.repo.list<Row>("cash_movements",{cashAccountId:a.id,status:{neq:"VOIDED"}});return{...a,bookBalance:balances.get(a.ledgerAccountId)??0,movementsBalance:sum(movements.map((m)=>m.direction==="IN"?m.amount:-m.amount))};}));}
  async saveCashAccount(id:string|null,body:Row,actor:FinanceActor){this.ctx.requireAny(actor,"finance.settings.manage","bank.reconcile");const ledger=await this.ctx.must<Row>("chart_of_accounts",requiredUuid(body.ledgerAccountId,"Cuenta contable"),"Cuenta contable");if(!ledger.isCash||!ledger.allowsPosting)throw new UnprocessableEntityException("La cuenta contable debe ser imputable y de disponible.");const data={name:requiredText(body.name,"Nombre",120),custodianUserId:optionalUuid(body.custodianUserId,"Custodio"),currency:"CLP",ledgerAccountId:ledger.id,active:body.active!==false};const saved=id?await this.repo.update("cash_accounts",id,data):await this.repo.create("cash_accounts",data);await this.repo.audit(actor,"CASH_ACCOUNT_SAVED","CASH_ACCOUNT",(saved as Row).id,`Caja ${data.name}`);return saved;}
  async cashMovements(cashAccountId:string,actor:FinanceActor){this.ctx.require(actor,"bank.view");return this.repo.list<Row>("cash_movements",{cashAccountId},{order:"movementDate"});}
  async addCashMovement(body:Row,actor:FinanceActor){this.ctx.require(actor,"bank.reconcile");if(!actor.userId)throw new BadRequestException("El movimiento de caja requiere responsable identificado.");const evidence=body.evidence?decodeUpload(body.evidence,"Respaldo"):null;const movement=await this.repo.create<Row>("cash_movements",{cashAccountId:requiredUuid(body.cashAccountId,"Caja"),movementDate:isoDate(body.movementDate,"Fecha"),direction:oneOf(body.direction,["IN","OUT"] as const,"Sentido"),amount:positiveAmount(body.amount,"Monto"),description:requiredText(body.description,"Descripción",300),responsibleUserId:actor.userId,evidencePath:evidence?await this.repo.saveFile("finance-documents",`cash/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType):null,status:"RECORDED",createdBy:actor.userId});await this.repo.audit(actor,"CASH_MOVEMENT","CASH_MOVEMENT",movement.id,`${movement.direction} ${money(movement.amount)}: ${movement.description}`);return movement;}
  async voidCashMovement(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"bank.reconcile");const reason=requiredText(body.reason,"Motivo",300);const updated=await this.repo.update("cash_movements",id,{status:"VOIDED",voidReason:reason});await this.repo.audit(actor,"CASH_MOVEMENT_VOIDED","CASH_MOVEMENT",id,`Movimiento anulado: ${reason}`);return updated;}
}

// =========================================================================================== Importación de cartolas
@Injectable()
export class StatementImportService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  async preview(body:Row,actor:FinanceActor):Promise<StatementPreview&{bankAccountId:string}>{
    this.ctx.require(actor,"bank.import");const bankAccountId=requiredUuid(body.bankAccountId,"Cuenta bancaria");await this.ctx.must("bank_accounts",bankAccountId,"Cuenta bancaria");const file=decodeUpload(body.file,"Cartola",15*1024*1024);const format=file.fileName.toLowerCase().endsWith(".xlsx")?"XLSX":"CSV";
    const matrix=format==="XLSX"?readXlsx(file.bytes):parseCsv(file.bytes);const headerIndex=matrix.findIndex((row)=>{const m=detectMapping(row);return Boolean(m.date&&(m.amount||m.debit||m.credit));});if(headerIndex<0)throw new UnprocessableEntityException("No se encontró la fila de encabezados (fecha y monto/cargo/abono).");
    const headers=matrix[headerIndex]!;const detected=detectMapping(headers);const mapping:Record<string,string|null>={...detected,...(body.mapping&&typeof body.mapping==="object"?body.mapping:{})};const col=(key:string)=>mapping[key]?headers.indexOf(mapping[key]!):-1;
    const existing=new Set((await this.repo.list<BankTransaction>("bank_transactions",{bankAccountId})).map((t)=>t.externalHash));const occurrences=new Map<string,number>();const rows:StatementPreviewRow[]=[];
    for(const[n,raw]of matrix.slice(headerIndex+1).entries()){const errors:string[]=[];const cell=(key:string)=>{const i=col(key);return i>=0?raw[i]??"":"";};const date=parseFlexibleDate(cell("date"));if(!date)errors.push("Fecha inválida");
      let amount:number|null=null,direction:"CREDIT"|"DEBIT"|null=null;if(col("debit")>=0||col("credit")>=0){const debit=parseAmount(cell("debit"))??0,credit=parseAmount(cell("credit"))??0;if(Math.abs(debit)>0&&Math.abs(credit)>0)errors.push("Fila con cargo y abono simultáneos");else if(Math.abs(credit)>0){amount=Math.abs(credit);direction="CREDIT";}else if(Math.abs(debit)>0){amount=Math.abs(debit);direction="DEBIT";}}else{const value=parseAmount(cell("amount"));if(value!==null&&value!==0){amount=Math.abs(value);direction=value>0?"CREDIT":"DEBIT";}}
      if(!amount)errors.push("Monto vacío o cero");const description=cell("description")||"(sin glosa)";const reference=cell("reference")||null;const balance=parseAmount(cell("balance"));
      if(!date&&!amount&&/total|saldo final|saldo inicial/i.test(raw.join(" ")))continue;
      let hash:string|null=null,duplicate=false;if(!errors.length){const base=`${date}|${direction}|${amount}|${normalize(description)}|${reference??""}|${balance??""}`;const occurrence=(occurrences.get(base)??0)+1;occurrences.set(base,occurrence);hash=transactionHash(bankAccountId,{date:date!,direction:direction!,amount:amount!,description,reference,balance},occurrence);duplicate=existing.has(hash);}
      rows.push({rowNumber:headerIndex+n+2,date,description,amount,direction,reference,balance,hash,errors,duplicate});}
    const already=Boolean(await this.repo.findOne("bank_statement_imports",{bankAccountId,fileSha256:file.sha256}));
    return{bankAccountId,fileName:file.fileName,fileSha256:file.sha256,format,headers,mapping,rows,valid:rows.filter((r)=>!r.errors.length&&!r.duplicate).length,invalid:rows.filter((r)=>r.errors.length).length,duplicates:rows.filter((r)=>r.duplicate).length,alreadyImported:already};
  }
  async commit(body:Row,actor:FinanceActor){
    const preview=await this.preview(body,actor);if(preview.alreadyImported)throw new ConflictException("Esta cartola ya fue importada en la cuenta.");if(!preview.valid)throw new UnprocessableEntityException("La cartola no tiene movimientos nuevos válidos.");
    const imported=await guarded(()=>this.repo.create<Row>("bank_statement_imports",{bankAccountId:preview.bankAccountId,fileName:preview.fileName,fileSha256:preview.fileSha256,fileFormat:preview.format,columnMapping:preview.mapping,rowsTotal:preview.rows.length,rowsValid:preview.valid,rowsInvalid:preview.invalid,rowsDuplicate:preview.duplicates,errors:preview.rows.filter((r)=>r.errors.length).slice(0,200).map((r)=>({row:r.rowNumber,errors:r.errors})),status:"IMPORTED",importedBy:actor.userId,importedAt:nowIso()}));
    const rows=preview.rows.filter((r)=>!r.errors.length&&!r.duplicate).map((r)=>({bankAccountId:preview.bankAccountId,importId:imported.id,transactionDate:r.date,description:r.description.slice(0,500),amount:r.amount,direction:r.direction,reference:r.reference,balance:r.balance,externalHash:r.hash,reconciliationStatus:"UNRECONCILED",reconciledAmount:0}));for(let i=0;i<rows.length;i+=500)await guarded(()=>this.repo.createMany("bank_transactions",rows.slice(i,i+500)));
    await this.repo.audit(actor,"BANK_STATEMENT_IMPORTED","BANK_STATEMENT",imported.id,`${preview.fileName}: ${rows.length} movimientos nuevos, ${preview.duplicates} duplicados omitidos`,{sha256:preview.fileSha256});
    await this.repo.notify({eventKey:`bank-reconcile:${imported.id}`,type:"BANK_RECONCILIATION_REQUIRED",title:`${rows.length} movimientos bancarios por conciliar`,body:preview.fileName,entityType:"BANK_STATEMENT",entityId:imported.id,href:"/finance/reconciliation",severity:"INFO"});return{importId:imported.id,inserted:rows.length,duplicates:preview.duplicates,invalid:preview.invalid};
  }
  imports(actor:FinanceActor,bankAccountId?:string){this.ctx.require(actor,"bank.view");return this.repo.list<Row>("bank_statement_imports",{bankAccountId:bankAccountId||undefined},{order:"importedAt"});}
}

// =========================================================================================== Conciliación bancaria
@Injectable()
export class ReconciliationService {
  constructor(private readonly ctx:FinanceContext,private readonly payments:PaymentService,private readonly ledger:LedgerService,private readonly rules:AccountingRuleEngine){}
  private get repo(){return this.ctx.repo;}
  async transactions(q:{bankAccountId?:string;status?:string;from?:string;to?:string},actor:FinanceActor){this.ctx.require(actor,"bank.view");return this.repo.list<BankTransaction>("bank_transactions",{bankAccountId:q.bankAccountId||undefined,reconciliationStatus:q.status?q.status.split(","):undefined,transactionDate:q.from||q.to?{gte:q.from||undefined,lte:q.to||undefined}:undefined},{order:"transactionDate"});}
  private async matchedByTarget(type:string){const matches=await this.repo.list<ReconciliationMatch>("reconciliation_matches",{targetType:type,status:"ACTIVE"});const totals=new Map<string,number>();for(const m of matches)totals.set(m.targetId,r2((totals.get(m.targetId)??0)+m.amount));return totals;}
  /** Candidatos con confianza y razones. Nunca concilia solo un caso ambiguo. */
  async suggestions(transactionId:string,actor:FinanceActor){
    this.ctx.require(actor,"bank.view");const tx=await this.ctx.must<BankTransaction>("bank_transactions",transactionId,"Movimiento");const settings=await this.repo.settings();const tolerance=Number(settings.reconciliationAmountTolerance)||0,days=Number(settings.reconciliationDateToleranceDays)||3;const open=r2(tx.amount-tx.reconciledAmount);const text=normalize(`${tx.description} ${tx.reference??""}`);const candidates:ReconciliationCandidate[]=[];
    const score=(amount:number,date:string|null,refs:Array<string|null|undefined>,names:Array<string|null|undefined>)=>{const reasons:string[]=[];let value=0;const diff=Math.abs(amount-open);if(diff===0){value+=0.5;reasons.push("Monto exacto");}else if(diff<=tolerance){value+=0.35;reasons.push(`Monto dentro de tolerancia (${money(diff)})`);}else return null;
      if(date){const gap=Math.abs(daysBetween(date,tx.transactionDate));if(gap<=days){value+=0.25*(1-gap/(days+1));reasons.push(gap===0?"Misma fecha":`Fecha a ${gap} día(s)`);}}
      if(refs.some((r)=>r&&normalize(r).length>=4&&text.includes(normalize(r)))){value+=0.2;reasons.push("Referencia coincide");}
      if(names.some((n)=>n&&normalize(n).split(" ").filter((w)=>w.length>3&&!genericWords.has(w)).some((w)=>text.split(" ").includes(w)))){value+=0.1;reasons.push("Nombre del cliente/proveedor en la glosa");}
      return{confidence:Math.min(0.99,r2(value)),reasons};};
    if(tx.direction==="CREDIT"){
      const matched=await this.matchedByTarget("PAYMENT");const payments=(await this.repo.list<Payment>("payments",{status:["PENDING_VERIFICATION","CONFIRMED","PARTIALLY_REFUNDED"],provider:{neq:"MERCADOPAGO"}})).filter((p)=>r2(p.grossAmount-(matched.get(p.id)??0))>0);const names=await this.ctx.sources.clientNames(payments.map((p)=>p.clientId));
      for(const p of payments){const remaining=r2(p.grossAmount-(matched.get(p.id)??0));const s=score(remaining,p.receivedAt.slice(0,10),[p.paymentReference,p.externalId],[names.get(p.clientId)]);if(s)candidates.push({targetType:"PAYMENT",targetId:p.id,label:`${p.paymentReference} · ${names.get(p.clientId)??"Cliente"} (${p.status==="PENDING_VERIFICATION"?"por verificar":"confirmado"})`,amount:remaining,date:p.receivedAt.slice(0,10),...s});}
      const payouts=await this.matchedByTarget("PROVIDER_PAYOUT");const settlements=(await this.repo.list<Payment>("payments",{provider:"MERCADOPAGO",status:["CONFIRMED","PARTIALLY_REFUNDED"],settlementStatus:"PENDING"})).filter((p)=>!payouts.has(p.id)&&p.moneyReleaseDate&&Math.abs(daysBetween(p.moneyReleaseDate,tx.transactionDate))<=days);
      const byDate=new Map<string,Payment[]>();for(const p of settlements){const list=byDate.get(p.moneyReleaseDate!)??[];list.push(p);byDate.set(p.moneyReleaseDate!,list);}
      for(const[date,group]of byDate){const net=sum(group.map((p)=>p.netAmount));const s=score(net,date,[],["mercado pago","mercadopago"]);if(s)candidates.push({targetType:"PROVIDER_PAYOUT",targetId:group.map((p)=>p.id).join(","),label:`Liquidación Mercado Pago ${date.split("-").reverse().join("-")} (${group.length} pagos)`,amount:net,date,confidence:s.confidence,reasons:[...s.reasons,"Suma de netos liberados"]});}
    }else{
      const vp=(await this.repo.list<VendorPayment>("vendor_payments",{status:"EXECUTED"}));const names=await this.ctx.withVendorNames(vp);for(const p of names){const s=score(p.amount,p.paymentDate,[p.paymentNumber,p.reference],[p.vendorName]);if(s)candidates.push({targetType:"VENDOR_PAYMENT",targetId:p.id,label:`${p.paymentNumber} · ${p.vendorName??"Proveedor"}`,amount:p.amount,date:p.paymentDate,...s});}
      const refunds=(await this.repo.list<Row>("payment_refunds",{status:"REFUNDED"}));const matchedRefunds=await this.matchedByTarget("REFUND");for(const r of refunds.filter((r)=>!matchedRefunds.has(r.id))){const s=score(r.amount,r.processedAt?.slice(0,10)??null,[],[]);if(s)candidates.push({targetType:"REFUND",targetId:r.id,label:`Devolución ${money(r.amount)}`,amount:r.amount,date:r.processedAt?.slice(0,10)??null,...s});}
      const commissions=(await this.repo.list<Row>("commission_payments",{status:"PAID"}));const matchedCommissions=await this.matchedByTarget("COMMISSION_PAYMENT");for(const c of commissions.filter((c)=>!matchedCommissions.has(c.id))){const s=score(c.amount,c.paidAt?.slice(0,10)??null,[c.paymentReference],[]);if(s)candidates.push({targetType:"COMMISSION_PAYMENT",targetId:c.id,label:`Pago de comisión ${c.paymentReference??""}`,amount:c.amount,date:c.paidAt?.slice(0,10)??null,...s});}
    }
    candidates.sort((a,b)=>b.confidence-a.confidence);const ambiguous=candidates.length>1&&candidates[0]!.confidence-candidates[1]!.confidence<0.1&&candidates[1]!.confidence>=0.5;return{bankTransaction:tx,candidates:candidates.slice(0,8),ambiguous};
  }
  async workspace(q:{bankAccountId?:string},actor:FinanceActor){const pending=await this.transactions({bankAccountId:q.bankAccountId,status:"UNRECONCILED,PARTIALLY_RECONCILED"},actor);const items=[];for(const tx of pending.slice(0,100))items.push(await this.suggestions(tx.id,actor));const reconciled=await this.repo.count("bank_transactions",{bankAccountId:q.bankAccountId||undefined,reconciliationStatus:"RECONCILED"});return{pending:pending.length,reconciled,items};}
  /** MATCH (1:1) o SPLIT (1 movimiento → varios destinos). */
  async match(transactionId:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"bank.reconcile");const tx=await this.ctx.must<BankTransaction>("bank_transactions",transactionId,"Movimiento");if(tx.reconciliationStatus==="IGNORED")throw new ConflictException("El movimiento está ignorado; deshaz la omisión primero.");const targets=Array.isArray(body.targets)?body.targets:[];if(!targets.length)throw new BadRequestException("Selecciona al menos un documento.");
    const expanded:Array<{targetType:string;targetId:string;amount:number}>=[];for(const t of targets){const type=oneOf(t.targetType,["PAYMENT","VENDOR_PAYMENT","JOURNAL_ENTRY","PROVIDER_PAYOUT","CASH_MOVEMENT","COMMISSION_PAYMENT","REFUND"] as const,"Destino");if(type==="PROVIDER_PAYOUT"){for(const id of String(t.targetId).split(",")){const p=await this.ctx.must<Payment>("payments",requiredUuid(id,"Pago"),"Pago");expanded.push({targetType:type,targetId:p.id,amount:p.netAmount});}}else expanded.push({targetType:type,targetId:requiredUuid(t.targetId,"Destino"),amount:positiveAmount(t.amount,"Monto")});}
    const total=sum(expanded.map((t)=>t.amount));if(total>r2(tx.amount-tx.reconciledAmount))throw new UnprocessableEntityException(`Concilias ${money(total)} y el movimiento tiene ${money(r2(tx.amount-tx.reconciledAmount))} disponible.`);
    for(const t of expanded)await this.validateTarget(tx,t.targetType,t.targetId,t.amount);
    const group=randomUUID();const kind=expanded.length>1?"SPLIT":"MATCH";for(const t of expanded)await guarded(()=>this.repo.create("reconciliation_matches",{bankTransactionId:transactionId,...t,matchGroup:group,matchKind:kind,confidence:body.confidence??null,status:"ACTIVE",createdBy:actor.userId}));await this.repo.afterMatchChange(transactionId);
    await this.sideEffects(tx,expanded,actor);await this.repo.audit(actor,"BANK_MATCHED","BANK_TRANSACTION",transactionId,`${kind}: ${money(total)} conciliado con ${expanded.length} documento(s)`,{group,targets:expanded});return this.ctx.must("bank_transactions",transactionId,"Movimiento");
  }
  /** MERGE: varios movimientos → un destino. */
  async merge(body:Row,actor:FinanceActor){this.ctx.require(actor,"bank.reconcile");const ids=(Array.isArray(body.transactionIds)?body.transactionIds:[]).map((id:unknown)=>requiredUuid(id,"Movimiento"));if(ids.length<2)throw new BadRequestException("Selecciona al menos dos movimientos.");const target=body.target??{};const type=oneOf(target.targetType,["PAYMENT","VENDOR_PAYMENT","JOURNAL_ENTRY","CASH_MOVEMENT","COMMISSION_PAYMENT","REFUND"] as const,"Destino");const targetId=requiredUuid(target.targetId,"Destino");const txs=await Promise.all(ids.map((id:string)=>this.ctx.must<BankTransaction>("bank_transactions",id,"Movimiento")));if(new Set(txs.map((t)=>t.direction)).size>1)throw new UnprocessableEntityException("Los movimientos deben tener el mismo sentido.");const total=sum(txs.map((t)=>r2(t.amount-t.reconciledAmount)));await this.validateTarget(txs[0]!,type,targetId,total);const group=randomUUID();
    for(const tx of txs){await guarded(()=>this.repo.create("reconciliation_matches",{bankTransactionId:tx.id,targetType:type,targetId,amount:r2(tx.amount-tx.reconciledAmount),matchGroup:group,matchKind:"MERGE",confidence:null,status:"ACTIVE",createdBy:actor.userId}));await this.repo.afterMatchChange(tx.id);}await this.sideEffects(txs[0]!,[{targetType:type,targetId,amount:total}],actor);await this.repo.audit(actor,"BANK_MERGED","BANK_TRANSACTION",txs[0]!.id,`MERGE de ${txs.length} movimientos (${money(total)})`,{group,ids});return{group,total};}
  private async validateTarget(tx:BankTransaction,type:string,id:string,amount:number){
    const matched=(await this.matchedByTarget(type)).get(id)??0;
    if(type==="PAYMENT"){if(tx.direction!=="CREDIT")throw new UnprocessableEntityException("Un cobro se concilia con un abono.");const p=await this.ctx.must<Payment>("payments",id,"Pago");if(amount>r2(p.grossAmount-matched))throw new UnprocessableEntityException("El monto excede lo pendiente de conciliar del pago.");return;}
    if(type==="PROVIDER_PAYOUT"){if(tx.direction!=="CREDIT")throw new UnprocessableEntityException("Una liquidación es un abono.");return;}
    if(type==="VENDOR_PAYMENT"){if(tx.direction!=="DEBIT")throw new UnprocessableEntityException("Un pago a proveedor es un cargo.");const p=await this.ctx.must<VendorPayment>("vendor_payments",id,"Pago a proveedor");if(!["EXECUTED","RECONCILED"].includes(p.status))throw new ConflictException("El pago a proveedor no está registrado como ejecutado.");if(amount>r2(p.amount-matched))throw new UnprocessableEntityException("Monto excede el pago.");return;}
    if(type==="JOURNAL_ENTRY"){const entry=await this.ctx.must<Row>("journal_entries",id,"Asiento");if(!["POSTED","DRAFT","PENDING_REVIEW"].includes(entry.status))throw new ConflictException("Asiento revertido.");return;}
    if(type==="REFUND"||type==="COMMISSION_PAYMENT"){if(tx.direction!=="DEBIT")throw new UnprocessableEntityException("Debe ser un cargo.");await this.ctx.must(type==="REFUND"?"payment_refunds":"commission_payments",id,"Documento");return;}
    if(type==="CASH_MOVEMENT")await this.ctx.must("cash_movements",id,"Movimiento de caja");
  }
  private async sideEffects(tx:BankTransaction,targets:Array<{targetType:string;targetId:string;amount:number}>,actor:FinanceActor){
    for(const t of targets){
      if(t.targetType==="PAYMENT"){const p=(await this.repo.get<Payment>("payments",t.targetId))!;if(p.status==="PENDING_VERIFICATION")await this.payments.confirm(p.id,{bankTransactionId:tx.id},actor);else if(!p.bankTransactionId)await this.repo.update("payments",p.id,{bankTransactionId:tx.id});}
      if(t.targetType==="VENDOR_PAYMENT")await this.repo.update("vendor_payments",t.targetId,{status:"RECONCILED",bankTransactionId:tx.id});
      if(t.targetType==="CASH_MOVEMENT")await this.repo.update("cash_movements",t.targetId,{status:"RECONCILED"});
    }
    const payouts=targets.filter((t)=>t.targetType==="PROVIDER_PAYOUT");if(payouts.length){for(const t of payouts)await this.repo.update("payments",t.targetId,{settlementStatus:"SETTLED"});const account=(await this.repo.get<BankAccount>("bank_accounts",tx.bankAccountId))!;await this.rules.record({eventType:"PROVIDER_PAYOUT",sourceType:"BANK_TRANSACTION",sourceId:tx.id,idempotencyKey:`payout:${tx.id}`,amounts:{AMOUNT:sum(payouts.map((p)=>p.amount))},context:{cashLedgerAccountId:account.ledgerAccountId},occurredOn:tx.transactionDate},actor);}
  }
  async ignore(transactionId:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"bank.reconcile");const reason=requiredText(body.reason,"Motivo para ignorar",300);const tx=await this.ctx.must<BankTransaction>("bank_transactions",transactionId,"Movimiento");if(tx.reconciledAmount>0)throw new ConflictException("El movimiento tiene conciliaciones activas.");await this.repo.update("bank_transactions",transactionId,{reconciliationStatus:"IGNORED",ignoredReason:reason,ignoredBy:actor.userId});await this.repo.audit(actor,"BANK_IGNORED","BANK_TRANSACTION",transactionId,`Movimiento ignorado: ${reason}`);return this.ctx.must("bank_transactions",transactionId,"Movimiento");}
  async unignore(transactionId:string,actor:FinanceActor){this.ctx.require(actor,"bank.reconcile");await this.repo.update("bank_transactions",transactionId,{reconciliationStatus:"UNRECONCILED",ignoredReason:null,ignoredBy:null});await this.repo.audit(actor,"BANK_UNIGNORED","BANK_TRANSACTION",transactionId,"Omisión deshecha");return this.ctx.must("bank_transactions",transactionId,"Movimiento");}
  /** CREATE TRANSACTION: comisiones bancarias, intereses u otros sin documento → borrador de asiento revisable; o cobro de cliente desde el abono. */
  async createFromTransaction(transactionId:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"bank.reconcile");const tx=await this.ctx.must<BankTransaction>("bank_transactions",transactionId,"Movimiento");const open=r2(tx.amount-tx.reconciledAmount);if(open<=0)throw new ConflictException("El movimiento ya está conciliado.");
    if(body.kind==="PAYMENT"){if(tx.direction!=="CREDIT")throw new UnprocessableEntityException("Sólo un abono genera un cobro.");const payment=await this.payments.record({clientId:body.clientId,provider:"BANK_TRANSFER",method:"TRANSFER",grossAmount:open,receivedAt:tx.transactionDate,bankAccountId:tx.bankAccountId,bankTransactionId:tx.id,notes:`Desde cartola: ${tx.description}`},actor);return this.match(transactionId,{targets:[{targetType:"PAYMENT",targetId:payment.id,amount:open}]},actor);}
    const account=(await this.repo.get<BankAccount>("bank_accounts",tx.bankAccountId))!;const counterpart=requiredUuid(body.accountId,"Cuenta contrapartida");const description=requiredText(body.description,"Glosa",300);
    const entry=await this.ledger.createEntry({entryDate:tx.transactionDate,description,lines:tx.direction==="DEBIT"?[{accountId:counterpart,debit:open,description},{accountId:account.ledgerAccountId,credit:open,description}]:[{accountId:account.ledgerAccountId,debit:open,description},{accountId:counterpart,credit:open,description}],submit:true},actor,{sourceType:"RECONCILIATION",sourceId:tx.id});
    await guarded(()=>this.repo.create("reconciliation_matches",{bankTransactionId:tx.id,targetType:"JOURNAL_ENTRY",targetId:entry.id,amount:open,matchKind:"CREATED",confidence:null,status:"ACTIVE",createdBy:actor.userId}));await this.repo.afterMatchChange(tx.id);await this.repo.audit(actor,"BANK_CREATED_ENTRY","BANK_TRANSACTION",tx.id,`Borrador de asiento creado desde cartola (${money(open)})`,{entryId:entry.id});return{transaction:await this.ctx.must("bank_transactions",tx.id,"Movimiento"),entry};
  }
  async undo(matchId:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"bank.reconcile");const reason=requiredText(body.reason,"Motivo",300);const match=await this.ctx.must<ReconciliationMatch>("reconciliation_matches",matchId,"Conciliación");if(match.status!=="ACTIVE")throw new ConflictException("La conciliación ya fue deshecha.");const group=await this.repo.list<ReconciliationMatch>("reconciliation_matches",{matchGroup:match.matchGroup,status:"ACTIVE"});
    for(const m of group){await this.repo.update("reconciliation_matches",m.id,{status:"UNDONE",undoneBy:actor.userId,undoneAt:nowIso(),undoReason:reason});await this.repo.afterMatchChange(m.bankTransactionId);if(m.targetType==="VENDOR_PAYMENT")await this.repo.update("vendor_payments",m.targetId,{status:"EXECUTED",bankTransactionId:null});if(m.targetType==="PROVIDER_PAYOUT")await this.repo.update("payments",m.targetId,{settlementStatus:"PENDING"});}
    await this.repo.audit(actor,"BANK_MATCH_UNDONE","BANK_TRANSACTION",match.bankTransactionId,`Conciliación deshecha: ${reason}`,{group:match.matchGroup,note:"Los pagos confirmados con este movimiento permanecen confirmados; revisa su evidencia."});return{undone:group.length};}
  matches(transactionId:string,actor:FinanceActor){this.ctx.require(actor,"bank.view");return this.repo.list<ReconciliationMatch>("reconciliation_matches",{bankTransactionId:transactionId},{order:"createdAt"});}
  /** Auto-conciliación opcional (apagada por defecto): sólo coincidencias exactas, no ambiguas y de alta confianza. */
  async autoMatch(actor:FinanceActor){const settings=await this.repo.settings();if(!settings.autoMatchEnabled)return{enabled:false,matched:0};let matched=0;for(const tx of await this.repo.list<BankTransaction>("bank_transactions",{reconciliationStatus:"UNRECONCILED"})){const s=await this.suggestions(tx.id,actor);const top=s.candidates[0];if(!top||s.ambiguous||top.confidence<0.95||top.amount!==tx.amount||top.targetType==="PROVIDER_PAYOUT")continue;await this.match(tx.id,{targets:[{targetType:top.targetType,targetId:top.targetId,amount:top.amount}],confidence:top.confidence},actor);matched++;}return{enabled:true,matched};}
}
