import { BadRequestException, ForbiddenException, Injectable, OnModuleDestroy, OnModuleInit } from "@nestjs/common";
import type { AccountingHealth, Anomaly, BillingSchedule, CashflowPoint, CashflowReport, ClientFinanceSummary, CopilotAnswer, FinanceDashboard, FinanceKpi, FinanceMetric, Invoice, JournalEntry, JournalLine, Payable, Payment, PaymentAllocation, PaymentPromise, ProfitabilityRow, ProjectFinanceSummary } from "@zyteron/contracts";
import { can, canSeeMargins } from "./finance.access.js";
import { BillingScheduleService, InvoiceService, monthlyEquivalent, nextDate, withEffective } from "./finance.billing.js";
import { BudgetService, CloseService, TaxService } from "./finance.close.js";
import { FinanceContext } from "./finance.core.js";
import { DteService } from "./finance.dte.js";
import { renderPdfReport, writeCsv, writeXlsx } from "./finance.formats.js";
import { LedgerService, StatementsService } from "./finance.ledger.js";
import { withPayableStatus, PayableService } from "./finance.payables.js";
import { CollectionsService, systemActor } from "./finance.payments.js";
import { ReconciliationService } from "./finance.banking.js";
import { QuotePaymentService } from "./finance.quote-payments.js";
import { addDays, addMonths, daysBetween, displayDate, displayDateTime, type FinanceActor, isoDate, money, monthRange, nowIso, previousPeriod, r2, type Row, sum, todayCl } from "./finance.util.js";

const severityWeight:Record<Anomaly["severity"],number>={INFO:0,ATTENTION:5,RISK:12,CRITICAL:25};
const periodLabel=(from:string,to:string)=>`${displayDate(from)} al ${displayDate(to)}`;

// =========================================================================================== Analítica: KPIs, métricas, flujo de caja, rentabilidad y anomalías
@Injectable()
export class AnalyticsService {
  constructor(private readonly ctx:FinanceContext,private readonly statements:StatementsService,private readonly collections:CollectionsService,private readonly payables:PayableService,private readonly invoices:InvoiceService,private readonly dte:DteService){}
  private get repo(){return this.ctx.repo;}
  private async cashAccounts():Promise<CashflowReport["cashAccounts"]>{const accounts=(await this.ctx.accounts()).filter((a)=>a.isCash&&a.allowsPosting);const balances=new Map((await this.repo.accountBalances("1900-01-01",todayCl())).map((b)=>[b.accountId,r2(b.opening+b.debit-b.credit)]));const banks=await this.repo.list<Row>("bank_accounts",{});const cash=await this.repo.list<Row>("cash_accounts",{});
    return accounts.map((a)=>{const bank=banks.find((b)=>b.ledgerAccountId===a.id);const box=cash.find((c)=>c.ledgerAccountId===a.id);return{id:a.id,name:bank?`${bank.bankName} ····${bank.accountNumberLast4}`:box?box.name:`${a.code} ${a.name}`,balance:balances.get(a.id)??0,kind:bank?"BANK" as const:box?"CASH" as const:"LEDGER" as const};}).filter((a)=>a.balance!==0||a.kind!=="LEDGER");}

  /** Anomalías determinísticas con monto, conteo y enlace al detalle (sin IA, sin estimaciones). */
  async anomalies():Promise<Anomaly[]>{
    const today=todayCl();const out:Anomaly[]=[];const push=(a:Anomaly)=>{if(a.count>0)out.push(a);};
    const open=(await this.repo.list<Invoice>("invoices",{status:["ISSUED","PARTIALLY_PAID"],documentTypeCode:{neq:61}})).map((i)=>withEffective(i,today)).filter((i)=>i.effectiveStatus==="OVERDUE");const oldest=Math.max(0,...open.map((i)=>i.daysOverdue??0));
    push({key:"OVERDUE_AR",severity:oldest>90?"CRITICAL":oldest>60?"RISK":"ATTENTION",title:"Cuentas por cobrar vencidas",detail:`${open.length} documentos vencidos; el más antiguo con ${oldest} días.`,count:open.length,amount:sum(open.map((i)=>i.balanceDue)),drillDown:"/finance/collections"});
    const rejected=await this.repo.list<Row>("tax_documents",{status:"REJECTED",rejectedAt:{gte:addDays(today,-30)}});const reissued=new Set((await this.repo.list<Row>("tax_documents",{invoiceId:rejected.map((d)=>d.invoiceId),status:{notIn:["REJECTED","CANCELLED"]}})).map((d)=>d.invoiceId));const pendingReissue=rejected.filter((d)=>!reissued.has(d.invoiceId));
    push({key:"DTE_REJECTED",severity:"CRITICAL",title:"DTE rechazados sin reemisión",detail:"Documentos rechazados por el SII en los últimos 30 días que siguen sin emitirse.",count:pendingReissue.length,amount:sum(pendingReissue.map((d)=>Number(d.totalAmount)||0)),drillDown:"/finance/tax-documents?status=REJECTED"});
    const stale=await this.repo.list<Row>("tax_documents",{status:["SUBMITTED","RECEIVED_BY_SII"],submittedAt:{lt:new Date(Date.now()-2*86400000).toISOString()}});push({key:"DTE_STALE",severity:"ATTENTION",title:"DTE sin respuesta del SII",detail:"Enviados hace más de 2 días sin estado final.",count:stale.length,amount:null,drillDown:"/finance/tax-documents?status=SUBMITTED"});
    const drafts=await this.repo.list<JournalEntry>("journal_entries",{status:["DRAFT","PENDING_REVIEW"],createdAt:{lt:new Date(Date.now()-7*86400000).toISOString()}});push({key:"STALE_DRAFTS",severity:"ATTENTION",title:"Asientos pendientes hace más de 7 días",detail:"Borradores o asientos en revisión sin contabilizar.",count:drafts.length,amount:null,drillDown:"/finance/journal?status=PENDING_REVIEW"});
    const unmapped=await this.repo.count("accounting_events",{status:["UNMAPPED","ERROR"]});push({key:"UNMAPPED_EVENTS",severity:unmapped>10?"RISK":"ATTENTION",title:"Hechos económicos sin asiento",detail:"Eventos sin regla activa o con error de regla.",count:unmapped,amount:null,drillDown:"/finance/accounting?tab=events"});
    const bank=await this.repo.list<Row>("bank_transactions",{reconciliationStatus:["UNRECONCILED","PARTIALLY_RECONCILED"],transactionDate:{lt:addDays(today,-15)}});push({key:"BANK_STALE",severity:"RISK",title:"Movimientos bancarios sin conciliar (> 15 días)",detail:"Conciliación atrasada.",count:bank.length,amount:sum(bank.map((t)=>r2(t.amount-t.reconciledAmount))),drillDown:"/finance/reconciliation"});
    const received=await this.repo.list<Row>("received_tax_documents",{taxCreditClassification:"PENDING_REVIEW"});push({key:"RECEIVED_UNCLASSIFIED",severity:"ATTENTION",title:"Compras sin clasificar crédito fiscal",detail:"El IVA no se considera recuperable hasta clasificarlo.",count:received.length,amount:sum(received.map((d)=>d.taxAmount)),drillDown:"/finance/tax-documents?tab=received&classification=PENDING_REVIEW"});
    const unapplied=(await this.repo.list<Payment>("payments",{status:["CONFIRMED","PARTIALLY_REFUNDED"],unappliedAmount:{gt:0}})).filter((p)=>p.receivedAt<new Date(Date.now()-7*86400000).toISOString());push({key:"UNAPPLIED_PAYMENTS",severity:"ATTENTION",title:"Pagos sin aplicar (> 7 días)",detail:"Saldos a favor de clientes o cobros sin factura asociada.",count:unapplied.length,amount:sum(unapplied.map((p)=>p.unappliedAmount)),drillDown:"/finance/payments?unapplied=true"});
    const verifying=(await this.repo.list<Payment>("payments",{status:"PENDING_VERIFICATION"})).filter((p)=>p.createdAt<new Date(Date.now()-3*86400000).toISOString());push({key:"PAYMENTS_UNVERIFIED",severity:"RISK",title:"Pagos sin verificar (> 3 días)",detail:"Registrados con comprobante pero sin verificación.",count:verifying.length,amount:sum(verifying.map((p)=>p.grossAmount)),drillDown:"/finance/payments?status=PENDING_VERIFICATION"});
    const ap=(await this.repo.list<Payable>("payables",{status:["APPROVED","SCHEDULED","PARTIALLY_PAID"],dueDate:{lt:today}})).filter((p)=>p.balance>0);push({key:"AP_OVERDUE",severity:"RISK",title:"Cuentas por pagar vencidas",detail:"Obligaciones con proveedores vencidas.",count:ap.length,amount:sum(ap.map((p)=>p.balance)),drillDown:"/finance/payables?overdue=true"});
    const expenses=(await this.repo.list<Row>("expenses",{status:"PENDING_APPROVAL"})).filter((e)=>e.updatedAt<new Date(Date.now()-7*86400000).toISOString());push({key:"EXPENSES_WAITING",severity:"ATTENTION",title:"Gastos esperando aprobación (> 7 días)",detail:"Flujo de aprobación detenido.",count:expenses.length,amount:sum(expenses.map((e)=>e.totalAmount)),drillDown:"/finance/expenses?status=PENDING_APPROVAL"});
    const certs=(await this.repo.list<Row>("dte_certificates",{status:"ACTIVE"})).filter((c)=>daysBetween(today,String(c.expiresAt).slice(0,10))<=30);push({key:"CERTIFICATE_EXPIRING",severity:certs.some((c)=>daysBetween(today,String(c.expiresAt).slice(0,10))<=7)?"CRITICAL":"RISK",title:"Certificado digital por vencer",detail:"La emisión directa se bloquea al vencer.",count:certs.length,amount:null,drillDown:"/finance/settings"});
    for(const a of await this.repo.list<Row>("tax_folio_authorizations",{status:"ACTIVE"})){const available=await this.repo.count("tax_folios",{authorizationId:a.id,status:"AVAILABLE"});const total=a.rangeTo-a.rangeFrom+1;if(available<=Math.max(5,Math.ceil(total*0.1)))push({key:`FOLIOS_LOW_${a.documentTypeCode}_${a.environment}`,severity:available===0?"CRITICAL":"RISK",title:`Folios por agotarse (tipo ${a.documentTypeCode}, ${a.environment==="PRODUCTION"?"producción":"certificación"})`,detail:`${available} de ${total} disponibles; solicita un nuevo CAF.`,count:1,amount:null,drillDown:"/finance/settings"});}
    if(Number(today.slice(8,10))>15){const prev=await this.repo.findOne<Row>("accounting_periods",{periodKey:previousPeriod(today.slice(0,7))});if(prev&&["OPEN","CLOSING"].includes(prev.status))push({key:"PERIOD_NOT_CLOSED",severity:"ATTENTION",title:`Período ${prev.periodKey} sin cerrar`,detail:"El mes anterior sigue abierto después del día 15.",count:1,amount:null,drillDown:`/finance/closing?period=${prev.periodKey}`});}
    const tb=await this.statements.trialBalance(`${today.slice(0,4)}-01-01`,today);if(!tb.balanced)push({key:"TRIAL_BALANCE",severity:"CRITICAL",title:"Balance de comprobación descuadrado",detail:`Debe ${money(tb.totals.debit)} vs Haber ${money(tb.totals.credit)}.`,count:1,amount:r2(tb.totals.debit-tb.totals.credit),drillDown:"/finance/reports?type=TRIAL_BALANCE"});
    const concentration=(await this.metrics()).find((m)=>m.key==="CLIENT_CONCENTRATION");const threshold=Number((await this.repo.settings()).clientConcentrationThreshold);if(concentration?.value!==null&&concentration?.value!==undefined&&concentration.value>=threshold)push({key:"CLIENT_CONCENTRATION",severity:"ATTENTION",title:"Concentración de ingresos en un cliente",detail:`El principal cliente explica ${concentration.value}% de lo facturado en 12 meses (umbral ${threshold}%).`,count:1,amount:null,drillDown:"/finance/reports?type=SALES"});
    return out.sort((a,b)=>severityWeight[b.severity]-severityWeight[a.severity]);
  }
  async health(anomalies?:Anomaly[]):Promise<AccountingHealth>{const factors=anomalies??await this.anomalies();const score=Math.max(0,100-sum(factors.map((f)=>severityWeight[f.severity])));const worst=factors[0]?.severity;const status=worst==="CRITICAL"?"CRITICAL":worst==="RISK"||score<70?"RISK":worst==="ATTENTION"?"ATTENTION":"GREEN";return{status,score,factors,explanation:factors.length?`${factors.length} factores: ${factors.slice(0,3).map((f)=>f.title.toLowerCase()).join("; ")}.`:"Sin anomalías detectadas por los controles determinísticos.",generatedAt:nowIso()};}

  /** Métricas con definición explícita. MRR/ARR sólo de ingresos recurrentes programados. */
  async metrics():Promise<FinanceMetric[]>{
    const today=todayCl();const schedules=await this.repo.list<BillingSchedule>("billing_schedules",{active:true});const mrr=sum(schedules.map((s)=>monthlyEquivalent(s.amount,s.frequency,s.intervalDays)));
    const issued=await this.repo.list<Invoice>("invoices",{issueDate:{gte:addDays(today,-365)},status:["ISSUED","PARTIALLY_PAID","PAID","CREDITED"]});const signed=(i:Invoice)=>i.documentTypeCode===61?-1:1;
    const last90=issued.filter((i)=>i.issueDate!>=addDays(today,-90));const sales90=sum(last90.map((i)=>signed(i)*i.totalAmount));const firstIssue=issued.map((i)=>i.issueDate!).sort()[0];const enoughHistory=Boolean(firstIssue&&daysBetween(firstIssue,today)>=90);
    const ar=sum((await this.repo.list<Invoice>("invoices",{status:["ISSUED","PARTIALLY_PAID"],documentTypeCode:{neq:61}})).map((i)=>i.balanceDue));
    const byClient=new Map<string,number>();for(const i of issued)byClient.set(i.clientId,r2((byClient.get(i.clientId)??0)+signed(i)*(i.netAmount+i.exemptAmount)));const totalNet=sum([...byClient.values()]);const top=Math.max(0,...byClient.values());
    return[
      {key:"MRR",label:"MRR",value:schedules.length?mrr:null,unit:"CLP",definition:"Suma mensualizada (neto) de programaciones de facturación recurrente activas. No incluye proyectos ni ventas únicas.",insufficientData:!schedules.length,drillDown:"/finance/invoices?tab=recurring"},
      {key:"ARR",label:"ARR",value:schedules.length?r2(mrr*12):null,unit:"CLP",definition:"MRR × 12. Proyección de ingresos recurrentes vigentes, no ingresos contabilizados.",insufficientData:!schedules.length,drillDown:"/finance/invoices?tab=recurring"},
      {key:"DSO",label:"DSO",value:enoughHistory&&sales90>0?Math.round(ar/sales90*90):null,unit:"DAYS",definition:"DSO = (Cuentas por cobrar abiertas ÷ ventas documentadas con IVA de los últimos 90 días) × 90.",insufficientData:!(enoughHistory&&sales90>0),drillDown:"/finance/receivables"},
      {key:"CLIENT_CONCENTRATION",label:"Concentración principal cliente",value:totalNet>0?r2(top/totalNet*100):null,unit:"PERCENT",definition:"Participación del cliente con mayor venta neta documentada en los últimos 12 meses.",insufficientData:totalNet<=0,drillDown:"/finance/reports?type=SALES"},
      {key:"AR_TOTAL",label:"Cuentas por cobrar",value:ar,unit:"CLP",definition:"Saldo pendiente de documentos emitidos (facturas y notas de débito).",insufficientData:false,drillDown:"/finance/receivables"},
    ];
  }
  async dashboard(actor:FinanceActor,periodKey=todayCl().slice(0,7)):Promise<FinanceDashboard>{
    this.ctx.require(actor,"finance.dashboard.view");const{from,to}=monthRange(periodKey);const today=todayCl();const ledgerVisible=can(actor.role,"accounting.view");
    const[income,aging,apAging,cashAccounts,anomalies,pending]=await Promise.all([ledgerVisible?this.statements.incomeStatement(from,to):null,this.collections.aging(actor),can(actor.role,"payable.view")?this.payables.aging(actor):null,ledgerVisible?this.cashAccounts():[],this.anomalies(),this.invoices.pendingToInvoice(actor)]);
    const issued=await this.repo.list<Invoice>("invoices",{issueDate:{gte:from,lte:to},status:["ISSUED","PARTIALLY_PAID","PAID","CREDITED"]});const invoiced=sum(issued.map((i)=>(i.documentTypeCode===61?-1:1)*i.totalAmount));
    const payments=await this.repo.list<Payment>("payments",{status:["CONFIRMED","PARTIALLY_REFUNDED","REFUNDED"],receivedAt:{gte:`${from}T00:00:00-04:00`,lte:`${to}T23:59:59-03:00`}});const collected=sum(payments.map((p)=>p.grossAmount-p.refundedAmount));
    const overdue=sum(aging.buckets.filter((b)=>b.key!=="CURRENT").map((b)=>b.amount));const cash=sum(cashAccounts.map((a)=>a.balance));
    const kpis:FinanceKpi[]=[
      {key:"INVOICED",label:"Facturado en el período",value:invoiced,currency:"CLP",definition:"Documentos tributarios emitidos con IVA (notas de crédito restan). Es facturación, no ingreso contable ni caja.",href:`/finance/invoices?from=${from}&to=${to}`,tone:"NEUTRAL"},
      {key:"COLLECTED",label:"Cobrado en el período",value:collected,currency:"CLP",definition:"Pagos de clientes confirmados con evidencia, menos devoluciones. Es caja, no ingreso.",href:"/finance/payments",tone:"GOOD"},
      {key:"AR",label:"Por cobrar",value:aging.total,currency:"CLP",definition:"Saldo de documentos emitidos pendientes.",href:"/finance/receivables",tone:"NEUTRAL"},
      {key:"AR_OVERDUE",label:"Vencido",value:overdue,currency:"CLP",definition:"Saldos con fecha de vencimiento anterior a hoy.",href:"/finance/collections",tone:overdue>0?"WARNING":"GOOD"},
      ...(apAging?[{key:"AP",label:"Por pagar",value:apAging.total,currency:"CLP",definition:"Obligaciones con proveedores abiertas.",href:"/finance/payables",tone:"NEUTRAL" as const}]:[]),
      ...(income?[{key:"REVENUE",label:"Ingresos contabilizados",value:income.revenue,currency:"CLP",definition:"Ingresos de explotación del libro mayor (asientos contabilizados del período).",href:`/finance/reports?type=INCOME_STATEMENT&from=${from}&to=${to}`,tone:"NEUTRAL" as const},{key:"NET_RESULT",label:"Resultado contable",value:income.netResult,currency:"CLP",definition:"Resultado del estado de resultados del período desde el libro mayor.",href:`/finance/reports?type=INCOME_STATEMENT&from=${from}&to=${to}`,tone:income.netResult<0?"CRITICAL" as const:"GOOD" as const},{key:"CASH",label:"Caja y bancos (libro)",value:cash,currency:"CLP",definition:"Saldo contable de cuentas de disponible a hoy.",href:"/finance/banks",tone:"NEUTRAL" as const}]:[]),
    ];
    const dueSoon=(await this.collections.openInvoices(actor)).filter((i)=>i.dueDate&&i.dueDate>=today&&daysBetween(today,i.dueDate)<=7);const payablesDue=apAging?(await this.repo.list<Payable>("payables",{status:["APPROVED","SCHEDULED","PARTIALLY_PAID"],dueDate:{lte:addDays(today,7)}})).map((p)=>withPayableStatus(p,today)):[];
    const history=ledgerVisible?await this.cashHistory(6):[];
    return{period:{from,to,periodKey},kpis,health:await this.health(anomalies),cash:{position:cash,accounts:cashAccounts},aging,apAging:apAging??{asOf:today,total:0,buckets:[],byParty:[]},dueSoon,payablesDue:await this.ctx.withVendorNames(payablesDue),pendingToInvoice:pending,revenueTrend:history,actions:anomalies.slice(0,6),dteReadiness:await this.dte.readiness(),generatedAt:nowIso()};
  }
  /** Flujo REAL: movimientos de cuentas de disponible en el libro (excluye traspasos entre ellas). */
  async cashHistory(months:number):Promise<CashflowPoint[]>{
    const today=todayCl();const start=`${addMonths(`${today.slice(0,7)}-01`,-(months-1)).slice(0,7)}-01`;const cash=new Set((await this.ctx.accounts()).filter((a)=>a.isCash).map((a)=>a.id));const entries=await this.repo.list<JournalEntry>("journal_entries",{status:["POSTED","REVERSED"],entryDate:{gte:start,lte:today}});const byId=new Map(entries.map((e)=>[e.id,e]));
    const lines=entries.length?(await this.repo.list<JournalLine>("journal_entry_lines",{journalEntryId:entries.map((e)=>e.id)})):[];const perEntry=new Map<string,JournalLine[]>();for(const l of lines){const list=perEntry.get(l.journalEntryId)??[];list.push(l);perEntry.set(l.journalEntryId,list);}
    const points=new Map<string,CashflowPoint>();for(let i=0;i<months;i++){const key=addMonths(start,i).slice(0,7);points.set(key,{periodKey:key,inflows:0,outflows:0,net:0,kind:"REAL"});}
    for(const[entryId,list]of perEntry){if(list.every((l)=>cash.has(l.accountId)))continue;const point=points.get(byId.get(entryId)!.entryDate.slice(0,7));if(!point)continue;for(const l of list.filter((x)=>cash.has(x.accountId))){point.inflows=r2(point.inflows+l.debit);point.outflows=r2(point.outflows+l.credit);}}
    return[...points.values()].map((p)=>({...p,net:r2(p.inflows-p.outflows)}));
  }
  async cashflow(actor:FinanceActor,scenarioCode="BASE",months=6):Promise<CashflowReport>{
    this.ctx.require(actor,"report.finance.view");const scenario=await this.repo.findOne<Row>("forecast_scenarios",{code:scenarioCode,active:true})??await this.repo.findOne<Row>("forecast_scenarios",{code:"BASE"});const factors=scenario!.collectionFactors as Record<string,number>;const today=todayCl();const horizon=Math.max(1,Math.min(12,months));
    const points=new Map<string,CashflowPoint>();for(let i=0;i<horizon;i++){const key=addMonths(`${today.slice(0,7)}-01`,i).slice(0,7);points.set(key,{periodKey:key,inflows:0,outflows:0,net:0,kind:"PROJECTION"});}const at=(date:string)=>points.get((date<today?today:date).slice(0,7));
    const open=(await this.repo.list<Invoice>("invoices",{status:["ISSUED","PARTIALLY_PAID"],documentTypeCode:{neq:61}})).filter((i)=>i.balanceDue>0);for(const i of open){const days=daysBetween(i.dueDate??today,today);const bucket=days<=0?"CURRENT":days<=30?"D1_30":days<=60?"D31_60":days<=90?"D61_90":"D90_PLUS";const point=at(i.dueDate??today);if(point)point.inflows=r2(point.inflows+i.balanceDue*(factors[bucket]??1));}
    const iva=await this.ctx.optionalTaxRate("IVA");for(const s of await this.repo.list<BillingSchedule>("billing_schedules",{active:true})){let date=s.nextBillingDate;let guard=0;while(guard++<60){const point=points.get(addDays(date,s.paymentTermsDays??30).slice(0,7));if(!point&&addDays(date,s.paymentTermsDays??30)>[...points.keys()].at(-1)!+"-31")break;if(point)point.inflows=r2(point.inflows+s.amount*(s.isExempt?1:1+(iva?.rate??0))*Number(scenario!.recurringFactor));if(s.endDate&&date>=s.endDate)break;date=nextDate(date,s.frequency,s.intervalDays);}}
    for(const p of (await this.repo.list<Payable>("payables",{status:["PENDING_REVIEW","APPROVED","SCHEDULED","PARTIALLY_PAID"]})).filter((p)=>p.balance>0)){const point=at(p.scheduledFor??p.dueDate);if(point)point.outflows=r2(point.outflows+p.balance*Number(scenario!.expenseFactor));}
    for(const c of await this.repo.list<Row>("scheduled_costs",{active:true})){let date=c.nextDate as string;let guard=0;while(guard++<60){const point=points.get(date.slice(0,7));if(point)point.outflows=r2(point.outflows+c.amount*Number(scenario!.expenseFactor));if(c.frequency==="ONE_TIME"||date>[...points.keys()].at(-1)!+"-31"||(c.endDate&&date>=c.endDate))break;date=addMonths(date,c.frequency==="MONTHLY"?1:c.frequency==="QUARTERLY"?3:12);}}
    const cashAccounts=await this.cashAccounts();return{cashPosition:sum(cashAccounts.map((a)=>a.balance)),cashAccounts,history:await this.cashHistory(6),projection:[...points.values()].map((p)=>({...p,net:r2(p.inflows-p.outflows)})),scenario:scenario!.name,assumptions:[`PROYECCIÓN escenario ${scenario!.name}: ${scenario!.description}`,"Cobros: saldos abiertos en su mes de vencimiento (vencidos se proyectan en el mes actual) ponderados por antigüedad.","Recurrentes: programaciones activas con IVA vigente según su plazo de pago.","Pagos: cuentas por pagar abiertas en su vencimiento o fecha programada y costos programados.","No incluye impuestos por pagar, remuneraciones ni ventas no documentadas salvo que estén registradas."]};
  }
  /** Rentabilidad desde el libro (dimensiones cliente/proyecto) + costo laboral sólo con tarifa configurada. */
  async profitability(actor:FinanceActor,dimension:"CLIENT"|"PROJECT",from:string,to:string,onlyId?:string):Promise<ProfitabilityRow[]>{
    if(!canSeeMargins(actor))throw new ForbiddenException("Márgenes y costos son visibles sólo para Finanzas, Contabilidad y Gerencia.");const accounts=await this.ctx.accountMap();const entries=await this.repo.list<JournalEntry>("journal_entries",{status:["POSTED","REVERSED"],entryDate:{gte:from,lte:to}});const ids=new Set(entries.map((e)=>e.id));
    const key=dimension==="CLIENT"?"clientId":"projectId";const lines=entries.length?(await this.repo.list<JournalLine>("journal_entry_lines",{journalEntryId:[...ids]})).filter((l)=>(l as Row)[key]&&(!onlyId||(l as Row)[key]===onlyId)):[];const rows=new Map<string,ProfitabilityRow>();
    const row=(id:string)=>{let r=rows.get(id);if(!r){r={dimension,id,name:id,revenue:0,directCosts:0,laborCost:null,laborHours:0,expenses:0,grossMargin:0,grossMarginPercent:null,operatingMargin:null,notes:[]};rows.set(id,r);}return r;};
    for(const l of lines){const a=accounts.get(l.accountId);if(!a)continue;const r=row((l as Row)[key]);if(a.accountType==="REVENUE")r.revenue=r2(r.revenue+l.credit-l.debit);else if(a.accountType==="EXPENSE"){if(a.statementSection==="COST_OF_SALES")r.directCosts=r2(r.directCosts+l.debit-l.credit);else r.expenses=r2(r.expenses+l.debit-l.credit);}}
    if(dimension==="PROJECT"){const projects=onlyId?[onlyId]:[...new Set([...rows.keys(),...(await this.ctx.sources.projects()).map((p)=>p.id)])];const rates=await this.repo.list<Row>("cost_rates",{});for(const projectId of projects){const logs=await this.ctx.sources.worklogs({projectId,from,to});if(!logs.length&&!rows.has(projectId))continue;const r=row(projectId);r.laborHours=r2(sum(logs.map((w)=>w.durationMinutes))/60);let cost=0;const missing=new Set<string>();for(const w of logs){const rate=rates.find((x)=>x.userId===w.userId&&x.effectiveFrom<=w.workDate&&(!x.effectiveTo||x.effectiveTo>=w.workDate));if(!rate)missing.add(w.userId);else cost+=rate.hourlyCost*w.durationMinutes/60;}r.laborCost=logs.length&&!missing.size?r2(cost):logs.length?null:0;if(missing.size)r.notes.push(`Costo laboral no calculado: ${missing.size} usuario(s) sin tarifa de costo configurada.`);}}
    const names=dimension==="CLIENT"?await this.ctx.sources.clientNames([...rows.keys()]):new Map((await this.ctx.sources.projects()).map((p)=>[p.id,p.name]));
    return[...rows.values()].map((r)=>{const gross=r2(r.revenue-r.directCosts-(r.laborCost??0));return{...r,name:names.get(r.id)??r.id,grossMargin:gross,grossMarginPercent:r.revenue?r2(gross/r.revenue*100):null,operatingMargin:r2(gross-r.expenses),notes:r.revenue?r.notes:[...r.notes,"Sin ingresos contabilizados con esta dimensión en el período."]};}).sort((a,b)=>b.revenue-a.revenue);
  }
  async clientSummary(clientId:string,actor:FinanceActor):Promise<ClientFinanceSummary>{
    this.ctx.require(actor,"invoice.view");await this.ctx.assertClientAccess(actor,clientId);const today=todayCl();const invoices=(await this.repo.list<Invoice>("invoices",{clientId},{order:"createdAt"})).map((i)=>withEffective(i,today));const issued=invoices.filter((i)=>["ISSUED","PARTIALLY_PAID","PAID","CREDITED"].includes(i.status));
    const payments=can(actor.role,"payment.view")?await this.repo.list<Payment>("payments",{clientId},{order:"receivedAt"}):[];const schedules=await this.repo.list<BillingSchedule>("billing_schedules",{clientId,active:true},{order:"nextBillingDate",ascending:true});const promises=await this.repo.list<PaymentPromise>("payment_promises",{clientId,status:"OPEN"});
    const next=schedules[0];return{clientId,invoiced:sum(issued.map((i)=>(i.documentTypeCode===61?-1:1)*i.totalAmount)),paid:sum(issued.map((i)=>i.amountPaid)),balance:sum(issued.filter((i)=>i.documentTypeCode!==61).map((i)=>i.balanceDue)),overdue:sum(issued.filter((i)=>i.effectiveStatus==="OVERDUE").map((i)=>i.balanceDue)),creditBalance:sum(payments.filter((p)=>["CONFIRMED","PARTIALLY_REFUNDED"].includes(p.status)).map((p)=>p.unappliedAmount)),nextBilling:next?{date:next.nextBillingDate,amount:next.amount,description:next.description}:null,recurring:schedules,invoices:invoices.slice(0,30),payments:payments.slice(0,30),promises,currency:"CLP"};
  }
  async projectSummary(projectId:string,actor:FinanceActor):Promise<ProjectFinanceSummary>{
    this.ctx.require(actor,"invoice.view");const project=await this.ctx.sources.project(projectId);if(project?.clientId)await this.ctx.assertClientAccess(actor,project.clientId);const invoices=(await this.repo.list<Invoice>("invoices",{projectId,status:["ISSUED","PARTIALLY_PAID","PAID","CREDITED"]}));const invoiced=sum(invoices.map((i)=>(i.documentTypeCode===61?-1:1)*i.totalAmount));
    const collected=invoices.length?sum((await this.repo.list<PaymentAllocation>("payment_allocations",{invoiceId:invoices.map((i)=>i.id)})).filter((a)=>!a.reversedAt).map((a)=>a.amount)):0;const sale=project?.quoteId?(await this.ctx.sources.wonSales()).find((s)=>s.quoteId===project.quoteId):undefined;
    const logs=await this.ctx.sources.worklogs({projectId});const hours=r2(sum(logs.map((w)=>w.durationMinutes))/60);
    if(!canSeeMargins(actor))return{projectId,soldValue:sale?.amount??null,invoiced,collected,directCosts:0,laborHours:hours,laborCost:null,expenses:0,margin:null,marginPercent:null,notes:["Costos y márgenes visibles sólo para Finanzas, Contabilidad y Gerencia."],currency:"CLP"};
    const[row]=await this.profitability(actor,"PROJECT","1900-01-01",todayCl(),projectId);return{projectId,soldValue:sale?.amount??null,invoiced,collected,directCosts:row?.directCosts??0,laborHours:hours,laborCost:row?.laborCost??(logs.length?null:0),expenses:row?.expenses??0,margin:row?row.operatingMargin:null,marginPercent:row?.grossMarginPercent??null,notes:row?.notes??["Sin movimientos contables asociados al proyecto."],currency:"CLP"};
  }
}

// =========================================================================================== Informes y exportaciones auditadas
export const reportTypes=["INCOME_STATEMENT","BALANCE_SHEET","TRIAL_BALANCE","JOURNAL","LEDGER","CASHFLOW","AR_AGING","AP_AGING","SALES","PURCHASES","VAT","PROFITABILITY_CLIENT","PROFITABILITY_PROJECT","BUDGET_VS_ACTUAL"] as const;
export type ReportType=(typeof reportTypes)[number];
interface ReportTable { type:ReportType; title:string; period:string; columns:Array<{label:string;width:number;align?:"left"|"right"}>; rows:Array<Array<string|number>>; summary:string[]; source:string; }
const n=(value:number)=>Math.round(value*100)/100;
@Injectable()
export class ReportsService {
  constructor(private readonly ctx:FinanceContext,private readonly statements:StatementsService,private readonly ledger:LedgerService,private readonly analytics:AnalyticsService,private readonly collections:CollectionsService,private readonly payables:PayableService,private readonly tax:TaxService,private readonly budgets:BudgetService,private readonly close:CloseService){}
  private get repo(){return this.ctx.repo;}
  private async closedSnapshot(from:string,to:string){if(from.slice(0,7)!==to.slice(0,7)||monthRange(from.slice(0,7)).from!==from||monthRange(from.slice(0,7)).to!==to)return null;const period=await this.repo.findOne<Row>("accounting_periods",{periodKey:from.slice(0,7)});if(!period||!["CLOSED","LOCKED"].includes(period.status))return null;return(await this.repo.list<Row>("period_snapshots",{periodId:period.id},{order:"version",limit:1}))[0]??null;}
  async build(type:ReportType,params:Row,actor:FinanceActor):Promise<ReportTable>{
    this.ctx.require(actor,"report.finance.view");const today=todayCl();const from=params.from?isoDate(params.from,"Desde"):`${today.slice(0,7)}-01`;const to=params.to?isoDate(params.to,"Hasta"):today;if(from>to)throw new BadRequestException("Rango de fechas inválido.");const period=periodLabel(from,to);
    const ledgerTypes:ReportType[]=["INCOME_STATEMENT","BALANCE_SHEET","TRIAL_BALANCE","JOURNAL","LEDGER","PROFITABILITY_CLIENT","PROFITABILITY_PROJECT","BUDGET_VS_ACTUAL","CASHFLOW"];if(ledgerTypes.includes(type))this.ctx.require(actor,"accounting.view");
    const snapshot=["INCOME_STATEMENT","BALANCE_SHEET","TRIAL_BALANCE"].includes(type)?await this.closedSnapshot(from,to):null;const snapNote=snapshot?`Snapshot de cierre v${snapshot.version} · SHA-256 ${String(snapshot.sha256).slice(0,16)}…`:"Libro mayor vigente (asientos contabilizados)";
    switch(type){
      case"INCOME_STATEMENT":{const s=snapshot?snapshot.incomeStatement:await this.statements.incomeStatement(from,to);const rows:Array<Array<string|number>>=[];for(const section of s.sections){rows.push(["",section.label.toUpperCase(),""]);for(const l of section.lines)rows.push([l.code??"",l.name,n(l.amount)]);rows.push(["",`Total ${section.label.toLowerCase()}`,n(section.total)]);}return{type,title:"Estado de Resultados",period,columns:[{label:"Cuenta",width:12},{label:"Concepto",width:50},{label:"Monto",width:18,align:"right"}],rows,summary:[`Margen bruto: ${money(s.grossProfit)}`,`Resultado operacional: ${money(s.operatingResult)}`,`Resultado del período: ${money(s.netResult)}`],source:snapNote};}
      case"BALANCE_SHEET":{const s=snapshot?snapshot.balanceSheet:await this.statements.balanceSheet(to);const rows:Array<Array<string|number>>=[["","ACTIVOS",""],...s.assets.map((l:Row)=>[l.code,l.name,n(l.amount)]),["","Total activos",n(s.totalAssets)],["","PASIVOS",""],...s.liabilities.map((l:Row)=>[l.code,l.name,n(l.amount)]),["","Total pasivos",n(s.totalLiabilities)],["","PATRIMONIO",""],...s.equity.map((l:Row)=>[l.code,l.name,n(l.amount)]),["","Resultado del ejercicio (no cerrado)",n(s.currentResult)],["","Total patrimonio",n(s.totalEquity)]];return{type,title:"Balance General",period:`Al ${displayDate(to)}`,columns:[{label:"Cuenta",width:12},{label:"Concepto",width:50},{label:"Monto",width:18,align:"right"}],rows,summary:[`Activos ${money(s.totalAssets)} = Pasivos ${money(s.totalLiabilities)} + Patrimonio ${money(s.totalEquity)}`,s.balanced?"Ecuación contable verificada.":`DESCUADRE: diferencia ${money(s.difference)}`],source:snapNote};}
      case"TRIAL_BALANCE":{const s=snapshot?snapshot.trialBalance:await this.statements.trialBalance(from,to);return{type,title:"Balance de Comprobación",period,columns:[{label:"Cuenta",width:12},{label:"Nombre",width:40},{label:"Saldo inicial",width:16,align:"right"},{label:"Debe",width:16,align:"right"},{label:"Haber",width:16,align:"right"},{label:"Saldo final",width:16,align:"right"}],rows:s.rows.map((r:Row)=>[r.code,r.name,n(r.opening),n(r.debit),n(r.credit),n(r.closing)]),summary:[`Total Debe ${money(s.totals.debit)} · Total Haber ${money(s.totals.credit)}`,s.balanced?"Cuadrado (Debe = Haber).":"DESCUADRADO"],source:snapNote};}
      case"JOURNAL":{const book=await this.ledger.journalBook(from,to);const rows:Array<Array<string|number>>=[];for(const e of book.entries){for(const l of e.lines??[])rows.push([displayDate(e.entryDate),e.entryNumber??"",l.accountCode??"",l.accountName??"",l.description??e.description,n(l.debit),n(l.credit)]);}return{type,title:"Libro Diario",period,columns:[{label:"Fecha",width:10},{label:"N° asiento",width:16},{label:"Cuenta",width:10},{label:"Nombre",width:26},{label:"Glosa",width:40},{label:"Debe",width:14,align:"right"},{label:"Haber",width:14,align:"right"}],rows,summary:[`${book.entries.length} asientos · Debe ${money(book.totalDebit)} · Haber ${money(book.totalCredit)}`],source:"Asientos contabilizados"};}
      case"LEDGER":{if(!params.accountId)throw new BadRequestException("Selecciona la cuenta.");const l=await this.ledger.ledger(String(params.accountId),from,to);return{type,title:`Libro Mayor · ${l.account.code} ${l.account.name}`,period,columns:[{label:"Fecha",width:10},{label:"N° asiento",width:16},{label:"Glosa",width:50},{label:"Debe",width:14,align:"right"},{label:"Haber",width:14,align:"right"},{label:"Saldo",width:16,align:"right"}],rows:[["","","Saldo inicial","","",n(l.opening)],...l.movements.map((m)=>[displayDate(m.entryDate),m.entryNumber??"",m.lineDescription??m.description,n(m.debit),n(m.credit),n(m.balance)])],summary:[`Saldo final ${money(l.closing)}`],source:"Asientos contabilizados"};}
      case"CASHFLOW":{const c=await this.analytics.cashflow(actor,String(params.scenario??"BASE"));return{type,title:"Flujo de Caja",period:`Real 6 meses + Proyección (${c.scenario})`,columns:[{label:"Mes",width:12},{label:"Tipo",width:14},{label:"Entradas",width:18,align:"right"},{label:"Salidas",width:18,align:"right"},{label:"Neto",width:18,align:"right"}],rows:[...c.history,...c.projection].map((p)=>[p.periodKey.split("-").reverse().join("-"),p.kind==="REAL"?"REAL":"PROYECCIÓN",n(p.inflows),n(p.outflows),n(p.net)]),summary:[`Posición de caja (libro): ${money(c.cashPosition)}`,...c.assumptions],source:"Libro mayor (real) y documentos abiertos (proyección)"};}
      case"AR_AGING":case"AP_AGING":{const a=type==="AR_AGING"?await this.collections.aging(actor,to):await this.payables.aging(actor,to);const keys=a.buckets.map((b)=>b.key);return{type,title:type==="AR_AGING"?"Antigüedad de Cuentas por Cobrar":"Antigüedad de Cuentas por Pagar",period:`Al ${displayDate(to)} (desde fecha de vencimiento)`,columns:[{label:type==="AR_AGING"?"Cliente":"Proveedor",width:40},...a.buckets.map((b)=>({label:b.label,width:15,align:"right" as const})),{label:"Total",width:16,align:"right"}],rows:a.byParty.map((p)=>[p.partyName,...keys.map((k)=>n(p.buckets[k]??0)),n(p.total)]),summary:[`Total ${money(a.total)}`],source:"Documentos abiertos"};}
      case"SALES":{const invoices=await this.ctx.withClientNames(await this.repo.list<Invoice>("invoices",{issueDate:{gte:from,lte:to},status:["ISSUED","PARTIALLY_PAID","PAID","CREDITED"]},{order:"issueDate",ascending:true}));const docs=await this.repo.list<Row>("tax_documents",{invoiceId:invoices.map((i)=>i.id)});const folio=(i:Invoice)=>docs.find((d)=>d.id===i.taxDocumentId)?.folio??"";const s=(i:Invoice)=>i.documentTypeCode===61?-1:1;return{type,title:"Libro de Ventas (registro interno)",period,columns:[{label:"Fecha",width:10},{label:"Tipo",width:6},{label:"Folio",width:10},{label:"Cliente",width:36},{label:"RUT",width:12},{label:"Neto",width:14,align:"right"},{label:"Exento",width:14,align:"right"},{label:"IVA",width:14,align:"right"},{label:"Total",width:14,align:"right"}],rows:invoices.map((i)=>[displayDate(i.issueDate),i.documentTypeCode,folio(i),i.clientName??i.clientSnapshot.legalName??"",i.clientSnapshot.rut??"",n(s(i)*i.netAmount),n(s(i)*i.exemptAmount),n(s(i)*i.taxAmount),n(s(i)*i.totalAmount)]),summary:[`Total ${money(sum(invoices.map((i)=>s(i)*i.totalAmount)))}`,"El Registro de Ventas oficial es el RCV del SII."],source:"Documentos emitidos en Zyteron"};}
      case"PURCHASES":{this.ctx.require(actor,"expense.view");const docs=await this.repo.list<Row>("received_tax_documents",{issueDate:{gte:from,lte:to}},{order:"issueDate",ascending:true});const s=(d:Row)=>d.documentTypeCode===61?-1:1;return{type,title:"Libro de Compras (registro interno)",period,columns:[{label:"Fecha",width:10},{label:"Tipo",width:6},{label:"Folio",width:10},{label:"Proveedor",width:34},{label:"RUT",width:12},{label:"Neto",width:14,align:"right"},{label:"IVA",width:14,align:"right"},{label:"Crédito",width:14,align:"right"},{label:"Total",width:14,align:"right"}],rows:docs.map((d)=>[displayDate(d.issueDate),d.documentTypeCode,d.folio,d.issuerName,d.issuerRut,n(s(d)*d.netAmount),n(s(d)*d.taxAmount),d.taxCreditClassification==="PENDING_REVIEW"?"Pendiente":n(s(d)*(d.taxCreditEligibleAmount??0)),n(s(d)*d.totalAmount)]),summary:[`Total ${money(sum(docs.map((d)=>s(d)*d.totalAmount)))}`,"El Registro de Compras oficial es el RCV del SII."],source:"DTE recibidos"};}
      case"VAT":{const v=await this.tax.vatSummary(String(params.period??from.slice(0,7)),actor);return{type,title:"IVA del período — Estimación interna",period:v.periodKey.split("-").reverse().join("-"),columns:[{label:"Concepto",width:60},{label:"Monto",width:20,align:"right"}],rows:[["Débito fiscal (facturas)",n(v.debit)],["Débito notas de débito",n(v.debitNotesDebit)],["Menos IVA notas de crédito",n(-v.creditNotesDebit)],["Débito neto",n(v.netDebit)],["Crédito potencial de compras",n(v.creditPotential)],["Crédito clasificado recuperable",n(v.creditEligible)],["Crédito pendiente de clasificar (excluido)",n(v.creditPendingReview)],["IVA no recuperable",n(v.creditNonRecoverable)],["Remanente período anterior",n(v.adjustments)],["IVA estimado a pagar",n(v.estimatedPayable)],["Remanente estimado",n(v.remainder)]],summary:["Estimación interna: no constituye declaración presentada ante el SII."],source:"Documentos registrados"};}
      case"PROFITABILITY_CLIENT":case"PROFITABILITY_PROJECT":{const rows=await this.analytics.profitability(actor,type==="PROFITABILITY_CLIENT"?"CLIENT":"PROJECT",from,to);return{type,title:`Rentabilidad por ${type==="PROFITABILITY_CLIENT"?"cliente":"proyecto"}`,period,columns:[{label:"Nombre",width:36},{label:"Ingresos",width:15,align:"right"},{label:"Costos directos",width:15,align:"right"},{label:"Costo laboral",width:15,align:"right"},{label:"Gastos",width:15,align:"right"},{label:"Margen bruto",width:15,align:"right"},{label:"Margen %",width:10,align:"right"}],rows:rows.map((r)=>[r.name,n(r.revenue),n(r.directCosts),r.laborCost===null?"Sin tarifa":n(r.laborCost),n(r.expenses),n(r.grossMargin),r.grossMarginPercent===null?"—":`${r.grossMarginPercent}%`]),summary:rows.flatMap((r)=>r.notes.map((note)=>`${r.name}: ${note}`)).slice(0,6),source:"Libro mayor con dimensiones + worklogs × tarifas"};}
      case"BUDGET_VS_ACTUAL":{if(!params.budgetId)throw new BadRequestException("Selecciona el presupuesto.");const r=await this.budgets.vsActual(String(params.budgetId),actor);return{type,title:`Presupuesto vs Real · ${r.budget.name}`,period:String(r.budget.fiscalYear),columns:[{label:"Cuenta",width:12},{label:"Nombre",width:34},{label:"Mes",width:10},{label:"Presupuesto",width:16,align:"right"},{label:"Real",width:16,align:"right"},{label:"Variación",width:16,align:"right"},{label:"%",width:8,align:"right"}],rows:r.rows.map((x)=>[x.accountCode,x.accountName,x.periodKey?.split("-").reverse().join("-")??"",n(x.budget),n(x.actual),n(x.variance),x.variancePercent===null?"—":`${x.variancePercent}%`]),summary:[`Presupuesto ${money(r.totals.budget)} · Real ${money(r.totals.actual)} · Variación ${money(r.totals.variance)}`],source:"Presupuesto aprobado y libro mayor"};}
    }
  }
  /** Exportación auditada; el PDF lleva encabezado institucional y nunca se presenta como documento del SII. */
  async export(type:ReportType,format:"csv"|"xlsx"|"pdf",params:Row,actor:FinanceActor){
    this.ctx.require(actor,"report.finance.export");const report=await this.build(type,params,actor);const settings=await this.repo.settings();const generated=displayDateTime(nowIso());const by=`${actor.role}${actor.userId?` · ${actor.userId.slice(0,8)}`:""}`;const base=`${report.title.replace(/[^\wÁÉÍÓÚáéíóúÑñ ]+/g,"").replace(/\s+/g,"_")}_${todayCl()}`;
    const headers=report.columns.map((c)=>c.label);let bytes:Buffer,mime:string,fileName:string;
    if(format==="csv"){bytes=writeCsv(headers,report.rows);mime="text/csv; charset=utf-8";fileName=`${base}.csv`;}
    else if(format==="xlsx"){bytes=writeXlsx(report.title.slice(0,31),headers,[[`${settings.companyLegalName} · ${report.title} · Período ${report.period} · Generado ${generated} por ${by}`],[],...report.rows]);mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";fileName=`${base}.xlsx`;}
    else{bytes=renderPdfReport({title:report.title,headerLines:[`${settings.companyLegalName}${settings.companyRut?` · RUT ${settings.companyRut}`:""}`,`Período: ${report.period}`,`Fecha de generación: ${generated} · Generado por: ${by}`,`Fuente: ${report.source}`],columns:report.columns,rows:report.rows.map((r)=>r.map((c)=>typeof c==="number"?new Intl.NumberFormat("es-CL",{maximumFractionDigits:2}).format(c):String(c))),summary:report.summary,footer:"Informe interno de gestión. No constituye documento tributario ni declaración ante el SII."});mime="application/pdf";fileName=`${base}.pdf`;}
    await this.repo.audit(actor,"FINANCE_REPORT_EXPORTED","REPORT",null,`${report.title} exportado (${format.toUpperCase()})`,{type,format,params,rows:report.rows.length});return{bytes,mime,fileName};
  }
}

// =========================================================================================== Contador Zyteron (copiloto determinístico)
const monthNames=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
export function parseQuestionPeriod(question:string,today=todayCl()):{from:string;to:string;label:string}{
  const q=question.toLowerCase();const range=/(\d{2}-\d{2}-\d{4})\s*(?:al|a|hasta|-)\s*(\d{2}-\d{2}-\d{4})/.exec(q);if(range){const from=isoDate(range[1],"Desde"),to=isoDate(range[2],"Hasta");return{from,to,label:periodLabel(from,to)};}
  const year=/(20\d{2})/.exec(q)?.[1];const monthIndex=monthNames.findIndex((m)=>q.includes(m));if(monthIndex>=0){const key=`${year??today.slice(0,4)}-${String(monthIndex+1).padStart(2,"0")}`;const r=monthRange(key);return{...r,label:`${monthNames[monthIndex]} ${key.slice(0,4)}`};}
  if(q.includes("mes pasado")||q.includes("mes anterior")){const r=monthRange(previousPeriod(today.slice(0,7)));return{...r,label:"mes anterior"};}
  if(q.includes("este año")||q.includes("año actual")||(year&&!q.includes("mes"))){const y=year??today.slice(0,4);return{from:`${y}-01-01`,to:y===today.slice(0,4)?today:`${y}-12-31`,label:`año ${y}`};}
  if(q.includes("hoy")){return{from:today,to:today,label:"hoy"};}
  const r=monthRange(today.slice(0,7));return{from:r.from,to:today,label:"mes en curso"};
}
@Injectable()
export class CopilotService {
  constructor(private readonly ctx:FinanceContext,private readonly statements:StatementsService,private readonly analytics:AnalyticsService,private readonly collections:CollectionsService,private readonly payables:PayableService,private readonly tax:TaxService,private readonly ledger:LedgerService){}
  private get repo(){return this.ctx.repo;}
  async ask(question:string,actor:FinanceActor):Promise<CopilotAnswer>{
    this.ctx.requireAny(actor,"report.finance.view","receivable.view");const text=String(question??"").trim().slice(0,500);if(!text)throw new BadRequestException("Escribe una pregunta.");const q=text.toLowerCase();const period=parseQuestionPeriod(text);const now=nowIso();
    const base={id:"",question:text,period:{from:period.from,to:period.to},rows:[] as Array<Record<string,unknown>>,proposal:null as CopilotAnswer["proposal"],lastUpdated:now,disclaimer:"Respuesta calculada con datos registrados en Zyteron a la hora indicada. El copiloto no contabiliza, emite, presenta, elimina ni paga."};let answer:CopilotAnswer;
    const ledgerOk=can(actor.role,"accounting.view");const needLedger=()=>{if(!ledgerOk)throw new ForbiddenException("Esa consulta usa el libro contable y tu rol no tiene acceso.");};
    if(/propon|sugier|asiento/.test(q)){needLedger();const amount=Number((/(\d[\d.]*)/.exec(q.replace(/\$/g,""))?.[1]??"0").replace(/\./g,""));const kinds:Array<[RegExp,string,string,string]>=[[/comisi[oó]n bancaria|gasto bancario/,"5.4.02","1.1.02.01","Comisión bancaria"],[/comisi[oó]n.*(mercado ?pago|pasarela)/,"5.4.01","1.1.05","Comisión de pasarela"],[/arriendo/,"5.2.02","2.1.01","Arriendo devengado"],[/software|suscripci/,"5.2.03","2.1.01","Suscripción de software"]];const kind=kinds.find(([re])=>re.test(q));
      if(!kind||!(amount>0))answer={...base,intent:"PROPOSE_ENTRY",answer:"Para proponer un asiento indica el concepto (comisión bancaria, comisión de pasarela, arriendo o software) y el monto exacto. La propuesta nunca se contabiliza sola: debes crear el borrador y otro usuario con permiso lo contabiliza.",amounts:[],sources:[],drillDown:"/finance/journal"};
      else answer={...base,intent:"PROPOSE_ENTRY",answer:`Propuesta: ${kind[3]} por ${money(amount)} — Debe ${kind[1]} / Haber ${kind[2]}. Revisa cuentas y fecha antes de crear el borrador.`,amounts:[{label:"Monto propuesto",value:amount,currency:"CLP"}],sources:[{label:"Plan de cuentas",query:"chart_of_accounts",href:"/finance/chart-of-accounts"}],drillDown:"/finance/journal",proposal:{kind:"JOURNAL_ENTRY",description:`${kind[3]} (propuesta Contador Zyteron)`,lines:[{accountCode:kind[1],debit:amount,credit:0},{accountCode:kind[2],debit:0,credit:amount}]}};}
    else if(/anomal|riesgo|alerta|problema|salud|revisar/.test(q)){const health=await this.analytics.health();answer={...base,intent:"ANOMALIES",period:null,answer:health.factors.length?`Salud contable ${health.status} (puntaje ${health.score}/100). ${health.factors.slice(0,5).map((f)=>`${f.title}: ${f.count}${f.amount!==null?` · ${money(f.amount)}`:""}`).join("; ")}.`:"Los controles determinísticos no detectan anomalías.",amounts:health.factors.filter((f)=>f.amount!==null).map((f)=>({label:f.title,value:f.amount!,currency:"CLP"})),rows:health.factors.map((f)=>({...f})),sources:health.factors.map((f)=>({label:f.title,query:f.key,href:f.drillDown})),drillDown:"/finance"};}
    else if(/iva|f29|impuesto/.test(q)){this.ctx.require(actor,"tax.view");const v=await this.tax.vatSummary(period.from.slice(0,7),actor);answer={...base,intent:"VAT",period:monthRange(v.periodKey),answer:`Estimación interna de IVA ${v.periodKey.split("-").reverse().join("-")}: débito neto ${money(v.netDebit)}, crédito recuperable clasificado ${money(v.creditEligible)}, pendiente de clasificar ${money(v.creditPendingReview)}. IVA estimado a pagar ${money(v.estimatedPayable)}${v.remainder?`, remanente ${money(v.remainder)}`:""}. No es una declaración presentada.`,amounts:[{label:"Débito neto",value:v.netDebit,currency:"CLP"},{label:"Crédito recuperable",value:v.creditEligible,currency:"CLP"},{label:"IVA estimado a pagar",value:v.estimatedPayable,currency:"CLP"}],sources:v.sources.map((s)=>({label:s.label,query:s.label,href:s.href})),drillDown:`/finance/taxes?period=${v.periodKey}`};}
    else if(/por pagar|proveedor|deudas? con/.test(q)){const a=await this.payables.aging(actor);answer={...base,intent:"AP",period:{from:a.asOf,to:a.asOf},answer:`Cuentas por pagar al ${displayDate(a.asOf)}: ${money(a.total)}. ${a.buckets.filter((b)=>b.amount).map((b)=>`${b.label}: ${money(b.amount)}`).join("; ")||"Sin saldos."}`,amounts:a.buckets.map((b)=>({label:b.label,value:b.amount,currency:"CLP"})),rows:a.byParty.slice(0,10).map((p)=>({...p})),sources:[{label:"Cuentas por pagar abiertas",query:"payables",href:"/finance/payables"}],drillDown:"/finance/payables"};}
    else if(/cobrar|deben|deuda|morosid|vencid|cobranza/.test(q)){const a=await this.collections.aging(actor);const overdue=sum(a.buckets.filter((b)=>b.key!=="CURRENT").map((b)=>b.amount));answer={...base,intent:"AR",period:{from:a.asOf,to:a.asOf},answer:`Por cobrar al ${displayDate(a.asOf)}: ${money(a.total)}, de los cuales ${money(overdue)} están vencidos. Mayores saldos: ${a.byParty.slice(0,5).map((p)=>`${p.partyName} ${money(p.total)}`).join("; ")||"sin saldos"}.`,amounts:[{label:"Total por cobrar",value:a.total,currency:"CLP"},{label:"Vencido",value:overdue,currency:"CLP"}],rows:a.byParty.slice(0,10).map((p)=>({...p})),sources:[{label:"Antigüedad desde vencimiento",query:"invoices abiertas",href:"/finance/receivables"}],drillDown:"/finance/collections"};}
    else if(/caja|efectivo|banco|liquidez|saldo/.test(q)){needLedger();const c=await this.analytics.cashflow(actor);answer={...base,intent:"CASH",period:{from:todayCl(),to:todayCl()},answer:`Posición de caja contable al ${displayDate(todayCl())}: ${money(c.cashPosition)}. ${c.cashAccounts.map((a)=>`${a.name}: ${money(a.balance)}`).join("; ")}.`,amounts:c.cashAccounts.map((a)=>({label:a.name,value:a.balance,currency:"CLP"})),sources:[{label:"Libro mayor cuentas de disponible",query:"is_cash",href:"/finance/banks"}],drillDown:"/finance/banks"};}
    else if(/gasto|costo/.test(q)){needLedger();const s=await this.statements.incomeStatement(period.from,period.to);const lines=s.sections.filter((x)=>["COST_OF_SALES","OPERATING_EXPENSE","FINANCIAL_EXPENSE","OTHER_EXPENSE"].includes(x.key)).flatMap((x)=>x.lines).sort((a,b)=>b.amount-a.amount);const total=sum(lines.map((l)=>l.amount));answer={...base,intent:"EXPENSES",answer:`Costos y gastos contabilizados ${period.label} (${periodLabel(period.from,period.to)}): ${money(total)}. Principales: ${lines.slice(0,5).map((l)=>`${l.code} ${l.name} ${money(l.amount)}`).join("; ")||"sin movimientos"}.`,amounts:[{label:"Costos y gastos",value:total,currency:"CLP"}],rows:lines.slice(0,10).map((l)=>({...l})),sources:[{label:"Estado de resultados",query:"income_statement",href:`/finance/reports?type=INCOME_STATEMENT&from=${period.from}&to=${period.to}`}],drillDown:`/finance/reports?type=INCOME_STATEMENT&from=${period.from}&to=${period.to}`};}
    else if(/resultado|utilidad|ganancia|p[eé]rdida|margen/.test(q)){needLedger();const s=await this.statements.incomeStatement(period.from,period.to);answer={...base,intent:"RESULT",answer:`Resultado contable ${period.label} (${periodLabel(period.from,period.to)}): ingresos ${money(s.revenue)}, costo de ventas ${money(s.costOfSales)}, margen bruto ${money(s.grossProfit)}, gastos operacionales ${money(s.operatingExpenses)}, resultado ${money(s.netResult)}.`,amounts:[{label:"Ingresos",value:s.revenue,currency:"CLP"},{label:"Margen bruto",value:s.grossProfit,currency:"CLP"},{label:"Resultado",value:s.netResult,currency:"CLP"}],sources:[{label:"Libro mayor",query:"income_statement",href:`/finance/reports?type=INCOME_STATEMENT&from=${period.from}&to=${period.to}`}],drillDown:`/finance/reports?type=INCOME_STATEMENT&from=${period.from}&to=${period.to}`};}
    else if(/factur|vend|ingres|venta/.test(q)){const issued=await this.repo.list<Invoice>("invoices",{issueDate:{gte:period.from,lte:period.to},status:["ISSUED","PARTIALLY_PAID","PAID","CREDITED"]});const s=(i:Invoice)=>i.documentTypeCode===61?-1:1;const total=sum(issued.map((i)=>s(i)*i.totalAmount)),net=sum(issued.map((i)=>s(i)*(i.netAmount+i.exemptAmount)));const revenue=ledgerOk?(await this.statements.incomeStatement(period.from,period.to)).revenue:null;
      answer={...base,intent:"REVENUE",answer:`Facturado ${period.label} (${periodLabel(period.from,period.to)}): ${money(total)} con IVA (${money(net)} neto) en ${issued.length} documentos.${revenue!==null?` Ingresos contabilizados en el libro: ${money(revenue)}.`:""} Facturación, ingreso contable y caja son cifras distintas.`,amounts:[{label:"Facturado con IVA",value:total,currency:"CLP"},{label:"Facturado neto",value:net,currency:"CLP"},...(revenue!==null?[{label:"Ingresos contabilizados",value:revenue,currency:"CLP"}]:[])],sources:[{label:"Documentos emitidos",query:"invoices issue_date",href:`/finance/invoices?from=${period.from}&to=${period.to}`}],drillDown:`/finance/invoices?from=${period.from}&to=${period.to}`};}
    else answer={...base,intent:"UNKNOWN",period:null,answer:"No tengo una consulta determinística para esa pregunta. Prueba: «¿cuánto facturamos en septiembre 2026?», «¿quiénes nos deben?», «¿cuál es la caja?», «resultado del mes pasado», «IVA del mes», «anomalías» o «propón asiento comisión bancaria 5.000».",amounts:[],sources:[],drillDown:null};
    const run=await this.repo.create<Row>("finance_analysis_runs",{question:text,intent:answer.intent,periodFrom:answer.period?.from??null,periodTo:answer.period?.to??null,result:{answer:answer.answer,amounts:answer.amounts,proposal:answer.proposal},sources:answer.sources,createdBy:actor.userId});return{...answer,id:run.id};
  }
  /** Convierte una propuesta en BORRADOR (requiere journal.create); la contabilización es otra acción humana. */
  async draftFromProposal(body:Row,actor:FinanceActor){this.ctx.require(actor,"journal.create");const lines=Array.isArray(body.lines)?body.lines.map((l:Row)=>({accountCode:String(l.accountCode),debit:Number(l.debit)||0,credit:Number(l.credit)||0})):[];return this.ledger.createEntry({entryDate:body.entryDate??todayCl(),description:String(body.description??"Propuesta Contador Zyteron"),lines},actor,{sourceType:"COPILOT_PROPOSAL",sourceId:optionalId(body.analysisRunId)});}
  history(actor:FinanceActor){this.ctx.requireAny(actor,"report.finance.view","receivable.view");return this.repo.list<Row>("finance_analysis_runs",{createdBy:actor.userId??undefined},{order:"createdAt",limit:30});}
}
const optionalId=(value:unknown)=>typeof value==="string"&&/^[0-9a-f-]{36}$/i.test(value)?value:null;

// =========================================================================================== Scheduler
@Injectable()
export class FinanceScheduler implements OnModuleInit,OnModuleDestroy {
  private timer:NodeJS.Timeout|null=null;private running=false;
  constructor(private readonly ctx:FinanceContext,private readonly billing:BillingScheduleService,private readonly dte:DteService,private readonly collections:CollectionsService,private readonly payables:PayableService,private readonly reconciliation:ReconciliationService,private readonly close:CloseService,private readonly quotePayments:QuotePaymentService){}
  onModuleInit(){const minutes=Number(process.env.FINANCE_SCHEDULER_INTERVAL_MINUTES);if(minutes>=5)this.timer=setInterval(()=>{void this.runDue(systemActor).catch(()=>undefined);},minutes*60000);}
  onModuleDestroy(){if(this.timer)clearInterval(this.timer);}
  /** Tareas idempotentes: borradores de facturación, estados DTE, alertas, recordatorios y promesas. Nunca emite ni contabiliza. */
  async runDue(actor:FinanceActor){
    if(this.running)return{skipped:"Ejecución en curso"};this.running=true;const today=todayCl();const result:Row={startedAt:nowIso()};
    try{const step=async(name:string,work:()=>Promise<unknown>)=>{try{result[name]=await work();}catch(error){result[name]={error:String((error as Error).message).slice(0,300)};}};
      await step("billing",()=>this.billing.runDue(today,actor));await step("dteStatus",()=>this.dte.pollPending(actor));await step("certificates",()=>this.dte.certificateAlerts());await step("reminders",()=>this.collections.runReminders(today));await step("promises",()=>this.collections.evaluatePromises(today));await step("payables",()=>this.payables.dueNotifications(today));await step("autoMatch",()=>this.reconciliation.autoMatch(actor));await step("quotePayments",()=>this.quotePayments.runDue(today));
      await step("close",async()=>{const run=await this.close.center(previousPeriod(today.slice(0,7)),{...actor,role:"GERENTE_GENERAL"});return{period:run.period.periodKey,status:run.status,blockers:run.blockers.length};});
      await this.ctx.repo.audit(actor,"FINANCE_SCHEDULER_RUN","SCHEDULER",null,"Tareas programadas de Finanzas ejecutadas",result);return{...result,finishedAt:nowIso()};}
    finally{this.running=false;}
  }
}

