import { BadRequestException, ConflictException, Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import type { DteCertificate, DteReadiness, DteRequirement, FolioAuthorization, Invoice, InvoiceLine, RcvComparisonRow, ReceivedTaxDocument, TaxDocument, TaxDocumentEvent } from "@zyteron/contracts";
import { documentLabel, InvoiceService } from "./finance.billing.js";
import { FinanceContext } from "./finance.core.js";
import { type CafData, DteCertificateProvider, type DteDocumentInput, type DteStatus, ExternalCertifiedDteProvider, parseCaf, parseReceivedXml, SiiDirectDteProvider, structuralErrors, type TaxDocumentProvider } from "./finance.dte-providers.js";
import { parseCsv, readXlsx } from "./finance.formats.js";
import type { PageQuery } from "./finance.repository.js";
import { daysBetween, decryptSecret, encryptionConfigured, encryptSecret, type FinanceActor, formatRut, guarded, isoDate, money, normalizeRut, nowIso, oneOf, optionalText, r2, requiredText, requireRut, type Row, sha256, todayCl, validRut } from "./finance.util.js";

export interface UploadedFile { fileName:string; contentBase64:string; mimeType?:string; }
export function decodeUpload(file:unknown,label:string,maxBytes=10*1024*1024){const value=file as UploadedFile|undefined;if(!value?.contentBase64||!value.fileName)throw new BadRequestException(`${label}: adjunta el archivo.`);const bytes=Buffer.from(value.contentBase64,"base64");if(!bytes.length)throw new BadRequestException(`${label}: archivo vacío.`);if(bytes.length>maxBytes)throw new BadRequestException(`${label}: excede ${Math.round(maxBytes/1048576)} MB.`);return{bytes,fileName:value.fileName.replace(/[^\w.\- ]+/g,"_").slice(0,120),mimeType:value.mimeType||"application/octet-stream",sha256:sha256(bytes)};}
const alertDays=[60,30,15,7,3,1];

@Injectable()
export class DteService {
  constructor(private readonly ctx:FinanceContext,private readonly invoices:InvoiceService,private readonly sii:SiiDirectDteProvider,private readonly external:ExternalCertifiedDteProvider,private readonly certificates:DteCertificateProvider){}
  private get repo(){return this.ctx.repo;}
  private provider(name:string):TaxDocumentProvider|null{return name==="SII_DIRECT"?this.sii:name==="EXTERNAL"?this.external:null;}

  // ---------------------------------------------------------------------------------- preparación (requisitos explícitos; nunca un botón habilitado sin ellos)
  async readiness(invoiceId?:string,actor?:FinanceActor):Promise<DteReadiness>{
    const settings=await this.repo.settings();const requirements:DteRequirement[]=[];const add=(key:string,label:string,satisfied:boolean,detail:string)=>requirements.push({key,label,satisfied,detail});
    add("provider","Proveedor DTE configurado",settings.dteProvider!=="NONE",settings.dteProvider==="NONE"?"Selecciona integración directa SII o proveedor certificado en Configuración contable.":settings.dteProvider==="SII_DIRECT"?"Integración directa con servicios oficiales del SII.":"Proveedor de facturación electrónica certificado.");
    const company=this.companyMissing(settings);add("company","Datos del emisor completos",!company.length,company.length?`Falta: ${company.join(", ")}.`:`${settings.companyLegalName} · ${settings.companyRut}`);
    add("resolution","Resolución SII (número y fecha)",Boolean(settings.dteResolutionDate&&settings.dteResolutionNumber!==null&&settings.dteResolutionNumber!==undefined),settings.dteResolutionDate?`Resolución N° ${settings.dteResolutionNumber} del ${String(settings.dteResolutionDate).split("-").reverse().join("-")}`:"Registra la resolución de autorización (en certificación: número 0 y fecha de postulación).");
    const production=settings.dteEnvironment==="PRODUCTION";add("environment",production?"Autorización de producción del SII":"Ambiente de certificación",!production||Boolean(settings.dteProductionAuthorized),production?(settings.dteProductionAuthorized?"Producción autorizada.":"Completa set de pruebas, simulación, intercambio, muestras y declaración de cumplimiento antes de producción."):"Ambiente de certificación (maullin.sii.cl): los documentos no tienen validez tributaria.");
    const provider=this.provider(settings.dteProvider);if(provider)requirements.push(...await provider.requirements(settings.dteEnvironment,33));
    if(settings.dteProvider==="SII_DIRECT"){const certificates=await this.repo.list<Row>("dte_certificates",{status:"ACTIVE"});const valid=certificates.find((c)=>Date.parse(c.expiresAt)>Date.now());add("certificate_registry","Certificado registrado y vigente",Boolean(valid),valid?`${valid.label}: vence el ${String(valid.expiresAt).slice(0,10).split("-").reverse().join("-")}`:"Registra los metadatos del certificado desde el secreto del servidor.");}
    let invoice:Invoice|undefined;
    if(invoiceId){invoice=await this.ctx.must<Invoice>("invoices",invoiceId,"Factura");const type=await this.repo.get<Row>("tax_document_types",invoice.documentTypeCode);add("document_type",`Tipo ${invoice.documentTypeCode} habilitado para emisión`,Boolean(type?.enabledForIssue&&(!production||type?.certified)),type?.enabledForIssue?(production&&!type.certified?"El tipo no está certificado para producción.":"Habilitado."):"Habilítalo en Configuración contable una vez certificado.");
      if(settings.dteProvider==="SII_DIRECT"){const available=await this.repo.count("tax_folios",{documentTypeCode:invoice.documentTypeCode,environment:settings.dteEnvironment,status:"AVAILABLE"});add("folios",`Folios CAF disponibles (tipo ${invoice.documentTypeCode})`,available>0,available>0?`${available} folios disponibles.`:"Carga un CAF vigente descargado desde el SII.");}
      add("status","Factura aprobada y lista para emitir",invoice.status==="READY_TO_ISSUE",invoice.status==="READY_TO_ISSUE"?"Lista.":invoice.status==="PENDING_APPROVAL"?"Pendiente de aprobación.":`Estado actual: ${invoice.status}.`);
      const client=await this.ctx.sources.client(invoice.clientId);const receiver=[!validRut(client?.billingRut||client?.rut)&&"RUT válido",!(client?.billingLegalName||client?.legalName)&&"razón social",[33,56,61].includes(invoice.documentTypeCode)&&!(client?.billingActivity||client?.businessActivity)&&"giro",[33,56,61].includes(invoice.documentTypeCode)&&!(client?.billingAddress||client?.address)&&"dirección",[33,56,61].includes(invoice.documentTypeCode)&&!client?.commune&&"comuna"].filter(Boolean) as string[];
      add("receiver","Datos tributarios del receptor",!receiver.length,receiver.length?`Completa en la ficha del cliente: ${receiver.join(", ")}.`:"Completos.");
      if(invoice.referenceInvoiceId){const reference=await this.repo.get<Invoice>("invoices",invoice.referenceInvoiceId);const refDoc=reference?.taxDocumentId?await this.repo.get<TaxDocument>("tax_documents",reference.taxDocumentId):undefined;add("reference","Documento referenciado con folio",Boolean(refDoc?.folio),refDoc?.folio?`Referencia folio ${refDoc.folio}.`:"El documento original no tiene folio emitido.");}
    }
    const missing=requirements.filter((r)=>!r.satisfied).map((r)=>`${r.label}: ${r.detail}`);void actor;return{canIssue:!missing.length&&Boolean(invoiceId),provider:settings.dteProvider,environment:settings.dteEnvironment,requirements,missing};
  }
  private companyMissing(settings:Row){return[!validRut(settings.companyRut)&&"RUT",!settings.companyLegalName&&"razón social",!settings.companyBusinessActivity&&"giro",!settings.companyActivityCode&&"código de actividad (Acteco)",!settings.companyAddress&&"dirección",!settings.companyCommune&&"comuna"].filter(Boolean) as string[];}

  // ---------------------------------------------------------------------------------- emisión
  private async buildInput(invoice:Invoice,taxDocumentId:string,folio:number,caf:CafData|null,environment:"CERTIFICATION"|"PRODUCTION"):Promise<DteDocumentInput>{
    const settings=await this.repo.settings();const lines=await this.repo.list<InvoiceLine>("invoice_lines",{invoiceId:invoice.id},{order:"lineNumber",ascending:true});let reference:DteDocumentInput["reference"]=null;
    if(invoice.referenceInvoiceId){const original=(await this.repo.get<Invoice>("invoices",invoice.referenceInvoiceId))!;const doc=(await this.repo.get<TaxDocument>("tax_documents",original.taxDocumentId!))!;reference={documentTypeCode:original.documentTypeCode,folio:Number(doc.folio),date:original.issueDate!,code:invoice.referenceCode??3,reason:invoice.referenceReason??"Corrección"};}
    const s=invoice.clientSnapshot;return{taxDocumentId,documentTypeCode:invoice.documentTypeCode,folio,issueDate:invoice.issueDate!,dueDate:invoice.dueDate,environment,company:{rut:settings.companyRut!,legalName:settings.companyLegalName,businessActivity:settings.companyBusinessActivity!,activityCode:Number(settings.companyActivityCode),address:settings.companyAddress!,commune:settings.companyCommune!,city:settings.companyCity,resolutionNumber:Number(settings.dteResolutionNumber??0),resolutionDate:String(settings.dteResolutionDate??"")},receiver:{rut:s.rut??"",legalName:s.legalName??"",businessActivity:s.businessActivity??null,address:s.address??null,commune:s.commune??null,city:s.city??null,email:s.dteEmail??null},lines:lines.map((l)=>({lineNumber:l.lineNumber,description:l.description,quantity:Number(l.quantity),unitPrice:Number(l.unitPrice),discountAmount:Number(l.discountAmount),netAmount:Number(l.netAmount),isExempt:l.isExempt})),totals:{net:invoice.netAmount,exempt:invoice.exemptAmount,taxRate:invoice.taxRate,tax:invoice.taxAmount,total:invoice.totalAmount},reference,caf};
  }
  private async log(taxDocumentId:string,status:string,message:string,actor:FinanceActor,detail:Row={},code:string|null=null){await this.repo.create("tax_document_events",{taxDocumentId,status,code,message,detail,actorId:actor.userId,occurredAt:nowIso()});}
  private async store(path:string,content:string|Buffer,mime="application/xml"){const bytes=Buffer.isBuffer(content)?content:Buffer.from(content,"latin1");await this.repo.saveFile("finance-documents",path,bytes,mime);return{path,sha:sha256(bytes)};}
  private async cafFor(type:number,environment:string,folio:number):Promise<CafData>{const authorization=(await this.repo.list<Row>("tax_folio_authorizations",{documentTypeCode:type,environment,status:"ACTIVE"})).find((a)=>folio>=a.rangeFrom&&folio<=a.rangeTo);if(!authorization)throw new UnprocessableEntityException("No se encontró el CAF del folio reservado.");const encrypted=await this.repo.readFile("finance-secrets",authorization.cafStoragePath);if(!encrypted)throw new UnprocessableEntityException("El archivo CAF no está disponible en el almacenamiento privado.");return parseCaf(decryptSecret(encrypted.toString("utf8")));}

  async issue(invoiceId:string,actor:FinanceActor){
    this.ctx.requireAny(actor,"dte.issue","invoice.issue");const readiness=await this.readiness(invoiceId);if(!readiness.canIssue)throw new ConflictException({message:"No se puede emitir el DTE: faltan requisitos.",missing:readiness.missing});
    const settings=await this.repo.settings();const environment=settings.dteEnvironment as "CERTIFICATION"|"PRODUCTION";const provider=this.provider(settings.dteProvider)!;
    let invoice=await this.invoices.prepareForIssue(invoiceId,todayCl());
    const pre=structuralErrors({...(await this.buildInput(invoice,"pending",1,null,environment)),caf:null});if(pre.length)throw new UnprocessableEntityException({message:"El documento no cumple el formato SII.",errors:pre});
    const existing=(await this.repo.list<TaxDocument>("tax_documents",{invoiceId,status:{notIn:["REJECTED","CANCELLED"]}}))[0];if(existing&&!["DRAFT","VALIDATED","SIGNED"].includes(existing.status))throw new ConflictException(`El documento ya fue enviado (estado ${existing.status}).`);
    const taxDocument=existing??await guarded(()=>this.repo.create<TaxDocument>("tax_documents",{invoiceId,documentTypeCode:invoice.documentTypeCode,folio:null,provider:provider.name,environment,status:"DRAFT",emitterRut:settings.companyRut,receiverRut:invoice.clientSnapshot.rut??null,issueDate:invoice.issueDate,netAmount:invoice.netAmount,exemptAmount:invoice.exemptAmount,taxAmount:invoice.taxAmount,totalAmount:invoice.totalAmount,createdBy:actor.userId}));
    invoice=await this.repo.update<Invoice>("invoices",invoiceId,{status:"ISSUING",taxDocumentId:taxDocument.id});await this.log(taxDocument.id,"DRAFT","Emisión iniciada",actor);
    const base=`dte/${environment.toLowerCase()}/${invoice.documentTypeCode}`;
    try{
      if(provider.name==="SII_DIRECT"){
        const folio=await guarded(()=>this.repo.reserveFolio(invoice.documentTypeCode,environment,taxDocument.id));const caf=await this.cafFor(invoice.documentTypeCode,environment,folio);const input=await this.buildInput(invoice,taxDocument.id,folio,caf,environment);
        const unsigned=await provider.createDraft(input);const errors=await provider.validate(unsigned,input);if(errors.length){await this.log(taxDocument.id,"DRAFT","Validación fallida",actor,{errors});throw new UnprocessableEntityException({message:"Validación del DTE fallida.",errors});}
        const u=await this.store(`${base}/${folio}/unsigned.xml`,unsigned);await this.repo.update("tax_documents",taxDocument.id,{status:"VALIDATED",xmlUnsignedPath:u.path,xmlUnsignedSha256:u.sha});await this.log(taxDocument.id,"VALIDATED","XML generado y validado estructuralmente",actor,{folio});
        const signed=await provider.sign(unsigned,input);const s=await this.store(`${base}/${folio}/signed.xml`,this.sii.standalone(signed));await this.repo.update("tax_documents",taxDocument.id,{status:"SIGNED",xmlSignedPath:s.path,xmlSignedSha256:s.sha});await this.log(taxDocument.id,"SIGNED","Documento firmado con el certificado del servidor",actor,{sha256:s.sha});
        const{trackId,envelopeXml}=await provider.send(signed,input);const envelope=envelopeXml?await this.store(`${base}/${folio}/envio.xml`,envelopeXml):null;
        const folioRow=await this.repo.findOne<Row>("tax_folios",{taxDocumentId:taxDocument.id});if(folioRow)await this.repo.update("tax_folios",folioRow.id,{status:"USED",usedAt:nowIso()});
        await this.repo.update("tax_documents",taxDocument.id,{status:"SUBMITTED",trackId,submittedAt:nowIso(),responsePath:envelope?.path??null,statusMessage:"Envío recibido por el SII; pendiente de validación."});await this.log(taxDocument.id,"SUBMITTED",`Track ID ${trackId}`,actor,{trackId});
      }else{
        const input=await this.buildInput(invoice,taxDocument.id,0,null,environment);const result=await provider.issue(input);
        const xml=result.signedXml?await this.store(`${base}/${result.folio??taxDocument.id}/signed.xml`,result.signedXml):null;const pdf=result.pdf?await this.store(`${base}/${result.folio??taxDocument.id}/documento.pdf`,result.pdf,"application/pdf"):null;
        await this.repo.update("tax_documents",taxDocument.id,{folio:result.folio??null,status:result.status,trackId:result.trackId,submissionId:result.submissionId,submittedAt:nowIso(),statusMessage:result.message,xmlSignedPath:xml?.path??null,xmlSignedSha256:xml?.sha??null,pdfPath:pdf?.path??null});await this.log(taxDocument.id,result.status,result.message,actor,{submissionId:result.submissionId});
        if(result.status==="ACCEPTED"||result.status==="ACCEPTED_WITH_REPAIRS"||result.status==="REJECTED")await this.apply(taxDocument.id,{status:result.status,code:null,message:result.message,detail:{}},actor);
      }
    }catch(error){await this.log(taxDocument.id,"ERROR",String((error as Error).message).slice(0,500),actor);const current=await this.repo.get<TaxDocument>("tax_documents",taxDocument.id);if(current&&["DRAFT","VALIDATED","SIGNED"].includes(current.status))await this.repo.update("invoices",invoiceId,{status:"READY_TO_ISSUE"});throw error;}
    await this.repo.audit(actor,"DTE_SUBMITTED","TAX_DOCUMENT",taxDocument.id,`${documentLabel(invoice)} enviada (${provider.name}, ${environment})`);return this.document(taxDocument.id,actor);
  }
  /** Aplica la respuesta oficial. Un rechazo nunca deja la factura como emitida. */
  private async apply(taxDocumentId:string,status:DteStatus,actor:FinanceActor){
    const doc=(await this.repo.get<TaxDocument>("tax_documents",taxDocumentId))!;const invoice=(await this.repo.get<Invoice>("invoices",doc.invoiceId))!;const now=nowIso();
    await this.repo.update("tax_documents",taxDocumentId,{status:status.status,statusCode:status.code,statusMessage:status.message,lastCheckedAt:now,acceptedAt:status.status.startsWith("ACCEPTED")?now:doc.acceptedAt,rejectedAt:status.status==="REJECTED"?now:doc.rejectedAt});if(status.status!==doc.status)await this.log(taxDocumentId,status.status,status.message,actor,status.detail,status.code);
    if(status.status==="ACCEPTED"||status.status==="ACCEPTED_WITH_REPAIRS"){await this.invoices.markIssued(invoice.id,taxDocumentId,doc.folio,actor);await this.repo.notify({eventKey:`dte-accepted:${taxDocumentId}`,type:"DTE_ACCEPTED",title:`${documentLabel(invoice,doc.folio)} aceptada por el SII`,body:status.status==="ACCEPTED_WITH_REPAIRS"?`Con reparos: ${status.message}`:null,entityType:"TAX_DOCUMENT",entityId:taxDocumentId,href:`/finance/tax-documents?document=${taxDocumentId}`,severity:status.status==="ACCEPTED"?"INFO":"WARNING"});}
    if(status.status==="REJECTED"&&doc.status!=="REJECTED"){await this.repo.update("invoices",invoice.id,{status:"READY_TO_ISSUE",taxDocumentId:null});await this.repo.event({aggregateType:"TAX_DOCUMENT",aggregateId:taxDocumentId,eventType:"DTE_REJECTED",actorId:actor.userId,clientId:invoice.clientId,title:`${documentLabel(invoice,doc.folio)} rechazada por el SII`,payload:{code:status.code,message:status.message}});await this.repo.notify({eventKey:`dte-rejected:${taxDocumentId}`,type:"DTE_REJECTED",title:`${documentLabel(invoice,doc.folio)} rechazada por el SII`,body:status.message,entityType:"TAX_DOCUMENT",entityId:taxDocumentId,href:`/finance/tax-documents?document=${taxDocumentId}`,severity:"CRITICAL"});}
  }
  async refreshStatus(taxDocumentId:string,actor:FinanceActor){
    const doc=await this.ctx.must<TaxDocument>("tax_documents",taxDocumentId,"Documento tributario");if(!["SUBMITTED","RECEIVED_BY_SII"].includes(doc.status))return this.document(taxDocumentId,actor);
    if(doc.statusMessage?.startsWith("Emitido fuera de Zyteron"))throw new ConflictException("Documento emitido externamente: registra la evidencia de aceptación.");
    const provider=this.provider(doc.provider)!;const settings=await this.repo.settings();const status=await provider.getDocumentStatus(doc as unknown as Row,settings.companyRut!);await this.apply(taxDocumentId,status,actor);return this.document(taxDocumentId,actor);
  }
  async pollPending(actor:FinanceActor){const pending=await this.repo.list<TaxDocument>("tax_documents",{status:["SUBMITTED","RECEIVED_BY_SII"]});let checked=0,failed=0;for(const doc of pending){if(doc.statusMessage?.startsWith("Emitido fuera de Zyteron"))continue;try{await this.refreshStatus(doc.id,actor);checked++;}catch{failed++;}}return{checked,failed};}
  /** Abandona un intento no enviado: el folio reservado queda anulado (nunca se reutiliza). */
  async abandon(taxDocumentId:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"dte.manage");const reason=requiredText(body.reason,"Motivo",300);const doc=await this.ctx.must<TaxDocument>("tax_documents",taxDocumentId,"Documento tributario");if(!["DRAFT","VALIDATED","SIGNED"].includes(doc.status))throw new ConflictException("Sólo se abandona un DTE no enviado al SII.");
    await this.repo.update("tax_documents",taxDocumentId,{status:"CANCELLED",statusMessage:`Abandonado: ${reason}`});const folio=await this.repo.findOne<Row>("tax_folios",{taxDocumentId});if(folio)await this.repo.update("tax_folios",folio.id,{status:"VOIDED",voidedAt:nowIso(),voidReason:reason});
    await this.repo.update("invoices",doc.invoiceId,{status:"READY_TO_ISSUE",taxDocumentId:null});await this.log(taxDocumentId,"CANCELLED",reason,actor,{folio:doc.folio});await this.repo.audit(actor,"DTE_ABANDONED","TAX_DOCUMENT",taxDocumentId,`Intento de emisión abandonado; folio ${doc.folio??"-"} anulado (informar anulación de folio al SII)`);return this.document(taxDocumentId,actor);
  }
  /** Emisión realizada fuera de Zyteron (portal SII o proveedor) registrada con evidencia verificable. */
  async registerExternal(invoiceId:string,body:Row,actor:FinanceActor){
    this.ctx.requireAny(actor,"dte.issue","invoice.issue");const issueDate=isoDate(body.issueDate,"Fecha de emisión");const folio=Number(body.folio);if(!Number.isInteger(folio)||folio<=0)throw new BadRequestException("Folio inválido.");
    const evidence=decodeUpload(body.evidence,"Evidencia (XML o PDF del DTE)");const settings=await this.repo.settings();const invoice=await this.invoices.prepareForIssue(invoiceId,issueDate);
    if(evidence.fileName.toLowerCase().endsWith(".xml")){const[parsed]=parseReceivedXml(evidence.bytes);const problems=[parsed!.documentTypeCode!==invoice.documentTypeCode&&"tipo de documento",parsed!.folio!==folio&&"folio",settings.companyRut&&normalizeRut(parsed!.issuerRut)!==normalizeRut(settings.companyRut)&&"RUT emisor",normalizeRut(parsed!.receiverRut)!==normalizeRut(invoice.clientSnapshot.rut)&&"RUT receptor",Math.round(parsed!.totalAmount)!==Math.round(invoice.totalAmount)&&`monto total (XML ${money(parsed!.totalAmount)} vs ${money(invoice.totalAmount)})`,parsed!.issueDate!==issueDate&&"fecha"].filter(Boolean);if(problems.length)throw new UnprocessableEntityException(`El XML no coincide con la factura: ${problems.join(", ")}.`);}
    const stored=await this.store(`dte/external/${invoice.documentTypeCode}/${folio}/${evidence.sha256.slice(0,12)}-${evidence.fileName}`,evidence.bytes,evidence.mimeType);
    const doc=await guarded(()=>this.repo.create<TaxDocument>("tax_documents",{invoiceId,documentTypeCode:invoice.documentTypeCode,folio,provider:"EXTERNAL",environment:"PRODUCTION",status:"SUBMITTED",trackId:optionalText(body.trackId,40),submittedAt:nowIso(),statusMessage:"Emitido fuera de Zyteron; aceptación del SII no verificada por Zyteron.",xmlSignedPath:evidence.fileName.toLowerCase().endsWith(".xml")?stored.path:null,xmlSignedSha256:evidence.fileName.toLowerCase().endsWith(".xml")?stored.sha:null,pdfPath:evidence.fileName.toLowerCase().endsWith(".pdf")?stored.path:null,emitterRut:settings.companyRut,receiverRut:invoice.clientSnapshot.rut??null,issueDate,netAmount:invoice.netAmount,exemptAmount:invoice.exemptAmount,taxAmount:invoice.taxAmount,totalAmount:invoice.totalAmount,createdBy:actor.userId}));
    await this.repo.update("invoices",invoiceId,{status:"ISSUING",taxDocumentId:doc.id});await this.log(doc.id,"SUBMITTED","Emisión externa registrada con evidencia",actor,{sha256:stored.sha});await this.invoices.markIssued(invoiceId,doc.id,folio,actor);
    await this.repo.audit(actor,"DTE_EXTERNAL_REGISTERED","TAX_DOCUMENT",doc.id,`Folio ${folio} emitido externamente registrado`,{evidenceSha256:stored.sha});return this.document(doc.id,actor);
  }
  async registerAcceptance(taxDocumentId:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"dte.manage");const doc=await this.ctx.must<TaxDocument>("tax_documents",taxDocumentId,"Documento tributario");if(doc.provider!=="EXTERNAL"||!["SUBMITTED","RECEIVED_BY_SII"].includes(doc.status))throw new ConflictException("Sólo aplica a documentos emitidos externamente pendientes de confirmación.");const evidence=decodeUpload(body.evidence,"Evidencia de aceptación SII");const stored=await this.store(`dte/external/acceptance/${taxDocumentId}-${evidence.fileName}`,evidence.bytes,evidence.mimeType);const accepted=body.status==="ACCEPTED_WITH_REPAIRS"?"ACCEPTED_WITH_REPAIRS":"ACCEPTED";await this.repo.update("tax_documents",taxDocumentId,{status:accepted,acceptedAt:nowIso(),responsePath:stored.path,statusMessage:"Aceptación respaldada con evidencia del SII registrada por usuario."});await this.log(taxDocumentId,accepted,"Evidencia de aceptación registrada",actor,{sha256:stored.sha});await this.repo.audit(actor,"DTE_ACCEPTANCE_EVIDENCE","TAX_DOCUMENT",taxDocumentId,"Evidencia de aceptación SII registrada");return this.document(taxDocumentId,actor);}

  async documents(q:PageQuery&{status?:string;documentTypeCode?:string},actor:FinanceActor){this.ctx.require(actor,"dte.view");return this.repo.page<TaxDocument>("tax_documents",{status:q.status||undefined,documentTypeCode:q.documentTypeCode?Number(q.documentTypeCode):undefined},{...q,order:"createdAt",searchColumns:["trackId","receiverRut"]});}
  async document(id:string,actor:FinanceActor){this.ctx.require(actor,"dte.view");const doc=await this.ctx.must<TaxDocument>("tax_documents",id,"Documento tributario");const[events,invoice]=await Promise.all([this.repo.list<TaxDocumentEvent>("tax_document_events",{taxDocumentId:id},{order:"occurredAt"}),this.repo.get<Invoice>("invoices",doc.invoiceId)]);return{...doc,events,invoice};}
  async download(id:string,kind:"xml"|"pdf",actor:FinanceActor){this.ctx.require(actor,"dte.view");const doc=await this.ctx.must<Row>("tax_documents",id,"Documento tributario");const path=kind==="xml"?doc.xmlSignedPath:doc.pdfPath;if(path){const bytes=await this.repo.readFile("finance-documents",path);if(bytes)return{bytes,fileName:`${doc.documentTypeCode}-${doc.folio??id}.${kind}`,mime:kind==="xml"?"application/xml":"application/pdf"};}
    const provider=this.provider(doc.provider);const bytes=provider?(kind==="xml"?await provider.downloadXml(doc):await provider.downloadPdf(doc)):null;if(!bytes)throw new NotFoundException(kind==="pdf"?"No existe representación impresa con folio y timbre real para este documento.":"XML no disponible.");return{bytes,fileName:`${doc.documentTypeCode}-${doc.folio??id}.${kind}`,mime:kind==="xml"?"application/xml":"application/pdf"};}

  // ---------------------------------------------------------------------------------- certificados y CAF
  async certificatesList(actor:FinanceActor):Promise<DteCertificate[]>{this.ctx.require(actor,"dte.view");return(await this.repo.list<DteCertificate>("dte_certificates",{},{order:"expiresAt"})).map((c)=>({...c,daysRemaining:daysBetween(todayCl(),String(c.expiresAt).slice(0,10))}));}
  async registerCertificate(body:Row,actor:FinanceActor){
    this.ctx.require(actor,"dte.manage");const secretRef=requiredText(body.secretRef,"Referencia del secreto",64);if(!/^[A-Z][A-Z0-9_]{2,63}$/.test(secretRef))throw new BadRequestException("La referencia del secreto debe ser el nombre de una variable de entorno (MAYÚSCULAS_Y_GUIONES).");
    const meta=this.certificates.metadata(secretRef);const created=await guarded(()=>this.repo.create<DteCertificate>("dte_certificates",{label:requiredText(body.label,"Nombre",120),...meta,holderRut:body.holderRut?requireRut(body.holderRut,"RUT del titular"):null,secretRef,status:Date.parse(meta.expiresAt)>Date.now()?"ACTIVE":"EXPIRED",uploadedBy:actor.userId}));
    await this.repo.audit(actor,"DTE_CERTIFICATE_REGISTERED","DTE_CERTIFICATE",created.id,`Certificado ${created.label} registrado (sólo metadatos)`,{fingerprint:meta.fingerprintSha256,secretRef});return created;
  }
  async retireCertificate(id:string,actor:FinanceActor){this.ctx.require(actor,"dte.manage");const updated=await this.repo.update("dte_certificates",id,{status:"RETIRED"});await this.repo.audit(actor,"DTE_CERTIFICATE_RETIRED","DTE_CERTIFICATE",id,"Certificado retirado");return updated;}
  /** Alertas de vencimiento a 60/30/15/7/3/1 días (una por umbral). */
  async certificateAlerts(){let sent=0;for(const cert of await this.repo.list<Row>("dte_certificates",{status:"ACTIVE"})){const days=daysBetween(todayCl(),String(cert.expiresAt).slice(0,10));if(days<=0){await this.repo.update("dte_certificates",cert.id,{status:"EXPIRED"});if(await this.repo.notify({eventKey:`cert-expired:${cert.id}`,type:"DTE_CERTIFICATE_EXPIRED",title:`Certificado ${cert.label} vencido`,body:"La emisión directa de DTE queda bloqueada.",entityType:"DTE_CERTIFICATE",entityId:cert.id,href:"/finance/settings",severity:"CRITICAL"}))sent++;continue;}const threshold=alertDays.filter((t)=>days<=t).sort((a,b)=>a-b)[0];if(threshold&&await this.repo.notify({eventKey:`cert-expiry:${cert.id}:${threshold}`,type:"DTE_CERTIFICATE_EXPIRING",title:`Certificado ${cert.label} vence en ${days} días`,body:`Vence el ${String(cert.expiresAt).slice(0,10).split("-").reverse().join("-")}. Renueva y registra el nuevo certificado.`,entityType:"DTE_CERTIFICATE",entityId:cert.id,href:"/finance/settings",severity:threshold<=7?"CRITICAL":"WARNING"}))sent++;}return{sent};}
  async uploadCaf(body:Row,actor:FinanceActor){
    this.ctx.require(actor,"dte.manage");if(!encryptionConfigured())throw new ConflictException("Configura FINANCE_ENCRYPTION_KEY antes de cargar CAF: contienen la llave privada de timbraje.");const environment=oneOf(body.environment,["CERTIFICATION","PRODUCTION"] as const,"Ambiente");
    const file=decodeUpload(body.file,"Archivo CAF",256*1024);const caf=parseCaf(file.bytes.toString("latin1"));const settings=await this.repo.settings();
    if(!settings.companyRut)throw new ConflictException("Registra el RUT de la empresa antes de cargar CAF.");if(normalizeRut(caf.companyRut)!==normalizeRut(settings.companyRut))throw new UnprocessableEntityException(`El CAF pertenece al RUT ${caf.companyRut}, no a ${settings.companyRut}.`);if(!await this.repo.get("tax_document_types",caf.documentTypeCode))throw new UnprocessableEntityException(`Tipo de documento ${caf.documentTypeCode} no catalogado.`);
    const path=`caf/${environment.toLowerCase()}/${caf.documentTypeCode}/${caf.rangeFrom}-${caf.rangeTo}-${file.sha256.slice(0,12)}.enc`;await this.repo.saveFile("finance-secrets",path,Buffer.from(encryptSecret(file.bytes.toString("latin1")),"utf8"),"application/octet-stream");
    const authorization=await guarded(()=>this.repo.create<Row>("tax_folio_authorizations",{documentTypeCode:caf.documentTypeCode,environment,rangeFrom:caf.rangeFrom,rangeTo:caf.rangeTo,authorizedAt:caf.authorizedAt,cafSha256:file.sha256,cafStoragePath:path,status:"ACTIVE",createdBy:actor.userId}));
    const folios:Row[]=[];for(let folio=caf.rangeFrom;folio<=caf.rangeTo;folio++)folios.push({authorizationId:authorization.id,documentTypeCode:caf.documentTypeCode,environment,folio,status:"AVAILABLE"});for(let i=0;i<folios.length;i+=500)await guarded(()=>this.repo.createMany("tax_folios",folios.slice(i,i+500)));
    await this.repo.audit(actor,"CAF_UPLOADED","FOLIO_AUTHORIZATION",authorization.id,`CAF tipo ${caf.documentTypeCode} folios ${caf.rangeFrom}–${caf.rangeTo} (${environment})`,{sha256:file.sha256});return authorization;
  }
  async folioAuthorizations(actor:FinanceActor):Promise<FolioAuthorization[]>{this.ctx.require(actor,"dte.view");const authorizations=await this.repo.list<Row>("tax_folio_authorizations",{},{order:"createdAt"});const out:FolioAuthorization[]=[];for(const a of authorizations){const count=(status:string)=>this.repo.count("tax_folios",{authorizationId:a.id,status});out.push({id:a.id,documentTypeCode:a.documentTypeCode,environment:a.environment,rangeFrom:a.rangeFrom,rangeTo:a.rangeTo,authorizedAt:a.authorizedAt,status:a.status,available:await count("AVAILABLE"),used:await count("USED"),reserved:await count("RESERVED"),voided:await count("VOIDED")});}return out;}
  documentTypes(){return this.repo.list<Row>("tax_document_types",{},{order:"code",ascending:true});}
  async updateDocumentType(code:number,body:Row,actor:FinanceActor){this.ctx.require(actor,"dte.manage");const patch:Row={};if(body.enabledForIssue!==undefined)patch.enabledForIssue=Boolean(body.enabledForIssue);if(body.certified!==undefined){if(body.certified&&!String(body.notes??"").trim())throw new BadRequestException("Indica la evidencia de certificación SII (resolución / fecha) al marcar como certificado.");patch.certified=Boolean(body.certified);patch.notes=optionalText(body.notes,500);}const updated=await this.repo.update("tax_document_types",code,patch);await this.repo.audit(actor,"DTE_TYPE_UPDATED","TAX_DOCUMENT_TYPE",null,`Tipo ${code} actualizado`,patch);return updated;}
}

// =========================================================================================== DTE recibidos (bandeja de compras)
const creditClasses=["DEL_GIRO","SUPERMERCADO","BIENES_RAICES","ACTIVO_FIJO","USO_COMUN","NO_RECUPERABLE","NO_CORRESPONDE"] as const;
@Injectable()
export class ReceivedDocumentsService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  async list(q:PageQuery&{classification?:string;status?:string;from?:string;to?:string},actor:FinanceActor){this.ctx.requireAny(actor,"dte.view","expense.view");return this.repo.page<ReceivedTaxDocument>("received_tax_documents",{taxCreditClassification:q.classification||undefined,status:q.status||undefined,issueDate:q.from||q.to?{gte:q.from||undefined,lte:q.to||undefined}:undefined},{...q,order:"issueDate",searchColumns:["issuerName","issuerRut"]});}
  async get(id:string,actor:FinanceActor){this.ctx.requireAny(actor,"dte.view","expense.view");return this.ctx.must<ReceivedTaxDocument>("received_tax_documents",id,"Documento recibido");}
  /** Importa EnvioDTE/DTE desde archivo; valida estructura, totales y receptor; detecta duplicados por emisor+tipo+folio. */
  async importXml(body:Row,actor:FinanceActor){
    this.ctx.requireAny(actor,"dte.manage","expense.create");const file=decodeUpload(body.file,"XML del documento",8*1024*1024);const settings=await this.repo.settings();const parsed=parseReceivedXml(file.bytes);
    const path=`received/${file.sha256.slice(0,2)}/${file.sha256}.xml`;await this.repo.saveFile("finance-documents",path,file.bytes,"application/xml").catch(()=>path);const results:Row[]=[];
    for(const doc of parsed){const errors=[...doc.errors];if(settings.companyRut&&normalizeRut(doc.receiverRut)!==normalizeRut(settings.companyRut))errors.push(`El receptor (${doc.receiverRut}) no es la empresa (${settings.companyRut}).`);if(!await this.repo.get("tax_document_types",doc.documentTypeCode))errors.push(`Tipo ${doc.documentTypeCode} no catalogado.`);
      const duplicate=await this.repo.findOne<ReceivedTaxDocument>("received_tax_documents",{issuerRut:doc.issuerRut,documentTypeCode:doc.documentTypeCode,folio:doc.folio});if(duplicate){results.push({folio:doc.folio,issuerRut:doc.issuerRut,result:"DUPLICATE",id:duplicate.id});continue;}
      if(errors.some((e)=>e.includes("no catalogado"))){results.push({folio:doc.folio,issuerRut:doc.issuerRut,result:"REJECTED",errors});continue;}
      const vendor=await this.repo.findOne<Row>("vendors",{rut:doc.issuerRut});
      const created=await guarded(()=>this.repo.create<ReceivedTaxDocument>("received_tax_documents",{issuerRut:doc.issuerRut,issuerName:doc.issuerName,issuerBusinessActivity:doc.issuerBusinessActivity,documentTypeCode:doc.documentTypeCode,folio:doc.folio,issueDate:doc.issueDate,receivedAt:nowIso(),netAmount:doc.netAmount,exemptAmount:doc.exemptAmount,taxAmount:doc.taxAmount,otherTaxes:doc.otherTaxes,totalAmount:doc.totalAmount,docReferences:doc.references,xmlPath:path,xmlSha256:file.sha256,source:body.source==="EMAIL"?"EMAIL":"XML_UPLOAD",signatureStatus:"NOT_VERIFIED",validationErrors:errors,vendorId:vendor?.id??null,status:errors.length?"UNDER_REVIEW":"RECEIVED",taxCreditClassification:"PENDING_REVIEW",taxCreditEligible:null,taxCreditEligibleAmount:null,classificationReason:null,createdBy:actor.userId}));
      results.push({folio:doc.folio,issuerRut:doc.issuerRut,result:"CREATED",id:created.id,errors});}
    await this.repo.audit(actor,"RECEIVED_DTE_IMPORTED","RECEIVED_TAX_DOCUMENT",null,`${results.filter((r)=>r.result==="CREATED").length} documentos importados desde ${file.fileName}`,{sha256:file.sha256,results});return{fileSha256:file.sha256,results};
  }
  /** Clasificación de crédito fiscal explícita: el sistema no presume que el IVA sea recuperable. */
  async classify(id:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"tax.review");const doc=await this.get(id,actor);const classification=oneOf(body.classification,creditClasses,"Clasificación");const reason=requiredText(body.reason,"Fundamento de la clasificación",500);if(typeof body.eligible!=="boolean")throw new BadRequestException("Indica explícitamente si el IVA es crédito fiscal.");
    const eligibleAmount=body.eligible?(body.eligibleAmount===undefined||body.eligibleAmount===null||body.eligibleAmount===""?doc.taxAmount:r2(body.eligibleAmount)):0;if(eligibleAmount<0||eligibleAmount>doc.taxAmount)throw new BadRequestException("El monto de crédito debe estar entre 0 y el IVA del documento.");if(classification==="USO_COMUN"&&body.eligible&&body.eligibleAmount===undefined)throw new BadRequestException("Uso común requiere el monto proporcional de crédito.");
    const updated=await this.repo.update<ReceivedTaxDocument>("received_tax_documents",id,{taxCreditClassification:classification,taxCreditEligible:body.eligible,taxCreditEligibleAmount:eligibleAmount,classificationReason:reason,reviewedBy:actor.userId,reviewedAt:nowIso()});
    if(doc.expenseId){const expense=await this.repo.get<Row>("expenses",doc.expenseId);if(expense&&["DRAFT","PENDING_APPROVAL"].includes(expense.status))await this.repo.update("expenses",doc.expenseId,{taxCreditClassification:classification,taxCreditEligible:body.eligible,eligibleTaxAmount:eligibleAmount,classificationReason:reason,reviewedBy:actor.userId,reviewedAt:nowIso()});}
    await this.repo.audit(actor,"RECEIVED_DTE_CLASSIFIED","RECEIVED_TAX_DOCUMENT",id,`Clasificado ${classification} (crédito ${money(eligibleAmount)})`,{before:doc.taxCreditClassification,reason});return updated;
  }
  /** Estado interno de revisión. El acuse/reclamo formal ante el SII no se automatiza desde aquí. */
  async setStatus(id:string,body:Row,actor:FinanceActor){this.ctx.requireAny(actor,"dte.manage","expense.approve");const status=oneOf(body.status,["UNDER_REVIEW","ACCEPTED","REJECTED","CLAIMED"] as const,"Estado");const reason=status==="ACCEPTED"?optionalText(body.reason):requiredText(body.reason,"Motivo",500);const updated=await this.repo.update("received_tax_documents",id,{status});await this.repo.audit(actor,"RECEIVED_DTE_STATUS","RECEIVED_TAX_DOCUMENT",id,`Estado interno ${status}${reason?`: ${reason}`:""}`);return updated;}
  async linkVendor(id:string,vendorId:string,actor:FinanceActor){this.ctx.requireAny(actor,"dte.manage","expense.create");await this.ctx.must("vendors",vendorId,"Proveedor");return this.repo.update("received_tax_documents",id,{vendorId});}
}

// =========================================================================================== RCV: importación de archivo y conciliación (sin scraping de sii.cl)
const normalizeHeader=(value:string)=>value.normalize("NFD").replace(/[̀-ͯ]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const rcvColumns:Record<string,string[]>={type:["tipo doc","tipo documento","tipo dte"],rut:["rut proveedor","rut cliente","rut contraparte","rut emisor","rut receptor"],name:["razon social"],folio:["folio"],date:["fecha docto","fecha documento","fecha emision"],exempt:["monto exento"],net:["monto neto"],tax:["monto iva recuperable","monto iva"],taxNon:["monto iva no recuperable","iva no recuperable"],total:["monto total"],state:["estado"],purchaseType:["tipo compra"]};
export function parseAmount(value:unknown):number|null{if(value===null||value===undefined)return null;let text=String(value).trim().replace(/\$|\s|CLP/gi,"");if(!text)return null;const negative=/^\(.*\)$/.test(text)||text.startsWith("-");text=text.replace(/[()\-+]/g,"");if(/^\d{1,3}(\.\d{3})+(,\d+)?$/.test(text)||/^\d+,\d+$/.test(text))text=text.replace(/\./g,"").replace(",",".");else if(/^\d{1,3}(,\d{3})+(\.\d+)?$/.test(text))text=text.replace(/,/g,"");const amount=Number(text);return Number.isFinite(amount)?(negative?-amount:amount):null;}
export function parseFlexibleDate(value:unknown):string|null{const text=String(value??"").trim();if(!text)return null;if(/^\d{5}(\.\d+)?$/.test(text)){const date=new Date(Date.UTC(1899,11,30)+Math.floor(Number(text))*86400000);return date.toISOString().slice(0,10);}let m=/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})/.exec(text);if(m)return`${m[3]}-${m[2]!.padStart(2,"0")}-${m[1]!.padStart(2,"0")}`;m=/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})/.exec(text);if(m)return`${m[1]}-${m[2]!.padStart(2,"0")}-${m[3]!.padStart(2,"0")}`;m=/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{2})$/.exec(text);if(m)return`20${m[3]}-${m[2]!.padStart(2,"0")}-${m[1]!.padStart(2,"0")}`;return null;}
@Injectable()
export class RcvService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  imports(actor:FinanceActor){this.ctx.require(actor,"tax.view");return this.repo.list<Row>("rcv_imports",{},{order:"importedAt"});}
  async importFile(body:Row,actor:FinanceActor){
    this.ctx.requireAny(actor,"tax.manage","tax.review");const registerType=oneOf(body.registerType,["COMPRAS","VENTAS"] as const,"Registro");const periodKey=requiredText(body.periodKey,"Período",7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(periodKey))throw new BadRequestException("Período inválido (AAAA-MM).");
    const file=decodeUpload(body.file,"Archivo RCV");const matrix=file.fileName.toLowerCase().endsWith(".xlsx")?readXlsx(file.bytes):parseCsv(file.bytes);if(matrix.length<2)throw new UnprocessableEntityException("El archivo no contiene filas.");
    const headers=matrix[0]!.map(normalizeHeader);const index=Object.fromEntries(Object.entries(rcvColumns).map(([key,names])=>[key,headers.findIndex((h)=>names.some((n)=>h===n||h.startsWith(n)))])) as Record<"type"|"rut"|"name"|"folio"|"date"|"exempt"|"net"|"tax"|"taxNon"|"total"|"state"|"purchaseType",number>;if(index.type<0||index.rut<0||index.folio<0||index.total<0)throw new UnprocessableEntityException("No se reconocen las columnas del RCV (Tipo Doc, RUT, Folio, Monto Total). Usa la exportación CSV oficial del Registro de Compras y Ventas.");
    const imported=await guarded(()=>this.repo.create<Row>("rcv_imports",{registerType,periodKey,fileName:file.fileName,fileSha256:file.sha256,rowsTotal:matrix.length-1,rowsValid:0,rowsInvalid:0,columnMapping:index,errors:[],status:"IMPORTED",importedBy:actor.userId,importedAt:nowIso()}));
    const errors:Row[]=[];let valid=0;const cell=(row:string[],key:keyof typeof index)=>index[key]>=0?row[index[key]]??"":"";
    for(const[n,row]of matrix.slice(1).entries()){const rut=formatRut(cell(row,"rut"));const folio=Number(cell(row,"folio"));const type=Number(cell(row,"type"));const total=parseAmount(cell(row,"total"));if(!validRut(rut)||!folio||!type||total===null){errors.push({row:n+2,error:"Fila incompleta o RUT inválido"});continue;}
      try{await this.repo.create("rcv_entries",{importId:imported.id,registerType,periodKey,counterpartRut:rut,counterpartName:cell(row,"name")||null,documentTypeCode:type,folio,issueDate:parseFlexibleDate(cell(row,"date")),netAmount:parseAmount(cell(row,"net"))??0,exemptAmount:parseAmount(cell(row,"exempt"))??0,taxAmount:parseAmount(cell(row,"tax"))??0,taxNonRecoverable:parseAmount(cell(row,"taxNon"))??0,totalAmount:total,rcvState:cell(row,"state")||null,purchaseType:cell(row,"purchaseType")||null,raw:Object.fromEntries(matrix[0]!.map((h,i)=>[h,row[i]??""])),matchStatus:"REVIEW_REQUIRED",matchedEntityId:null,matchDetail:null});valid++;}catch{errors.push({row:n+2,error:"Documento repetido en el archivo"});}}
    for(const previous of await this.repo.list<Row>("rcv_imports",{registerType,periodKey,status:"IMPORTED"}))if(previous.id!==imported.id)await this.repo.update("rcv_imports",previous.id,{status:"SUPERSEDED"});
    await this.repo.update("rcv_imports",imported.id,{rowsValid:valid,rowsInvalid:errors.length,errors:errors.slice(0,200)});await this.repo.audit(actor,"RCV_IMPORTED","RCV_IMPORT",imported.id,`RCV ${registerType} ${periodKey}: ${valid} filas`,{sha256:file.sha256});
    return{import:{...imported,rowsValid:valid,rowsInvalid:errors.length},comparison:await this.compare(registerType,periodKey,actor)};
  }
  async compare(registerType:"COMPRAS"|"VENTAS",periodKey:string,actor:FinanceActor){
    this.ctx.require(actor,"tax.view");const current=(await this.repo.list<Row>("rcv_imports",{registerType,periodKey,status:"IMPORTED"}))[0];const entries=current?await this.repo.list<Row>("rcv_entries",{importId:current.id}):[];const from=`${periodKey}-01`,to=`${periodKey}-31`;
    const locals=registerType==="COMPRAS"?(await this.repo.list<ReceivedTaxDocument>("received_tax_documents",{issueDate:{gte:from,lte:to}})).map((d)=>({id:d.id,rut:d.issuerRut,name:d.issuerName,type:d.documentTypeCode,folio:Number(d.folio),date:d.issueDate,total:d.totalAmount,tax:d.taxAmount,bad:["REJECTED","CLAIMED"].includes(d.status)}))
      :(await Promise.all((await this.repo.list<TaxDocument>("tax_documents",{issueDate:{gte:from,lte:to},status:{notIn:["CANCELLED","DRAFT"]}})).map(async(d)=>({id:d.id,rut:d.receiverRut??"",name:null as string|null,type:d.documentTypeCode,folio:Number(d.folio),date:d.issueDate,total:Number(d.totalAmount),tax:Number(d.taxAmount??0),bad:d.status==="REJECTED"}))));
    const key=(rut:string,type:number,folio:number)=>`${normalizeRut(rut)}|${type}|${folio}`;const localMap=new Map(locals.map((l)=>[key(l.rut,l.type,l.folio),l]));const seen=new Set<string>();const rows:RcvComparisonRow[]=[];
    for(const entry of entries){const k=key(entry.counterpartRut,entry.documentTypeCode,Number(entry.folio));seen.add(k);const local=localMap.get(k);let status:RcvComparisonRow["status"],detail:string;
      if(!local){status="MISSING_LOCAL";detail="Está en el RCV del SII pero no en Zyteron.";}else if(local.bad){status="STATUS_MISMATCH";detail="En Zyteron figura rechazado/reclamado y el SII lo registra.";}else if(Math.round(local.total)!==Math.round(entry.totalAmount)||Math.round(local.tax)!==Math.round(entry.taxAmount)){status="AMOUNT_MISMATCH";detail=`Total SII ${money(entry.totalAmount)} vs Zyteron ${money(local.total)}; IVA SII ${money(entry.taxAmount)} vs ${money(local.tax)}.`;}else{status="MATCHED";detail="Coincide.";}
      await this.repo.update("rcv_entries",entry.id,{matchStatus:status,matchedEntityId:local?.id??null,matchDetail:detail});rows.push({key:k,registerType,counterpartRut:entry.counterpartRut,counterpartName:entry.counterpartName,documentTypeCode:entry.documentTypeCode,folio:Number(entry.folio),issueDate:entry.issueDate,siiTotal:entry.totalAmount,localTotal:local?.total??null,siiTax:entry.taxAmount,localTax:local?.tax??null,status,detail,localId:local?.id??null,rcvEntryId:entry.id});}
    if(current)for(const local of locals){const k=key(local.rut,local.type,local.folio);if(seen.has(k))continue;rows.push({key:k,registerType,counterpartRut:local.rut,counterpartName:local.name,documentTypeCode:local.type,folio:local.folio,issueDate:local.date,siiTotal:null,localTotal:local.total,siiTax:null,localTax:local.tax,status:local.bad?"STATUS_MISMATCH":"MISSING_SII",detail:local.bad?"Rechazado en Zyteron y ausente del RCV.":"Registrado en Zyteron pero ausente del RCV del SII.",localId:local.id,rcvEntryId:null});}
    const summary=Object.fromEntries(["MATCHED","MISSING_LOCAL","MISSING_SII","AMOUNT_MISMATCH","STATUS_MISMATCH","REVIEW_REQUIRED"].map((s)=>[s,rows.filter((r)=>r.status===s).length]));
    return{registerType,periodKey,importId:current?.id??null,importedAt:current?.importedAt??null,rows,summary,notice:current?null:"Sin archivo RCV importado para el período: descarga el CSV oficial del Registro de Compras y Ventas en sii.cl e impórtalo."};
  }
}
