import { BadRequestException, ForbiddenException, Injectable } from "@nestjs/common";
import { scopeOf } from "./finance.access.js";
import { FinanceContext } from "./finance.core.js";
import { DteSchemaValidator } from "./finance.dte-providers.js";
import { type FinanceActor, isoDate, nonNegative, nowIso, oneOf, optionalText, optionalUuid, positiveAmount, requiredText, requiredUuid, requireRut, type Row } from "./finance.util.js";

/** Configuración contable y catálogos auxiliares (empresa, DTE, tolerancias, tarifas de costo, costos programados, escenarios). */
@Injectable()
export class FinanceSettingsService {
  constructor(private readonly ctx:FinanceContext,private readonly dteSchema:DteSchemaValidator){}
  private get repo(){return this.ctx.repo;}
  scope(actor:FinanceActor){return scopeOf(actor);}
  async get(actor:FinanceActor){this.ctx.requireAny(actor,"finance.dashboard.view","invoice.view");const settings=await this.repo.settings();return{...settings,integrations:{supabase:this.repo.configured(),encryption:Boolean(process.env.FINANCE_ENCRYPTION_KEY),mercadoPago:Boolean(process.env.MERCADOPAGO_ACCESS_TOKEN&&process.env.MERCADOPAGO_PUBLIC_KEY&&process.env.MERCADOPAGO_WEBHOOK_SECRET),resend:Boolean(process.env.RESEND_API_KEY&&(process.env.FINANCE_MAIL_FROM||process.env.SALES_MAIL_FROM)),externalDte:Boolean(process.env.DTE_PROVIDER_URL&&process.env.DTE_PROVIDER_API_KEY),xsd:this.dteSchema.available()}};}
  async update(body:Row,actor:FinanceActor){
    this.ctx.require(actor,"finance.settings.manage");const patch:Row={};const text=(key:string,max=200)=>{if(body[key]!==undefined)patch[key]=optionalText(body[key],max);};
    for(const key of ["companyLegalName","companyBusinessActivity","companyAddress","companyCommune","companyCity","companyEmail"])text(key);
    if(body.companyRut!==undefined)patch.companyRut=body.companyRut?requireRut(body.companyRut,"RUT de la empresa"):null;if(body.companyActivityCode!==undefined)patch.companyActivityCode=body.companyActivityCode?Number(body.companyActivityCode):null;
    if(body.invoiceRequiresApproval!==undefined)patch.invoiceRequiresApproval=Boolean(body.invoiceRequiresApproval);if(body.invoiceApprovalThreshold!==undefined)patch.invoiceApprovalThreshold=body.invoiceApprovalThreshold===null||body.invoiceApprovalThreshold===""?null:nonNegative(body.invoiceApprovalThreshold,"Umbral");
    if(body.defaultPaymentTermsDays!==undefined)patch.defaultPaymentTermsDays=Math.max(0,Math.min(365,Number(body.defaultPaymentTermsDays)||0));for(const key of ["autoCreateBillingDrafts","autoMatchEnabled","collectionRemindersEnabled","onlinePaymentsEnabled"])if(body[key]!==undefined)patch[key]=Boolean(body[key]);
    if(body.reconciliationDateToleranceDays!==undefined)patch.reconciliationDateToleranceDays=Math.max(0,Math.min(30,Number(body.reconciliationDateToleranceDays)||0));if(body.reconciliationAmountTolerance!==undefined)patch.reconciliationAmountTolerance=nonNegative(body.reconciliationAmountTolerance,"Tolerancia");if(body.clientConcentrationThreshold!==undefined)patch.clientConcentrationThreshold=Math.max(1,Math.min(100,Number(body.clientConcentrationThreshold)||30));
    if(body.dteProvider!==undefined)patch.dteProvider=oneOf(body.dteProvider,["NONE","SII_DIRECT","EXTERNAL"] as const,"Proveedor DTE");if(body.dteEnvironment!==undefined)patch.dteEnvironment=oneOf(body.dteEnvironment,["CERTIFICATION","PRODUCTION"] as const,"Ambiente DTE");
    if(body.dteResolutionNumber!==undefined)patch.dteResolutionNumber=body.dteResolutionNumber===""||body.dteResolutionNumber===null?null:Math.max(0,Number(body.dteResolutionNumber)||0);if(body.dteResolutionDate!==undefined)patch.dteResolutionDate=body.dteResolutionDate?isoDate(body.dteResolutionDate,"Fecha de resolución"):null;
    if(body.dteProductionAuthorized!==undefined){if(actor.role!=="GERENTE_GENERAL")throw new ForbiddenException("Sólo Gerencia declara la autorización de producción del SII.");if(body.dteProductionAuthorized&&!String(body.productionEvidence??"").trim())throw new BadRequestException("Indica la evidencia de autorización del SII (resolución y fecha).");patch.dteProductionAuthorized=Boolean(body.dteProductionAuthorized);}
    const before=await this.repo.settings();const updated=await this.repo.updateSettings({...patch,updatedBy:actor.userId});await this.repo.audit(actor,"FINANCE_SETTINGS_UPDATED","FINANCE_SETTINGS",null,"Configuración contable actualizada",{changes:Object.fromEntries(Object.keys(patch).map((k)=>[k,{from:before[k],to:patch[k]}])),productionEvidence:body.productionEvidence??null});return updated;
  }
  async catalogs(actor:FinanceActor){this.ctx.requireAny(actor,"finance.dashboard.view","invoice.view");const[costCenters,categories,documentTypes,scenarios,checklist]=await Promise.all([this.repo.list<Row>("cost_centers",{},{order:"code",ascending:true}),this.repo.list<Row>("expense_categories",{},{order:"code",ascending:true}),this.repo.list<Row>("tax_document_types",{},{order:"code",ascending:true}),this.repo.list<Row>("forecast_scenarios",{},{order:"code",ascending:true}),this.repo.list<Row>("close_checklist_items",{},{order:"sortOrder",ascending:true})]);return{costCenters,categories,documentTypes,scenarios,checklist,accounts:await this.ctx.accounts()};}
  costRates(actor:FinanceActor){this.ctx.require(actor,"accounting.view");return this.repo.list<Row>("cost_rates",{},{order:"effectiveFrom"});}
  async addCostRate(body:Row,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const from=isoDate(body.effectiveFrom,"Vigencia desde");const userId=requiredUuid(body.userId,"Usuario");const overlapping=(await this.repo.list<Row>("cost_rates",{userId})).filter((r)=>!r.effectiveTo||r.effectiveTo>=from);for(const r of overlapping)if(r.effectiveFrom<from)await this.repo.update("cost_rates",r.id,{effectiveTo:new Date(Date.parse(`${from}T00:00:00Z`)-86400000).toISOString().slice(0,10)});else throw new BadRequestException("Ya existe una tarifa vigente desde esa fecha o posterior.");const created=await this.repo.create("cost_rates",{userId,hourlyCost:positiveAmount(body.hourlyCost,"Costo hora"),currency:"CLP",effectiveFrom:from,effectiveTo:body.effectiveTo?isoDate(body.effectiveTo,"Vigencia hasta"):null,createdBy:actor.userId});await this.repo.audit(actor,"COST_RATE_CREATED","COST_RATE",(created as Row).id,"Tarifa de costo registrada",{userId,from});return created;}
  scheduledCosts(actor:FinanceActor){this.ctx.require(actor,"report.finance.view");return this.repo.list<Row>("scheduled_costs",{},{order:"nextDate",ascending:true});}
  async saveScheduledCost(id:string|null,body:Row,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const data={name:requiredText(body.name,"Nombre",160),categoryId:optionalUuid(body.categoryId,"Categoría"),vendorId:optionalUuid(body.vendorId,"Proveedor"),amount:positiveAmount(body.amount,"Monto"),currency:"CLP",frequency:oneOf(body.frequency,["MONTHLY","QUARTERLY","ANNUAL","ONE_TIME"] as const,"Frecuencia"),nextDate:isoDate(body.nextDate,"Próxima fecha"),endDate:body.endDate?isoDate(body.endDate,"Término"):null,costCenterId:optionalUuid(body.costCenterId,"Centro de costo"),active:body.active!==false};const saved=id?await this.repo.update("scheduled_costs",id,data):await this.repo.create("scheduled_costs",{...data,createdBy:actor.userId});await this.repo.audit(actor,"SCHEDULED_COST_SAVED","SCHEDULED_COST",(saved as Row).id,`Costo programado ${data.name}`);return saved;}
  async updateScenario(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const patch:Row={};if(body.collectionFactors!==undefined){const factors=body.collectionFactors as Row;for(const key of ["CURRENT","D1_30","D31_60","D61_90","D90_PLUS"]){const value=Number(factors?.[key]);if(!(value>=0&&value<=1))throw new BadRequestException(`Factor ${key} debe estar entre 0 y 1.`);}patch.collectionFactors=factors;}for(const key of ["recurringFactor","expenseFactor"])if(body[key]!==undefined){const value=Number(body[key]);if(!(value>=0&&value<=2))throw new BadRequestException(`${key} fuera de rango.`);patch[key]=value;}if(body.description!==undefined)patch.description=optionalText(body.description,500);const updated=await this.repo.update("forecast_scenarios",id,patch);await this.repo.audit(actor,"FORECAST_SCENARIO_UPDATED","FORECAST_SCENARIO",id,"Supuestos de proyección actualizados",patch);return updated;}
  /** Selector de clientes para Finanzas (sin exponer el módulo Clientes completo); respeta el alcance de la ejecutiva. */
  async clientOptions(actor:FinanceActor,search?:string){this.ctx.requireAny(actor,"invoice.view","receivable.view");const allowed=await this.ctx.clientFilter(actor);const needle=search?.trim().toLowerCase();return(await this.ctx.sources.clientsList()).filter((c)=>(!allowed||allowed.includes(c.id))&&(!needle||[c.legalName,c.tradeName,c.rut].some((v)=>v?.toLowerCase().includes(needle)))).slice(0,50).map((c)=>({id:c.id,name:c.tradeName||c.legalName,legalName:c.billingLegalName||c.legalName,rut:c.billingRut||c.rut,dteEmail:c.dteEmail,complete:Boolean((c.billingActivity||c.businessActivity)&&(c.billingAddress||c.address)&&c.commune)}));}
  async projectOptions(actor:FinanceActor){this.ctx.requireAny(actor,"invoice.view","accounting.view");const allowed=await this.ctx.clientFilter(actor);return(await this.ctx.sources.projects()).filter((p)=>!allowed||(p.clientId&&allowed.includes(p.clientId))).map((p)=>({id:p.id,name:p.name,projectNumber:p.projectNumber,clientId:p.clientId}));}
  async notifications(actor:FinanceActor){const own=actor.userId?await this.repo.list<Row>("finance_notifications",{userId:actor.userId},{order:"createdAt",limit:50}):[];const role=actor.role?await this.repo.list<Row>("finance_notifications",{audienceRole:actor.role},{order:"createdAt",limit:50}):[];return[...own,...role].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,60);}
  async markRead(id:string,actor:FinanceActor){const item=await this.ctx.must<Row>("finance_notifications",id,"Notificación");if(item.userId!==actor.userId&&item.audienceRole!==actor.role)throw new ForbiddenException("Notificación ajena.");return this.repo.update("finance_notifications",id,{readAt:nowIso()});}
  async activity(actor:FinanceActor,clientId?:string){this.ctx.require(actor,"finance.dashboard.view");return this.repo.list<Row>("finance_events",{clientId:clientId||undefined},{order:"occurredAt",limit:80});}
  async audit(actor:FinanceActor,q:{entityType?:string;entityId?:string}){if(!["GERENTE_GENERAL","FINANZAS"].includes(actor.role))throw new ForbiddenException("La auditoría financiera es visible para Gerencia y Finanzas.");return this.repo.list<Row>("finance_audit_events",{entityType:q.entityType||undefined,entityId:q.entityId||undefined},{order:"occurredAt",limit:200});}
}
