import { ConflictException, ForbiddenException, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { createHash, createHmac, createVerify, generateKeyPairSync } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import { financeRoleMatrix } from "./finance.access.js";
import { BankService, detectMapping, ReconciliationService, StatementImportService } from "./finance.banking.js";
import { BillingScheduleService, InvoiceService } from "./finance.billing.js";
import { BudgetService, CloseService, CommissionFinanceService, TaxService } from "./finance.close.js";
import { FinanceContext } from "./finance.core.js";
import { DteCertificateProvider, DteSchemaValidator, ExternalCertifiedDteProvider, parseCaf, siiSoapEnvelope, SiiDirectDteProvider, structuralErrors, xmlSignature, type DteDocumentInput } from "./finance.dte-providers.js";
import { DteService, parseAmount, parseFlexibleDate, RcvService, ReceivedDocumentsService } from "./finance.dte.js";
import { parseCsv, parseXml, readXlsx, writeCsv, writeXlsx } from "./finance.formats.js";
import { AccountingRuleEngine, LedgerService, StatementsService } from "./finance.ledger.js";
import { ApprovalService, ExpenseService, PayableService, VendorService } from "./finance.payables.js";
import { agingReport, CollectionsService, MercadoPagoPaymentProvider, OnlinePaymentService, PaymentService } from "./finance.payments.js";
import { FinanceRepository } from "./finance.repository.js";
import { AnalyticsService, CopilotService, parseQuestionPeriod, ReportsService } from "./finance.reports.js";
import { seedAccounts, seedRules } from "./finance.seed.js";
import { FinanceSources, type SourceClient } from "./finance.sources.js";
import { addDays, type FinanceActor, formatRut, sha256, todayCl, validRut } from "./finance.util.js";

const sql=readFileSync(resolve(process.cwd(),"../../supabase/migrations/20261001150000_financial_accounting_center.sql"),"utf8");
const quotePaymentsSql=readFileSync(resolve(process.cwd(),"../../supabase/migrations/20261004120000_quote_payment_calendar.sql"),"utf8");
/** Permisos concedidos a un rol en todas las migraciones financieras (unión de los INSERT en role_permissions). */
const grantedTo=(role:string)=>[...new Set([sql,quotePaymentsSql].flatMap((text)=>[...text.matchAll(new RegExp(`select '${role}',code from public.app_permissions where code in\\(([^)]+)\\)`,"g"))].flatMap((m)=>m[1]!.match(/'([^']+)'/g)!.map((x)=>x.slice(1,-1)))))].sort();
const ids={gg:"11111111-1111-4111-8111-111111111111",fin:"22222222-2222-4222-8222-222222222222",cont:"33333333-3333-4333-8333-333333333333",ej:"44444444-4444-4444-8444-444444444444"};
const gg:FinanceActor={userId:ids.gg,role:"GERENTE_GENERAL"},fin:FinanceActor={userId:ids.fin,role:"FINANZAS"},cont:FinanceActor={userId:ids.cont,role:"CONTADOR"},ej:FinanceActor={userId:ids.ej,role:"EJECUTIVA_VENTAS"},dev:FinanceActor={userId:"55555555-5555-4555-8555-555555555555",role:"PROGRAMADOR"};
const rut=(n:number)=>{let s=0,f=2;for(const d of String(n).split("").reverse()){s+=Number(d)*f;f=f===7?2:f+1;}const r=11-(s%11);return`${n}-${r===11?"0":r===10?"K":r}`;};
const companyRut=rut(77123456);
const client=(id:string,n:number,extra:Partial<SourceClient>={}):SourceClient=>({id,legalName:`Cliente ${n} SpA`,tradeName:null,rut:rut(76000000+n),businessActivity:"Servicios",billingLegalName:null,billingRut:null,billingActivity:"Servicios informáticos",billingAddress:"Av. Siempre Viva 742",address:null,commune:"Santiago",region:"RM",dteEmail:`dte${n}@cliente.cl`,generalEmail:null,creditDays:30,currency:"CLP",accountExecutiveId:null,...extra});
const b64=(value:string|Buffer)=>Buffer.from(value).toString("base64");
const evidence={fileName:"respaldo.pdf",contentBase64:b64("%PDF-1.4 respaldo"),mimeType:"application/pdf"};
const today=todayCl();

describe("Financial & Accounting Control Center",()=>{
  let repo:FinanceRepository,sources:FinanceSources,ctx:FinanceContext,ledger:LedgerService,rules:AccountingRuleEngine,statements:StatementsService,invoices:InvoiceService,schedules:BillingScheduleService,dte:DteService,received:ReceivedDocumentsService,rcv:RcvService,payments:PaymentService,online:OnlinePaymentService,collections:CollectionsService,vendors:VendorService,approvals:ApprovalService,expenses:ExpenseService,payables:PayableService,banks:BankService,imports:StatementImportService,reconciliation:ReconciliationService,close:CloseService,budgets:BudgetService,tax:TaxService,commissions:CommissionFinanceService,analytics:AnalyticsService,reports:ReportsService,copilot:CopilotService;
  const c1="aaaaaaaa-0000-4000-8000-000000000001",c2="aaaaaaaa-0000-4000-8000-000000000002";
  beforeEach(async()=>{
    delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;for(const key of ["MERCADOPAGO_ACCESS_TOKEN","MERCADOPAGO_PUBLIC_KEY","MERCADOPAGO_WEBHOOK_SECRET","PUBLIC_API_URL","FINANCE_ENCRYPTION_KEY","RESEND_API_KEY"])delete process.env[key];
    repo=new FinanceRepository();sources=new FinanceSources();ctx=new FinanceContext(repo,sources);ledger=new LedgerService(ctx);rules=new AccountingRuleEngine(ctx,ledger);statements=new StatementsService(ctx);invoices=new InvoiceService(ctx,rules);schedules=new BillingScheduleService(ctx,invoices);
    const certs=new DteCertificateProvider();dte=new DteService(ctx,invoices,new SiiDirectDteProvider(certs,new DteSchemaValidator()),new ExternalCertifiedDteProvider(),certs);received=new ReceivedDocumentsService(ctx);rcv=new RcvService(ctx);
    const mp=new MercadoPagoPaymentProvider();payments=new PaymentService(ctx,rules,mp);online=new OnlinePaymentService(ctx,payments,mp);collections=new CollectionsService(ctx);vendors=new VendorService(ctx);approvals=new ApprovalService(ctx);expenses=new ExpenseService(ctx,approvals,rules);payables=new PayableService(ctx,rules);
    banks=new BankService(ctx);imports=new StatementImportService(ctx);reconciliation=new ReconciliationService(ctx,payments,ledger,rules);close=new CloseService(ctx,ledger,statements);budgets=new BudgetService(ctx);tax=new TaxService(ctx);commissions=new CommissionFinanceService(ctx,rules);
    analytics=new AnalyticsService(ctx,statements,collections,payables,invoices,dte);reports=new ReportsService(ctx,statements,ledger,analytics,collections,payables,tax,budgets,close);copilot=new CopilotService(ctx,statements,analytics,collections,payables,tax,ledger);
    sources.fixtures.clients.set(c1,client(c1,1));sources.fixtures.clients.set(c2,client(c2,2,{accountExecutiveId:ids.ej}));await repo.updateSettings({companyRut,companyBusinessActivity:"Desarrollo de software",companyActivityCode:620200,companyAddress:"Av. Zyteron 1",companyCommune:"Las Condes"});
  });
  const issuedInvoice=async(amount=1000000,clientId=c1)=>{const draft=await invoices.createDraft({clientId,lines:[{description:"Servicio",quantity:1,unitPrice:amount}]},fin);await invoices.submit(draft.id,fin);await invoices.approve(draft.id,gg);const xml=`<DTE><Documento><Encabezado><IdDoc><TipoDTE>33</TipoDTE><Folio>${Math.floor(Math.random()*1e6)}</Folio><FchEmis>${today}</FchEmis></IdDoc><Emisor><RUTEmisor>${companyRut}</RUTEmisor><RznSoc>Zyteron</RznSoc></Emisor><Receptor><RUTRecep>${draft.clientSnapshot.rut}</RUTRecep></Receptor><Totales><MntNeto>${amount}</MntNeto><IVA>${Math.round(amount*0.19)}</IVA><MntTotal>${amount+Math.round(amount*0.19)}</MntTotal></Totales></Encabezado><TED/></Documento></DTE>`;const folio=Number(/<Folio>(\d+)/.exec(xml)![1]);await dte.registerExternal(draft.id,{folio,issueDate:today,evidence:{fileName:"dte.xml",contentBase64:b64(xml)}},fin);return(await repo.get<any>("invoices",draft.id))!;};
  const confirmedPayment=async(amount:number,clientId=c1)=>{const account=await ctx.accountByCode("1.1.02.01");const bank=await banks.saveAccount(null,{bankName:"Banco",accountType:"CHECKING",accountNumber:"12345678",ledgerAccountId:account.id},fin);const p=await payments.record({clientId,grossAmount:amount,receivedAt:today,bankAccountId:bank.id,evidence},fin);await payments.confirm(p.id,{},gg);return p;};

  // ------------------------------------------------------------------ consistencia con la migración
  it("los datos base del modo memoria son espejo exacto de la migración",()=>{for(const[code]of seedAccounts)expect(sql).toContain(`('${code}',`);for(const[code]of seedRules)expect(sql).toContain(`('${code}',`);expect(seedAccounts.length).toBe((sql.match(/\('\d+(\.\d+)*','[^']+','(ASSET|LIABILITY|EQUITY|REVENUE|EXPENSE)'/g)??[]).length);});
  it("la matriz RBAC replica role_permissions y Desarrollo no tiene acceso",()=>{expect([...financeRoleMatrix.CONTADOR!].sort()).toEqual(grantedTo("CONTADOR"));expect([...financeRoleMatrix.EJECUTIVA_VENTAS!].sort()).toEqual(grantedTo("EJECUTIVA_VENTAS"));expect(financeRoleMatrix.PROGRAMADOR).toBeUndefined();expect(financeRoleMatrix.DESARROLLO).toBeUndefined();});
  it("migración con partida doble, inmutabilidad, RLS, realtime, buckets privados y sin Azure",()=>{for(const token of ["FINANCE_UNBALANCED","FINANCE_IMMUTABLE","FINANCE_PERIOD_CLOSED","for update skip locked","enable row level security","supabase_realtime","'finance-secrets','finance-secrets',false","finance_append_only","business_event_outbox","finance_portal_invoices"])expect(sql).toContain(token);expect(sql.toLowerCase()).not.toContain("azure");});

  // ------------------------------------------------------------------ contabilidad
  it("rechaza asientos descuadrados y contabiliza con numeración AST correlativa",async()=>{const bad=await ledger.createEntry({entryDate:today,description:"Descuadre",lines:[{accountCode:"1.1.01",debit:100},{accountCode:"4.1.01",credit:90}]},cont);await expect(ledger.post(bad.id,cont)).rejects.toBeInstanceOf(UnprocessableEntityException);const ok=await ledger.createEntry({entryDate:today,description:"Aporte",lines:[{accountCode:"1.1.01",debit:500},{accountCode:"3.1",credit:500}]},cont);const posted=await ledger.post(ok.id,cont);expect(posted.entryNumber).toMatch(/^AST-\d{4}-000001$/);await expect(ledger.updateEntry(ok.id,{description:"x"},cont)).rejects.toBeInstanceOf(ConflictException);await expect(ledger.discard(ok.id,cont)).rejects.toBeInstanceOf(ConflictException);});
  it("no permite imputar cuentas agrupadoras ni líneas con debe y haber",async()=>{await expect(ledger.createEntry({entryDate:today,description:"x",lines:[{accountCode:"1.1",debit:1},{accountCode:"4.1.01",credit:1}]},cont)).rejects.toBeInstanceOf(UnprocessableEntityException);await expect(ledger.createEntry({entryDate:today,description:"x",lines:[{accountCode:"1.1.01",debit:1,credit:1},{accountCode:"4.1.01",credit:1}]},cont)).rejects.toBeInstanceOf(UnprocessableEntityException);});
  it("corrige por reversa (una sola vez) y el balance de comprobación cuadra",async()=>{const e=await ledger.createEntry({entryDate:today,description:"Venta",lines:[{accountCode:"1.1.03",debit:1190},{accountCode:"4.1.01",credit:1000},{accountCode:"2.1.02",credit:190}]},cont);await ledger.post(e.id,cont);const{reversal,original}=await ledger.reverse(e.id,{reason:"Error de cliente"},cont);expect(original.status).toBe("REVERSED");expect(reversal.lines!.find((l)=>l.accountCode==="1.1.03")!.credit).toBe(1190);await expect(ledger.reverse(e.id,{reason:"otra"},cont)).rejects.toBeTruthy();const tb=await statements.trialBalance(`${today.slice(0,7)}-01`,today);expect(tb.balanced).toBe(true);});
  it("bloquea contabilizar en período cerrado y reabrir exige motivo",async()=>{const past=addDays(`${today.slice(0,7)}-01`,-40);const key=past.slice(0,7);const run=await close.center(key,cont);for(const t of run.tasks.filter((x)=>x.checkType==="MANUAL"))await close.updateTask(t.id,{status:"NOT_APPLICABLE",notes:"Sin operaciones"},gg);const blocked=(await close.center(key,cont)).tasks.filter((t)=>t.status==="BLOCKED");expect(blocked.map((t)=>t.code)).toEqual(["VAT"]);await expect(close.close(key,cont)).rejects.toBeInstanceOf(ConflictException);await expect(close.updateTask(blocked[0]!.id,{status:"WAIVED",notes:"Sin IVA"},cont)).rejects.toBeInstanceOf(ForbiddenException);await close.updateTask(blocked[0]!.id,{status:"WAIVED",notes:"Período sin operaciones afectas"},gg);const closed=await close.close(key,cont);expect(closed.period.status).toBe("CLOSED");expect((await close.snapshot(key,undefined,cont)).integrity).toBe("VERIFIED");const draft=await ledger.createEntry({entryDate:past,description:"Tarde",lines:[{accountCode:"1.1.01",debit:1},{accountCode:"3.1",credit:1}]},cont);await expect(ledger.post(draft.id,cont)).rejects.toBeInstanceOf(ConflictException);await expect(ledger.reopenPeriod(closed.periodId,"",cont)).rejects.toBeTruthy();expect((await ledger.reopenPeriod(closed.periodId,"Ajuste auditoría",cont)).reopenCount).toBe(1);});
  it("las reglas propuestas no generan asientos hasta activarse y nunca contabilizan solas",async()=>{const event=await rules.record({eventType:"PAYMENT_RECEIVED",sourceType:"PAYMENT",sourceId:c1,idempotencyKey:"k1",amounts:{GROSS:100,FEE:0,NET_SETTLEMENT:100},context:{channel:"BANK",clientId:c1,paymentReference:"PAG-1"},occurredOn:today},fin);expect(event.status).toBe("UNMAPPED");const rule=(await rules.rules()).find((r)=>r.code==="PAYMENT_RECEIVED_BANK")!;await rules.activate(rule.versions![0]!.id,cont);const again=await rules.process(event.id,fin);expect(again.status).toBe("ENTRY_CREATED");const entry=await ledger.entry(again.journalEntryId!);expect(entry.status).toBe("PENDING_REVIEW");expect(entry.lines!.map((l)=>l.accountCode)).toEqual(["1.1.02.01","2.1.04"]);expect((await rules.record({eventType:"PAYMENT_RECEIVED",sourceType:"PAYMENT",sourceId:c1,idempotencyKey:"k1",amounts:{},context:{},occurredOn:today},fin)).id).toBe(event.id);});

  // ------------------------------------------------------------------ facturación
  it("calcula IVA con la regla versionada vigente a la fecha de emisión",async()=>{const iva=(await repo.list<any>("tax_rules",{code:"IVA"}))[0];const current=(await repo.list<any>("tax_rule_versions",{taxRuleId:iva.id}))[0];await repo.update("tax_rule_versions",current.id,{effectiveTo:"2099-12-31"});await expect(tax.addVersion(iva.id,{rate:0.2,effectiveFrom:"2099-06-01",sourceReference:"Prueba"},cont)).rejects.toBeInstanceOf(ConflictException);const draft=await invoices.createDraft({clientId:c1,lines:[{description:"A",quantity:2,unitPrice:50000},{description:"Exento",quantity:1,unitPrice:10000,isExempt:true}]},fin);expect([draft.netAmount,draft.exemptAmount,draft.taxAmount,draft.totalAmount]).toEqual([100000,10000,19000,129000]);expect(draft.taxRuleVersionId).toBe(current.id);});
  it("exige aprobación con segregación y no borra documentos emitidos",async()=>{const draft=await invoices.createDraft({clientId:c1,lines:[{description:"S",quantity:1,unitPrice:100}]},fin);await invoices.submit(draft.id,fin);await expect(invoices.approve(draft.id,fin)).rejects.toBeInstanceOf(ConflictException);const inv=await issuedInvoice();await expect(invoices.cancel(inv.id,{reason:"x"},fin)).rejects.toBeInstanceOf(ConflictException);await expect(repo.remove("invoices",inv.id)).rejects.toBeTruthy();await expect(repo.update("invoices",inv.id,{netAmount:1,taxAmount:0,totalAmount:1})).rejects.toBeTruthy();});
  it("nota de crédito referenciada no excede lo acreditable y rebaja el saldo al aceptarse",async()=>{const inv=await issuedInvoice(100000);await expect(invoices.creditNote(inv.id,{reason:"Descuento",referenceCode:"3",lines:[{description:"Ajuste",quantity:1,unitPrice:200000}]},fin)).rejects.toBeInstanceOf(UnprocessableEntityException);const nc=await invoices.creditNote(inv.id,{reason:"Descuento",referenceCode:"3",lines:[{description:"Ajuste",quantity:1,unitPrice:10000}]},fin);expect(nc.documentTypeCode).toBe(61);expect(nc.referenceInvoiceId).toBe(inv.id);await repo.update("invoices",nc.id,{status:"READY_TO_ISSUE"});const xml=`<DTE><Documento><Encabezado><IdDoc><TipoDTE>61</TipoDTE><Folio>9001</Folio><FchEmis>${today}</FchEmis></IdDoc><Emisor><RUTEmisor>${companyRut}</RUTEmisor></Emisor><Receptor><RUTRecep>${nc.clientSnapshot.rut}</RUTRecep></Receptor><Totales><MntNeto>10000</MntNeto><IVA>1900</IVA><MntTotal>11900</MntTotal></Totales></Encabezado><TED/></Documento></DTE>`;await dte.registerExternal(nc.id,{folio:9001,issueDate:today,evidence:{fileName:"nc.xml",contentBase64:b64(xml)}},fin);const after=await repo.get<any>("invoices",inv.id);expect(after.balanceDue).toBe(119000-11900);expect((await repo.get<any>("invoices",nc.id)).balanceDue).toBe(0);});
  it("programación recurrente crea borradores idempotentes y nunca emite",async()=>{const s=await schedules.create({clientId:c1,description:"Hosting",frequency:"MONTHLY",amount:50000,nextBillingDate:addDays(today,-35)},fin);const first=await schedules.runDue(today,fin);const second=await schedules.runDue(today,fin);expect(first.draftsCreated).toBeGreaterThanOrEqual(1);expect(second.draftsCreated).toBe(0);const drafts=await repo.list<any>("invoices",{billingScheduleId:s.id});expect(drafts.every((d)=>d.status==="DRAFT")).toBe(true);expect((await repo.get<any>("billing_schedules",s.id)).nextBillingDate>today).toBe(true);});
  it("venta ganada queda pendiente de facturar sin generar factura automática",async()=>{sources.fixtures.sales.set("s1",{id:"bbbbbbbb-0000-4000-8000-000000000001",quoteId:"q1",clientId:c1,amount:595000,currency:"CLP",closedAt:`${today}T10:00:00Z`,contractId:null,status:"WON",ownerId:null});sources.fixtures.sales.set("bbbbbbbb-0000-4000-8000-000000000001",sources.fixtures.sales.get("s1")!);sources.fixtures.sales.delete("s1");sources.fixtures.quoteItems.set("q1",[{description:"Sitio web",quantity:1,unitPrice:500000,discountPercent:0,taxable:true,catalogServiceId:null}]);expect((await invoices.pendingToInvoice(fin))[0]!.pending).toBe(595000);expect(await repo.count("invoices")).toBe(0);const draft=await invoices.fromSale("bbbbbbbb-0000-4000-8000-000000000001",fin);expect(draft.totalAmount).toBe(595000);expect(draft.status).toBe("DRAFT");});

  // ------------------------------------------------------------------ DTE / SII
  it("Emitir DTE se bloquea y guía hacia cada requisito faltante",async()=>{const draft=await invoices.createDraft({clientId:c1,lines:[{description:"S",quantity:1,unitPrice:100}]},fin);const r=await dte.readiness(draft.id);expect(r.canIssue).toBe(false);expect(r.missing.some((m)=>m.includes("Proveedor DTE"))).toBe(true);expect(r.missing.some((m)=>m.includes("Resolución"))).toBe(true);expect(r.missing.some((m)=>m.includes("aprobada"))).toBe(true);expect(r.requirements.find(item=>item.key==="provider")?.actionHref).toBe("/finance/settings#dte-emission");expect(r.requirements.find(item=>item.key==="company")?.actionLabel).toBe("Completar emisor");await expect(dte.issue(draft.id,fin)).rejects.toBeInstanceOf(ConflictException);});
  it("genera TED firmado con la llave del CAF y firma XMLDSig verificable",async()=>{
    const caf=generateKeyPairSync("rsa",{modulusLength:1024});const pem=caf.privateKey.export({type:"pkcs1",format:"pem"}).toString();const cafXml=`<AUTORIZACION><CAF version="1.0"><DA><RE>${companyRut}</RE><RS>ZYTERON SPA</RS><TD>33</TD><RNG><D>1</D><H>50</H></RNG><FA>2026-09-01</FA><RSAPK><M>eA==</M><E>Aw==</E></RSAPK><IDK>100</IDK></DA><FRMA algoritmo="SHA1withRSA">c2ln</FRMA></CAF><RSASK>${pem}</RSASK><RSAPUBK>pub</RSAPUBK></AUTORIZACION>`;const parsed=parseCaf(cafXml);expect([parsed.documentTypeCode,parsed.rangeFrom,parsed.rangeTo]).toEqual([33,1,50]);
    const input:DteDocumentInput={taxDocumentId:"t",documentTypeCode:33,folio:7,issueDate:today,dueDate:addDays(today,30),environment:"CERTIFICATION",company:{rut:companyRut,legalName:"Zyteron SpA",businessActivity:"Software",activityCode:620200,address:"Av. 1",commune:"Las Condes",city:"Santiago",resolutionNumber:0,resolutionDate:today},receiver:{rut:rut(76000001),legalName:"Cliente & Cía",businessActivity:"Servicios",address:"Calle 2",commune:"Santiago",city:null,email:null},lines:[{lineNumber:1,description:"Desarrollo <web>",quantity:1,unitPrice:1000,discountAmount:0,netAmount:1000,isExempt:false}],totals:{net:1000,exempt:0,taxRate:0.19,tax:190,total:1190},reference:null,caf:parsed};
    expect(structuralErrors(input)).toEqual([]);const provider=new SiiDirectDteProvider(new DteCertificateProvider(),new DteSchemaValidator());const xml=await provider.createDraft(input);expect(xml).toContain('<Documento ID="F7T33">');expect(xml).toContain("Cliente &amp; Cía");const dd=/<DD>.*<\/DD>/.exec(xml)![0];const frmt=/<FRMT algoritmo="SHA1withRSA">([^<]+)<\/FRMT>/.exec(xml)![1]!;expect(createVerify("RSA-SHA1").update(dd,"latin1").verify(caf.publicKey,frmt,"base64")).toBe(true);
    const cert=generateKeyPairSync("rsa",{modulusLength:1024});const jwk=cert.publicKey.export({format:"jwk"}) as {n:string;e:string};const loaded={key:cert.privateKey,certificate:null as never,certificateBase64:"MIIB",modulus:Buffer.from(jwk.n,"base64url").toString("base64"),exponent:Buffer.from(jwk.e,"base64url").toString("base64")};const canonical=xml.replace(/^<Documento /,'<Documento xmlns="http://www.sii.cl/SiiDte" ');const signature=xmlSignature(canonical,"#F7T33",loaded,"");
    expect(/<DigestValue>([^<]+)</.exec(signature)![1]).toBe(createHash("sha1").update(canonical).digest("base64"));const signedInfo=/<SignedInfo>(.*)<\/SignedInfo>/.exec(signature)![1]!;expect(createVerify("RSA-SHA1").update(`<SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#">${signedInfo}</SignedInfo>`).verify(cert.publicKey,/<SignatureValue>([^<]+)</.exec(signature)![1]!,"base64")).toBe(true);
    const certificateProvider={load:()=>loaded,metadata:()=>({expiresAt:"2099-01-01T00:00:00.000Z"})}as unknown as DteCertificateProvider,direct=new SiiDirectDteProvider(certificateProvider,new DteSchemaValidator()),signed=await direct.sign(xml,input),envelope=direct.envelope([signed],input);expect(await new DteSchemaValidator().validate(envelope)).toEqual([]);
    expect(structuralErrors({...input,folio:99})).toContain("El folio está fuera del rango autorizado por el CAF.");
  });
  it("asigna folios correlativos sin reutilizar y sin folios disponibles falla explícitamente",async()=>{const auth=await repo.create<any>("tax_folio_authorizations",{documentTypeCode:33,environment:"CERTIFICATION",rangeFrom:1,rangeTo:2,authorizedAt:today,cafSha256:"x".repeat(64),cafStoragePath:"p",status:"ACTIVE"});for(const folio of [1,2])await repo.create("tax_folios",{authorizationId:auth.id,documentTypeCode:33,environment:"CERTIFICATION",folio,status:"AVAILABLE"});const docs=[];for(let i=0;i<3;i++){const inv=await invoices.createDraft({clientId:c1,lines:[{description:"S",quantity:1,unitPrice:1}]},fin);docs.push(await repo.create<any>("tax_documents",{invoiceId:inv.id,documentTypeCode:33,provider:"SII_DIRECT",environment:"CERTIFICATION",status:"DRAFT",folio:null}));}expect(await repo.reserveFolio(33,"CERTIFICATION",docs[0].id)).toBe(1);expect(await repo.reserveFolio(33,"CERTIFICATION",docs[0].id)).toBe(1);expect(await repo.reserveFolio(33,"CERTIFICATION",docs[1].id)).toBe(2);await expect(repo.reserveFolio(33,"CERTIFICATION",docs[2].id)).rejects.toThrow(/FINANCE_NO_FOLIOS/);const used=(await repo.list<any>("tax_folios",{folio:1}))[0];await repo.update("tax_folios",used.id,{status:"USED"});await expect(repo.update("tax_folios",used.id,{status:"AVAILABLE"})).rejects.toThrow(/FINANCE_FOLIO/);});
  it("emisión externa exige evidencia que coincida con la factura",async()=>{const draft=await invoices.createDraft({clientId:c1,lines:[{description:"S",quantity:1,unitPrice:1000}]},fin);await invoices.submit(draft.id,fin);await invoices.approve(draft.id,gg);const xml=`<DTE><Documento><Encabezado><IdDoc><TipoDTE>33</TipoDTE><Folio>5</Folio><FchEmis>${today}</FchEmis></IdDoc><Emisor><RUTEmisor>${companyRut}</RUTEmisor></Emisor><Receptor><RUTRecep>${draft.clientSnapshot.rut}</RUTRecep></Receptor><Totales><MntNeto>999</MntNeto><IVA>190</IVA><MntTotal>1189</MntTotal></Totales></Encabezado><TED/></Documento></DTE>`;await expect(dte.registerExternal(draft.id,{folio:5,issueDate:today,evidence:{fileName:"x.xml",contentBase64:b64(xml)}},fin)).rejects.toThrow(/monto total/);expect((await repo.get<any>("invoices",draft.id)).status).toBe("READY_TO_ISSUE");});
  it("importa DTE recibidos, detecta duplicados y no presume IVA recuperable",async()=>{const issuer=rut(96500000);const xml=`<EnvioDTE><SetDTE><DTE><Documento><Encabezado><IdDoc><TipoDTE>33</TipoDTE><Folio>44</Folio><FchEmis>${today}</FchEmis></IdDoc><Emisor><RUTEmisor>${issuer}</RUTEmisor><RznSoc>Proveedor SA</RznSoc><GiroEmis>Hosting</GiroEmis></Emisor><Receptor><RUTRecep>${companyRut}</RUTRecep></Receptor><Totales><MntNeto>10000</MntNeto><IVA>1900</IVA><MntTotal>11900</MntTotal></Totales></Encabezado><TED/></Documento></DTE></SetDTE></EnvioDTE>`;const first=await received.importXml({file:{fileName:"c.xml",contentBase64:b64(xml)}},fin);expect(first.results[0]!.result).toBe("CREATED");expect((await received.importXml({file:{fileName:"c.xml",contentBase64:b64(xml)}},fin)).results[0]!.result).toBe("DUPLICATE");const doc=(await repo.list<any>("received_tax_documents"))[0];expect(doc.taxCreditClassification).toBe("PENDING_REVIEW");await expect(received.classify(doc.id,{classification:"DEL_GIRO",reason:"Insumo"},cont)).rejects.toBeTruthy();expect((await received.classify(doc.id,{classification:"DEL_GIRO",eligible:true,reason:"Insumo del giro"},cont)).taxCreditEligibleAmount).toBe(1900);expect((await tax.vatSummary(today.slice(0,7),cont)).creditEligible).toBe(1900);});
  it("rechaza XML con DOCTYPE/ENTITY (XXE)",()=>{expect(()=>parseXml('<?xml version="1.0"?><!DOCTYPE a [<!ENTITY x SYSTEM "file:///etc/passwd">]><a>&x;</a>')).toThrow(/DOCTYPE/);});
  it("genera SOAP SII con namespace oficial por ambiente y tipos RPC",()=>{const certification=siiSoapEnvelope("CERTIFICATION","CrSeed","getSeed",{}),production=siiSoapEnvelope("PRODUCTION","GetTokenFromSeed","getToken",{pszXml:"<getToken>&</getToken>"});expect(certification).toContain('<m:getSeed xmlns:m="https://maullin.sii.cl/DTEWS/CrSeed.jws">');expect(production).toContain('<m:getToken xmlns:m="https://palena.sii.cl/DTEWS/GetTokenFromSeed.jws">');expect(production).toContain('<pszXml xsi:type="xsd:string">&lt;getToken&gt;&amp;&lt;/getToken&gt;</pszXml>');});
  it("carga los cuatro XSD oficiales y rechaza un sobre DTE inválido sin binarios del sistema",async()=>{const validator=new DteSchemaValidator();expect(validator.available()).toBe(true);expect(await validator.validate('<?xml version="1.0" encoding="ISO-8859-1"?><bad/>')).not.toEqual([]);});
  it("concilia RCV: coincide, diferencia de monto, falta local y falta en SII",async()=>{const issuer=rut(96500000),other=rut(96600000),local=rut(96700000);for(const[r,folio,total]of [[issuer,1,11900],[local,3,5000]] as const)await repo.create("received_tax_documents",{issuerRut:r,issuerName:"P",documentTypeCode:33,folio,issueDate:today,netAmount:total/1.19,exemptAmount:0,taxAmount:Math.round(total-total/1.19),totalAmount:total,source:"MANUAL",status:"RECEIVED",taxCreditClassification:"PENDING_REVIEW"});const csv=`Nro;Tipo Doc;Tipo Compra;RUT Proveedor;Razon Social;Folio;Fecha Docto;Monto Exento;Monto Neto;Monto IVA Recuperable;Monto Total\n1;33;Del Giro;${issuer};P;1;${today.split("-").reverse().join("/")};0;10000;1900;11900\n2;33;Del Giro;${other};Q;2;${today.split("-").reverse().join("/")};0;1000;190;1190\n`;const result=await rcv.importFile({registerType:"COMPRAS",periodKey:today.slice(0,7),file:{fileName:"rcv.csv",contentBase64:b64(csv)}},cont);expect(result.comparison.summary.MISSING_LOCAL).toBe(1);expect(result.comparison.summary.MISSING_SII).toBe(1);expect(result.comparison.rows.find((r)=>r.folio===1)!.status).toMatch(/MATCHED|AMOUNT_MISMATCH/);});

  // ------------------------------------------------------------------ cobros
  it("pagos: evidencia obligatoria, verificación, aplicación parcial, sobrepago y reversa",async()=>{const inv=await issuedInvoice(100000);await expect(payments.record({clientId:c1,grossAmount:1,receivedAt:today,bankAccountId:"cccccccc-0000-4000-8000-000000000001"},fin)).rejects.toThrow(/evidencia/);const account=await ctx.accountByCode("1.1.02.01");const bank=await banks.saveAccount(null,{bankName:"B",accountType:"CHECKING",accountNumber:"99887766",ledgerAccountId:account.id},fin);const p=await payments.record({clientId:c1,grossAmount:150000,receivedAt:today,bankAccountId:bank.id,evidence},fin);await expect(payments.allocate(p.id,{allocations:[{invoiceId:inv.id,amount:1000}]},fin)).rejects.toBeInstanceOf(ConflictException);await payments.confirm(p.id,{},gg);await expect(payments.allocate(p.id,{allocations:[{invoiceId:inv.id,amount:130000}]},fin)).rejects.toBeInstanceOf(UnprocessableEntityException);await payments.allocate(p.id,{allocations:[{invoiceId:inv.id,amount:119000}]},fin);expect((await repo.get<any>("invoices",inv.id)).status).toBe("PAID");expect((await payments.creditBalances(fin))[0]!.unappliedAmount).toBe(31000);const allocation=(await repo.list<any>("payment_allocations"))[0];await payments.reverseAllocation(allocation.id,{reason:"Error"},fin);expect((await repo.get<any>("invoices",inv.id)).status).toBe("ISSUED");await expect(repo.update("payment_allocations",allocation.id,{amount:1})).rejects.toBeTruthy();});
  it("no aplica pagos entre clientes distintos y devolución sólo sobre saldo no aplicado",async()=>{const inv=await issuedInvoice(10000,c2);const p=await confirmedPayment(50000,c1);await expect(payments.allocate(p.id,{allocations:[{invoiceId:inv.id,amount:100}]},fin)).rejects.toThrow(/clientes distintos/);await expect(payments.refund(p.id,{amount:60000,reason:"x"},fin)).rejects.toBeInstanceOf(UnprocessableEntityException);const refund=await payments.refund(p.id,{amount:10000,reason:"Duplicado"},fin);expect(refund.refunds[0]!.status).toBe("REQUESTED");await payments.completeRefund(refund.refunds[0]!.id,{evidence},fin);expect((await repo.get<any>("payments",p.id)).status).toBe("PARTIALLY_REFUNDED");});
  it("webhook de Mercado Pago valida HMAC con id, request-id y ts",()=>{process.env.MERCADOPAGO_WEBHOOK_SECRET="secret";const mp=new MercadoPagoPaymentProvider();const ts=String(Math.floor(Date.now()/1000));const v1=createHmac("sha256","secret").update(`id:123;request-id:req-1;ts:${ts};`).digest("hex");expect(mp.verifyWebhook({"x-signature":`ts=${ts},v1=${v1}`,"x-request-id":"req-1"},"123")).toBe(true);expect(mp.verifyWebhook({"x-signature":`ts=${ts},v1=${v1}`,"x-request-id":"req-2"},"123")).toBe(false);expect(mp.verifyWebhook({"x-signature":`ts=1000,v1=${createHmac("sha256","secret").update("id:123;request-id:req-1;ts:1000;").digest("hex")}`,"x-request-id":"req-1"},"123")).toBe(false);});
  it("link de pago guarda sólo el hash del token, vence y no expone IDs",async()=>{const inv=await issuedInvoice(1000);const link=await online.createLink(inv.id,{expiresInDays:1},fin);const token=link.url.split("/").pop()!;const stored=(await repo.list<any>("payment_links"))[0];expect(stored.tokenHash).toBe(sha256(token));expect(JSON.stringify(stored)).not.toContain(token);const view=await online.publicView(token);expect(JSON.stringify(view)).not.toContain(inv.id);expect(view.online.enabled).toBe(false);await repo.update("payment_links",stored.id,{expiresAt:new Date(Date.now()-1000).toISOString()});await expect(online.publicView(token)).rejects.toBeInstanceOf(NotFoundException);});
  it("aging desde vencimiento y promesas evaluadas con pagos reales",async()=>{const report=agingReport([{partyId:"a",partyName:"A",dueDate:addDays(today,-45),balance:100},{partyId:"a",partyName:"A",dueDate:addDays(today,5),balance:50}],today);expect(report.buckets.find((b)=>b.key==="D31_60")!.amount).toBe(100);expect(report.buckets.find((b)=>b.key==="CURRENT")!.amount).toBe(50);const promise=await collections.createPromise({clientId:c1,amount:1000,promisedDate:today},fin);await repo.update("payment_promises",promise.id,{promisedDate:addDays(today,-1)});expect((await collections.evaluatePromises(today)).broken).toBe(1);});
  it("recordatorios sin proveedor no simulan envíos y no se duplican",async()=>{await repo.updateSettings({collectionRemindersEnabled:true});const rule=(await repo.list<any>("collection_reminder_rules",{offsetDays:0}))[0];await repo.update("collection_reminder_rules",rule.id,{active:true});const inv=await issuedInvoice(1000);await repo.update("invoices",inv.id,{dueDate:today});const first=await collections.runReminders(today);const second=await collections.runReminders(today);expect(first.notConfigured).toBe(1);expect(second.notConfigured).toBe(0);expect((await repo.list<any>("collection_reminders"))[0].status).toBe("PROVIDER_NOT_CONFIGURED");});

  // ------------------------------------------------------------------ proveedores, gastos y CxP
  it("gastos: políticas configurables, segregación, clasificación de crédito y CxP con pago respaldado",async()=>{const vendor=await vendors.create({rut:rut(96500000),legalName:"Proveedor SA",paymentTermsDays:15,bankAccountLast4:"1234"},fin);await expect(vendors.create({rut:"11111111-2",legalName:"x"},fin)).rejects.toBeTruthy();const category=(await vendors.categories())[0]!;await approvals.savePolicy(null,{entityType:"EXPENSE",name:"Gerencia sobre 100k",minAmount:100000,approverRole:"GERENTE_GENERAL",level:1},gg);
    const e=await expenses.create({vendorId:vendor.id,categoryId:category.id,expenseDate:today,description:"Servidores",netAmount:100000,taxAmount:19000,evidence,paymentMethod:"TRANSFER"},fin);await expenses.submit(e.id,fin);await expect(expenses.decide(e.id,{decision:"APPROVED"},gg)).rejects.toThrow(/crédito fiscal/);await expenses.classify(e.id,{classification:"DEL_GIRO",eligible:true,reason:"Giro"},cont);await expect(expenses.decide(e.id,{decision:"APPROVED"},fin)).rejects.toBeInstanceOf(ForbiddenException);const approved=await expenses.decide(e.id,{decision:"APPROVED"},gg);expect(approved.status).toBe("APPROVED");
    const payable=(await repo.list<any>("payables"))[0];expect(payable.amount).toBe(119000);const vp=await payables.requestPayment({vendorId:vendor.id,allocations:[{payableId:payable.id,amount:119000}]},fin);await expect(payables.approvePayment(vp.id,fin)).rejects.toBeInstanceOf(ForbiddenException);await payables.approvePayment(vp.id,gg);await expect(payables.executePayment(vp.id,{},fin)).rejects.toThrow(/comprobante/);await payables.executePayment(vp.id,{evidence,reference:"TRF-1"},fin);expect((await repo.get<any>("payables",payable.id)).status).toBe("PAID");});
  it("datos bancarios completos sólo cifrados con clave del servidor",async()=>{await expect(vendors.create({rut:rut(96500001),legalName:"P",bankAccountNumber:"000123456789"},fin)).rejects.toBeInstanceOf(ConflictException);process.env.FINANCE_ENCRYPTION_KEY=Buffer.alloc(32,7).toString("base64");const v=await vendors.create({rut:rut(96500001),legalName:"P",bankAccountNumber:"000123456789"},fin);expect(v.bankAccountLast4).toBe("6789");expect(JSON.stringify(v)).not.toContain("000123456789");expect((await vendors.bankDetails(v.id,fin)).accountNumber).toBe("000123456789");});

  // ------------------------------------------------------------------ bancos y conciliación
  it("importa cartola CSV chilena y XLSX con hash determinístico anti-duplicados",async()=>{const account=await ctx.accountByCode("1.1.02.01");const bank=await banks.saveAccount(null,{bankName:"B",accountType:"CHECKING",accountNumber:"1234",ledgerAccountId:account.id},fin);const d=today.split("-").reverse().join("/");const csv=`Cartola\nFecha;Descripción;Cargos;Abonos;Saldo\n${d};ABONO A;;1.000;1.000\n${d};ABONO A;;1.000;2.000\n${d};COMISION;150;;1.850\n`;const preview=await imports.preview({bankAccountId:bank.id,file:{fileName:"c.csv",contentBase64:b64(csv)}},fin);expect(preview.valid).toBe(3);expect(new Set(preview.rows.map((r)=>r.hash)).size).toBe(3);await imports.commit({bankAccountId:bank.id,file:{fileName:"c.csv",contentBase64:b64(csv)}},fin);const xlsx=writeXlsx("Cartola",["Fecha","Glosa","Monto","Saldo"],[[d,"ABONO A",1000,1000],[d,"NUEVO",500,1500]]);const p2=await imports.preview({bankAccountId:bank.id,file:{fileName:"c.xlsx",contentBase64:b64(xlsx)}},fin);expect(p2.rows.map((r)=>r.duplicate)).toEqual([true,false]);expect(p2.rows[1]!.direction).toBe("CREDIT");expect(detectMapping(["Fecha","Glosa","Cargos","Abonos"]).debit).toBe("Cargos");});
  it("no concilia automáticamente casos ambiguos",async()=>{const account=await ctx.accountByCode("1.1.02.01");const bank=await banks.saveAccount(null,{bankName:"B",accountType:"CHECKING",accountNumber:"1234",ledgerAccountId:account.id},fin);for(let i=0;i<2;i++)await payments.record({clientId:c1,grossAmount:5000,receivedAt:today,bankAccountId:bank.id,evidence},fin);const tx=await repo.create<any>("bank_transactions",{bankAccountId:bank.id,transactionDate:today,description:"TRANSFERENCIA",amount:5000,direction:"CREDIT",externalHash:"h1",reconciliationStatus:"UNRECONCILED",reconciledAmount:0});const s=await reconciliation.suggestions(tx.id,fin);expect(s.candidates.length).toBe(2);expect(s.ambiguous).toBe(true);await repo.updateSettings({autoMatchEnabled:true});expect((await reconciliation.autoMatch(fin)).matched).toBe(0);await expect(reconciliation.match(tx.id,{targets:[{targetType:"PAYMENT",targetId:s.candidates[0]!.targetId,amount:6000}]},fin)).rejects.toBeInstanceOf(UnprocessableEntityException);const done=await reconciliation.match(tx.id,{targets:[{targetType:"PAYMENT",targetId:s.candidates[0]!.targetId,amount:5000}]},fin);expect((done as any).reconciliationStatus).toBe("RECONCILED");const match=(await repo.list<any>("reconciliation_matches"))[0];await reconciliation.undo(match.id,{reason:"Error"},fin);expect((await repo.get<any>("bank_transactions",tx.id)).reconciliationStatus).toBe("UNRECONCILED");await expect(repo.remove("reconciliation_matches",match.id)).rejects.toBeTruthy();});

  // ------------------------------------------------------------------ impuestos, cierre, comisiones, presupuestos
  it("F29 es estimación interna y no se marca presentado sin evidencia",async()=>{await issuedInvoice(100000);const prep=await tax.prepareF29(today.slice(0,7),cont);expect(prep.disclaimer).toMatch(/no es una declaración presentada/i);expect(prep.status).toBe("REVIEW_REQUIRED");expect(prep.lines.find((l)=>l.key==="PPM")!.label).toMatch(/no configurada/);const ppm=(await repo.list<any>("tax_rules",{code:"PPM"}))[0];await tax.addVersion(ppm.id,{rate:0.0025,effectiveFrom:"2026-01-01",sourceReference:"Tasa informada por SII al contribuyente"},cont);await tax.prepareF29(today.slice(0,7),cont);await tax.transitionF29(today.slice(0,7),"review",{},cont);await tax.transitionF29(today.slice(0,7),"ready",{},fin);await expect(tax.transitionF29(today.slice(0,7),"file",{filedReference:"123"},fin)).rejects.toBeTruthy();expect((await tax.transitionF29(today.slice(0,7),"file",{filedReference:"F29-123",evidence},fin)).status).toBe("FILED_EXTERNALLY");});
  it("comisiones: Finanzas decide elegibilidad por política configurable",async()=>{const sale="dddddddd-0000-4000-8000-000000000001";sources.fixtures.sales.set(sale,{id:sale,quoteId:"q",clientId:c1,amount:119000,currency:"CLP",closedAt:`${today}T00:00:00Z`,contractId:null,status:"WON",ownerId:null});sources.fixtures.commissions.set("eeeeeeee-0000-4000-8000-000000000001",{id:"eeeeeeee-0000-4000-8000-000000000001",saleId:sale,userId:ids.ej,amount:5000,currency:"CLP",status:"APPROVED"});expect((await commissions.view(fin))[0]!.financeStatus).toBe("NOT_ELIGIBLE");await commissions.savePolicy(null,{name:"50% cobrado",triggerType:"COLLECTED_PERCENT",collectedPercent:50},fin);
    const draft=await invoices.createDraft({clientId:c1,saleId:sale,lines:[{description:"Venta",quantity:1,unitPrice:100000}]},fin);await invoices.submit(draft.id,fin);await invoices.approve(draft.id,gg);const xml=`<DTE><Documento><Encabezado><IdDoc><TipoDTE>33</TipoDTE><Folio>77</Folio><FchEmis>${today}</FchEmis></IdDoc><Emisor><RUTEmisor>${companyRut}</RUTEmisor></Emisor><Receptor><RUTRecep>${draft.clientSnapshot.rut}</RUTRecep></Receptor><Totales><MntNeto>100000</MntNeto><IVA>19000</IVA><MntTotal>119000</MntTotal></Totales></Encabezado><TED/></Documento></DTE>`;await dte.registerExternal(draft.id,{folio:77,issueDate:today,evidence:{fileName:"d.xml",contentBase64:b64(xml)}},fin);const p=await confirmedPayment(60000);await payments.allocate(p.id,{allocations:[{invoiceId:draft.id,amount:60000}]},fin);const row=(await commissions.view(fin))[0]!;expect(row.financeStatus).toBe("ELIGIBLE");await commissions.approve(row.commissionId,fin);expect((await commissions.view(fin))[0]!.financeStatus).toBe("PAYABLE");await expect(commissions.pay(row.commissionId,{paymentReference:"X"},fin)).rejects.toBeTruthy();});
  it("presupuesto vs real desde el libro",async()=>{const account=await ctx.accountByCode("5.2.03");const budget=await budgets.create({name:"Opex",fiscalYear:Number(today.slice(0,4))},fin);await budgets.setLines(budget.id,{lines:[{accountId:account.id,periodKey:today.slice(0,7),amount:1000}]},fin);const e=await ledger.createEntry({entryDate:today,description:"Licencias",lines:[{accountCode:"5.2.03",debit:1200},{accountCode:"2.1.01",credit:1200}]},cont);await ledger.post(e.id,cont);const r=await budgets.vsActual(budget.id,fin);expect(r.rows[0]).toMatchObject({budget:1000,actual:1200,variance:200,variancePercent:20});});

  // ------------------------------------------------------------------ informes, copiloto, alcance
  it("Desarrollo no accede y ventas no ve márgenes ni el libro",async()=>{await expect(invoices.list({page:1,pageSize:10},dev)).rejects.toBeInstanceOf(ForbiddenException);await expect(analytics.profitability(ej,"CLIENT","2026-01-01",today)).rejects.toBeInstanceOf(ForbiddenException);await expect(reports.build("TRIAL_BALANCE",{},ej)).rejects.toBeInstanceOf(ForbiddenException);await issuedInvoice(1000,c1);await issuedInvoice(1000,c2);const visible=await invoices.list({page:1,pageSize:10},ej);expect(visible.items.every((i)=>i.clientId===c2)).toBe(true);await expect(invoices.get((await repo.list<any>("invoices",{clientId:c1}))[0].id,ej)).rejects.toBeInstanceOf(ForbiddenException);});
  it("exportaciones auditadas con encabezado institucional y CSV sin inyección de fórmulas",async()=>{const pdf=await reports.export("TRIAL_BALANCE","pdf",{},cont);const text=pdf.bytes.toString("latin1");expect(text.startsWith("%PDF-1.4")).toBe(true);expect(text).toContain("Zyteron SpA");expect(text).toContain("No constituye documento tributario");expect((await repo.list<any>("finance_audit_events",{action:"FINANCE_REPORT_EXPORTED"})).length).toBe(1);expect(writeCsv(["a"],[["=HYPERLINK(1)"]]).toString("utf8")).toContain("'=HYPERLINK");expect(readXlsx(writeXlsx("S",["A","B"],[["x",1]]))).toEqual([["A","B"],["x","1"]]);});
  it("Contador Zyteron: montos exactos, período, fuentes y propuesta sin contabilizar",async()=>{await issuedInvoice(100000);const a=await copilot.ask("¿Cuánto facturamos este mes?",cont);expect(a.amounts[0]!.value).toBe(119000);expect(a.sources.length).toBeGreaterThan(0);expect(a.answer).not.toMatch(/aproximadamente/i);expect(await repo.count("finance_analysis_runs")).toBe(1);const before=await repo.count("journal_entries",{status:"POSTED"});const p=await copilot.ask("propón asiento comisión bancaria 5.000",cont);expect(p.proposal!.lines).toEqual([{accountCode:"5.4.02",debit:5000,credit:0},{accountCode:"1.1.02.01",debit:0,credit:5000}]);expect(await repo.count("journal_entries",{status:"POSTED"})).toBe(before);const draft=await copilot.draftFromProposal({description:p.proposal!.description,lines:p.proposal!.lines},cont);expect(draft.status).toBe("DRAFT");expect(draft.sourceType).toBe("COPILOT_PROPOSAL");expect(parseQuestionPeriod("ventas de septiembre 2026")).toMatchObject({from:"2026-09-01",to:"2026-09-30"});expect(parseQuestionPeriod("del 01-09-2026 al 15-09-2026")).toMatchObject({from:"2026-09-01",to:"2026-09-15"});});
  it("métricas con definición y datos insuficientes explícitos",async()=>{const m=await analytics.metrics();expect(m.find((x)=>x.key==="MRR")!.insufficientData).toBe(true);expect(m.find((x)=>x.key==="DSO")!.value).toBeNull();await schedules.create({clientId:c1,description:"Soporte",frequency:"QUARTERLY",amount:300000,nextBillingDate:addDays(today,10)},fin);expect((await analytics.metrics()).find((x)=>x.key==="MRR")!.value).toBe(100000);});
  it("flujo de caja separa REAL de PROYECCIÓN",async()=>{await issuedInvoice(100000);const c=await analytics.cashflow(cont,"CONSERVATIVE");expect(c.history.every((p)=>p.kind==="REAL")).toBe(true);expect(c.projection.every((p)=>p.kind==="PROJECTION")).toBe(true);expect(c.assumptions[0]).toMatch(/PROYECCIÓN/);expect(c.projection.reduce((t,p)=>t+p.inflows,0)).toBeCloseTo(119000*0.95,0);});

  // ------------------------------------------------------------------ utilidades
  it("valida RUT, montos y fechas en formato chileno",()=>{expect(validRut(rut(12345678))).toBe(true);expect(validRut("12345678-0")).toBe(false);expect(formatRut("12.345.678-5")).toBe("12345678-5");expect(parseAmount("$ 1.234.567")).toBe(1234567);expect(parseAmount("-1.234,50")).toBe(-1234.5);expect(parseAmount("(500)")).toBe(-500);expect(parseFlexibleDate("05/09/2026")).toBe("2026-09-05");expect(parseFlexibleDate("46270")).toBe("2026-09-05");expect(parseCsv("a;b\n\"x;y\";2")).toEqual([["a","b"],["x;y","2"]]);});
});
