import { BadRequestException, ConflictException, ForbiddenException, Injectable, UnprocessableEntityException } from "@nestjs/common";
import type { AccountingPeriod, Budget, BudgetLine, BudgetVsActualRow, CloseRun, CloseTask, CommissionFinanceView, F29Line, F29Preparation, Invoice, JournalEntry, JournalLine, PaymentAllocation, ReceivedTaxDocument, TaxObligation, VatSummary } from "@zyteron/contracts";
import { FinanceContext } from "./finance.core.js";
import { decodeUpload } from "./finance.dte.js";
import { AccountingRuleEngine, LedgerService, StatementsService } from "./finance.ledger.js";
import { daysBetween, type FinanceActor, guarded, isoDate, monthRange, money, nowIso, oneOf, optionalText, optionalUuid, positiveAmount, previousPeriod, r2, requiredText, requiredUuid, type Row, sha256, sum, todayCl } from "./finance.util.js";

const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value as Row).sort().map((k)=>`${JSON.stringify(k)}:${stable((value as Row)[k])}`).join(",")}}`:JSON.stringify(value);
const doneStatuses=["OK","WAIVED","NOT_APPLICABLE"];

// =========================================================================================== Cierre mensual
@Injectable()
export class CloseService {
  constructor(private readonly ctx:FinanceContext,private readonly ledger:LedgerService,private readonly statements:StatementsService){}
  private get repo(){return this.ctx.repo;}
  /** Controles automáticos: cada uno devuelve conteo real y enlace al detalle. */
  async autoCheck(key:string,period:AccountingPeriod):Promise<{ok:boolean;count:number;detail:string;drillDown:string}>{
    const range={gte:period.startsOn,lte:period.endsOn};
    switch(key){
      case"DTE_PENDING":{const n=await this.repo.count("tax_documents",{issueDate:range,status:["DRAFT","VALIDATED","SIGNED","SUBMITTED","RECEIVED_BY_SII"]})+await this.repo.count("invoices",{status:"ISSUING"});return{ok:n===0,count:n,detail:n?`${n} DTE sin respuesta final del SII.`:"Sin DTE pendientes.",drillDown:"/finance/tax-documents"};}
      case"RECEIVED_DOCS_REVIEW":{const n=await this.repo.count("received_tax_documents",{issueDate:range,taxCreditClassification:"PENDING_REVIEW"});return{ok:n===0,count:n,detail:n?`${n} documentos recibidos sin clasificar crédito fiscal.`:"Todos clasificados.",drillDown:"/finance/tax-documents?tab=received"};}
      case"BANK_UNRECONCILED":{const n=await this.repo.count("bank_transactions",{transactionDate:range,reconciliationStatus:["UNRECONCILED","PARTIALLY_RECONCILED"]});return{ok:n===0,count:n,detail:n?`${n} movimientos bancarios sin conciliar.`:"Bancos conciliados.",drillDown:"/finance/reconciliation"};}
      case"VAT_REVIEWED":{const prep=await this.repo.findOne<F29Preparation>("f29_preparations",{periodKey:period.periodKey});const ok=Boolean(prep&&["REVIEWED","READY","FILED_EXTERNALLY","SUBMITTED","ACCEPTED"].includes(prep.status));return{ok,count:ok?0:1,detail:ok?`Preparación F29 ${prep!.status}.`:"La preparación F29 del período no está revisada.",drillDown:"/finance/taxes"};}
      case"COMMISSIONS_PENDING":{const pending=(await this.ctx.sources.commissions()).filter((c)=>c.status==="PAYABLE").length;return{ok:pending===0,count:pending,detail:pending?`${pending} comisiones por pagar.`:"Sin comisiones pendientes.",drillDown:"/finance/commissions"};}
      case"EXPENSES_PENDING":{const n=await this.repo.count("expenses",{expenseDate:range,status:["DRAFT","PENDING_APPROVAL"]});return{ok:n===0,count:n,detail:n?`${n} gastos sin resolver.`:"Gastos resueltos.",drillDown:"/finance/expenses"};}
      case"DRAFT_ENTRIES":{const n=await this.repo.count("journal_entries",{periodId:period.id,status:["DRAFT","PENDING_REVIEW"]});return{ok:n===0,count:n,detail:n?`${n} asientos sin contabilizar.`:"Sin borradores.",drillDown:"/finance/journal?status=PENDING_REVIEW"};}
      case"UNPOSTED_EVENTS":{const events=await this.repo.list<Row>("accounting_events",{occurredOn:range});const entryIds=events.filter((e)=>e.journalEntryId).map((e)=>e.journalEntryId);const entries=entryIds.length?await this.repo.list<JournalEntry>("journal_entries",{id:entryIds}):[];const posted=new Set(entries.filter((e)=>["POSTED","REVERSED"].includes(e.status)).map((e)=>e.id));const n=events.filter((e)=>["PENDING","UNMAPPED","ERROR"].includes(e.status)||(e.status==="ENTRY_CREATED"&&!posted.has(e.journalEntryId))).length;return{ok:n===0,count:n,detail:n?`${n} hechos económicos sin asiento contabilizado.`:"Todo documento tiene asiento.",drillDown:"/finance/accounting?tab=events"};}
      default:return{ok:false,count:1,detail:`Control automático ${key} no implementado.`,drillDown:"/finance/closing"};
    }
  }
  async center(periodKey:string,actor:FinanceActor):Promise<CloseRun>{
    this.ctx.require(actor,"period.view");const period=await this.ledger.period(periodKey);let run=await this.repo.findOne<Row>("period_close_runs",{periodId:period.id});if(!run)run=await guarded(()=>this.repo.create<Row>("period_close_runs",{periodId:period.id,status:period.status==="CLOSED"||period.status==="LOCKED"?"CLOSED":"IN_PROGRESS",startedBy:actor.userId,startedAt:nowIso()}));
    const items=(await this.repo.list<Row>("close_checklist_items",{active:true},{order:"sortOrder",ascending:true}));const existing=await this.repo.list<Row>("period_close_tasks",{closeRunId:run.id});const tasks:CloseTask[]=[];const closed=["CLOSED","LOCKED"].includes(period.status);
    for(const item of items){let task=existing.find((t)=>t.checklistItemId===item.id);if(!task)task=await this.repo.create<Row>("period_close_tasks",{closeRunId:run.id,checklistItemId:item.id,status:"PENDING",result:{}});
      if(item.checkType==="AUTO"&&!closed&&!["WAIVED","NOT_APPLICABLE"].includes(task.status)){const result=await this.autoCheck(item.autoCheckKey,period);task=await this.repo.update<Row>("period_close_tasks",task.id,{status:result.ok?"OK":item.blocking?"BLOCKED":"PENDING",result,checkedAt:nowIso()});}
      tasks.push({id:task.id,checklistItemId:item.id,code:item.code,label:item.label,checkType:item.checkType,blocking:item.blocking,status:task.status,result:task.result??{},responsibleUserId:task.responsibleUserId??null,evidencePath:task.evidencePath??null,notes:task.notes??null,checkedAt:task.checkedAt??null});}
    const blockers=tasks.filter((t)=>t.blocking&&!doneStatuses.includes(t.status)).map((t)=>`${t.label}${(t.result as Row).detail?`: ${(t.result as Row).detail}`:""}`);
    if(!closed){const status=blockers.length?"BLOCKED":"READY";if(run.status!==status){run=await this.repo.update<Row>("period_close_runs",run.id,{status});if(status==="READY")await this.repo.notify({eventKey:`period-ready:${period.id}:${period.reopenCount}`,type:"ACCOUNTING_PERIOD_READY_TO_CLOSE",title:`Período ${periodKey} listo para cerrar`,entityType:"ACCOUNTING_PERIOD",entityId:period.id,href:`/finance/closing?period=${periodKey}`});}}
    const snapshots=(await this.repo.list<Row>("period_snapshots",{periodId:period.id},{order:"version"})).map((s)=>({id:s.id,version:s.version,sha256:s.sha256,createdAt:s.createdAt}));
    return{id:run.id,periodId:period.id,period:(await this.repo.get<AccountingPeriod>("accounting_periods",period.id))!,status:run.status,tasks,blockers,snapshots};
  }
  async updateTask(taskId:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"period.close");const task=await this.ctx.must<Row>("period_close_tasks",taskId,"Tarea de cierre");const item=(await this.repo.get<Row>("close_checklist_items",task.checklistItemId))!;const status=oneOf(body.status,["PENDING","OK","WAIVED","NOT_APPLICABLE"] as const,"Estado");
    if(item.checkType==="AUTO"&&status==="OK")throw new ConflictException("Un control automático se aprueba solo cuando el dato cumple; corrige la causa.");if(status==="WAIVED"&&item.blocking&&actor.role!=="GERENTE_GENERAL")throw new ForbiddenException("Dispensar un control bloqueante requiere Gerencia.");
    const notes=status==="WAIVED"||status==="NOT_APPLICABLE"?requiredText(body.notes,"Justificación",1000):optionalText(body.notes,1000);const evidence=body.evidence?decodeUpload(body.evidence,"Evidencia"):null;if(item.checkType==="MANUAL"&&status==="OK"&&!evidence&&!notes)throw new BadRequestException("Registra evidencia o nota de la revisión.");
    const updated=await this.repo.update("period_close_tasks",taskId,{status,notes,evidencePath:evidence?await this.repo.saveFile("finance-documents",`close/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType):task.evidencePath,checkedAt:nowIso(),checkedBy:actor.userId,responsibleUserId:task.responsibleUserId??actor.userId});
    await this.repo.audit(actor,"CLOSE_TASK_UPDATED","CLOSE_TASK",taskId,`${item.label}: ${status}`,{notes});return updated;
  }
  async statementsFor(periodKey:string){const{from,to}=monthRange(periodKey);const[trialBalance,incomeStatement,balanceSheet]=await Promise.all([this.statements.trialBalance(from,to),this.statements.incomeStatement(from,to),this.statements.balanceSheet(to)]);return{trialBalance,incomeStatement,balanceSheet};}
  /** Cierre con snapshot inmutable y hash: el período cerrado se reproduce siempre igual. */
  async close(periodKey:string,actor:FinanceActor){
    this.ctx.require(actor,"period.close");const center=await this.center(periodKey,actor);if(center.blockers.length)throw new ConflictException({message:"El período tiene bloqueos de cierre.",blockers:center.blockers});
    const statements=await this.statementsFor(periodKey);if(!statements.trialBalance.balanced||!statements.balanceSheet.balanced)throw new UnprocessableEntityException("Los estados no cuadran; revisa el libro antes de cerrar.");
    const hash=sha256(stable(statements));const result=await guarded(()=>this.repo.closePeriod(center.periodId,actor.userId,{...statements,sha256:hash}));
    await this.repo.audit(actor,"PERIOD_CLOSED","ACCOUNTING_PERIOD",center.periodId,`Período ${periodKey} cerrado (snapshot v${result.version})`,{sha256:hash});await this.repo.event({aggregateType:"ACCOUNTING_PERIOD",aggregateId:center.periodId,eventType:"PERIOD_CLOSED",actorId:actor.userId,title:`Período ${periodKey} cerrado`,payload:{sha256:hash,version:result.version}});return this.center(periodKey,actor);
  }
  async snapshot(periodKey:string,version:number|undefined,actor:FinanceActor){this.ctx.require(actor,"period.view");const period=await this.ledger.period(periodKey);const snapshots=await this.repo.list<Row>("period_snapshots",{periodId:period.id},{order:"version"});const snap=version?snapshots.find((s)=>s.version===version):snapshots[0];if(!snap)throw new UnprocessableEntityException("El período no tiene snapshot de cierre.");const verified=sha256(stable({trialBalance:snap.trialBalance,incomeStatement:snap.incomeStatement,balanceSheet:snap.balanceSheet}))===snap.sha256;return{...snap,integrity:verified?"VERIFIED":"MISMATCH"};}
  checklist(actor:FinanceActor){this.ctx.require(actor,"period.view");return this.repo.list<Row>("close_checklist_items",{},{order:"sortOrder",ascending:true});}
  async saveChecklistItem(id:string|null,body:Row,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const data:Row={label:requiredText(body.label,"Nombre",200),description:optionalText(body.description,1000),blocking:Boolean(body.blocking),sortOrder:Number(body.sortOrder)||0,active:body.active!==false};const saved=id?await this.repo.update("close_checklist_items",id,data):await guarded(()=>this.repo.create("close_checklist_items",{...data,code:requiredText(body.code,"Código",40).toUpperCase(),checkType:"MANUAL",autoCheckKey:null}));await this.repo.audit(actor,"CLOSE_ITEM_SAVED","CLOSE_ITEM",(saved as Row).id,`Ítem de cierre ${data.label}`);return saved;}
}

// =========================================================================================== Presupuestos
@Injectable()
export class BudgetService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  list(actor:FinanceActor){this.ctx.require(actor,"report.finance.view");return this.repo.list<Budget>("budgets",{},{order:"fiscalYear"});}
  async get(id:string,actor:FinanceActor){this.ctx.require(actor,"report.finance.view");return{...await this.ctx.must<Budget>("budgets",id,"Presupuesto"),lines:await this.repo.list<BudgetLine>("budget_lines",{budgetId:id},{order:"periodKey",ascending:true})};}
  async create(body:Row,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const budget=await this.repo.create<Budget>("budgets",{name:requiredText(body.name,"Nombre",160),fiscalYear:Number(body.fiscalYear)||Number(todayCl().slice(0,4)),scopeType:oneOf(body.scopeType,["COMPANY","DEPARTMENT","COST_CENTER","PROJECT"] as const,"Alcance","COMPANY"),costCenterId:optionalUuid(body.costCenterId,"Centro de costo"),projectId:optionalUuid(body.projectId,"Proyecto"),departmentCode:optionalText(body.departmentCode,40),status:"DRAFT",createdBy:actor.userId});await this.repo.audit(actor,"BUDGET_CREATED","BUDGET",budget.id,`Presupuesto ${budget.name} ${budget.fiscalYear}`);return budget;}
  async setLines(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const budget=await this.ctx.must<Budget>("budgets",id,"Presupuesto");if(budget.status!=="DRAFT")throw new ConflictException("Un presupuesto aprobado no se edita; crea una nueva versión.");const lines=Array.isArray(body.lines)?body.lines:[];const accounts=await this.ctx.accountMap();
    for(const line of lines){const account=accounts.get(requiredUuid(line.accountId,"Cuenta"));if(!account||!["REVENUE","EXPENSE"].includes(account.accountType))throw new UnprocessableEntityException("Las líneas de presupuesto usan cuentas de ingreso o gasto.");if(!String(line.periodKey).startsWith(String(budget.fiscalYear)))throw new BadRequestException("El período debe pertenecer al año fiscal.");}
    await this.repo.removeWhere("budget_lines",{budgetId:id});for(const line of lines)await guarded(()=>this.repo.create("budget_lines",{budgetId:id,accountId:line.accountId,periodKey:line.periodKey,amount:r2(line.amount),costCenterId:optionalUuid(line.costCenterId,"Centro de costo")??budget.costCenterId,projectId:optionalUuid(line.projectId,"Proyecto")??budget.projectId,notes:optionalText(line.notes,300)}));await this.repo.audit(actor,"BUDGET_LINES_SET","BUDGET",id,`${lines.length} líneas de presupuesto`);return this.get(id,actor);}
  async approve(id:string,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const budget=await this.ctx.must<Budget>("budgets",id,"Presupuesto");if(budget.status!=="DRAFT")throw new ConflictException("El presupuesto no está en borrador.");if(!await this.repo.count("budget_lines",{budgetId:id}))throw new UnprocessableEntityException("El presupuesto no tiene líneas.");const updated=await this.repo.update("budgets",id,{status:"APPROVED",approvedBy:actor.userId,approvedAt:nowIso()});await this.repo.audit(actor,"BUDGET_APPROVED","BUDGET",id,`Presupuesto ${budget.name} aprobado`);return updated;}
  async archive(id:string,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");return this.repo.update("budgets",id,{status:"ARCHIVED"});}
  /** Real desde el libro contabilizado, con las dimensiones del presupuesto. */
  async vsActual(id:string,actor:FinanceActor):Promise<{budget:Budget;rows:BudgetVsActualRow[];totals:{budget:number;actual:number;variance:number}}>{
    const budget=await this.get(id,actor);const accounts=await this.ctx.accountMap();const lines=budget.lines;const accountIds=[...new Set(lines.map((l)=>l.accountId))];
    const entries=await this.repo.list<JournalEntry>("journal_entries",{status:["POSTED","REVERSED"],entryDate:{gte:`${budget.fiscalYear}-01-01`,lte:`${budget.fiscalYear}-12-31`}});const byId=new Map(entries.map((e)=>[e.id,e]));
    const journal=accountIds.length&&entries.length?(await this.repo.list<JournalLine>("journal_entry_lines",{accountId:accountIds})).filter((l)=>byId.has(l.journalEntryId)&&(!budget.costCenterId||l.costCenterId===budget.costCenterId)&&(!budget.projectId||l.projectId===budget.projectId)&&(!budget.departmentCode||l.departmentCode===budget.departmentCode)):[];
    const actual=new Map<string,number>();for(const l of journal){const account=accounts.get(l.accountId)!;const key=`${l.accountId}|${byId.get(l.journalEntryId)!.entryDate.slice(0,7)}`;actual.set(key,r2((actual.get(key)??0)+(account.accountType==="REVENUE"?l.credit-l.debit:l.debit-l.credit)));}
    const rows=lines.map((line)=>{const account=accounts.get(line.accountId)!;const real=actual.get(`${line.accountId}|${line.periodKey}`)??0;const variance=r2(real-line.amount);return{accountId:line.accountId,accountCode:account.code,accountName:account.name,periodKey:line.periodKey,budget:line.amount,actual:real,variance,variancePercent:line.amount?r2(variance/line.amount*100):null};});
    return{budget,rows,totals:{budget:sum(rows.map((r)=>r.budget)),actual:sum(rows.map((r)=>r.actual)),variance:sum(rows.map((r)=>r.variance))}};
  }
}

// =========================================================================================== Impuestos: IVA (estimación interna), F29 y obligaciones
const F29_DISCLAIMER="Estimación interna preparada desde documentos registrados en Zyteron. No es una declaración presentada ante el SII; la presentación se realiza en sii.cl y se registra aquí con evidencia.";
@Injectable()
export class TaxService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  async rules(actor:FinanceActor){this.ctx.require(actor,"tax.view");const[rules,versions]=await Promise.all([this.repo.list<Row>("tax_rules",{},{order:"code",ascending:true}),this.repo.list<Row>("tax_rule_versions",{},{order:"effectiveFrom"})]);return rules.map((r)=>({...r,versions:versions.filter((v)=>v.taxRuleId===r.id)}));}
  async addVersion(ruleId:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"tax.manage");await this.ctx.must("tax_rules",ruleId,"Regla tributaria");const rate=Number(body.rate);if(!(rate>=0&&rate<1))throw new BadRequestException("La tasa debe expresarse como fracción (ej. 0,19).");const version=await guarded(()=>this.repo.create("tax_rule_versions",{taxRuleId:ruleId,rate,effectiveFrom:isoDate(body.effectiveFrom,"Vigencia desde"),effectiveTo:body.effectiveTo?isoDate(body.effectiveTo,"Vigencia hasta"):null,sourceReference:requiredText(body.sourceReference,"Fuente legal o del SII",500),active:true,createdBy:actor.userId}));await this.repo.audit(actor,"TAX_VERSION_CREATED","TAX_RULE",ruleId,`Nueva tasa ${rate} desde ${body.effectiveFrom}`,{sourceReference:body.sourceReference});return version;}
  async deactivateVersion(versionId:string,actor:FinanceActor){this.ctx.require(actor,"tax.manage");const updated=await this.repo.update("tax_rule_versions",versionId,{active:false});await this.repo.audit(actor,"TAX_VERSION_DEACTIVATED","TAX_RULE_VERSION",versionId,"Versión tributaria desactivada");return updated;}
  async vatSummary(periodKey:string,actor:FinanceActor):Promise<VatSummary>{
    this.ctx.require(actor,"tax.view");const{from,to}=monthRange(periodKey);const issued=await this.repo.list<Invoice>("invoices",{issueDate:{gte:from,lte:to},status:["ISSUED","PARTIALLY_PAID","PAID","CREDITED"]});
    const debit=sum(issued.filter((i)=>[33,34].includes(i.documentTypeCode)).map((i)=>i.taxAmount)),debitNotes=sum(issued.filter((i)=>i.documentTypeCode===56).map((i)=>i.taxAmount)),creditNotes=sum(issued.filter((i)=>i.documentTypeCode===61).map((i)=>i.taxAmount));
    const received=await this.repo.list<ReceivedTaxDocument>("received_tax_documents",{issueDate:{gte:from,lte:to},status:{neq:"REJECTED"}});const sign=(d:ReceivedTaxDocument)=>d.documentTypeCode===61?-1:1;
    const manual=await this.repo.list<Row>("expenses",{expenseDate:{gte:from,lte:to},status:"APPROVED",receivedTaxDocumentId:null,taxAmount:{gt:0}});
    const potential=r2(sum(received.map((d)=>sign(d)*d.taxAmount))+sum(manual.map((e)=>e.taxAmount)));const eligible=r2(sum(received.filter((d)=>d.taxCreditEligible).map((d)=>sign(d)*(d.taxCreditEligibleAmount??0)))+sum(manual.filter((e)=>e.taxCreditEligible).map((e)=>e.eligibleTaxAmount)));
    const pending=r2(sum(received.filter((d)=>d.taxCreditClassification==="PENDING_REVIEW").map((d)=>sign(d)*d.taxAmount))+sum(manual.filter((e)=>e.taxCreditClassification==="PENDING_REVIEW").map((e)=>e.taxAmount)));const nonRecoverable=r2(potential-eligible-pending);
    const previous=await this.repo.findOne<F29Preparation>("f29_preparations",{periodKey:previousPeriod(periodKey)});const carried=Number(previous?.totals?.remainder??0);const netDebit=r2(debit+debitNotes-creditNotes);const balance=r2(netDebit-eligible-carried);
    return{periodKey,debit,creditNotesDebit:creditNotes,debitNotesDebit:debitNotes,netDebit,creditPotential:potential,creditEligible:eligible,creditPendingReview:pending,creditNonRecoverable:nonRecoverable,adjustments:carried,estimatedPayable:Math.max(0,balance),remainder:Math.max(0,-balance),label:"Estimación interna",
      sources:[{label:"Facturas y notas emitidas",count:issued.length,amount:netDebit,href:`/finance/invoices?from=${from}&to=${to}`},{label:"DTE recibidos",count:received.length,amount:sum(received.map((d)=>sign(d)*d.taxAmount)),href:`/finance/tax-documents?tab=received&from=${from}&to=${to}`},{label:"Gastos sin DTE con IVA",count:manual.length,amount:sum(manual.map((e)=>e.taxAmount)),href:`/finance/expenses?from=${from}&to=${to}`},{label:"Remanente período anterior (preparación F29)",count:previous?1:0,amount:carried,href:`/finance/taxes?period=${previousPeriod(periodKey)}`}]};
  }
  async f29(periodKey:string,actor:FinanceActor){this.ctx.require(actor,"tax.view");const prep=await this.repo.findOne<F29Preparation>("f29_preparations",{periodKey});return prep?{...prep,disclaimer:F29_DISCLAIMER}:null;}
  async prepareF29(periodKey:string,actor:FinanceActor){
    this.ctx.require(actor,"tax.review");const vat=await this.vatSummary(periodKey,actor);const{from,to}=monthRange(periodKey);const existing=await this.repo.findOne<F29Preparation>("f29_preparations",{periodKey});if(existing&&!["PREPARATION","REVIEW_REQUIRED"].includes(existing.status))throw new ConflictException(`La preparación está ${existing.status}; no se recalcula.`);
    const issued=await this.repo.list<Invoice>("invoices",{issueDate:{gte:from,lte:to},status:["ISSUED","PARTIALLY_PAID","PAID","CREDITED"]});const salesBase=r2(sum(issued.map((i)=>(i.documentTypeCode===61?-1:1)*(i.netAmount+i.exemptAmount))));const ppm=await this.ctx.optionalTaxRate("PPM",to);
    const href=(path:string)=>`${path}${path.includes("?")?"&":"?"}from=${from}&to=${to}`;
    const lines:F29Line[]=[{key:"SALES_BASE",label:"Ventas netas + exentas del período",amount:salesBase,source:`${issued.length} documentos emitidos`,drillDown:href("/finance/invoices"),officialCode:null},{key:"VAT_DEBIT",label:"IVA débito fiscal (facturas y notas de débito)",amount:r2(vat.debit+vat.debitNotesDebit),source:"Documentos emitidos",drillDown:href("/finance/invoices"),officialCode:null},{key:"VAT_CREDIT_NOTES",label:"IVA de notas de crédito emitidas",amount:vat.creditNotesDebit,source:"Notas de crédito",drillDown:href("/finance/invoices?documentTypeCode=61"),officialCode:null},{key:"VAT_CREDIT",label:"IVA crédito fiscal clasificado como recuperable",amount:vat.creditEligible,source:"DTE recibidos clasificados",drillDown:href("/finance/tax-documents?tab=received"),officialCode:null},{key:"VAT_PENDING",label:"IVA de compras pendiente de clasificar (no incluido)",amount:vat.creditPendingReview,source:"Revisión pendiente",drillDown:href("/finance/tax-documents?tab=received&classification=PENDING_REVIEW"),officialCode:null},{key:"REMAINDER_IN",label:"Remanente de crédito del período anterior",amount:vat.adjustments,source:"Preparación F29 anterior",drillDown:`/finance/taxes?period=${previousPeriod(periodKey)}`,officialCode:null},{key:"VAT_PAYABLE",label:"IVA determinado estimado",amount:vat.estimatedPayable,source:"Cálculo interno",drillDown:`/finance/taxes?period=${periodKey}`,officialCode:null},{key:"PPM",label:ppm?`PPM estimado (tasa ${(ppm.rate*100).toFixed(3).replace(/\.?0+$/,"")}% configurada)`:"PPM: tasa no configurada por contabilidad",amount:ppm?Math.round(salesBase*ppm.rate):0,source:ppm?ppm.sourceReference:"Configura la tasa PPM informada por el SII",drillDown:"/finance/taxes?tab=rules",officialCode:null}];
    const totals={debit:r2(vat.debit+vat.debitNotesDebit-vat.creditNotesDebit),credit:vat.creditEligible,remainderIn:vat.adjustments,vatPayable:vat.estimatedPayable,remainder:vat.remainder,ppm:lines.at(-1)!.amount,totalEstimated:r2(vat.estimatedPayable+lines.at(-1)!.amount)};const status=vat.creditPendingReview!==0||!ppm?"REVIEW_REQUIRED":"PREPARATION";
    const data={periodKey,status,lines,totals,ppmRate:ppm?.rate??null,preparedBy:actor.userId,preparedAt:nowIso()};const saved=existing?await this.repo.update<F29Preparation>("f29_preparations",existing.id,data):await this.repo.create<F29Preparation>("f29_preparations",data);
    if(status==="REVIEW_REQUIRED")await this.repo.notify({eventKey:`tax-review:${periodKey}:${saved.preparedAt}`,type:"TAX_REVIEW_REQUIRED",title:`Preparación F29 ${periodKey} requiere revisión`,body:vat.creditPendingReview?`IVA compras sin clasificar: ${money(vat.creditPendingReview)}`:"Tasa PPM no configurada",entityType:"F29_PREPARATION",entityId:saved.id,href:`/finance/taxes?period=${periodKey}`,severity:"WARNING",audienceRole:"CONTADOR"});
    await this.repo.audit(actor,"F29_PREPARED","F29_PREPARATION",saved.id,`Preparación F29 ${periodKey}: ${status}`,{totals});return{...saved,disclaimer:F29_DISCLAIMER};
  }
  async transitionF29(periodKey:string,action:"review"|"ready"|"file"|"accept",body:Row,actor:FinanceActor){
    const prep=await this.repo.findOne<F29Preparation>("f29_preparations",{periodKey});if(!prep)throw new UnprocessableEntityException("Primero prepara el F29 del período.");let patch:Row;
    if(action==="review"){this.ctx.require(actor,"tax.review");if(prep.status!=="PREPARATION")throw new ConflictException(prep.status==="REVIEW_REQUIRED"?"Resuelve las clasificaciones pendientes y recalcula.":`Estado ${prep.status}.`);patch={status:"REVIEWED",reviewedBy:actor.userId,reviewedAt:nowIso(),notes:optionalText(body.notes,1000)};}
    else if(action==="ready"){this.ctx.require(actor,"tax.manage");if(prep.status!=="REVIEWED")throw new ConflictException("Debe estar revisado.");if(prep.reviewedBy===actor.userId&&actor.role!=="GERENTE_GENERAL")throw new ForbiddenException("Segregación: quien revisa no marca como listo.");patch={status:"READY"};}
    else if(action==="file"){this.ctx.require(actor,"tax.manage");if(prep.status!=="READY")throw new ConflictException("Debe estar listo para presentar.");const evidence=decodeUpload(body.evidence,"Comprobante de presentación (sii.cl)");patch={status:"FILED_EXTERNALLY",filedReference:requiredText(body.filedReference,"Folio/N° de declaración",80),filedEvidencePath:await this.repo.saveFile("finance-documents",`tax/f29/${periodKey}/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType),filedAt:nowIso()};}
    else{this.ctx.require(actor,"tax.manage");if(!["FILED_EXTERNALLY","SUBMITTED"].includes(prep.status))throw new ConflictException("Primero registra la presentación.");const evidence=decodeUpload(body.evidence,"Evidencia de aceptación");patch={status:"ACCEPTED",acceptedEvidencePath:await this.repo.saveFile("finance-documents",`tax/f29/${periodKey}/accepted-${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType)};}
    const updated=await guarded(()=>this.repo.update<F29Preparation>("f29_preparations",prep.id,patch));await this.repo.audit(actor,`F29_${action.toUpperCase()}`,"F29_PREPARATION",prep.id,`F29 ${periodKey} → ${updated.status}`);return{...updated,disclaimer:F29_DISCLAIMER};
  }
  async obligations(actor:FinanceActor,periodKey?:string):Promise<TaxObligation[]>{this.ctx.require(actor,"tax.view");const today=todayCl();return(await this.repo.list<TaxObligation>("tax_obligations",{periodKey:periodKey||undefined},{order:"dueDate",ascending:true})).map((o)=>({...o,daysToDue:daysBetween(today,o.dueDate)}));}
  /** Sin fechas legales supuestas: el vencimiento lo informa contabilidad con su fuente. */
  async createObligation(body:Row,actor:FinanceActor){this.ctx.require(actor,"tax.manage");const created=await guarded(()=>this.repo.create<TaxObligation>("tax_obligations",{code:requiredText(body.code,"Código",40).toUpperCase(),name:requiredText(body.name,"Nombre",160),taxType:requiredText(body.taxType,"Tipo",40),periodKey:requiredText(body.periodKey,"Período",7),dueDate:isoDate(body.dueDate,"Vencimiento"),status:"PENDING",responsibleUserId:optionalUuid(body.responsibleUserId,"Responsable"),sourceReference:requiredText(body.sourceReference,"Fuente del vencimiento",300),notes:optionalText(body.notes,1000),createdBy:actor.userId}));await this.repo.audit(actor,"TAX_OBLIGATION_CREATED","TAX_OBLIGATION",created.id,`${created.name} ${created.periodKey}`);return created;}
  async updateObligation(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"tax.manage");const status=oneOf(body.status,["PENDING","IN_PREPARATION","READY","FILED_EXTERNALLY","PAID","NOT_APPLICABLE"] as const,"Estado");const patch:Row={status,notes:optionalText(body.notes,1000)};if(["FILED_EXTERNALLY","PAID"].includes(status)){const evidence=decodeUpload(body.evidence,"Evidencia");patch.filedReference=requiredText(body.filedReference,"Referencia",80);patch.filedEvidencePath=await this.repo.saveFile("finance-documents",`tax/obligations/${id}/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType);patch.filedAt=nowIso();}if(status==="NOT_APPLICABLE")patch.notes=requiredText(body.notes,"Justificación",1000);const updated=await guarded(()=>this.repo.update("tax_obligations",id,patch));await this.repo.audit(actor,"TAX_OBLIGATION_UPDATED","TAX_OBLIGATION",id,`Obligación → ${status}`);return updated;}
}

// =========================================================================================== Comisiones (Finanzas determina elegibilidad y pago)
@Injectable()
export class CommissionFinanceService {
  constructor(private readonly ctx:FinanceContext,private readonly rules:AccountingRuleEngine){}
  private get repo(){return this.ctx.repo;}
  policies(actor:FinanceActor){this.ctx.require(actor,"commission.finance.manage");return this.repo.list<Row>("commission_finance_policies",{},{order:"createdAt"});}
  async savePolicy(id:string|null,body:Row,actor:FinanceActor){this.ctx.require(actor,"commission.finance.manage");const trigger=oneOf(body.triggerType,["INVOICE_PAID","COLLECTED_PERCENT","PERIOD_END"] as const,"Disparador");const data={name:requiredText(body.name,"Nombre",120),triggerType:trigger,collectedPercent:trigger==="COLLECTED_PERCENT"?Math.max(1,Math.min(100,Number(body.collectedPercent)||0))||null:null,userId:optionalUuid(body.userId,"Vendedor"),commissionRuleId:optionalUuid(body.commissionRuleId,"Regla comercial"),active:body.active!==false};if(trigger==="COLLECTED_PERCENT"&&!data.collectedPercent)throw new BadRequestException("Indica el porcentaje cobrado requerido.");const saved=id?await this.repo.update("commission_finance_policies",id,data):await this.repo.create("commission_finance_policies",{...data,createdBy:actor.userId});await this.repo.audit(actor,"COMMISSION_POLICY_SAVED","COMMISSION_POLICY",(saved as Row).id,`Política de comisión ${data.name}`,data);return saved;}
  async view(actor:FinanceActor):Promise<CommissionFinanceView[]>{
    this.ctx.require(actor,"commission.finance.manage");const commissions=await this.ctx.sources.commissions();if(!commissions.length)return[];const policies=(await this.repo.list<Row>("commission_finance_policies",{active:true}));const payments=await this.repo.list<Row>("commission_payments",{commissionId:commissions.map((c)=>c.id)});
    const saleIds=[...new Set(commissions.map((c)=>c.saleId))];const invoices=await this.repo.list<Invoice>("invoices",{saleId:saleIds,status:{notIn:["CANCELLED","VOID","DRAFT","PENDING_APPROVAL","READY_TO_ISSUE","ISSUING"]}});const allocations=invoices.length?(await this.repo.list<PaymentAllocation>("payment_allocations",{invoiceId:invoices.map((i)=>i.id)})).filter((a)=>!a.reversedAt):[];const today=todayCl();
    const out:CommissionFinanceView[]=[];for(const c of commissions){const sale=await this.ctx.sources.sale(c.saleId);const own=invoices.filter((i)=>i.saleId===c.saleId);const invoiced=sum(own.map((i)=>i.documentTypeCode===61?-i.totalAmount:i.totalAmount));const collected=sum(allocations.filter((a)=>own.some((i)=>i.id===a.invoiceId)).map((a)=>a.amount));const base=sale?.amount??0;const percent=base>0?r2(collected/base*100):null;
      const policy=policies.find((p)=>p.userId===c.userId)??policies.find((p)=>!p.userId);const payment=payments.find((p)=>p.commissionId===c.id);let eligible=false,reason="Sin política financiera de comisiones configurada.";
      if(policy){if(policy.triggerType==="INVOICE_PAID"){eligible=own.length>0&&invoiced>=base&&own.filter((i)=>i.documentTypeCode!==61).every((i)=>i.status==="PAID"||i.balanceDue===0);reason=eligible?"Venta facturada y pagada.":`Pendiente: facturado ${money(invoiced)} de ${money(base)}; cobrado ${money(collected)}.`;}
        else if(policy.triggerType==="COLLECTED_PERCENT"){eligible=percent!==null&&percent>=Number(policy.collectedPercent);reason=eligible?`Cobrado ${percent}% ≥ ${policy.collectedPercent}%.`:`Cobrado ${percent??0}% de ${policy.collectedPercent}% requerido.`;}
        else{const end=sale?monthRange(sale.closedAt.slice(0,7)).to:null;eligible=Boolean(end&&end<today);reason=eligible?"Período de la venta cerrado.":"Período de la venta en curso.";}}
      const financeStatus:CommissionFinanceView["financeStatus"]=c.status==="CANCELLED"?"CANCELLED":c.status==="PAID"||payment?.status==="PAID"?"PAID":payment?.status==="APPROVED"?"PAYABLE":eligible?"ELIGIBLE":"NOT_ELIGIBLE";
      out.push({commissionId:c.id,saleId:c.saleId,userId:c.userId,amount:c.amount,currency:c.currency,commercialStatus:c.status,financeStatus,collectedPercent:percent,invoicedAmount:invoiced,collectedAmount:collected,reason,payment:payment?{id:payment.id,status:payment.status,paidAt:payment.paidAt??null,paymentReference:payment.paymentReference??null}:null});}
    return out;
  }
  async approve(commissionId:string,actor:FinanceActor){this.ctx.require(actor,"commission.finance.manage");const row=(await this.view(actor)).find((c)=>c.commissionId===commissionId);if(!row)throw new UnprocessableEntityException("Comisión no encontrada.");if(row.financeStatus!=="ELIGIBLE")throw new ConflictException(`La comisión no es elegible: ${row.reason}`);
    const payment=await guarded(()=>this.repo.create<Row>("commission_payments",{commissionId,amount:positiveAmount(row.amount,"Monto"),payableDate:todayCl(),status:"APPROVED",approvedBy:actor.userId,approvedAt:nowIso()}));await this.ctx.sources.transitionCommission(commissionId,"PAYABLE");
    await this.rules.record({eventType:"COMMISSION_APPROVED",sourceType:"COMMISSION",sourceId:commissionId,idempotencyKey:`commission-approved:${commissionId}`,amounts:{AMOUNT:row.amount},context:{documentLabel:`venta ${row.saleId.slice(0,8)}`},occurredOn:todayCl()},actor);await this.repo.audit(actor,"COMMISSION_APPROVED","COMMISSION",commissionId,`Comisión ${money(row.amount)} aprobada para pago`);return payment;}
  async pay(commissionId:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"commission.finance.manage");const payment=await this.repo.findOne<Row>("commission_payments",{commissionId});if(!payment||payment.status!=="APPROVED")throw new ConflictException("La comisión debe estar aprobada para pago.");const evidence=decodeUpload(body.evidence,"Comprobante de pago");const paidAt=isoDate(body.paidAt??todayCl(),"Fecha de pago");
    const updated=await this.repo.update("commission_payments",payment.id,{status:"PAID",paidAt:`${paidAt}T12:00:00-03:00`,paymentReference:requiredText(body.paymentReference,"Referencia",80),bankAccountId:optionalUuid(body.bankAccountId,"Cuenta bancaria"),evidencePath:await this.repo.saveFile("finance-documents",`commissions/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType)});await this.ctx.sources.transitionCommission(commissionId,"PAID");
    const ledger=body.bankAccountId?(await this.repo.get<Row>("bank_accounts",body.bankAccountId))?.ledgerAccountId:null;await this.rules.record({eventType:"COMMISSION_PAID",sourceType:"COMMISSION",sourceId:commissionId,idempotencyKey:`commission-paid:${commissionId}`,amounts:{AMOUNT:payment.amount},context:{documentLabel:body.paymentReference,cashLedgerAccountId:ledger??null},occurredOn:paidAt},actor);await this.repo.audit(actor,"COMMISSION_PAID","COMMISSION",commissionId,`Comisión pagada (${money(payment.amount)})`,{evidenceSha256:evidence.sha256});return updated;}
}
