import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, ServiceUnavailableException, UnauthorizedException, UnprocessableEntityException } from "@nestjs/common";
import type { AgingReport, CollectionActivity, Invoice, OnlinePaymentConfig, Payment, PaymentAllocation, PaymentPromise, PaymentRefund } from "@zyteron/contracts";
import { createHmac, timingSafeEqual } from "node:crypto";
import { documentLabel, withEffective } from "./finance.billing.js";
import { FinanceContext } from "./finance.core.js";
import { decodeUpload } from "./finance.dte.js";
import { AccountingRuleEngine } from "./finance.ledger.js";
import type { PageQuery } from "./finance.repository.js";
import { daysBetween, displayDate, type FinanceActor, fill, guarded, isoDate, money, nowIso, oneOf, optionalText, optionalUuid, positiveAmount, r2, randomToken, requiredText, requiredUuid, type Row, sha256, sum, todayCl } from "./finance.util.js";

export const systemActor:FinanceActor={userId:null,role:"FINANZAS"};
const buckets=[{key:"CURRENT",label:"Por vencer",min:-Infinity,max:0},{key:"D1_30",label:"1–30 días",min:1,max:30},{key:"D31_60",label:"31–60 días",min:31,max:60},{key:"D61_90",label:"61–90 días",min:61,max:90},{key:"D90_PLUS",label:"Más de 90 días",min:91,max:Infinity}] as const;
export const bucketOf=(daysOverdue:number)=>buckets.find((b)=>daysOverdue>=b.min&&daysOverdue<=b.max)!.key;
/** Antigüedad calculada desde la fecha de vencimiento (due_date), nunca desde la emisión. */
export function agingReport(items:Array<{partyId:string;partyName:string;dueDate:string;balance:number}>,asOf:string):AgingReport{
  const result:AgingReport={asOf,total:0,buckets:buckets.map((b)=>({key:b.key,label:b.label,amount:0,count:0})),byParty:[]};const parties=new Map<string,AgingReport["byParty"][number]>();
  for(const item of items){if(item.balance<=0)continue;const days=daysBetween(item.dueDate,asOf);const key=bucketOf(days);const bucket=result.buckets.find((b)=>b.key===key)!;bucket.amount=r2(bucket.amount+item.balance);bucket.count++;result.total=r2(result.total+item.balance);
    const party=parties.get(item.partyId)??{partyId:item.partyId,partyName:item.partyName,total:0,buckets:{},oldestDays:-Infinity};party.total=r2(party.total+item.balance);party.buckets[key]=r2((party.buckets[key]??0)+item.balance);party.oldestDays=Math.max(party.oldestDays,days);parties.set(item.partyId,party);}
  result.byParty=[...parties.values()].map((p)=>({...p,oldestDays:Math.max(0,p.oldestDays)})).sort((a,b)=>b.total-a.total);return result;
}

// =========================================================================================== Proveedor de pagos
export interface ProviderPayment { id:string; status:string; statusDetail:string|null; amount:number; currency:string; fee:number; netReceived:number|null; moneyReleaseDate:string|null; externalReference:string|null; dateApproved:string|null; refunds:Array<{id:string;amount:number;status:string}>; }
export abstract class PaymentProvider {
  abstract readonly name:"MERCADOPAGO";
  abstract configured():{ok:boolean;missing:string[]};
  abstract createPaymentIntent(input:{amount:number;currency:string;description:string;externalReference:string;idempotencyKey:string;form:Row;payerEmail:string|null}):Promise<ProviderPayment>;
  abstract createCheckout(input:{amount:number;currency:string;description:string;externalReference:string;returnUrl:string}):Promise<{checkoutUrl:string;preferenceId:string}>;
  abstract getPayment(id:string):Promise<ProviderPayment>;
  abstract refund(id:string,amount:number,idempotencyKey:string):Promise<{id:string;status:string;amount:number}>;
  abstract cancel(id:string):Promise<ProviderPayment>;
  abstract verifyWebhook(headers:Record<string,string|undefined>,dataId:string):boolean;
  async handleWebhook(headers:Record<string,string|undefined>,dataId:string){if(!this.verifyWebhook(headers,dataId))throw new UnauthorizedException("Firma de webhook inválida.");return this.getPayment(dataId);}
  getFees(payment:ProviderPayment){return{gross:payment.amount,fee:payment.fee,net:r2(payment.amount-payment.fee)};}
  getSettlement(payment:ProviderPayment){return{moneyReleaseDate:payment.moneyReleaseDate,netReceived:payment.netReceived??r2(payment.amount-payment.fee)};}
}
/** API oficial de Mercado Pago: ACCESS_TOKEN sólo en backend; PUBLIC KEY para el Payment Brick embebido. Nunca se reciben PAN ni CVV. */
@Injectable()
export class MercadoPagoPaymentProvider extends PaymentProvider {
  readonly name="MERCADOPAGO" as const;
  configured(){const missing=[!process.env.MERCADOPAGO_ACCESS_TOKEN&&"MERCADOPAGO_ACCESS_TOKEN",!process.env.MERCADOPAGO_PUBLIC_KEY&&"MERCADOPAGO_PUBLIC_KEY",!process.env.MERCADOPAGO_WEBHOOK_SECRET&&"MERCADOPAGO_WEBHOOK_SECRET",!process.env.PUBLIC_API_URL&&"PUBLIC_API_URL"].filter(Boolean) as string[];return{ok:!missing.length,missing};}
  private async call(method:string,path:string,body?:unknown,idempotencyKey?:string){const token=process.env.MERCADOPAGO_ACCESS_TOKEN?.trim();if(!token)throw new ServiceUnavailableException("Mercado Pago no está configurado.");const response=await fetch(`https://api.mercadopago.com${path}`,{method,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(idempotencyKey?{"X-Idempotency-Key":idempotencyKey}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)});const data=await response.json().catch(()=>({})) as Row;if(!response.ok)throw new UnprocessableEntityException(`Mercado Pago: ${data.message??data.error??`HTTP ${response.status}`}`);return data;}
  private map(data:Row):ProviderPayment{return{id:String(data.id),status:String(data.status),statusDetail:data.status_detail??null,amount:Number(data.transaction_amount),currency:data.currency_id??"CLP",fee:r2((data.fee_details??[]).reduce((t:number,f:Row)=>t+Number(f.amount||0),0)),netReceived:data.transaction_details?.net_received_amount??null,moneyReleaseDate:data.money_release_date?String(data.money_release_date).slice(0,10):null,externalReference:data.external_reference??null,dateApproved:data.date_approved??null,refunds:(data.refunds??[]).map((r:Row)=>({id:String(r.id),amount:Number(r.amount),status:String(r.status)}))};}
  async createPaymentIntent(input:{amount:number;currency:string;description:string;externalReference:string;idempotencyKey:string;form:Row;payerEmail:string|null}){
    const form=input.form??{};if(!form.token&&!form.payment_method_id)throw new BadRequestException("Datos del Payment Brick incompletos.");
    const payer=form.payer??{};const data=await this.call("POST","/v1/payments",{transaction_amount:input.amount,description:input.description.slice(0,250),external_reference:input.externalReference,notification_url:`${process.env.PUBLIC_API_URL!.replace(/\/$/,"")}/webhooks/payments/mercadopago`,token:form.token,installments:form.installments?Number(form.installments):undefined,payment_method_id:form.payment_method_id,issuer_id:form.issuer_id,transaction_details:form.transaction_details,payer:{email:payer.email??input.payerEmail??undefined,identification:payer.identification,entity_type:payer.entity_type,first_name:payer.first_name,last_name:payer.last_name},statement_descriptor:"ZYTERON"},input.idempotencyKey);
    return this.map(data);
  }
  async createCheckout(input:{amount:number;currency:string;description:string;externalReference:string;returnUrl:string}){const data=await this.call("POST","/checkout/preferences",{items:[{title:input.description.slice(0,250),quantity:1,unit_price:input.amount,currency_id:input.currency}],external_reference:input.externalReference,back_urls:{success:input.returnUrl,failure:input.returnUrl,pending:input.returnUrl},notification_url:`${process.env.PUBLIC_API_URL!.replace(/\/$/,"")}/webhooks/payments/mercadopago`});return{checkoutUrl:String(data.init_point),preferenceId:String(data.id)};}
  async getPayment(id:string){return this.map(await this.call("GET",`/v1/payments/${encodeURIComponent(id)}`));}
  async refund(id:string,amount:number,idempotencyKey:string){const data=await this.call("POST",`/v1/payments/${encodeURIComponent(id)}/refunds`,{amount},idempotencyKey);return{id:String(data.id),status:String(data.status),amount:Number(data.amount)};}
  async cancel(id:string){return this.map(await this.call("PUT",`/v1/payments/${encodeURIComponent(id)}`,{status:"cancelled"}));}
  /** Validación oficial x-signature: HMAC-SHA256 de "id:<data.id>;request-id:<x-request-id>;ts:<ts>;" con la clave secreta. */
  verifyWebhook(headers:Record<string,string|undefined>,dataId:string){
    const secret=process.env.MERCADOPAGO_WEBHOOK_SECRET?.trim();const signature=headers["x-signature"];const requestId=headers["x-request-id"];if(!secret||!signature||!dataId)return false;
    const parts=Object.fromEntries(signature.split(",").map((part)=>part.split("=").map((s)=>s.trim()) as [string,string]));if(!parts.ts||!parts.v1)return false;
    if(Math.abs(Date.now()-Number(parts.ts)*(parts.ts.length>11?1:1000))>15*60*1000)return false;
    const id=/^[a-z0-9]+$/i.test(dataId)?dataId.toLowerCase():dataId;const manifest=`id:${id};${requestId?`request-id:${requestId};`:""}ts:${parts.ts};`;const expected=createHmac("sha256",secret).update(manifest).digest("hex");
    const a=Buffer.from(expected),b=Buffer.from(parts.v1);return a.length===b.length&&timingSafeEqual(a,b);
  }
}
const mpStatus=(status:string):Payment["status"]=>({approved:"CONFIRMED",authorized:"PENDING",pending:"PENDING",in_process:"PENDING",in_mediation:"DISPUTED",rejected:"FAILED",cancelled:"CANCELLED",refunded:"REFUNDED",charged_back:"CHARGEBACK"} as Record<string,Payment["status"]>)[status]??"PENDING";

// =========================================================================================== Pagos recibidos
@Injectable()
export class PaymentService {
  constructor(private readonly ctx:FinanceContext,private readonly rules:AccountingRuleEngine,private readonly provider:MercadoPagoPaymentProvider){}
  private get repo(){return this.ctx.repo;}
  async list(q:PageQuery&{status?:string;clientId?:string;provider?:string;unapplied?:string},actor:FinanceActor){this.ctx.require(actor,"payment.view");const filters=await this.ctx.scopedFilters(actor,{status:q.status||undefined,provider:q.provider||undefined,unappliedAmount:q.unapplied==="true"?{gt:0}:undefined},q.clientId||null);const page=await this.repo.page<Payment>("payments",filters,{...q,order:"receivedAt",searchColumns:["paymentReference","externalId","notes"]});return{...page,items:await this.ctx.withClientNames(page.items)};}
  async get(id:string,actor:FinanceActor){this.ctx.require(actor,"payment.view");const payment=await this.ctx.must<Payment>("payments",id,"Pago");await this.ctx.assertClientAccess(actor,payment.clientId);const[allocations,refunds]=await Promise.all([this.repo.list<PaymentAllocation>("payment_allocations",{paymentId:id},{order:"allocatedAt"}),this.repo.list<PaymentRefund>("payment_refunds",{paymentId:id})]);const invoices=allocations.length?await this.repo.list<Invoice>("invoices",{id:[...new Set(allocations.map((a)=>a.invoiceId))]}):[];const[named]=await this.ctx.withClientNames([payment]);return{...named!,allocations:allocations.map((a)=>({...a,invoice:invoices.find((i)=>i.id===a.invoiceId)??null})),refunds};}
  /** Registro manual: nace PENDING_VERIFICATION y exige evidencia (comprobante) o movimiento bancario. Nunca marca facturas pagadas por sí solo. */
  async record(body:Row,actor:FinanceActor,idempotencyKey?:string){
    this.ctx.require(actor,"payment.record");const clientId=requiredUuid(body.clientId,"Cliente");await this.ctx.assertClientAccess(actor,clientId);const provider=oneOf(body.provider,["BANK_TRANSFER","CASH","OTHER"] as const,"Medio",body.cashAccountId?"CASH":"BANK_TRANSFER");
    const method=oneOf(body.method,["TRANSFER","CASH","CHECK","CARD","WALLET","OTHER"] as const,"Método",provider==="CASH"?"CASH":"TRANSFER");const grossAmount=positiveAmount(body.grossAmount,"Monto");const receivedOn=isoDate(body.receivedAt,"Fecha de recepción");if(receivedOn>todayCl())throw new BadRequestException("La fecha de recepción no puede ser futura.");
    const bankTransactionId=optionalUuid(body.bankTransactionId,"Movimiento bancario");const bankAccountId=optionalUuid(body.bankAccountId,"Cuenta bancaria");const cashAccountId=optionalUuid(body.cashAccountId,"Caja");
    if(!body.evidence&&!bankTransactionId)throw new BadRequestException("Adjunta el comprobante o vincula el movimiento de la cartola: un pago no se registra sin evidencia.");if(provider==="CASH"&&!cashAccountId)throw new BadRequestException("Selecciona la caja que recibió el efectivo.");if(provider==="BANK_TRANSFER"&&!bankAccountId&&!bankTransactionId)throw new BadRequestException("Selecciona la cuenta bancaria de destino.");
    if(idempotencyKey){const existing=await this.repo.findOne<Row>("finance_idempotency_keys",{idempotencyKey,operation:"payment.record"});if(existing)return this.get(existing.resourceId,actor);}
    const evidence=body.evidence?decodeUpload(body.evidence,"Comprobante"):null;const evidencePath=evidence?await this.repo.saveFile("finance-documents",`payments/evidence/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType):null;
    let cashMovementId:string|null=null;if(cashAccountId){if(!actor.userId)throw new ForbiddenException("Un movimiento de caja requiere responsable identificado.");const movement=await this.repo.create<Row>("cash_movements",{cashAccountId,movementDate:receivedOn,direction:"IN",amount:grossAmount,description:`Cobro en efectivo ${optionalText(body.notes,120)??""}`.trim(),responsibleUserId:actor.userId,evidencePath,status:"RECORDED",createdBy:actor.userId});cashMovementId=movement.id;}
    const tx=bankTransactionId?await this.ctx.must<Row>("bank_transactions",bankTransactionId,"Movimiento bancario"):null;if(tx&&(tx.direction!=="CREDIT"||r2(tx.amount-tx.reconciledAmount)<grossAmount))throw new UnprocessableEntityException("El movimiento bancario no es un abono o no tiene saldo conciliable suficiente.");
    const payment=await guarded(()=>this.repo.create<Payment>("payments",{clientId,provider,method,currency:body.currency??"CLP",grossAmount,feeAmount:0,receivedAt:`${receivedOn}T12:00:00-03:00`,status:"PENDING_VERIFICATION",externalId:optionalText(body.reference,120),externalStatus:null,allocatedAmount:0,refundedAmount:0,bankAccountId:bankAccountId??tx?.bankAccountId??null,bankTransactionId,cashMovementId,evidencePath,notes:optionalText(body.notes,1000),recordedBy:actor.userId,confirmedBy:null,confirmedAt:null,settlementStatus:"NOT_APPLICABLE",moneyReleaseDate:null}));
    if(idempotencyKey)await this.repo.claimIdempotency(idempotencyKey,"payment.record",payment.id);
    await this.repo.audit(actor,"PAYMENT_RECORDED","PAYMENT",payment.id,`${payment.paymentReference} registrado por ${money(grossAmount)} (pendiente de verificación)`,{evidenceSha256:evidence?.sha256??null,bankTransactionId});
    await this.repo.notify({eventKey:`payment-verify:${payment.id}`,type:"PAYMENT_VERIFICATION_REQUIRED",title:`Verificar pago ${payment.paymentReference}`,body:money(grossAmount),entityType:"PAYMENT",entityId:payment.id,href:`/finance/payments?payment=${payment.id}`,audienceRole:"FINANZAS"});return this.get(payment.id,actor);
  }
  /** Verificación humana con evidencia: sólo entonces el pago queda CONFIRMED y se contabiliza (borrador). */
  async confirm(id:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"payment.record");const payment=await this.ctx.must<Payment>("payments",id,"Pago");if(payment.status!=="PENDING_VERIFICATION")throw new ConflictException(`El pago está ${payment.status}.`);if(payment.provider==="MERCADOPAGO")throw new ConflictException("Los pagos de Mercado Pago se confirman sólo con la validación del proveedor.");
    const bankTransactionId=optionalUuid(body.bankTransactionId,"Movimiento bancario")??payment.bankTransactionId;if(!payment.evidencePath&&!bankTransactionId)throw new UnprocessableEntityException("Sin comprobante ni movimiento bancario no se confirma el pago.");
    await this.repo.update("payments",id,{status:"CONFIRMED",confirmedBy:actor.userId,confirmedAt:nowIso(),bankTransactionId});
    if(bankTransactionId){const existing=await this.repo.findOne<Row>("reconciliation_matches",{bankTransactionId,targetType:"PAYMENT",targetId:id,status:"ACTIVE"});if(!existing){await guarded(()=>this.repo.create("reconciliation_matches",{bankTransactionId,targetType:"PAYMENT",targetId:id,amount:payment.grossAmount,matchKind:"MATCH",confidence:null,status:"ACTIVE",createdBy:actor.userId}));await this.repo.afterMatchChange(bankTransactionId);}}
    await this.onConfirmed(id,actor);return this.get(id,actor);
  }
  async onConfirmed(id:string,actor:FinanceActor){
    const payment=(await this.repo.get<Payment>("payments",id))!;const channel=payment.provider==="MERCADOPAGO"?"PROVIDER":payment.provider==="CASH"?"CASH":"BANK";
    const ledger=payment.bankAccountId?(await this.repo.get<Row>("bank_accounts",payment.bankAccountId))?.ledgerAccountId:payment.cashMovementId?(await this.repo.get<Row>("cash_accounts",(await this.repo.get<Row>("cash_movements",payment.cashMovementId))!.cashAccountId))?.ledgerAccountId:null;
    await this.rules.record({eventType:"PAYMENT_RECEIVED",sourceType:"PAYMENT",sourceId:id,idempotencyKey:`payment-received:${id}`,amounts:{GROSS:payment.grossAmount,FEE:payment.feeAmount,NET_SETTLEMENT:payment.netAmount},context:{clientId:payment.clientId,channel,cashLedgerAccountId:ledger??null,paymentReference:payment.paymentReference},occurredOn:payment.receivedAt.slice(0,10)},actor);
    await this.repo.event({aggregateType:"PAYMENT",aggregateId:id,eventType:"PAYMENT_RECEIVED",actorId:actor.userId,clientId:payment.clientId,title:`Pago ${payment.paymentReference} confirmado por ${money(payment.grossAmount,payment.currency)}`,payload:{provider:payment.provider,grossAmount:payment.grossAmount,feeAmount:payment.feeAmount}});
    await this.repo.notify({eventKey:`payment-received:${id}`,type:"PAYMENT_RECEIVED",title:`Pago recibido ${payment.paymentReference}`,body:`${money(payment.grossAmount,payment.currency)} · por aplicar ${money(payment.unappliedAmount,payment.currency)}`,entityType:"PAYMENT",entityId:id,href:`/finance/payments?payment=${id}`});
    await this.repo.audit(actor,"PAYMENT_CONFIRMED","PAYMENT",id,`${payment.paymentReference} confirmado`);
  }
  async reject(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"payment.record");const reason=requiredText(body.reason,"Motivo",500);const payment=await this.ctx.must<Payment>("payments",id,"Pago");if(!["PENDING","PENDING_VERIFICATION"].includes(payment.status))throw new ConflictException("Sólo se rechaza un pago pendiente.");await this.repo.update("payments",id,{status:"FAILED",notes:[payment.notes,`Rechazado: ${reason}`].filter(Boolean).join("\n")});if(payment.cashMovementId)await this.repo.update("cash_movements",payment.cashMovementId,{status:"VOIDED",voidReason:reason});await this.repo.audit(actor,"PAYMENT_REJECTED","PAYMENT",id,`Pago rechazado: ${reason}`);await this.repo.notify({eventKey:`payment-failed:${id}`,type:"PAYMENT_FAILED",title:`Pago ${payment.paymentReference} rechazado`,body:reason,entityType:"PAYMENT",entityId:id,href:`/finance/payments?payment=${id}`,severity:"WARNING"});return this.get(id,actor);}
  async allocate(id:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"payment.allocate");const items=Array.isArray(body.allocations)?body.allocations:[];if(!items.length)throw new BadRequestException("Indica facturas y montos a aplicar.");const payment=await this.ctx.must<Payment>("payments",id,"Pago");
    const total=sum(items.map((i:Row)=>Number(i.amount)));if(total>payment.unappliedAmount)throw new UnprocessableEntityException(`Aplicas ${money(total)} y el saldo sin aplicar es ${money(payment.unappliedAmount)}.`);
    for(const item of items){const invoiceId=requiredUuid(item.invoiceId,"Factura");const amount=positiveAmount(item.amount,"Monto aplicado");const allocationId=await guarded(()=>this.repo.allocatePayment(id,invoiceId,amount,actor.userId));const invoice=(await this.repo.get<Invoice>("invoices",invoiceId))!;
      await this.rules.record({eventType:"PAYMENT_ALLOCATED",sourceType:"PAYMENT_ALLOCATION",sourceId:allocationId,idempotencyKey:`allocation:${allocationId}`,amounts:{AMOUNT:amount},context:{clientId:payment.clientId,paymentReference:payment.paymentReference,documentLabel:documentLabel(invoice)},occurredOn:todayCl()},actor);
      await this.repo.event({aggregateType:"INVOICE",aggregateId:invoiceId,eventType:"PAYMENT_ALLOCATED",actorId:actor.userId,clientId:payment.clientId,projectId:invoice.projectId,title:`${money(amount)} de ${payment.paymentReference} aplicado a ${documentLabel(invoice)}`,payload:{paymentId:id,allocationId,amount,balanceDue:invoice.balanceDue,status:invoice.status}});}
    await this.repo.audit(actor,"PAYMENT_ALLOCATED","PAYMENT",id,`${money(total)} aplicado a ${items.length} documento(s)`,{items});return this.get(id,actor);
  }
  /** Sugerencia FIFO por vencimiento (no se aplica sola). */
  async suggestAllocation(id:string,actor:FinanceActor){this.ctx.require(actor,"payment.view");const payment=await this.ctx.must<Payment>("payments",id,"Pago");const open=(await this.repo.list<Invoice>("invoices",{clientId:payment.clientId,status:["ISSUED","PARTIALLY_PAID"],currency:payment.currency},{order:"dueDate",ascending:true})).filter((i)=>i.documentTypeCode!==61&&i.balanceDue>0);let remaining=payment.unappliedAmount;const suggestions=[];for(const invoice of open){if(remaining<=0)break;const amount=Math.min(remaining,invoice.balanceDue);suggestions.push({invoiceId:invoice.id,invoiceNumber:invoice.invoiceNumber,dueDate:invoice.dueDate,balanceDue:invoice.balanceDue,amount});remaining=r2(remaining-amount);}return{paymentId:id,unapplied:payment.unappliedAmount,suggestions,creditBalanceAfter:remaining};}
  async reverseAllocation(allocationId:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"payment.allocate");const reason=requiredText(body.reason,"Motivo",500);const allocation=await this.ctx.must<PaymentAllocation>("payment_allocations",allocationId,"Aplicación");await guarded(()=>this.repo.reverseAllocation(allocationId,actor.userId,reason));const payment=(await this.repo.get<Payment>("payments",allocation.paymentId))!;
    await this.rules.record({eventType:"PAYMENT_ALLOCATION_REVERSED",sourceType:"PAYMENT_ALLOCATION",sourceId:allocationId,idempotencyKey:`allocation-reversed:${allocationId}`,amounts:{AMOUNT:allocation.amount},context:{clientId:payment.clientId,paymentReference:payment.paymentReference},occurredOn:todayCl()},actor);await this.repo.audit(actor,"ALLOCATION_REVERSED","PAYMENT",payment.id,`Aplicación de ${money(allocation.amount)} revertida: ${reason}`,{allocationId});return this.get(payment.id,actor);}
  /** Devoluciones: preservan el pago original. Primero se revierte la aplicación si el monto está aplicado. */
  async refund(id:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"payment.refund");const payment=await this.ctx.must<Payment>("payments",id,"Pago");if(!["CONFIRMED","PARTIALLY_REFUNDED"].includes(payment.status))throw new ConflictException("Sólo se devuelve un pago confirmado.");const amount=positiveAmount(body.amount,"Monto a devolver");const reason=requiredText(body.reason,"Motivo",500);
    if(amount>payment.unappliedAmount)throw new UnprocessableEntityException(`Sólo se puede devolver el saldo no aplicado (${money(payment.unappliedAmount)}); revierte aplicaciones primero.`);
    if(payment.provider==="MERCADOPAGO"&&payment.externalId){const result=await this.provider.refund(payment.externalId,amount,`refund:${id}:${amount}:${sha256(reason).slice(0,8)}`);const refund=await this.repo.create<PaymentRefund>("payment_refunds",{paymentId:id,amount,reason,status:result.status==="approved"?"REFUNDED":"PROCESSING",providerRefundId:result.id,requestedBy:actor.userId,processedAt:result.status==="approved"?nowIso():null});if(refund.status==="REFUNDED")await this.applyRefund(refund.id,actor);return this.get(id,actor);}
    const refund=await this.repo.create<PaymentRefund>("payment_refunds",{paymentId:id,amount,reason,status:"REQUESTED",requestedBy:actor.userId});await this.repo.audit(actor,"REFUND_REQUESTED","PAYMENT",id,`Devolución de ${money(amount)} solicitada: ${reason}`,{refundId:refund.id});return this.get(id,actor);
  }
  /** Una devolución manual se completa sólo con comprobante de la transferencia realizada. */
  async completeRefund(refundId:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"payment.refund");const refund=await this.ctx.must<PaymentRefund>("payment_refunds",refundId,"Devolución");if(refund.status!=="REQUESTED")throw new ConflictException("La devolución no está pendiente.");const evidence=decodeUpload(body.evidence,"Comprobante de devolución");const path=await this.repo.saveFile("finance-documents",`payments/refunds/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType);await this.repo.update("payment_refunds",refundId,{status:"REFUNDED",evidencePath:path,processedAt:nowIso()});await this.applyRefund(refundId,actor);return this.get(refund.paymentId,actor);}
  async applyRefund(refundId:string,actor:FinanceActor){const refund=(await this.repo.get<PaymentRefund>("payment_refunds",refundId))!;const payment=(await this.repo.get<Payment>("payments",refund.paymentId))!;const refunded=r2(payment.refundedAmount+refund.amount);await guarded(()=>this.repo.update("payments",payment.id,{refundedAmount:refunded,status:refunded>=payment.grossAmount?"REFUNDED":"PARTIALLY_REFUNDED"}));
    const ledger=payment.bankAccountId?(await this.repo.get<Row>("bank_accounts",payment.bankAccountId))?.ledgerAccountId:null;await this.rules.record({eventType:"PAYMENT_REFUNDED",sourceType:"PAYMENT_REFUND",sourceId:refundId,idempotencyKey:`refund:${refundId}`,amounts:{AMOUNT:refund.amount},context:{clientId:payment.clientId,paymentReference:payment.paymentReference,cashLedgerAccountId:ledger??null},occurredOn:todayCl()},actor);
    await this.repo.event({aggregateType:"PAYMENT",aggregateId:payment.id,eventType:"PAYMENT_REFUNDED",actorId:actor.userId,clientId:payment.clientId,title:`Devolución de ${money(refund.amount)} sobre ${payment.paymentReference}`,payload:{refundId}});await this.repo.notify({eventKey:`payment-refunded:${refundId}`,type:"PAYMENT_REFUNDED",title:`Devolución ${payment.paymentReference}`,body:money(refund.amount),entityType:"PAYMENT",entityId:payment.id,href:`/finance/payments?payment=${payment.id}`,severity:"WARNING"});await this.repo.audit(actor,"REFUND_COMPLETED","PAYMENT",payment.id,`Devolución ${money(refund.amount)} completada`,{refundId});}
  async creditBalances(actor:FinanceActor){this.ctx.require(actor,"receivable.view");const filters=await this.ctx.scopedFilters(actor,{status:["CONFIRMED","PARTIALLY_REFUNDED"],unappliedAmount:{gt:0}});return this.ctx.withClientNames(await this.repo.list<Payment>("payments",filters,{order:"receivedAt"}));}
}

// =========================================================================================== Pago en línea: links con token y Payment Brick
const REDIRECT_NOTICE="El pago se procesa con Mercado Pago dentro de esta página (Payment Brick). Algunos medios pueden abrir la autenticación de tu banco (3D Secure) o una redirección del medio de pago; al volver, el estado final llega por confirmación del proveedor.";
@Injectable()
export class OnlinePaymentService {
  constructor(private readonly ctx:FinanceContext,private readonly payments:PaymentService,private readonly provider:MercadoPagoPaymentProvider){}
  private get repo(){return this.ctx.repo;}
  async config():Promise<OnlinePaymentConfig>{const settings=await this.repo.settings();const status=this.provider.configured();const missing=[...(!settings.onlinePaymentsEnabled?["Pagos en línea deshabilitados en Configuración contable"]:[]),...status.missing];return{enabled:!missing.length,provider:"MERCADOPAGO",publicKey:!missing.length?process.env.MERCADOPAGO_PUBLIC_KEY!.trim():null,missing,redirectNotice:REDIRECT_NOTICE};}
  /** Token aleatorio de 256 bits; sólo se guarda su SHA-256. Expira y tiene alcance limitado a una factura. */
  async createLink(invoiceId:string,body:Row,actor:FinanceActor){
    this.ctx.requireAny(actor,"payment.record","collection.manage");const invoice=await this.ctx.must<Invoice>("invoices",invoiceId,"Factura");await this.ctx.assertClientAccess(actor,invoice.clientId);if(!["ISSUED","PARTIALLY_PAID"].includes(invoice.status)||invoice.balanceDue<=0||invoice.documentTypeCode===61)throw new ConflictException("Sólo se cobran en línea documentos emitidos con saldo.");
    const days=Math.max(1,Math.min(30,Number(body.expiresInDays)||7));const token=randomToken();const expiresAt=new Date(Date.now()+days*86400000).toISOString();
    const link=await this.repo.create<Row>("payment_links",{invoiceId,clientId:invoice.clientId,tokenHash:sha256(token),scope:"PAY_INVOICE",expiresAt,createdBy:actor.userId,revokedAt:null,lastUsedAt:null});
    await this.repo.audit(actor,"PAYMENT_LINK_CREATED","INVOICE",invoiceId,`Link de pago creado (vence ${displayDate(expiresAt.slice(0,10))})`,{linkId:link.id});
    const base=(process.env.CLIENT_PORTAL_URL?.trim()||"https://clientes.zyteron.cl").replace(/\/$/,"");return{linkId:link.id,url:`${base}/payments/${token}`,expiresAt,notice:"El token se muestra una sola vez; guárdalo o envíalo ahora."};
  }
  async links(invoiceId:string,actor:FinanceActor){this.ctx.require(actor,"invoice.view");return(await this.repo.list<Row>("payment_links",{invoiceId})).map(({tokenHash:_,...rest})=>rest);}
  async revokeLink(linkId:string,actor:FinanceActor){this.ctx.requireAny(actor,"payment.record","collection.manage");const updated=await this.repo.update("payment_links",linkId,{revokedAt:nowIso()});await this.repo.audit(actor,"PAYMENT_LINK_REVOKED","PAYMENT_LINK",linkId,"Link de pago revocado");return updated;}
  private async resolveLink(token:string){if(!/^[A-Za-z0-9_-]{40,64}$/.test(token))throw new NotFoundException("Link de pago inválido o vencido.");const link=await this.repo.findOne<Row>("payment_links",{tokenHash:sha256(token)});if(!link||link.revokedAt||link.expiresAt<=nowIso()||link.scope!=="PAY_INVOICE")throw new NotFoundException("Link de pago inválido o vencido.");const invoice=(await this.repo.get<Invoice>("invoices",link.invoiceId))!;return{link,invoice};}
  /** Vista pública mínima: nunca expone IDs internos, costos ni otras facturas. */
  async publicView(token:string){const{invoice}=await this.resolveLink(token);const settings=await this.repo.settings();const doc=invoice.taxDocumentId?await this.repo.get<Row>("tax_documents",invoice.taxDocumentId):null;const payable=["ISSUED","PARTIALLY_PAID"].includes(invoice.status)&&invoice.balanceDue>0;
    return{issuer:settings.companyLegalName,document:documentLabel(invoice,doc?.folio??null),clientName:invoice.clientSnapshot.legalName??null,issueDate:invoice.issueDate,dueDate:invoice.dueDate,currency:invoice.currency,total:invoice.totalAmount,balance:invoice.balanceDue,status:withEffective(invoice).effectiveStatus,payable,online:await this.config()};}
  /** El monto lo define el servidor (saldo vigente), nunca el navegador. */
  async pay(token:string,form:Row,idempotencyKey:string|undefined){
    const{link,invoice}=await this.resolveLink(token);const config=await this.config();if(!config.enabled)throw new ServiceUnavailableException(`Pago en línea no disponible: ${config.missing.join(", ")}.`);if(!["ISSUED","PARTIALLY_PAID"].includes(invoice.status)||invoice.balanceDue<=0)throw new ConflictException("Este documento no tiene saldo pendiente.");
    if(!idempotencyKey||!/^[A-Za-z0-9-]{16,80}$/.test(idempotencyKey))throw new BadRequestException("Falta Idempotency-Key.");
    const prior=await this.repo.findOne<Row>("finance_idempotency_keys",{idempotencyKey,operation:"online.pay"});if(prior){const payment=(await this.repo.get<Payment>("payments",prior.resourceId))!;return{status:payment.status,reference:payment.paymentReference,message:this.message(payment.status)};}
    const result=await this.provider.createPaymentIntent({amount:invoice.balanceDue,currency:invoice.currency,description:`${documentLabel(invoice)} · Zyteron`,externalReference:`inv:${invoice.id}:link:${link.id}`,idempotencyKey,form,payerEmail:invoice.clientSnapshot.dteEmail??null});
    const verified=await this.provider.getPayment(result.id);await this.repo.update("payment_links",link.id,{lastUsedAt:nowIso()});const payment=await this.upsertProviderPayment(verified,invoice.id);await this.repo.claimIdempotency(idempotencyKey,"online.pay",payment.id);
    return{status:payment.status,reference:payment.paymentReference,message:this.message(payment.status)};
  }
  private message(status:string){return status==="CONFIRMED"?"Pago aprobado y verificado con Mercado Pago.":status==="PENDING"?"Pago en proceso: lo confirmaremos cuando Mercado Pago lo apruebe. Esta pantalla no es un comprobante de pago confirmado.":"El pago no fue aprobado por el medio de pago.";}
  /** Estado obtenido desde la API del proveedor (nunca desde el navegador ni del cuerpo del webhook). */
  async upsertProviderPayment(remote:{id:string;status:string;amount:number;currency:string;fee:number;moneyReleaseDate:string|null;externalReference:string|null;dateApproved:string|null;refunds:Array<{id:string;amount:number;status:string}>},invoiceHint?:string):Promise<Payment>{
    const invoiceId=invoiceHint??/^inv:([0-9a-f-]{36})/.exec(remote.externalReference??"")?.[1];let payment=await this.repo.findOne<Payment>("payments",{provider:"MERCADOPAGO",externalId:remote.id});const status=mpStatus(remote.status);
    if(!payment){if(!invoiceId)throw new UnprocessableEntityException("Pago del proveedor sin referencia a factura.");const invoice=await this.ctx.must<Invoice>("invoices",invoiceId,"Factura");payment=await guarded(()=>this.repo.create<Payment>("payments",{clientId:invoice.clientId,provider:"MERCADOPAGO",method:"CARD",currency:remote.currency,grossAmount:remote.amount,feeAmount:Math.min(remote.fee,remote.amount),receivedAt:remote.dateApproved??nowIso(),status:status==="CONFIRMED"?"PENDING":status,externalId:remote.id,externalStatus:remote.status,allocatedAmount:0,refundedAmount:0,settlementStatus:"PENDING",moneyReleaseDate:remote.moneyReleaseDate,notes:`Pago en línea ${documentLabel(invoice)}`}));}
    const was=payment.status;if(was===status&&status!=="CONFIRMED")return payment;
    if(status==="CONFIRMED"&&!["CONFIRMED","PARTIALLY_REFUNDED","REFUNDED"].includes(was)){await this.repo.update("payments",payment.id,{status:"CONFIRMED",externalStatus:remote.status,feeAmount:Math.min(remote.fee,payment.grossAmount),confirmedAt:nowIso(),moneyReleaseDate:remote.moneyReleaseDate,receivedAt:payment.status==="PENDING"&&remote.dateApproved?payment.receivedAt:payment.receivedAt});await this.payments.onConfirmed(payment.id,systemActor);
      if(invoiceId){const invoice=(await this.repo.get<Invoice>("invoices",invoiceId))!;const amount=Math.min(invoice.balanceDue,payment.grossAmount);if(amount>0&&["ISSUED","PARTIALLY_PAID"].includes(invoice.status))await this.payments.allocate(payment.id,{allocations:[{invoiceId,amount}]},{userId:null,role:"FINANZAS"});}}
    else if(["FAILED","CANCELLED","DISPUTED","CHARGEBACK"].includes(status)&&status!==was){await this.repo.update("payments",payment.id,{status,externalStatus:remote.status});await this.repo.notify({eventKey:`payment-${status.toLowerCase()}:${payment.id}`,type:status==="FAILED"||status==="CANCELLED"?"PAYMENT_FAILED":"PAYMENT_DISPUTED",title:`Pago ${payment.paymentReference}: ${status}`,body:"Estado informado por Mercado Pago.",entityType:"PAYMENT",entityId:payment.id,href:`/finance/payments?payment=${payment.id}`,severity:status==="CHARGEBACK"?"CRITICAL":"WARNING"});await this.repo.audit(systemActor,"PROVIDER_PAYMENT_STATUS","PAYMENT",payment.id,`Mercado Pago informó ${remote.status}`);}
    else if(status==="REFUNDED"){for(const refund of remote.refunds){const known=await this.repo.findOne<PaymentRefund>("payment_refunds",{providerRefundId:refund.id});if(known&&known.status!=="REFUNDED"){await this.repo.update("payment_refunds",known.id,{status:"REFUNDED",processedAt:nowIso()});await this.payments.applyRefund(known.id,systemActor);}}}
    return(await this.repo.get<Payment>("payments",payment.id))!;
  }
  /** Webhook idempotente con firma verificada; vuelve a consultar el pago en la API oficial. */
  async webhook(query:Row,body:Row,headers:Record<string,string|undefined>){
    const dataId=String(query["data.id"]??body?.data?.id??"");const type=String(query.type??body?.type??body?.topic??"");const requestId=headers["x-request-id"]??"";const payloadHash=sha256(JSON.stringify(body??{}));
    const valid=this.provider.verifyWebhook(headers,dataId);const eventKey=`${type}:${dataId}:${requestId||payloadHash.slice(0,16)}`;
    let event:Row;try{event=await this.repo.create<Row>("payment_provider_events",{provider:"MERCADOPAGO",eventKey,eventType:type,externalId:dataId||null,signatureValid:valid,payloadSha256:payloadHash,status:valid?"RECEIVED":"IGNORED",error:valid?null:"Firma inválida"});}catch{return{received:true,duplicate:true};}
    if(!valid)throw new UnauthorizedException("Firma de webhook inválida.");if(type!=="payment"||!dataId){await this.repo.update("payment_provider_events",event.id,{status:"IGNORED",processedAt:nowIso()});return{received:true,ignored:true};}
    try{const remote=await this.provider.getPayment(dataId);await this.upsertProviderPayment(remote);await this.repo.update("payment_provider_events",event.id,{status:"PROCESSED",processedAt:nowIso()});return{received:true};}
    catch(error){await this.repo.update("payment_provider_events",event.id,{status:"FAILED",error:String((error as Error).message).slice(0,500),processedAt:nowIso()});throw error;}
  }
}

// =========================================================================================== Cuentas por cobrar y cobranza
@Injectable()
export class CollectionsService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  async openInvoices(actor:FinanceActor,clientId?:string|null){const filters=await this.ctx.scopedFilters(actor,{status:["ISSUED","PARTIALLY_PAID"],documentTypeCode:{neq:61}},clientId??null);return(await this.ctx.withClientNames(await this.repo.list<Invoice>("invoices",filters,{order:"dueDate",ascending:true}))).filter((i)=>i.balanceDue>0).map((i)=>withEffective(i));}
  async aging(actor:FinanceActor,asOf=todayCl()){this.ctx.require(actor,"receivable.view");const invoices=await this.openInvoices(actor);return agingReport(invoices.map((i)=>({partyId:i.clientId,partyName:i.clientName??i.clientSnapshot.legalName??"Cliente",dueDate:i.dueDate??i.issueDate??asOf,balance:i.balanceDue})),asOf);}
  async center(actor:FinanceActor){
    this.ctx.require(actor,"receivable.view");const today=todayCl();const invoices=await this.openInvoices(actor);const clientIds=[...new Set(invoices.map((i)=>i.clientId))];
    const[activities,promises]=await Promise.all([clientIds.length?this.repo.list<CollectionActivity>("collection_activities",{clientId:clientIds},{order:"occurredAt"}):[],clientIds.length?this.repo.list<PaymentPromise>("payment_promises",{clientId:clientIds,status:"OPEN"},{order:"promisedDate",ascending:true}):[]]);
    const clients=clientIds.map((clientId)=>{const own=invoices.filter((i)=>i.clientId===clientId);const overdue=own.filter((i)=>i.effectiveStatus==="OVERDUE");return{clientId,clientName:own[0]?.clientName??own[0]?.clientSnapshot.legalName??null,balance:sum(own.map((i)=>i.balanceDue)),overdue:sum(overdue.map((i)=>i.balanceDue)),oldestDays:Math.max(0,...overdue.map((i)=>i.daysOverdue??0)),invoices:own,lastActivity:activities.find((a)=>a.clientId===clientId)??null,openPromise:promises.find((p)=>p.clientId===clientId)??null,priority:overdue.length?Math.max(...overdue.map((i)=>i.daysOverdue??0))*Math.log10(10+sum(overdue.map((i)=>i.balanceDue))):0};}).sort((a,b)=>b.priority-a.priority);
    return{asOf:today,totals:{balance:sum(clients.map((c)=>c.balance)),overdue:sum(clients.map((c)=>c.overdue)),clients:clients.length,withPromise:clients.filter((c)=>c.openPromise).length},clients,dueSoon:invoices.filter((i)=>i.dueDate&&i.dueDate>=today&&daysBetween(today,i.dueDate)<=7)};
  }
  async activities(clientId:string,actor:FinanceActor){this.ctx.require(actor,"receivable.view");await this.ctx.assertClientAccess(actor,clientId);return this.repo.list<CollectionActivity>("collection_activities",{clientId},{order:"occurredAt"});}
  async addActivity(body:Row,actor:FinanceActor){this.ctx.require(actor,"collection.manage");const clientId=requiredUuid(body.clientId,"Cliente");await this.ctx.assertClientAccess(actor,clientId);const activity=await this.repo.create<CollectionActivity>("collection_activities",{clientId,invoiceId:optionalUuid(body.invoiceId,"Factura"),activityType:oneOf(body.activityType,["EMAIL","CALL","WHATSAPP","MEETING","NOTE","REMINDER","PROMISE"] as const,"Tipo"),outcome:optionalText(body.outcome,200),notes:optionalText(body.notes,2000),performedBy:actor.userId,occurredAt:body.occurredAt?`${isoDate(body.occurredAt,"Fecha")}T12:00:00-03:00`:nowIso()});await this.repo.event({aggregateType:"COLLECTION",aggregateId:activity.id,eventType:"COLLECTION_ACTIVITY",actorId:actor.userId,clientId,title:`Gestión de cobranza: ${activity.activityType}${activity.outcome?` · ${activity.outcome}`:""}`});return activity;}
  async promises(actor:FinanceActor,status?:string){this.ctx.require(actor,"receivable.view");return this.ctx.withClientNames(await this.repo.list<PaymentPromise>("payment_promises",await this.ctx.scopedFilters(actor,{status:status||undefined}),{order:"promisedDate",ascending:true}));}
  async createPromise(body:Row,actor:FinanceActor){this.ctx.require(actor,"collection.manage");const clientId=requiredUuid(body.clientId,"Cliente");await this.ctx.assertClientAccess(actor,clientId);const promisedDate=isoDate(body.promisedDate,"Fecha comprometida");if(promisedDate<todayCl())throw new BadRequestException("La fecha comprometida no puede estar en el pasado.");const promise=await this.repo.create<PaymentPromise>("payment_promises",{clientId,invoiceId:optionalUuid(body.invoiceId,"Factura"),amount:positiveAmount(body.amount,"Monto"),promisedDate,responsibleUserId:optionalUuid(body.responsibleUserId,"Responsable")??actor.userId,status:"OPEN",notes:optionalText(body.notes,1000),createdBy:actor.userId,resolvedAt:null});await this.repo.event({aggregateType:"COLLECTION",aggregateId:promise.id,eventType:"PAYMENT_PROMISE_CREATED",actorId:actor.userId,clientId,title:`Promesa de pago por ${money(promise.amount)} para el ${displayDate(promisedDate)}`});return promise;}
  async resolvePromise(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"collection.manage");const promise=await this.ctx.must<PaymentPromise>("payment_promises",id,"Promesa");if(promise.status!=="OPEN")throw new ConflictException("La promesa ya fue resuelta.");const status=oneOf(body.status,["KEPT","BROKEN","RESCHEDULED"] as const,"Resultado");
    if(status==="RESCHEDULED"){const next=await this.createPromise({clientId:promise.clientId,invoiceId:promise.invoiceId,amount:body.amount??promise.amount,promisedDate:body.promisedDate,notes:body.notes??promise.notes},actor);await this.repo.update("payment_promises",id,{status,resolvedAt:nowIso(),rescheduledToId:next.id});return next;}
    return this.repo.update("payment_promises",id,{status,resolvedAt:nowIso(),notes:[promise.notes,optionalText(body.notes)].filter(Boolean).join("\n")||null});}
  /** Cumplimiento por pagos efectivamente aplicados desde la creación de la promesa (no por declaración). */
  async evaluatePromises(asOf=todayCl()){let kept=0,broken=0;for(const promise of await this.repo.list<PaymentPromise>("payment_promises",{status:"OPEN",promisedDate:{lt:asOf}})){const invoiceIds=promise.invoiceId?[promise.invoiceId]:(await this.repo.list<Invoice>("invoices",{clientId:promise.clientId})).map((i)=>i.id);const paid=sum((invoiceIds.length?await this.repo.list<PaymentAllocation>("payment_allocations",{invoiceId:invoiceIds,allocatedAt:{gte:promise.createdAt}}):[]).filter((a)=>!a.reversedAt).map((a)=>a.amount));const ok=paid>=promise.amount;await this.repo.update("payment_promises",promise.id,{status:ok?"KEPT":"BROKEN",resolvedAt:nowIso()});if(ok)kept++;else{broken++;await this.repo.notify({eventKey:`promise-broken:${promise.id}`,type:"PAYMENT_PROMISE_BROKEN",title:"Promesa de pago incumplida",body:`${money(promise.amount)} comprometido para el ${displayDate(promise.promisedDate)}`,entityType:"PAYMENT_PROMISE",entityId:promise.id,href:"/finance/collections",severity:"WARNING",userId:promise.responsibleUserId});}}return{kept,broken};}
  reminderRules(actor:FinanceActor){this.ctx.require(actor,"receivable.view");return this.repo.list<Row>("collection_reminder_rules",{},{order:"offsetDays",ascending:true});}
  async updateReminderRule(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"collection.manage");const patch:Row={};if(body.active!==undefined)patch.active=Boolean(body.active);if(body.subjectTemplate!==undefined)patch.subjectTemplate=requiredText(body.subjectTemplate,"Asunto",200);if(body.bodyTemplate!==undefined)patch.bodyTemplate=requiredText(body.bodyTemplate,"Mensaje",4000);const updated=await this.repo.update("collection_reminder_rules",id,patch);await this.repo.audit(actor,"REMINDER_RULE_UPDATED","REMINDER_RULE",id,"Regla de recordatorio actualizada",patch);return updated;}
  /** Recordatorios configurables, una sola vez por factura/regla (sin spam) y nunca con promesa vigente. */
  async runReminders(asOf=todayCl()){
    const settings=await this.repo.settings();const notifications={dueSoon:0,overdue:0};const results={sent:0,notConfigured:0,skipped:0,noAddress:0,failed:0};
    const invoices=(await this.repo.list<Invoice>("invoices",{status:["ISSUED","PARTIALLY_PAID"],documentTypeCode:{neq:61}})).filter((i)=>i.balanceDue>0&&i.dueDate);
    for(const invoice of invoices){const offset=daysBetween(invoice.dueDate!,asOf);
      if(offset===-3&&await this.repo.notify({eventKey:`due-soon:${invoice.id}`,type:"INVOICE_DUE_SOON",title:`${documentLabel(invoice)} vence el ${displayDate(invoice.dueDate)}`,body:`${invoice.clientSnapshot.legalName??""} · ${money(invoice.balanceDue,invoice.currency)}`,entityType:"INVOICE",entityId:invoice.id,href:`/finance/invoices?invoice=${invoice.id}`}))notifications.dueSoon++;
      if(offset===1&&await this.repo.notify({eventKey:`overdue:${invoice.id}`,type:"INVOICE_OVERDUE",title:`${documentLabel(invoice)} vencida`,body:`${invoice.clientSnapshot.legalName??""} · saldo ${money(invoice.balanceDue,invoice.currency)}`,entityType:"INVOICE",entityId:invoice.id,href:"/finance/collections",severity:"WARNING"}))notifications.overdue++;}
    if(!settings.collectionRemindersEnabled)return{enabled:false,...results,notifications};
    const rules=await this.repo.list<Row>("collection_reminder_rules",{active:true});const promises=await this.repo.list<PaymentPromise>("payment_promises",{status:"OPEN",promisedDate:{gte:asOf}});
    for(const invoice of invoices){const offset=daysBetween(invoice.dueDate!,asOf);const rule=rules.find((r)=>r.offsetDays===offset);if(!rule)continue;if(promises.some((p)=>p.clientId===invoice.clientId&&(!p.invoiceId||p.invoiceId===invoice.id))){results.skipped++;continue;}
      const recipient=invoice.clientSnapshot.dteEmail??(await this.ctx.sources.client(invoice.clientId))?.generalEmail??null;let reminder:Row;try{reminder=await this.repo.create<Row>("collection_reminders",{invoiceId:invoice.id,ruleId:rule.id,offsetDays:offset,channel:"EMAIL",status:"SKIPPED",recipient});}catch{continue;}
      if(!recipient){await this.repo.update("collection_reminders",reminder.id,{status:"NO_ADDRESS"});results.noAddress++;continue;}
      const key=process.env.RESEND_API_KEY?.trim(),from=(process.env.FINANCE_MAIL_FROM??process.env.SALES_MAIL_FROM)?.trim();if(!key||!from){await this.repo.update("collection_reminders",reminder.id,{status:"PROVIDER_NOT_CONFIGURED"});results.notConfigured++;continue;}
      const values={invoiceLabel:documentLabel(invoice),dueDate:displayDate(invoice.dueDate),balance:money(invoice.balanceDue,invoice.currency)};
      try{const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json","idempotency-key":`reminder-${reminder.id}`},body:JSON.stringify({from,to:[recipient],subject:fill(rule.subjectTemplate,values),text:fill(rule.bodyTemplate,values)}),signal:AbortSignal.timeout(20000)});const data=await response.json().catch(()=>({})) as Row;if(!response.ok||!data.id)throw new Error(data.message??`HTTP ${response.status}`);await this.repo.update("collection_reminders",reminder.id,{status:"SENT",providerReference:data.id,sentAt:nowIso()});await this.repo.create("collection_activities",{clientId:invoice.clientId,invoiceId:invoice.id,activityType:"REMINDER",outcome:`Recordatorio ${offset>=0?`+${offset}`:offset} días enviado`,notes:recipient,performedBy:null,occurredAt:nowIso()});results.sent++;}
      catch(error){await this.repo.update("collection_reminders",reminder.id,{status:"FAILED",error:String((error as Error).message).slice(0,300)});results.failed++;}}
    return{enabled:true,...results,notifications};
  }
}
