import { BadRequestException, ConflictException, Injectable, UnprocessableEntityException } from "@nestjs/common";
import type { BillingSchedule, Invoice, InvoiceLine, PaymentAllocation, TaxDocument } from "@zyteron/contracts";
import { FinanceContext } from "./finance.core.js";
import { AccountingRuleEngine } from "./finance.ledger.js";
import type { PageQuery } from "./finance.repository.js";
import { addDays, addMonths, daysBetween, displayDate, type FinanceActor, guarded, isoDate, money, nowIso, oneOf, optionalText, optionalUuid, positiveAmount, r2, requiredText, requiredUuid, roundCurrency, type Row, sum, todayCl } from "./finance.util.js";

const openStatuses=["ISSUED","PARTIALLY_PAID"];
const preIssue=["DRAFT","PENDING_APPROVAL","READY_TO_ISSUE"];
export const documentLabel=(invoice:Pick<Invoice,"documentTypeCode"|"invoiceNumber">,folio?:number|null)=>`${({33:"Factura",34:"Factura exenta",61:"Nota de crédito",56:"Nota de débito"} as Record<number,string>)[invoice.documentTypeCode]??"Documento"} ${folio?`N° ${folio}`:invoice.invoiceNumber}`;
export function withEffective(invoice:Invoice,today=todayCl()):Invoice{const overdue=openStatuses.includes(invoice.status)&&Boolean(invoice.dueDate)&&invoice.dueDate!<today&&invoice.balanceDue>0;return{...invoice,effectiveStatus:overdue?"OVERDUE":invoice.status,daysOverdue:overdue?daysBetween(invoice.dueDate!,today):0};}
interface LineInput { description?:string; quantity?:number; unitPrice?:number; discountAmount?:number; isExempt?:boolean; clientServiceId?:string|null; catalogServiceId?:string|null; projectId?:string|null; costCenterId?:string|null; revenueAccountId?:string|null; }

@Injectable()
export class InvoiceService {
  constructor(private readonly ctx:FinanceContext,private readonly rules:AccountingRuleEngine){}
  private get repo(){return this.ctx.repo;}

  async list(q:PageQuery&{status?:string;clientId?:string;documentTypeCode?:string;overdue?:string;from?:string;to?:string},actor:FinanceActor){
    this.ctx.require(actor,"invoice.view");const today=todayCl();const filters=await this.ctx.scopedFilters(actor,{documentTypeCode:q.documentTypeCode?Number(q.documentTypeCode):undefined,status:q.overdue==="true"?openStatuses:q.status||undefined,dueDate:q.overdue==="true"?{lt:today}:undefined,issueDate:q.from||q.to?{gte:q.from||undefined,lte:q.to||undefined}:undefined},q.clientId||null);
    const page=await this.repo.page<Invoice>("invoices",filters,{...q,order:"createdAt",searchColumns:["invoiceNumber","description"]});return{...page,items:(await this.ctx.withClientNames(page.items)).map((i)=>withEffective(i,today))};
  }
  async get(id:string,actor:FinanceActor){
    this.ctx.require(actor,"invoice.view");const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");await this.ctx.assertClientAccess(actor,invoice.clientId);
    const[lines,allocations,taxDocuments,credits,events]=await Promise.all([this.repo.list<InvoiceLine>("invoice_lines",{invoiceId:id},{order:"lineNumber",ascending:true}),this.repo.list<PaymentAllocation>("payment_allocations",{invoiceId:id},{order:"allocatedAt"}),this.repo.list<TaxDocument>("tax_documents",{invoiceId:id}),this.repo.list<Invoice>("invoices",{referenceInvoiceId:id}),this.repo.list<Row>("finance_events",{aggregateId:id},{order:"occurredAt"})]);
    const[named]=await this.ctx.withClientNames([invoice]);return{...withEffective(named!),lines,allocations,taxDocuments,relatedNotes:credits,events};
  }
  private async buildLines(raw:unknown,documentTypeCode:number){
    if(!Array.isArray(raw)||!raw.length)throw new BadRequestException("El documento necesita al menos una línea.");if(raw.length>60)throw new BadRequestException("Máximo 60 líneas por documento (límite SII de detalle).");
    return raw.map((line:LineInput,index)=>{const quantity=Number(line.quantity??1);const unitPrice=Number(line.unitPrice);if(!(quantity>0))throw new BadRequestException(`Línea ${index+1}: cantidad inválida.`);if(!(unitPrice>=0))throw new BadRequestException(`Línea ${index+1}: precio inválido.`);const discountAmount=r2(line.discountAmount??0);const net=roundCurrency(quantity*unitPrice-discountAmount);if(net<0)throw new BadRequestException(`Línea ${index+1}: el descuento supera el monto.`);
      return{lineNumber:index+1,description:requiredText(line.description,`Descripción línea ${index+1}`,1000),quantity,unitPrice,discountAmount,netAmount:net,isExempt:documentTypeCode===34?true:Boolean(line.isExempt),clientServiceId:optionalUuid(line.clientServiceId,"Servicio"),catalogServiceId:optionalUuid(line.catalogServiceId,"Servicio de catálogo"),projectId:optionalUuid(line.projectId,"Proyecto"),costCenterId:optionalUuid(line.costCenterId,"Centro de costo"),revenueAccountId:optionalUuid(line.revenueAccountId,"Cuenta de ingreso")};});
  }
  /** Totales con la tasa de IVA vigente versionada a la fecha indicada (nunca constante en código). */
  private async totals(lines:Array<{netAmount:number;isExempt:boolean}>,documentTypeCode:number,date:string){
    const net=sum(lines.filter((l)=>!l.isExempt).map((l)=>l.netAmount)),exempt=sum(lines.filter((l)=>l.isExempt).map((l)=>l.netAmount));
    if(documentTypeCode===33&&net<=0)throw new UnprocessableEntityException("Una factura afecta (33) requiere monto neto afecto; usa factura exenta (34) si todo es exento.");if(documentTypeCode===34&&net>0)throw new UnprocessableEntityException("Una factura exenta (34) no lleva líneas afectas.");
    const tax=net>0?await this.ctx.taxRate("IVA",date):null;const taxAmount=tax?roundCurrency(net*tax.rate):0;return{netAmount:net,exemptAmount:exempt,taxAmount,totalAmount:r2(net+exempt+taxAmount),taxRate:tax?.rate??null,taxRuleVersionId:tax?.versionId??null};
  }
  private async snapshot(clientId:string){const client=await this.ctx.sources.client(clientId);if(!client)throw new UnprocessableEntityException("Cliente no encontrado.");return{snapshot:{rut:client.billingRut||client.rut,legalName:client.billingLegalName||client.legalName,businessActivity:client.billingActivity||client.businessActivity,address:client.billingAddress||client.address,commune:client.commune,city:client.region,dteEmail:client.dteEmail||client.generalEmail},creditDays:client.creditDays,currency:client.currency};}

  async createDraft(body:Row,actor:FinanceActor,origin:{billingScheduleId?:string|null;referenceInvoiceId?:string|null;referenceCode?:number|null;referenceReason?:string|null;system?:boolean}={}){
    if(!origin.system)this.ctx.require(actor,"invoice.create");const clientId=requiredUuid(body.clientId,"Cliente");if(!origin.system)await this.ctx.assertClientAccess(actor,clientId);
    const documentTypeCode=Number(body.documentTypeCode??(Array.isArray(body.lines)&&body.lines.every((l:LineInput)=>l.isExempt)?34:33));if(![33,34,56,61].includes(documentTypeCode))throw new BadRequestException("Tipo de documento no habilitado para facturación (33, 34, 56, 61).");
    if([56,61].includes(documentTypeCode)&&!origin.referenceInvoiceId)throw new BadRequestException("Las notas se crean desde el documento que referencian.");
    const lines=await this.buildLines(body.lines,documentTypeCode);const totals=await this.totals(lines,documentTypeCode,todayCl());const{snapshot,creditDays,currency}=await this.snapshot(clientId);const settings=await this.repo.settings();
    const paymentTermsDays=body.paymentTermsDays!==undefined&&body.paymentTermsDays!==null&&body.paymentTermsDays!==""?Math.max(0,Math.min(365,Number(body.paymentTermsDays))):(creditDays||settings.defaultPaymentTermsDays);
    const invoice=await guarded(()=>this.repo.create<Invoice>("invoices",{documentTypeCode,clientId,saleId:optionalUuid(body.saleId,"Venta"),contractId:optionalUuid(body.contractId,"Contrato"),projectId:optionalUuid(body.projectId,"Proyecto"),clientServiceId:optionalUuid(body.clientServiceId,"Servicio"),billingScheduleId:origin.billingScheduleId??null,referenceInvoiceId:origin.referenceInvoiceId??null,referenceCode:origin.referenceCode??null,referenceReason:origin.referenceReason??null,currency:body.currency??currency??"CLP",exchangeRate:1,...totals,amountPaid:0,amountCredited:0,status:"DRAFT",issueDate:null,dueDate:body.dueDate?isoDate(body.dueDate,"Vencimiento"):null,paymentTermsDays,paymentTerms:optionalText(body.paymentTerms,200),description:optionalText(body.description,500),notes:optionalText(body.notes,1000),clientSnapshot:snapshot,taxDocumentId:null,approvalRequired:false,approvedBy:null,approvedAt:null,issuedAt:null,cancelledAt:null,cancelReason:null,createdBy:actor.userId}));
    for(const line of lines)await guarded(()=>this.repo.create("invoice_lines",{...line,invoiceId:invoice.id}));
    await this.repo.audit(actor,"INVOICE_DRAFT_CREATED","INVOICE",invoice.id,`${documentLabel(invoice)} borrador por ${money(invoice.totalAmount,invoice.currency)}`,{origin:origin.billingScheduleId?"BILLING_SCHEDULE":origin.referenceInvoiceId?"REFERENCE":body.saleId?"SALE":"MANUAL"});
    await this.repo.notify({eventKey:`invoice-draft:${invoice.id}`,type:"INVOICE_DRAFT_CREATED",title:`${documentLabel(invoice)} en borrador`,body:`${snapshot.legalName} · ${money(invoice.totalAmount,invoice.currency)}`,entityType:"INVOICE",entityId:invoice.id,href:`/finance/invoices?invoice=${invoice.id}`,audienceRole:"FINANZAS"});
    return this.get(invoice.id,{...actor,role:origin.system?"FINANZAS":actor.role});
  }
  async updateDraft(id:string,body:Row,actor:FinanceActor){
    this.ctx.requireAny(actor,"invoice.edit","invoice.create");const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");await this.ctx.assertClientAccess(actor,invoice.clientId);if(!["DRAFT","PENDING_APPROVAL"].includes(invoice.status))throw new ConflictException("Sólo se editan borradores; un documento emitido se corrige con nota de crédito o débito.");
    const patch:Row={};if(body.lines!==undefined){const lines=await this.buildLines(body.lines,invoice.documentTypeCode);Object.assign(patch,await this.totals(lines,invoice.documentTypeCode,todayCl()));await guarded(()=>this.repo.removeWhere("invoice_lines",{invoiceId:id}));for(const line of lines)await guarded(()=>this.repo.create("invoice_lines",{...line,invoiceId:id}));}
    for(const key of ["description","notes","paymentTerms"])if(body[key]!==undefined)patch[key]=optionalText(body[key],1000);if(body.dueDate!==undefined)patch.dueDate=body.dueDate?isoDate(body.dueDate,"Vencimiento"):null;if(body.paymentTermsDays!==undefined)patch.paymentTermsDays=Math.max(0,Math.min(365,Number(body.paymentTermsDays)||0));
    if(invoice.status==="PENDING_APPROVAL"&&body.lines!==undefined){patch.status="DRAFT";patch.approvalRequired=false;}
    await guarded(()=>this.repo.update("invoices",id,patch));await this.repo.audit(actor,"INVOICE_DRAFT_UPDATED","INVOICE",id,`${documentLabel(invoice)} actualizada`,{before:{totalAmount:invoice.totalAmount},patch:Object.keys(patch)});return this.get(id,actor);
  }
  async submit(id:string,actor:FinanceActor){
    this.ctx.requireAny(actor,"invoice.edit","invoice.create");const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");await this.ctx.assertClientAccess(actor,invoice.clientId);if(invoice.status!=="DRAFT")throw new ConflictException("Sólo se envía un borrador.");
    const settings=await this.repo.settings();const threshold=settings.invoiceApprovalThreshold===null||settings.invoiceApprovalThreshold===undefined?null:Number(settings.invoiceApprovalThreshold);const required=Boolean(settings.invoiceRequiresApproval)&&(threshold===null||invoice.totalAmount>=threshold);
    await this.repo.update("invoices",id,{status:required?"PENDING_APPROVAL":"READY_TO_ISSUE",approvalRequired:required});
    if(required)await this.repo.notify({eventKey:`invoice-approval:${id}:${nowIso().slice(0,16)}`,type:"INVOICE_APPROVAL_REQUIRED",title:`Aprobar ${documentLabel(invoice)}`,body:`${invoice.clientSnapshot.legalName??""} · ${money(invoice.totalAmount,invoice.currency)}`,entityType:"INVOICE",entityId:id,href:`/finance/invoices?invoice=${id}`,severity:"WARNING",audienceRole:"FINANZAS"});
    await this.repo.audit(actor,"INVOICE_SUBMITTED","INVOICE",id,required?"Enviada a aprobación":"Lista para emitir (política sin aprobación)");return this.get(id,actor);
  }
  async approve(id:string,actor:FinanceActor){this.ctx.require(actor,"invoice.approve");const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");if(invoice.status!=="PENDING_APPROVAL")throw new ConflictException("La factura no está pendiente de aprobación.");if(invoice.createdBy&&invoice.createdBy===actor.userId&&actor.role!=="GERENTE_GENERAL")throw new ConflictException("Segregación de funciones: quien crea el documento no lo aprueba.");await this.repo.update("invoices",id,{status:"READY_TO_ISSUE",approvedBy:actor.userId,approvedAt:nowIso()});await this.repo.audit(actor,"INVOICE_APPROVED","INVOICE",id,`${documentLabel(invoice)} aprobada`);return this.get(id,actor);}
  async reject(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"invoice.approve");const reason=requiredText(body.reason,"Motivo",500);const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");if(invoice.status!=="PENDING_APPROVAL")throw new ConflictException("La factura no está pendiente de aprobación.");await this.repo.update("invoices",id,{status:"DRAFT",notes:[invoice.notes,`Rechazada: ${reason}`].filter(Boolean).join("\n")});await this.repo.audit(actor,"INVOICE_REJECTED","INVOICE",id,`Aprobación rechazada: ${reason}`);return this.get(id,actor);}
  async cancel(id:string,body:Row,actor:FinanceActor){this.ctx.requireAny(actor,"invoice.edit","invoice.approve");const reason=requiredText(body.reason,"Motivo",500);const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");if(!preIssue.includes(invoice.status))throw new ConflictException("Un documento emitido no se anula ni se borra: emite una nota de crédito.");await this.repo.update("invoices",id,{status:"CANCELLED",cancelledAt:nowIso(),cancelReason:reason});const run=await this.repo.findOne<Row>("billing_schedule_runs",{invoiceId:id});await this.repo.audit(actor,"INVOICE_CANCELLED","INVOICE",id,`Borrador anulado: ${reason}`,{billingRun:run?.id??null});return this.get(id,actor);}

  /** Se invoca al fijar la fecha de emisión: recalcula IVA vigente a esa fecha y congela snapshot del receptor. */
  async prepareForIssue(id:string,issueDate:string){
    const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");if(invoice.status!=="READY_TO_ISSUE")throw new ConflictException(invoice.status==="PENDING_APPROVAL"?"La factura requiere aprobación antes de emitir.":`La factura está ${invoice.status}; debe estar lista para emitir.`);
    const lines=await this.repo.list<InvoiceLine>("invoice_lines",{invoiceId:id});const totals=[56,61].includes(invoice.documentTypeCode)&&invoice.totalAmount===0?{}:await this.totals(lines,invoice.documentTypeCode,issueDate);const{snapshot}=await this.snapshot(invoice.clientId);
    const dueDate=invoice.dueDate&&invoice.dueDate>=issueDate?invoice.dueDate:addDays(issueDate,invoice.paymentTermsDays??0);
    return this.repo.update<Invoice>("invoices",id,{...totals,clientSnapshot:snapshot,issueDate,dueDate});
  }
  /** Transición a ISSUED: sólo tras aceptación del SII (o registro de emisión externa con evidencia). */
  async markIssued(id:string,taxDocumentId:string,folio:number|null,actor:FinanceActor){
    const invoice=await this.ctx.must<Invoice>("invoices",id,"Factura");if(!["ISSUING","READY_TO_ISSUE"].includes(invoice.status))return invoice;
    const updated=await this.repo.update<Invoice>("invoices",id,{status:"ISSUED",taxDocumentId,issuedAt:nowIso()});const label=documentLabel(updated,folio);
    // Una NC no es cuenta por cobrar: rebaja el saldo del original; el exceso (original ya pagado) queda como saldo a favor a resolver.
    if(updated.documentTypeCode===61&&updated.referenceInvoiceId){const original=await this.ctx.must<Invoice>("invoices",updated.referenceInvoiceId,"Documento referenciado");const credit=Math.min(updated.totalAmount,original.balanceDue);const excess=r2(updated.totalAmount-credit);if(credit>0){await this.repo.update("invoices",original.id,{amountCredited:r2(original.amountCredited+credit)});await this.repo.refreshInvoiceBalance(original.id);}await this.repo.update("invoices",id,{status:"CREDITED",amountCredited:updated.totalAmount});
      if(excess>0)await this.repo.event({aggregateType:"INVOICE",aggregateId:id,eventType:"CREDIT_NOTE_EXCESS",actorId:actor.userId,clientId:updated.clientId,title:`Saldo a favor del cliente por ${money(excess,updated.currency)} (NC sobre documento pagado)`,payload:{excess,originalId:original.id}});}
    const lines=await this.repo.list<InvoiceLine>("invoice_lines",{invoiceId:id});const revenueAccountId=lines.find((l)=>l.revenueAccountId)?.revenueAccountId??null;const costCenterId=lines.find((l)=>l.costCenterId)?.costCenterId??null;
    await this.rules.record({eventType:updated.documentTypeCode===61?"CREDIT_NOTE_ISSUED":"INVOICE_ISSUED",sourceType:"INVOICE",sourceId:id,idempotencyKey:`invoice-issued:${id}`,amounts:{TOTAL:updated.totalAmount,NET:updated.netAmount,EXEMPT:updated.exemptAmount,TAX:updated.taxAmount},context:{clientId:updated.clientId,projectId:updated.projectId,serviceId:updated.clientServiceId,revenueAccountId,costCenterId,documentLabel:label},occurredOn:updated.issueDate??todayCl()},actor);
    await this.repo.event({aggregateType:"INVOICE",aggregateId:id,eventType:updated.documentTypeCode===61?"CREDIT_NOTE_ISSUED":"INVOICE_ISSUED",actorId:actor.userId,clientId:updated.clientId,projectId:updated.projectId,title:`${label} emitida por ${money(updated.totalAmount,updated.currency)}`,payload:{folio,totalAmount:updated.totalAmount,dueDate:updated.dueDate}});
    await this.repo.audit(actor,"INVOICE_ISSUED","INVOICE",id,`${label} emitida`,{taxDocumentId,folio});return this.ctx.must<Invoice>("invoices",id,"Factura");
  }

  // ---------------------------------------------------------------------------------- documentos de referencia
  async creditNote(id:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"dte.credit_note");const original=await this.ctx.must<Invoice>("invoices",id,"Factura");if(![33,34,56].includes(original.documentTypeCode)||!["ISSUED","PARTIALLY_PAID","PAID"].includes(original.status))throw new ConflictException("Sólo se emiten notas de crédito sobre documentos emitidos.");
    const reason=requiredText(body.reason,"Motivo de la nota de crédito",90);const code=Number(oneOf(String(body.referenceCode??"3"),["1","2","3"],"Código de referencia"));
    const credited=sum((await this.repo.list<Invoice>("invoices",{referenceInvoiceId:id,documentTypeCode:61,status:{notIn:["CANCELLED","VOID"]}})).map((n)=>n.totalAmount));const available=r2(original.totalAmount-credited);
    const originalLines=await this.repo.list<InvoiceLine>("invoice_lines",{invoiceId:id},{order:"lineNumber",ascending:true});
    const lines=code===1?originalLines.map((l)=>({description:l.description,quantity:l.quantity,unitPrice:l.unitPrice,discountAmount:l.discountAmount,isExempt:l.isExempt,clientServiceId:l.clientServiceId,projectId:l.projectId,costCenterId:l.costCenterId,revenueAccountId:l.revenueAccountId})):code===2?[{description:`Corrige texto: ${reason}`,quantity:1,unitPrice:0,isExempt:original.netAmount===0}]:body.lines;
    if(code===1&&credited>0)throw new ConflictException("El documento ya tiene notas de crédito; anula el saldo con una nota que corrija montos.");
    const draft=await this.createDraft({clientId:original.clientId,documentTypeCode:61,lines,projectId:original.projectId,saleId:original.saleId,contractId:original.contractId,clientServiceId:original.clientServiceId,description:reason,paymentTermsDays:0},actor,{referenceInvoiceId:id,referenceCode:code,referenceReason:reason,system:true});
    if(code!==2&&draft.totalAmount>available){await this.repo.update("invoices",draft.id,{status:"CANCELLED",cancelledAt:nowIso(),cancelReason:"Excede el monto disponible para acreditar"});throw new UnprocessableEntityException(`La nota de crédito (${money(draft.totalAmount)}) excede el monto acreditable (${money(available)}).`);}
    return draft;
  }
  async debitNote(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"dte.debit_note");const original=await this.ctx.must<Invoice>("invoices",id,"Factura");if(![33,34,61].includes(original.documentTypeCode)||["DRAFT","PENDING_APPROVAL","READY_TO_ISSUE","ISSUING","CANCELLED","VOID"].includes(original.status))throw new ConflictException("Sólo se emiten notas de débito sobre documentos emitidos.");const reason=requiredText(body.reason,"Motivo de la nota de débito",90);return this.createDraft({clientId:original.clientId,documentTypeCode:56,lines:body.lines,projectId:original.projectId,description:reason},actor,{referenceInvoiceId:id,referenceCode:3,referenceReason:reason,system:true});}

  // ---------------------------------------------------------------------------------- orígenes: venta, contrato, servicio
  async fromSale(saleId:string,actor:FinanceActor){
    this.ctx.require(actor,"invoice.create");const sale=await this.ctx.sources.sale(saleId);if(!sale||sale.status!=="WON")throw new UnprocessableEntityException("La venta no existe o no está ganada.");if(!sale.clientId)throw new UnprocessableEntityException("La venta no tiene cliente asociado; conviértelo en cliente antes de facturar.");
    const pending=(await this.pendingToInvoice(actor)).find((p)=>p.saleId===saleId);if(!pending||pending.pending<=0)throw new ConflictException("La venta ya está facturada por completo.");
    const items=await this.ctx.sources.quoteItems(sale.quoteId);const lines=items.length?items.map((item)=>({description:item.description,quantity:item.quantity,unitPrice:item.unitPrice,discountAmount:roundCurrency(item.quantity*item.unitPrice*item.discountPercent/100),isExempt:!item.taxable,catalogServiceId:item.catalogServiceId})):[{description:"Venta según cotización aceptada",quantity:1,unitPrice:sale.amount}];
    return this.createDraft({clientId:sale.clientId,saleId,contractId:sale.contractId,lines,description:"Facturación de venta ganada",currency:sale.currency},actor);
  }
  async fromContract(contractId:string,actor:FinanceActor){this.ctx.require(actor,"invoice.create");const contract=await this.ctx.sources.contract(contractId);if(!contract)throw new UnprocessableEntityException("Contrato no encontrado.");if(!(contract.subtotal>0))throw new UnprocessableEntityException("El contrato no tiene un monto neto para facturar.");return this.createDraft({clientId:contract.clientId,contractId,lines:[{description:`${contract.name} (${contract.contractNumber})`,quantity:1,unitPrice:contract.subtotal,isExempt:contract.tax===0}],currency:contract.currency},actor);}
  async fromClientService(serviceId:string,actor:FinanceActor){this.ctx.require(actor,"invoice.create");const service=await this.ctx.sources.clientService(serviceId);if(!service)throw new UnprocessableEntityException("Servicio no encontrado.");if(!(Number(service.agreedPrice)>0))throw new UnprocessableEntityException("El servicio no tiene precio acordado.");return this.createDraft({clientId:service.clientId,clientServiceId:serviceId,contractId:service.contractId,projectId:service.projectId,lines:[{description:service.serviceName,quantity:1,unitPrice:Number(service.agreedPrice),clientServiceId:serviceId,projectId:service.projectId}],currency:service.currency},actor);}
  /** Ventas ganadas aún no facturadas por completo. Nunca genera facturas automáticamente. */
  async pendingToInvoice(actor:FinanceActor){
    this.ctx.require(actor,"invoice.view");const allowed=await this.ctx.clientFilter(actor);const sales=(await this.ctx.sources.wonSales()).filter((s)=>s.clientId&&(!allowed||allowed.includes(s.clientId)));if(!sales.length)return[];
    const invoices=await this.repo.list<Invoice>("invoices",{saleId:sales.map((s)=>s.id),status:{notIn:["CANCELLED","VOID"]}});const names=await this.ctx.sources.clientNames(sales.map((s)=>s.clientId));
    return sales.map((sale)=>{const invoiced=sum(invoices.filter((i)=>i.saleId===sale.id).map((i)=>i.documentTypeCode===61?-i.totalAmount:i.totalAmount));return{saleId:sale.id,clientId:sale.clientId,clientName:sale.clientId?names.get(sale.clientId)??null:null,amount:sale.amount,invoiced,pending:r2(sale.amount-invoiced),currency:sale.currency,closedAt:sale.closedAt};}).filter((p)=>p.pending>0).sort((a,b)=>a.closedAt.localeCompare(b.closedAt));
  }
  /** Cambios aprobados con impacto en costo: candidatos a facturar (Finanzas decide). */
  async billableChangeRequests(actor:FinanceActor){this.ctx.require(actor,"invoice.view");const changes=(await this.ctx.sources.approvedChangeRequests()).filter((c)=>Number(c.costImpact)>0);const linked=changes.length?await this.repo.list<Row>("finance_events",{eventType:"CHANGE_REQUEST_INVOICED",aggregateId:changes.map((c)=>c.id)}):[];const done=new Set(linked.map((e)=>e.aggregateId));return changes.filter((c)=>!done.has(c.id));}
}

// =========================================================================================== Programación de facturación recurrente
const frequencies=["MONTHLY","QUARTERLY","SEMIANNUAL","ANNUAL","CUSTOM_DAYS"] as const;
export const nextDate=(date:string,frequency:BillingSchedule["frequency"],intervalDays:number|null)=>frequency==="MONTHLY"?addMonths(date,1):frequency==="QUARTERLY"?addMonths(date,3):frequency==="SEMIANNUAL"?addMonths(date,6):frequency==="ANNUAL"?addMonths(date,12):addDays(date,intervalDays??30);
export const monthlyEquivalent=(amount:number,frequency:BillingSchedule["frequency"],intervalDays:number|null)=>r2(frequency==="MONTHLY"?amount:frequency==="QUARTERLY"?amount/3:frequency==="SEMIANNUAL"?amount/6:frequency==="ANNUAL"?amount/12:amount*30/(intervalDays??30));
@Injectable()
export class BillingScheduleService {
  constructor(private readonly ctx:FinanceContext,private readonly invoices:InvoiceService){}
  private get repo(){return this.ctx.repo;}
  async list(actor:FinanceActor,clientId?:string){this.ctx.require(actor,"invoice.view");return this.ctx.withClientNames(await this.repo.list<BillingSchedule>("billing_schedules",await this.ctx.scopedFilters(actor,{},clientId??null),{order:"nextBillingDate",ascending:true}));}
  async create(body:Row,actor:FinanceActor){
    this.ctx.require(actor,"invoice.edit");let clientId=optionalUuid(body.clientId,"Cliente");const clientServiceId=optionalUuid(body.clientServiceId,"Servicio");let amount=body.amount,description=body.description,currency=body.currency,contractId=optionalUuid(body.contractId,"Contrato");
    if(clientServiceId){const service=await this.ctx.sources.clientService(clientServiceId);if(!service)throw new UnprocessableEntityException("Servicio no encontrado.");clientId=service.clientId;amount=amount??service.agreedPrice;description=description??service.serviceName;currency=currency??service.currency;contractId=contractId??service.contractId;}
    if(!clientId)throw new BadRequestException("Cliente obligatorio.");const frequency=oneOf(body.frequency,frequencies,"Frecuencia");const intervalDays=frequency==="CUSTOM_DAYS"?Math.max(1,Math.min(730,Number(body.intervalDays)||0)):null;if(frequency==="CUSTOM_DAYS"&&!intervalDays)throw new BadRequestException("Define el intervalo en días.");
    const created=await guarded(()=>this.repo.create<BillingSchedule>("billing_schedules",{clientId,clientServiceId,contractId,description:requiredText(description,"Descripción",300),frequency,intervalDays,amount:positiveAmount(amount,"Monto"),currency:currency??"CLP",isExempt:Boolean(body.isExempt),nextBillingDate:isoDate(body.nextBillingDate,"Próxima facturación"),endDate:body.endDate?isoDate(body.endDate,"Término"):null,active:true,paymentTermsDays:body.paymentTermsDays===undefined||body.paymentTermsDays===null||body.paymentTermsDays===""?null:Number(body.paymentTermsDays),revenueAccountId:optionalUuid(body.revenueAccountId,"Cuenta de ingreso"),costCenterId:optionalUuid(body.costCenterId,"Centro de costo"),createdBy:actor.userId}));
    await this.repo.audit(actor,"BILLING_SCHEDULE_CREATED","BILLING_SCHEDULE",created.id,`Programación ${created.description} (${frequency})`);return created;
  }
  async update(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"invoice.edit");const patch:Row={};if(body.active!==undefined)patch.active=Boolean(body.active);if(body.amount!==undefined)patch.amount=positiveAmount(body.amount,"Monto");if(body.nextBillingDate!==undefined)patch.nextBillingDate=isoDate(body.nextBillingDate,"Próxima facturación");if(body.endDate!==undefined)patch.endDate=body.endDate?isoDate(body.endDate,"Término"):null;if(body.description!==undefined)patch.description=requiredText(body.description,"Descripción",300);const updated=await guarded(()=>this.repo.update<BillingSchedule>("billing_schedules",id,patch));await this.repo.audit(actor,"BILLING_SCHEDULE_UPDATED","BILLING_SCHEDULE",id,"Programación actualizada",patch);return updated;}
  /** Servicios recurrentes activos sin programación: Finanzas decide crearla (sin automatismos ocultos). */
  async suggestions(actor:FinanceActor){this.ctx.require(actor,"invoice.view");const services=await this.ctx.sources.activeRecurringServices();const schedules=await this.repo.list<BillingSchedule>("billing_schedules",{active:true});const covered=new Set(schedules.map((s)=>s.clientServiceId));const names=await this.ctx.sources.clientNames(services.map((s)=>s.clientId));return services.filter((s)=>!covered.has(s.id)).map((s)=>({clientServiceId:s.id,clientId:s.clientId,clientName:names.get(s.clientId)??null,serviceName:s.serviceName,amount:Number(s.agreedPrice),currency:s.currency,billingFrequency:s.billingFrequency,startDate:s.startDate}));}
  /** Genera BORRADORES para las programaciones vencidas; idempotente por (programación, período). Nunca emite. */
  async runDue(asOf:string,actor:FinanceActor){
    const settings=await this.repo.settings();const due=(await this.repo.list<BillingSchedule>("billing_schedules",{active:true,nextBillingDate:{lte:asOf}},{order:"nextBillingDate",ascending:true}));const created:string[]=[],skipped:string[]=[];
    for(const schedule of due){let date=schedule.nextBillingDate;let guard=0;
      while(date<=asOf&&(!schedule.endDate||date<=schedule.endDate)&&guard++<24){
        let run:Row|null=null;try{run=await this.repo.create<Row>("billing_schedule_runs",{scheduleId:schedule.id,periodKey:date,invoiceId:null});}catch{skipped.push(`${schedule.id}:${date}`);}
        if(run&&settings.autoCreateBillingDrafts){const invoice=await this.invoices.createDraft({clientId:schedule.clientId,clientServiceId:schedule.clientServiceId,contractId:schedule.contractId,currency:schedule.currency,paymentTermsDays:schedule.paymentTermsDays??undefined,description:`${schedule.description} · período desde ${displayDate(date)}`,lines:[{description:`${schedule.description} (${displayDate(date)} – ${displayDate(addDays(nextDate(date,schedule.frequency,schedule.intervalDays),-1))})`,quantity:1,unitPrice:schedule.amount,isExempt:schedule.isExempt,clientServiceId:schedule.clientServiceId,revenueAccountId:schedule.revenueAccountId,costCenterId:schedule.costCenterId}]},actor,{billingScheduleId:schedule.id,system:true});await this.repo.update("billing_schedule_runs",run.id,{invoiceId:invoice.id});created.push(invoice.id);}
        date=nextDate(date,schedule.frequency,schedule.intervalDays);}
      await this.repo.update("billing_schedules",schedule.id,{nextBillingDate:date,active:!schedule.endDate||date<=schedule.endDate});}
    return{schedules:due.length,draftsCreated:created.length,skipped:skipped.length,invoiceIds:created,draftsEnabled:Boolean(settings.autoCreateBillingDrafts)};
  }
}
export const sumAllocations=(rows:PaymentAllocation[])=>sum(rows.filter((r)=>!r.reversedAt).map((r)=>r.amount));
