import { BadRequestException, ConflictException, ForbiddenException, Injectable, UnprocessableEntityException } from "@nestjs/common";
import type { ApprovalPolicy, ApprovalRequest, Expense, ExpenseCategory, Payable, ReceivedTaxDocument, Vendor, VendorPayment } from "@zyteron/contracts";
import { can } from "./finance.access.js";
import { FinanceContext } from "./finance.core.js";
import { decodeUpload } from "./finance.dte.js";
import { AccountingRuleEngine } from "./finance.ledger.js";
import { agingReport } from "./finance.payments.js";
import type { PageQuery } from "./finance.repository.js";
import { addDays, decryptSecret, encryptionConfigured, encryptSecret, type FinanceActor, guarded, isoDate, last4, money, nonNegative, nowIso, oneOf, optionalText, optionalUuid, positiveAmount, r2, requiredText, requiredUuid, requireRut, type Row, sum, todayCl } from "./finance.util.js";

const toVendor=(row:Row):Vendor=>{const{bankAccountEncrypted,...rest}=row;return{...(rest as Vendor),hasEncryptedBankAccount:Boolean(bankAccountEncrypted)};};
export const withPayableStatus=(p:Payable,today=todayCl()):Payable=>({...p,effectiveStatus:["APPROVED","SCHEDULED","PARTIALLY_PAID","PENDING_REVIEW"].includes(p.status)&&p.dueDate<today&&p.balance>0?"OVERDUE":p.status});

// =========================================================================================== Proveedores
@Injectable()
export class VendorService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  async list(q:PageQuery&{status?:string},actor:FinanceActor){this.ctx.require(actor,"payable.view");const page=await this.repo.page<Row>("vendors",{status:q.status||undefined},{...q,order:"legalName",ascending:true,searchColumns:["legalName","tradeName","rut","email"]});return{...page,items:page.items.map(toVendor)};}
  private bank(body:Row){
    const out:Row={};if(body.bankName!==undefined)out.bankName=optionalText(body.bankName,80);if(body.bankAccountType!==undefined)out.bankAccountType=optionalText(body.bankAccountType,40);if(body.bankHolderRut)out.bankHolderRut=requireRut(body.bankHolderRut,"RUT del titular");
    if(body.bankAccountNumber){const digits=String(body.bankAccountNumber).replace(/\D/g,"");if(digits.length<4)throw new BadRequestException("Número de cuenta inválido.");if(!encryptionConfigured())throw new ConflictException("FINANCE_ENCRYPTION_KEY no configurada: registra sólo los últimos 4 dígitos.");out.bankAccountEncrypted=encryptSecret(digits);out.bankAccountLast4=last4(digits);}
    else if(body.bankAccountLast4!==undefined)out.bankAccountLast4=body.bankAccountLast4?last4(body.bankAccountLast4):null;return out;
  }
  async create(body:Row,actor:FinanceActor){this.ctx.requireAny(actor,"expense.create","payable.approve");const vendor=await guarded(()=>this.repo.create<Row>("vendors",{rut:requireRut(body.rut,"RUT del proveedor"),legalName:requiredText(body.legalName,"Razón social",200),tradeName:optionalText(body.tradeName,200),businessActivity:optionalText(body.businessActivity,200),contactName:optionalText(body.contactName,120),email:optionalText(body.email,160),phone:optionalText(body.phone,40),address:optionalText(body.address,200),paymentTermsDays:Math.max(0,Math.min(365,Number(body.paymentTermsDays??30)||0)),status:"ACTIVE",defaultExpenseCategoryId:optionalUuid(body.defaultExpenseCategoryId,"Categoría"),createdBy:actor.userId,...this.bank(body)}));await this.repo.audit(actor,"VENDOR_CREATED","VENDOR",vendor.id,`Proveedor ${vendor.legalName} (${vendor.rut})`);return toVendor(vendor);}
  async update(id:string,body:Row,actor:FinanceActor){this.ctx.requireAny(actor,"expense.create","payable.approve");const patch:Row={...this.bank(body)};for(const key of ["tradeName","businessActivity","contactName","email","phone","address"])if(body[key]!==undefined)patch[key]=optionalText(body[key],200);if(body.legalName!==undefined)patch.legalName=requiredText(body.legalName,"Razón social",200);if(body.paymentTermsDays!==undefined)patch.paymentTermsDays=Math.max(0,Math.min(365,Number(body.paymentTermsDays)||0));if(body.status!==undefined)patch.status=oneOf(body.status,["ACTIVE","INACTIVE","BLOCKED"] as const,"Estado");if(body.defaultExpenseCategoryId!==undefined)patch.defaultExpenseCategoryId=optionalUuid(body.defaultExpenseCategoryId,"Categoría");const updated=await this.repo.update<Row>("vendors",id,patch);await this.repo.audit(actor,"VENDOR_UPDATED","VENDOR",id,`Proveedor ${updated.legalName} actualizado`,{fields:Object.keys(patch).filter((k)=>k!=="bankAccountEncrypted")});return toVendor(updated);}
  /** Vista 360 del proveedor: documentos, gastos, cuentas por pagar y pagos. */
  async get(id:string,actor:FinanceActor){this.ctx.require(actor,"payable.view");const vendor=toVendor(await this.ctx.must<Row>("vendors",id,"Proveedor"));const[payables,expenses,payments,documents]=await Promise.all([this.repo.list<Payable>("payables",{vendorId:id},{order:"dueDate"}),this.repo.list<Expense>("expenses",{vendorId:id},{order:"expenseDate"}),this.repo.list<VendorPayment>("vendor_payments",{vendorId:id},{order:"createdAt"}),this.repo.list<ReceivedTaxDocument>("received_tax_documents",{issuerRut:vendor.rut},{order:"issueDate"})]);return{vendor,payables:payables.map((p)=>withPayableStatus(p)),expenses,payments,documents,totals:{outstanding:sum(payables.filter((p)=>!["PAID","CANCELLED"].includes(p.status)).map((p)=>p.balance)),purchasedYtd:sum(expenses.filter((e)=>e.status==="APPROVED"&&e.expenseDate.startsWith(todayCl().slice(0,4))).map((e)=>e.totalAmount))}};}
  /** Datos bancarios completos sólo para ejecutar un pago; queda auditado. */
  async bankDetails(id:string,actor:FinanceActor){this.ctx.require(actor,"payable.pay");const vendor=await this.ctx.must<Row>("vendors",id,"Proveedor");if(!vendor.bankAccountEncrypted)throw new UnprocessableEntityException("El proveedor no tiene cuenta bancaria cifrada registrada.");await this.repo.audit(actor,"VENDOR_BANK_REVEALED","VENDOR",id,"Datos bancarios consultados para pago");return{bankName:vendor.bankName,bankAccountType:vendor.bankAccountType,accountNumber:decryptSecret(vendor.bankAccountEncrypted),holderRut:vendor.bankHolderRut??vendor.rut};}
  categories(){return this.repo.list<ExpenseCategory>("expense_categories",{},{order:"code",ascending:true});}
  async saveCategory(id:string|null,body:Row,actor:FinanceActor){this.ctx.requireAny(actor,"finance.settings.manage","journal.review");const account=await this.ctx.must<Row>("chart_of_accounts",requiredUuid(body.expenseAccountId,"Cuenta de gasto"),"Cuenta");if(!account.allowsPosting||!["EXPENSE","ASSET"].includes(account.accountType))throw new UnprocessableEntityException("La cuenta debe ser imputable de gasto o activo.");const data:Row={name:requiredText(body.name,"Nombre",120),expenseAccountId:account.id,defaultCostCenterId:optionalUuid(body.defaultCostCenterId,"Centro de costo"),active:body.active!==false};const saved=id?await this.repo.update("expense_categories",id,data):await guarded(()=>this.repo.create("expense_categories",{...data,code:requiredText(body.code,"Código",30).toUpperCase()}));await this.repo.audit(actor,id?"CATEGORY_UPDATED":"CATEGORY_CREATED","EXPENSE_CATEGORY",(saved as Row).id,`Categoría ${(saved as Row).code}`);return saved;}
}

// =========================================================================================== Aprobaciones configurables (sin límites hardcodeados)
@Injectable()
export class ApprovalService {
  constructor(private readonly ctx:FinanceContext){}
  private get repo(){return this.ctx.repo;}
  policies(actor:FinanceActor){this.ctx.requireAny(actor,"expense.view","payable.view");return this.repo.list<ApprovalPolicy>("approval_policies",{},{order:"minAmount",ascending:true});}
  async savePolicy(id:string|null,body:Row,actor:FinanceActor){this.ctx.require(actor,"finance.settings.manage");const min=nonNegative(body.minAmount,"Monto mínimo");const max=body.maxAmount===undefined||body.maxAmount===null||body.maxAmount===""?null:nonNegative(body.maxAmount,"Monto máximo");if(max!==null&&max<min)throw new BadRequestException("El máximo debe ser mayor o igual al mínimo.");
    const data:Row={entityType:oneOf(body.entityType,["EXPENSE","PAYABLE","VENDOR_PAYMENT","INVOICE","JOURNAL_ENTRY","COMMISSION"] as const,"Entidad"),name:requiredText(body.name,"Nombre",120),minAmount:min,maxAmount:max,categoryId:optionalUuid(body.categoryId,"Categoría"),costCenterId:optionalUuid(body.costCenterId,"Centro de costo"),departmentCode:optionalText(body.departmentCode,40),approverRole:requiredText(body.approverRole,"Rol aprobador",40),approverUserId:optionalUuid(body.approverUserId,"Usuario aprobador"),level:Math.max(1,Math.min(5,Number(body.level)||1)),active:body.active!==false};
    const saved=id?await this.repo.update("approval_policies",id,data):await this.repo.create("approval_policies",{...data,createdBy:actor.userId});await this.repo.audit(actor,id?"APPROVAL_POLICY_UPDATED":"APPROVAL_POLICY_CREATED","APPROVAL_POLICY",(saved as Row).id,`Política ${data.name}`,data);return saved;}
  /** Crea solicitudes por nivel según políticas activas que calzan con monto/categoría/centro/departamento. */
  async request(entityType:string,entityId:string,amount:number,attrs:{categoryId?:string|null;costCenterId?:string|null;departmentCode?:string|null},actor:FinanceActor){
    const policies=(await this.repo.list<ApprovalPolicy>("approval_policies",{entityType,active:true})).filter((p)=>amount>=p.minAmount&&(p.maxAmount===null||amount<=p.maxAmount)&&(!p.categoryId||p.categoryId===attrs.categoryId)&&(!p.costCenterId||p.costCenterId===attrs.costCenterId)&&(!p.departmentCode||p.departmentCode===attrs.departmentCode));
    const levels=new Map<number,ApprovalPolicy>();for(const policy of policies.sort((a,b)=>a.level-b.level))if(!levels.has(policy.level))levels.set(policy.level,policy);
    const existing=await this.repo.list<ApprovalRequest>("approval_requests",{entityType,entityId});for(const request of existing.filter((r)=>r.status==="PENDING"))await this.repo.update("approval_requests",request.id,{status:"CANCELLED"});
    const base=Math.max(0,...existing.map((r)=>r.level));const requests:ApprovalRequest[]=[];
    if(!levels.size)requests.push(await this.repo.create<ApprovalRequest>("approval_requests",{entityType,entityId,policyId:null,level:base+1,requiredRole:"ANY_APPROVER",requiredUserId:null,status:"PENDING",requestedBy:actor.userId}));
    else{let n=base;for(const policy of levels.values())requests.push(await this.repo.create<ApprovalRequest>("approval_requests",{entityType,entityId,policyId:policy.id,level:++n,requiredRole:policy.approverRole,requiredUserId:policy.approverUserId,status:"PENDING",requestedBy:actor.userId}));}
    return requests;
  }
  async forEntity(entityType:string,entityId:string){return this.repo.list<ApprovalRequest>("approval_requests",{entityType,entityId},{order:"level",ascending:true});}
  /** Decide el nivel pendiente más bajo. Segregación: quien solicita no aprueba. */
  async decide(entityType:string,entityId:string,decision:"APPROVED"|"REJECTED",comment:string|null,actor:FinanceActor,permission:"expense.approve"|"payable.approve"){
    this.ctx.require(actor,permission);const pending=(await this.forEntity(entityType,entityId)).filter((r)=>r.status==="PENDING").sort((a,b)=>a.level-b.level);const current=pending[0];if(!current)throw new ConflictException("No hay aprobaciones pendientes.");
    if(current.requestedBy&&current.requestedBy===actor.userId&&actor.role!=="GERENTE_GENERAL")throw new ForbiddenException("Segregación de funciones: quien solicita no puede aprobar.");
    if(current.requiredUserId&&current.requiredUserId!==actor.userId)throw new ForbiddenException("Esta aprobación está asignada a otro usuario.");if(current.requiredRole!=="ANY_APPROVER"&&current.requiredRole!==actor.role&&actor.role!=="GERENTE_GENERAL")throw new ForbiddenException(`Este nivel lo aprueba el rol ${current.requiredRole}.`);
    if(decision==="REJECTED"&&!comment)throw new BadRequestException("El rechazo requiere comentario.");
    await this.repo.update("approval_requests",current.id,{status:decision,decidedBy:actor.userId,decidedAt:nowIso(),comment});if(decision==="REJECTED")for(const other of pending.slice(1))await this.repo.update("approval_requests",other.id,{status:"CANCELLED"});
    return{completed:decision==="REJECTED"||pending.length===1,approved:decision==="APPROVED"&&pending.length===1,level:current.level};
  }
  async inbox(actor:FinanceActor){const pending=await this.repo.list<ApprovalRequest>("approval_requests",{status:"PENDING"},{order:"createdAt",ascending:true});const lowest=new Map<string,ApprovalRequest>();for(const r of pending){const key=`${r.entityType}:${r.entityId}`;const cur=lowest.get(key);if(!cur||r.level<cur.level)lowest.set(key,r);}return[...lowest.values()].filter((r)=>(r.requiredRole==="ANY_APPROVER"?can(actor.role,r.entityType==="EXPENSE"?"expense.approve":"payable.approve"):r.requiredRole===actor.role||actor.role==="GERENTE_GENERAL")&&(!r.requiredUserId||r.requiredUserId===actor.userId));}
}

// =========================================================================================== Gastos
const creditClasses=["PENDING_REVIEW","DEL_GIRO","SUPERMERCADO","BIENES_RAICES","ACTIVO_FIJO","USO_COMUN","NO_RECUPERABLE","NO_CORRESPONDE"] as const;
@Injectable()
export class ExpenseService {
  constructor(private readonly ctx:FinanceContext,private readonly approvals:ApprovalService,private readonly rules:AccountingRuleEngine){}
  private get repo(){return this.ctx.repo;}
  async list(q:PageQuery&{status?:string;vendorId?:string;categoryId?:string;from?:string;to?:string},actor:FinanceActor){this.ctx.require(actor,"expense.view");const page=await this.repo.page<Expense>("expenses",{status:q.status||undefined,vendorId:q.vendorId||undefined,categoryId:q.categoryId||undefined,expenseDate:q.from||q.to?{gte:q.from||undefined,lte:q.to||undefined}:undefined},{...q,order:"expenseDate",searchColumns:["expenseNumber","description","documentNumber"]});return{...page,items:await this.ctx.withVendorNames(page.items)};}
  async get(id:string,actor:FinanceActor){this.ctx.require(actor,"expense.view");const expense=await this.ctx.must<Expense>("expenses",id,"Gasto");const[named]=await this.ctx.withVendorNames([expense]);return{...named!,approvals:await this.approvals.forEntity("EXPENSE",id)};}
  private amounts(body:Row){const net=nonNegative(body.netAmount,"Neto"),exempt=nonNegative(body.exemptAmount,"Exento"),tax=nonNegative(body.taxAmount,"IVA");const total=r2(net+exempt+tax);if(total<=0)throw new BadRequestException("El gasto debe tener monto.");if(body.totalAmount!==undefined&&r2(body.totalAmount)!==total)throw new BadRequestException(`El total (${money(r2(body.totalAmount))}) no coincide con neto + exento + IVA (${money(total)}).`);return{netAmount:net,exemptAmount:exempt,taxAmount:tax,totalAmount:total};}
  async create(body:Row,actor:FinanceActor){
    this.ctx.require(actor,"expense.create");const categoryId=requiredUuid(body.categoryId,"Categoría");const category=await this.ctx.must<ExpenseCategory>("expense_categories",categoryId,"Categoría");const evidence=body.evidence?decodeUpload(body.evidence,"Respaldo"):null;
    const expense=await guarded(async()=>this.repo.create<Expense>("expenses",{vendorId:optionalUuid(body.vendorId,"Proveedor"),receivedTaxDocumentId:optionalUuid(body.receivedTaxDocumentId,"Documento recibido"),expenseDate:isoDate(body.expenseDate,"Fecha del gasto"),documentTypeCode:body.documentTypeCode?Number(body.documentTypeCode):null,documentNumber:optionalText(body.documentNumber,40),categoryId,description:requiredText(body.description,"Descripción",500),...this.amounts(body),currency:"CLP",taxCreditClassification:"PENDING_REVIEW",taxCreditEligible:null,eligibleTaxAmount:0,classificationReason:null,costCenterId:optionalUuid(body.costCenterId,"Centro de costo")??category.defaultCostCenterId,projectId:optionalUuid(body.projectId,"Proyecto"),clientId:optionalUuid(body.clientId,"Cliente"),departmentCode:optionalText(body.departmentCode,40),responsibleUserId:optionalUuid(body.responsibleUserId,"Responsable")??actor.userId,paymentMethod:body.paymentMethod?oneOf(body.paymentMethod,["TRANSFER","CARD","CASH","CHECK","OTHER"] as const,"Medio de pago"):null,evidencePath:evidence?await this.repo.saveFile("finance-documents",`expenses/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType):null,evidenceSha256:evidence?.sha256??null,status:"DRAFT",approvedBy:null,approvedAt:null,payableId:null,createdBy:actor.userId}));
    if(expense.receivedTaxDocumentId)await this.repo.update("received_tax_documents",expense.receivedTaxDocumentId,{expenseId:expense.id});await this.repo.audit(actor,"EXPENSE_CREATED","EXPENSE",expense.id,`${expense.expenseNumber} ${expense.description} por ${money(expense.totalAmount)}`);return this.get(expense.id,actor);
  }
  async fromReceivedDocument(receivedId:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"expense.create");const doc=await this.ctx.must<ReceivedTaxDocument>("received_tax_documents",receivedId,"Documento recibido");if(doc.expenseId)throw new ConflictException("El documento ya está asociado a un gasto.");if(doc.documentTypeCode===61)throw new UnprocessableEntityException("Una nota de crédito recibida se registra como ajuste, no como gasto.");
    const vendor=doc.vendorId?await this.repo.get<Row>("vendors",doc.vendorId):await this.repo.findOne<Row>("vendors",{rut:doc.issuerRut});const categoryId=optionalUuid(body.categoryId,"Categoría")??vendor?.defaultExpenseCategoryId;if(!categoryId)throw new BadRequestException("Selecciona la categoría del gasto.");
    const created=await this.create({vendorId:vendor?.id??null,receivedTaxDocumentId:receivedId,expenseDate:doc.issueDate,documentTypeCode:doc.documentTypeCode,documentNumber:String(doc.folio),categoryId,description:optionalText(body.description)??`${doc.issuerName} folio ${doc.folio}`,netAmount:doc.netAmount,exemptAmount:r2(doc.exemptAmount+(doc.totalAmount-doc.netAmount-doc.exemptAmount-doc.taxAmount)),taxAmount:doc.taxAmount,costCenterId:body.costCenterId,projectId:body.projectId,departmentCode:body.departmentCode},actor);
    if(doc.taxCreditClassification!=="PENDING_REVIEW")await this.repo.update("expenses",created.id,{taxCreditClassification:doc.taxCreditClassification,taxCreditEligible:doc.taxCreditEligible,eligibleTaxAmount:doc.taxCreditEligibleAmount??0,classificationReason:doc.classificationReason,reviewedBy:doc.reviewedBy,reviewedAt:doc.reviewedAt});return this.get(created.id,actor);
  }
  async update(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"expense.create");const expense=await this.ctx.must<Expense>("expenses",id,"Gasto");if(expense.status!=="DRAFT")throw new ConflictException("Sólo se editan gastos en borrador.");if(expense.receivedTaxDocumentId&&["netAmount","exemptAmount","taxAmount"].some((k)=>body[k]!==undefined))throw new ConflictException("Los montos de un gasto respaldado por DTE provienen del documento.");const patch:Row={};if(["netAmount","exemptAmount","taxAmount"].some((k)=>body[k]!==undefined))Object.assign(patch,this.amounts({netAmount:body.netAmount??expense.netAmount,exemptAmount:body.exemptAmount??expense.exemptAmount,taxAmount:body.taxAmount??expense.taxAmount}),{eligibleTaxAmount:0,taxCreditClassification:"PENDING_REVIEW",taxCreditEligible:null});for(const key of ["description","documentNumber","departmentCode"])if(body[key]!==undefined)patch[key]=optionalText(body[key],500);for(const key of ["categoryId","costCenterId","projectId","clientId","vendorId"])if(body[key]!==undefined)patch[key]=optionalUuid(body[key],key);if(body.expenseDate!==undefined)patch.expenseDate=isoDate(body.expenseDate,"Fecha");const updated=await guarded(()=>this.repo.update("expenses",id,patch));await this.repo.audit(actor,"EXPENSE_UPDATED","EXPENSE",id,"Gasto actualizado",{fields:Object.keys(patch)});return updated;}
  /** Clasificación de crédito fiscal explícita (no se asume IVA recuperable). */
  async classify(id:string,body:Row,actor:FinanceActor){this.ctx.requireAny(actor,"tax.review","expense.approve");const expense=await this.ctx.must<Expense>("expenses",id,"Gasto");if(!["DRAFT","PENDING_APPROVAL"].includes(expense.status))throw new ConflictException("El gasto ya fue resuelto.");const classification=oneOf(body.classification,creditClasses.filter((c)=>c!=="PENDING_REVIEW"),"Clasificación");if(typeof body.eligible!=="boolean")throw new BadRequestException("Indica explícitamente si el IVA es crédito fiscal.");const eligible=body.eligible?(body.eligibleAmount===undefined||body.eligibleAmount===null||body.eligibleAmount===""?expense.taxAmount:r2(body.eligibleAmount)):0;if(eligible<0||eligible>expense.taxAmount)throw new BadRequestException("El crédito debe estar entre 0 y el IVA.");const updated=await this.repo.update("expenses",id,{taxCreditClassification:classification,taxCreditEligible:body.eligible,eligibleTaxAmount:eligible,classificationReason:requiredText(body.reason,"Fundamento",500),reviewedBy:actor.userId,reviewedAt:nowIso()});await this.repo.audit(actor,"EXPENSE_CLASSIFIED","EXPENSE",id,`Crédito fiscal ${classification}: ${money(eligible)}`);return updated;}
  async submit(id:string,actor:FinanceActor){this.ctx.require(actor,"expense.create");const expense=await this.ctx.must<Expense>("expenses",id,"Gasto");if(expense.status!=="DRAFT")throw new ConflictException("Sólo se envía un borrador.");if(!expense.evidencePath&&!expense.receivedTaxDocumentId)throw new UnprocessableEntityException("Adjunta el respaldo del gasto antes de enviarlo a aprobación.");
    await this.approvals.request("EXPENSE",id,expense.totalAmount,{categoryId:expense.categoryId,costCenterId:expense.costCenterId,departmentCode:expense.departmentCode},actor);await this.repo.update("expenses",id,{status:"PENDING_APPROVAL"});
    await this.repo.notify({eventKey:`expense-approval:${id}:${nowIso().slice(0,16)}`,type:"EXPENSE_APPROVAL_REQUIRED",title:`Aprobar gasto ${expense.expenseNumber}`,body:`${expense.description} · ${money(expense.totalAmount)}`,entityType:"EXPENSE",entityId:id,href:`/finance/expenses?expense=${id}`,severity:"WARNING"});await this.repo.audit(actor,"EXPENSE_SUBMITTED","EXPENSE",id,"Gasto enviado a aprobación");return this.get(id,actor);}
  async decide(id:string,body:Row,actor:FinanceActor){
    const decision=oneOf(body.decision,["APPROVED","REJECTED"] as const,"Decisión");const expense=await this.ctx.must<Expense>("expenses",id,"Gasto");if(expense.status!=="PENDING_APPROVAL")throw new ConflictException("El gasto no está pendiente de aprobación.");
    if(decision==="APPROVED"&&expense.taxAmount>0&&expense.taxCreditClassification==="PENDING_REVIEW")throw new UnprocessableEntityException("Clasifica el crédito fiscal (IVA recuperable o no) antes de aprobar.");
    const result=await this.approvals.decide("EXPENSE",id,decision,optionalText(body.comment,500),actor,"expense.approve");
    if(decision==="REJECTED"){await this.repo.update("expenses",id,{status:"REJECTED"});await this.repo.audit(actor,"EXPENSE_REJECTED","EXPENSE",id,`Gasto rechazado: ${body.comment}`);return this.get(id,actor);}
    if(!result.approved){await this.repo.audit(actor,"EXPENSE_LEVEL_APPROVED","EXPENSE",id,`Nivel ${result.level} aprobado`);return this.get(id,actor);}
    await this.repo.update("expenses",id,{status:"APPROVED",approvedBy:actor.userId,approvedAt:nowIso()});const category=(await this.repo.get<ExpenseCategory>("expense_categories",expense.categoryId))!;
    if(expense.vendorId&&!["CASH","CARD"].includes(expense.paymentMethod??"")){const vendor=(await this.repo.get<Vendor>("vendors",expense.vendorId))!;const payable=await guarded(()=>this.repo.create<Payable>("payables",{vendorId:vendor.id,sourceType:expense.receivedTaxDocumentId?"RECEIVED_DTE":"EXPENSE",sourceId:expense.receivedTaxDocumentId??id,documentNumber:expense.documentNumber,description:expense.description,amount:expense.totalAmount,amountPaid:0,currency:expense.currency,issueDate:expense.expenseDate,dueDate:addDays(expense.expenseDate,vendor.paymentTermsDays),status:"APPROVED",approvedBy:actor.userId,approvedAt:nowIso(),createdBy:actor.userId}));await this.repo.update("expenses",id,{payableId:payable.id});}
    await this.rules.record({eventType:"EXPENSE_APPROVED",sourceType:"EXPENSE",sourceId:id,idempotencyKey:`expense-approved:${id}`,amounts:{NET:expense.netAmount,EXEMPT:expense.exemptAmount,TAX_ELIGIBLE:expense.eligibleTaxAmount,TAX_NON_ELIGIBLE:r2(expense.taxAmount-expense.eligibleTaxAmount),TOTAL:expense.totalAmount},context:{expenseAccountId:category.expenseAccountId,costCenterId:expense.costCenterId,projectId:expense.projectId,clientId:expense.clientId,documentLabel:`${expense.expenseNumber} ${expense.description}`.slice(0,120)},occurredOn:expense.expenseDate},actor);
    await this.repo.audit(actor,"EXPENSE_APPROVED","EXPENSE",id,`${expense.expenseNumber} aprobado`);return this.get(id,actor);
  }
  async cancel(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"expense.create");const expense=await this.ctx.must<Expense>("expenses",id,"Gasto");if(!["DRAFT","PENDING_APPROVAL"].includes(expense.status))throw new ConflictException("Un gasto aprobado se corrige con un asiento de ajuste o nota de crédito del proveedor.");await this.repo.update("expenses",id,{status:"CANCELLED"});for(const r of(await this.approvals.forEntity("EXPENSE",id)).filter((r)=>r.status==="PENDING"))await this.repo.update("approval_requests",r.id,{status:"CANCELLED"});await this.repo.audit(actor,"EXPENSE_CANCELLED","EXPENSE",id,`Gasto anulado: ${requiredText(body.reason,"Motivo",300)}`);return this.get(id,actor);}
}

// =========================================================================================== Cuentas por pagar y pagos a proveedores
@Injectable()
export class PayableService {
  constructor(private readonly ctx:FinanceContext,private readonly rules:AccountingRuleEngine){}
  private get repo(){return this.ctx.repo;}
  async list(q:PageQuery&{status?:string;vendorId?:string;overdue?:string},actor:FinanceActor){this.ctx.require(actor,"payable.view");const today=todayCl();const page=await this.repo.page<Payable>("payables",{status:q.overdue==="true"?["APPROVED","SCHEDULED","PARTIALLY_PAID","PENDING_REVIEW"]:q.status||undefined,vendorId:q.vendorId||undefined,dueDate:q.overdue==="true"?{lt:today}:undefined},{...q,order:"dueDate",ascending:true,searchColumns:["description","documentNumber"]});return{...page,items:(await this.ctx.withVendorNames(page.items)).map((p)=>withPayableStatus(p,today))};}
  async aging(actor:FinanceActor,asOf=todayCl()){this.ctx.require(actor,"payable.view");const open=(await this.ctx.withVendorNames(await this.repo.list<Payable>("payables",{status:["PENDING_REVIEW","APPROVED","SCHEDULED","PARTIALLY_PAID","DISPUTED"]}))).filter((p)=>p.balance>0);return agingReport(open.map((p)=>({partyId:p.vendorId,partyName:p.vendorName??"Proveedor",dueDate:p.dueDate,balance:p.balance})),asOf);}
  async createManual(body:Row,actor:FinanceActor){this.ctx.require(actor,"payable.approve");const vendorId=requiredUuid(body.vendorId,"Proveedor");await this.ctx.must("vendors",vendorId,"Proveedor");const evidence=decodeUpload(body.evidence,"Respaldo de la obligación");const path=await this.repo.saveFile("finance-documents",`payables/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType);const payable=await guarded(()=>this.repo.create<Payable>("payables",{vendorId,sourceType:"MANUAL",sourceId:null,documentNumber:optionalText(body.documentNumber,40),description:`${requiredText(body.description,"Descripción",300)} [respaldo ${path}]`,amount:positiveAmount(body.amount,"Monto"),amountPaid:0,currency:"CLP",issueDate:body.issueDate?isoDate(body.issueDate,"Emisión"):null,dueDate:isoDate(body.dueDate,"Vencimiento"),status:"PENDING_REVIEW",createdBy:actor.userId}));await this.repo.audit(actor,"PAYABLE_CREATED","PAYABLE",payable.id,`Obligación manual ${money(payable.amount)}`,{evidenceSha256:evidence.sha256});return payable;}
  async transition(id:string,action:"approve"|"schedule"|"dispute"|"resolve"|"cancel",body:Row,actor:FinanceActor){
    this.ctx.require(actor,"payable.approve");const payable=await this.ctx.must<Payable>("payables",id,"Cuenta por pagar");let patch:Row;
    if(action==="approve"){if(payable.status!=="PENDING_REVIEW")throw new ConflictException("Sólo se aprueba una obligación en revisión.");if(payable.createdBy===actor.userId&&actor.role!=="GERENTE_GENERAL")throw new ForbiddenException("Segregación: quien registra no aprueba.");patch={status:"APPROVED",approvedBy:actor.userId,approvedAt:nowIso()};}
    else if(action==="schedule"){if(!["APPROVED","SCHEDULED","PARTIALLY_PAID"].includes(payable.status))throw new ConflictException("Sólo se programa una obligación aprobada.");patch={status:payable.amountPaid>0?"PARTIALLY_PAID":"SCHEDULED",scheduledFor:isoDate(body.scheduledFor,"Fecha programada")};}
    else if(action==="dispute"){if(["PAID","CANCELLED"].includes(payable.status))throw new ConflictException("La obligación ya está cerrada.");patch={status:"DISPUTED",disputeReason:requiredText(body.reason,"Motivo de la disputa",500)};}
    else if(action==="resolve"){if(payable.status!=="DISPUTED")throw new ConflictException("La obligación no está en disputa.");patch={status:payable.amountPaid>0?"PARTIALLY_PAID":"APPROVED",disputeReason:null};}
    else{if(payable.amountPaid>0)throw new ConflictException("Una obligación con pagos no se anula; registra un ajuste.");patch={status:"CANCELLED",disputeReason:requiredText(body.reason,"Motivo",500)};}
    const updated=await this.repo.update<Payable>("payables",id,patch);await this.repo.audit(actor,`PAYABLE_${action.toUpperCase()}`,"PAYABLE",id,`Cuenta por pagar: ${action}`,patch);return withPayableStatus(updated);
  }
  async vendorPayments(q:PageQuery&{status?:string},actor:FinanceActor){this.ctx.require(actor,"payable.view");const page=await this.repo.page<VendorPayment>("vendor_payments",{status:q.status||undefined},{...q,order:"createdAt",searchColumns:["paymentNumber","reference"]});return{...page,items:await this.ctx.withVendorNames(page.items)};}
  async vendorPayment(id:string,actor:FinanceActor){this.ctx.require(actor,"payable.view");const payment=await this.ctx.must<VendorPayment>("vendor_payments",id,"Pago a proveedor");const allocations=await this.repo.list<Row>("vendor_payment_allocations",{vendorPaymentId:id});const[named]=await this.ctx.withVendorNames([payment]);return{...named!,allocations:allocations.map((a)=>({payableId:a.payableId,amount:a.amount}))};}
  async requestPayment(body:Row,actor:FinanceActor){
    this.ctx.require(actor,"payable.pay");const vendorId=requiredUuid(body.vendorId,"Proveedor");const vendor=await this.ctx.must<Row>("vendors",vendorId,"Proveedor");if(vendor.status==="BLOCKED")throw new ConflictException("Proveedor bloqueado.");const items=Array.isArray(body.allocations)?body.allocations:[];if(!items.length)throw new BadRequestException("Selecciona las cuentas por pagar.");
    for(const item of items){const payable=await this.ctx.must<Payable>("payables",requiredUuid(item.payableId,"Cuenta por pagar"),"Cuenta por pagar");if(payable.vendorId!==vendorId)throw new UnprocessableEntityException("Todas las obligaciones deben ser del mismo proveedor.");if(!["APPROVED","SCHEDULED","PARTIALLY_PAID"].includes(payable.status))throw new ConflictException(`La obligación ${payable.documentNumber??payable.id.slice(0,8)} no está aprobada.`);if(positiveAmount(item.amount,"Monto")>payable.balance)throw new UnprocessableEntityException("El monto excede el saldo de la obligación.");}
    const amount=sum(items.map((i:Row)=>Number(i.amount)));const payment=await this.repo.create<VendorPayment>("vendor_payments",{vendorId,amount,currency:"CLP",paymentDate:body.paymentDate?isoDate(body.paymentDate,"Fecha"):null,method:oneOf(body.method,["TRANSFER","CHECK","CASH","CARD","OTHER"] as const,"Método","TRANSFER"),reference:null,evidencePath:null,bankAccountId:optionalUuid(body.bankAccountId,"Cuenta bancaria"),bankTransactionId:null,status:"REQUESTED",requestedBy:actor.userId});
    for(const item of items)await this.repo.create("vendor_payment_allocations",{vendorPaymentId:payment.id,payableId:item.payableId,amount:r2(item.amount)});await this.repo.audit(actor,"VENDOR_PAYMENT_REQUESTED","VENDOR_PAYMENT",payment.id,`${payment.paymentNumber} solicitado por ${money(amount)}`);return this.vendorPayment(payment.id,actor);
  }
  async approvePayment(id:string,actor:FinanceActor){this.ctx.require(actor,"payable.approve");const payment=await this.ctx.must<VendorPayment>("vendor_payments",id,"Pago a proveedor");if(payment.status!=="REQUESTED")throw new ConflictException("El pago no está solicitado.");if(payment.requestedBy===actor.userId&&actor.role!=="GERENTE_GENERAL")throw new ForbiddenException("Segregación: quien solicita el pago no lo aprueba.");await this.repo.update("vendor_payments",id,{status:"APPROVED",approvedBy:actor.userId,approvedAt:nowIso()});await this.repo.audit(actor,"VENDOR_PAYMENT_APPROVED","VENDOR_PAYMENT",id,`${payment.paymentNumber} aprobado`);return this.vendorPayment(id,actor);}
  /** Zyteron no transfiere dinero: registra una transferencia ya realizada con comprobante o movimiento de cartola. */
  async executePayment(id:string,body:Row,actor:FinanceActor){
    this.ctx.require(actor,"payable.pay");const payment=await this.ctx.must<VendorPayment>("vendor_payments",id,"Pago a proveedor");if(payment.status!=="APPROVED")throw new ConflictException("El pago debe estar aprobado.");const bankTransactionId=optionalUuid(body.bankTransactionId,"Movimiento bancario");if(!body.evidence&&!bankTransactionId)throw new UnprocessableEntityException("Adjunta el comprobante de la transferencia o vincula el cargo de la cartola.");
    const evidence=body.evidence?decodeUpload(body.evidence,"Comprobante"):null;const evidencePath=evidence?await this.repo.saveFile("finance-documents",`vendor-payments/${evidence.sha256}-${evidence.fileName}`,evidence.bytes,evidence.mimeType):null;const paymentDate=isoDate(body.paymentDate??todayCl(),"Fecha de pago");
    if(bankTransactionId){const tx=await this.ctx.must<Row>("bank_transactions",bankTransactionId,"Movimiento");if(tx.direction!=="DEBIT"||r2(tx.amount-tx.reconciledAmount)<payment.amount)throw new UnprocessableEntityException("El movimiento no es un cargo o no tiene saldo conciliable suficiente.");}
    await this.repo.update("vendor_payments",id,{status:bankTransactionId?"RECONCILED":"EXECUTED",paymentDate,reference:optionalText(body.reference,120),evidencePath,bankTransactionId,executedBy:actor.userId,executedAt:nowIso()});
    for(const allocation of await this.repo.list<Row>("vendor_payment_allocations",{vendorPaymentId:id})){const payable=(await this.repo.get<Payable>("payables",allocation.payableId))!;const paid=r2(payable.amountPaid+allocation.amount);await guarded(()=>this.repo.update("payables",payable.id,{amountPaid:paid,status:paid>=payable.amount?"PAID":"PARTIALLY_PAID"}));}
    if(bankTransactionId){await guarded(()=>this.repo.create("reconciliation_matches",{bankTransactionId,targetType:"VENDOR_PAYMENT",targetId:id,amount:payment.amount,matchKind:"MATCH",confidence:null,status:"ACTIVE",createdBy:actor.userId}));await this.repo.afterMatchChange(bankTransactionId);}
    const ledger=payment.bankAccountId?(await this.repo.get<Row>("bank_accounts",payment.bankAccountId))?.ledgerAccountId:null;await this.rules.record({eventType:"VENDOR_PAYMENT_EXECUTED",sourceType:"VENDOR_PAYMENT",sourceId:id,idempotencyKey:`vendor-payment:${id}`,amounts:{AMOUNT:payment.amount},context:{paymentReference:payment.paymentNumber,cashLedgerAccountId:ledger??null},occurredOn:paymentDate},actor);
    await this.repo.audit(actor,"VENDOR_PAYMENT_EXECUTED","VENDOR_PAYMENT",id,`${payment.paymentNumber} registrado como pagado (${money(payment.amount)})`,{evidenceSha256:evidence?.sha256??null,bankTransactionId});return this.vendorPayment(id,actor);
  }
  async cancelPayment(id:string,body:Row,actor:FinanceActor){this.ctx.require(actor,"payable.pay");const payment=await this.ctx.must<VendorPayment>("vendor_payments",id,"Pago a proveedor");if(!["REQUESTED","APPROVED"].includes(payment.status))throw new ConflictException("Un pago ejecutado no se anula: registra un reverso con evidencia.");await this.repo.update("vendor_payments",id,{status:"CANCELLED"});await this.repo.audit(actor,"VENDOR_PAYMENT_CANCELLED","VENDOR_PAYMENT",id,`Pago anulado: ${requiredText(body.reason,"Motivo",300)}`);return this.vendorPayment(id,actor);}
  async dueNotifications(asOf=todayCl()){let sent=0;for(const payable of await this.repo.list<Payable>("payables",{status:["APPROVED","SCHEDULED","PARTIALLY_PAID"],dueDate:{lte:addDays(asOf,3)}})){if(payable.balance<=0)continue;if(await this.repo.notify({eventKey:`ap-due:${payable.id}:${payable.dueDate}`,type:"AP_DUE",title:payable.dueDate<asOf?"Cuenta por pagar vencida":"Cuenta por pagar por vencer",body:`${payable.description.slice(0,80)} · ${money(payable.balance)} · vence ${payable.dueDate.split("-").reverse().join("-")}`,entityType:"PAYABLE",entityId:payable.id,href:"/finance/payables",severity:payable.dueDate<asOf?"CRITICAL":"WARNING"}))sent++;}return{sent};}
}
