import { ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { Commission, CommercialEvent, QuoteItem, Sale, SalesFollowUp, SalesGoal, SalesHandoff, SalesLead, SalesOpportunity, SalesPipelineStage, SalesQuote } from "@zyteron/contracts";
import { cleanSearch, createServerSupabase, pageBounds } from "../domain/server-supabase.js";

type PageInput={page:number;pageSize:number;search?:string;status?:string;ownerId?:string;view?:string;clientId?:string};
const now=()=>new Date().toISOString();
const page=<T>(items:T[],input:PageInput)=>{const start=(input.page-1)*input.pageSize;return{items:items.slice(start,start+input.pageSize),page:input.page,pageSize:input.pageSize,total:items.length,totalPages:Math.ceil(items.length/input.pageSize)};};

@Injectable()
export class CommercialRepository {
  private readonly supabase=createServerSupabase();
  private readonly leads=new Map<string,SalesLead>();
  private readonly opportunities=new Map<string,SalesOpportunity>();
  private readonly followUps=new Map<string,SalesFollowUp>();
  private readonly quotes=new Map<string,SalesQuote>();
  private readonly sales=new Map<string,Sale>();
  private readonly goals=new Map<string,SalesGoal>();
  private readonly commissions=new Map<string,Commission>();
  private readonly handoffs=new Map<string,SalesHandoff>();
  private readonly events:CommercialEvent[]=[];
  private readonly quoteSequences=new Map<number,number>();
  private readonly memoryStages:SalesPipelineStage[]=[
    {id:"10000000-0000-4000-8000-000000000001",pipelineId:"20000000-0000-4000-8000-000000000001",code:"NEW",name:"Nuevo",position:1,probability:10,kind:"OPEN",active:true},
    {id:"10000000-0000-4000-8000-000000000002",pipelineId:"20000000-0000-4000-8000-000000000001",code:"CONTACTED",name:"Contactado",position:2,probability:20,kind:"OPEN",active:true},
    {id:"10000000-0000-4000-8000-000000000003",pipelineId:"20000000-0000-4000-8000-000000000001",code:"QUALIFICATION",name:"Calificación",position:3,probability:35,kind:"OPEN",active:true},
    {id:"10000000-0000-4000-8000-000000000004",pipelineId:"20000000-0000-4000-8000-000000000001",code:"DISCOVERY",name:"Levantamiento",position:4,probability:50,kind:"OPEN",active:true},
    {id:"10000000-0000-4000-8000-000000000005",pipelineId:"20000000-0000-4000-8000-000000000001",code:"PROPOSAL",name:"Propuesta",position:5,probability:65,kind:"OPEN",active:true},
    {id:"10000000-0000-4000-8000-000000000006",pipelineId:"20000000-0000-4000-8000-000000000001",code:"NEGOTIATION",name:"Negociación",position:6,probability:80,kind:"OPEN",active:true},
    {id:"10000000-0000-4000-8000-000000000007",pipelineId:"20000000-0000-4000-8000-000000000001",code:"WON",name:"Ganado",position:7,probability:100,kind:"WON",active:true},
    {id:"10000000-0000-4000-8000-000000000008",pipelineId:"20000000-0000-4000-8000-000000000001",code:"LOST",name:"Perdido",position:8,probability:0,kind:"LOST",active:true},
  ];

  async stages():Promise<SalesPipelineStage[]>{
    if(!this.supabase)return this.memoryStages;
    const{data,error}=await this.supabase.from("pipeline_stages").select("*").eq("active",true).order("position");if(error)throw error;
    return(data??[]).map(this.stageFromRow);
  }
  async leadSources(){if(!this.supabase)return["WEB","GOOGLE","EMAIL","LINKEDIN","INSTAGRAM","REFERIDO","PRESENCIAL","OUTBOUND","PARTNER","OTRO"].map((code)=>({id:code,code,name:code}));const{data,error}=await this.supabase.from("lead_sources").select("id,code,name").eq("active",true).order("position");if(error)throw error;return data??[];}
  async serviceCatalog(){if(!this.supabase)return[];const{data,error}=await this.supabase.from("service_catalog").select("*").eq("active",true).order("name");if(error)throw error;return data??[];}
  async discountLimit(role:string){if(!this.supabase)return({EJECUTIVA_VENTAS:10,JEFE_VENTAS:25,COMERCIAL:25,GERENTE_GENERAL:100}as Record<string,number>)[role]??0;const{data,error}=await this.supabase.from("discount_policies").select("maximum_percent").eq("role",role).eq("service_category","*").eq("active",true).maybeSingle();if(error)throw error;return Number(data?.maximum_percent??0);}

  async listLeads(input:PageInput){if(!this.supabase){const search=input.search?.toLowerCase();return page([...this.leads.values()].filter((i)=>!i.archivedAt&&(!input.status||i.status===input.status)&&(!input.ownerId||i.assignedTo===input.ownerId)&&(!search||[i.companyName,i.contactName,i.email,i.phone,i.rut].some((v)=>v?.toLowerCase().includes(search)))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),input);}const{from,to}=pageBounds(input.page,input.pageSize);const search=cleanSearch(input.search);let q=this.supabase.from("leads").select("*,lead_sources(name)",{count:"exact"}).is("archived_at",null);if(search)q=q.or(`company_name.ilike.%${search}%,contact_name.ilike.%${search}%,email.ilike.%${search}%,phone.ilike.%${search}%,rut.ilike.%${search}%`);if(input.status)q=q.eq("status",input.status);if(input.ownerId)q=q.eq("assigned_to",input.ownerId);const{data,error,count}=await q.order("created_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.leadFromRow),page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize)};}
  async getLead(id:string){if(!this.supabase)return this.leads.get(id);const{data,error}=await this.supabase.from("leads").select("*,lead_sources(name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.leadFromRow(data):undefined;}
  async duplicateLeads(input:Partial<SalesLead>){const all=this.supabase?(await this.supabase.from("leads").select("id,company_name,email,phone,rut,website").is("archived_at",null)).data??[]:[...this.leads.values()].map((i)=>({id:i.id,company_name:i.companyName,email:i.email,phone:i.phone,rut:i.rut,website:i.website}));const norm=(v?:string|null)=>v?.trim().toLowerCase().replace(/\s+/g," ")||"";return all.filter((i:any)=>i.id!==input.id&&((input.email&&norm(i.email)===norm(input.email))||(input.phone&&norm(i.phone)===norm(input.phone))||(input.rut&&norm(i.rut)===norm(input.rut))||(input.companyName&&norm(i.company_name)===norm(input.companyName))||(input.website&&norm(i.website).replace(/^https?:\/\/(www\.)?/,"").split("/")[0]===norm(input.website).replace(/^https?:\/\/(www\.)?/,"").split("/")[0]))).map((i:any)=>i.id);}
  async clientDuplicate(input:Partial<SalesLead>){if(!this.supabase)return null;const filters=[];if(input.rut)filters.push(`rut.eq.${input.rut}`);if(input.email)filters.push(`general_email.eq.${input.email}`);if(!filters.length)return null;const{data,error}=await this.supabase.from("clients").select("id,legal_name,rut").or(filters.join(",")).limit(1).maybeSingle();if(error)throw error;return data;}
  async createLead(input:Partial<SalesLead>){const stamp=now();const item:SalesLead={id:randomUUID(),companyName:input.companyName!.trim(),contactName:input.contactName!.trim(),email:input.email||null,phone:input.phone||null,whatsapp:input.whatsapp||null,website:input.website||null,rut:input.rut||null,sourceId:input.sourceId||null,sourceName:null,campaign:input.campaign||null,interest:input.interest||null,notes:input.notes||null,assignedTo:input.assignedTo||null,status:input.assignedTo?"ASSIGNED":"NEW",score:null,scoreReason:"Información insuficiente",nextActionAt:input.nextActionAt||null,clientId:input.clientId||null,assignedBy:input.assignedBy||null,assignedAt:input.assignedTo?stamp:null,createdBy:input.createdBy||null,createdAt:stamp,updatedAt:stamp,archivedAt:null};if(!this.supabase){this.leads.set(item.id,item);return item;}const{data,error}=await this.supabase.from("leads").insert(this.leadToRow(item)).select("*,lead_sources(name)").single();if(error?.code==="23505")throw new ConflictException("Ya existe un lead con esos datos.");if(error)throw error;return this.leadFromRow(data);}
  async updateLead(id:string,patch:Partial<SalesLead>){const current=await this.getLead(id);if(!current)throw new NotFoundException("Lead no encontrado.");if(!this.supabase){const next={...current,...patch,updatedAt:now()};this.leads.set(id,next);return next;}const row=this.leadPatch(patch);const{data,error}=await this.supabase.from("leads").update(row).eq("id",id).select("*,lead_sources(name)").single();if(error)throw error;return this.leadFromRow(data);}

  async listOpportunities(input:PageInput){if(!this.supabase){const search=input.search?.toLowerCase();return page([...this.opportunities.values()].filter((i)=>(!input.status||i.status===input.status)&&(!input.ownerId||i.ownerId===input.ownerId)&&(!input.clientId||i.clientId===input.clientId)&&(!search||[i.company,i.name,i.description].some((v)=>v?.toLowerCase().includes(search)))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),input);}const{from,to}=pageBounds(input.page,input.pageSize);const search=cleanSearch(input.search);let q=this.supabase.from("opportunities").select("*,pipeline_stages(name)",{count:"exact"});if(search)q=q.or(`company.ilike.%${search}%,name.ilike.%${search}%,description.ilike.%${search}%`);if(input.status)q=q.eq("status",input.status);if(input.ownerId)q=q.eq("owner_id",input.ownerId);if(input.clientId)q=q.eq("client_id",input.clientId);const{data,error,count}=await q.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.opportunityFromRow),page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize)};}
  async getOpportunity(id:string){if(!this.supabase)return this.opportunities.get(id);const{data,error}=await this.supabase.from("opportunities").select("*,pipeline_stages(name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.opportunityFromRow(data):undefined;}
  async createOpportunity(input:Partial<SalesOpportunity>){const stages=await this.stages();const stage=stages.find((i)=>i.id===input.stageId)||stages.find((i)=>i.kind==="OPEN")!;const stamp=now();const item:SalesOpportunity={id:randomUUID(),clientId:input.clientId||null,leadId:input.leadId||null,company:input.company!.trim(),name:input.name!.trim(),description:input.description||null,serviceCategory:input.serviceCategory||null,ownerId:input.ownerId||null,estimatedValue:Number(input.estimatedValue||0),currency:input.currency||"CLP",probability:input.probability??stage.probability,pipelineId:stage.pipelineId,stageId:stage.id,stageName:stage.name,expectedCloseDate:input.expectedCloseDate||null,nextActionAt:input.nextActionAt||null,status:"OPEN",lostReasonId:null,lostExplanation:null,stageEnteredAt:stamp,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.opportunities.set(item.id,item);return item;}const{data,error}=await this.supabase.from("opportunities").insert(this.opportunityToRow(item)).select("*,pipeline_stages(name)").single();if(error)throw error;return this.opportunityFromRow(data);}
  async updateOpportunity(id:string,patch:Partial<SalesOpportunity>){const current=await this.getOpportunity(id);if(!current)throw new NotFoundException("Oportunidad no encontrada.");if(!this.supabase){const next={...current,...patch,updatedAt:now()};this.opportunities.set(id,next);return next;}const{data,error}=await this.supabase.from("opportunities").update(this.opportunityPatch(patch)).eq("id",id).select("*,pipeline_stages(name)").single();if(error)throw error;return this.opportunityFromRow(data);}
  async changeOpportunityStage(id:string,stage:SalesPipelineStage,actorId:string|null,reason:string|null){const current=await this.getOpportunity(id);if(!current)throw new NotFoundException("Oportunidad no encontrada.");if(!this.supabase){const next={...current,stageId:stage.id,stageName:stage.name,probability:stage.probability,status:stage.kind==="WON"?"WON" as const:stage.kind==="LOST"?"LOST" as const:"OPEN" as const,lostExplanation:stage.kind==="LOST"?reason:null,stageEnteredAt:now(),updatedAt:now()};this.opportunities.set(id,next);return next;}const{error}=await this.supabase.rpc("change_opportunity_stage",{target_opportunity_id:id,target_stage_id:stage.id,actor_user_id:actorId,change_reason:reason});if(error)throw error;return(await this.getOpportunity(id))!;}

  async listFollowUps(input:PageInput){const decorate=(i:SalesFollowUp)=>i.status==="PENDING"&&i.scheduledAt<now()?{...i,status:"OVERDUE" as const}:i;if(!this.supabase){let items=[...this.followUps.values()].map(decorate);if(input.status)items=items.filter((i)=>i.status===input.status);if(input.ownerId)items=items.filter((i)=>i.assignedTo===input.ownerId);if(input.clientId)items=items.filter((i)=>i.clientId===input.clientId);return page(items.sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)),input);}const{from,to}=pageBounds(input.page,input.pageSize);let q=this.supabase.from("follow_ups").select("*",{count:"exact"});if(input.status==="OVERDUE")q=q.eq("status","PENDING").lt("scheduled_at",now());else if(input.status)q=q.eq("status",input.status);if(input.ownerId)q=q.eq("assigned_to",input.ownerId);if(input.clientId)q=q.eq("client_id",input.clientId);const{data,error,count}=await q.order("scheduled_at").range(from,to);if(error)throw error;return{items:(data??[]).map(this.followUpFromRow).map(decorate),page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize)};}
  async getFollowUp(id:string){if(!this.supabase)return this.followUps.get(id);const{data,error}=await this.supabase.from("follow_ups").select("*").eq("id",id).maybeSingle();if(error)throw error;return data?this.followUpFromRow(data):undefined;}
  async createFollowUp(input:Partial<SalesFollowUp>){const stamp=now();const item:SalesFollowUp={id:randomUUID(),leadId:input.leadId||null,opportunityId:input.opportunityId||null,clientId:input.clientId||null,assignedTo:input.assignedTo||null,type:input.type||"FOLLOW_UP",title:input.title!.trim(),description:input.description||null,scheduledAt:input.scheduledAt!,completedAt:null,status:"PENDING",outcome:null,createdBy:input.createdBy||null,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.followUps.set(item.id,item);return item;}const{data,error}=await this.supabase.from("follow_ups").insert(this.followUpToRow(item)).select("*").single();if(error)throw error;return this.followUpFromRow(data);}
  async updateFollowUp(id:string,patch:Partial<SalesFollowUp>){const current=await this.getFollowUp(id);if(!current)throw new NotFoundException("Seguimiento no encontrado.");if(!this.supabase){const next={...current,...patch,updatedAt:now()};this.followUps.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={title:"title",description:"description",scheduledAt:"scheduled_at",assignedTo:"assigned_to",status:"status",outcome:"outcome",completedAt:"completed_at"};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;const{data,error}=await this.supabase.from("follow_ups").update(row).eq("id",id).select("*").single();if(error)throw error;return this.followUpFromRow(data);}

  async listQuotes(input:PageInput){if(!this.supabase){const search=input.search?.toLowerCase();return page([...this.quotes.values()].filter((i)=>(!input.status||i.status===input.status)&&(!input.ownerId||i.ownerId===input.ownerId)&&(!input.clientId||i.clientId===input.clientId)&&(!search||[i.quoteNumber,i.companyName,i.contactName,i.contactEmail].some((v)=>v?.toLowerCase().includes(search)))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),input);}const{from,to}=pageBounds(input.page,input.pageSize);const search=cleanSearch(input.search);let q=this.supabase.from("quotes").select("*",{count:"exact"});if(search)q=q.or(`quote_number.ilike.%${search}%,company_name.ilike.%${search}%,contact_name.ilike.%${search}%,contact_email.ilike.%${search}%`);if(input.status)q=q.eq("status",input.status);if(input.ownerId)q=q.eq("owner_id",input.ownerId);if(input.clientId)q=q.eq("client_id",input.clientId);const{data,error,count}=await q.order("created_at",{ascending:false}).range(from,to);if(error)throw error;const items=await Promise.all((data??[]).map((r)=>this.quoteWithItems(r)));return{items,page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize)};}
  async getQuote(id:string){if(!this.supabase)return this.quotes.get(id);const{data,error}=await this.supabase.from("quotes").select("*").eq("id",id).maybeSingle();if(error)throw error;return data?this.quoteWithItems(data):undefined;}
  async createQuote(input:Partial<SalesQuote>,items:QuoteItem[]){const stamp=now();const quoteId=randomUUID();const normalized=items.map((i)=>({...i,id:randomUUID(),quoteId}));const year=new Date().getUTCFullYear(),sequence=(this.quoteSequences.get(year)??9999)+1;this.quoteSequences.set(year,sequence);const item:SalesQuote={id:quoteId,quoteNumber:`COT-${year}-${sequence}`,version:1,clientId:input.clientId||null,leadId:input.leadId||null,opportunityId:input.opportunityId||null,companyName:input.companyName!.trim(),contactName:input.contactName||null,contactEmail:input.contactEmail||null,ownerId:input.ownerId||null,status:input.status||"DRAFT",currency:input.currency||"CLP",subtotal:Number(input.subtotal||0),discountTotal:Number(input.discountTotal||0),netAmount:Number(input.netAmount||0),taxRate:Number(input.taxRate??19),taxAmount:Number(input.taxAmount||0),totalAmount:Number(input.totalAmount||0),validUntil:input.validUntil||null,paymentTerms:input.paymentTerms||null,commercialTerms:input.commercialTerms||null,notes:input.notes||null,documentId:null,documentHash:null,sentAt:null,acceptedAt:null,saleId:null,createdAt:stamp,updatedAt:stamp,items:normalized};if(!this.supabase){this.quotes.set(item.id,item);return item;}const rows=normalized.map((i)=>this.quoteItemToRow(i));const{data,error}=await this.supabase.rpc("create_sales_quote",{quote_payload:this.quoteToRow(item),item_payload:rows});if(error)throw error;return(await this.getQuote(data as string))!;}
  async transitionQuote(id:string,status:SalesQuote["status"],extra:Partial<SalesQuote>={}){const current=await this.getQuote(id);if(!current)throw new NotFoundException("Cotización no encontrada.");if(!this.supabase){const next={...current,...extra,status,updatedAt:now()};this.quotes.set(id,next);return next;}const row:Record<string,unknown>={status,updated_at:now()};if(extra.documentId!==undefined)row.document_id=extra.documentId;if(extra.documentHash!==undefined)row.document_hash=extra.documentHash;if(extra.sentAt!==undefined)row.sent_at=extra.sentAt;if(extra.acceptedAt!==undefined)row.accepted_at=extra.acceptedAt;const{error}=await this.supabase.from("quotes").update(row).eq("id",id);if(error)throw error;return(await this.getQuote(id))!;}
  async updateQuote(id:string,patch:Partial<SalesQuote>){const current=await this.getQuote(id);if(!current)throw new NotFoundException("Cotización no encontrada.");const next={...current,...patch,updatedAt:now()};if(!this.supabase){this.quotes.set(id,next);return next;}const row:Record<string,unknown>={updated_at:now()};const map:Record<string,string>={contactName:"contact_name",contactEmail:"contact_email",validUntil:"valid_until",paymentTerms:"payment_terms",commercialTerms:"commercial_terms",notes:"notes"};for(const[key,value]of Object.entries(patch))if(map[key])row[map[key]!]=value;const{error}=await this.supabase.from("quotes").update(row).eq("id",id);if(error)throw error;return(await this.getQuote(id))!;}
  async linkQuoteClient(id:string,clientId:string){const current=await this.getQuote(id);if(!current)throw new NotFoundException("Cotización no encontrada.");if(!this.supabase){const next={...current,clientId,updatedAt:now()};this.quotes.set(id,next);if(current.saleId){const sale=this.sales.get(current.saleId);if(sale)this.sales.set(sale.id,{...sale,clientId});}return next;}const{error}=await this.supabase.from("quotes").update({client_id:clientId,updated_at:now()}).eq("id",id);if(error)throw error;const saleResult=await this.supabase.from("sales").update({client_id:clientId}).eq("quote_id",id);if(saleResult.error)throw saleResult.error;return(await this.getQuote(id))!;}
  async linkSaleContract(quoteId:string,contractId:string){if(!this.supabase){const quote=await this.getQuote(quoteId);if(quote?.saleId){const sale=this.sales.get(quote.saleId);if(sale)this.sales.set(sale.id,{...sale,contractId});}return;}const{error}=await this.supabase.from("sales").update({contract_id:contractId}).eq("quote_id",quoteId);if(error)throw error;}
  async versionQuote(id:string,actorId:string|null){const current=await this.getQuote(id);if(!current)throw new NotFoundException("Cotización no encontrada.");if(!this.supabase){await this.createQuoteVersion(current,current as unknown as Record<string,unknown>);const next={...current,version:current.version+1,status:"DRAFT" as const,documentId:null,documentHash:null,sentAt:null,acceptedAt:null,updatedAt:now()};this.quotes.set(id,next);return next;}const{data,error}=await this.supabase.rpc("create_quote_version",{target_quote_id:id,actor_user_id:actorId});if(error)throw error;return(await this.getQuote(data as string))!;}
  async createQuoteVersion(quote:SalesQuote,snapshot:Record<string,unknown>,document?:{id:string;hash:string;path:string}){if(!this.supabase){return{id:randomUUID(),quoteId:quote.id,versionNumber:quote.version,snapshot,documentId:document?.id??null,documentHash:document?.hash??null};}const{data,error}=await this.supabase.from("quote_versions").insert({quote_id:quote.id,version_number:quote.version,snapshot,document_id:document?.id??null,document_hash:document?.hash??null,storage_path:document?.path??null}).select("*").single();if(error)throw error;return data;}
  async uploadQuotePdf(quote:SalesQuote,bytes:Uint8Array,hash:string){if(!this.supabase)return{id:randomUUID(),path:null,hash};const documentId=randomUUID();const path=`${quote.id}/v${quote.version}/${quote.quoteNumber}.pdf`;const uploaded=await this.supabase.storage.from("commercial-documents").upload(path,bytes,{contentType:"application/pdf",upsert:false});if(uploaded.error)throw uploaded.error;const{error}=await this.supabase.from("commercial_documents").insert({id:documentId,quote_id:quote.id,storage_path:path,document_hash:hash,mime_type:"application/pdf",template_version:"QUOTE_V2"});if(error)throw error;return{id:documentId,path,hash};}
  async recordQuoteEmail(quoteId:string,input:{to:string;subject:string;provider:string;providerMessageId:string;sentBy:string|null}){if(!this.supabase)return{...input,quoteId,sentAt:now(),deliveryStatus:"SENT"};const{data,error}=await this.supabase.from("quote_email_deliveries").insert({quote_id:quoteId,to_addresses:[input.to],subject:input.subject,provider:input.provider,provider_message_id:input.providerMessageId,sent_by:input.sentBy,sent_at:now(),delivery_status:"SENT"}).select("*").single();if(error)throw error;return data;}
  async acceptQuote(id:string,actorId:string|null,idempotencyKey:string){if(!this.supabase){const quote=await this.getQuote(id);if(!quote)throw new NotFoundException("Cotización no encontrada.");if(quote.saleId)return this.sales.get(quote.saleId)!;const sale:Sale={id:randomUUID(),quoteId:id,quoteVersionId:null,opportunityId:quote.opportunityId,clientId:quote.clientId,amount:quote.totalAmount,currency:quote.currency,ownerId:quote.ownerId,closedAt:now(),contractId:null,workOrderId:null,status:"WON",createdAt:now()};this.sales.set(sale.id,sale);this.quotes.set(id,{...quote,status:"ACCEPTED",acceptedAt:now(),saleId:sale.id,updatedAt:now()});if(quote.opportunityId){const opportunity=this.opportunities.get(quote.opportunityId);if(opportunity)this.opportunities.set(opportunity.id,{...opportunity,status:"WON",updatedAt:now()});}await this.publish("QUOTE",id,"QUOTE_ACCEPTED",actorId,{saleId:sale.id,version:quote.version});await this.publish("SALE",sale.id,"SALE_WON",actorId,{quoteId:id,clientId:sale.clientId});return sale;}const{data,error}=await this.supabase.rpc("accept_sales_quote",{target_quote_id:id,actor_user_id:actorId,idempotency_key:idempotencyKey});if(error)throw error;const result=await this.supabase.from("sales").select("*").eq("id",data as string).single();if(result.error)throw result.error;return this.saleFromRow(result.data);}
  async convertQuoteToWorkOrder(id:string,actorId:string|null,idempotencyKey:string,overrideReason:string|null){if(!this.supabase){const quote=await this.getQuote(id);if(!quote||!quote.saleId)throw new ConflictException("La cotización debe estar aceptada antes de crear la OT.");const sale=this.sales.get(quote.saleId)!;if(sale.workOrderId)return{workOrderId:sale.workOrderId,created:false};const workOrderId=randomUUID();this.sales.set(sale.id,{...sale,workOrderId});this.quotes.set(id,{...quote,status:"CONVERTED",updatedAt:now()});await this.publish("WORK_ORDER",workOrderId,"WORK_ORDER_CREATED",actorId,{quoteId:id,overrideReason});return{workOrderId,created:true};}const{data,error}=await this.supabase.rpc("convert_quote_to_work_order",{target_quote_id:id,actor_user_id:actorId,idempotency_key:idempotencyKey,override_reason:overrideReason});if(error)throw error;return data;}
  async listSales(input:PageInput){if(!this.supabase)return page([...this.sales.values()].sort((a,b)=>b.closedAt.localeCompare(a.closedAt)),input);const{from,to}=pageBounds(input.page,input.pageSize);let q=this.supabase.from("sales").select("*",{count:"exact"});if(input.clientId)q=q.eq("client_id",input.clientId);const{data,error,count}=await q.order("closed_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map(this.saleFromRow),page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize)};}
  async listGoals(){if(!this.supabase)return[...this.goals.values()];const{data,error}=await this.supabase.from("sales_goals").select("*").order("period_start",{ascending:false});if(error)throw error;return(data??[]).map(this.goalFromRow);}
  async createGoal(input:Partial<SalesGoal>){const item:SalesGoal={id:randomUUID(),userId:input.userId||null,teamId:input.teamId||null,periodType:input.periodType!,periodStart:input.periodStart!,periodEnd:input.periodEnd!,goalType:input.goalType!,target:Number(input.target||0),actual:0,createdAt:now()};if(!this.supabase){this.goals.set(item.id,item);return item;}const{data,error}=await this.supabase.from("sales_goals").insert({user_id:item.userId,team_id:item.teamId,period_type:item.periodType,period_start:item.periodStart,period_end:item.periodEnd,goal_type:item.goalType,target:item.target}).select("*").single();if(error)throw error;return this.goalFromRow(data);}
  async listCommissions(userId?:string){if(!this.supabase)return[...this.commissions.values()].filter((i)=>!userId||i.userId===userId);let q=this.supabase.from("commissions").select("*").order("created_at",{ascending:false});if(userId)q=q.eq("user_id",userId);const{data,error}=await q;if(error)throw error;return(data??[]).map(this.commissionFromRow);}
  async transitionCommission(id:string,status:Commission["status"]){if(!this.supabase){const current=this.commissions.get(id);if(!current)throw new NotFoundException("Comisión no encontrada.");const next={...current,status,updatedAt:now()};this.commissions.set(id,next);return next;}const{data,error}=await this.supabase.from("commissions").update({status,updated_at:now()}).eq("id",id).select("*").single();if(error)throw error;return this.commissionFromRow(data);}
  async listHandoffs(){if(!this.supabase)return[...this.handoffs.values()];const{data,error}=await this.supabase.from("sales_handoffs").select("*").order("created_at",{ascending:false});if(error)throw error;return(data??[]).map(this.handoffFromRow);}
  async createHandoff(input:Partial<SalesHandoff>){const stamp=now();const item:SalesHandoff={id:randomUUID(),saleId:input.saleId!,clientId:input.clientId||null,quoteId:input.quoteId!,workOrderId:input.workOrderId||null,status:input.status||"DRAFT",scope:input.scope!.trim(),committedDeadline:input.committedDeadline||null,risks:input.risks||null,dependencies:input.dependencies||null,commercialOwnerId:input.commercialOwnerId||null,developmentOwnerId:input.developmentOwnerId||null,overrideReason:input.overrideReason||null,createdAt:stamp,updatedAt:stamp};if(!this.supabase){this.handoffs.set(item.id,item);return item;}const{data,error}=await this.supabase.from("sales_handoffs").insert({sale_id:item.saleId,client_id:item.clientId,quote_id:item.quoteId,work_order_id:item.workOrderId,status:item.status,scope:item.scope,committed_deadline:item.committedDeadline,risks:item.risks,dependencies:item.dependencies,commercial_owner_id:item.commercialOwnerId,development_owner_id:item.developmentOwnerId,override_reason:item.overrideReason}).select("*").single();if(error)throw error;if(item.status==="READY"){const notification=await this.supabase.from("commercial_notifications").upsert([{event_key:`HANDOFF_READY:${data.id}:JEFE_DESARROLLO`,audience_role:"JEFE_DESARROLLO",type:"HANDOFF_READY",title:"Nuevo handoff comercial listo",body:item.scope,entity_type:"HANDOFF",entity_id:data.id},{event_key:`HANDOFF_READY:${data.id}:GERENTE_GENERAL`,audience_role:"GERENTE_GENERAL",type:"HANDOFF_READY",title:"Handoff comercial listo",body:item.scope,entity_type:"HANDOFF",entity_id:data.id}],{onConflict:"event_key"});if(notification.error)throw notification.error;}return this.handoffFromRow(data);}
  async publish(aggregateType:string,aggregateId:string,eventType:string,actorId:string|null,payload:Record<string,unknown>={}){const event:CommercialEvent={id:randomUUID(),aggregateType,aggregateId,eventType,actorId,payload,occurredAt:now()};if(!this.supabase){this.events.unshift(event);return event;}const{data,error}=await this.supabase.from("commercial_events").insert({aggregate_type:aggregateType,aggregate_id:aggregateId,event_type:eventType,actor_id:actorId,payload}).select("*").single();if(error)throw error;await this.supabase.from("business_event_outbox").insert({aggregate_type:aggregateType,aggregate_id:aggregateId,event_type:eventType,payload:{...payload,commercialEventId:data.id}});return event;}
  async activity(limit=50){if(!this.supabase)return this.events.slice(0,limit);const{data,error}=await this.supabase.from("commercial_events").select("*").order("occurred_at",{ascending:false}).limit(limit);if(error)throw error;return(data??[]).map((r)=>({id:r.id,aggregateType:r.aggregate_type,aggregateId:r.aggregate_id,eventType:r.event_type,actorId:r.actor_id,payload:r.payload??{},occurredAt:r.occurred_at}));}

  private stageFromRow=(r:any):SalesPipelineStage=>({id:r.id,pipelineId:r.pipeline_id,code:r.code,name:r.name,position:r.position,probability:Number(r.probability),kind:r.kind,active:r.active});
  private leadFromRow=(r:any):SalesLead=>({id:r.id,companyName:r.company_name,contactName:r.contact_name,email:r.email,phone:r.phone,whatsapp:r.whatsapp,website:r.website,rut:r.rut,sourceId:r.source_id,sourceName:(Array.isArray(r.lead_sources)?r.lead_sources[0]:r.lead_sources)?.name??null,campaign:r.campaign,interest:r.interest,notes:r.notes,assignedTo:r.assigned_to,status:r.status,score:r.score===null?null:Number(r.score),scoreReason:r.score_reason||"Información insuficiente",nextActionAt:r.next_action_at,clientId:r.client_id,assignedBy:r.assigned_by,assignedAt:r.assigned_at,createdBy:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at,archivedAt:r.archived_at});
  private leadToRow=(i:SalesLead)=>({id:i.id,company_name:i.companyName,contact_name:i.contactName,email:i.email,phone:i.phone,whatsapp:i.whatsapp,website:i.website,rut:i.rut,source_id:i.sourceId,campaign:i.campaign,interest:i.interest,notes:i.notes,assigned_to:i.assignedTo,status:i.status,score:i.score,score_reason:i.scoreReason,next_action_at:i.nextActionAt,client_id:i.clientId,assigned_by:i.assignedBy,assigned_at:i.assignedAt,created_by:i.createdBy,created_at:i.createdAt,updated_at:i.updatedAt,archived_at:i.archivedAt});
  private leadPatch=(i:Partial<SalesLead>)=>{const map:Record<string,string>={companyName:"company_name",contactName:"contact_name",email:"email",phone:"phone",whatsapp:"whatsapp",website:"website",rut:"rut",sourceId:"source_id",campaign:"campaign",interest:"interest",notes:"notes",assignedTo:"assigned_to",status:"status",nextActionAt:"next_action_at",clientId:"client_id",assignedBy:"assigned_by",assignedAt:"assigned_at",archivedAt:"archived_at"};const row:Record<string,unknown>={updated_at:now()};for(const[k,v]of Object.entries(i))if(map[k])row[map[k]!]=v;return row;};
  private opportunityFromRow=(r:any):SalesOpportunity=>({id:r.id,clientId:r.client_id,leadId:r.lead_id,company:r.company,name:r.name,description:r.description,serviceCategory:r.service_category,ownerId:r.owner_id,estimatedValue:Number(r.estimated_value),currency:r.currency,probability:Number(r.probability),pipelineId:r.pipeline_id,stageId:r.stage_id,stageName:(Array.isArray(r.pipeline_stages)?r.pipeline_stages[0]:r.pipeline_stages)?.name??null,expectedCloseDate:r.expected_close_date,nextActionAt:r.next_action_at,status:r.status,lostReasonId:r.lost_reason_id,lostExplanation:r.lost_explanation,stageEnteredAt:r.stage_entered_at,createdAt:r.created_at,updatedAt:r.updated_at});
  private opportunityToRow=(i:SalesOpportunity)=>({id:i.id,client_id:i.clientId,lead_id:i.leadId,company:i.company,name:i.name,description:i.description,service_category:i.serviceCategory,owner_id:i.ownerId,estimated_value:i.estimatedValue,currency:i.currency,probability:i.probability,pipeline_id:i.pipelineId,stage_id:i.stageId,expected_close_date:i.expectedCloseDate,next_action_at:i.nextActionAt,status:i.status,stage_entered_at:i.stageEnteredAt});
  private opportunityPatch=(i:Partial<SalesOpportunity>)=>{const map:Record<string,string>={clientId:"client_id",company:"company",name:"name",description:"description",serviceCategory:"service_category",ownerId:"owner_id",estimatedValue:"estimated_value",currency:"currency",probability:"probability",expectedCloseDate:"expected_close_date",nextActionAt:"next_action_at",lostReasonId:"lost_reason_id",lostExplanation:"lost_explanation"};const row:Record<string,unknown>={updated_at:now()};for(const[k,v]of Object.entries(i))if(map[k])row[map[k]!]=v;return row;};
  private followUpFromRow=(r:any):SalesFollowUp=>({id:r.id,leadId:r.lead_id,opportunityId:r.opportunity_id,clientId:r.client_id,assignedTo:r.assigned_to,type:r.type,title:r.title,description:r.description,scheduledAt:r.scheduled_at,completedAt:r.completed_at,status:r.status,outcome:r.outcome,createdBy:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at});
  private followUpToRow=(i:SalesFollowUp)=>({id:i.id,lead_id:i.leadId,opportunity_id:i.opportunityId,client_id:i.clientId,assigned_to:i.assignedTo,type:i.type,title:i.title,description:i.description,scheduled_at:i.scheduledAt,completed_at:i.completedAt,status:i.status,outcome:i.outcome,created_by:i.createdBy});
  private quoteFromRow=(r:any,items:QuoteItem[]):SalesQuote=>({id:r.id,quoteNumber:r.quote_number,version:r.version,clientId:r.client_id,leadId:r.lead_id,opportunityId:r.opportunity_id,companyName:r.company_name,contactName:r.contact_name,contactEmail:r.contact_email,ownerId:r.owner_id,status:r.status,currency:r.currency,subtotal:Number(r.subtotal),discountTotal:Number(r.discount_total),netAmount:Number(r.net_amount),taxRate:Number(r.tax_rate),taxAmount:Number(r.tax_amount),totalAmount:Number(r.total_amount),validUntil:r.valid_until,paymentTerms:r.payment_terms,commercialTerms:r.commercial_terms,notes:r.notes,documentId:r.document_id,documentHash:r.document_hash,sentAt:r.sent_at,acceptedAt:r.accepted_at,saleId:r.sale_id,createdAt:r.created_at,updatedAt:r.updated_at,items});
  private async quoteWithItems(r:any){const{data,error}=await this.supabase!.from("quote_items").select("*").eq("quote_id",r.id).order("position");if(error)throw error;return this.quoteFromRow(r,(data??[]).map(this.quoteItemFromRow));}
  private quoteItemFromRow=(r:any):QuoteItem=>({id:r.id,quoteId:r.quote_id,catalogServiceId:r.catalog_service_id,description:r.description,quantity:Number(r.quantity),unitPrice:Number(r.unit_price),discountPercent:Number(r.discount_percent),taxable:r.taxable,subtotal:Number(r.subtotal)});
  private quoteToRow=(i:SalesQuote)=>({id:i.id,client_id:i.clientId,lead_id:i.leadId,opportunity_id:i.opportunityId,company_name:i.companyName,contact_name:i.contactName,contact_email:i.contactEmail,owner_id:i.ownerId,status:i.status,currency:i.currency,subtotal:i.subtotal,discount_total:i.discountTotal,net_amount:i.netAmount,tax_rate:i.taxRate,tax_amount:i.taxAmount,total_amount:i.totalAmount,valid_until:i.validUntil,payment_terms:i.paymentTerms,commercial_terms:i.commercialTerms,notes:i.notes});
  private quoteItemToRow=(i:QuoteItem)=>({id:i.id,quote_id:i.quoteId,catalog_service_id:i.catalogServiceId,description:i.description,quantity:i.quantity,unit_price:i.unitPrice,discount_percent:i.discountPercent,taxable:i.taxable,subtotal:i.subtotal});
  private saleFromRow=(r:any):Sale=>({id:r.id,quoteId:r.quote_id,quoteVersionId:r.quote_version_id,opportunityId:r.opportunity_id,clientId:r.client_id,amount:Number(r.amount),currency:r.currency,ownerId:r.owner_id,closedAt:r.closed_at,contractId:r.contract_id,workOrderId:r.work_order_id,status:r.status,createdAt:r.created_at});
  private goalFromRow=(r:any):SalesGoal=>({id:r.id,userId:r.user_id,teamId:r.team_id,periodType:r.period_type,periodStart:r.period_start,periodEnd:r.period_end,goalType:r.goal_type,target:Number(r.target),actual:Number(r.actual),createdAt:r.created_at});
  private commissionFromRow=(r:any):Commission=>({id:r.id,saleId:r.sale_id,userId:r.user_id,ruleId:r.rule_id,baseAmount:Number(r.base_amount),amount:Number(r.amount),currency:r.currency,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at});
  private handoffFromRow=(r:any):SalesHandoff=>({id:r.id,saleId:r.sale_id,clientId:r.client_id,quoteId:r.quote_id,workOrderId:r.work_order_id,status:r.status,scope:r.scope,committedDeadline:r.committed_deadline,risks:r.risks,dependencies:r.dependencies,commercialOwnerId:r.commercial_owner_id,developmentOwnerId:r.development_owner_id,overrideReason:r.override_reason,createdAt:r.created_at,updatedAt:r.updated_at});
}
