import{BadRequestException,ConflictException,Injectable,NotFoundException,Optional}from"@nestjs/common";import type{CreateClientInput,QuoteItem,SalesQuote}from"@zyteron/contracts";import{ClientsService}from"../clients/clients.service.js";import{ContractsService}from"../contracts/contracts.service.js";import{DocumentService}from"../documents/documents.service.js";import{CommercialRepository}from"./commercial.repository.js";import{MailProviderService}from"./mail-provider.service.js";import{QuoteDocumentService}from"./quote-document.service.js";import{optionalUuid,required}from"./commercial.validation.js";
const round=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
export function calculateQuote(items:Array<Pick<QuoteItem,"quantity"|"unitPrice"|"discountPercent"|"taxable">>,taxRate=19){let subtotal=0,discountTotal=0,taxableNet=0;for(const i of items){const raw=round(Number(i.quantity)*Number(i.unitPrice));const discount=round(raw*Number(i.discountPercent||0)/100);const net=round(raw-discount);subtotal=round(subtotal+raw);discountTotal=round(discountTotal+discount);if(i.taxable)taxableNet=round(taxableNet+net);}const netAmount=round(subtotal-discountTotal),taxAmount=round(taxableNet*taxRate/100);return{subtotal,discountTotal,netAmount,taxRate,taxAmount,totalAmount:round(netAmount+taxAmount)};}
const transitions:Record<SalesQuote["status"],SalesQuote["status"][]>={DRAFT:["PENDING_APPROVAL","APPROVED","CANCELLED"],PENDING_APPROVAL:["APPROVED","REJECTED","CANCELLED"],APPROVED:["READY_TO_SEND","CANCELLED"],REJECTED:["DRAFT","CANCELLED"],READY_TO_SEND:["SENT","CANCELLED"],SENT:["NEGOTIATING","ACCEPTED","DECLINED","EXPIRED","CANCELLED"],NEGOTIATING:["ACCEPTED","DECLINED","EXPIRED","CANCELLED"],ACCEPTED:["CONVERTED"],DECLINED:[],EXPIRED:[],CONVERTED:[],CANCELLED:[]};
@Injectable()export class QuotesService{constructor(private readonly r:CommercialRepository,private readonly pdf:QuoteDocumentService,private readonly mail:MailProviderService,private readonly clients:ClientsService,private readonly contracts:ContractsService,@Optional()private readonly documents?:DocumentService){}list(q:any){return this.r.listQuotes(q);}catalog(){return this.r.serviceCatalog();}async get(id:string){const i=await this.r.getQuote(id);if(!i)throw new NotFoundException("Cotización no encontrada.");return i;}
async create(b:Omit<Partial<SalesQuote>,"items">&{items?:Partial<QuoteItem>[]},actorId:string|null,role="GERENTE_GENERAL"){
  required(b.companyName,"La empresa");
  const opportunityId=optionalUuid(b.opportunityId,"La oportunidad"),clientId=optionalUuid(b.clientId,"El cliente"),leadId=optionalUuid(b.leadId,"El lead");
  optionalUuid(b.ownerId,"La ejecutiva responsable");
  if(!opportunityId&&!clientId&&!leadId)throw new BadRequestException("Selecciona una oportunidad, un cliente o un lead para crear la cotización.");
  let normalizedClientId=clientId,normalizedLeadId=leadId;
  if(opportunityId){const opportunity=await this.r.getOpportunity(opportunityId);if(!opportunity)throw new BadRequestException("La oportunidad seleccionada no existe.");if(clientId&&opportunity.clientId&&clientId!==opportunity.clientId)throw new BadRequestException("El cliente no corresponde a la oportunidad seleccionada.");if(leadId&&opportunity.leadId&&leadId!==opportunity.leadId)throw new BadRequestException("El lead no corresponde a la oportunidad seleccionada.");normalizedClientId=clientId||opportunity.clientId;normalizedLeadId=leadId||opportunity.leadId;}
  if(normalizedClientId)await this.clients.get(normalizedClientId);
  if(normalizedLeadId&&!await this.r.getLead(normalizedLeadId))throw new BadRequestException("El lead seleccionado no existe.");
  if(!b.items?.length)throw new BadRequestException("Agrega al menos un servicio.");
  if(role==="EJECUTIVA_VENTAS"&&b.items.some((item)=>!item.catalogServiceId))throw new BadRequestException("Los ítems personalizados requieren autorización comercial.");
  const items=b.items.map((i,index)=>{required(i.description,`La descripción del ítem ${index+1}`);const quantity=Number(i.quantity||0),unitPrice=Number(i.unitPrice||0),discountPercent=Number(i.discountPercent||0);if(quantity<=0||unitPrice<0||discountPercent<0||discountPercent>100)throw new BadRequestException("Revisa cantidades, precios y descuentos.");return{id:"",quoteId:"",catalogServiceId:i.catalogServiceId||null,description:i.description!.trim(),quantity,unitPrice,discountPercent,taxable:i.taxable!==false,subtotal:round(quantity*unitPrice*(1-discountPercent/100))};});
  const totals=calculateQuote(items,Number(b.taxRate??19)),limit=await this.r.discountLimit(role),requiresApproval=items.some((item)=>item.discountPercent>limit);
  const quote=await this.r.createQuote({...b,opportunityId,clientId:normalizedClientId,leadId:normalizedLeadId,...totals,status:requiresApproval?"PENDING_APPROVAL":"DRAFT"} as Partial<SalesQuote>,items);
  await this.r.publish("QUOTE",quote.id,"QUOTE_CREATED",actorId,{quoteNumber:quote.quoteNumber,total:quote.totalAmount});if(requiresApproval)await this.r.publish("QUOTE",quote.id,"QUOTE_APPROVAL_REQUIRED",actorId,{maximumAllowed:limit});return quote;
}
async update(id:string,b:Partial<SalesQuote>,actorId:string|null){const current=await this.get(id);if(!["DRAFT","REJECTED"].includes(current.status))throw new ConflictException("Crea una nueva versión para modificar una cotización enviada.");const item=await this.r.updateQuote(id,b);await this.r.publish("QUOTE",id,"QUOTE_UPDATED",actorId,{fields:Object.keys(b)});return item;}
async duplicate(id:string,actorId:string|null,role:string){const quote=await this.get(id);return this.create({clientId:quote.clientId,leadId:quote.leadId,opportunityId:quote.opportunityId,companyName:quote.companyName,contactName:quote.contactName,contactEmail:quote.contactEmail,ownerId:quote.ownerId,currency:quote.currency,validUntil:quote.validUntil,paymentTerms:quote.paymentTerms,commercialTerms:quote.commercialTerms,notes:quote.notes,taxRate:quote.taxRate,items:quote.items.map((item)=>({...item,id:undefined,quoteId:undefined}))},actorId,role);}
async transition(id:string,status:SalesQuote["status"],actorId:string|null,payload:Record<string,unknown>={}){const current=await this.get(id);if(!transitions[current.status].includes(status))throw new BadRequestException(`No se puede pasar de ${current.status} a ${status}.`);const item=await this.r.transitionQuote(id,status);await this.r.publish("QUOTE",id,`QUOTE_${status}`,actorId,payload);return item;}
submit(id:string,actorId:string|null){return this.transition(id,"PENDING_APPROVAL",actorId);}approve(id:string,actorId:string|null){return this.transition(id,"APPROVED",actorId);}reject(id:string,reason:string,actorId:string|null){required(reason,"El motivo de rechazo");return this.transition(id,"REJECTED",actorId,{reason});}decline(id:string,reason:string,actorId:string|null){required(reason,"El motivo de rechazo");return this.transition(id,"DECLINED",actorId,{reason});}
async version(id:string,actorId:string|null){const current=await this.get(id);if(["ACCEPTED","CONVERTED","CANCELLED"].includes(current.status))throw new ConflictException("Esta cotización ya no admite nuevas versiones.");const item=await this.r.versionQuote(id,actorId);await this.r.publish("QUOTE",id,"QUOTE_VERSION_CREATED",actorId,{version:item.version});return item;}
cancel(id:string,actorId:string|null){return this.transition(id,"CANCELLED",actorId);}
async preview(id:string){const quote=await this.get(id);const result=this.pdf.render(quote);return{filename:result.filename,mimeType:"application/pdf",hash:result.hash,contentBase64:result.bytes.toString("base64")};}
async generatePdf(id:string,actorId:string|null){const quote=await this.get(id);if(!["APPROVED","READY_TO_SEND","SENT","NEGOTIATING"].includes(quote.status))throw new ConflictException("La cotización debe estar aprobada para registrar su PDF final.");const result=this.pdf.render(quote);let document:{id:string;path:string|null;hash:string};if(this.documents){const actor={userId:actorId,role:"COMERCIAL",clientId:quote.clientId,contactId:null},links=[{linkType:"QUOTE",linkedId:quote.id,primaryLink:true},...(quote.clientId?[{linkType:"CLIENT",linkedId:quote.clientId,primaryLink:false}]:[])],central=await this.documents.create({title:`Cotización ${quote.quoteNumber}`,description:`Propuesta comercial para ${quote.companyName}`,typeCode:"QUOTE",classification:"CLIENT",links},actor),uploaded=await this.documents.addVersion(central.id,{filename:result.filename,mimeType:"application/pdf",base64:result.bytes.toString("base64"),changeSummary:`Cotización ${quote.quoteNumber} · versión comercial ${quote.version}`},actor);document={id:central.id,path:uploaded.version.storagePath,hash:uploaded.version.sha256};}else document=await this.r.uploadQuotePdf(quote,result.bytes,result.hash);await this.r.createQuoteVersion(quote,quote as unknown as Record<string,unknown>,document.path?{id:document.id,hash:document.hash,path:document.path}:undefined);const item=await this.r.transitionQuote(id,"READY_TO_SEND",{documentId:document.id,documentHash:document.hash});await this.r.publish("QUOTE",id,"QUOTE_PDF_GENERATED",actorId,{documentId:document.id,hash:document.hash,templateVersion:"QUOTE_V1"});return{quote:item,filename:result.filename,hash:result.hash};}
async send(id:string,to:string,idempotencyKey:string,actorId:string|null){const quote=await this.get(id);if(quote.status!=="READY_TO_SEND"||!quote.documentId)throw new ConflictException("Genera el PDF aprobado antes de enviar.");if(!to?.includes("@"))throw new BadRequestException("Email destinatario inválido.");if(!idempotencyKey)throw new BadRequestException("Falta Idempotency-Key.");const document=this.pdf.render(quote);const subject=`Cotización ${quote.quoteNumber} · Zyteron`;const sent=await this.mail.send({to,subject,idempotencyKey,html:`<div style="font-family:Arial;max-width:620px"><h1>Propuesta ${quote.quoteNumber}</h1><p>Hola ${quote.contactName||quote.companyName},</p><p>Adjuntamos la propuesta comercial preparada por Zyteron SpA, vigente hasta ${quote.validUntil||"la fecha acordada"}.</p><p><strong>Total: ${quote.totalAmount.toLocaleString("es-CL")} ${quote.currency}</strong></p><p>Responde este correo si necesitas cambios.</p></div>`,attachment:{filename:document.filename,contentBase64:document.bytes.toString("base64")}});await this.r.recordQuoteEmail(id,{to,subject,provider:sent.provider,providerMessageId:sent.messageId,sentBy:actorId});const item=await this.r.transitionQuote(id,"SENT",{sentAt:new Date().toISOString()});await this.r.publish("QUOTE",id,"QUOTE_SENT",actorId,{to,provider:sent.provider,providerMessageId:sent.messageId});return item;}
async accept(id:string,idempotencyKey:string,actorId:string|null){if(!idempotencyKey)throw new BadRequestException("Falta Idempotency-Key.");const quote=await this.get(id);if(!["SENT","NEGOTIATING","ACCEPTED"].includes(quote.status))throw new ConflictException("La cotización no está disponible para aceptación.");return this.r.acceptQuote(id,actorId,idempotencyKey);}
async workOrder(id:string,idempotencyKey:string,overrideReason:string|null,actorId:string|null){if(!idempotencyKey)throw new BadRequestException("Falta Idempotency-Key.");const quote=await this.get(id);if(!quote.clientId)throw new ConflictException("Vincula o crea el cliente antes de generar la OT.");return this.r.convertQuoteToWorkOrder(id,actorId,idempotencyKey,overrideReason);}
async createClient(id:string,input:CreateClientInput,actorId:string|null){const quote=await this.get(id);if(quote.clientId)return this.clients.get(quote.clientId);if(quote.status!=="ACCEPTED"&&quote.status!=="CONVERTED")throw new ConflictException("La cotización debe estar aceptada antes de crear el cliente.");const client=await this.clients.create(input);await this.r.linkQuoteClient(id,client.id);await this.r.publish("QUOTE",id,"QUOTE_CLIENT_LINKED",actorId,{clientId:client.id});return client;}
async contract(id:string,actorId:string|null){const quote=await this.get(id);if(!quote.clientId)throw new ConflictException("Vincula o crea el cliente antes de generar un contrato.");if(quote.status!=="ACCEPTED"&&quote.status!=="CONVERTED")throw new ConflictException("La cotización debe estar aceptada.");const contract=await this.contracts.create({clientId:quote.clientId,name:`Contrato ${quote.quoteNumber}`,description:quote.items.map((i)=>i.description).join(", "),contractType:"DESARROLLO",status:"DRAFT",startDate:new Date().toISOString().slice(0,10),endDate:null,renewalType:"NONE",renewalNoticeDays:30,billingFrequency:"ONE_TIME",currency:quote.currency,subtotal:quote.netAmount,tax:quote.taxAmount,total:quote.totalAmount,responsibleUserId:quote.ownerId,portalVisible:false});await this.r.linkSaleContract(id,contract.id);await this.r.publish("QUOTE",id,"QUOTE_CONVERTED_TO_CONTRACT",actorId,{contractId:contract.id});return contract;}
}
