import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import type {
  AssignmentRecommendation, DevelopmentAssignment, DevelopmentAttentionItem, DevelopmentBug, DevelopmentProjectSnapshot,
  DevelopmentRelease, DevelopmentSummary, DevelopmentTeamMember, DeveloperSkill, IntegrationConnection, ProjectEnvironment,
  ProjectRepository, ProjectTechnology, PullRequest, QaRun, QaTestCase, QaTestResult, TechnicalDebtItem,
} from "@zyteron/contracts";
import { optionalUuid, required } from "../commercial/commercial.validation.js";
import { OperationsService, type OperationsActor } from "../operations/operations.service.js";
import { DevelopmentRepository } from "./development.repository.js";
import { GitHubActionsProvider, GitHubSourceControlProvider, RenderDeploymentProvider } from "./development.providers.js";

const managers=new Set(["GERENTE_GENERAL","JEFE_DESARROLLO"]);
const technicalRoles=new Set(["GERENTE_GENERAL","JEFE_DESARROLLO","TECH_LEAD","PROGRAMADOR","QA","SOPORTE_TECNICO","DESARROLLO"]);
const uuid=(value:unknown,label:string)=>{const result=optionalUuid(value,label);if(!result)throw new BadRequestException(`${label} obligatorio.`);return result;};
const percent=(value:unknown)=>{const number=Number(value);if(!Number.isFinite(number)||number<0||number>100)throw new BadRequestException("Allocation debe estar entre 0 y 100.");return number;};
const page={page:1,pageSize:100};

@Injectable()
export class DevelopmentReadService {
  constructor(private readonly repository:DevelopmentRepository,private readonly operations:OperationsService){}
  private assertTechnical(actor:OperationsActor){if(!technicalRoles.has(actor.role))throw new ForbiddenException("No tienes acceso técnico.");}
  private async allowed<T extends{projectId:string}>(items:T[],actor:OperationsActor){if(managers.has(actor.role))return items;const projects=await this.operations.listProjects(page,actor),ids=new Set(projects.items.map(i=>i.id));return items.filter(i=>ids.has(i.projectId));}
  async summary(actor:OperationsActor):Promise<DevelopmentSummary>{
    this.assertTechnical(actor);
    const[projects,tasks,deployments,rawPrs,rawQa,rawBugs,rawReleases,rawEnvironments,team]=await Promise.all([this.operations.listProjects(page,actor),this.operations.listTasks(page,actor),this.operations.listDeployments(page,actor),this.repository.list<PullRequest>("pull_requests"),this.repository.list<QaRun>("qa_runs"),this.repository.list<DevelopmentBug>("bugs"),this.repository.list<DevelopmentRelease>("releases"),this.repository.list<ProjectEnvironment>("project_environments"),this.team(actor)]);const[prs,qa,bugs,releases,environments]=await Promise.all([this.allowed(rawPrs,actor),this.allowed(rawQa,actor),this.allowed(rawBugs,actor),this.allowed(rawReleases,actor),this.allowed(rawEnvironments,actor)]);
    const active=projects.items.filter(i=>!["COMPLETED","CANCELLED","ARCHIVED"].includes(i.status));const horizon=new Date(Date.now()+14*86400000).toISOString();
    return{unassignedProjects:active.filter(i=>!i.projectLeadId).length,activeProjects:active.length,availableDevelopers:team.filter(i=>i.availability==="AVAILABLE"||i.availability==="PARTIAL").length,overloadedDevelopers:team.filter(i=>i.availability==="FULL").length,blockedTasks:tasks.items.filter(i=>i.status==="BLOCKED").length,pendingPullRequests:prs.filter(i=>["OPEN","REVIEW_REQUIRED","CHANGES_REQUESTED"].includes(i.status)).length,pendingQa:qa.filter(i=>["PLANNED","IN_PROGRESS","BLOCKED"].includes(i.status)).length,criticalBugs:bugs.filter(i=>["CRITICAL","BLOCKER"].includes(i.severity)&&!["RESOLVED","CLOSED","WONT_FIX","DUPLICATE"].includes(i.status)).length,failedDeployments:deployments.items.filter(i=>i.status==="FAILED").length,upcomingReleases:releases.filter(i=>i.plannedAt&&i.plannedAt<=horizon&&!["RELEASED","CANCELLED"].includes(i.status)).length,productionPending:releases.filter(i=>i.targetEnvironment==="PRODUCTION"&&["READY","PENDING_APPROVAL"].includes(i.status)).length,technicalIncidents:environments.filter(i=>["DOWN","DEGRADED"].includes(i.status)).length};
  }
  async attention(actor:OperationsActor):Promise<DevelopmentAttentionItem[]>{
    const[projects,tasks,deployments,rawPrs,rawQa,rawBugs,rawReleases,rawEnvironments]=await Promise.all([this.operations.listProjects(page,actor),this.operations.listTasks(page,actor),this.operations.listDeployments(page,actor),this.repository.list<PullRequest>("pull_requests"),this.repository.list<QaRun>("qa_runs"),this.repository.list<DevelopmentBug>("bugs"),this.repository.list<DevelopmentRelease>("releases"),this.repository.list<ProjectEnvironment>("project_environments")]);const[prs,qa,bugs,releases,environments]=await Promise.all([this.allowed(rawPrs,actor),this.allowed(rawQa,actor),this.allowed(rawBugs,actor),this.allowed(rawReleases,actor),this.allowed(rawEnvironments,actor)]);
    const items:DevelopmentAttentionItem[]=[];const push=(value:DevelopmentAttentionItem)=>items.push(value);
    deployments.items.filter(i=>i.status==="FAILED").forEach(i=>push({id:i.id,type:"DEPLOYMENT",title:`${i.projectName??"Proyecto"} · ${i.environment}`,reason:"Deployment fallido",severity:"CRITICAL",href:"/development/deployments",occurredAt:i.completedAt}));
    bugs.filter(i=>["CRITICAL","BLOCKER"].includes(i.severity)&&!["CLOSED","RESOLVED"].includes(i.status)).forEach(i=>push({id:i.id,type:"BUG",title:i.title,reason:`Bug ${i.severity.toLowerCase()}`,severity:"CRITICAL",href:"/development/bugs",occurredAt:i.detectedAt}));
    projects.items.filter(i=>!i.projectLeadId&&!["COMPLETED","CANCELLED","ARCHIVED"].includes(i.status)).forEach(i=>push({id:i.id,type:"PROJECT",title:i.name,reason:"Proyecto sin responsable técnico",severity:"AT_RISK",href:"/development/assignments",occurredAt:i.createdAt}));
    tasks.items.filter(i=>i.status==="BLOCKED").forEach(i=>push({id:i.id,type:"TASK",title:i.title,reason:i.blockedReason||"Tarea bloqueada",severity:i.priority==="CRITICAL"?"CRITICAL":"AT_RISK",href:"/tasks",occurredAt:i.updatedAt}));
    qa.filter(i=>i.status==="FAILED").forEach(i=>push({id:i.id,type:"QA",title:i.name,reason:"QA rechazado",severity:"AT_RISK",href:"/development/qa",occurredAt:i.completedAt}));
    prs.filter(i=>i.status==="CHANGES_REQUESTED"||i.checksStatus==="FAIL").forEach(i=>push({id:i.id,type:"PULL_REQUEST",title:`PR #${i.number} · ${i.title}`,reason:i.checksStatus==="FAIL"?"Checks fallando":"Cambios solicitados",severity:"AT_RISK",href:"/development/pull-requests",occurredAt:i.updatedAt}));
    environments.filter(i=>["DOWN","DEGRADED"].includes(i.status)).forEach(i=>push({id:i.id,type:"ENVIRONMENT",title:i.name,reason:`Ambiente ${i.status.toLowerCase()}`,severity:i.status==="DOWN"?"CRITICAL":"AT_RISK",href:"/development/environments",occurredAt:i.updatedAt}));
    releases.filter(i=>i.plannedAt&&new Date(i.plannedAt).getTime()<Date.now()&&!["RELEASED","CANCELLED"].includes(i.status)).forEach(i=>push({id:i.id,type:"RELEASE",title:i.name,reason:"Release fuera de plazo",severity:"AT_RISK",href:"/development/releases",occurredAt:i.plannedAt}));
    return items.sort((a,b)=>({CRITICAL:0,AT_RISK:1,ATTENTION:2}[a.severity]-{CRITICAL:0,AT_RISK:1,ATTENTION:2}[b.severity])).slice(0,40);
  }
  async assignments(actor:OperationsActor):Promise<DevelopmentAssignment[]>{const projects=await this.operations.listProjects(page,actor);const result:DevelopmentAssignment[]=[];for(const project of projects.items.filter(i=>!i.projectLeadId||!i.developmentManagerId)){const[members,technologies]=await Promise.all([this.operations.listMembers(project.id,actor),this.repository.list<ProjectTechnology>("project_technologies",{projectId:project.id})]);result.push({project,members,technologies,recommendation:await this.recommend(technologies,actor)});}return result;}
  async recommend(technologies:ProjectTechnology[],actor:OperationsActor):Promise<AssignmentRecommendation|null>{const team=await this.team(actor);const ranked=team.filter(i=>i.role==="PROGRAMADOR"||i.role==="TECH_LEAD").map(person=>{const matches=person.skills.filter(skill=>technologies.some(tech=>tech.name.toLowerCase()===skill.skill.toLowerCase())).map(i=>i.skill);return{person,matches,score:(100-person.allocation)+matches.length*20};}).sort((a,b)=>b.score-a.score)[0];return ranked?{userId:ranked.person.userId,name:ranked.person.name,allocation:ranked.person.allocation,activeProjects:ranked.person.activeProjects,matchingSkills:ranked.matches,reasons:[`${ranked.person.allocation}% carga`,ranked.matches.length?ranked.matches.join(" + "):"Disponibilidad operacional",`${ranked.person.activeProjects} proyectos activos`]}:null;}
  async team(actor:OperationsActor):Promise<DevelopmentTeamMember[]>{
    const[projects,tasks,skills]=await Promise.all([this.operations.listProjects(page,actor),this.operations.listTasks(page,actor),this.repository.list<DeveloperSkill>("developer_skills")]);
    const members=new Map<string,{name:string;role:"PROGRAMADOR"|"TECH_LEAD"|"QA"|null;allocations:number[];projects:Set<string>}>();
    for(const project of projects.items){for(const member of await this.operations.listMembers(project.id,actor)){const current=members.get(member.userId)??{name:member.userName||`Usuario ${member.userId.slice(0,8)}`,role:member.projectRole==="TECH_LEAD"?"TECH_LEAD":member.projectRole==="QA"?"QA":"PROGRAMADOR",allocations:[],projects:new Set<string>()};current.allocations.push(member.allocationPercentage??0);current.projects.add(project.id);members.set(member.userId,current);}}
    return[...members.entries()].map(([userId,value])=>{const allocation=Math.min(100,value.allocations.reduce((a,b)=>a+b,0));const assigned=tasks.items.filter(i=>i.assignedTo===userId&&!['DONE','CANCELLED'].includes(i.status));const deadlines=projects.items.filter(i=>value.projects.has(i.id)&&i.targetDate).map(i=>i.targetDate!).sort();return{userId,name:value.name,role:value.role,availability:allocation>=100?"FULL":allocation>=70?"PARTIAL":"AVAILABLE",activeProjects:value.projects.size,openTasks:assigned.length,blockedTasks:assigned.filter(i=>i.status==="BLOCKED").length,plannedHours:Math.round(assigned.reduce((sum,i)=>sum+(i.estimatedMinutes??0),0)/60),allocation,nextDeadline:deadlines[0]??null,skills:skills.filter(i=>i.userId===userId)};});
  }
  async myProjects(actor:OperationsActor){return this.operations.listProjects({...page,userId:actor.userId??undefined},actor);}
  async repositories(actor:OperationsActor){return this.allowed(await this.repository.list<ProjectRepository>("project_repositories"),actor);}
  async pullRequests(actor:OperationsActor){return this.allowed(await this.repository.list<PullRequest>("pull_requests"),actor);}
  async environments(actor:OperationsActor){return this.allowed(await this.repository.list<ProjectEnvironment>("project_environments"),actor);}
  async technologies(actor:OperationsActor,projectId?:string){const items=await this.repository.list<ProjectTechnology>("project_technologies",projectId?{projectId}:{});return this.allowed(items,actor);}
  skills(){return this.repository.list<DeveloperSkill>("developer_skills");}
  integrations(){return this.repository.list<IntegrationConnection>("integration_connections");}
  async activity(actor:OperationsActor,projectId?:string){const items=await this.repository.activity(projectId);if(managers.has(actor.role))return items;const projects=await this.operations.listProjects(page,actor),ids=new Set(projects.items.map(i=>i.id));return items.filter(i=>i.projectId&&ids.has(i.projectId));}
  async snapshot(projectId:string,actor:OperationsActor):Promise<DevelopmentProjectSnapshot>{const project=await this.operations.getProject(projectId,actor);const[members,technologies,repositories,environments,pullRequests,qaRuns,bugs,releases,deployments]=await Promise.all([this.operations.listMembers(projectId,actor),this.technologies(actor,projectId),this.repository.list<ProjectRepository>("project_repositories",{projectId}),this.repository.list<ProjectEnvironment>("project_environments",{projectId}),this.repository.list<PullRequest>("pull_requests",{projectId}),this.repository.list<QaRun>("qa_runs",{projectId}),this.repository.list<DevelopmentBug>("bugs",{projectId}),this.repository.list<DevelopmentRelease>("releases",{projectId}),this.operations.listDeployments({...page,projectId},actor)]);const reasons:string[]=[];if(bugs.some(i=>["CRITICAL","BLOCKER"].includes(i.severity)&&!["RESOLVED","CLOSED"].includes(i.status)))reasons.push("Bug crítico abierto");if(qaRuns.some(i=>i.status==="FAILED"))reasons.push("QA fallido");if(deployments.items.some(i=>i.status==="FAILED"))reasons.push("Deployment fallido");if(environments.some(i=>i.status==="DOWN"))reasons.push("Ambiente fuera de servicio");const techHealth=reasons.some(i=>i.includes("crítico")||i.includes("fuera"))?"CRITICAL":reasons.length?"AT_RISK":"HEALTHY";return{project,members,technologies,repositories,environments,pullRequests,qaRuns,bugs,releases,deployments:deployments.items,techHealth,healthReasons:reasons.length?reasons:["Sin señales técnicas negativas disponibles."]};}
}

@Injectable()
export class DevelopmentManagementService {
  constructor(private readonly repository:DevelopmentRepository,private readonly operations:OperationsService){}
  private manager(actor:OperationsActor){if(!managers.has(actor.role))throw new ForbiddenException("Solo Jefatura de Desarrollo o Gerencia puede ejecutar esta acción.");}
  async assign(projectId:string,body:any,actor:OperationsActor){this.manager(actor);await this.operations.getProject(projectId,actor);const userId=uuid(body.userId,"Usuario");const member=await this.operations.addMember(projectId,{userId,userName:body.userName,projectRole:body.projectRole||"DEVELOPER",allocationPercentage:percent(body.allocationPercentage??0)},actor);if(body.projectRole==="TECH_LEAD")await this.operations.updateProject(projectId,{projectLeadId:userId},actor);await this.repository.publish(projectId,"PROJECT_MEMBER",member.id,"PROJECT_TECH_ASSIGNED",actor.userId,{userId,projectRole:member.projectRole});return member;}
  async addSkill(body:any,actor:OperationsActor){const userId=uuid(body.userId,"Usuario");if(!managers.has(actor.role)&&actor.userId!==userId)throw new ForbiddenException();const item=await this.repository.create<DeveloperSkill&Record<string,unknown>>("developer_skills",{userId,skill:required(body.skill,"Skill"),level:body.level||"INTERMEDIATE",verifiedBy:managers.has(actor.role)?actor.userId:null,updatedAt:new Date().toISOString()} as DeveloperSkill&Record<string,unknown>);return item;}
  async connectRepository(projectId:string,body:any,actor:OperationsActor){this.manager(actor);await this.operations.getProject(projectId,actor);const url=required(body.repositoryUrl,"URL de repositorio");try{new URL(url);}catch{throw new BadRequestException("URL de repositorio inválida.");}const item=await this.repository.create<ProjectRepository&Record<string,unknown>>("project_repositories",{projectId,projectName:null,provider:body.provider||"GITHUB",repositoryOwner:required(body.repositoryOwner,"Owner"),repositoryName:required(body.repositoryName,"Repositorio"),repositoryUrl:url,defaultBranch:body.defaultBranch||"main",integrationStatus:"NOT_CONFIGURED",visibility:body.visibility||"PRIVATE"} as ProjectRepository&Record<string,unknown>);await this.repository.publish(projectId,"REPOSITORY",item.id,"REPOSITORY_CONNECTED",actor.userId,{provider:item.provider,configured:false});return item;}
  async disconnectRepository(id:string,actor:OperationsActor){this.manager(actor);const item=await this.repository.get<ProjectRepository>("project_repositories",id);if(!item)throw new NotFoundException("Repositorio no encontrado.");await this.repository.remove("project_repositories",id);await this.repository.publish(item.projectId,"REPOSITORY",id,"REPOSITORY_DISCONNECTED",actor.userId);return{deleted:true};}
  async createEnvironment(projectId:string,body:any,actor:OperationsActor){this.manager(actor);await this.operations.getProject(projectId,actor);return this.repository.create<ProjectEnvironment&Record<string,unknown>>("project_environments",{projectId,projectName:null,name:required(body.name,"Nombre"),type:body.type||"DEVELOPMENT",url:body.url||null,status:body.status||"UNKNOWN",deploymentProvider:body.deploymentProvider||null,externalReference:body.externalReference||null,lastDeploymentId:null,responsibleUserId:optionalUuid(body.responsibleUserId,"Responsable")} as ProjectEnvironment&Record<string,unknown>);}
  updateEnvironment(id:string,body:any,actor:OperationsActor){this.manager(actor);return this.repository.update<ProjectEnvironment&Record<string,unknown>>("project_environments",id,body);}
  async addTechnology(projectId:string,body:any,actor:OperationsActor){this.manager(actor);await this.operations.getProject(projectId,actor);return this.repository.create<ProjectTechnology&Record<string,unknown>>("project_technologies",{projectId,category:body.category||"OTHER",name:required(body.name,"Tecnología"),version:body.version||null} as ProjectTechnology&Record<string,unknown>);}
}

@Injectable()
export class IntegrationService {
  constructor(private readonly repository:DevelopmentRepository,private readonly github:GitHubSourceControlProvider,private readonly actions:GitHubActionsProvider,private readonly render:RenderDeploymentProvider){}
  health(){return[{provider:"GITHUB",status:this.github.configured()?"CONNECTED":"NOT_CONFIGURED",message:this.github.configured()?"GitHub App configurada":"GitHub no configurado"},{provider:"GITHUB_ACTIONS",status:this.actions.configured()?"CONNECTED":"NOT_CONFIGURED",message:this.actions.configured()?"CI configurado":"GitHub Actions no configurado"},{provider:"RENDER",status:this.render.configured()?"CONNECTED":"NOT_CONFIGURED",message:this.render.configured()?"Render configurado":"Proveedor de despliegue no configurado"},{provider:"SUPABASE",status:process.env.SUPABASE_URL?"CONNECTED":"NOT_CONFIGURED",message:process.env.SUPABASE_URL?"Supabase conectado":"Supabase no configurado"}];}
  async recordExternalEvent(provider:string,eventType:string,externalId:string,actorId:string|null){const previous=await this.repository.list<any>("external_integration_events",{provider,externalId});if(previous.length)return{duplicate:true,id:previous[0].id};const item=await this.repository.create<any>("external_integration_events",{provider,eventType,externalId,receivedAt:new Date().toISOString(),processedAt:new Date().toISOString(),status:"PROCESSED",error:null});await this.repository.publish(null,"EXTERNAL_EVENT",item.id,`${provider}_${eventType}`,actorId,{externalId});return{duplicate:false,id:item.id};}
}

@Injectable()
export class QualityService {
  constructor(private readonly repository:DevelopmentRepository,private readonly operations:OperationsService){}
  private async allowed<T extends{projectId:string}>(items:T[],actor:OperationsActor){if(managers.has(actor.role))return items;const projects=await this.operations.listProjects(page,actor),ids=new Set(projects.items.map(i=>i.id));return items.filter(i=>ids.has(i.projectId));}
  async qaRuns(actor:OperationsActor,projectId?:string){return this.allowed(await this.repository.list<QaRun>("qa_runs",projectId?{projectId}:{}),actor);}
  async testCases(actor:OperationsActor,projectId?:string){return this.allowed(await this.repository.list<QaTestCase>("qa_test_cases",projectId?{projectId}:{}),actor);}
  async bugs(actor:OperationsActor,projectId?:string){return this.allowed(await this.repository.list<DevelopmentBug>("bugs",projectId?{projectId}:{}),actor);}
  async createQa(body:any,actor:OperationsActor){const projectId=uuid(body.projectId,"Proyecto");await this.operations.getProject(projectId,actor);const item=await this.repository.create<any>("qa_runs",{projectId,releaseId:optionalUuid(body.releaseId,"Release"),environmentId:optionalUuid(body.environmentId,"Ambiente"),name:required(body.name,"Nombre"),status:"PLANNED",startedBy:null,assignedTo:optionalUuid(body.assignedTo,"Responsable"),startedAt:null,completedAt:null,result:null,notes:body.notes||null});await this.repository.publish(projectId,"QA_RUN",item.id,"QA_RUN_CREATED",actor.userId);return item;}
  async startQa(id:string,actor:OperationsActor){const current=await this.qa(id,actor);if(current.status!=="PLANNED")throw new BadRequestException("Solo una ejecución planificada puede iniciarse.");const item=await this.repository.update<any>("qa_runs",id,{status:"IN_PROGRESS",startedBy:actor.userId,startedAt:new Date().toISOString()});await this.repository.publish(current.projectId,"QA_RUN",id,"QA_STARTED",actor.userId);return item;}
  async addResult(id:string,body:any,actor:OperationsActor){const run=await this.qa(id,actor);if(run.status!=="IN_PROGRESS")throw new BadRequestException("QA debe estar en progreso.");const testCaseId=uuid(body.testCaseId,"Caso de prueba");const item=await this.repository.create<any>("qa_test_results",{qaRunId:id,testCaseId,status:body.status||"PASS",actualResult:body.actualResult||null,evidenceDocumentId:optionalUuid(body.evidenceDocumentId,"Documento"),executedBy:actor.userId,executedAt:new Date().toISOString()});await this.repository.publish(run.projectId,"QA_RESULT",item.id,item.status==="FAIL"?"QA_FAILED":"QA_RESULT_RECORDED",actor.userId,{qaRunId:id,status:item.status});return item;}
  async completeQa(id:string,body:any,actor:OperationsActor){const run=await this.qa(id,actor);if(run.status!=="IN_PROGRESS")throw new BadRequestException("QA debe estar en progreso.");const results=await this.repository.list<QaTestResult>("qa_test_results",{qaRunId:id});const status=body.status||(results.some(i=>i.status==="FAIL")?"FAILED":results.some(i=>i.status==="BLOCKED")?"BLOCKED":"PASSED");if(!["PASSED","PASSED_WITH_OBSERVATIONS","FAILED","BLOCKED","CANCELLED"].includes(status))throw new BadRequestException("Resultado QA inválido.");const item=await this.repository.update<any>("qa_runs",id,{status,result:body.result||null,notes:body.notes??run.notes,completedAt:new Date().toISOString()});await this.repository.publish(run.projectId,"QA_RUN",id,status==="PASSED"?"QA_PASSED":"QA_FAILED",actor.userId,{status});return item;}
  async qa(id:string,actor?:OperationsActor){const item=await this.repository.get<QaRun>("qa_runs",id);if(!item)throw new NotFoundException("Ejecución QA no encontrada.");if(actor)await this.operations.getProject(item.projectId,actor);return item;}
  async createTestCase(body:any,actor:OperationsActor){const projectId=uuid(body.projectId,"Proyecto");await this.operations.getProject(projectId,actor);return this.repository.create<any>("qa_test_cases",{projectId,suite:body.suite||"General",title:required(body.title,"Título"),description:body.description||null,preconditions:body.preconditions||null,expectedResult:required(body.expectedResult,"Resultado esperado"),priority:body.priority||"NORMAL",active:true});}
  async createBug(body:any,actor:OperationsActor){const projectId=uuid(body.projectId,"Proyecto");await this.operations.getProject(projectId,actor);const item=await this.repository.create<any>("bugs",{projectId,taskId:optionalUuid(body.taskId,"Tarea"),title:required(body.title,"Título"),description:required(body.description,"Descripción"),severity:body.severity||"MEDIUM",priority:body.priority||"NORMAL",environment:body.environment||null,status:"NEW",reportedBy:actor.userId,assignedTo:optionalUuid(body.assignedTo,"Responsable"),stepsToReproduce:body.stepsToReproduce||null,expectedBehavior:body.expectedBehavior||null,actualBehavior:body.actualBehavior||null,evidenceDocumentId:optionalUuid(body.evidenceDocumentId,"Documento"),clientVisibility:body.clientVisibility||"INTERNAL_ONLY",detectedAt:new Date().toISOString(),resolvedAt:null});await this.repository.publish(projectId,"BUG",item.id,item.severity==="CRITICAL"||item.severity==="BLOCKER"?"BUG_CRITICAL":"BUG_CREATED",actor.userId,{severity:item.severity});return item;}
  async bug(id:string,actor?:OperationsActor){const item=await this.repository.get<DevelopmentBug>("bugs",id);if(!item)throw new NotFoundException("Bug no encontrado.");if(actor)await this.operations.getProject(item.projectId,actor);return item;}
  async changeBug(id:string,patch:any,actor:OperationsActor){const current=await this.bug(id,actor);const allowed:Record<string,string[]>={NEW:["TRIAGED","ASSIGNED","WONT_FIX","DUPLICATE"],TRIAGED:["ASSIGNED","IN_PROGRESS","WONT_FIX","DUPLICATE"],ASSIGNED:["IN_PROGRESS","WONT_FIX"],IN_PROGRESS:["READY_FOR_QA","RESOLVED"],READY_FOR_QA:["RESOLVED","REOPENED"],REOPENED:["IN_PROGRESS","READY_FOR_QA"],RESOLVED:["CLOSED","REOPENED"],CLOSED:["REOPENED"],WONT_FIX:["REOPENED"],DUPLICATE:["REOPENED"]};if(patch.status&&patch.status!==current.status&&!allowed[current.status]?.includes(patch.status))throw new BadRequestException(`Transición ${current.status} → ${patch.status} no permitida.`);const item=await this.repository.update<any>("bugs",id,{...patch,resolvedAt:["RESOLVED","CLOSED"].includes(patch.status)?new Date().toISOString():patch.status?null:undefined});for(const field of ["status","assignedTo","severity"]){if(patch[field]!==undefined&&patch[field]!==current[field as keyof DevelopmentBug])await this.repository.create<any>("bug_history",{bugId:id,field,fromValue:String(current[field as keyof DevelopmentBug]??""),toValue:String(patch[field]),reason:patch.reason||null,changedBy:actor.userId,changedAt:new Date().toISOString()});}await this.repository.publish(current.projectId,"BUG",id,patch.status==="REOPENED"?"BUG_REOPENED":patch.status==="RESOLVED"?"BUG_RESOLVED":"BUG_UPDATED",actor.userId,{status:patch.status,assignedTo:patch.assignedTo});return item;}
}

@Injectable()
export class ReleaseService {
  constructor(private readonly repository:DevelopmentRepository,private readonly operations:OperationsService){}
  private async allowed<T extends{projectId:string}>(items:T[],actor:OperationsActor){if(managers.has(actor.role))return items;const projects=await this.operations.listProjects(page,actor),ids=new Set(projects.items.map(i=>i.id));return items.filter(i=>ids.has(i.projectId));}
  async releases(actor:OperationsActor,projectId?:string){return this.allowed(await this.repository.list<DevelopmentRelease>("releases",projectId?{projectId}:{}),actor);}
  async debt(actor:OperationsActor,projectId?:string){return this.allowed(await this.repository.list<TechnicalDebtItem>("technical_debt_items",projectId?{projectId}:{}),actor);}
  async createRelease(body:any,actor:OperationsActor){const projectId=uuid(body.projectId,"Proyecto");await this.operations.getProject(projectId,actor);const item=await this.repository.create<any>("releases",{projectId,version:required(body.version,"Versión"),name:body.name||body.version,status:body.status||"DRAFT",targetEnvironment:body.targetEnvironment||"STAGING",plannedAt:body.plannedAt||null,releasedAt:null,createdBy:actor.userId,approvedBy:null,releaseNotes:body.releaseNotes||null,commitSha:body.commitSha||null,deploymentId:null,clientVisibility:body.clientVisibility||"INTERNAL_ONLY"});await this.repository.publish(projectId,"RELEASE",item.id,"RELEASE_CREATED",actor.userId);return item;}
  async release(id:string,actor?:OperationsActor){const item=await this.repository.get<DevelopmentRelease>("releases",id);if(!item)throw new NotFoundException("Release no encontrada.");if(actor)await this.operations.getProject(item.projectId,actor);return item;}
  async updateRelease(id:string,body:any,actor:OperationsActor){await this.release(id,actor);return this.repository.update<any>("releases",id,body);}
  async approve(id:string,actor:OperationsActor){if(!managers.has(actor.role))throw new ForbiddenException("No tienes permiso para aprobar releases.");const current=await this.release(id,actor);if(!["READY","PENDING_APPROVAL"].includes(current.status))throw new BadRequestException("La release no está lista para aprobación.");const item=await this.repository.update<any>("releases",id,{status:"READY",approvedBy:actor.userId});await this.repository.publish(current.projectId,"RELEASE",id,"RELEASE_READY",actor.userId);return item;}
  async deploy(id:string,body:any,actor:OperationsActor){const release=await this.release(id,actor);if(!["READY","PENDING_APPROVAL"].includes(release.status))throw new BadRequestException("La release debe estar lista.");if(release.targetEnvironment==="PRODUCTION"){const[qa,prs]=await Promise.all([this.repository.list<QaRun>("qa_runs",{projectId:release.projectId}),this.repository.list<PullRequest>("pull_requests",{projectId:release.projectId})]);if(!qa.some(i=>i.status==="PASSED"||i.status==="PASSED_WITH_OBSERVATIONS")&&!body.overrideReason)throw new BadRequestException("Producción requiere QA aprobado o un override autorizado con motivo.");if(prs.length&& !prs.some(i=>i.status==="MERGED")&&!body.overrideReason)throw new BadRequestException("Producción requiere una PR merged o un override autorizado con motivo.");if(body.overrideReason&&!managers.has(actor.role))throw new ForbiddenException("Solo Jefatura o Gerencia puede aplicar override.");}
    const deployment=await this.operations.createDeployment({projectId:release.projectId,environment:release.targetEnvironment,version:release.version,commitSha:release.commitSha,status:"PLANNED",notes:body.overrideReason?`Override: ${body.overrideReason}`:"Release aprobada",clientVisibility:release.clientVisibility==="CLIENT_VISIBLE"?"CLIENT_VISIBLE":"INTERNAL"},actor);const item=await this.repository.update<any>("releases",id,{status:"DEPLOYING",deploymentId:deployment.id});await this.repository.publish(release.projectId,"RELEASE",id,"RELEASE_DEPLOYMENT_REQUESTED",actor.userId,{deploymentId:deployment.id});return item;}
  async rollback(id:string,body:any,actor:OperationsActor){if(!managers.has(actor.role))throw new ForbiddenException();const release=await this.release(id,actor);const reason=required(body.reason,"Motivo");const item=await this.repository.update<any>("releases",id,{status:"ROLLED_BACK"});await this.repository.publish(release.projectId,"RELEASE",id,"RELEASE_ROLLBACK_RECORDED",actor.userId,{reason,manual:true});return item;}
  async createDebt(body:any,actor:OperationsActor){const projectId=uuid(body.projectId,"Proyecto");await this.operations.getProject(projectId,actor);return this.repository.create<any>("technical_debt_items",{projectId,title:required(body.title,"Título"),description:required(body.description,"Descripción"),impact:body.impact||null,severity:body.severity||"MEDIUM",estimatedEffort:body.estimatedEffort===undefined?null:Number(body.estimatedEffort),status:"OPEN",ownerId:optionalUuid(body.ownerId,"Responsable"),targetDate:body.targetDate||null});}
  async updateDebt(id:string,body:any,actor:OperationsActor){const current=await this.repository.get<TechnicalDebtItem>("technical_debt_items",id);if(!current)throw new NotFoundException("Deuda técnica no encontrada.");await this.operations.getProject(current.projectId,actor);return this.repository.update<any>("technical_debt_items",id,body);}
}
