import { BadRequestException, ForbiddenException } from "@nestjs/common";
import { createHmac } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import { OperationsRepository } from "../operations/operations.repository.js";
import { OperationsService, type OperationsActor } from "../operations/operations.service.js";
import { GitHubActionsProvider, GitHubSourceControlProvider, RenderDeploymentProvider } from "./development.providers.js";
import { DevelopmentRepository } from "./development.repository.js";
import { DevelopmentManagementService, DevelopmentReadService, IntegrationService, QualityService, ReleaseService } from "./development.service.js";

const managerId="33333333-3333-4333-8333-333333333333",developerId="44444444-4444-4444-8444-444444444444";
const manager:OperationsActor={userId:managerId,role:"GERENTE_GENERAL"};

describe("Development Operations Center",()=>{
  let operations:OperationsService,repository:DevelopmentRepository,read:DevelopmentReadService,management:DevelopmentManagementService,quality:QualityService,releases:ReleaseService,integrations:IntegrationService;
  beforeEach(()=>{delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;delete process.env.GITHUB_APP_ID;delete process.env.GITHUB_PRIVATE_KEY;delete process.env.RENDER_API_KEY;operations=new OperationsService(new OperationsRepository());repository=new DevelopmentRepository();read=new DevelopmentReadService(repository,operations);management=new DevelopmentManagementService(repository,operations);quality=new QualityService(repository,operations);releases=new ReleaseService(repository,operations);integrations=new IntegrationService(repository,new GitHubSourceControlProvider(),new GitHubActionsProvider(),new RenderDeploymentProvider());});
  async function project(key="dev-project",assignee=developerId){const order=await operations.createWorkOrder({title:"Plataforma",scope:"Desarrollo técnico"},manager);await operations.workOrderStatus(order.id,"READY_FOR_HANDOFF",null,manager);await operations.acceptHandoff(order.id,manager);await operations.planWorkOrder(order.id,{plannedStartDate:"2026-10-01",targetDate:"2026-12-01",estimatedHours:100},manager);await operations.assignWorkOrder(order.id,assignee,manager);return operations.convertWorkOrder(order.id,{},key,manager);}

  it("asigna Project Core y calcula carga sin duplicar proyectos",async()=>{const p=await project();await management.assign(p.id,{userId:developerId,projectRole:"DEVELOPER",allocationPercentage:75},manager);const team=await read.team(manager);expect(team[0]?.allocation).toBe(75);expect((await read.assignments(manager)).some(i=>i.project.id===p.id)).toBe(true);});
  it("vincula repositorios reales como no configurados cuando no existe provider",async()=>{const p=await project("repo-project");const repo=await management.connectRepository(p.id,{repositoryOwner:"iag-lol",repositoryName:"zyteroncontrol",repositoryUrl:"https://github.com/iag-lol/zyteroncontrol",defaultBranch:"main"},manager);expect(repo.integrationStatus).toBe("NOT_CONFIGURED");expect(integrations.health().find(i=>i.provider==="GITHUB")?.status).toBe("NOT_CONFIGURED");});
  it("ejecuta QA y deriva FAILED o PASSED desde resultados",async()=>{const p=await project("qa-project");const testCase=await quality.createTestCase({projectId:p.id,title:"Login",expectedResult:"Acceso autorizado"},manager);const run=await quality.createQa({projectId:p.id,name:"Regression"},manager);await quality.startQa(run.id,manager);await quality.addResult(run.id,{testCaseId:testCase.id,status:"FAIL",actualResult:"Error 500"},manager);expect((await quality.completeQa(run.id,{},manager)).status).toBe("FAILED");const second=await quality.createQa({projectId:p.id,name:"Retest"},manager);await quality.startQa(second.id,manager);expect((await quality.completeQa(second.id,{status:"PASSED"},manager)).status).toBe("PASSED");});
  it("mantiene historia de bugs y permite reopen después de resolver",async()=>{const p=await project("bug-project");const bug=await quality.createBug({projectId:p.id,title:"Formulario",description:"No envía",severity:"CRITICAL"},manager);await quality.changeBug(bug.id,{status:"TRIAGED"},manager);await quality.changeBug(bug.id,{status:"ASSIGNED",assignedTo:developerId},manager);await quality.changeBug(bug.id,{status:"IN_PROGRESS"},manager);await quality.changeBug(bug.id,{status:"RESOLVED"},manager);expect((await quality.changeBug(bug.id,{status:"REOPENED",reason:"QA volvió a fallar"},manager)).status).toBe("REOPENED");expect((await repository.list("bug_history",{bugId:bug.id})).length).toBeGreaterThan(3);});
  it("bloquea producción sin QA y registra deployment cuando el gate se cumple",async()=>{const p=await project("release-gate");const release=await releases.createRelease({projectId:p.id,version:"1.0.0",status:"READY",targetEnvironment:"PRODUCTION"},manager);await expect(releases.deploy(release.id,{},manager)).rejects.toBeInstanceOf(BadRequestException);const run=await quality.createQa({projectId:p.id,name:"Production gate"},manager);await quality.startQa(run.id,manager);await quality.completeQa(run.id,{status:"PASSED"},manager);expect((await releases.deploy(release.id,{},manager)).status).toBe("DEPLOYING");});
  it("valida firma GitHub y procesa deliveries idempotentes",async()=>{process.env.GITHUB_WEBHOOK_SECRET="secret";const provider=new GitHubSourceControlProvider(),payload=Buffer.from('{"action":"opened"}'),signature=`sha256=${createHmac("sha256","secret").update(payload).digest("hex")}`;expect(provider.verifyWebhook(payload,signature)).toBe(true);expect(provider.verifyWebhook(payload,"sha256=bad")).toBe(false);expect((await integrations.recordExternalEvent("GITHUB","pull_request","delivery-1",null)).duplicate).toBe(false);expect((await integrations.recordExternalEvent("GITHUB","pull_request","delivery-1",null)).duplicate).toBe(true);});
  it("deniega al programador A los recursos del Project B en backend",async()=>{const a=await project("scope-a",developerId),b=await project("scope-b","55555555-5555-4555-8555-555555555555");await management.connectRepository(a.id,{repositoryOwner:"org",repositoryName:"a",repositoryUrl:"https://github.com/org/a"},manager);await management.connectRepository(b.id,{repositoryOwner:"org",repositoryName:"b",repositoryUrl:"https://github.com/org/b"},manager);const actor:OperationsActor={userId:developerId,role:"PROGRAMADOR"};expect((await read.repositories(actor)).map(i=>i.projectId)).toEqual([a.id]);const bug=await quality.createBug({projectId:b.id,title:"Privado",description:"No visible"},manager);await expect(quality.changeBug(bug.id,{status:"TRIAGED"},actor)).rejects.toBeInstanceOf(ForbiddenException);});
});

describe("migración Desarrollo",()=>{const sql=readFileSync(resolve(process.cwd(),"../../supabase/migrations/20261001020000_development_operations_center.sql"),"utf8");it("extiende Project Core sin tablas duplicadas",()=>{expect(sql).not.toContain("development_projects");expect(sql).not.toContain("development_tasks");expect(sql).not.toContain("developer_worklogs");expect(sql).toContain("references public.projects");expect(sql).toContain("references public.tasks");});it("incluye QA, bugs, releases, integraciones y gates",()=>{expect(sql).toContain("qa_runs");expect(sql).toContain("bug_history");expect(sql).toContain("project_development_settings");expect(sql).toContain("external_integration_events");});it("activa RLS, Realtime, RBAC y eventos",()=>{expect(sql).toContain("enable row level security");expect(sql).toContain("supabase_realtime");expect(sql).toContain("development.assignment.manage");expect(sql).toContain("development_events");});});
