"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Check, ChevronLeft, ChevronRight, FileCheck2, FileText, Layers3, ShieldCheck } from "lucide-react";
import type { Client } from "@zyteron/contracts";
import { useAccess } from "@/components/access-context";
import { clientsApi } from "@/lib/clients-api";
import { contractsApi,type ContractBuilderContext,type ContractTemplateCatalogItem } from "@/lib/client-domain-api";

const steps=["Origen","Plantillas","Condiciones","Economía","Revisión"];
const core=["ZT-PROYECTO-CL","ZT-CONDICIONES-CL"];
const today=new Date().toISOString().slice(0,10);
const get=(source:Record<string,unknown>,key:string)=>key.split(".").reduce<unknown>((value,part)=>value&&typeof value==="object"?(value as Record<string,unknown>)[part]:undefined,source);
const set=(source:Record<string,unknown>,key:string,value:string)=>{const copy=structuredClone(source),parts=key.split(".");let node=copy;parts.forEach((part,index)=>{if(index===parts.length-1)node[part]=value;else{if(!node[part]||typeof node[part]!=="object")node[part]={};node=node[part] as Record<string,unknown>;}});return copy;};
const text=(value:unknown)=>String(value??"");

export function ContractBuilder(){
  const{role}=useAccess(),router=useRouter();const[step,setStep]=useState(0),[clients,setClients]=useState<Client[]>([]),[templates,setTemplates]=useState<ContractTemplateCatalogItem[]>([]),[context,setContext]=useState<ContractBuilderContext>({client:null,projects:[],quotes:[],contacts:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const[form,setForm]=useState({clientId:"",projectId:"",quoteId:"",independentReason:"",name:"Contrato de desarrollo y servicios tecnológicos",contractType:"DESARROLLO",startDate:today,endDate:"",renewalType:"NONE",billingFrequency:"ONE_TIME",currency:"CLP",subtotal:0,tax:0,total:0,templateCodes:core as string[],values:{contrato:{lugar:"Santiago, Chile",fecha:today},empresa:{razon_social:"Zyteron SpA",rut:"78.398.774-0",domicilio:"Santiago, Chile"},pi:{modalidad:"A"}} as Record<string,unknown>});
  useEffect(()=>{Promise.all([clientsApi.list(role,new URLSearchParams({pageSize:"100"})),contractsApi.templates(role)]).then(([c,t])=>{setClients(c.items);setTemplates(t);const projectId=new URL(window.location.href).searchParams.get("projectId");const clientId=new URL(window.location.href).searchParams.get("clientId");if(clientId)setForm(value=>({...value,clientId}));if(projectId)setForm(value=>({...value,projectId}));}).catch((cause:Error)=>setError(cause.message)).finally(()=>setLoading(false));},[role]);
  useEffect(()=>{if(!form.clientId){setContext({client:null,projects:[],quotes:[],contacts:[]});return;}setError("");contractsApi.context(role,form.clientId).then(data=>{setContext(data);const client=data.client??{};setForm(value=>({...value,projectId:data.projects.some(project=>project.id===value.projectId)?value.projectId:data.projects.length===1?text(data.projects[0]?.id):"",quoteId:data.quotes.some(quote=>quote.id===value.quoteId)?value.quoteId:data.quotes.length===1?text(data.quotes[0]?.id):"",independentReason:data.quotes.length===1?"":value.independentReason,values:set(set(set(set(value.values,"cliente.razon_social",text(client.legal_name||client.trade_name)),"cliente.rut",text(client.rut)),"cliente.domicilio",[client.address,client.commune,client.region].filter(Boolean).join(", ")),"cliente.email_dte",text(client.dte_email))}));}).catch((cause:Error)=>setError(cause.message));},[form.clientId,role]);
  useEffect(()=>{const project=context.projects.find(item=>item.id===form.projectId);if(!project)return;setForm(value=>({...value,values:set(set(set(set(value.values,"proyecto.codigo",text(project.project_number)),"proyecto.nombre",text(project.name)),"proyecto.alcance",text(project.scope)),"calendario.inicio",text(project.planned_start_date||value.startDate))}));},[form.projectId,context.projects]);
  const selectedTemplates=templates.filter(template=>form.templateCodes.includes(template.code));const variables=useMemo(()=>[...new Map(selectedTemplates.flatMap(template=>template.variables).map(variable=>[variable.key,variable])).values()],[templates,form.templateCodes]);const humanVariables=variables.filter(variable=>!["contrato.numero"].includes(variable.key));
  const quote=context.quotes.find(item=>item.id===form.quoteId);useEffect(()=>{if(!quote)return;const subtotal=Number(quote.net_amount||0),tax=Number(quote.tax_amount||0),total=Number(quote.total_amount||0);setForm(value=>({...value,currency:text(quote.currency||"CLP"),subtotal,tax,total,values:set(set(set(set(set(value.values,"cotizacion.numero",text(quote.quote_number)),"cotizacion.version",text(quote.version)),"cotizacion.fecha_aceptacion",text(quote.accepted_at).slice(0,10)),"precio.neto",String(subtotal)),"precio.total",String(total))}));},[form.quoteId,context.quotes]);
  const localErrors=[!form.clientId?"Selecciona un cliente.":"",!form.projectId?"Selecciona un proyecto del mismo cliente.":"",!form.quoteId&&!form.independentReason.trim()?"Selecciona una cotización aceptada o justifica el contrato independiente.":"",!form.templateCodes.includes("ZT-PROYECTO-CL")||!form.templateCodes.includes("ZT-CONDICIONES-CL")?"Contrato base y Anexo 1 son obligatorios.":"",Math.abs(form.subtotal+form.tax-form.total)>.01?"Subtotal, impuestos y total no coinciden.":"",...[...variables].filter(variable=>variable.required&&variable.key!=="contrato.numero"&&!text(get(form.values,variable.key)).trim()).slice(0,8).map(variable=>`Completa ${variable.label}.`)].filter(Boolean);
  async function save(){setSaving(true);setError("");try{const created=await contractsApi.create(role,{clientId:form.clientId,projectId:form.projectId,quoteId:form.quoteId||null,independentReason:form.independentReason||null,name:form.name,description:"Contrato generado desde el asistente contractual.",contractType:form.contractType,status:"DRAFT",startDate:form.startDate||null,endDate:form.endDate||null,renewalType:form.renewalType,renewalNoticeDays:30,billingFrequency:form.billingFrequency,currency:form.currency,subtotal:form.subtotal,tax:form.tax,total:form.total,responsibleUserId:null,portalVisible:false,templateCodes:form.templateCodes,builderValues:form.values});router.push(`/clients/contracts/${created.id}`);}catch(cause){setError(cause instanceof Error?cause.message:"No fue posible crear el contrato.");}finally{setSaving(false);}}
  if(loading)return <main className="contractBuilder"><div className="domainLoading">Preparando el asistente contractual…</div></main>;
  return <main className="contractBuilder"><header className="builderHeader"><div><Link href="/clients/contracts">← Contratos</Link><span>Contractual System · Chile</span><h1>Crear contrato</h1><p>Documento versionado, revisable y listo para firma electrónica real.</p></div><div className="legalFlag"><ShieldCheck/><span><strong>Revisión legal requerida</strong><small>Las plantillas no se presentan como aprobadas profesionalmente.</small></span></div></header><nav className="builderSteps">{steps.map((label,index)=><button className={index===step?"active":index<step?"done":""} onClick={()=>setStep(index)} key={label}><i>{index<step?<Check/>:index+1}</i><span>{label}</span></button>)}</nav>{error?<div className="builderAlert"><AlertTriangle/>{error}</div>:null}<section className="builderCanvas">
    {step===0?<div className="builderPanel"><PanelTitle icon={<FileText/>} eyebrow="FUENTES CANÓNICAS" title="Cliente, proyecto y cotización" text="Solo se muestran proyectos y cotizaciones aceptadas del cliente seleccionado."/><div className="builderGrid"><label>Cliente existente *<select value={form.clientId} onChange={event=>setForm({...form,clientId:event.target.value,projectId:"",quoteId:""})}><option value="">Seleccionar cliente</option>{clients.map(client=><option value={client.id} key={client.id}>{client.tradeName||client.legalName}</option>)}</select></label><label>Proyecto del mismo cliente *<select value={form.projectId} onChange={event=>setForm({...form,projectId:event.target.value})}><option value="">Seleccionar proyecto</option>{context.projects.map(project=><option value={text(project.id)} key={text(project.id)}>{text(project.project_number)} · {text(project.name)}</option>)}</select></label><label>Cotización aceptada<select value={form.quoteId} onChange={event=>setForm({...form,quoteId:event.target.value,independentReason:event.target.value?"":form.independentReason})}><option value="">Contrato independiente</option>{context.quotes.map(item=><option value={text(item.id)} key={text(item.id)}>{text(item.quote_number)} · v{String(item.version)}</option>)}</select></label><label>Justificación si no hay cotización<textarea disabled={Boolean(form.quoteId)} value={form.independentReason} onChange={event=>setForm({...form,independentReason:event.target.value})} placeholder="Motivo verificable del contrato independiente"/></label></div><div className="sourceSnapshot"><strong>Snapshot de origen</strong><span>{context.client?"Cliente cargado":"Cliente pendiente"}</span><span>{form.projectId?"Proyecto vinculado":"Proyecto pendiente"}</span><span>{form.quoteId?"Cotización aceptada vinculada":"Sin cotización"}</span></div></div>:null}
    {step===1?<div className="builderPanel"><PanelTitle icon={<Layers3/>} eyebrow="DOCUMENTOS APLICABLES" title="Plantillas y anexos" text="El contrato base y las condiciones particulares son obligatorios; los demás anexos dependen del alcance real."/><div className="templatePicker">{templates.map(template=>{const required=core.includes(template.code),checked=form.templateCodes.includes(template.code);return <label className={checked?"selected":""} key={template.code}><input type="checkbox" checked={checked} disabled={required} onChange={()=>setForm({...form,templateCodes:checked?form.templateCodes.filter(code=>code!==template.code):[...form.templateCodes,template.code]})}/><FileCheck2/><span><strong>{template.name}</strong><small>{template.code} · v{template.version} · {template.variableCount} variables</small></span><b>{required?"Obligatorio":template.category}</b></label>})}</div></div>:null}
    {step===2?<div className="builderPanel"><PanelTitle icon={<FileText/>} eyebrow="REGISTRO DE VARIABLES" title="Condiciones y decisiones humanas" text={`${humanVariables.length} variables provienen de fuentes canónicas o requieren una decisión explícita.`}/><div className="variableEditor">{humanVariables.map(variable=><label key={variable.key}><span>{variable.label} {variable.required?"*":""}<small>{variable.origin}</small></span><textarea value={text(get(form.values,variable.key))} onChange={event=>setForm({...form,values:set(form.values,variable.key,event.target.value)})} placeholder={`Completar ${variable.key}`}/></label>)}</div></div>:null}
    {step===3?<div className="builderPanel"><PanelTitle icon={<ShieldCheck/>} eyebrow="CONSISTENCIA" title="Economía, vigencia y propiedad intelectual" text="La modalidad de propiedad intelectual es exclusiva; los montos deben cerrar antes de aprobar."/><div className="builderGrid"><label>Nombre contractual<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Inicio<input type="date" value={form.startDate} onChange={event=>setForm({...form,startDate:event.target.value})}/></label><label>Término<input type="date" value={form.endDate} onChange={event=>setForm({...form,endDate:event.target.value})}/></label><label>Moneda<select value={form.currency} onChange={event=>setForm({...form,currency:event.target.value})}><option>CLP</option><option>UF</option><option>USD</option></select></label><label>Neto<input type="number" min="0" value={form.subtotal} onChange={event=>setForm({...form,subtotal:Number(event.target.value)})}/></label><label>Impuestos<input type="number" min="0" value={form.tax} onChange={event=>setForm({...form,tax:Number(event.target.value)})}/></label><label>Total<input type="number" min="0" value={form.total} onChange={event=>setForm({...form,total:Number(event.target.value)})}/></label><label>Modalidad de propiedad intelectual *<select value={text(get(form.values,"pi.modalidad"))} onChange={event=>setForm({...form,values:set(form.values,"pi.modalidad",event.target.value)})}><option value="A">A · Licencia perpetua</option><option value="B">B · Transferencia patrimonial</option><option value="C">C · Suscripción a plataforma</option></select></label></div></div>:null}
    {step===4?<div className="builderPanel review"><PanelTitle icon={<FileCheck2/>} eyebrow="CONTROL PREVIO" title="Revisión integral" text="Al guardar se crea un borrador. La aprobación, congelación, PDF final y firma ocurren después y quedan auditados."/><div className="reviewGrid"><article><strong>Origen</strong><p>{clients.find(client=>client.id===form.clientId)?.legalName||"Cliente pendiente"}</p><p>{text(context.projects.find(item=>item.id===form.projectId)?.name)||"Proyecto pendiente"}</p><p>{text(quote?.quote_number)||form.independentReason||"Origen comercial pendiente"}</p></article><article><strong>Paquete documental</strong>{selectedTemplates.map(template=><p key={template.code}>{template.code} · {template.name}</p>)}</article><article><strong>Estados separados</strong><p>Contrato: DRAFT</p><p>Firma: NOT_CONFIGURED / pendiente</p><p>Vigencia: NOT_STARTED</p><p>Cumplimiento: NOT_ASSESSED</p><p>Cobranza: NOT_DUE</p></article><article><strong>Validación</strong><p>{variables.length-localErrors.filter(value=>value.startsWith("Completa ")).length}/{variables.length} variables resueltas</p><p>{form.currency} {new Intl.NumberFormat("es-CL").format(form.total)}</p></article></div>{localErrors.length?<div className="validationList"><strong>Falta resolver</strong>{localErrors.map(item=><p key={item}><AlertTriangle/>{item}</p>)}</div>:<div className="validationOk"><Check/>La versión está completa para guardarse como borrador y pasar a revisión.</div>}<div className="legalNotice"><ShieldCheck/><p><strong>No se enviará ni firmará nada ahora.</strong> Después de guardar, Gerencia deberá confirmar revisión legal, congelar el PDF y recién entonces podrá usar un proveedor de firma configurado.</p></div></div>:null}
  </section><footer className="builderFooter"><button disabled={step===0} onClick={()=>setStep(value=>Math.max(0,value-1))}><ChevronLeft/>Anterior</button><span>Paso {step+1} de {steps.length}</span>{step<steps.length-1?<button className="domainPrimary" onClick={()=>setStep(value=>Math.min(steps.length-1,value+1))}>Continuar<ChevronRight/></button>:<button className="domainPrimary" disabled={saving||localErrors.length>0} onClick={()=>void save()}>{saving?"Creando borrador…":"Crear borrador contractual"}</button>}</footer></main>;
}

function PanelTitle({icon,eyebrow,title,text:description}:{icon:React.ReactNode;eyebrow:string;title:string;text:string}){return <header className="panelTitle"><i>{icon}</i><div><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p></div></header>}
