"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Check, ChevronLeft, ChevronRight, FileCheck2, FileText, Layers3, Settings2, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import type { Client } from "@zyteron/contracts";
import { useAccess } from "@/components/access-context";
import { clientsApi } from "@/lib/clients-api";
import { contractsApi,type ContractBuilderContext,type ContractTemplateCatalogItem } from "@/lib/client-domain-api";
import { applyContractDefaults,contractValue,essentialContractFields,friendlyContractLabel,missingEssentialContractFields,resolvedContractVariables,withContractValue,withoutContractNamespaces } from "@/lib/contract-builder-model";

const steps=["Origen","Documentos","Datos esenciales","Condiciones comerciales","Revisión"];
const core=["ZT-PROYECTO-CL","ZT-CONDICIONES-CL"];
const today=new Date().toISOString().slice(0,10);
const text=(value:unknown)=>String(value??"");
const essentialKeys:Set<string>=new Set(essentialContractFields.map(field=>field.key));
const visibleDecisionKeys=new Set(["proyecto.objetivo","pagos.medios","calendario.revision","pi.modalidad","firma.modalidad"]);
const templatePurposes:Record<string,string>={
  "ZT-PROYECTO-CL":"Identifica a las partes y establece las reglas generales del proyecto.",
  "ZT-CONDICIONES-CL":"Fija alcance, precio, calendario, entregables y condiciones particulares.",
  "ZT-NDA-CL":"Añádelo sólo si necesitas un acuerdo de confidencialidad independiente.",
  "ZT-RECURRENTES-CL":"Para hosting, soporte, licencias u otros cobros periódicos.",
  "ZT-DATOS-CL":"Cuando Zyteron tratará datos personales por cuenta del cliente.",
  "ZT-CAMBIO-CL":"Para modificar un contrato ya acordado; normalmente no corresponde al contrato inicial.",
};
const emptyContext=():ContractBuilderContext=>({client:null,company:null,projects:[],quotes:[],contacts:[]});

export function ContractBuilder(){
  const{role}=useAccess(),router=useRouter();
  const[step,setStep]=useState(0),[clients,setClients]=useState<Client[]>([]),[templates,setTemplates]=useState<ContractTemplateCatalogItem[]>([]),[context,setContext]=useState<ContractBuilderContext>(emptyContext()),[selectedContactId,setSelectedContactId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const[form,setForm]=useState({clientId:"",projectId:"",quoteId:"",independentReason:"",name:"Contrato de desarrollo y servicios tecnológicos",contractType:"DESARROLLO",startDate:today,endDate:"",renewalType:"NONE",billingFrequency:"ONE_TIME",currency:"CLP",subtotal:0,tax:0,total:0,templateCodes:core as string[],values:{contrato:{lugar:"Santiago, Chile",fecha:today},empresa:{razon_social:"Zyteron SpA",rut:"78.398.774-0",domicilio:"Santiago, Chile",representante_cargo:"Gerente General"},pi:{modalidad:"A"}} as Record<string,unknown>});

  useEffect(()=>{Promise.all([clientsApi.list(role,new URLSearchParams({pageSize:"100"})),contractsApi.templates(role)]).then(([clientPage,catalog])=>{setClients(clientPage.items);setTemplates(catalog);const url=new URL(window.location.href),projectId=url.searchParams.get("projectId"),clientId=url.searchParams.get("clientId");setForm(value=>({...value,clientId:clientId||value.clientId,projectId:projectId||value.projectId}));}).catch((cause:Error)=>setError(cause.message)).finally(()=>setLoading(false));},[role]);

  useEffect(()=>{if(!form.clientId){setContext(emptyContext());setSelectedContactId("");return;}setError("");contractsApi.context(role,form.clientId).then(data=>{setContext(data);setForm(value=>({...value,projectId:data.projects.some(project=>project.id===value.projectId)?value.projectId:data.projects.length===1?text(data.projects[0]?.id):"",quoteId:data.quotes.some(quote=>quote.id===value.quoteId)?value.quoteId:data.quotes.length===1?text(data.quotes[0]?.id):"",independentReason:data.quotes.length===1?"":value.independentReason}));}).catch((cause:Error)=>setError(cause.message));},[form.clientId,role]);

  useEffect(()=>{if(!context.contacts.length){if(selectedContactId!=="__manual__")setSelectedContactId("");return;}if(selectedContactId==="__manual__")return;const selected=context.contacts.find(item=>item.id===selectedContactId)??context.contacts.find(item=>item.is_primary)??context.contacts[0];if(!selected)return;const id=text(selected.id);if(id!==selectedContactId)setSelectedContactId(id);setForm(current=>{let values=current.values,changed=false;for(const[key,value]of [["cliente.representante_nombre",selected.name],["cliente.representante_cargo",selected.position],["cliente.email_dte",selected.email]] as Array<[string,unknown]>){if(text(contractValue(values,key)).trim()||!text(value).trim())continue;values=withContractValue(values,key,text(value));changed=true;}return changed?{...current,values}:current;});},[context.contacts,selectedContactId]);

  const selectedTemplates=templates.filter(template=>form.templateCodes.includes(template.code));
  const variables=useMemo(()=>[...new Map(selectedTemplates.flatMap(template=>template.variables).map(variable=>[variable.key,variable])).values()],[selectedTemplates]);
  const project=context.projects.find(item=>item.id===form.projectId)??null,quote=context.quotes.find(item=>item.id===form.quoteId)??null,contact=context.contacts.find(item=>item.id===selectedContactId)??null;

  useEffect(()=>{if(!quote)return;const subtotal=Number(quote.net_amount||0),tax=Number(quote.tax_amount||0),total=Number(quote.total_amount||0);setForm(value=>value.currency===text(quote.currency||"CLP")&&value.subtotal===subtotal&&value.tax===tax&&value.total===total?value:{...value,currency:text(quote.currency||"CLP"),subtotal,tax,total});},[quote]);
  useEffect(()=>{setForm(current=>{const values=applyContractDefaults(current.values,variables,{client:context.client,company:context.company,project,quote,contact,currency:current.currency,subtotal:current.subtotal,tax:current.tax,total:current.total,today});return values===current.values?current:{...current,values};});},[variables,context.client,context.company,project,quote,contact,form.currency,form.subtotal,form.tax,form.total]);

  const missingFields=missingEssentialContractFields(form.values);
  const localErrors=[!form.clientId?"Selecciona un cliente.":"",!form.projectId?"Selecciona un proyecto del mismo cliente.":"",!form.quoteId&&!form.independentReason.trim()?"Selecciona una cotización aceptada o justifica el contrato independiente.":"",!form.templateCodes.includes("ZT-PROYECTO-CL")||!form.templateCodes.includes("ZT-CONDICIONES-CL")?"Contrato base y condiciones particulares son obligatorios.":"",Math.abs(form.subtotal+form.tax-form.total)>.01?"Subtotal, impuestos y total no coinciden.":"",...missingFields].filter(Boolean);
  const advancedVariables=variables.filter(variable=>variable.key!=="contrato.numero"&&!essentialKeys.has(variable.key)&&!visibleDecisionKeys.has(variable.key)&&["HUMAN_DECISION","SIGNATURE"].includes(variable.origin));
  const resolved=resolvedContractVariables(form.values,variables);

  const updateValue=(key:string,value:string)=>setForm(current=>({...current,values:withContractValue(current.values,key,value)}));
  const chooseContact=(id:string)=>{setSelectedContactId(id);const item=context.contacts.find(candidate=>candidate.id===id);if(!item){if(id==="__manual__")setForm(current=>({...current,values:withContractValue(withContractValue(current.values,"cliente.representante_nombre",""),"cliente.representante_cargo","")}));return;}setForm(current=>({...current,values:withContractValue(withContractValue(withContractValue(current.values,"cliente.representante_nombre",text(item.name)),"cliente.representante_cargo",text(item.position)),"cliente.email_dte",text(item.email))}));};

  async function save(){setSaving(true);setError("");try{const builderValues=applyContractDefaults(form.values,variables,{client:context.client,company:context.company,project,quote,contact,currency:form.currency,subtotal:form.subtotal,tax:form.tax,total:form.total,today});const created=await contractsApi.create(role,{clientId:form.clientId,projectId:form.projectId,quoteId:form.quoteId||null,independentReason:form.independentReason||null,name:form.name,description:"Contrato generado desde el asistente contractual.",contractType:form.contractType,status:"DRAFT",startDate:form.startDate||null,endDate:form.endDate||null,renewalType:form.renewalType,renewalNoticeDays:30,billingFrequency:form.billingFrequency,currency:form.currency,subtotal:form.subtotal,tax:form.tax,total:form.total,responsibleUserId:null,portalVisible:false,templateCodes:form.templateCodes,builderValues});router.push(`/clients/contracts/${created.id}`);}catch(cause){setError(cause instanceof Error?cause.message:"No fue posible crear el contrato.");}finally{setSaving(false);}}

  if(loading)return <main className="contractBuilder"><div className="domainLoading">Preparando el asistente contractual…</div></main>;
  return <main className="contractBuilder">
    <header className="builderHeader"><div><Link href="/clients/contracts">← Contratos</Link><span>Contractual System · Chile</span><h1>Crear contrato</h1><p>Un flujo breve con datos automáticos y decisiones contractuales claras.</p></div><div className="legalFlag"><ShieldCheck/><span><strong>Revisión legal requerida</strong><small>El borrador no se firma ni envía hasta completar la revisión profesional.</small></span></div></header>
    <nav className="builderSteps">{steps.map((label,index)=><button type="button" className={index===step?"active":index<step?"done":""} onClick={()=>setStep(index)} key={label}><i>{index<step?<Check/>:index+1}</i><span>{label}</span></button>)}</nav>
    {error?<div className="builderAlert"><AlertTriangle/>{error}</div>:null}
    <section className="builderCanvas">
      {step===0?<div className="builderPanel"><PanelTitle icon={<FileText/>} eyebrow="FUENTES CANÓNICAS" title="¿De dónde nace este contrato?" text="Selecciona el cliente. El proyecto y la cotización aceptada se muestran automáticamente y siempre deben pertenecer al mismo cliente."/><div className="builderGrid"><label>Cliente existente *<select value={form.clientId} onChange={event=>{setContext(emptyContext());setSelectedContactId("");setForm(current=>({...current,clientId:event.target.value,projectId:"",quoteId:"",independentReason:"",values:withoutContractNamespaces(current.values,["cliente","proyecto","cotizacion","precio","calendario","pagos","tabla","ot"])}));}}><option value="">Seleccionar cliente</option>{clients.map(client=><option value={client.id} key={client.id}>{client.tradeName||client.legalName}</option>)}</select></label><label>Proyecto del cliente *<select value={form.projectId} onChange={event=>setForm(current=>({...current,projectId:event.target.value,values:withoutContractNamespaces(current.values,["proyecto","calendario","tabla","ot"])}))}><option value="">Seleccionar proyecto</option>{context.projects.map(item=><option value={text(item.id)} key={text(item.id)}>{text(item.project_number)} · {text(item.name)}</option>)}</select></label><label>Cotización aceptada<select value={form.quoteId} onChange={event=>setForm(current=>({...current,quoteId:event.target.value,independentReason:event.target.value?"":current.independentReason,values:withoutContractNamespaces(current.values,["cotizacion","precio","pagos","tabla"])}))}><option value="">Contrato independiente</option>{context.quotes.map(item=><option value={text(item.id)} key={text(item.id)}>{text(item.quote_number)} · versión {String(item.version)}</option>)}</select></label><label>Motivo si no existe cotización<textarea disabled={Boolean(form.quoteId)} value={form.independentReason} onChange={event=>setForm({...form,independentReason:event.target.value})} placeholder="Explica brevemente por qué este contrato no proviene de una cotización aceptada."/></label></div><div className="sourceSnapshot"><strong>Vínculos verificados</strong><span>{context.client?"Cliente cargado":"Falta cliente"}</span><span>{form.projectId?"Proyecto vinculado":"Falta proyecto"}</span><span>{form.quoteId?"Cotización aceptada":"Contrato independiente"}</span></div></div>:null}

      {step===1?<div className="builderPanel"><PanelTitle icon={<Layers3/>} eyebrow="PAQUETE DOCUMENTAL" title="¿Qué documentos corresponden?" text="El contrato y sus condiciones son obligatorios. Activa anexos únicamente cuando realmente apliquen al servicio."/><div className="templatePicker">{templates.map(template=>{const required=core.includes(template.code),checked=form.templateCodes.includes(template.code);return <label className={checked?"selected":""} key={template.code}><input type="checkbox" checked={checked} disabled={required} onChange={()=>setForm({...form,templateCodes:checked?form.templateCodes.filter(code=>code!==template.code):[...form.templateCodes,template.code]})}/><FileCheck2/><span><strong>{template.name}</strong><small>{templatePurposes[template.code]||"Documento contractual sujeto a revisión legal."}</small></span><b>{required?"Incluido":checked?"Añadido":"Opcional"}</b></label>})}</div></div>:null}

      {step===2?<div className="builderPanel contractEssentials"><PanelTitle icon={<UserRound/>} eyebrow="DATOS ESENCIALES" title="Representantes y condiciones principales" text="El sistema ya completó los datos del cliente, proyecto, cotización y montos. Revisa sólo quién firma y las decisiones que sí requieren criterio humano."/>
        <div className="contractProgress"><article><Sparkles/><span><strong>{resolved} de {variables.length}</strong><small>datos preparados</small></span></article><article className={missingFields.length?"attention":"ready"}>{missingFields.length?<AlertTriangle/>:<Check/>}<span><strong>{missingFields.length}</strong><small>{missingFields.length?"datos obligatorios pendientes":"datos esenciales completos"}</small></span></article><article><ShieldCheck/><span><strong>Borrador</strong><small>sin firma ni envío automático</small></span></article></div>
        <div className="contractPartyGrid">
          <section className="contractQuestionCard"><header><i><UserRound/></i><div><span>CLIENTE</span><h3>Quién firmará por el cliente</h3><p>Selecciona un contacto existente para evitar volver a escribir sus datos.</p></div></header><label>Contacto del directorio<select value={selectedContactId||"__manual__"} onChange={event=>chooseContact(event.target.value)}><option value="__manual__">Ingresar representante manualmente</option>{context.contacts.map(item=><option value={text(item.id)} key={text(item.id)}>{text(item.name)}{item.position?` · ${text(item.position)}`:""}</option>)}</select></label>{essentialContractFields.slice(0,4).map(field=><ContractInput field={field} value={text(contractValue(form.values,field.key))} onChange={value=>updateValue(field.key,value)} key={field.key}/>)}</section>
          <section className="contractQuestionCard"><header><i><ShieldCheck/></i><div><span>ZYTERON</span><h3>Quién firmará por Zyteron</h3><p>Estos datos deben coincidir con los poderes que serán revisados antes de firmar.</p></div></header>{essentialContractFields.slice(4).map(field=><ContractInput field={field} value={text(contractValue(form.values,field.key))} onChange={value=>updateValue(field.key,value)} key={field.key}/>)}</section>
        </div>
        <section className="contractDecisionCard"><header><div><span>CONDICIONES PRINCIPALES</span><h3>Qué se acuerda</h3><p>Partimos desde la cotización y el proyecto. Puedes ajustar el texto sin trabajar con códigos internos.</p></div></header><div className="contractDecisionGrid"><label className="wide">Objetivo del proyecto<textarea value={text(contractValue(form.values,"proyecto.objetivo"))} onChange={event=>updateValue("proyecto.objetivo",event.target.value)} placeholder="Resultado que debe conseguir el proyecto"/><small>Se propone desde el alcance del proyecto.</small></label><label>Forma y condiciones de pago<input value={text(contractValue(form.values,"pagos.medios"))} onChange={event=>updateValue("pagos.medios",event.target.value)} placeholder="Ej.: 50% anticipo y 50% contra entrega"/><small>Se propone desde la cotización aceptada.</small></label><label>Plazo para revisar entregas<input value={text(contractValue(form.values,"calendario.revision"))} onChange={event=>updateValue("calendario.revision",event.target.value)} placeholder="Ej.: 5 días hábiles"/><small>Tiempo para aprobar u observar una entrega.</small></label><label>Propiedad intelectual<select value={text(contractValue(form.values,"pi.modalidad"))} onChange={event=>updateValue("pi.modalidad",event.target.value)}><option value="A">Licencia perpetua de uso</option><option value="B">Transferencia de derechos</option><option value="C">Suscripción a plataforma</option></select><small>Elige una sola modalidad.</small></label><label>Firma prevista<select value={text(contractValue(form.values,"firma.modalidad"))} onChange={event=>updateValue("firma.modalidad",event.target.value)}><option value="Firma electrónica conforme a la Ley N.º 19.799, con evidencia verificable y copia íntegra para cada parte.">Firma electrónica</option><option value="Firma presencial en ejemplares íntegros para ambas partes, con verificación de identidad y facultades.">Firma presencial</option></select><small>La firma se solicita sólo después de aprobar el documento.</small></label></div></section>
        <details className="contractAdvanced"><summary><Settings2/><span><strong>Revisar cláusulas propuestas</strong><small>{advancedVariables.length} condiciones preparadas automáticamente · sólo abre esto si necesitas ajustarlas</small></span><ChevronRight/></summary><div className="contractAdvancedGrid">{advancedVariables.map(variable=><label key={variable.key}>{friendlyContractLabel(variable.key)}<textarea rows={2} value={text(contractValue(form.values,variable.key))} onChange={event=>updateValue(variable.key,event.target.value)}/><small>{variable.origin==="SIGNATURE"?"Firma y evidencia":"Condición contractual"}</small></label>)}</div></details>
      </div>:null}

      {step===3?<div className="builderPanel"><PanelTitle icon={<ShieldCheck/>} eyebrow="CONSISTENCIA COMERCIAL" title="Economía y vigencia" text="Los montos vienen de la cotización aceptada. Revísalos antes de crear el borrador; no se emitirá ningún documento tributario."/><div className="builderGrid"><label>Nombre del contrato<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Fecha o inicio previsto<input type="date" value={form.startDate} onChange={event=>setForm({...form,startDate:event.target.value})}/></label><label>Término previsto<input type="date" value={form.endDate} onChange={event=>setForm({...form,endDate:event.target.value})}/></label><label>Moneda<select value={form.currency} onChange={event=>setForm({...form,currency:event.target.value})}><option>CLP</option><option>UF</option><option>USD</option></select></label><label>Neto<input type="number" min="0" value={form.subtotal} onChange={event=>setForm({...form,subtotal:Number(event.target.value)})}/></label><label>Impuestos<input type="number" min="0" value={form.tax} onChange={event=>setForm({...form,tax:Number(event.target.value)})}/></label><label>Total<input type="number" min="0" value={form.total} onChange={event=>setForm({...form,total:Number(event.target.value)})}/></label></div></div>:null}

      {step===4?<div className="builderPanel review"><PanelTitle icon={<FileCheck2/>} eyebrow="CONTROL PREVIO" title="Revisa y crea el borrador" text="Aquí todavía no se envía, firma ni activa nada. El contrato quedará disponible para revisión legal y aprobación interna."/><div className="reviewGrid"><article><strong>Origen verificado</strong><p>{clients.find(client=>client.id===form.clientId)?.legalName||"Cliente pendiente"}</p><p>{text(project?.name)||"Proyecto pendiente"}</p><p>{text(quote?.quote_number)||form.independentReason||"Origen comercial pendiente"}</p></article><article><strong>Documentos incluidos</strong>{selectedTemplates.map(template=><p key={template.code}>{template.name}</p>)}</article><article><strong>Representantes</strong><p>Cliente: {text(contractValue(form.values,"cliente.representante_nombre"))||"Pendiente"}</p><p>Zyteron: {text(contractValue(form.values,"empresa.representante_nombre"))||"Pendiente"}</p><p>Facultades: revisión obligatoria antes de firma</p></article><article><strong>Preparación</strong><p>{resolved}/{variables.length} datos contractuales preparados</p><p>{form.currency} {new Intl.NumberFormat("es-CL").format(form.total)}</p><p>Estado inicial: borrador</p></article></div>{localErrors.length?<div className="validationList"><strong>Antes de crear el borrador</strong>{localErrors.map(item=><p key={item}><AlertTriangle/>{item}</p>)}</div>:<div className="validationOk"><Check/>Los datos esenciales están completos. Puedes crear el borrador para revisión.</div>}<div className="legalNotice"><ShieldCheck/><p><strong>No se enviará ni firmará nada ahora.</strong> Gerencia deberá revisar las cláusulas, verificar las facultades de ambas partes y aprobar la versión antes de solicitar una firma.</p></div></div>:null}
    </section>
    <footer className="builderFooter"><button type="button" disabled={step===0} onClick={()=>setStep(value=>Math.max(0,value-1))}><ChevronLeft/>Anterior</button><span>Paso {step+1} de {steps.length}</span>{step<steps.length-1?<button type="button" className="domainPrimary" onClick={()=>setStep(value=>Math.min(steps.length-1,value+1))}>Continuar<ChevronRight/></button>:<button type="button" className="domainPrimary" disabled={saving||localErrors.length>0} onClick={()=>void save()}>{saving?"Creando borrador…":"Crear borrador contractual"}</button>}</footer>
  </main>;
}

function ContractInput({field,value,onChange}:{field:(typeof essentialContractFields)[number];value:string;onChange:(value:string)=>void}){const long=field.key.endsWith("personeria");return <label>{field.label} *{long?<textarea value={value} onChange={event=>onChange(event.target.value)} placeholder={field.placeholder}/>:<input value={value} onChange={event=>onChange(event.target.value)} placeholder={field.placeholder}/>}<small>{field.help}</small></label>}
function PanelTitle({icon,eyebrow,title,text:description}:{icon:React.ReactNode;eyebrow:string;title:string;text:string}){return <header className="panelTitle"><i>{icon}</i><div><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p></div></header>}
