import { Injectable,NotFoundException } from "@nestjs/common";
import { createHash,randomBytes,randomUUID } from "node:crypto";
import { createServerSupabase,pageBounds } from "../domain/server-supabase.js";

type Row=Record<string,any>;type Filters=Record<string,string|number|boolean|null|undefined>;
const now=()=>new Date().toISOString();const snake=(key:string)=>key.replace(/[A-Z]/g,letter=>`_${letter.toLowerCase()}`);const camel=(key:string)=>key.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase());
const toRow=(value:Row)=>Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined).map(([key,item])=>[snake(key),item]));
const fromRow=<T>(value:Row):T=>Object.fromEntries(Object.entries(value).map(([key,item])=>[camel(key),item])) as T;
@Injectable()
export class DocumentsRepository{
 private readonly supabase=createServerSupabase();private readonly memory=new Map<string,Map<string,Row>>();private readonly files=new Map<string,Buffer>();private sequence=0;
 constructor(){if(!this.supabase){const stamp=now(),allowed=["application/pdf","image/png","image/jpeg","text/plain","text/csv","video/mp4","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"];for(const[index,[code,name,approval,sharing]]of([["GENERAL","Documento general",false,true],["CONTRACT","Contrato / anexo",true,true],["QUOTE","Cotización / propuesta",true,true],["REPORT","Informe",true,true],["EVIDENCE","Evidencia",false,false]] as const).entries()){const id=`d1000000-0000-4000-8000-${String(index+1).padStart(12,"0")}`;this.store("document_types").set(id,{id,code,name,description:null,maxSizeBytes:code==="EVIDENCE"?104857600:52428800,allowedMimeTypes:allowed,requiresApproval:approval,allowsClientSharing:sharing,retentionPolicyId:null,active:true,createdAt:stamp,updatedAt:stamp});}}}
 configured(){return Boolean(this.supabase);}private store(table:string){let item=this.memory.get(table);if(!item){item=new Map();this.memory.set(table,item);}return item;}
 async list<T>(table:string,filters:Filters={},order="created_at",ascending=false):Promise<T[]>{if(!this.supabase){return[...this.store(table).values()].filter(row=>Object.entries(filters).every(([key,value])=>value===undefined||row[key]===value)).sort((a,b)=>String(ascending?a[camel(order)]??"":b[camel(order)]??"").localeCompare(String(ascending?b[camel(order)]??"":a[camel(order)]??""))) as T[];}let query=(this.supabase.from(table) as any).select("*");for(const[key,value]of Object.entries(filters))if(value!==undefined)query=value===null?query.is(snake(key),null):query.eq(snake(key),value);const{data,error}=await query.order(order,{ascending});if(error)throw error;return(data??[]).map((row:Row)=>fromRow<T>(row));}
 async page<T>(q:{page:number;pageSize:number;search?:string;status?:string;classification?:string;typeId?:string;ownerId?:string;clientVisible?:boolean;expiresBefore?:string}){if(!this.supabase){let items=[...this.store("documents").values()];const term=q.search?.toLowerCase();items=items.filter(item=>(!term||[item.title,item.description,item.documentNumber].some(value=>String(value??"").toLowerCase().includes(term)))&&(!q.status||item.status===q.status)&&(!q.classification||item.classification===q.classification)&&(!q.typeId||item.typeId===q.typeId)&&(!q.ownerId||item.ownerId===q.ownerId)&& (q.clientVisible===undefined||item.clientVisible===q.clientVisible)&&(!q.expiresBefore||item.expiresAt&&item.expiresAt<=q.expiresBefore));items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));const start=(q.page-1)*q.pageSize;return{items:items.slice(start,start+q.pageSize) as T[],page:q.page,pageSize:q.pageSize,total:items.length,totalPages:Math.ceil(items.length/q.pageSize)};}const{from,to}=pageBounds(q.page,q.pageSize);let query=(this.supabase.from("documents") as any).select("*",{count:"exact"});if(q.search){const term=q.search.replace(/[,()]/g," ");query=query.or(`title.ilike.%${term}%,description.ilike.%${term}%,document_number.ilike.%${term}%`);}for(const[key,value]of Object.entries({status:q.status,classification:q.classification,typeId:q.typeId,ownerId:q.ownerId,clientVisible:q.clientVisible}))if(value!==undefined)query=query.eq(snake(key),value);if(q.expiresBefore)query=query.lte("expires_at",q.expiresBefore);const{data,error,count}=await query.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map((row:Row)=>fromRow<T>(row)),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
 async get<T>(table:string,id:string):Promise<T|undefined>{if(!this.supabase)return this.store(table).get(id) as T|undefined;const{data,error}=await(this.supabase.from(table) as any).select("*").eq("id",id).maybeSingle();if(error)throw error;return data?fromRow<T>(data as Row):undefined;}
 async create<T extends Row>(table:string,input:T):Promise<T>{const stamp=now(),item={id:randomUUID(),...input,createdAt:input.createdAt??stamp,updatedAt:input.updatedAt??stamp} as T;if(!this.supabase){this.store(table).set(String(item.id),item);return item;}const{data,error}=await(this.supabase.from(table) as any).insert(toRow(item)).select("*").single();if(error)throw error;return fromRow<T>(data as Row);}
 async update<T extends Row>(table:string,id:string,patch:Partial<T>):Promise<T>{if(!this.supabase){const current=this.store(table).get(id);if(!current)throw new NotFoundException("Registro documental no encontrado.");const item={...current,...Object.fromEntries(Object.entries(patch).filter(([,v])=>v!==undefined)),updatedAt:now()} as unknown as T;this.store(table).set(id,item);return item;}const{data,error}=await(this.supabase.from(table) as any).update(toRow({...patch,updatedAt:now()})).eq("id",id).select("*").single();if(error)throw error;return fromRow<T>(data as Row);}
 async remove(table:string,id:string){if(!this.supabase){this.store(table).delete(id);return;}const{error}=await this.supabase.from(table).delete().eq("id",id);if(error)throw error;}
 async nextNumber(){if(!this.supabase)return`DOC-${new Date().getUTCFullYear()}-${String(++this.sequence).padStart(6,"0")}`;const{data,error}=await this.supabase.rpc("next_document_number");if(error)throw error;return String(data);}
 async createVersion(documentId:string,input:Row){if(!this.supabase){const versions=await this.list<Row>("document_versions",{documentId});const number=Math.max(0,...versions.map(item=>Number(item.versionNumber)))+1;return this.create<any>("document_versions",{...input,documentId,versionNumber:number});}const{data,error}=await this.supabase.rpc("create_document_version",{target_document_id:documentId,version_payload:toRow(input)});if(error)throw error;const value=await this.get<any>("document_versions",String(data));if(!value)throw new Error("No fue posible recuperar la versión creada.");return value;}
 async storeFile(documentId:string,versionId:string,filename:string,mimeType:string,bytes:Buffer){const safe=filename.replace(/[^a-zA-Z0-9._-]/g,"-"),path=`${documentId}/${versionId}/${safe}`;if(!this.supabase)this.files.set(path,bytes);else{const{error}=await this.supabase.storage.from("enterprise-documents").upload(path,bytes,{contentType:mimeType,upsert:false});if(error)throw error;}return path;}
 async signedUrl(path:string,expiresIn=300){if(!this.supabase)return this.files.has(path)?`memory://enterprise-documents/${path}`:null;const{data,error}=await this.supabase.storage.from("enterprise-documents").createSignedUrl(path,expiresIn);if(error)throw error;return data.signedUrl;}
 async bytes(path:string){if(!this.supabase)return this.files.get(path)??null;const{data,error}=await this.supabase.storage.from("enterprise-documents").download(path);if(error)throw error;return Buffer.from(await data.arrayBuffer());}
 async hashDuplicates(sha256:string,exceptDocumentId?:string){const items=await this.list<any>("document_versions",{sha256});return items.filter(item=>item.documentId!==exceptDocumentId);}
 async publish(documentId:string|null,eventType:string,actorId:string|null,payload:Row={}){return this.create<any>("document_events",{documentId,eventType,actorId,payload,occurredAt:now()});}
 token(){const raw=randomBytes(32).toString("base64url");return{raw,hash:createHash("sha256").update(raw).digest("hex")};}
 hashToken(raw:string){return createHash("sha256").update(raw).digest("hex");}
 async byToken(hash:string){const items=await this.list<any>("document_share_links",{tokenHash:hash});return items[0]??null;}
 async portalIdentity(userId:string){if(!this.supabase)return null;const{data,error}=await this.supabase.from("client_portal_users").select("client_id,contact_id").eq("auth_user_id",userId).eq("status","ACTIVE").maybeSingle();if(error)throw error;return data?{clientId:String(data.client_id),contactId:String(data.contact_id)}:null;}
}
