import { Injectable,ServiceUnavailableException,UnprocessableEntityException } from "@nestjs/common";
import { createHmac,timingSafeEqual } from "node:crypto";

export interface FileScanResult { status:"CLEAN"|"SUSPICIOUS"|"INFECTED"|"SCAN_FAILED"|"NOT_CONFIGURED"; provider:string; details:string|null; }
export abstract class FileSecurityScanner { abstract scan(input:{bytes:Buffer;filename:string;mimeType:string;sha256:string}):Promise<FileScanResult>; }
@Injectable() export class DeferredFileSecurityScanner implements FileSecurityScanner { async scan(){return{status:"NOT_CONFIGURED" as const,provider:"NOT_CONFIGURED",details:"Antivirus no configurado; el archivo no se declara limpio."};} }

export abstract class DocumentTextExtractor { abstract readonly status:string; abstract extract(input:{bytes:Buffer;mimeType:string}):Promise<string|null>; }
@Injectable() export class DeferredTextExtractor implements DocumentTextExtractor { readonly status="NOT_CONFIGURED";async extract(){return null;} }
export abstract class DocumentOcrProvider { abstract readonly status:string; }
@Injectable() export class DeferredOcrProvider implements DocumentOcrProvider { readonly status="NOT_CONFIGURED"; }
export abstract class DocumentRenderingService { abstract readonly status:string; abstract preview(bodyHtml:string,variables:Record<string,unknown>):Promise<{html:string;watermark:string}>; }
@Injectable() export class SafePreviewRenderer implements DocumentRenderingService { readonly status="PREVIEW_ONLY";async preview(bodyHtml:string,variables:Record<string,unknown>){const escaped=Object.fromEntries(Object.entries(variables).map(([key,value])=>[key,String(value??"").replace(/[<>&"']/g,char=>({"<":"&lt;",">":"&gt;","&":"&amp;","\"":"&quot;","'":"&#39;"}[char]!))]));let html=bodyHtml;for(const[key,value]of Object.entries(escaped))html=html.replaceAll(`{{${key}}}`,value);return{html,watermark:"PREVIEW — NO ES UN DOCUMENTO EMITIDO"};} }
export type SignatureStatus="DRAFT"|"SENT"|"IN_PROGRESS"|"COMPLETED"|"DECLINED"|"CANCELLED"|"EXPIRED"|"FAILED";
export interface SignatureProviderInput { documentId:string;versionId:string;sha256:string;fileName:string;mimeType:string;downloadUrl:string;signers:Array<{name:string;email:string;order:number}>;callbackUrl:string; }
export abstract class EnterpriseSignatureProvider { abstract readonly name:string;abstract readonly configured:boolean;abstract create(input:SignatureProviderInput):Promise<{providerRequestId:string;status:string}>;abstract status(providerRequestId:string):Promise<{status:string;evidence:Record<string,unknown>}>;abstract cancel(providerRequestId:string):Promise<void>;abstract verifyWebhook(headers:Record<string,string|undefined>,rawBody:string):boolean; }
@Injectable() export class DeferredSignatureProvider implements EnterpriseSignatureProvider { readonly name="NOT_CONFIGURED";readonly configured=false;async create():Promise<never>{throw new Error("Proveedor de firma electrónica no configurado.");}async status(){return{status:"NOT_CONFIGURED",evidence:{}};}async cancel(){return;}verifyWebhook(){return false;} }

const statuses=new Set<SignatureStatus>(["DRAFT","SENT","IN_PROGRESS","COMPLETED","DECLINED","CANCELLED","EXPIRED","FAILED"]);
function statusOf(value:unknown):SignatureStatus{const raw=String(value??"").trim().toUpperCase().replace(/[ -]/g,"_");const aliases:Record<string,SignatureStatus>={CREATED:"DRAFT",PENDING:"SENT",DELIVERED:"SENT",OPENED:"IN_PROGRESS",VIEWED:"IN_PROGRESS",SIGNED:"COMPLETED",COMPLETE:"COMPLETED",REJECTED:"DECLINED",CANCELED:"CANCELLED",ERROR:"FAILED"};const status=(aliases[raw]??raw)as SignatureStatus;if(!statuses.has(status))throw new UnprocessableEntityException(`El proveedor devolvió un estado de firma desconocido (${raw||"vacío"}).`);return status;}
function safeEvidence(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))return{};const denied=/token|secret|password|authorization|api.?key|private.?key/i;return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([key])=>!denied.test(key)).slice(0,50).map(([key,item])=>[key,typeof item==="string"?item.slice(0,2000):item]));}

/** Adaptador HTTPS real y agnóstico. Las credenciales viven únicamente en secretos del backend.
 * El proveedor elegido debe implementar el contrato descrito en docs/ELECTRONIC-SIGNATURE.md. */
@Injectable()
export class ExternalElectronicSignatureProvider implements EnterpriseSignatureProvider{
 readonly name=(process.env.ELECTRONIC_SIGNATURE_PROVIDER_NAME?.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,"_").slice(0,40)||"EXTERNAL");
 get configured(){return Boolean(process.env.ELECTRONIC_SIGNATURE_PROVIDER_URL?.trim()&&process.env.ELECTRONIC_SIGNATURE_API_KEY?.trim()&&process.env.ELECTRONIC_SIGNATURE_WEBHOOK_SECRET?.trim()&&process.env.PUBLIC_API_URL?.trim());}
 private config(){const url=process.env.ELECTRONIC_SIGNATURE_PROVIDER_URL?.trim().replace(/\/$/,"");const key=process.env.ELECTRONIC_SIGNATURE_API_KEY?.trim(),webhookSecret=process.env.ELECTRONIC_SIGNATURE_WEBHOOK_SECRET?.trim(),publicApiUrl=process.env.PUBLIC_API_URL?.trim().replace(/\/$/,"");if(!url||!key||!webhookSecret||!publicApiUrl)throw new ServiceUnavailableException("Firma electrónica no configurada: faltan URL, API key, secreto de webhook o PUBLIC_API_URL.");const local=/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(url);if(!url.startsWith("https://")&&!(process.env.NODE_ENV!=="production"&&local))throw new ServiceUnavailableException("El proveedor de firma electrónica debe usar HTTPS.");if(!publicApiUrl.startsWith("https://")&&process.env.NODE_ENV==="production")throw new ServiceUnavailableException("PUBLIC_API_URL debe usar HTTPS en producción.");return{url,key,webhookSecret,publicApiUrl};}
 private async call(method:string,route:string,body?:unknown){const{url,key}=this.config();const response=await fetch(`${url}${route}`,{method,headers:{authorization:`Bearer ${key}`,accept:"application/json",...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(45000)});const data=await response.json().catch(()=>({}))as Record<string,unknown>;if(!response.ok)throw new UnprocessableEntityException(`Proveedor de firma: ${String(data.message??`HTTP ${response.status}`).slice(0,500)}`);return data;}
 async create(input:SignatureProviderInput){const{publicApiUrl}=this.config();const callbackUrl=`${publicApiUrl}/webhooks/signature/${encodeURIComponent(this.name)}`;const data=await this.call("POST","/signature-requests",{externalId:input.documentId,document:{id:input.documentId,versionId:input.versionId,fileName:input.fileName,mimeType:input.mimeType,sha256:input.sha256,downloadUrl:input.downloadUrl},signers:input.signers,callbackUrl});const providerRequestId=String(data.id??data.requestId??"").trim();if(!providerRequestId)throw new UnprocessableEntityException("El proveedor no devolvió el ID de la solicitud de firma.");return{providerRequestId,status:statusOf(data.status??"SENT")};}
 async status(providerRequestId:string){const data=await this.call("GET",`/signature-requests/${encodeURIComponent(providerRequestId)}`);return{status:statusOf(data.status),evidence:safeEvidence(data.evidence??data)};}
 async cancel(providerRequestId:string){await this.call("POST",`/signature-requests/${encodeURIComponent(providerRequestId)}/cancel`,{});}
 verifyWebhook(headers:Record<string,string|undefined>,rawBody:string){const secret=process.env.ELECTRONIC_SIGNATURE_WEBHOOK_SECRET?.trim(),provided=(headers["x-signature"]??headers["x-webhook-signature"]??"").replace(/^sha256=/i,"").trim().toLowerCase();if(!secret||!/^[a-f0-9]{64}$/.test(provided))return false;const expected=createHmac("sha256",secret).update(rawBody).digest("hex");const a=Buffer.from(provided,"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b);}
}
