import { describe,expect,it,beforeEach } from "vitest";
import { BadRequestException,ConflictException,ForbiddenException } from "@nestjs/common";
import { DeferredFileSecurityScanner,DeferredOcrProvider,DeferredSignatureProvider,DeferredTextExtractor,SafePreviewRenderer } from "./documents.providers.js";
import { DocumentsRepository } from "./documents.repository.js";
import { DocumentAccessService,DocumentReadService,DocumentService,DocumentSharingService,DocumentSignatureService,DocumentTemplateService,DocumentWorkflowService,type DocumentActor } from "./documents.service.js";

const user="10000000-0000-4000-8000-000000000001",reviewer="10000000-0000-4000-8000-000000000002",client="10000000-0000-4000-8000-000000000003";
const actor:DocumentActor={userId:user,role:"GERENTE_GENERAL",clientId:null,contactId:null};
const pdf=Buffer.from("%PDF-1.7\nzyteron").toString("base64");
describe("Document Control Center",()=>{
 let repository:DocumentsRepository,documents:DocumentService,reviews:DocumentWorkflowService,sharing:DocumentSharingService,signatures:DocumentSignatureService,templates:DocumentTemplateService,read:DocumentReadService;
 beforeEach(()=>{delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;repository=new DocumentsRepository();const access=new DocumentAccessService(repository),scanner=new DeferredFileSecurityScanner(),extractor=new DeferredTextExtractor(),signature=new DeferredSignatureProvider(),renderer=new SafePreviewRenderer();documents=new DocumentService(repository,access,scanner,extractor);reviews=new DocumentWorkflowService(repository,documents);sharing=new DocumentSharingService(repository,documents,access);signatures=new DocumentSignatureService(repository,documents,signature);templates=new DocumentTemplateService(repository,renderer);read=new DocumentReadService(repository,scanner,signature,renderer,extractor,new DeferredOcrProvider());});
 async function create(classification="INTERNAL"){return documents.create({title:"Contrato marco",description:"Expediente controlado",typeCode:"GENERAL",classification},actor);}
 async function version(id:string,content=pdf){return documents.addVersion(id,{filename:"contrato.pdf",mimeType:"application/pdf",base64:content,changeSummary:"Versión inicial"},actor);}
 it("loads the baseline catalog without fake documents",async()=>{const data=await read.workspace();expect(data.types.length).toBe(5);expect(data.documents).toEqual([]);});
 it("creates a numbered document",async()=>{const item=await create();expect(item.documentNumber).toMatch(/^DOC-/);expect(item.status).toBe("DRAFT");});
 it("rejects an unknown type",async()=>{await expect(documents.create({title:"X",typeCode:"UNKNOWN"},actor)).rejects.toBeInstanceOf(BadRequestException);});
 it("creates flexible links",async()=>{const item=await documents.create({title:"Cliente",typeCode:"GENERAL",links:[{linkType:"CLIENT",linkedId:client}]},actor);const detail=await documents.detail(item.id,actor);expect(detail.links[0]?.linkedId).toBe(client);});
 it("does not duplicate an existing link",async()=>{const item=await create();await documents.link(item.id,{linkType:"CLIENT",linkedId:client},actor);await documents.link(item.id,{linkType:"CLIENT",linkedId:client},actor);expect((await documents.detail(item.id,actor)).links).toHaveLength(1);});
 it("creates immutable sequential versions",async()=>{const item=await create();expect((await version(item.id)).version.versionNumber).toBe(1);expect((await version(item.id)).version.versionNumber).toBe(2);});
 it("records SHA-256 and explicit scanner status",async()=>{const item=await create(),result=await version(item.id);expect(result.version.sha256).toMatch(/^[0-9a-f]{64}$/);expect(result.version.malwareStatus).toBe("NOT_CONFIGURED");});
 it("rejects empty uploads",async()=>{const item=await create();await expect(documents.addVersion(item.id,{filename:"x.pdf",mimeType:"application/pdf",base64:""},actor)).rejects.toBeInstanceOf(BadRequestException);});
 it("rejects MIME spoofing",async()=>{const item=await create();await expect(documents.addVersion(item.id,{filename:"x.pdf",mimeType:"application/pdf",base64:Buffer.from("plain text").toString("base64")},actor)).rejects.toBeInstanceOf(BadRequestException);});
 it("warns on duplicates but does not merge",async()=>{const first=await create(),second=await create();await version(first.id);const result=await version(second.id);expect(result.duplicateWarnings).toHaveLength(1);expect((await read.workspace()).documents).toHaveLength(2);});
 it("verifies the stored hash",async()=>{const item=await create();await version(item.id);expect((await documents.verify(item.id,actor)).matches).toBe(true);});
 it("returns a temporary download descriptor",async()=>{const item=await create();await version(item.id);const result=await documents.download(item.id,actor);expect(result.url).toContain("memory://enterprise-documents");expect(result.expiresIn).toBe(300);});
 it("requests a sequential review",async()=>{const item=await create();await version(item.id);const result=await reviews.request(item.id,{reviewerIds:[reviewer],mode:"SEQUENTIAL"},actor);expect(result[0].status).toBe("PENDING");expect((await documents.get(item.id,actor)).status).toBe("IN_REVIEW");});
 it("only lets the assigned reviewer decide",async()=>{const item=await create();await version(item.id);const[review]=await reviews.request(item.id,{reviewerIds:[reviewer]},actor);await expect(reviews.decide(review.id,"APPROVED",null,{...actor,userId:"10000000-0000-4000-8000-000000000004",role:"QA"})).rejects.toBeInstanceOf(ForbiddenException);});
 it("approves a reviewed version",async()=>{const item=await create();await version(item.id);const[review]=await reviews.request(item.id,{reviewerIds:[reviewer]},actor);await reviews.decide(review.id,"APPROVED",null,{...actor,userId:reviewer,role:"QA"});expect((await documents.get(item.id,actor)).status).toBe("APPROVED");});
 it("requires a reason when requesting changes",async()=>{const item=await create();await version(item.id);const[review]=await reviews.request(item.id,{reviewerIds:[reviewer]},actor);await expect(reviews.decide(review.id,"CHANGES_REQUESTED",null,{...actor,userId:reviewer,role:"QA"})).rejects.toBeInstanceOf(BadRequestException);});
 it("does not fake electronic signatures",async()=>{const item=await create();await version(item.id);await repository.update<any>("documents",item.id,{status:"APPROVED"});await expect(signatures.request(item.id,{signers:[{name:"A",email:"a@b.cl",order:1}]},actor)).rejects.toBeInstanceOf(ConflictException);});
 it("shares only CLIENT or PUBLIC classifications",async()=>{const item=await create();await documents.link(item.id,{linkType:"CLIENT",linkedId:client},actor);await expect(sharing.client(item.id,true,actor)).rejects.toBeInstanceOf(ConflictException);});
 it("shares a client document after client linkage",async()=>{const item=await create("CLIENT");await documents.link(item.id,{linkType:"CLIENT",linkedId:client},actor);expect((await sharing.client(item.id,true,actor)).clientVisible).toBe(true);});
 it("isolates portal clients",async()=>{const item=await create("CLIENT");await documents.link(item.id,{linkType:"CLIENT",linkedId:client},actor);await sharing.client(item.id,true,actor);await expect(documents.get(item.id,{userId:reviewer,role:"PORTAL_CLIENT",clientId:"10000000-0000-4000-8000-000000000009",contactId:null})).rejects.toBeInstanceOf(ForbiddenException);});
 it("creates hashed secure links without exposing the stored token",async()=>{const item=await create("CLIENT"),link=await sharing.link(item.id,{},actor),stored=await repository.get<any>("document_share_links",link.id);expect(link.token).toBeTruthy();expect(stored.tokenHash).not.toBe(link.token);});
 it("archives and restores a document",async()=>{const item=await create();expect((await documents.archive(item.id,actor)).status).toBe("ARCHIVED");expect((await documents.restore(item.id,actor)).status).toBe("DRAFT");});
 it("prevents archive during legal hold",async()=>{const item=await create();await repository.update<any>("documents",item.id,{legalHold:true});await expect(documents.archive(item.id,actor)).rejects.toBeInstanceOf(ConflictException);});
 it("uses controlled trash instead of immediate deletion",async()=>{const item=await create(),trashed=await documents.trash(item.id,actor);expect(trashed.status).toBe("TRASHED");expect(trashed.purgeAfter).toBeTruthy();});
 it("renders a marked preview",async()=>{const item=await templates.create({code:"TEST",name:"Test",bodyHtml:"<h1>{{name}}</h1>"},actor),preview=await templates.preview(item.id,{name:"Zyteron"});expect(preview.html).toContain("Zyteron");expect(preview.watermark).toContain("PREVIEW");});
});
