import { BadRequestException,ConflictException,ForbiddenException,Inject,Injectable,NotFoundException } from "@nestjs/common";
import { createHash,timingSafeEqual } from "node:crypto";
import type { DocumentDetail,DocumentLinkType,DocumentWorkspace,EnterpriseDocument,RelatedDocumentsSnapshot } from "@zyteron/contracts";
import { DocumentsRepository } from "./documents.repository.js";
import { DocumentOcrProvider,DocumentRenderingService,DocumentTextExtractor,EnterpriseSignatureProvider,FileSecurityScanner } from "./documents.providers.js";

export interface DocumentActor{userId:string|null;role:string;clientId?:string|null;contactId?:string|null;}
const now=()=>new Date().toISOString(),uuid=(value:unknown,label:string,nullable=false)=>{if(nullable&&(value===null||value===undefined||value===""))return null;if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new BadRequestException(`${label} debe ser UUID.`);return value;};
const required=(value:unknown,label:string)=>{if(typeof value!=="string"||!value.trim())throw new BadRequestException(`${label} es obligatorio.`);return value.trim();};
const managers=new Set(["GERENTE_GENERAL","JEFE_DESARROLLO","TECH_LEAD"]),internalRoles=new Set(["GERENTE_GENERAL","JEFE_DESARROLLO","TECH_LEAD","QA","SOPORTE_TECNICO","OPERACIONES","PROGRAMADOR","DESARROLLO","FINANZAS","RRHH","JEFE_VENTAS","EJECUTIVA_VENTAS","COMERCIAL"]);
const defaultMimes=["application/pdf","image/png","image/jpeg","text/plain","text/csv","video/mp4","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"];
function detectMime(bytes:Buffer){if(bytes.subarray(0,4).toString("hex")==="25504446")return"application/pdf";if(bytes.subarray(0,8).toString("hex")==="89504e470d0a1a0a")return"image/png";if(bytes.subarray(0,3).toString("hex")==="ffd8ff")return"image/jpeg";if(bytes.subarray(4,8).toString("ascii")==="ftyp")return"video/mp4";if(bytes.subarray(0,2).toString("hex")==="504b")return"application/zip";const sample=bytes.subarray(0,512);if(!sample.includes(0))return"text/plain";return"application/octet-stream";}
function compatible(declared:string,detected:string){return declared===detected||(detected==="application/zip"&&declared.startsWith("application/vnd.openxmlformats-officedocument."))||(detected==="text/plain"&&["text/plain","text/csv"].includes(declared));}

@Injectable()
export class DocumentAccessService{
 constructor(private readonly repository:DocumentsRepository){}
 async assert(document:EnterpriseDocument,actor:DocumentActor,action:"read"|"write"|"share"|"purge"="read"){
  if(!internalRoles.has(actor.role)&&actor.role!=="PORTAL_CLIENT")throw new ForbiddenException("Sin acceso al dominio documental.");
  if(actor.role==="PORTAL_CLIENT"){if(action!=="read"||!document.clientVisible||["INTERNAL","CONFIDENTIAL","RESTRICTED","CRITICAL"].includes(document.classification))throw new ForbiddenException("Documento no visible para el cliente.");const links=await this.repository.list<any>("document_links",{documentId:document.id,linkType:"CLIENT"});if(!actor.clientId||!links.some(link=>link.linkedId===actor.clientId))throw new ForbiddenException("El documento pertenece a otro cliente.");}
  if(action==="purge"&&!managers.has(actor.role))throw new ForbiddenException("Solo Gerencia o jefatura autorizada puede purgar.");
  if(action==="share"&&!["GERENTE_GENERAL","JEFE_DESARROLLO","JEFE_VENTAS","EJECUTIVA_VENTAS","COMERCIAL"].includes(actor.role))throw new ForbiddenException("Sin permiso para compartir documentos.");
 }
}

@Injectable()
export class DocumentService{
 constructor(private readonly repository:DocumentsRepository,private readonly access:DocumentAccessService,@Inject(FileSecurityScanner)private readonly scanner:FileSecurityScanner,@Inject(DocumentTextExtractor)private readonly extractor:DocumentTextExtractor){}
 async list(q:Record<string,string|undefined>,actor:DocumentActor){const page=Math.max(1,Number(q.page)||1),pageSize=Math.min(100,Math.max(1,Number(q.pageSize)||25));if(actor.role==="PORTAL_CLIENT")return this.portal(actor);const result=await this.repository.page<EnterpriseDocument>({page,pageSize,search:q.q||q.search,status:q.status,classification:q.classification,typeId:q.typeId,ownerId:q.ownerId,clientVisible:q.clientVisible===undefined?undefined:q.clientVisible==="true",expiresBefore:q.expiresBefore});if(q.linkType||q.linkedId||q.tag){const links=await this.repository.list<any>("document_links",{});const tags=await this.repository.list<any>("document_tags",{});const ids=new Set(links.filter(link=>(!q.linkType||link.linkType===q.linkType)&&(!q.linkedId||link.linkedId===q.linkedId)).map(link=>link.documentId));result.items=result.items.filter((item:EnterpriseDocument)=>(!q.linkType&&!q.linkedId||ids.has(item.id))&&(!q.tag||tags.some(tag=>tag.documentId===item.id&&tag.tag===q.tag)));result.total=result.items.length;result.totalPages=Math.ceil(result.total/pageSize);}return result;}
 async create(body:any,actor:DocumentActor){if(actor.role==="PORTAL_CLIENT")throw new ForbiddenException();const types=await this.repository.list<any>("document_types",{active:true}),type=types.find(item=>item.id===body.typeId||item.code===body.typeCode);if(!type)throw new BadRequestException("Tipo documental inválido.");const classification=body.classification||"INTERNAL";if(!["PUBLIC","CLIENT","INTERNAL","CONFIDENTIAL","RESTRICTED","CRITICAL"].includes(classification))throw new BadRequestException("Clasificación inválida.");const item=await this.repository.create<any>("documents",{documentNumber:body.numbered===false?null:await this.repository.nextNumber(),title:required(body.title,"Título"),description:body.description?.trim()||null,typeId:type.id,classification,status:"DRAFT",ownerId:uuid(body.ownerId??actor.userId,"Responsable",true),currentVersionId:null,currentVersionNumber:0,clientVisible:false,expiresAt:body.expiresAt||null,retentionPolicyId:uuid(body.retentionPolicyId,"Política de retención",true),legalHold:false,archivedAt:null,trashedAt:null,purgeAfter:null,createdBy:actor.userId});for(const link of body.links??[])await this.link(item.id,link,actor);for(const tag of body.tags??[])if(String(tag).trim())await this.repository.create<any>("document_tags",{documentId:item.id,tag:String(tag).trim().toLowerCase(),createdBy:actor.userId});await this.repository.publish(item.id,"DOCUMENT_CREATED",actor.userId,{classification,typeCode:type.code});return item as EnterpriseDocument;}
 async get(id:string,actor:DocumentActor){const item=await this.repository.get<EnterpriseDocument>("documents",uuid(id,"Documento")!);if(!item)throw new NotFoundException("Documento no encontrado.");await this.access.assert(item,actor);return item;}
 async detail(id:string,actor:DocumentActor):Promise<DocumentDetail>{const document=await this.get(id,actor);const[versions,links,reviews,signatures,relationships,comments,permissions,activity]=await Promise.all([this.repository.list<any>("document_versions",{documentId:id},"version_number",false),this.repository.list<any>("document_links",{documentId:id}),this.repository.list<any>("document_reviews",{documentId:id}),this.repository.list<any>("signature_requests",{documentId:id}),this.repository.list<any>("document_relationships",{documentId:id}),this.repository.list<any>("document_comments",{documentId:id}),this.repository.list<any>("document_permissions",{documentId:id}),this.repository.list<any>("document_events",{documentId:id},"occurred_at",false)]);const duplicateWarnings=[...new Set((await Promise.all(versions.map(v=>this.repository.hashDuplicates(v.sha256,id)))).flat().map(v=>v.documentId))];return{document,versions,links,reviews,signatures,relationships,comments:actor.role==="PORTAL_CLIENT"?comments.filter(c=>c.clientVisible):comments,permissions:actor.role==="PORTAL_CLIENT"?[]:permissions,activity:actor.role==="PORTAL_CLIENT"?activity.filter(e=>e.payload?.clientVisible):activity,duplicateWarnings};}
 async update(id:string,body:any,actor:DocumentActor){const current=await this.get(id,actor);await this.access.assert(current,actor,"write");if(["SIGNED","ARCHIVED","TRASHED"].includes(current.status))throw new ConflictException("El documento firmado, archivado o en papelera no puede editarse.");const patch:any={title:body.title===undefined?undefined:required(body.title,"Título"),description:body.description===undefined?undefined:body.description?.trim()||null,classification:body.classification,ownerId:body.ownerId===undefined?undefined:uuid(body.ownerId,"Responsable",true),expiresAt:body.expiresAt===undefined?undefined:body.expiresAt||null};const item=await this.repository.update<any>("documents",id,patch);await this.repository.publish(id,"DOCUMENT_METADATA_UPDATED",actor.userId,{fields:Object.keys(patch).filter(key=>patch[key]!==undefined)});return item;}
 async addVersion(id:string,body:any,actor:DocumentActor){const document=await this.get(id,actor);await this.access.assert(document,actor,"write");if(["ARCHIVED","TRASHED"].includes(document.status))throw new ConflictException("Restaura el documento antes de versionarlo.");const filename=required(body.filename,"Nombre de archivo"),mimeType=required(body.mimeType,"MIME declarado");if(typeof body.base64!=="string")throw new BadRequestException("Contenido base64 obligatorio.");const bytes=Buffer.from(body.base64,"base64");if(!bytes.length)throw new BadRequestException("El archivo está vacío.");const type=await this.repository.get<any>("document_types",document.typeId),max=Number(type?.maxSizeBytes??50*1024*1024),allowed=type?.allowedMimeTypes?.length?type.allowedMimeTypes:defaultMimes;if(bytes.byteLength>max)throw new BadRequestException(`El archivo supera el máximo de ${Math.round(max/1024/1024)} MB.`);if(!allowed.includes(mimeType))throw new BadRequestException("Tipo MIME no permitido para este tipo documental.");const detected=detectMime(bytes);if(!compatible(mimeType,detected))throw new BadRequestException(`El contenido detectado (${detected}) no coincide con el MIME declarado.`);const sha256=createHash("sha256").update(bytes).digest("hex"),scan=await this.scanner.scan({bytes,filename,mimeType,sha256}),quarantined=["SUSPICIOUS","INFECTED","SCAN_FAILED"].includes(scan.status);const pending=await this.repository.createVersion(id,{filename,storagePath:`pending/${id}`,mimeType,detectedMimeType:detected,sizeBytes:bytes.byteLength,sha256,malwareStatus:scan.status,status:quarantined?"QUARANTINED":"AVAILABLE",changeSummary:body.changeSummary?.trim()||null,lockedAt:null,signedAt:null,createdBy:actor.userId});const path=await this.repository.storeFile(id,pending.id,filename,mimeType,bytes),version=await this.repository.update<any>("document_versions",pending.id,{storagePath:path});if(!quarantined){await this.repository.update<any>("documents",id,{currentVersionId:version.id,currentVersionNumber:version.versionNumber,status:"DRAFT"});if(["text/plain","text/csv"].includes(mimeType)){const extracted=await this.extractor.extract({bytes,mimeType});if(extracted)await this.repository.create<any>("document_search_content",{documentId:id,versionId:version.id,content:extracted});}}await this.repository.publish(id,quarantined?"DOCUMENT_VERSION_QUARANTINED":"DOCUMENT_VERSION_CREATED",actor.userId,{versionId:version.id,versionNumber:version.versionNumber,sha256,malwareStatus:scan.status,scanner:scan.provider});return{version,duplicateWarnings:(await this.repository.hashDuplicates(sha256,id)).map(item=>({documentId:item.documentId,versionId:item.id})),scanner:scan};}
 async download(id:string,actor:DocumentActor){const document=await this.get(id,actor);if(!document.currentVersionId)throw new NotFoundException("El documento no tiene una versión descargable.");const version=await this.repository.get<any>("document_versions",document.currentVersionId);if(!version||version.status==="QUARANTINED")throw new ForbiddenException("La versión está en cuarentena.");const url=await this.repository.signedUrl(version.storagePath,300);await this.repository.create<any>("document_access_events",{documentId:id,versionId:version.id,actorId:actor.userId,actorRole:actor.role,eventType:"DOWNLOAD",classification:document.classification,occurredAt:now()});return{url,expiresIn:300,filename:version.filename,sha256:version.sha256};}
 async verify(id:string,actor:DocumentActor){const document=await this.get(id,actor);if(!document.currentVersionId)throw new NotFoundException("Sin versión para verificar.");const version=await this.repository.get<any>("document_versions",document.currentVersionId),bytes=version?await this.repository.bytes(version.storagePath):null;if(!version||!bytes)throw new NotFoundException("Archivo no disponible.");const actual=createHash("sha256").update(bytes).digest("hex"),expected=Buffer.from(version.sha256),received=Buffer.from(actual),matches=expected.length===received.length&&timingSafeEqual(expected,received);await this.repository.create<any>("document_integrity_checks",{documentId:id,versionId:version.id,expectedSha256:version.sha256,actualSha256:actual,matches,verifiedBy:actor.userId,verifiedAt:now()});return{matches,expectedSha256:version.sha256,actualSha256:actual,verifiedAt:now()};}
 async link(id:string,body:any,actor:DocumentActor){await this.get(id,actor);const linkType=required(body.linkType,"Tipo de vínculo") as DocumentLinkType,linkedId=uuid(body.linkedId,"Entidad vinculada")!;const existing=(await this.repository.list<any>("document_links",{documentId:id,linkType,linkedId}))[0];if(existing)return existing;const item=await this.repository.create<any>("document_links",{documentId:id,linkType,linkedId,label:body.label?.trim()||null,primaryLink:Boolean(body.primaryLink),createdBy:actor.userId});await this.repository.publish(id,"DOCUMENT_LINKED",actor.userId,{linkType,linkedId});return item;}
 async comment(id:string,body:any,actor:DocumentActor){await this.get(id,actor);const item=await this.repository.create<any>("document_comments",{documentId:id,body:required(body.body,"Comentario"),authorId:actor.userId,clientVisible:Boolean(body.clientVisible),mentions:Array.isArray(body.mentions)?body.mentions:[]});await this.repository.publish(id,"DOCUMENT_COMMENT_ADDED",actor.userId,{commentId:item.id,clientVisible:item.clientVisible,mentions:item.mentions});return item;}
 async archive(id:string,actor:DocumentActor){const item=await this.get(id,actor);if(item.legalHold)throw new ConflictException("El documento está bajo legal hold.");const updated=await this.repository.update<any>("documents",id,{status:"ARCHIVED",archivedAt:now()});await this.repository.publish(id,"DOCUMENT_ARCHIVED",actor.userId);return updated;}
 async restore(id:string,actor:DocumentActor){await this.get(id,actor);const updated=await this.repository.update<any>("documents",id,{status:"DRAFT",archivedAt:null,trashedAt:null,purgeAfter:null});await this.repository.publish(id,"DOCUMENT_RESTORED",actor.userId);return updated;}
 async trash(id:string,actor:DocumentActor){const item=await this.get(id,actor);if(item.legalHold)throw new ConflictException("Legal hold impide enviar a papelera.");const purgeAfter=new Date(Date.now()+30*86400000).toISOString(),updated=await this.repository.update<any>("documents",id,{status:"TRASHED",trashedAt:now(),purgeAfter});await this.repository.publish(id,"DOCUMENT_TRASHED",actor.userId,{purgeAfter});return updated;}
 async purge(id:string,actor:DocumentActor){const item=await this.get(id,actor);await this.access.assert(item,actor,"purge");if(item.legalHold||item.status!=="TRASHED"||!item.purgeAfter||item.purgeAfter>now())throw new ConflictException("El documento aún no cumple las condiciones de purga controlada.");await this.repository.publish(id,"DOCUMENT_PURGED",actor.userId,{documentNumber:item.documentNumber});await this.repository.remove("documents",id);return{purged:true,id};}
 async activity(id:string,actor:DocumentActor){await this.get(id,actor);return this.repository.list<any>("document_events",{documentId:id},"occurred_at",false);}
 async portal(actor:DocumentActor){if(!actor.clientId&&actor.userId){const identity=await this.repository.portalIdentity(actor.userId);actor={...actor,clientId:identity?.clientId??null,contactId:identity?.contactId??null};}if(!actor.clientId)throw new ForbiddenException("Identidad de Portal Cliente no vinculada.");const links=await this.repository.list<any>("document_links",{linkType:"CLIENT",linkedId:actor.clientId}),ids=new Set(links.map(item=>item.documentId)),items=(await this.repository.list<EnterpriseDocument>("documents",{clientVisible:true})).filter(item=>ids.has(item.id)&&["PUBLIC","CLIENT"].includes(item.classification)&&!["ARCHIVED","TRASHED"].includes(item.status));return{items,page:1,pageSize:items.length,total:items.length,totalPages:1};}
}

@Injectable()
export class DocumentWorkflowService{
 constructor(private readonly repository:DocumentsRepository,private readonly documents:DocumentService){}
 async request(id:string,body:any,actor:DocumentActor){const document=await this.documents.get(id,actor);if(!document.currentVersionId)throw new ConflictException("Sube una versión antes de solicitar revisión.");const reviewers=Array.isArray(body.reviewerIds)?body.reviewerIds:[];if(!reviewers.length)throw new BadRequestException("Selecciona al menos un revisor del directorio.");const mode=body.mode==="PARALLEL"?"PARALLEL":"SEQUENTIAL",items=[];for(let index=0;index<reviewers.length;index++)items.push(await this.repository.create<any>("document_reviews",{documentId:id,versionId:document.currentVersionId,reviewerId:uuid(reviewers[index],"Revisor")!,sequence:index+1,mode,status:"PENDING",comment:null,decidedAt:null,createdBy:actor.userId}));await this.repository.update<any>("documents",id,{status:"IN_REVIEW"});await this.repository.publish(id,"DOCUMENT_REVIEW_REQUESTED",actor.userId,{reviewIds:items.map(item=>item.id),mode});return items;}
 async decide(reviewId:string,decision:"APPROVED"|"CHANGES_REQUESTED"|"REJECTED",comment:string|null,actor:DocumentActor){const review=await this.repository.get<any>("document_reviews",uuid(reviewId,"Revisión")!);if(!review)throw new NotFoundException("Revisión no encontrada.");if(review.status!=="PENDING")throw new ConflictException("La revisión ya fue resuelta.");if(review.reviewerId!==actor.userId&&!managers.has(actor.role))throw new ForbiddenException("Solo el revisor asignado puede decidir.");if(decision!=="APPROVED"&&!comment?.trim())throw new BadRequestException("El comentario es obligatorio.");const updated=await this.repository.update<any>("document_reviews",reviewId,{status:decision,comment:comment?.trim()||null,decidedAt:now()});const reviews=await this.repository.list<any>("document_reviews",{documentId:review.documentId,versionId:review.versionId});let status="IN_REVIEW";if(decision==="CHANGES_REQUESTED")status="CHANGES_REQUESTED";else if(decision==="REJECTED")status="REJECTED";else if(reviews.every(item=>item.id===reviewId||item.status==="APPROVED"))status="APPROVED";await this.repository.update<any>("documents",review.documentId,{status});await this.repository.publish(review.documentId,`DOCUMENT_REVIEW_${decision}`,actor.userId,{reviewId,comment});return updated;}
}

@Injectable()
export class DocumentSharingService{
 constructor(private readonly repository:DocumentsRepository,private readonly documents:DocumentService,private readonly access:DocumentAccessService){}
 async client(id:string,visible:boolean,actor:DocumentActor){const document=await this.documents.get(id,actor);await this.access.assert(document,actor,"share");if(visible&&!(["PUBLIC","CLIENT"].includes(document.classification)))throw new ConflictException("Solo documentos PUBLIC o CLIENT pueden compartirse con Portal Cliente.");const links=await this.repository.list<any>("document_links",{documentId:id,linkType:"CLIENT"});if(visible&&!links.length)throw new ConflictException("Vincula al menos un cliente antes de compartir.");const updated=await this.repository.update<any>("documents",id,{clientVisible:visible});await this.repository.publish(id,visible?"DOCUMENT_SHARED_WITH_CLIENT":"DOCUMENT_UNSHARED_FROM_CLIENT",actor.userId,{clientVisible:visible});return updated;}
 async link(id:string,body:any,actor:DocumentActor){const document=await this.documents.get(id,actor);await this.access.assert(document,actor,"share");if(["RESTRICTED","CRITICAL"].includes(document.classification))throw new ForbiddenException("La clasificación impide enlaces externos.");const token=this.repository.token(),expiresAt=body.expiresAt||new Date(Date.now()+7*86400000).toISOString(),item=await this.repository.create<any>("document_share_links",{documentId:id,tokenHash:token.hash,expiresAt,maxUses:Math.min(100,Math.max(1,Number(body.maxUses)||10)),useCount:0,passwordHash:null,revokedAt:null,createdBy:actor.userId});await this.repository.publish(id,"DOCUMENT_SHARE_LINK_CREATED",actor.userId,{shareLinkId:item.id,expiresAt});return{...item,token:token.raw,url:`/shared/documents/${token.raw}`};}
 async revoke(id:string,actor:DocumentActor){const item=await this.repository.get<any>("document_share_links",id);if(!item)throw new NotFoundException("Enlace no encontrado.");const document=await this.documents.get(item.documentId,actor);await this.access.assert(document,actor,"share");const updated=await this.repository.update<any>("document_share_links",id,{revokedAt:now()});await this.repository.publish(item.documentId,"DOCUMENT_SHARE_LINK_REVOKED",actor.userId,{shareLinkId:id});return updated;}
 async resolve(raw:string){const item=await this.repository.byToken(this.repository.hashToken(raw));if(!item||item.revokedAt||item.expiresAt<now()||item.useCount>=item.maxUses)throw new NotFoundException("Enlace inválido o vencido.");const document=await this.repository.get<EnterpriseDocument>("documents",item.documentId);if(!document||["RESTRICTED","CRITICAL","TRASHED"].includes(document.classification))throw new NotFoundException("Documento no disponible.");const version=document.currentVersionId?await this.repository.get<any>("document_versions",document.currentVersionId):null;if(!version)throw new NotFoundException("Versión no disponible.");await this.repository.update<any>("document_share_links",item.id,{useCount:item.useCount+1});await this.repository.create<any>("document_access_events",{documentId:document.id,versionId:version.id,actorId:null,actorRole:"SECURE_LINK",eventType:"DOWNLOAD",classification:document.classification,occurredAt:now()});return{document:{id:document.id,title:document.title,classification:document.classification},download:{url:await this.repository.signedUrl(version.storagePath,120),expiresIn:120,filename:version.filename}};}
}

@Injectable()
export class DocumentSignatureService{
 constructor(private readonly repository:DocumentsRepository,private readonly documents:DocumentService,@Inject(EnterpriseSignatureProvider)private readonly provider:EnterpriseSignatureProvider){}
 async request(id:string,body:any,actor:DocumentActor){const document=await this.documents.get(id,actor);if(!this.provider.configured)throw new ConflictException("Proveedor de firma electrónica no configurado.");if(document.status!=="APPROVED"||!document.currentVersionId)throw new ConflictException("Solo una versión aprobada puede enviarse a firma.");const version=await this.repository.get<any>("document_versions",document.currentVersionId),signers=Array.isArray(body.signers)?body.signers:[];if(!signers.length)throw new BadRequestException("Agrega al menos un firmante.");const external=await this.provider.create({documentId:id,versionId:version.id,sha256:version.sha256,signers,callbackUrl:body.callbackUrl||null}),request=await this.repository.create<any>("signature_requests",{documentId:id,versionId:version.id,provider:this.provider.name,providerRequestId:external.providerRequestId,status:external.status,frozenSha256:version.sha256,evidence:{},createdBy:actor.userId});for(const signer of signers)await this.repository.create<any>("signature_signers",{requestId:request.id,name:required(signer.name,"Firmante"),email:required(signer.email,"Email"),signingOrder:Number(signer.order)||1,status:"PENDING"});await this.repository.update<any>("document_versions",version.id,{status:"LOCKED",lockedAt:now()});await this.repository.update<any>("documents",id,{status:"SIGNING"});await this.repository.publish(id,"DOCUMENT_SIGNATURE_REQUESTED",actor.userId,{requestId:request.id,provider:this.provider.name});return request;}
 async list(id:string,actor:DocumentActor){await this.documents.get(id,actor);return this.repository.list<any>("signature_requests",{documentId:id});}
 async status(id:string,actor:DocumentActor){const item=await this.repository.get<any>("signature_requests",id);if(!item)throw new NotFoundException("Solicitud de firma no encontrada.");await this.documents.get(item.documentId,actor);if(!this.provider.configured)return item;const result=await this.provider.status(item.providerRequestId),updated=await this.repository.update<any>("signature_requests",id,{status:result.status,evidence:result.evidence});if(result.status==="COMPLETED"){await this.repository.update<any>("documents",item.documentId,{status:"SIGNED"});await this.repository.update<any>("document_versions",item.versionId,{signedAt:now()});}return updated;}
 async cancel(id:string,actor:DocumentActor){const item=await this.repository.get<any>("signature_requests",id);if(!item)throw new NotFoundException("Solicitud de firma no encontrada.");await this.documents.get(item.documentId,actor);if(this.provider.configured&&item.providerRequestId)await this.provider.cancel(item.providerRequestId);await this.repository.update<any>("documents",item.documentId,{status:"APPROVED"});return this.repository.update<any>("signature_requests",id,{status:"CANCELLED"});}
 async webhook(provider:string,headers:Record<string,string|undefined>,body:any){const raw=JSON.stringify(body);if(provider!==this.provider.name||!this.provider.verifyWebhook(headers,raw))throw new ForbiddenException("Firma de webhook inválida.");const eventId=required(body.eventId,"Event ID"),existing=(await this.repository.list<any>("signature_events",{provider,eventId}))[0];if(existing)return{accepted:true,duplicate:true};await this.repository.create<any>("signature_events",{provider,eventId,providerRequestId:body.requestId||null,eventType:body.type||"UNKNOWN",payload:body,occurredAt:now()});return{accepted:true,duplicate:false};}
}

@Injectable()
export class DocumentTemplateService{
 constructor(private readonly repository:DocumentsRepository,@Inject(DocumentRenderingService)private readonly renderer:DocumentRenderingService){}
 list(){return this.repository.list<any>("document_templates",{active:true},"created_at",false);}async get(id:string){const item=await this.repository.get<any>("document_templates",id);if(!item)throw new NotFoundException("Plantilla no encontrada.");return{...item,versions:await this.repository.list<any>("document_template_versions",{templateId:id},"version",false)};}
 async create(body:any,actor:DocumentActor){return this.repository.create<any>("document_templates",{code:required(body.code,"Código").toUpperCase(),version:1,name:required(body.name,"Nombre"),bodyHtml:required(body.bodyHtml,"Plantilla HTML"),description:body.description?.trim()||null,classification:body.classification||"INTERNAL",active:true,createdBy:actor.userId});}
 async version(id:string,body:any,actor:DocumentActor){const template=await this.get(id),version=Math.max(Number(template.version)||1,...template.versions.map((item:any)=>Number(item.version)))+1,item=await this.repository.create<any>("document_template_versions",{templateId:id,version,bodyHtml:required(body.bodyHtml,"Plantilla HTML"),variables:Array.isArray(body.variables)?body.variables:[],changeSummary:body.changeSummary?.trim()||null,status:"PUBLISHED",createdBy:actor.userId});await this.repository.update<any>("document_templates",id,{version,bodyHtml:item.bodyHtml});return item;}
 async preview(id:string,variables:Record<string,unknown>){const template=await this.get(id);return{...(await this.renderer.preview(template.bodyHtml,variables)),renderer:this.renderer.status};}
}

@Injectable()
export class DocumentReadService{
 constructor(private readonly repository:DocumentsRepository,@Inject(FileSecurityScanner)private readonly scanner:FileSecurityScanner,@Inject(EnterpriseSignatureProvider)private readonly signature:EnterpriseSignatureProvider,@Inject(DocumentRenderingService)private readonly rendering:DocumentRenderingService,@Inject(DocumentTextExtractor)private readonly extraction:DocumentTextExtractor,@Inject(DocumentOcrProvider)private readonly ocr:DocumentOcrProvider){}
 async workspace(actor?:DocumentActor):Promise<DocumentWorkspace>{const[documents,types,reviews,signatures,templates,activity,versions]=await Promise.all([this.repository.list<any>("documents",{}),this.repository.list<any>("document_types",{active:true},"name",true),this.repository.list<any>("document_reviews",{}),this.repository.list<any>("signature_requests",{}),this.repository.list<any>("document_templates",{active:true}),this.repository.list<any>("document_events",{},"occurred_at",false),this.repository.list<any>("document_versions",{})]),today=now(),soon=new Date(Date.now()+30*86400000).toISOString(),active=documents.filter(item=>!item.trashedAt),summary={total:active.length,mine:actor?.userId?active.filter(item=>item.ownerId===actor.userId).length:0,shared:active.filter(item=>item.clientVisible).length,pendingReview:reviews.filter(item=>item.status==="PENDING").length,pendingSignature:signatures.filter(item=>["SENT","IN_PROGRESS"].includes(item.status)).length,expiring:active.filter(item=>item.expiresAt&&item.expiresAt>=today&&item.expiresAt<=soon).length,quarantined:versions.filter(item=>item.status==="QUARANTINED").length,archived:documents.filter(item=>item.status==="ARCHIVED").length,trash:documents.filter(item=>item.status==="TRASHED").length,storageBytes:versions.reduce((sum,item)=>sum+Number(item.sizeBytes||0),0)},attention:any[]=[];for(const item of reviews.filter(r=>r.status==="PENDING").slice(0,20))attention.push({id:item.id,type:"REVIEW",title:"Revisión pendiente",reason:"Una versión espera decisión formal.",severity:"ATTENTION",href:`/documents/${item.documentId}`,dueAt:null});for(const item of versions.filter(v=>v.status==="QUARANTINED").slice(0,20))attention.push({id:item.id,type:"QUARANTINE",title:item.filename,reason:"Archivo aislado por validación de seguridad.",severity:"CRITICAL",href:`/documents/${item.documentId}`,dueAt:null});for(const item of active.filter(d=>d.expiresAt&&d.expiresAt<=soon).slice(0,20))attention.push({id:item.id,type:"EXPIRY",title:item.title,reason:"Documento próximo a vencer.",severity:item.expiresAt<today?"CRITICAL":"AT_RISK",href:`/documents/${item.id}`,dueAt:item.expiresAt});return{summary,attention,documents:documents.slice(0,100),types,reviews:reviews.slice(0,100),signatures:signatures.slice(0,100),templates:templates.slice(0,100),activity:activity.slice(0,100),providers:{malware:this.scanner.constructor.name==="DeferredFileSecurityScanner"?"NOT_CONFIGURED":"CONFIGURED",signature:this.signature.configured?this.signature.name:"NOT_CONFIGURED",rendering:this.rendering.status,textExtraction:this.extraction.status,ocr:this.ocr.status},generatedAt:now()};}
 async related(filter:{clientId?:string;projectId?:string;linkType?:DocumentLinkType;linkedId?:string}):Promise<RelatedDocumentsSnapshot>{const type=filter.clientId?"CLIENT":filter.projectId?"PROJECT":filter.linkType,linkedId=filter.clientId||filter.projectId||filter.linkedId,links=await this.repository.list<any>("document_links",{linkType:type,linkedId}),ids=new Set(links.map(item=>item.documentId)),documents=(await this.repository.list<EnterpriseDocument>("documents",{})).filter(item=>ids.has(item.id)&&item.status!=="TRASHED"),today=now(),soon=new Date(Date.now()+30*86400000).toISOString();return{clientId:filter.clientId,projectId:filter.projectId,linkType:filter.linkType,documents,total:documents.length,expiring:documents.filter(item=>item.expiresAt&&item.expiresAt>=today&&item.expiresAt<=soon).length,pendingReview:documents.filter(item=>item.status==="IN_REVIEW").length,pendingSignature:documents.filter(item=>["READY_FOR_SIGNATURE","SIGNING"].includes(item.status)).length};}
}
