import{Injectable,NotFoundException}from"@nestjs/common";import{randomUUID}from"node:crypto";import type{ClientRenewal,RenewalStatus}from"@zyteron/contracts";import{cleanSearch,createServerSupabase,pageBounds}from"../domain/server-supabase.js";import type{RenewalInput}from"./renewals.dto.js";
@Injectable()export class RenewalsRepository{private readonly supabase=createServerSupabase();private readonly memory=new Map<string,ClientRenewal>();
async list(input:Record<string,string|number|undefined>&{page:number;pageSize:number}){if(!this.supabase)return this.memoryList(input);await this.processDueAlerts();const{from,to}=pageBounds(input.page,input.pageSize);const s=cleanSearch(String(input.search??""));let q=this.supabase.from("client_renewals").select("*,clients!inner(legal_name,trade_name)",{count:"exact"});if(s)q=q.ilike("title",`%${s}%`);if(input.clientId)q=q.eq("client_id",String(input.clientId));if(input.status)q=q.eq("status",String(input.status));if(input.sourceType)q=q.eq("source_type",String(input.sourceType));if(input.from)q=q.gte("renewal_date",String(input.from));if(input.to)q=q.lte("renewal_date",String(input.to));const{data,error,count}=await q.order(String(input.sort||"renewal_date"),{ascending:input.order!=="desc"}).range(from,to);if(error)throw error;const items=(data??[]).map((r)=>this.fromRow(r)),summary=await this.summary();return{items,page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize),summary};}
async get(id:string){if(!this.supabase)return this.memory.get(id);const{data,error}=await this.supabase.from("client_renewals").select("*,clients!inner(legal_name,trade_name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.fromRow(data):undefined;}
async create(i:RenewalInput){const now=new Date().toISOString(),item:ClientRenewal={...i,id:randomUUID(),clientName:null,opportunityId:null,outcome:null,completedAt:null,createdAt:now,updatedAt:now};if(!this.supabase){this.memory.set(item.id,item);return item;}const{data,error}=await this.supabase.from("client_renewals").insert(this.toRow(item)).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;const created=this.fromRow(data);await this.createAlerts(created);return created;}
async update(id:string,p:Partial<RenewalInput>){const current=await this.get(id);if(!current)throw new NotFoundException("Renovación no encontrada.");if(!this.supabase){const next={...current,...p,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}const row=this.patchRow(p);const{data,error}=await this.supabase.from("client_renewals").update(row).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;const item=this.fromRow(data);if(p.renewalDate)await this.createAlerts(item);return item;}
async contact(id:string){return this.status(id,"CONTACTED");}
async status(id:string,status:RenewalStatus,outcome?:string){const current=await this.get(id);if(!current)throw new NotFoundException("Renovación no encontrada.");if(!this.supabase){const next={...current,status,outcome:outcome??current.outcome,completedAt:["NOT_RENEWED","CANCELLED"].includes(status)?new Date().toISOString():current.completedAt,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}const{data,error}=await this.supabase.from("client_renewals").update({status,outcome:outcome??current.outcome,completed_at:["NOT_RENEWED","CANCELLED"].includes(status)?new Date().toISOString():current.completedAt,updated_at:new Date().toISOString()}).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}
async createOpportunity(id:string){const current=await this.get(id);if(!current)throw new NotFoundException("Renovación no encontrada.");if(current.opportunityId)return current;const opportunityId=randomUUID();if(!this.supabase){const next={...current,opportunityId,status:"NEGOTIATING"as const,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}const{error}=await this.supabase.from("client_renewals").update({opportunity_id:opportunityId,status:"NEGOTIATING",updated_at:new Date().toISOString()}).eq("id",id).is("opportunity_id",null);if(error)throw error;await this.supabase.from("business_event_outbox").insert({aggregate_type:"RENEWAL",aggregate_id:id,event_type:"RENEWAL_OPPORTUNITY_REQUESTED",payload:{opportunityId,clientId:current.clientId,renewalId:id,title:current.title,estimatedValue:current.estimatedValue,currency:current.currency}});return this.get(id);}
async renew(id:string,nextDate:string,notes?:string){const current=await this.get(id);if(!current)throw new NotFoundException("Renovación no encontrada.");if(!this.supabase){const next={...current,status:"RENEWED"as const,outcome:notes??null,completedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}const{data,error}=await this.supabase.rpc("complete_client_renewal",{target_renewal_id:id,next_renewal_date:nextDate,result_notes:notes??null});if(error)throw error;return this.get(data.id);}
private async createAlerts(r:ClientRenewal){if(!this.supabase)return;const due=new Date(`${r.renewalDate}T12:00:00Z`);const rows=[90,60,30,15,7,1].map((days)=>({renewal_id:r.id,threshold_days:days,scheduled_for:new Date(due.getTime()-days*86400000).toISOString().slice(0,10)}));await this.supabase.from("renewal_notification_events").upsert(rows,{onConflict:"renewal_id,threshold_days"});}
private async processDueAlerts(){if(!this.supabase)return;const{error}=await this.supabase.rpc("process_client_renewal_notifications");if(error)throw error;}
private async summary(){if(!this.supabase)return this.summaryFrom([...this.memory.values()]);const{data,error}=await this.supabase.from("client_renewals").select("status,renewal_date,estimated_value,currency");if(error)throw error;return this.summaryFrom((data??[]).map((r)=>({status:r.status,renewalDate:r.renewal_date,estimatedValue:r.estimated_value===null?null:Number(r.estimated_value),currency:r.currency})));}
private summaryFrom(all:Array<any>){const now=new Date(),d30=new Date(Date.now()+30*86400000),d90=new Date(Date.now()+90*86400000);return{upcoming:all.filter((i)=>["UPCOMING","CONTACT_REQUIRED"].includes(i.status)).length,contactRequired:all.filter((i)=>i.status==="CONTACT_REQUIRED").length,negotiating:all.filter((i)=>i.status==="NEGOTIATING").length,renewed:all.filter((i)=>i.status==="RENEWED").length,expired:all.filter((i)=>i.status==="EXPIRED"||(i.renewalDate&&new Date(i.renewalDate)<now&&!['RENEWED','NOT_RENEWED','CANCELLED'].includes(i.status))).length,next30Value:all.filter((i)=>i.renewalDate&&new Date(i.renewalDate)>=now&&new Date(i.renewalDate)<=d30).reduce((s,i)=>s+Number(i.estimatedValue||0),0),next90Value:all.filter((i)=>i.renewalDate&&new Date(i.renewalDate)>=now&&new Date(i.renewalDate)<=d90).reduce((s,i)=>s+Number(i.estimatedValue||0),0)};}
private memoryList(input:Record<string,string|number|undefined>&{page:number;pageSize:number}){const s=cleanSearch(String(input.search??""))?.toLowerCase();const all=[...this.memory.values()].filter((i)=>(!s||i.title.toLowerCase().includes(s))&&(!input.status||i.status===input.status)&&(!input.clientId||i.clientId===input.clientId));const start=(input.page-1)*input.pageSize;return{items:all.slice(start,start+input.pageSize),page:input.page,pageSize:input.pageSize,total:all.length,totalPages:Math.ceil(all.length/input.pageSize),summary:this.summaryFrom(all)};}
private fromRow(r:Record<string,any>):ClientRenewal{const c=Array.isArray(r.clients)?r.clients[0]:r.clients;return{id:r.id,clientId:r.client_id,clientName:c?.trade_name||c?.legal_name||null,sourceType:r.source_type,sourceId:r.source_id,title:r.title,renewalDate:r.renewal_date,noticeDate:r.notice_date,assignedTo:r.assigned_to,status:r.status,estimatedValue:r.estimated_value===null?null:Number(r.estimated_value),currency:r.currency,autoRenew:r.auto_renew,notes:r.notes,opportunityId:r.opportunity_id,outcome:r.outcome,completedAt:r.completed_at,createdAt:r.created_at,updatedAt:r.updated_at};}
private toRow(i:ClientRenewal){return{id:i.id,client_id:i.clientId,source_type:i.sourceType,source_id:i.sourceId,title:i.title,renewal_date:i.renewalDate,notice_date:i.noticeDate,assigned_to:i.assignedTo,status:i.status,estimated_value:i.estimatedValue,currency:i.currency,auto_renew:i.autoRenew,notes:i.notes,opportunity_id:i.opportunityId,outcome:i.outcome,completed_at:i.completedAt,created_at:i.createdAt,updated_at:i.updatedAt};}
private patchRow(i:Partial<RenewalInput>){const map:Record<string,string>={clientId:"client_id",sourceType:"source_type",sourceId:"source_id",title:"title",renewalDate:"renewal_date",noticeDate:"notice_date",assignedTo:"assigned_to",status:"status",estimatedValue:"estimated_value",currency:"currency",autoRenew:"auto_renew",notes:"notes"};const row:Record<string,unknown>={updated_at:new Date().toISOString()};for(const[k,v]of Object.entries(i))if(map[k])row[map[k]!]=v;return row;}}
