"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { DevelopmentAssignment, DevelopmentAttentionItem, DevelopmentBug, DevelopmentEvent, DevelopmentRelease, DevelopmentSummary, DevelopmentTeamMember, OperationsProject, ProjectDeployment, ProjectEnvironment, ProjectRepository, PullRequest, QaRun, TechnicalDebtItem, UserDirectoryItem } from "@zyteron/contracts";
import { AlertTriangle, ArrowRight, Boxes, Braces, Bug, Check, CircleDot, CloudCog, Code2, FileCode2, Gauge, GitBranch, GitPullRequest, Plus, RefreshCw, Rocket, ServerCog, ShieldCheck, Users, X } from "lucide-react";
import { useAccess } from "@/components/access-context";
import { usersDirectoryApi } from "@/lib/client-domain-api";
import { formatDate, formatDateTime } from "@/lib/date-time";
import { developmentApi } from "@/lib/development-api";
import { subscribeToDevelopment } from "@/lib/development-realtime";

export type DevelopmentSection="command"|"assignments"|"team"|"workload"|"my-projects"|"repositories"|"pull-requests"|"qa"|"bugs"|"releases"|"environments"|"deployments"|"docs"|"technical-debt";
type ModalKind="repository"|"environment"|"qa"|"bug"|"release"|"debt"|null;
const emptySummary:DevelopmentSummary={unassignedProjects:0,activeProjects:0,availableDevelopers:0,overloadedDevelopers:0,blockedTasks:0,pendingPullRequests:0,pendingQa:0,criticalBugs:0,failedDeployments:0,upcomingReleases:0,productionPending:0,technicalIncidents:0};
const label=(value:string)=>value.replaceAll("_"," ");
const tabs:[DevelopmentSection,string,string][]=[["command","Command","/development"],["assignments","Asignación","/development/assignments"],["team","Equipo","/development/team"],["workload","Capacidad","/development/workload"],["repositories","Repos","/development/repositories"],["pull-requests","PR","/development/pull-requests"],["qa","QA","/development/qa"],["bugs","Bugs","/development/bugs"],["releases","Releases","/development/releases"],["environments","Ambientes","/development/environments"],["deployments","Deploy","/development/deployments"]];
const sectionTitles:Record<DevelopmentSection,string>={command:"Development Operations Center",assignments:"Proyectos por asignar",team:"Equipo técnico",workload:"Team Capacity", "my-projects":"Mis proyectos",repositories:"Repositorios", "pull-requests":"Review Queue",qa:"Quality Assurance Center",bugs:"Bug Operations",releases:"Release Management",environments:"Environment Control",deployments:"Deployment Center",docs:"Documentación técnica","technical-debt":"Deuda técnica"};

export function DevelopmentWorkspace({section="command"}:{section?:DevelopmentSection}){
  const{role}=useAccess();const[summary,setSummary]=useState(emptySummary),[attention,setAttention]=useState<DevelopmentAttentionItem[]>([]),[assignments,setAssignments]=useState<DevelopmentAssignment[]>([]),[team,setTeam]=useState<DevelopmentTeamMember[]>([]),[projects,setProjects]=useState<OperationsProject[]>([]),[repositories,setRepositories]=useState<ProjectRepository[]>([]),[pullRequests,setPullRequests]=useState<PullRequest[]>([]),[qa,setQa]=useState<QaRun[]>([]),[bugs,setBugs]=useState<DevelopmentBug[]>([]),[releases,setReleases]=useState<DevelopmentRelease[]>([]),[environments,setEnvironments]=useState<ProjectEnvironment[]>([]),[deployments,setDeployments]=useState<ProjectDeployment[]>([]),[debt,setDebt]=useState<TechnicalDebtItem[]>([]),[events,setEvents]=useState<DevelopmentEvent[]>([]),[integrations,setIntegrations]=useState<{provider:string;status:string;message:string}[]>([]),[users,setUsers]=useState<UserDirectoryItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[modal,setModal]=useState<ModalKind>(null);
  const refresh=async()=>{setLoading(true);setError("");try{const[s,a,tm,p,r,pr,q,b,rl,e,d,td,ev,ig,u,as]=await Promise.all([developmentApi.summary(role),developmentApi.attention(role),developmentApi.team(role),developmentApi.projects(role),developmentApi.repositories(role),developmentApi.pullRequests(role),developmentApi.qa(role),developmentApi.bugs(role),developmentApi.releases(role),developmentApi.environments(role),developmentApi.deployments(role),developmentApi.debt(role),developmentApi.activity(role),developmentApi.integrations(role),usersDirectoryApi.list(role).catch(()=>[]),["GERENTE_GENERAL","JEFE_DESARROLLO","TECH_LEAD"].includes(role)?developmentApi.assignments(role):Promise.resolve([])]);setSummary(s);setAttention(a);setTeam(tm);setProjects(p.items);setRepositories(r);setPullRequests(pr);setQa(q);setBugs(b);setReleases(rl);setEnvironments(e);setDeployments(d.items);setDebt(td);setEvents(ev);setIntegrations(ig);setUsers(u);setAssignments(as);}catch(cause){setError(cause instanceof Error?cause.message:"No fue posible cargar Desarrollo.");}finally{setLoading(false);}};
  useEffect(()=>{void refresh();return subscribeToDevelopment(()=>void refresh());},[role]);
  const act=async(message:string,action:()=>Promise<unknown>)=>{try{setError("");await action();setNotice(message);setModal(null);await refresh();}catch(cause){setError(cause instanceof Error?cause.message:"La acción no pudo completarse.");}};
  const create=({repositories:"repository",qa:"qa",bugs:"bug",releases:"release",environments:"environment","technical-debt":"debt"} as Partial<Record<DevelopmentSection,ModalKind>>)[section]??null;
  return <main className="devWorkspace">
    <header className="devHeader"><div><span>Desarrollo · Engineering Operations</span><h1>{sectionTitles[section]}</h1><p>{section==="command"?"Prioriza asignación, revisión, calidad y producción con señales técnicas reales.":"Ejecución técnica conectada directamente a Project Core."}</p></div><div><button onClick={()=>void refresh()} aria-label="Actualizar"><RefreshCw size={15}/></button>{create?<button className="devPrimary" onClick={()=>setModal(create)}><Plus size={15}/>Nuevo</button>:null}</div></header>
    <nav className="devTabs" aria-label="Navegación técnica">{tabs.map(([id,text,href])=><Link className={section===id?"active":""} href={href} key={id}>{text}</Link>)}</nav>
    {error?<div className="devAlert error"><AlertTriangle size={16}/>{error}</div>:null}{notice?<div className="devAlert success"><Check size={16}/>{notice}<button onClick={()=>setNotice("")}>×</button></div>:null}
    {loading?<div className="devLoading">Sincronizando ingeniería…</div>:<>
      {section==="command"?<Command summary={summary} attention={attention} events={events} integrations={integrations}/>:null}
      {section==="assignments"?<Assignments items={assignments} users={users} assign={(projectId,userId,userName,projectRole,allocationPercentage)=>void act("Asignación técnica registrada.",()=>developmentApi.assign(role,projectId,{userId,userName,projectRole,allocationPercentage}))}/>:null}
      {section==="team"?<Team items={team}/>:null}
      {section==="workload"?<Workload items={team}/>:null}
      {section==="my-projects"?<Projects items={projects.filter(project=>team.some(member=>member.userId===project.projectLeadId)||role!=="PROGRAMADOR")}/>:null}
      {section==="repositories"?<Repositories items={repositories} integrations={integrations}/>:null}
      {section==="pull-requests"?<PullRequests items={pullRequests} github={integrations.find(i=>i.provider==="GITHUB")}/>:null}
      {section==="qa"?<Qa items={qa} start={id=>void act("QA iniciada.",()=>developmentApi.startQa(role,id))} complete={(id,status)=>void act("QA completada.",()=>developmentApi.completeQa(role,id,{status}))}/>:null}
      {section==="bugs"?<Bugs items={bugs} status={(id,status)=>void act("Bug actualizado.",()=>developmentApi.bugStatus(role,id,status))}/>:null}
      {section==="releases"?<Releases items={releases} ready={id=>void act("Release lista para aprobación.",()=>developmentApi.updateRelease(role,id,{status:"PENDING_APPROVAL"}))} approve={id=>void act("Release aprobada.",()=>developmentApi.approveRelease(role,id))} deploy={id=>void act("Deployment solicitado.",()=>developmentApi.deployRelease(role,id))}/>:null}
      {section==="environments"?<Environments items={environments}/>:null}
      {section==="deployments"?<Deployments items={deployments} render={integrations.find(i=>i.provider==="RENDER")}/>:null}
      {section==="docs"?<TechnicalDocs projects={projects}/>:null}
      {section==="technical-debt"?<Debt items={debt} resolve={id=>void act("Deuda técnica resuelta.",()=>developmentApi.updateDebt(role,id,{status:"RESOLVED"}))}/>:null}
    </>}
    {modal?<CreateModal kind={modal} projects={projects} close={()=>setModal(null)} save={value=>{const projectId=String(value.projectId||"");const action=modal==="repository"?developmentApi.connectRepo(role,projectId,value):modal==="environment"?developmentApi.createEnvironment(role,projectId,value):modal==="qa"?developmentApi.createQa(role,value):modal==="bug"?developmentApi.createBug(role,value):modal==="release"?developmentApi.createRelease(role,value):developmentApi.createDebt(role,value);return act("Registro técnico creado.",()=>action);}}/>:null}
  </main>;
}

function Command({summary:s,attention,events,integrations}:{summary:DevelopmentSummary;attention:DevelopmentAttentionItem[];events:DevelopmentEvent[];integrations:{provider:string;status:string;message:string}[]}){
  const metrics=[ ["Sin asignación",s.unassignedProjects,"/development/assignments",Users],["Proyectos activos",s.activeProjects,"/development/my-projects",Code2],["Disponibles",s.availableDevelopers,"/development/team",Gauge],["Sobrecargados",s.overloadedDevelopers,"/development/workload",AlertTriangle],["Tareas bloqueadas",s.blockedTasks,"/tasks",Boxes],["PR por revisar",s.pendingPullRequests,"/development/pull-requests",GitPullRequest],["QA pendiente",s.pendingQa,"/development/qa",ShieldCheck],["Bugs críticos",s.criticalBugs,"/development/bugs",Bug],["Deploy fallidos",s.failedDeployments,"/development/deployments",CloudCog],["Releases próximas",s.upcomingReleases,"/development/releases",Rocket] ] as const;
  return <><section className="devHero"><div><small>ENGINEERING PULSE</small><h2>{attention.length?`${attention.length} señales requieren atención técnica`:"Flujo técnico estable"}</h2><p>{s.activeProjects} proyectos activos · {s.productionPending} pendientes de producción · {s.technicalIncidents} incidencias de ambiente</p></div><Link href="/development/assignments">Abrir cola <ArrowRight size={16}/></Link><div className="devTerminal"><span>zyteron / engineering</span>{integrations.map(i=><code key={i.provider}><i className={i.status==="CONNECTED"?"online":"offline"}/>{i.provider.toLowerCase()} · {i.status.toLowerCase()}</code>)}</div></section>
    <section className="devMetricRail">{metrics.map(([text,value,href,Icon])=><Link href={href} key={text}><Icon size={16}/><span>{text}</span><strong>{value}</strong></Link>)}</section>
    <section className="devCommandGrid"><article className="attentionQueue"><header><span>Requiere atención técnica</span><b>{attention.length}</b></header>{attention.length?attention.slice(0,9).map(item=><Link href={item.href} key={`${item.type}-${item.id}`}><i className={item.severity.toLowerCase()}/><div><strong>{item.title}</strong><small>{item.reason}</small></div><time>{formatDate(item.occurredAt)}</time></Link>):<Empty title="Sin señales críticas" text="La cola se alimenta de proyectos, tareas, PR, QA, bugs, deployments y ambientes."/>}</article>
      <article className="devActivity"><header><span>Technical activity</span><b>{events.length}</b></header>{events.slice(0,9).map(event=><div key={event.id}><CircleDot size={12}/><span><strong>{label(event.eventType)}</strong><small>{event.aggregateType}</small></span><time>{formatDateTime(event.occurredAt)}</time></div>)}{!events.length?<Empty title="Sin actividad técnica" text="Las acciones del módulo aparecerán aquí sin registros manuales duplicados."/>:null}</article></section></>;
}

function Assignments({items,users,assign}:{items:DevelopmentAssignment[];users:UserDirectoryItem[];assign:(projectId:string,userId:string,userName:string,role:string,allocation:number)=>void}){const[choice,setChoice]=useState<Record<string,string>>({});return <section className="assignmentGrid">{items.map(item=><article key={item.project.id}><header><span>{item.project.projectNumber}</span><b>{item.project.priority}</b></header><h2>{item.project.name}</h2><p>{item.project.clientName||"Cliente vinculado en Project Core"}</p><dl><div><dt>Deadline</dt><dd>{formatDate(item.project.targetDate)}</dd></div><div><dt>Horas</dt><dd>{item.project.estimatedHours??"—"}</dd></div><div><dt>Stack</dt><dd>{item.technologies.map(i=>i.name).join(", ")||"Sin configurar"}</dd></div><div><dt>Riesgo</dt><dd>{label(item.project.health)}</dd></div></dl>{item.recommendation?<div className="recommendation"><strong>Recomendado · {item.recommendation.name}</strong><small>{item.recommendation.reasons.join(" · ")}</small></div>:null}<footer><select value={choice[item.project.id]||""} onChange={e=>setChoice({...choice,[item.project.id]:e.target.value})}><option value="">Seleccionar usuario…</option>{users.filter(u=>["PROGRAMADOR","TECH_LEAD"].includes(u.role||"")).map(u=><option value={u.id} key={u.id}>{u.name} · {label(u.role||"")}</option>)}</select><button disabled={!choice[item.project.id]} onClick={()=>{const selected=users.find(user=>user.id===choice[item.project.id]);assign(item.project.id,choice[item.project.id]!,selected?.name||"Usuario técnico","DEVELOPER",50);}}>Asignar</button></footer></article>)}{!items.length?<Empty title="No hay proyectos pendientes" text="Todos los proyectos activos tienen asignación técnica completa."/>:null}</section>;}

function Team({items}:{items:DevelopmentTeamMember[]}){return <section className="teamGrid">{items.map(person=><article key={person.userId}><header><span>{person.name.split(" ").map(i=>i[0]).join("").slice(0,2)}</span><i className={person.availability.toLowerCase()}/></header><h3>{person.name}</h3><small>{label(person.role||"DESARROLLO")} · {label(person.availability)}</small><div className="teamStats"><p><b>{person.activeProjects}</b>proyectos</p><p><b>{person.openTasks}</b>tareas</p><p><b>{person.blockedTasks}</b>bloqueos</p></div><footer><span>{person.allocation}% allocation</span><div><i style={{width:`${person.allocation}%`}}/></div><small>Próximo deadline {formatDate(person.nextDeadline)}</small></footer></article>)}{!items.length?<Empty title="Sin asignaciones de equipo" text="El directorio se construye desde project_members; no existe una tabla paralela de programadores."/>:null}</section>;}

function Workload({items}:{items:DevelopmentTeamMember[]}){return <section className="capacityMatrix"><header><span>Persona</span><span>Capacidad</span><span>Planificadas</span><span>Proyectos</span><span>Deadline</span></header>{items.map(item=><div key={item.userId}><strong>{item.name}<small>{label(item.availability)}</small></strong><span><i><b style={{width:`${item.allocation}%`}}/></i>{item.allocation}%</span><span>{item.plannedHours} h</span><span>{item.activeProjects}</span><time>{formatDate(item.nextDeadline)}</time></div>)}{!items.length?<Empty title="Sin capacidad asignada" text="La vista aparecerá cuando Project Core tenga miembros y allocation real."/>:null}</section>;}
function Projects({items}:{items:OperationsProject[]}){return <section className="devProjectGrid">{items.map(item=><Link href={`/projects/${item.id}`} key={item.id}><small>{item.projectNumber}</small><h3>{item.name}</h3><p>{item.clientName||"Proyecto interno"}</p><div><span>{label(item.status)}</span><b>{item.progress}%</b></div><footer>{formatDate(item.targetDate)}</footer></Link>)}{!items.length?<Empty title="Sin proyectos autorizados" text="Solo se muestran proyectos asignados o visibles para tu rol."/>:null}</section>;}
function Repositories({items,integrations}:{items:ProjectRepository[];integrations:{provider:string;status:string;message:string}[]}){const github=integrations.find(i=>i.provider==="GITHUB");return <><div className={`providerBanner ${github?.status==="CONNECTED"?"connected":""}`}><GitBranch size={17}/><div><strong>{github?.message||"GitHub no configurado"}</strong><small>Las credenciales viven solo en backend; nunca se exponen en esta pantalla.</small></div></div><section className="repoGrid">{items.map(repo=><article key={repo.id}><header><Braces size={18}/><span>{repo.visibility}</span></header><small>{repo.projectName||"Proyecto"}</small><h3>{repo.repositoryOwner}/{repo.repositoryName}</h3><p><GitBranch size={12}/>{repo.defaultBranch}</p><footer><span className={repo.integrationStatus.toLowerCase()}>{label(repo.integrationStatus)}</span><a href={repo.repositoryUrl} target="_blank" rel="noreferrer">Abrir proveedor</a></footer></article>)}{!items.length?<Empty title="Sin repositorios conectados" text="Conecta un repositorio autorizado; no se inventarán branches, commits ni PR."/>:null}</section></>;}
function PullRequests({items,github}:{items:PullRequest[];github?:{status:string;message:string}}){return <section className="reviewQueue"><header><span>Proyecto / PR</span><span>Checks</span><span>Reviewers</span><span>Edad</span><span>Estado</span></header>{items.map(pr=><a href={pr.providerUrl||"#"} target={pr.providerUrl?"_blank":undefined} rel="noreferrer" key={pr.id}><strong>#{pr.number} · {pr.title}<small>{pr.projectName} · {pr.sourceBranch} → {pr.targetBranch}</small></strong><b className={pr.checksStatus.toLowerCase()}>{pr.checksStatus}</b><span>{pr.reviewers.join(", ")||"Sin reviewer"}</span><time>{formatDate(pr.openedAt)}</time><em>{label(pr.status)}</em></a>)}{!items.length?<Empty title="No existen PR esperando revisión" text={github?.status==="CONNECTED"?"La cola está al día.":"GitHub no configurado; no se muestran PR ficticias."}/>:null}</section>;}
function Qa({items,start,complete}:{items:QaRun[];start:(id:string)=>void;complete:(id:string,status:string)=>void}){const columns=["PLANNED","IN_PROGRESS","PASSED","FAILED","BLOCKED"] as const;return <section className="qaMatrix">{columns.map(status=><article key={status}><header><span>{label(status)}</span><b>{items.filter(i=>i.status===status).length}</b></header>{items.filter(i=>i.status===status).map(run=><div key={run.id}><small>{run.projectName||"Proyecto"}</small><h3>{run.name}</h3><p>{formatDateTime(run.startedAt||run.createdAt)}</p><footer>{status==="PLANNED"?<button onClick={()=>start(run.id)}>Iniciar</button>:null}{status==="IN_PROGRESS"?<><button onClick={()=>complete(run.id,"PASSED")}>Aprobar</button><button className="danger" onClick={()=>complete(run.id,"FAILED")}>Fallar</button></>:null}</footer></div>)}</article>)}{!items.length?<Empty title="No se han ejecutado pruebas QA" text="Crea una ejecución y casos de prueba vinculados al proyecto y ambiente correctos."/>:null}</section>;}
function Bugs({items,status}:{items:DevelopmentBug[];status:(id:string,status:string)=>void}){const groups=["BLOCKER","CRITICAL","HIGH","MEDIUM","LOW"] as const;return <section className="bugBoard">{groups.map(severity=><article key={severity}><header><span>{severity}</span><b>{items.filter(i=>i.severity===severity&&!['CLOSED','RESOLVED'].includes(i.status)).length}</b></header>{items.filter(i=>i.severity===severity).map(bug=><div key={bug.id}><small>{bug.projectName||"Proyecto"} · {label(bug.status)}</small><h3>{bug.title}</h3><p>{bug.description}</p><footer><span>{formatDate(bug.detectedAt)}</span>{!['RESOLVED','CLOSED'].includes(bug.status)?<button onClick={()=>status(bug.id,"RESOLVED")}>Resolver</button>:<button onClick={()=>status(bug.id,"REOPENED")}>Reabrir</button>}</footer></div>)}</article>)}{!items.length?<Empty title="No existen bugs abiertos" text="Los bugs se registran con severidad y prioridad separadas; no se generan datos ficticios."/>:null}</section>;}
function Releases({items,ready,approve,deploy}:{items:DevelopmentRelease[];ready:(id:string)=>void;approve:(id:string)=>void;deploy:(id:string)=>void}){return <section className="releaseTimeline">{items.map(item=><article key={item.id}><i className={item.status.toLowerCase()}/><div><small>{item.projectName||"Proyecto"} · {item.targetEnvironment}</small><h3>{item.version} · {item.name}</h3><p>{item.releaseNotes||"Release notes pendientes de revisión."}</p></div><time>{formatDateTime(item.plannedAt)}</time><span>{label(item.status)}</span><footer>{["DRAFT","PLANNED"].includes(item.status)?<button onClick={()=>ready(item.id)}>Solicitar aprobación</button>:null}{item.status==="PENDING_APPROVAL"?<button onClick={()=>approve(item.id)}>Aprobar</button>:null}{item.status==="READY"?<button onClick={()=>deploy(item.id)}>Desplegar</button>:null}</footer></article>)}{!items.length?<Empty title="Sin releases planificadas" text="Crea una release revisable a partir de cambios reales del proyecto."/>:null}</section>;}
function Environments({items}:{items:ProjectEnvironment[]}){return <section className="environmentRack">{items.map(item=><article key={item.id}><header><ServerCog size={18}/><i className={item.status.toLowerCase()}/></header><small>{item.projectName||"Proyecto"}</small><h3>{item.name}</h3><p>{item.type} · {label(item.status)}</p><footer>{item.url?<a href={item.url} target="_blank" rel="noreferrer">Abrir ambiente</a>:<span>URL no configurada</span>}<b>{item.deploymentProvider||"Manual"}</b></footer></article>)}{!items.length?<Empty title="Sin ambientes configurados" text="Registra metadata técnica sin almacenar secretos."/>:null}</section>;}
function Deployments({items,render}:{items:ProjectDeployment[];render?:{status:string;message:string}}){return <><div className="providerBanner"><CloudCog size={17}/><div><strong>{render?.message||"Proveedor de despliegue no configurado"}</strong><small>Los registros manuales permanecen identificados y nunca simulan un deploy exitoso.</small></div></div><section className="deploymentLanes">{["QUEUED","IN_PROGRESS","SUCCESS","FAILED"].map(status=><article key={status}><header><span>{label(status)}</span><b>{items.filter(i=>(status==="FAILED"?["FAILED","BUILD_FAILED","DEPLOY_FAILED","HEALTH_CHECK_FAILED"].includes(i.status):i.status===status)).length}</b></header>{items.filter(i=>(status==="FAILED"?["FAILED","BUILD_FAILED","DEPLOY_FAILED","HEALTH_CHECK_FAILED"].includes(i.status):i.status===status)).map(item=><div key={item.id}><small>{item.projectName||"Proyecto"}</small><h3>{item.version}</h3><p>{item.environment} · {item.commitSha?.slice(0,8)||"Sin commit"}</p><footer>{label(item.recordType)}<time>{formatDateTime(item.createdAt)}</time></footer></div>)}</article>)}{!items.length?<Empty title="No existen deployments registrados" text="Conecta Render o registra un deployment manual claramente identificado."/>:null}</section></>;}
function TechnicalDocs({projects}:{projects:OperationsProject[]}){return <section className="docsLibrary"><header><FileCode2 size={22}/><div><h2>Technical knowledge base</h2><p>Los documentos se administran en Documents y se vinculan por project_id; aquí no se duplica el archivo.</p></div><Link href="/documents/projects">Abrir Documents <ArrowRight size={14}/></Link></header><div>{projects.map(project=><article key={project.id}><small>{project.projectNumber}</small><h3>{project.name}</h3><p>Overview · Stack · Setup · Environments · Deployment · Known Issues</p><Link href={`/projects/${project.id}`}>Abrir Project 360</Link></article>)}{!projects.length?<Empty title="Sin proyectos para documentar" text="La biblioteca técnica se activa con Project Core."/>:null}</div></section>;}
function Debt({items,resolve}:{items:TechnicalDebtItem[];resolve:(id:string)=>void}){return <section className="debtLedger"><header><span>Proyecto / ítem</span><span>Impacto</span><span>Esfuerzo</span><span>Objetivo</span><span>Estado</span></header>{items.map(item=><div key={item.id}><strong>{item.title}<small>{item.projectName||"Proyecto"}</small></strong><span className={item.severity.toLowerCase()}>{item.severity}</span><span>{item.estimatedEffort??"—"} h</span><time>{formatDate(item.targetDate)}</time><em>{label(item.status)}</em>{item.status!=="RESOLVED"?<button onClick={()=>resolve(item.id)}>Resolver</button>:null}</div>)}{!items.length?<Empty title="Sin deuda técnica registrada" text="La deuda se mantiene separada de bugs y tareas."/>:null}</section>;}

function CreateModal({kind,projects,close,save}:{kind:Exclude<ModalKind,null>;projects:OperationsProject[];close:()=>void;save:(value:Record<string,unknown>)=>Promise<void>}){const[busy,setBusy]=useState(false);const fields=useMemo<Array<[string,string]>>(()=>({repository:[["repositoryOwner","Owner"],["repositoryName","Repositorio"],["repositoryUrl","URL"],["defaultBranch","Branch principal"]],environment:[["name","Nombre"],["url","URL opcional"],["type","Tipo: DEVELOPMENT/STAGING/PRODUCTION"]],qa:[["name","Nombre QA"],["assignedTo","UUID responsable opcional"]],bug:[["title","Título"],["description","Descripción"],["severity","Severidad: LOW/MEDIUM/HIGH/CRITICAL/BLOCKER"]],release:[["version","Versión"],["name","Nombre"],["targetEnvironment","Ambiente destino"],["releaseNotes","Release notes"]],debt:[["title","Título"],["description","Descripción"],["severity","Severidad"],["estimatedEffort","Horas estimadas"]]} satisfies Record<Exclude<ModalKind,null>,Array<[string,string]>>)[kind]??[],[kind]);return <div className="devModal"><div><button className="devModalClose" onClick={close}><X size={17}/></button><small>Engineering record</small><h2>Nuevo {kind}</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);const value=Object.fromEntries(new FormData(e.currentTarget).entries());await save(value);setBusy(false);}}><label>Proyecto<select name="projectId" required><option value="">Seleccionar…</option>{projects.map(p=><option value={p.id} key={p.id}>{p.projectNumber} · {p.name}</option>)}</select></label>{fields.map(([name,text])=><label key={name} className={["description","releaseNotes"].includes(name)?"wide":""}>{text}{["description","releaseNotes"].includes(name)?<textarea name={name} required={name==="description"}/>:<input name={name} required={["repositoryOwner","repositoryName","repositoryUrl","name","title","version"].includes(name)}/>}</label>)}<p className="devFormNote">Los IDs, estados y eventos se validan nuevamente en backend.</p><footer><button type="button" onClick={close}>Cancelar</button><button className="devPrimary" disabled={busy}>{busy?"Guardando…":"Guardar"}</button></footer></form></div></div>;}
function Empty({title,text}:{title:string;text:string}){return <div className="devEmpty"><i/><strong>{title}</strong><p>{text}</p></div>;}
