"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { DevelopmentProjectSnapshot } from "@zyteron/contracts";
import { AlertTriangle, ArrowLeft, Bug, GitPullRequest, GitBranch, Rocket, ServerCog, ShieldCheck } from "lucide-react";
import { useAccess } from "@/components/access-context";
import { developmentApi } from "@/lib/development-api";
import { formatDateTime } from "@/lib/date-time";
const label=(value:string)=>value.replaceAll("_"," ");
export function DevelopmentProjectView({projectId}:{projectId:string}){const{role}=useAccess();const[data,setData]=useState<DevelopmentProjectSnapshot>(),[error,setError]=useState("");useEffect(()=>{void developmentApi.snapshot(role,projectId).then(setData).catch(c=>setError(c instanceof Error?c.message:"No fue posible cargar Desarrollo."));},[projectId,role]);if(error)return <main className="devWorkspace"><div className="devAlert error"><AlertTriangle size={16}/>{error}</div></main>;if(!data)return <main className="devWorkspace"><div className="devLoading">Sincronizando vista técnica…</div></main>;return <main className="devWorkspace"><header className="devHeader"><div><span>{data.project.projectNumber} · Project 360 / Desarrollo</span><h1>{data.project.name}</h1><p>Stack, repositorios, QA, bugs, releases y producción desde el mismo proyecto.</p></div><Link href={`/projects/${projectId}`} className="devPrimary"><ArrowLeft size={14}/>Volver al proyecto</Link></header><section className="devHero"><div><small>PROJECT TECH HEALTH</small><h2>{data.techHealth}</h2><p>{data.healthReasons.join(" · ")}</p></div><div/><div className="devTerminal"><code>stack · {data.technologies.map(i=>i.name).join(" + ")||"sin configurar"}</code><code>repos · {data.repositories.length}</code><code>team · {data.members.length}</code></div></section><section className="project360Grid"><article><header><GitBranch size={17}/><span>Repositorio</span><b>{data.repositories.length}</b></header>{data.repositories.map(i=><p key={i.id}><span>{i.repositoryOwner}/{i.repositoryName}</span><small>{i.defaultBranch}</small></p>)}</article><article><header><ServerCog size={17}/><span>Ambientes</span><b>{data.environments.length}</b></header>{data.environments.map(i=><p key={i.id}><span>{i.name}</span><small>{label(i.status)}</small></p>)}</article><article><header><GitPullRequest size={17}/><span>PR abiertas</span><b>{data.pullRequests.filter(i=>!["MERGED","CLOSED"].includes(i.status)).length}</b></header>{data.pullRequests.slice(0,4).map(i=><p key={i.id}><span>#{i.number} {i.title}</span><small>{label(i.status)}</small></p>)}</article><article><header><ShieldCheck size={17}/><span>QA</span><b>{data.qaRuns.length}</b></header>{data.qaRuns.slice(0,4).map(i=><p key={i.id}><span>{i.name}</span><small>{label(i.status)}</small></p>)}</article><article><header><Bug size={17}/><span>Bugs</span><b>{data.bugs.length}</b></header>{data.bugs.slice(0,4).map(i=><p key={i.id}><span>{i.title}</span><small>{i.severity}</small></p>)}</article><article><header><Rocket size={17}/><span>Última release</span></header>{data.releases.slice(0,3).map(i=><p key={i.id}><span>{i.version}</span><small>{label(i.status)}</small></p>)}</article><article><header><Rocket size={17}/><span>Último deployment</span></header>{data.deployments.slice(0,3).map(i=><p key={i.id}><span>{i.environment} · {i.version}</span><small>{formatDateTime(i.completedAt||i.createdAt)}</small></p>)}</article></section></main>;}
