import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, Optional } from "@nestjs/common";
import { createHash, randomUUID } from "node:crypto";
import type { AuditCheckResult, AuditEvidence, AuditFinding, AuditPlan, AuditReport, AuditRetest, AuditRun, AuditSummary, AuditTemplate, AuditTemplateCheck, AuditTemplateVersion, AuditWorkspace } from "@zyteron/contracts";
import { OperationsService, type OperationsActor } from "../operations/operations.service.js";
import { QualityService } from "../development/development.service.js";
import { AuditsRepository, type AuditPage } from "./audits.repository.js";
import { AuditAutomationProvider, AuditReportRenderer } from "./audits.providers.js";
import { DocumentService } from "../documents/documents.service.js";

const managers=new Set(["GERENTE_GENERAL","JEFE_DESARROLLO","TECH_LEAD"]);
const finalCheckStatuses=new Set(["PASS","PASS_WITH_OBSERVATION","FAIL","NOT_APPLICABLE","BLOCKED"]);
const activeFindingStatuses=new Set(["OPEN","ACKNOWLEDGED","ASSIGNED","IN_REMEDIATION","READY_FOR_RETEST","RETEST_FAILED"]);
const required=(value:unknown,label:string)=>{if(typeof value!=="string"||!value.trim())throw new BadRequestException(`${label} obligatorio.`);return value.trim();};
const uuid=(value:unknown,label:string,optional=false)=>{if((value===null||value===undefined||value==="")&&optional)return null;if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new BadRequestException(`${label} inválido.`);return value;};
const date=(value:unknown,label:string,optional=false)=>{if((value===null||value===undefined||value==="")&&optional)return null;if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}/.test(value)||Number.isNaN(Date.parse(value)))throw new BadRequestException(`${label} inválida.`);return value;};
const now=()=>new Date().toISOString();
const pageInput=(q:Record<string,string|undefined>):AuditPage=>({page:Math.max(1,Number(q.page)||1),pageSize:Math.min(100,Math.max(1,Number(q.pageSize)||25)),search:q.search?.trim(),status:q.status,clientId:q.clientId,projectId:q.projectId,responsibleUserId:q.responsibleUserId,auditType:q.auditType,severity:q.severity,overdue:q.overdue==="true"});
export { pageInput as auditPage };

const addFrequency=(source:string,frequency:AuditPlan["frequency"],customDays:number|null)=>{const value=new Date(source);const days=frequency==="WEEKLY"?7:frequency==="MONTHLY"?30:frequency==="QUARTERLY"?90:frequency==="SEMIANNUAL"?182:frequency==="ANNUAL"?365:frequency==="CUSTOM"?customDays??0:0;if(!days)return null;value.setUTCDate(value.getUTCDate()+days);return value.toISOString();};

@Injectable()
export class AuditCatalogService {
  constructor(private readonly repository:AuditsRepository){}
  async ensureBaseline(){let templates=await this.repository.list<AuditTemplate>("audit_templates",{active:true});if(templates.length)return templates;
    const template=await this.repository.create<any>("audit_templates",{code:"WEB-BASE",name:"Revisión web integral",auditType:"WEB_GENERAL",description:"Base segura para disponibilidad, HTTPS, cabeceras, SEO y operación.",active:true,currentVersion:1,createdBy:null});
    const version=await this.repository.create<any>("audit_template_versions",{templateId:template.id,version:1,status:"DRAFT",changeSummary:"Versión inicial controlada",publishedAt:null,publishedBy:null});
    const definitions=[{code:"SECURITY",title:"Seguridad defensiva",weight:35,checks:[["HTTPS","HTTPS activo","AUTOMATED",15,"HIGH","SSL"],["HEADERS","Cabeceras defensivas","AUTOMATED",20,"MEDIUM","SECURITY_HEADERS"]]},{code:"PERFORMANCE",title:"Disponibilidad y respuesta",weight:35,checks:[["HTTP","Disponibilidad HTTP","AUTOMATED",20,"HIGH","HTTP_AVAILABILITY"],["LATENCY","Tiempo de respuesta","AUTOMATED",15,"MEDIUM","RESPONSE_TIME"]]},{code:"QUALITY",title:"Calidad funcional",weight:30,checks:[["FORMS","Formularios y validaciones","MANUAL",15,"HIGH",null],["BACKUP","Backup reciente y restauración verificada","MANUAL",15,"HIGH",null]]}];
    for(let s=0;s<definitions.length;s++){const def=definitions[s]!;const section=await this.repository.create<any>("audit_template_sections",{templateVersionId:version.id,code:def.code,title:def.title,description:null,weight:def.weight,sortOrder:s});for(let c=0;c<def.checks.length;c++){const check=def.checks[c]!;await this.repository.create<any>("audit_template_checks",{templateVersionId:version.id,sectionId:section.id,code:check[0],title:check[1],description:null,checkType:check[2],required:true,weight:check[3],severityOnFailure:check[4],instructions:null,automationKey:check[5],autoCreateFinding:true,evidenceRequired:check[2]==="MANUAL",sortOrder:c});}}
    await this.repository.update<any>("audit_template_versions",version.id,{status:"PUBLISHED",publishedAt:now()});
    templates=[template];return templates;
  }
  templates(){return this.ensureBaseline();}
  async template(id:string){const item=await this.repository.get<AuditTemplate>("audit_templates",id);if(!item)throw new NotFoundException("Plantilla de auditoría no encontrada.");const versions=await this.repository.list<AuditTemplateVersion>("audit_template_versions",{templateId:id},"version",false);return{...item,versions};}
  async create(body:any,actor:OperationsActor){const item=await this.repository.create<any>("audit_templates",{code:required(body.code,"Código").toUpperCase(),name:required(body.name,"Nombre"),auditType:body.auditType||"CUSTOM",description:body.description||null,active:true,currentVersion:0,createdBy:actor.userId});await this.repository.publish(null,null,"AUDIT_TEMPLATE",item.id,"AUDIT_TEMPLATE_CREATED",actor.userId);return item;}
  async version(id:string,body:any,actor:OperationsActor){const template=await this.repository.get<AuditTemplate>("audit_templates",id);if(!template)throw new NotFoundException("Plantilla no encontrada.");const versions=await this.repository.list<AuditTemplateVersion>("audit_template_versions",{templateId:id},"version",false);let item=await this.repository.create<any>("audit_template_versions",{templateId:id,version:(versions[0]?.version??0)+1,status:"DRAFT",changeSummary:body.changeSummary||null,publishedAt:null,publishedBy:null});for(const [sectionIndex,sectionInput] of (body.sections??[]).entries()){const section=await this.repository.create<any>("audit_template_sections",{templateVersionId:item.id,code:required(sectionInput.code,"Código de sección"),title:required(sectionInput.title,"Título de sección"),description:sectionInput.description||null,weight:Number(sectionInput.weight)||0,sortOrder:sectionIndex});for(const[checkIndex,checkInput]of(sectionInput.checks??[]).entries())await this.repository.create<any>("audit_template_checks",{templateVersionId:item.id,sectionId:section.id,code:required(checkInput.code,"Código de check"),title:required(checkInput.title,"Título de check"),description:checkInput.description||null,checkType:checkInput.checkType||"MANUAL",required:checkInput.required!==false,weight:Number(checkInput.weight)||0,severityOnFailure:checkInput.severityOnFailure||"MEDIUM",instructions:checkInput.instructions||null,automationKey:checkInput.automationKey||null,autoCreateFinding:Boolean(checkInput.autoCreateFinding),evidenceRequired:Boolean(checkInput.evidenceRequired),sortOrder:checkIndex});}
    if(body.publish){item=await this.repository.update<any>("audit_template_versions",item.id,{status:"PUBLISHED",publishedAt:now(),publishedBy:actor.userId});await this.repository.update<any>("audit_templates",id,{currentVersion:item.version});}await this.repository.publish(null,null,"AUDIT_TEMPLATE_VERSION",item.id,"AUDIT_TEMPLATE_VERSION_CREATED",actor.userId,{templateId:id,version:item.version});return item;}
  async updateVersion(id:string,body:any){const item=await this.repository.get<AuditTemplateVersion>("audit_template_versions",id);if(!item)throw new NotFoundException("Versión no encontrada.");if(item.status!=="DRAFT")throw new BadRequestException("Una versión publicada es inmutable; crea una nueva versión.");return this.repository.update<any>("audit_template_versions",id,{changeSummary:body.changeSummary});}
}

@Injectable()
export class AuditPlanService {
  constructor(private readonly repository:AuditsRepository,private readonly catalog:AuditCatalogService){}
  list(q:AuditPage){return this.repository.page<AuditPlan>("audit_plans",q);}
  async get(id:string){const item=await this.repository.get<AuditPlan>("audit_plans",id);if(!item)throw new NotFoundException("Plan de auditoría no encontrado.");return item;}
  async create(body:any,actor:OperationsActor){await this.catalog.ensureBaseline();const templateId=uuid(body.templateId,"Plantilla")!;const startDate=date(body.startDate,"Fecha de inicio")!;const frequency=body.frequency||"ONE_TIME";const item=await this.repository.create<any>("audit_plans",{clientId:uuid(body.clientId,"Cliente")!,projectId:uuid(body.projectId,"Proyecto",true),serviceId:uuid(body.serviceId,"Servicio",true),name:required(body.name,"Nombre"),auditType:body.auditType||"WEB_GENERAL",templateId,frequency,customIntervalDays:frequency==="CUSTOM"?Number(body.customIntervalDays)||null:null,responsibleUserId:uuid(body.responsibleUserId,"Auditor",true),reviewerUserId:uuid(body.reviewerUserId,"Revisor",true),startDate,nextRunAt:new Date(`${startDate}T12:00:00.000Z`).toISOString(),active:true,clientVisibility:body.clientVisibility||"INTERNAL_ONLY",createdBy:actor.userId});await this.repository.publish(null,null,"AUDIT_PLAN",item.id,"AUDIT_PLAN_CREATED",actor.userId,{clientId:item.clientId,projectId:item.projectId});return item;}
  async update(id:string,body:any,actor:OperationsActor){await this.get(id);const item=await this.repository.update<any>("audit_plans",id,{name:body.name?.trim(),responsibleUserId:body.responsibleUserId===undefined?undefined:uuid(body.responsibleUserId,"Auditor",true),reviewerUserId:body.reviewerUserId===undefined?undefined:uuid(body.reviewerUserId,"Revisor",true),nextRunAt:body.nextRunAt===undefined?undefined:date(body.nextRunAt,"Próxima ejecución",true),clientVisibility:body.clientVisibility});await this.repository.publish(null,null,"AUDIT_PLAN",id,"AUDIT_PLAN_UPDATED",actor.userId);return item;}
  async toggle(id:string,active:boolean,actor:OperationsActor){await this.get(id);const item=await this.repository.update<any>("audit_plans",id,{active});await this.repository.publish(null,null,"AUDIT_PLAN",id,active?"AUDIT_PLAN_ENABLED":"AUDIT_PLAN_DISABLED",actor.userId);return item;}
  async runNow(id:string,actor:OperationsActor,idempotencyKey?:string){const plan=await this.get(id);const key=idempotencyKey?.trim()||`plan:${id}:${new Date().toISOString().slice(0,10)}`;const provisional=randomUUID();const existing=await this.repository.claimIdempotency(key,"AUDIT_PLAN_RUN",provisional);if(existing){const audit=await this.repository.get<AuditRun>("audit_runs",existing);if(audit)return audit;}const audit=await this.createRun(plan,actor,provisional);if(plan.frequency!=="ONE_TIME")await this.repository.update<any>("audit_plans",id,{nextRunAt:addFrequency(plan.nextRunAt||now(),plan.frequency,plan.customIntervalDays)});else await this.repository.update<any>("audit_plans",id,{nextRunAt:null,active:false});return audit;}
  async createRun(plan:AuditPlan,actor:OperationsActor,id?:string){const versions=await this.repository.list<AuditTemplateVersion>("audit_template_versions",{templateId:plan.templateId,status:"PUBLISHED"},"version",false);const version=versions[0];if(!version)throw new BadRequestException("El plan no tiene una versión de plantilla publicada.");const audit=await this.repository.create<any>("audit_runs",{id:id||randomUUID(),auditNumber:await this.repository.nextAuditNumber(),planId:plan.id,clientId:plan.clientId,projectId:plan.projectId,serviceId:plan.serviceId,templateVersionId:version.id,auditType:plan.auditType,status:"SCHEDULED",scheduledAt:plan.nextRunAt||now(),startedAt:null,completedAt:null,responsibleUserId:plan.responsibleUserId,reviewerUserId:plan.reviewerUserId,score:null,progress:0,clientVisibility:plan.clientVisibility,createdBy:actor.userId});const checks=await this.repository.list<AuditTemplateCheck>("audit_template_checks",{templateVersionId:version.id},"sort_order",true);for(const check of checks)await this.repository.create<any>("audit_check_results",{auditId:audit.id,checkId:check.id,sectionId:check.sectionId,status:"NOT_STARTED",notes:null,notApplicableReason:null,evidenceRequired:check.evidenceRequired,executedBy:null,executedAt:null,automationSource:null,weight:check.weight,severityOnFailure:check.severityOnFailure,findingId:null});await this.repository.publish(audit.id,null,"AUDIT",audit.id,"AUDIT_SCHEDULED",actor.userId,{clientId:audit.clientId,projectId:audit.projectId});return audit;}
  async runDue(actor:OperationsActor){const plans=await this.repository.list<AuditPlan>("audit_plans",{active:true},"next_run_at",true);const due=plans.filter((item)=>item.nextRunAt&&item.nextRunAt<=now());const created:AuditRun[]=[];for(const plan of due)created.push(await this.runNow(plan.id,actor,`scheduler:${plan.id}:${plan.nextRunAt}`));return created;}
}

@Injectable()
export class AuditExecutionService {
  constructor(private readonly repository:AuditsRepository,private readonly automation:AuditAutomationProvider){}
  async get(id:string){const item=await this.repository.get<AuditRun>("audit_runs",id);if(!item)throw new NotFoundException("Auditoría no encontrada.");return item;}
  list(q:AuditPage){return this.repository.page<AuditRun>("audit_runs",q);}
  async checks(id:string){const[results,definitions,sections]=await Promise.all([this.repository.list<AuditCheckResult>("audit_check_results",{auditId:id},"created_at",true),this.repository.list<AuditTemplateCheck>("audit_template_checks"),this.repository.list<any>("audit_template_sections")]);const checks=new Map(definitions.map(item=>[item.id,item])),sectionMap=new Map(sections.map(item=>[item.id,item]));return results.map(item=>{const definition=checks.get(item.checkId),section=sectionMap.get(definition?.sectionId);return{...item,checkCode:item.checkCode||definition?.code||null,checkTitle:item.checkTitle||definition?.title||null,sectionCode:item.sectionCode||section?.code||null,sectionTitle:item.sectionTitle||section?.title||null};});}
  async detail(id:string){const audit=await this.get(id);const[checks,findings,evidence,allRemediations,allRetests,reports,activity]=await Promise.all([this.checks(id),this.repository.list<AuditFinding>("audit_findings",{auditId:id}),this.repository.list("audit_evidence",{auditId:id}),this.repository.list<any>("audit_remediations",{}),this.repository.list<AuditRetest>("audit_retests",{}),this.repository.list("audit_reports",{auditId:id}),this.repository.list("audit_events",{auditId:id},"occurred_at",false)]);const findingIds=new Set(findings.map(item=>item.id));const remediations=allRemediations.filter(item=>findingIds.has(item.findingId));const retests=allRetests.filter(item=>findingIds.has(item.findingId));return{audit,checks,findings,evidence,remediations,retests,reports,activity};}
  async update(id:string,body:any,actor:OperationsActor){await this.get(id);const item=await this.repository.update<any>("audit_runs",id,{responsibleUserId:body.responsibleUserId===undefined?undefined:uuid(body.responsibleUserId,"Auditor",true),reviewerUserId:body.reviewerUserId===undefined?undefined:uuid(body.reviewerUserId,"Revisor",true),scheduledAt:body.scheduledAt===undefined?undefined:date(body.scheduledAt,"Programación"),clientVisibility:body.clientVisibility});await this.repository.publish(id,null,"AUDIT",id,"AUDIT_UPDATED",actor.userId);return item;}
  async start(id:string,actor:OperationsActor){const current=await this.get(id);if(!["SCHEDULED","READY","WAITING_INFORMATION"].includes(current.status))throw new BadRequestException("La auditoría no puede iniciarse desde su estado actual.");const item=await this.repository.update<any>("audit_runs",id,{status:"IN_PROGRESS",startedAt:current.startedAt||now(),responsibleUserId:current.responsibleUserId||actor.userId});await this.repository.publish(id,null,"AUDIT",id,"AUDIT_STARTED",actor.userId);return item;}
  async submitReview(id:string,actor:OperationsActor){const current=await this.get(id);if(current.status!=="IN_PROGRESS")throw new BadRequestException("Solo una auditoría en ejecución puede enviarse a revisión.");const checks=await this.checks(id);if(checks.some((item)=>item.status==="NOT_STARTED"))throw new BadRequestException("Completa o bloquea todos los checks antes de enviar a revisión.");const item=await this.repository.update<any>("audit_runs",id,{status:"IN_REVIEW"});await this.repository.publish(id,null,"AUDIT",id,"AUDIT_SUBMITTED_REVIEW",actor.userId);return item;}
  async complete(id:string,actor:OperationsActor){const current=await this.get(id);if(!["IN_REVIEW","REMEDIATION_REQUIRED","RETEST_REQUIRED"].includes(current.status))throw new BadRequestException("La auditoría no está lista para completar.");const findings=await this.repository.list<AuditFinding>("audit_findings",{auditId:id});if(findings.some((item)=>activeFindingStatuses.has(item.status)&&item.severity==="CRITICAL"))throw new BadRequestException("Existen hallazgos críticos abiertos.");const item=await this.repository.update<any>("audit_runs",id,{status:"COMPLETED",completedAt:now()});await this.repository.publish(id,null,"AUDIT",id,"AUDIT_COMPLETED",actor.userId,{score:item.score});return item;}
  async updateCheck(auditId:string,checkId:string,body:any,actor:OperationsActor){const audit=await this.get(auditId);if(audit.status!=="IN_PROGRESS")throw new BadRequestException("La auditoría debe estar en ejecución.");const result=await this.repository.get<AuditCheckResult>("audit_check_results",checkId);if(!result||result.auditId!==auditId)throw new NotFoundException("Check no encontrado.");const status=String(body.status||"");if(!finalCheckStatuses.has(status)&&status!=="NOT_STARTED")throw new BadRequestException("Estado de check inválido.");if(status==="NOT_APPLICABLE")required(body.notApplicableReason,"Motivo de no aplicabilidad");const evidence=await this.repository.list<AuditEvidence>("audit_evidence",{checkResultId:checkId});if(result.evidenceRequired&&["PASS","PASS_WITH_OBSERVATION","FAIL"].includes(status)&&!evidence.length)throw new BadRequestException("Este check exige evidencia antes de registrar el resultado.");const item=await this.repository.update<any>("audit_check_results",checkId,{status,notes:body.notes?.trim()||null,notApplicableReason:status==="NOT_APPLICABLE"?body.notApplicableReason.trim():null,executedBy:actor.userId,executedAt:now(),automationSource:body.automationSource||null});await this.recalculate(auditId);await this.repository.publish(auditId,null,"AUDIT_CHECK",checkId,"AUDIT_CHECK_CHANGED",actor.userId,{status});return item;}
  async automate(auditId:string,checkId:string,endpointId:string,actor:OperationsActor){const audit=await this.get(auditId);if(!audit.projectId)throw new BadRequestException("La auditoría no está vinculada a un proyecto con endpoints autorizados.");const endpoint=await this.repository.authorizedEndpoint(audit.projectId,uuid(endpointId,"Endpoint")!);if(!endpoint)throw new ForbiddenException("El endpoint no pertenece al proyecto o no está autorizado.");const check=await this.repository.get<AuditCheckResult>("audit_check_results",checkId);if(!check||check.auditId!==auditId)throw new NotFoundException("Check no encontrado.");const definition=await this.repository.get<AuditTemplateCheck>("audit_template_checks",check.checkId);if(!definition?.automationKey)throw new BadRequestException("Este check no tiene automatización segura configurada.");const output=await this.automation.execute(definition.automationKey,String(endpoint.url));return this.updateCheck(auditId,checkId,{status:output.status,notes:output.notes,automationSource:output.source},actor).then((result)=>({result,evidence:output.evidence}));}
  private async recalculate(auditId:string){const checks=await this.checks(auditId);const applicable=checks.filter((item)=>item.status!=="NOT_APPLICABLE");const completed=applicable.filter((item)=>item.status!=="NOT_STARTED");const earned=applicable.reduce((sum,item)=>sum+(item.status==="PASS"?item.weight:item.status==="PASS_WITH_OBSERVATION"?item.weight*.65:0),0);const total=applicable.reduce((sum,item)=>sum+item.weight,0);const complete=applicable.length>0&&completed.length===applicable.length;return this.repository.update<any>("audit_runs",auditId,{progress:applicable.length?Math.round(completed.length/applicable.length*100):100,score:complete&&total?Math.round(earned/total*10000)/100:null});}
}

@Injectable()
export class AuditFindingService {
  constructor(private readonly repository:AuditsRepository,private readonly operations:OperationsService,private readonly quality:QualityService){}
  list(q:AuditPage){return this.repository.page<AuditFinding>("audit_findings",q);}
  async get(id:string){const item=await this.repository.get<AuditFinding>("audit_findings",id);if(!item)throw new NotFoundException("Hallazgo no encontrado.");return item;}
  async create(body:any,actor:OperationsActor){const audit=await this.repository.get<AuditRun>("audit_runs",uuid(body.auditId,"Auditoría")!);if(!audit)throw new NotFoundException("Auditoría no encontrada.");if(body.checkResultId){const existing=(await this.repository.list<AuditFinding>("audit_findings",{checkResultId:body.checkResultId}))[0];if(existing)return existing;}const item=await this.repository.create<any>("audit_findings",{findingNumber:await this.repository.nextFindingNumber(),auditId:audit.id,clientId:audit.clientId,projectId:audit.projectId,checkResultId:uuid(body.checkResultId,"Resultado",true),category:required(body.category||audit.auditType,"Categoría"),title:required(body.title,"Título"),description:required(body.description,"Descripción"),severity:body.severity||"MEDIUM",priority:body.priority||"NORMAL",status:"OPEN",responsibleUserId:uuid(body.responsibleUserId,"Responsable",true),dueDate:date(body.dueDate,"Fecha objetivo",true),recommendation:body.recommendation||null,internalNotes:body.internalNotes||null,clientSummary:body.clientSummary||null,clientVisibility:body.clientVisibility||"INTERNAL_ONLY",taskId:null,bugId:null,acceptedRiskReason:null,acceptedRiskBy:null,riskReviewAt:null,resolvedAt:null});if(body.checkResultId)await this.repository.update<any>("audit_check_results",body.checkResultId,{findingId:item.id});await this.repository.update<any>("audit_runs",audit.id,{status:"REMEDIATION_REQUIRED"});await this.repository.publish(audit.id,item.id,"FINDING",item.id,item.severity==="CRITICAL"?"CRITICAL_FINDING_CREATED":"FINDING_CREATED",actor.userId,{severity:item.severity,responsibleUserId:item.responsibleUserId});return item;}
  async update(id:string,body:any,actor:OperationsActor){const current=await this.get(id);const item=await this.repository.update<any>("audit_findings",id,{title:body.title?.trim(),description:body.description?.trim(),category:body.category,severity:body.severity,priority:body.priority,dueDate:body.dueDate===undefined?undefined:date(body.dueDate,"Fecha objetivo",true),recommendation:body.recommendation,internalNotes:body.internalNotes,clientSummary:body.clientSummary,clientVisibility:body.clientVisibility});await this.repository.publish(current.auditId,id,"FINDING",id,"FINDING_UPDATED",actor.userId,{severity:item.severity});return item;}
  async assign(id:string,userId:string,actor:OperationsActor){const current=await this.get(id);const item=await this.repository.update<any>("audit_findings",id,{responsibleUserId:uuid(userId,"Responsable")!,status:"ASSIGNED"});await this.repository.publish(current.auditId,id,"FINDING",id,"FINDING_ASSIGNED",actor.userId,{responsibleUserId:userId});return item;}
  async remediation(id:string,body:any,actor:OperationsActor){const finding=await this.get(id);const current=(await this.repository.list<any>("audit_remediations",{findingId:id}))[0];const value={ownerId:uuid(body.ownerId??finding.responsibleUserId,"Responsable",true),actionPlan:required(body.actionPlan,"Plan de acción"),status:body.status||"PLANNED",targetDate:date(body.targetDate,"Fecha objetivo",true),taskId:finding.taskId,bugId:finding.bugId,startedAt:body.status==="IN_PROGRESS"?now():current?.startedAt??null,completedAt:body.status==="COMPLETED"?now():null};const item=current?await this.repository.update<any>("audit_remediations",current.id,value):await this.repository.create<any>("audit_remediations",{findingId:id,...value});await this.repository.update<any>("audit_findings",id,{status:item.status==="READY_FOR_RETEST"?"READY_FOR_RETEST":"IN_REMEDIATION"});await this.repository.publish(finding.auditId,id,"REMEDIATION",item.id,"REMEDIATION_UPDATED",actor.userId,{status:item.status});return item;}
  async createTask(id:string,body:any,actor:OperationsActor){const finding=await this.get(id);if(finding.taskId)return this.operations.getTask(finding.taskId,actor);if(!finding.projectId)throw new BadRequestException("El hallazgo necesita un proyecto para crear una tarea correctiva.");const task=await this.operations.createTask({projectId:finding.projectId,title:`${finding.findingNumber} · ${finding.title}`,description:body.description||finding.recommendation||finding.description,priority:finding.severity==="CRITICAL"?"CRITICAL":finding.severity==="HIGH"?"URGENT":finding.priority,assignedTo:body.assignedTo||finding.responsibleUserId,dueDate:body.dueDate||finding.dueDate,status:"TODO",clientVisibility:finding.clientVisibility==="CLIENT_VISIBLE"?"CLIENT_VISIBLE":"INTERNAL"},actor);await this.repository.update<any>("audit_findings",id,{taskId:task.id,status:"IN_REMEDIATION"});const remediation=(await this.repository.list<any>("audit_remediations",{findingId:id}))[0];if(remediation)await this.repository.update<any>("audit_remediations",remediation.id,{taskId:task.id});await this.repository.publish(finding.auditId,id,"FINDING",id,"CORRECTIVE_TASK_CREATED",actor.userId,{taskId:task.id});return task;}
  async createBug(id:string,body:any,actor:OperationsActor){const finding=await this.get(id);if(finding.bugId)return this.quality.bug(finding.bugId,actor);if(!finding.projectId)throw new BadRequestException("El hallazgo necesita un proyecto para crear un bug.");const bug=await this.quality.createBug({projectId:finding.projectId,taskId:finding.taskId,title:`${finding.findingNumber} · ${finding.title}`,description:finding.description,severity:finding.severity==="INFO"?"LOW":finding.severity,priority:finding.priority,assignedTo:body.assignedTo||finding.responsibleUserId,evidenceDocumentId:body.evidenceDocumentId,clientVisibility:finding.clientVisibility},actor);await this.repository.update<any>("audit_findings",id,{bugId:bug.id,status:"IN_REMEDIATION"});const remediation=(await this.repository.list<any>("audit_remediations",{findingId:id}))[0];if(remediation)await this.repository.update<any>("audit_remediations",remediation.id,{bugId:bug.id});await this.repository.publish(finding.auditId,id,"FINDING",id,"DEVELOPMENT_BUG_LINKED",actor.userId,{bugId:bug.id});return bug;}
  async ready(id:string,actor:OperationsActor){const finding=await this.get(id);if(!["ASSIGNED","IN_REMEDIATION","RETEST_FAILED"].includes(finding.status))throw new BadRequestException("El hallazgo no está listo para retest.");const item=await this.repository.update<any>("audit_findings",id,{status:"READY_FOR_RETEST"});await this.repository.update<any>("audit_runs",finding.auditId,{status:"RETEST_REQUIRED"});await this.repository.publish(finding.auditId,id,"FINDING",id,"RETEST_REQUIRED",actor.userId);return item;}
  async retest(id:string,body:any,actor:OperationsActor){const finding=await this.get(id);if(finding.status!=="READY_FOR_RETEST"&&finding.status!=="RETEST_FAILED")throw new BadRequestException("El hallazgo no está listo para retest.");const result=String(body.result||"");if(!["PASS","FAIL","BLOCKED"].includes(result))throw new BadRequestException("Resultado de retest inválido.");const item=await this.repository.create<AuditRetest&Record<string,unknown>>("audit_retests",{findingId:id,performedBy:actor.userId,performedAt:now(),result:result as AuditRetest["result"],notes:required(body.notes,"Notas"),evidenceId:uuid(body.evidenceId,"Evidencia",true),createdAt:now(),id:randomUUID()});await this.repository.update<any>("audit_findings",id,{status:result==="PASS"?"RESOLVED":result==="FAIL"?"RETEST_FAILED":"READY_FOR_RETEST",resolvedAt:result==="PASS"?now():null});await this.repository.publish(finding.auditId,id,"RETEST",item.id,result==="PASS"?"RETEST_PASSED":result==="FAIL"?"RETEST_FAILED":"RETEST_BLOCKED",actor.userId);return item;}
  retests(id:string){return this.get(id).then(()=>this.repository.list<AuditRetest>("audit_retests",{findingId:id},"performed_at",false));}
  async acceptRisk(id:string,body:any,actor:OperationsActor){if(!managers.has(actor.role))throw new ForbiddenException("Solo Jefatura o Gerencia puede aceptar riesgo.");const finding=await this.get(id);const item=await this.repository.update<any>("audit_findings",id,{status:"ACCEPTED_RISK",acceptedRiskReason:required(body.reason,"Motivo"),acceptedRiskBy:actor.userId,riskReviewAt:date(body.reviewAt,"Fecha de revisión")});await this.repository.publish(finding.auditId,id,"FINDING",id,"FINDING_RISK_ACCEPTED",actor.userId,{reviewAt:item.riskReviewAt});return item;}
  async close(id:string,actor:OperationsActor){const finding=await this.get(id);if(!["RESOLVED","ACCEPTED_RISK","NOT_APPLICABLE"].includes(finding.status))throw new BadRequestException("Solo un hallazgo resuelto, aceptado o no aplicable puede cerrarse.");const item=await this.repository.update<any>("audit_findings",id,{status:"CLOSED",resolvedAt:finding.resolvedAt||now()});await this.repository.publish(finding.auditId,id,"FINDING",id,"FINDING_CLOSED",actor.userId);return item;}
}

@Injectable()
export class AuditEvidenceService {
  constructor(private readonly repository:AuditsRepository,@Optional() private readonly documents?:DocumentService){}
  list(){return this.repository.list<AuditEvidence>("audit_evidence",{},"uploaded_at",false);}
  async add(auditId:string,checkResultId:string|null,body:any,actor:OperationsActor){const audit=await this.repository.get<AuditRun>("audit_runs",auditId);if(!audit)throw new NotFoundException("Auditoría no encontrada.");const content=body.contentBase64?Buffer.from(String(body.contentBase64),"base64"):body.textContent?Buffer.from(String(body.textContent)):null;const unsafe=content?.toString("utf8",0,Math.min(content.length,100_000))??"";if(/(authorization:\s*bearer|api[_-]?key\s*[=:]|password\s*[=:]|cookie:\s*)/i.test(unsafe))throw new BadRequestException("La evidencia parece contener credenciales o secretos y fue rechazada.");const hash=content?createHash("sha256").update(content).digest("hex"):null;let documentId=uuid(body.documentId,"Documento",true),storagePath:string|null=null;if(content&&this.documents&&!documentId){const links=[{linkType:"AUDIT",linkedId:audit.id,primaryLink:true},{linkType:"CLIENT",linkedId:audit.clientId},...(audit.projectId?[{linkType:"PROJECT",linkedId:audit.projectId}]:[])],document=await this.documents.create({title:required(body.title,"Título"),description:body.description||`Evidencia de ${audit.auditNumber}`,typeCode:"EVIDENCE",classification:body.visibility==="CLIENT_VISIBLE"?"CLIENT":"INTERNAL",links},actor);const result=await this.documents.addVersion(document.id,{filename:body.filename||"evidence.txt",mimeType:body.mimeType||"text/plain",base64:content.toString("base64"),changeSummary:"Evidencia incorporada desde Auditorías"},actor);documentId=document.id;storagePath=result.version.storagePath;}else if(content){const evidenceId=randomUUID();const path=`${audit.clientId}/${audit.id}/${evidenceId}-${String(body.filename||"evidence.bin").replace(/[^a-zA-Z0-9._-]/g,"_")}`;storagePath=await this.repository.saveFile("audit-evidence",path,content,body.mimeType||"application/octet-stream");}
    const item=await this.repository.create<any>("audit_evidence",{auditId,findingId:uuid(body.findingId,"Hallazgo",true),checkResultId:checkResultId?uuid(checkResultId,"Check"):null,documentId,storagePath,evidenceType:body.evidenceType||"TEXT",title:required(body.title,"Título"),description:body.description||null,filename:body.filename||null,mimeType:body.mimeType||null,sizeBytes:content?.length??null,sha256:hash,externalUrl:body.externalUrl||null,textContent:body.textContent||null,visibility:body.visibility||"INTERNAL_ONLY",uploadedBy:actor.userId,uploadedAt:now()});await this.repository.publish(auditId,item.findingId,"EVIDENCE",item.id,"AUDIT_EVIDENCE_ADDED",actor.userId,{visibility:item.visibility,sha256:item.sha256});return item;}
}

@Injectable()
export class AuditReportService {
  constructor(private readonly repository:AuditsRepository,private readonly renderer:AuditReportRenderer,@Optional() private readonly documents?:DocumentService){}
  list(){return this.repository.list<AuditReport>("audit_reports",{},"generated_at",false);}
  reports(auditId:string){return this.repository.list<AuditReport>("audit_reports",{auditId},"version",false);}
  async generate(auditId:string,body:any,actor:OperationsActor){
    const audit=await this.repository.get<AuditRun>("audit_runs",auditId);if(!audit)throw new NotFoundException("Auditoría no encontrada.");
    const type=body.reportType==="CLIENT"?"CLIENT":"INTERNAL";
    const[checks,findings,evidence,reports]=await Promise.all([this.repository.list<AuditCheckResult>("audit_check_results",{auditId}),this.repository.list<AuditFinding>("audit_findings",{auditId}),this.repository.list<AuditEvidence>("audit_evidence",{auditId}),this.reports(auditId)]);
    const safeFindings=type==="CLIENT"?findings.filter((item)=>item.clientVisibility!=="INTERNAL_ONLY").map((item)=>({...item,description:item.clientSummary||item.recommendation||"Resumen autorizado",internalNotes:null})):findings;
    const safeEvidence=type==="CLIENT"?evidence.filter((item)=>item.visibility==="CLIENT_VISIBLE"):evidence;
    const snapshot={audit:{auditNumber:audit.auditNumber,auditType:audit.auditType,score:audit.score,completedAt:audit.completedAt},checks:checks.map((item)=>({code:item.checkCode,status:item.status})),findings:safeFindings.map((item)=>({number:item.findingNumber,title:item.title,severity:item.severity,status:item.status,summary:type==="CLIENT"?item.clientSummary:item.description})),evidence:safeEvidence.map((item)=>({title:item.title,sha256:item.sha256}))};
    const version=Math.max(0,...reports.filter((item)=>item.reportType===type).map((item)=>item.version))+1;
    const rendered=this.renderer.render(audit.auditNumber,type,["ZYTERON CONTROL",type==="CLIENT"?"INFORME DE AUDITORIA PARA CLIENTE":"INFORME INTERNO DE AUDITORIA",`Auditoria: ${audit.auditNumber}`,`Tipo: ${audit.auditType}`,`Fecha: ${new Date().toISOString().slice(0,10)}`,`Score: ${audit.score??"No calculable"}`,`Checks: ${checks.length}`,`Hallazgos: ${safeFindings.length}`,...safeFindings.slice(0,18).map((item)=>`${item.findingNumber} [${item.severity}] ${item.title}`)]);
    let documentId:string|null;
    if(this.documents){
      const links=[{linkType:"AUDIT",linkedId:audit.id,primaryLink:true},{linkType:"CLIENT",linkedId:audit.clientId,primaryLink:false},...(audit.projectId?[{linkType:"PROJECT",linkedId:audit.projectId,primaryLink:false}]:[])];
      const document=await this.documents.create({title:`Informe ${type==="CLIENT"?"cliente":"interno"} · ${audit.auditNumber}`,description:`Informe controlado de auditoría ${audit.auditNumber}`,typeCode:"REPORT",classification:type==="CLIENT"?"CLIENT":"CONFIDENTIAL",links},actor);
      const uploaded=await this.documents.addVersion(document.id,{filename:rendered.filename.replace(".pdf",`-v${version}.pdf`),mimeType:"application/pdf",base64:rendered.bytes.toString("base64"),changeSummary:`Informe ${type} · versión ${version}`},actor);
      documentId=document.id;
      if(uploaded.version.sha256!==rendered.sha256)throw new ConflictException("La huella del informe almacenado no coincide con el artefacto generado.");
    }else{
      const path=`${audit.clientId}/${audit.id}/${rendered.filename.replace(".pdf",`-v${version}.pdf`)}`;
      documentId=await this.repository.saveFile("audit-reports",path,rendered.bytes,"application/pdf");
    }
    const item=await this.repository.create<any>("audit_reports",{auditId,version,reportType:type,status:"DRAFT",documentId,sha256:rendered.sha256,templateVersionId:audit.templateVersionId,auditSnapshot:snapshot,generatedBy:actor.userId,generatedAt:now(),approvedBy:null,approvedAt:null,publishedAt:null});
    await this.repository.publish(auditId,null,"AUDIT_REPORT",item.id,"REPORT_READY",actor.userId,{version,type,sha256:item.sha256,documentId});return item;
  }
  async approve(auditId:string,actor:OperationsActor){const reports=await this.reports(auditId),item=reports.find((entry)=>entry.status==="DRAFT"||entry.status==="REVIEW");if(!item)throw new BadRequestException("No existe un informe pendiente de aprobación.");const result=await this.repository.update<any>("audit_reports",item.id,{status:"APPROVED",approvedBy:actor.userId,approvedAt:now()});await this.repository.publish(auditId,null,"AUDIT_REPORT",item.id,"REPORT_APPROVED",actor.userId);return result;}
  async publish(auditId:string,actor:OperationsActor){const reports=await this.reports(auditId),item=reports.find((entry)=>entry.status==="APPROVED"&&entry.reportType==="CLIENT");if(!item)throw new BadRequestException("No existe un informe cliente aprobado.");const audit=await this.repository.get<AuditRun>("audit_runs",auditId);if(audit?.clientVisibility==="INTERNAL_ONLY")throw new BadRequestException("La auditoría no tiene visibilidad cliente habilitada.");const result=await this.repository.update<any>("audit_reports",item.id,{status:"PUBLISHED",publishedAt:now()});await this.repository.publish(auditId,null,"AUDIT_REPORT",item.id,"REPORT_PUBLISHED",actor.userId);return result;}
}

@Injectable()
export class AuditReadService {
  constructor(private readonly repository:AuditsRepository,private readonly plans:AuditPlanService,private readonly execution:AuditExecutionService,private readonly findings:AuditFindingService,private readonly evidence:AuditEvidenceService,private readonly reports:AuditReportService,private readonly catalog:AuditCatalogService){}
  async summary():Promise<AuditSummary>{const[audits,findings,remediations,retests,reports]=await Promise.all([this.repository.list<AuditRun>("audit_runs"),this.repository.list<AuditFinding>("audit_findings"),this.repository.list<any>("audit_remediations"),this.repository.list<AuditRetest>("audit_retests"),this.repository.list<AuditReport>("audit_reports")]);const time=now(),open=findings.filter((item)=>activeFindingStatuses.has(item.status)),completed=audits.filter((item)=>item.status==="COMPLETED"),resolved=findings.filter((item)=>item.resolvedAt),passed=retests.filter((item)=>item.result==="PASS");return{scheduled:audits.filter((item)=>["SCHEDULED","READY"].includes(item.status)).length,overdue:audits.filter((item)=>["SCHEDULED","READY"].includes(item.status)&&item.scheduledAt<time).length,inProgress:audits.filter((item)=>item.status==="IN_PROGRESS").length,pendingReview:audits.filter((item)=>item.status==="IN_REVIEW").length,openFindings:open.length,criticalFindings:open.filter((item)=>item.severity==="CRITICAL").length,overdueRemediations:remediations.filter((item)=>item.targetDate&&item.targetDate<time.slice(0,10)&&!["COMPLETED","CANCELLED"].includes(item.status)).length,pendingRetests:findings.filter((item)=>item.status==="READY_FOR_RETEST"||item.status==="RETEST_FAILED").length,pendingReports:completed.filter((audit)=>!reports.some((report)=>report.auditId===audit.id&&["APPROVED","PUBLISHED"].includes(report.status))).length,nextAuditAt:audits.filter((item)=>["SCHEDULED","READY"].includes(item.status)).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt))[0]?.scheduledAt??null,completionRate:audits.length?Math.round(completed.length/audits.length*10000)/100:null,retestSuccessRate:retests.length?Math.round(passed.length/retests.length*10000)/100:null,averageResolutionHours:resolved.length?Math.round(resolved.reduce((sum,item)=>sum+(Date.parse(item.resolvedAt!)-Date.parse(item.createdAt))/3_600_000,0)/resolved.length*100)/100:null};}
  async attention(){const[audits,findings,remediations,reports]=await Promise.all([this.repository.list<AuditRun>("audit_runs"),this.repository.list<AuditFinding>("audit_findings"),this.repository.list<any>("audit_remediations"),this.repository.list<AuditReport>("audit_reports")]),time=now();return[...findings.filter((item)=>activeFindingStatuses.has(item.status)&&item.severity==="CRITICAL").map((item)=>({id:item.id,type:"FINDING" as const,title:item.findingNumber,reason:"Hallazgo crítico abierto",severity:"CRITICAL" as const,href:`/audits/findings/${item.id}`,dueAt:item.dueDate})),...audits.filter((item)=>["SCHEDULED","READY"].includes(item.status)&&item.scheduledAt<time).map((item)=>({id:item.id,type:"AUDIT" as const,title:item.auditNumber,reason:"Auditoría vencida",severity:"AT_RISK" as const,href:`/audits/${item.id}`,dueAt:item.scheduledAt})),...remediations.filter((item)=>item.targetDate&&item.targetDate<time.slice(0,10)&&!["COMPLETED","CANCELLED"].includes(item.status)).map((item)=>({id:item.id,type:"REMEDIATION" as const,title:"Remediación vencida",reason:"La fecha objetivo ya pasó",severity:"AT_RISK" as const,href:"/audits/remediations",dueAt:item.targetDate})),...audits.filter((item)=>item.status==="COMPLETED"&&!reports.some((report)=>report.auditId===item.id)).map((item)=>({id:item.id,type:"REPORT" as const,title:item.auditNumber,reason:"Informe pendiente",severity:"ATTENTION" as const,href:`/audits/${item.id}`,dueAt:null}))].slice(0,30);}
  async workspace():Promise<AuditWorkspace>{await this.catalog.ensureBaseline();const[summary,attention,audits,plans,findings,remediations,evidence,templates,reports,activity]=await Promise.all([this.summary(),this.attention(),this.repository.list<AuditRun>("audit_runs"),this.repository.list<AuditPlan>("audit_plans"),this.repository.list<AuditFinding>("audit_findings"),this.repository.list<any>("audit_remediations"),this.evidence.list(),this.catalog.templates(),this.reports.list(),this.repository.list<any>("audit_events",{},"occurred_at",false)]);return{summary,attention,audits,plans,findings,remediations,evidence,templates,reports,activity};}
  activity(){return this.repository.list("audit_events",{},"occurred_at",false);}
  async search(query:string){const value=query.trim();if(value.length<2)return{audits:[],findings:[]};const[audits,findings]=await Promise.all([this.repository.page<AuditRun>("audit_runs",{page:1,pageSize:8,search:value}),this.repository.page<AuditFinding>("audit_findings",{page:1,pageSize:8,search:value})]);return{audits:audits.items,findings:findings.items};}
  async related(filter:{clientId?:string;projectId?:string}){const[audits,findings,allRemediations,reports]=await Promise.all([this.repository.list<AuditRun>("audit_runs",filter),this.repository.list<AuditFinding>("audit_findings",filter),this.repository.list<any>("audit_remediations"),this.repository.list<AuditReport>("audit_reports")]);const ids=new Set(findings.map(item=>item.id)),auditIds=new Set(audits.map(item=>item.id)),time=now();const scheduled=audits.filter(item=>["SCHEDULED","READY"].includes(item.status)&&item.scheduledAt>=time).sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt));const completed=audits.filter(item=>item.status==="COMPLETED").sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));const openFindings=findings.filter(item=>activeFindingStatuses.has(item.status));return{nextAudit:scheduled[0]??null,lastAudit:completed[0]??null,audits,openFindings,criticalFindings:openFindings.filter(item=>item.severity==="CRITICAL").length,remediations:allRemediations.filter(item=>ids.has(item.findingId)),reports:reports.filter(item=>auditIds.has(item.auditId))};}
}
