import { BadRequestException, ForbiddenException } from "@nestjs/common";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import type { OperationsActor } from "../operations/operations.service.js";
import { SafeHttpAuditProvider, AuditReportRenderer } from "./audits.providers.js";
import { AuditsRepository } from "./audits.repository.js";
import { AuditCatalogService, AuditEvidenceService, AuditExecutionService, AuditFindingService, AuditPlanService, AuditReadService, AuditReportService } from "./audits.service.js";

const managerId="11111111-1111-4111-8111-111111111111",clientId="22222222-2222-4222-8222-222222222222",projectId="33333333-3333-4333-8333-333333333333";
const manager:OperationsActor={userId:managerId,role:"GERENTE_GENERAL"};

describe("Quality & Compliance Center",()=>{
  let repository:AuditsRepository,catalog:AuditCatalogService,plans:AuditPlanService,execution:AuditExecutionService,evidence:AuditEvidenceService,findings:AuditFindingService,reports:AuditReportService,read:AuditReadService;
  const taskService={createTask:async(body:any)=>({id:"44444444-4444-4444-8444-444444444444",...body}),getTask:async(id:string)=>({id})};
  const qualityService={createBug:async(body:any)=>({id:"55555555-5555-4555-8555-555555555555",...body}),bug:async(id:string)=>({id})};
  beforeEach(()=>{delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;repository=new AuditsRepository();catalog=new AuditCatalogService(repository);plans=new AuditPlanService(repository,catalog);execution=new AuditExecutionService(repository,new SafeHttpAuditProvider());evidence=new AuditEvidenceService(repository);findings=new AuditFindingService(repository,taskService as any,qualityService as any);reports=new AuditReportService(repository,new AuditReportRenderer());read=new AuditReadService(repository,plans,execution,findings,evidence,reports,catalog);});
  async function audit(key="audit-test"){const templates=await catalog.ensureBaseline();const plan=await plans.create({clientId,projectId,name:"Revisión trimestral",auditType:"WEB_GENERAL",templateId:templates[0]!.id,frequency:"QUARTERLY",startDate:"2026-10-01",responsibleUserId:managerId},manager);return plans.runNow(plan.id,manager,key);}

  it("crea catálogo configurable con versión publicada y checks ponderados",async()=>{const templates=await catalog.ensureBaseline();expect(templates[0]?.currentVersion).toBe(1);const detail=await catalog.template(templates[0]!.id);expect(detail.versions[0]?.status).toBe("PUBLISHED");expect((await repository.list("audit_template_checks",{})).length).toBe(6);});
  it("crea plan y Audit Run con numeración empresarial",async()=>{const run=await audit();expect(run.auditNumber).toMatch(/^AUD-\d{4}-\d{6}$/);expect((await execution.checks(run.id)).length).toBe(6);});
  it("evita doble Audit Run con idempotencia",async()=>{const templates=await catalog.ensureBaseline();const plan=await plans.create({clientId,name:"Mensual",templateId:templates[0]!.id,frequency:"MONTHLY",startDate:"2026-10-01"},manager);const first=await plans.runNow(plan.id,manager,"same-period"),second=await plans.runNow(plan.id,manager,"same-period");expect(second.id).toBe(first.id);});
  it("actualiza recurrencia sin duplicar períodos",async()=>{const templates=await catalog.ensureBaseline();const plan=await plans.create({clientId,name:"Semanal",templateId:templates[0]!.id,frequency:"WEEKLY",startDate:"2026-10-01"},manager);await plans.runNow(plan.id,manager,"weekly-1");expect((await plans.get(plan.id)).nextRunAt).toContain("2026-10-08");});
  it("aplica máquina de estados y exige checklist antes de revisión",async()=>{const run=await audit("state");await execution.start(run.id,manager);await expect(execution.submitReview(run.id,manager)).rejects.toBeInstanceOf(BadRequestException);expect((await execution.get(run.id)).status).toBe("IN_PROGRESS");});
  it("exige motivo cuando un check es no aplicable",async()=>{const run=await audit("na");await execution.start(run.id,manager);const check=(await execution.checks(run.id))[0]!;await expect(execution.updateCheck(run.id,check.id,{status:"NOT_APPLICABLE"},manager)).rejects.toBeInstanceOf(BadRequestException);expect((await execution.updateCheck(run.id,check.id,{status:"NOT_APPLICABLE",notApplicableReason:"Fuera de alcance"},manager)).status).toBe("NOT_APPLICABLE");});
  it("excluye N/A del score y no publica score con checklist parcial",async()=>{const run=await audit("score");await execution.start(run.id,manager);const checks=await execution.checks(run.id),first=checks.find(item=>!item.evidenceRequired)!;await execution.updateCheck(run.id,first.id,{status:"PASS"},manager);expect((await execution.get(run.id)).score).toBeNull();for(const check of checks.filter(item=>item.id!==first.id))await execution.updateCheck(run.id,check.id,check.evidenceRequired?{status:"NOT_APPLICABLE",notApplicableReason:"Fuera de alcance"}:{status:"PASS"},manager);const current=await execution.get(run.id);expect(current.score).toBe(100);expect(current.progress).toBe(100);});
  it("exige evidencia en controles manuales",async()=>{const run=await audit("required-evidence");await execution.start(run.id,manager);const manual=(await execution.checks(run.id)).find(item=>item.evidenceRequired)!;await expect(execution.updateCheck(run.id,manual.id,{status:"PASS"},manager)).rejects.toBeInstanceOf(BadRequestException);await evidence.add(run.id,manual.id,{title:"Validación",evidenceType:"TEXT",textContent:"Ejecución autorizada sin secretos"},manager);expect((await execution.updateCheck(run.id,manual.id,{status:"PASS"},manager)).status).toBe("PASS");});
  it("calcula SHA-256 y rechaza secretos en evidencia",async()=>{const run=await audit("evidence");const item=await evidence.add(run.id,null,{title:"Acta",textContent:"resultado autorizado"},manager);expect(item.sha256).toMatch(/^[a-f0-9]{64}$/);await expect(evidence.add(run.id,null,{title:"Secreto",textContent:"Authorization: Bearer token"},manager)).rejects.toBeInstanceOf(BadRequestException);});
  it("crea hallazgo único y lo vincula al check",async()=>{const run=await audit("finding");const check=(await execution.checks(run.id))[0]!;const finding=await findings.create({auditId:run.id,checkResultId:check.id,category:"SECURITY",title:"HTTPS ausente",description:"El endpoint no usa HTTPS",severity:"HIGH"},manager);const duplicate=await findings.create({auditId:run.id,checkResultId:check.id,category:"SECURITY",title:"Duplicado",description:"Duplicado"},manager);expect(finding.findingNumber).toMatch(/^FND-\d{4}-\d{6}$/);expect(duplicate.id).toBe(finding.id);});
  it("reutiliza tasks y bugs para la corrección",async()=>{const run=await audit("links");const finding=await findings.create({auditId:run.id,category:"QUALITY",title:"Error funcional",description:"Falla",severity:"HIGH"},manager);expect((await findings.createTask(finding.id,{},manager) as any).id).toBe("44444444-4444-4444-8444-444444444444");expect((await findings.createBug(finding.id,{},manager) as any).id).toBe("55555555-5555-4555-8555-555555555555");const linked=await findings.get(finding.id);expect(linked.taskId).toBeTruthy();expect(linked.bugId).toBeTruthy();});
  it("resuelve hallazgo únicamente con retest PASS",async()=>{const run=await audit("retest-pass");const finding=await findings.create({auditId:run.id,category:"QUALITY",title:"Falla",description:"Falla",severity:"MEDIUM"},manager);await findings.remediation(finding.id,{actionPlan:"Corregir",status:"IN_PROGRESS"},manager);await findings.ready(finding.id,manager);await findings.retest(finding.id,{result:"PASS",notes:"Verificado"},manager);expect((await findings.get(finding.id)).status).toBe("RESOLVED");});
  it("mantiene riesgo abierto cuando el retest falla",async()=>{const run=await audit("retest-fail");const finding=await findings.create({auditId:run.id,category:"QUALITY",title:"Falla",description:"Falla",severity:"MEDIUM"},manager);await findings.remediation(finding.id,{actionPlan:"Corregir",status:"IN_PROGRESS"},manager);await findings.ready(finding.id,manager);await findings.retest(finding.id,{result:"FAIL",notes:"Sigue fallando"},manager);expect((await findings.get(finding.id)).status).toBe("RETEST_FAILED");});
  it("restringe aceptación de riesgo y exige revisión futura",async()=>{const run=await audit("risk");const finding=await findings.create({auditId:run.id,category:"RISK",title:"Riesgo",description:"Contexto",severity:"LOW"},manager);await expect(findings.acceptRisk(finding.id,{reason:"Temporal",reviewAt:"2026-12-01"},{userId:managerId,role:"QA"})).rejects.toBeInstanceOf(ForbiddenException);expect((await findings.acceptRisk(finding.id,{reason:"Aceptado por negocio",reviewAt:"2026-12-01"},manager)).status).toBe("ACCEPTED_RISK");});
  it("genera PDF versionado con hash inmutable",async()=>{const run=await audit("report");const first=await reports.generate(run.id,{reportType:"INTERNAL"},manager),second=await reports.generate(run.id,{reportType:"INTERNAL"},manager);expect(first.sha256).toMatch(/^[a-f0-9]{64}$/);expect(second.version).toBe(2);expect(second.sha256).toBe(first.sha256);});
  it("construye métricas reales sin inventar porcentajes",async()=>{expect((await read.summary()).completionRate).toBeNull();const run=await audit("metrics");expect((await read.summary()).scheduled).toBe(1);expect((await read.workspace()).audits[0]?.id).toBe(run.id);});
  it("bloquea SSRF y automatizaciones no autorizadas",async()=>{const provider=new SafeHttpAuditProvider();await expect(provider.execute("HTTP_AVAILABILITY","http://127.0.0.1/admin")).rejects.toBeInstanceOf(BadRequestException);await expect(provider.execute("EXPLOIT","https://example.com")).rejects.toBeInstanceOf(BadRequestException);});
});

describe("migración Auditorías",()=>{const sql=readFileSync(resolve(process.cwd(),"../../supabase/migrations/20261001040000_quality_compliance_center.sql"),"utf8");it("reutiliza Client, Project, Task y Bug sin duplicarlos",()=>{expect(sql).toContain("references public.clients");expect(sql).toContain("references public.projects");expect(sql).toContain("references public.tasks");expect(sql).toContain("references public.bugs");expect(sql).not.toContain("create table if not exists public.audit_tasks");});it("incluye RLS, RBAC, Realtime, Storage y outbox",()=>{expect(sql).toContain("enable row level security");expect(sql).toContain("audit.execute");expect(sql).toContain("supabase_realtime");expect(sql).toContain("audit-evidence");expect(sql).toContain("business_event_outbox");});it("protege versiones, números e idempotencia",()=>{expect(sql).toContain("audit_template_version_immutable");expect(sql).toContain("before insert or update or delete on public.audit_template_sections");expect(sql).toContain("before insert or update or delete on public.audit_template_checks");expect(sql).toContain("next_audit_number");expect(sql).toContain("next_finding_number");expect(sql).toContain("audit_idempotency_keys");});});
