import { BadRequestException,ConflictException,ForbiddenException,Injectable } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { AlertRule,AutomationRule,AutomationRun,ConfigurationEntry,ConfigurationHistoryItem,FeatureFlag,SettingsIntegrationConnection,OutgoingWebhook,SettingsWorkspace,SystemDiagnostic,SystemJob } from "@zyteron/contracts";
import { automationActions,businessEvents,conditionOperators,dependencies,integrationCatalog,jobCatalog,protectedInvariants,valueTypes } from "./settings.defaults.js";
import { SettingsRepository } from "./settings.repository.js";

export interface SettingsActor{userId:string|null;role:string;aal:"aal1"|"aal2";requestId:string|null;}
type Row=Record<string,any>;
const now=()=>new Date().toISOString();
const required=(value:unknown,label:string)=>{const result=String(value??"").trim();if(!result)throw new BadRequestException(`${label} es obligatorio.`);return result;};
const safe=(value:unknown):unknown=>{const blocked=/password|secret.?value|token|authorization|cookie|private.?key|service.?role/i;const walk=(item:unknown):unknown=>Array.isArray(item)?item.slice(0,100).map(walk):item&&typeof item==="object"?Object.fromEntries(Object.entries(item as Row).filter(([key])=>!blocked.test(key)).map(([key,entry])=>[key,walk(entry)])):typeof item==="string"?item.slice(0,1000):item;return walk(value);};
const rejectSecrets=(value:unknown)=>{const inspect=(item:unknown)=>{if(!item||typeof item!=="object")return;for(const[key,entry]of Object.entries(item as Row)){if(/password|secret.?value|api.?key|private.?key|service.?role|access.?token/i.test(key))throw new BadRequestException("Los secretos plaintext están prohibidos; utiliza secretReference de Security Vault.");inspect(entry);}};inspect(value);};

@Injectable()
export class SettingsService{
 private cache:{expiresAt:number;data:SettingsWorkspace}|null=null;
 private locks=new Set<string>();
 constructor(private readonly repository:SettingsRepository){}
 private invalidate(){this.cache=null;}
 private assertAal2(actor:SettingsActor){if(actor.aal!=="aal2")throw new ForbiddenException("Esta operación crítica requiere verificación MFA (AAL2).");}
 private assertNamespaceOwnership(namespace:string,actor:SettingsActor){const normalized=namespace.trim().toLowerCase();if(["GERENTE_GENERAL","SECURITY_ADMIN"].includes(actor.role))return;if(actor.role==="RRHH"&&["hr","organization","calendar"].includes(normalized))return;if(actor.role==="FINANZAS"&&normalized==="finance")return;throw new ForbiddenException("Tu rol no administra este dominio de configuración.");}
 private async audit(actor:SettingsActor,action:string,resourceType:string,resourceId:string|null,before:unknown,after:unknown,reason:string){await this.repository.append("configuration_audit_events",{action,resourceType,resourceId,actorId:actor.userId,actorRole:actor.role,beforeSafe:safe(before),afterSafe:safe(after),reason:required(reason,"Motivo"),requestId:actor.requestId,occurredAt:now()});}
 private async outbox(eventType:string,aggregateType:string,aggregateId:string,payload:Row){await this.repository.append("configuration_outbox",{eventType,aggregateType,aggregateId,payloadSafe:safe(payload),status:"PENDING",attempts:0,availableAt:now(),createdAt:now()});}
 private async seedMemoryCatalog(){if(this.repository.configured())return;const integrations=await this.repository.list<SettingsIntegrationConnection>("integration_connections");if(!integrations.length)for(const[code,name,category,ownerDomain]of integrationCatalog)await this.repository.create("integration_connections",{id:"",code,name,category,status:"NOT_CONFIGURED",environment:"DEVELOPMENT",ownerDomain,configuration:{},secretReference:null,lastTestAt:null,lastSuccessAt:null,lastErrorSafe:null,lastLatencyMs:null,enabled:false,createdAt:"",updatedAt:""});const jobs=await this.repository.list<SystemJob>("system_jobs");if(!jobs.length)for(const[code,name,ownerDomain]of jobCatalog)await this.repository.create("system_jobs",{id:"",code,name,ownerDomain,schedule:null,enabled:false,manualRunAllowed:true,status:"DISABLED",lastRunAt:null,nextRunAt:null,durationMs:null,lastErrorSafe:null,createdAt:"",updatedAt:""});}

 async workspace(force=false):Promise<SettingsWorkspace>{
  if(!force&&this.cache&&this.cache.expiresAt>Date.now())return this.cache.data;
  await this.seedMemoryCatalog();
  const[configuration,history,automations,automationRuns,alerts,integrations,webhooks,webhookDeliveries,features,workflows,approvals,jobs,diagnostics,numbering,calendars,departments,teams,_permissions,rolePermissions,templates,supportSla,securityControls,securityGates]=await Promise.all([
   this.repository.list<ConfigurationEntry>("configuration_registry",{},"updated_at"),this.repository.list<ConfigurationHistoryItem>("configuration_history",{},"occurred_at"),this.repository.list<AutomationRule>("automation_rules",{},"updated_at"),this.repository.list<AutomationRun>("automation_runs",{},"created_at"),this.repository.list<AlertRule>("alert_rules",{},"updated_at"),this.repository.list<SettingsIntegrationConnection>("integration_connections",{},"updated_at"),this.repository.list<OutgoingWebhook>("outgoing_webhooks",{},"updated_at"),this.repository.list<Row>("webhook_deliveries",{},"created_at"),this.repository.list<FeatureFlag>("feature_flags",{},"updated_at"),this.repository.list<Row>("workflow_definitions",{},"updated_at"),this.repository.list<Row>("configuration_change_requests",{},"created_at"),this.repository.list<SystemJob>("system_jobs",{},"updated_at"),this.repository.list<SystemDiagnostic>("system_diagnostics",{},"checked_at"),this.repository.list<Row>("numbering_sequences",{},"code",true),this.repository.list<Row>("business_calendars",{},"name",true),this.repository.list<Row>("departments",{},"name",true),this.repository.list<Row>("teams",{},"name",true),this.repository.list<Row>("app_permissions",{},"code",true),this.repository.list<Row>("role_permissions",{},"role",true),this.repository.list<Row>("document_templates",{},"name",true),this.repository.list<Row>("sla_policies",{},"name",true),this.repository.list<Row>("security_controls",{},"control_code",true),this.repository.list<Row>("production_security_gates",{},"evaluated_at"),
  ]);
  const roles=[...new Set(rolePermissions.map(item=>String(item.role)))].sort().map(role=>({role,permissionCount:rolePermissions.filter(item=>item.role===role).length,permissions:rolePermissions.filter(item=>item.role===role).map(item=>item.permissionCode),source:"SECURITY"}));
  const failedRuns=automationRuns.filter(item=>["FAILED","DEAD_LETTER"].includes(item.result));const gate=securityGates[0];
  const reasons:Array<{status:"HEALTHY"|"ATTENTION"|"AT_RISK"|"CRITICAL";label:string;detail:string;href:string}>=[];
  if(integrations.some(item=>item.status==="ERROR"))reasons.push({status:"AT_RISK",label:"Integraciones con error",detail:`${integrations.filter(item=>item.status==="ERROR").length} conexiones requieren intervención.`,href:"/settings/integrations"});
  if(failedRuns.length)reasons.push({status:"AT_RISK",label:"Automatizaciones fallidas",detail:`${failedRuns.length} ejecuciones fallaron o llegaron a dead-letter.`,href:"/settings/automations"});
  if(jobs.some(item=>item.status==="FAILED"))reasons.push({status:"CRITICAL",label:"Jobs críticos fallidos",detail:`${jobs.filter(item=>item.status==="FAILED").length} jobs están fallando.`,href:"/settings/jobs"});
  if(gate?.status==="FAIL")reasons.push({status:"CRITICAL",label:"Production Security Gate",detail:"La última evaluación de seguridad bloquea producción.",href:"/settings/security"});
  if(configuration.filter(item=>item.environment==="PRODUCTION").length===0)reasons.push({status:"ATTENTION",label:"Configuración productiva incompleta",detail:"No existen entradas productivas en el registro tipado.",href:"/settings/company"});
  if(!reasons.length)reasons.push({status:"HEALTHY",label:"Control Plane consistente",detail:"No se detectaron bloqueos con la evidencia disponible.",href:"/settings/history"});
  const health=reasons.some(item=>item.status==="CRITICAL")?"CRITICAL":reasons.some(item=>item.status==="AT_RISK")?"AT_RISK":reasons.some(item=>item.status==="ATTENTION")?"ATTENTION":"HEALTHY";
  const posture=securityControls.length?{status:gate?.status==="FAIL"?"CRITICAL":"ATTENTION",reasons:securityControls.filter(item=>["FAILED","NOT_IMPLEMENTED"].includes(item.status)).slice(0,8).map(item=>({key:String(item.controlCode),label:String(item.title),status:item.status==="FAILED"?"CRITICAL":"ATTENTION",explanation:String(item.evidenceSummary??"Sin evidencia verificada."),href:"/security/compliance"})),evaluatedAt:String(gate?.evaluatedAt??now())}:null;
  const data:SettingsWorkspace={summary:{health,reasons,activeIntegrations:integrations.filter(item=>item.status==="CONNECTED").length,failedIntegrations:integrations.filter(item=>["DEGRADED","ERROR"].includes(item.status)).length,activeAutomations:automations.filter(item=>item.enabled).length,failedAutomations:failedRuns.length,activeAlerts:alerts.filter(item=>item.enabled).length,failedJobs:jobs.filter(item=>item.status==="FAILED").length,featureFlags:features.filter(item=>item.enabled).length,pendingApprovals:approvals.filter(item=>["DRAFT","REVIEW","PENDING"].includes(String(item.status))).length,incompleteConfigurations:configuration.filter(item=>item.value===null||item.value==="").length,failingWebhooks:webhookDeliveries.filter(item=>["FAILED","DEAD_LETTER"].includes(String(item.status))).length,recentCriticalChanges:history.filter(item=>item.occurredAt>new Date(Date.now()-7*86400000).toISOString()&&String(item.namespace).startsWith("security")).length},configuration,history,automations,automationRuns,alerts,integrations,webhooks,webhookDeliveries,features,workflows,approvals,jobs,diagnostics,numbering,calendars,dependencies,canonical:{departments,teams,roles,templates,supportSla,securityPosture:posture as any},generatedAt:now()};
  this.cache={expiresAt:Date.now()+10_000,data};return data;
 }

 async configuration(namespace?:string){const items=await this.repository.list<ConfigurationEntry>("configuration_registry",namespace?{namespace}:{},"updated_at");return items.map(item=>item.valueType==="SECRET_REFERENCE"?{...item,value:item.value?"[VAULT REFERENCE]":null}:item);}
 async getConfiguration(namespace:string,key:string){const item=await this.repository.find<ConfigurationEntry>("configuration_registry",{namespace,key});if(!item)throw new BadRequestException("La configuración solicitada no existe.");return item.valueType==="SECRET_REFERENCE"?{...item,value:item.value?"[VAULT REFERENCE]":null}:item;}
 private validateValue(type:string,value:unknown,schema:Row){if(!valueTypes.includes(type as any))throw new BadRequestException("Tipo de configuración no soportado.");if(type==="BOOLEAN"&&typeof value!=="boolean")throw new BadRequestException("El valor debe ser booleano.");if(type==="INTEGER"&&(!Number.isInteger(value)||typeof value!=="number"))throw new BadRequestException("El valor debe ser entero.");if(type==="DECIMAL"&&typeof value!=="number")throw new BadRequestException("El valor debe ser numérico.");if(type==="STRING"&&typeof value!=="string")throw new BadRequestException("El valor debe ser texto.");if(type==="ENUM"&&(!Array.isArray(schema.allowed)||!schema.allowed.includes(value)))throw new BadRequestException("El valor no pertenece al catálogo permitido.");if(type==="SECRET_REFERENCE"&&(typeof value!=="string"||value.length<8))throw new BadRequestException("Se requiere una referencia válida de Security Vault.");}
 async changeConfiguration(namespace:string,key:string,input:Row,actor:SettingsActor){this.assertNamespaceOwnership(namespace,actor);rejectSecrets(input);const existing=await this.repository.find<ConfigurationEntry>("configuration_registry",{namespace,key}),classification=String(input.classification??existing?.classification??"INTERNAL")as ConfigurationEntry["classification"],valueType=String(input.valueType??existing?.valueType??"STRING")as ConfigurationEntry["valueType"],value=input.value,schema=(input.schema??existing?.schema??{})as Row,reason=required(input.reason,"Motivo");if(protectedInvariants.includes(`${namespace}.${key}` as any)&&value!==true)throw new ForbiddenException("Security invariants no pueden debilitarse desde Configuración.");if(["RESTRICTED","CRITICAL"].includes(classification)||["security","payments","tax","signature","authentication","vault","production"].includes(namespace.toLowerCase()))this.assertAal2(actor);this.validateValue(valueType,value,schema);const before=existing??null,version=(existing?.version??0)+1;const base={namespace,key,value:safe(value),valueType,environment:String(input.environment??existing?.environment??"PRODUCTION")as ConfigurationEntry["environment"],classification,version,effectiveFrom:input.effectiveFrom??now(),description:input.description??existing?.description??null,schema:safe(schema)as Record<string,unknown>,ownerDomain:input.ownerDomain??existing?.ownerDomain??namespace.toUpperCase(),approvalRequired:Boolean(input.approvalRequired??existing?.approvalRequired),updatedBy:actor.userId,updatedAt:now()};
  if(base.approvalRequired){const request=await this.repository.create("configuration_change_requests",{id:"",configurationId:existing?.id??null,namespace,key,beforeValue:safe(existing?.value??null),afterValue:safe(value),valueType,classification,reason,status:"REVIEW",requestedBy:actor.userId,reviewedBy:null,reviewReason:null,effectiveFrom:base.effectiveFrom,createdAt:"",updatedAt:""});await this.audit(actor,"CONFIG_CHANGE_REQUESTED","CONFIGURATION",String(request.id),before,request,reason);this.invalidate();return{pendingApproval:true,request};}
  const result=existing?await this.repository.update<ConfigurationEntry>("configuration_registry",existing.id,base):await this.repository.create<ConfigurationEntry>("configuration_registry",{id:"",...base}as ConfigurationEntry);await this.repository.create("configuration_versions",{id:"",configurationId:result.id,version,value:safe(value),effectiveFrom:base.effectiveFrom,createdBy:actor.userId,changeReason:reason,createdAt:""});await this.repository.create("configuration_history",{id:"",configurationId:result.id,namespace,key,action:"CONFIG_CHANGED",beforeValue:safe(existing?.value??null),afterValue:safe(value),actorId:actor.userId,actorRole:actor.role,reason,approvalId:null,version,occurredAt:now()});await this.audit(actor,namespace==="security"?"SECURITY_POLICY_CHANGED":"CONFIG_CHANGED","CONFIGURATION",result.id,before,result,reason);await this.outbox("CONFIG_CHANGED","CONFIGURATION",result.id,{namespace,key,version});this.invalidate();return result;
 }
 async approve(id:string,input:Row,actor:SettingsActor){this.assertAal2(actor);const request=await this.repository.get<Row>("configuration_change_requests",id);if(request.requestedBy===actor.userId)throw new ForbiddenException("La segregación de funciones impide autoaprobar este cambio.");if(request.status!=="REVIEW")throw new ConflictException("La solicitud ya fue resuelta.");await this.repository.update("configuration_change_requests",id,{status:"APPROVED",reviewedBy:actor.userId,reviewReason:required(input.reason,"Motivo de aprobación")});const result=await this.changeConfiguration(request.namespace,request.key,{value:request.afterValue,valueType:request.valueType,classification:request.classification,reason:`Aprobado: ${input.reason}`,approvalRequired:false,effectiveFrom:request.effectiveFrom},actor);await this.repository.update("configuration_change_requests",id,{status:"APPLIED",appliedAt:now()});return result;}
 async rollback(id:string,input:Row,actor:SettingsActor){this.assertAal2(actor);const current=await this.repository.get<ConfigurationEntry>("configuration_registry",id),versions=await this.repository.list<Row>("configuration_versions",{configurationId:id},"version"),target=versions.find(item=>item.version===Number(input.version))??versions[1];if(!target)throw new BadRequestException("No existe una versión anterior apta para rollback.");return this.changeConfiguration(current.namespace,current.key,{value:target.value,valueType:current.valueType,classification:current.classification,environment:current.environment,schema:current.schema,reason:required(input.reason,"Motivo del rollback"),approvalRequired:false},actor);}

 async createAutomation(input:Row,actor:SettingsActor){const eventType=required(input.eventType,"Evento");if(!businessEvents.includes(eventType as any))throw new BadRequestException("El evento no pertenece al catálogo Business Events.");const actions=(input.actions??[])as Row[];if(!actions.length||actions.some(item=>!automationActions.includes(item.type as any)))throw new BadRequestException("La automatización contiene una acción no permitida.");const conditions=(input.conditions??[])as Row[];if(conditions.some(item=>!conditionOperators.includes(item.operator as any)))throw new BadRequestException("La automatización contiene un operador no permitido.");const rule=await this.repository.create<AutomationRule>("automation_rules",{id:"",name:required(input.name,"Nombre"),description:input.description?String(input.description):null,eventType,conditions:safe(conditions)as any,actions:safe(actions)as any,priority:Number(input.priority)||100,enabled:false,dryRun:input.dryRun!==false,environment:String(input.environment??"PRODUCTION"),version:1,maxDepth:Math.min(10,Math.max(1,Number(input.maxDepth)||3)),retryPolicy:{maxAttempts:Math.min(10,Math.max(1,Number(input.retryPolicy?.maxAttempts)||3)),backoffSeconds:Math.max(1,Number(input.retryPolicy?.backoffSeconds)||30)},createdBy:actor.userId,updatedBy:actor.userId,createdAt:"",updatedAt:""});await this.repository.create("automation_rule_versions",{id:"",ruleId:rule.id,version:1,snapshot:safe(rule),createdBy:actor.userId,reason:required(input.reason??"Creación inicial","Motivo"),createdAt:""});await this.audit(actor,"AUTOMATION_CREATED","AUTOMATION",rule.id,null,rule,String(input.reason??"Creación inicial"));this.invalidate();return rule;}
 async updateAutomation(id:string,input:Row,actor:SettingsActor){const current=await this.repository.get<AutomationRule>("automation_rules",id),version=current.version+1,updated=await this.repository.update<AutomationRule>("automation_rules",id,{...safe(input)as any,id:current.id,version,enabled:current.enabled,updatedBy:actor.userId});await this.repository.create("automation_rule_versions",{id:"",ruleId:id,version,snapshot:safe(updated),createdBy:actor.userId,reason:required(input.reason,"Motivo"),createdAt:""});await this.audit(actor,"AUTOMATION_CHANGED","AUTOMATION",id,current,updated,input.reason);this.invalidate();return updated;}
 private matches(rule:AutomationRule,event:Row){return rule.eventType===event.eventType&&rule.conditions.every(condition=>{const actual=event.payload?.[condition.field]??event[condition.field];if(condition.operator==="equals")return actual===condition.value;if(condition.operator==="not_equals")return actual!==condition.value;if(condition.operator==="in")return Array.isArray(condition.value)&&condition.value.includes(actual);if(condition.operator==="contains")return String(actual??"").includes(String(condition.value));if(condition.operator==="exists")return condition.value?actual!==undefined&&actual!==null:actual===undefined||actual===null;if(condition.operator==="greater_than")return Number(actual)>Number(condition.value);if(condition.operator==="less_than")return Number(actual)<Number(condition.value);return false;});}
 async testAutomation(id:string,input:Row,actor:SettingsActor){const rule=await this.repository.get<AutomationRule>("automation_rules",id),event={eventType:input.eventType??rule.eventType,payload:safe(input.payload??{}),correlationId:input.correlationId??randomUUID(),causationId:input.causationId??null,depth:Number(input.depth)||0},started=Date.now(),loop=event.depth>=rule.maxDepth,matched=!loop&&this.matches(rule,event),actions=matched?rule.actions.map(action=>({...action,wouldExecute:true})):[];const run=await this.repository.create<AutomationRun>("automation_runs",{id:"",ruleId:id,eventId:null,correlationId:event.correlationId,causationId:event.causationId,depth:event.depth,matched,actions,result:loop?"SKIPPED_LOOP":"DRY_RUN",durationMs:Date.now()-started,errorSafe:null,createdAt:""});await this.audit(actor,"AUTOMATION_TESTED","AUTOMATION",id,null,run,String(input.reason??"Dry run explícito"));this.invalidate();return run;}
 async toggleAutomation(id:string,enabled:boolean,actor:SettingsActor,reason:string){this.assertAal2(actor);const current=await this.repository.get<AutomationRule>("automation_rules",id),next=await this.repository.update<AutomationRule>("automation_rules",id,{enabled});await this.audit(actor,enabled?"AUTOMATION_ENABLED":"AUTOMATION_DISABLED","AUTOMATION",id,current,next,reason);await this.outbox(enabled?"AUTOMATION_ENABLED":"AUTOMATION_DISABLED","AUTOMATION",id,{});this.invalidate();return next;}

 async createAlert(input:Row,actor:SettingsActor){const rule=await this.repository.create<AlertRule>("alert_rules",{id:"",name:required(input.name,"Nombre"),source:required(input.source,"Fuente"),eventType:required(input.eventType,"Evento"),severityMin:input.severityMin??"MEDIUM",conditions:safe(input.conditions??[])as Row[],recipients:(input.recipients??[])as string[],channels:(input.channels??["IN_APP"])as string[],quietHours:safe(input.quietHours??{})as Row,dedupWindowMinutes:Math.max(1,Number(input.dedupWindowMinutes)||15),escalationPolicyId:input.escalationPolicyId??null,acknowledgeRequired:Boolean(input.acknowledgeRequired),criticalOverride:Boolean(input.criticalOverride),enabled:false,createdAt:"",updatedAt:""});await this.audit(actor,"ALERT_RULE_CHANGED","ALERT_RULE",rule.id,null,rule,String(input.reason??"Creación"));this.invalidate();return rule;}
 async updateAlert(id:string,input:Row,actor:SettingsActor){const current=await this.repository.get<AlertRule>("alert_rules",id),next=await this.repository.update<AlertRule>("alert_rules",id,safe(input)as Partial<AlertRule>);await this.audit(actor,"ALERT_RULE_CHANGED","ALERT_RULE",id,current,next,required(input.reason,"Motivo"));this.invalidate();return next;}
 async testAlert(id:string,input:Row,actor:SettingsActor){const rule=await this.repository.get<AlertRule>("alert_rules",id),preview={test:true,eventType:rule.eventType,severity:input.severity??rule.severityMin,recipientResolvers:rule.recipients,channels:rule.channels.filter(channel=>["IN_APP","REALTIME","EMAIL","WEB_PUSH"].includes(channel)),dedupWindowMinutes:rule.dedupWindowMinutes,escalationPolicyId:rule.escalationPolicyId,acknowledgeRequired:rule.acknowledgeRequired};await this.audit(actor,"ALERT_RULE_TESTED","ALERT_RULE",id,null,preview,String(input.reason??"Test explícito"));return preview;}
 async toggleAlert(id:string,enabled:boolean,actor:SettingsActor,reason:string){this.assertAal2(actor);const current=await this.repository.get<AlertRule>("alert_rules",id),next=await this.repository.update<AlertRule>("alert_rules",id,{enabled});await this.audit(actor,"ALERT_RULE_CHANGED","ALERT_RULE",id,current,next,reason);this.invalidate();return next;}

 async configureIntegration(id:string,input:Row,actor:SettingsActor){this.assertAal2(actor);rejectSecrets(input);const current=await this.repository.get<SettingsIntegrationConnection>("integration_connections",id),configuration=safe(input.configuration??{})as Row,secretReference=input.secretReference?required(input.secretReference,"Referencia Vault"):current.secretReference,next=await this.repository.update<SettingsIntegrationConnection>("integration_connections",id,{configuration,secretReference,status:Object.keys(configuration).length||secretReference?"CONFIGURED":"NOT_CONFIGURED",enabled:false});await this.audit(actor,"INTEGRATION_CONFIGURED","INTEGRATION",id,current,{...next,secretReference:secretReference?"[VAULT REFERENCE]":null},required(input.reason,"Motivo"));this.invalidate();return{...next,secretReference:secretReference?"[VAULT REFERENCE]":null};}
 async testIntegration(id:string,actor:SettingsActor){const current=await this.repository.get<SettingsIntegrationConnection>("integration_connections",id),started=Date.now();let status:SettingsIntegrationConnection["status"]="ERROR",message="No existe un adapter de prueba configurado.";if(current.code==="SUPABASE"&&this.repository.supabase){const{error}=await this.repository.supabase.from("configuration_registry").select("id",{head:true,count:"exact"}).limit(1);status=error?"ERROR":"CONNECTED";message=error?"Supabase no respondió de forma válida.":"Conexión Supabase verificada.";}else if(!current.configuration||(!Object.keys(current.configuration).length&&!current.secretReference)){status="NOT_CONFIGURED";message="La integración requiere metadata y/o una referencia de Vault.";}const stamp=now(),latency=Date.now()-started,next=await this.repository.update<SettingsIntegrationConnection>("integration_connections",id,{status,lastTestAt:stamp,lastSuccessAt:status==="CONNECTED"?stamp:current.lastSuccessAt,lastErrorSafe:status==="CONNECTED"?null:message,lastLatencyMs:latency});await this.repository.create("integration_health_checks",{id:"",integrationId:id,status,messageSafe:message,latencyMs:latency,checkedAt:stamp});await this.audit(actor,"INTEGRATION_TESTED","INTEGRATION",id,null,{status,latency},"Prueba de conexión explícita");this.invalidate();return{...next,secretReference:next.secretReference?"[VAULT REFERENCE]":null,message};}
 async toggleIntegration(id:string,enabled:boolean,actor:SettingsActor,reason:string){this.assertAal2(actor);const current=await this.repository.get<SettingsIntegrationConnection>("integration_connections",id);if(enabled&&current.status!=="CONNECTED")throw new ConflictException("Solo una integración con conexión verificada puede habilitarse.");const next=await this.repository.update<SettingsIntegrationConnection>("integration_connections",id,{enabled,status:enabled?"CONNECTED":"DISABLED"});await this.audit(actor,enabled?"INTEGRATION_ENABLED":"INTEGRATION_DISABLED","INTEGRATION",id,current,next,reason);await this.outbox(enabled?"INTEGRATION_ENABLED":"INTEGRATION_DISABLED","INTEGRATION",id,{});this.invalidate();return next;}

 async createWebhook(input:Row,actor:SettingsActor){this.assertAal2(actor);rejectSecrets(input);const url=required(input.url,"URL");if(!/^https:\/\//i.test(url))throw new BadRequestException("Los webhooks requieren HTTPS.");const hook=await this.repository.create<OutgoingWebhook>("outgoing_webhooks",{id:"",name:required(input.name,"Nombre"),url,events:(input.events??[])as string[],secretReference:required(input.secretReference,"Referencia Vault"),enabled:false,retryPolicy:{maxAttempts:Math.min(10,Math.max(1,Number(input.retryPolicy?.maxAttempts)||5)),backoffSeconds:Math.max(5,Number(input.retryPolicy?.backoffSeconds)||30)},status:"CONFIGURED",createdAt:"",updatedAt:""});await this.audit(actor,"WEBHOOK_CHANGED","WEBHOOK",hook.id,null,{...hook,secretReference:"[VAULT REFERENCE]"},String(input.reason??"Creación"));this.invalidate();return hook;}
 async updateWebhook(id:string,input:Row,actor:SettingsActor){rejectSecrets(input);const current=await this.repository.get<OutgoingWebhook>("outgoing_webhooks",id),next=await this.repository.update<OutgoingWebhook>("outgoing_webhooks",id,safe(input)as Partial<OutgoingWebhook>);await this.audit(actor,"WEBHOOK_CHANGED","WEBHOOK",id,current,next,required(input.reason,"Motivo"));this.invalidate();return next;}
 async testWebhook(id:string,actor:SettingsActor){const hook=await this.repository.get<OutgoingWebhook>("outgoing_webhooks",id),deliveryId=randomUUID(),delivery=await this.repository.create("webhook_deliveries",{id:deliveryId,webhookId:id,eventType:"ZYTERON_WEBHOOK_TEST",deliveryId,status:"PENDING",attempts:0,responseCode:null,durationMs:null,errorSafe:null,nextAttemptAt:now(),createdAt:""});await this.outbox("WEBHOOK_TEST_REQUESTED","WEBHOOK",id,{deliveryId,test:true,destinationHost:new URL(hook.url).host});await this.audit(actor,"WEBHOOK_TEST_REQUESTED","WEBHOOK",id,null,delivery,"Test explícito encolado mediante outbox");this.invalidate();return delivery;}

 async createFeature(input:Row,actor:SettingsActor){const flag=await this.repository.create<FeatureFlag>("feature_flags",{id:"",key:required(input.key,"Key").toLowerCase().replace(/[^a-z0-9._-]/g,"_"),description:required(input.description,"Descripción"),enabled:false,environment:String(input.environment??"PRODUCTION"),scope:input.scope??"GLOBAL",rollout:Math.min(100,Math.max(0,Number(input.rollout)||0)),killSwitch:Boolean(input.killSwitch),createdBy:actor.userId,createdAt:"",updatedAt:""});await this.audit(actor,"FEATURE_FLAG_CHANGED","FEATURE_FLAG",flag.id,null,flag,String(input.reason??"Creación"));this.invalidate();return flag;}
 async updateFeature(id:string,input:Row,actor:SettingsActor){const current=await this.repository.get<FeatureFlag>("feature_flags",id),next=await this.repository.update<FeatureFlag>("feature_flags",id,safe(input)as Partial<FeatureFlag>);await this.audit(actor,"FEATURE_FLAG_CHANGED","FEATURE_FLAG",id,current,next,required(input.reason,"Motivo"));this.invalidate();return next;}
 async toggleFeature(id:string,enabled:boolean,actor:SettingsActor,reason:string){this.assertAal2(actor);const current=await this.repository.get<FeatureFlag>("feature_flags",id),next=await this.repository.update<FeatureFlag>("feature_flags",id,{enabled});await this.audit(actor,"FEATURE_FLAG_CHANGED","FEATURE_FLAG",id,current,next,reason);await this.outbox("FEATURE_FLAG_CHANGED","FEATURE_FLAG",id,{key:next.key,enabled});this.invalidate();return next;}

 async runDiagnostics(actor:SettingsActor){const checks:Array<{service:string;run:()=>Promise<{status:SystemDiagnostic["status"];message:string}>}>=[{service:"API",run:async()=>({status:"HEALTHY",message:"Proceso API operativo."})},{service:"SUPABASE",run:async()=>{if(!this.repository.supabase)return{status:"NOT_CONFIGURED",message:"Supabase no está configurado."};const{error}=await this.repository.supabase.from("configuration_registry").select("id",{head:true,count:"exact"}).limit(1);return{status:error?"ERROR":"HEALTHY",message:error?"La consulta de salud falló.":"Base de datos accesible."};}},{service:"REALTIME",run:async()=>({status:process.env.SUPABASE_URL?"HEALTHY":"NOT_CONFIGURED",message:process.env.SUPABASE_URL?"Endpoint Supabase configurado; la suscripción se valida desde cliente.":"Realtime no configurado."})},{service:"STORAGE",run:async()=>({status:this.repository.supabase?"HEALTHY":"NOT_CONFIGURED",message:this.repository.supabase?"Cliente Storage disponible.":"Storage no configurado."})}];const results:SystemDiagnostic[]=[];for(const check of checks){const started=Date.now();try{const outcome=await check.run();results.push(await this.repository.create<SystemDiagnostic>("system_diagnostics",{id:"",service:check.service,...outcome,latencyMs:Date.now()-started,checkedAt:now()}));}catch{results.push(await this.repository.create<SystemDiagnostic>("system_diagnostics",{id:"",service:check.service,status:"ERROR",latencyMs:Date.now()-started,message:"El check falló sin exponer detalles internos.",checkedAt:now()}));}}await this.audit(actor,"DIAGNOSTICS_RUN","SYSTEM",null,null,{services:results.map(item=>({service:item.service,status:item.status}))},"Diagnóstico manual");this.invalidate();return results;}
 async runJob(id:string,actor:SettingsActor){this.assertAal2(actor);const job=await this.repository.get<SystemJob>("system_jobs",id);if(!job.manualRunAllowed)throw new ForbiddenException("Este job no permite ejecución manual.");if(!job.enabled)throw new ConflictException("Habilita el job antes de ejecutarlo manualmente.");if(this.locks.has(id)||job.status==="RUNNING")throw new ConflictException("El job ya tiene una ejecución activa.");this.locks.add(id);try{const run=await this.repository.create("system_job_runs",{id:"",jobId:id,status:"QUEUED",requestedBy:actor.userId,startedAt:null,finishedAt:null,durationMs:null,errorSafe:null,createdAt:""});await this.repository.update<SystemJob>("system_jobs",id,{status:"RUNNING",lastRunAt:now()});await this.outbox("SYSTEM_JOB_REQUESTED","SYSTEM_JOB",id,{runId:run.id,code:job.code});await this.audit(actor,"SYSTEM_JOB_REQUESTED","SYSTEM_JOB",id,null,run,"Ejecución manual");this.invalidate();return run;}finally{this.locks.delete(id);}}
 async toggleJob(id:string,enabled:boolean,actor:SettingsActor,reason:string){this.assertAal2(actor);const current=await this.repository.get<SystemJob>("system_jobs",id),next=await this.repository.update<SystemJob>("system_jobs",id,{enabled,status:enabled?"IDLE":"DISABLED"});await this.audit(actor,"SYSTEM_JOB_CHANGED","SYSTEM_JOB",id,current,next,reason);this.invalidate();return next;}
 async history(){return this.repository.list<ConfigurationHistoryItem>("configuration_history",{},"occurred_at");}
}
