import { BadRequestException, ConflictException, Injectable, NotFoundException, Optional } from "@nestjs/common";
import type { ClientContract, ContractStatus } from "@zyteron/contracts";
import { ClientEventsService } from "../clients/client-events.service.js";
import { pagination } from "../domain/server-supabase.js";
import { DocumentService, DocumentSignatureService, type DocumentActor } from "../documents/documents.service.js";
import { EnterpriseSignatureProvider } from "../documents/documents.providers.js";
import { chileanContractTemplates, contractTemplateByCode } from "./contract-template-catalog.js";
import { ContractDocumentService } from "./contract-document.service.js";
import { validateContract,type ContractInput } from "./contracts.dto.js";
import { ContractsRepository } from "./contracts.repository.js";

const transitions:Record<ContractStatus,ContractStatus[]>={DRAFT:["IN_REVIEW","CANCELLED"],IN_REVIEW:["DRAFT","PENDING_SIGNATURE","ACTIVE","CANCELLED"],PENDING_SIGNATURE:["CANCELLED"],SIGNED:["ACTIVE","CANCELLED"],ACTIVE:["EXPIRING","TERMINATED"],EXPIRING:["ACTIVE","EXPIRED","TERMINATED"],EXPIRED:[],TERMINATED:[],CANCELLED:[]};
const empty=(value:unknown)=>value===null||value===undefined||(typeof value==="string"&&!value.trim())||(Array.isArray(value)&&!value.length);
const at=(source:Record<string,unknown>,key:string)=>key.split(".").reduce<unknown>((value,part)=>value&&typeof value==="object"?(value as Record<string,unknown>)[part]:undefined,source);

export type ContractActor = DocumentActor;

@Injectable()
export class ContractsService{
  constructor(private readonly repository:ContractsRepository,private readonly events:ClientEventsService,@Optional()private readonly documentRenderer?:ContractDocumentService,@Optional()private readonly documents?:DocumentService,@Optional()private readonly signatures?:DocumentSignatureService,@Optional()private readonly signatureProvider?:EnterpriseSignatureProvider){}
  types(){return this.repository.types();}
  templates(){return chileanContractTemplates.map(item=>({...item,body:undefined,variableCount:item.variables.length}));}
  template(code:string){const item=contractTemplateByCode(code);if(!item)throw new NotFoundException("Plantilla contractual no encontrada.");return item;}
  context(clientId?:string){return this.repository.builderContext(clientId);}
  list(query:Record<string,string|undefined>){return this.repository.list({...query,...pagination(query)});}
  async get(id:string){const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");const[versions,authorityReviews,copyReceipts]=await Promise.all([this.repository.versions(id),this.repository.reviews(id),this.repository.receipts(id)]);return{...item,versions,authorityReviews,copyReceipts,signatureConfigured:Boolean(this.signatureProvider?.configured),validation:this.validateBuilder(item)};}

  async create(input:ContractInput){
    const normalized=validateContract(input);const context=await this.repository.builderContext(normalized.clientId);
    if(context.client&&normalized.projectId&&!context.projects.some((item:any)=>item.id===normalized.projectId))throw new BadRequestException("El proyecto no pertenece al cliente seleccionado.");
    const quote=normalized.quoteId?context.quotes.find((item:any)=>item.id===normalized.quoteId):null;if(context.client&&normalized.quoteId&&!quote)throw new BadRequestException("La cotización no pertenece al cliente o no está aceptada.");
    const snapshot={capturedAt:new Date().toISOString(),client:context.client,project:context.projects.find((item:any)=>item.id===normalized.projectId)??null,quote:quote??null};
    const item=await this.repository.create({...normalized,sourceSnapshot:snapshot});await this.events.publish(item.clientId,"CONTRACT_CREATED","Contrato creado",`${item.contractNumber} · ${item.name}`);return item;
  }

  async update(id:string,patch:Partial<ContractInput>){const item=await this.repository.update(id,patch);await this.events.publish(item.clientId,"CONTRACT_UPDATED","Contrato actualizado",item.contractNumber);return item;}
  async saveBuilder(id:string,body:{templateCodes?:string[];builderValues?:Record<string,unknown>;projectId?:string|null;quoteId?:string|null;quoteVersionId?:string|null;independentReason?:string|null}){
    const current=await this.repository.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");const selected=body.templateCodes??current.templateCodes??[];
    if(!selected.includes("ZT-PROYECTO-CL")||!selected.includes("ZT-CONDICIONES-CL"))throw new BadRequestException("El contrato base y sus condiciones particulares son obligatorios.");
    if(selected.some(code=>!contractTemplateByCode(code)))throw new BadRequestException("Hay una plantilla contractual desconocida.");
    if(body.projectId||body.quoteId){const context=await this.repository.builderContext(current.clientId);if(body.projectId&&!context.projects.some((item:any)=>item.id===body.projectId))throw new BadRequestException("El proyecto pertenece a otro cliente.");if(body.quoteId&&!context.quotes.some((item:any)=>item.id===body.quoteId))throw new BadRequestException("La cotización pertenece a otro cliente o no está aceptada.");}
    const item=await this.repository.builderPatch(id,{...body,templateCodes:selected,legalReviewStatus:"REQUIRED",approvalStatus:"DRAFT"});await this.events.publish(item.clientId,"CONTRACT_UPDATED","Borrador contractual actualizado",item.contractNumber);return{item,validation:this.validateBuilder(item)};
  }

  async preview(id:string){const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");const preview=this.renderer().preview(item);return{...preview,validation:this.validateBuilder(item)};}
  async previewPdf(id:string){const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");const rendered=await this.renderer().render(item);return{filename:rendered.filename,mimeType:"application/pdf",hash:rendered.hash,contentBase64:rendered.bytes.toString("base64"),unresolved:rendered.unresolved,watermark:"BORRADOR — REVISIÓN LEGAL REQUERIDA"};}
  validate(id:string){return this.repository.get(id).then(item=>{if(!item)throw new NotFoundException("Contrato no encontrado.");return this.validateBuilder(item);});}

  async approve(id:string,body:{legalReviewConfirmed?:boolean;comment?:string},actor:ContractActor){
    if(!body.legalReviewConfirmed)throw new BadRequestException("Debes confirmar explícitamente la revisión legal antes de aprobar.");const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");if(item.frozenAt)throw new ConflictException("La versión ya está congelada.");const validation=this.validateBuilder(item);if(!validation.valid)throw new BadRequestException({message:"El contrato aún no puede aprobarse.",errors:validation.errors});
    if(!this.documents)throw new ConflictException("El dominio documental no está disponible.");const rendered=await this.renderer().render(item);if(rendered.unresolved.length)throw new BadRequestException(`Existen variables sin resolver: ${rendered.unresolved.join(", ")}.`);
    const central=await this.documents.create({title:`${item.contractNumber} · ${item.name}`,description:"Versión contractual original aprobada y congelada.",typeCode:"CONTRACT",classification:"CONFIDENTIAL",links:[{linkType:"CLIENT",linkedId:item.clientId,primaryLink:true},{linkType:"CONTRACT",linkedId:item.id},{...(item.projectId?{linkType:"PROJECT",linkedId:item.projectId}:{} as any)},{...(item.quoteId?{linkType:"QUOTE",linkedId:item.quoteId}:{} as any)}].filter(link=>link.linkType)},actor);
    await this.documents.addVersion(central.id,{filename:rendered.filename,mimeType:"application/pdf",base64:rendered.bytes.toString("base64"),changeSummary:`Contrato ${item.contractNumber} aprobado internamente. ${body.comment?.trim()||""}`},actor);await this.documents.approveGenerated(central.id,actor);
    const approved=await this.repository.approveBuilder(id,{hash:rendered.hash,documentId:central.id,actorId:actor.userId});await this.events.publish(item.clientId,"CONTRACT_APPROVED","Versión contractual aprobada y congelada",item.contractNumber);return{item:approved,documentId:central.id,hash:rendered.hash};
  }

  async requestSignature(id:string,body:{signers?:Array<{name:string;email:string;order:number}>;callbackUrl?:string|null},actor:ContractActor){
    const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");if(!item.frozenAt||item.approvalStatus!=="APPROVED"||!item.originalDocumentId)throw new ConflictException("Aprueba y congela la versión contractual antes de enviarla a firma.");const reviews=await this.repository.reviews(id),verified=new Set(reviews.filter(review=>review.status==="VERIFIED").map(review=>review.party));if(!verified.has("ZYTERON")||!verified.has("CLIENT"))throw new ConflictException("Verifica las facultades de representación de ambas Partes antes de enviar a firma.");if(!this.signatures)throw new ConflictException("Proveedor de firma electrónica no configurado.");const request=await this.signatures.request(item.originalDocumentId,body,actor);const updated=await this.repository.signatureRequested(id,{id:request.id,provider:request.provider});await this.events.publish(item.clientId,"CONTRACT_SIGNATURE_REQUESTED","Contrato enviado a firma electrónica",item.contractNumber);return{item:updated,request};
  }

  async recordAuthorityReview(id:string,body:{party?:string;representativeName?:string;representativeRut?:string|null;authorityBasis?:string;evidenceDocumentId?:string|null;status?:string},actor:ContractActor){const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");if(!["ZYTERON","CLIENT"].includes(body.party??""))throw new BadRequestException("Parte inválida.");if(!body.representativeName?.trim()||!body.authorityBasis?.trim())throw new BadRequestException("Nombre del representante y fundamento de sus facultades son obligatorios.");if(body.status==="VERIFIED"&&actor.role!=="GERENTE_GENERAL")throw new BadRequestException("Solo Gerencia puede verificar facultades de representación.");return this.repository.recordReview(id,{party:body.party!,representativeName:body.representativeName,representativeRut:body.representativeRut,authorityBasis:body.authorityBasis,evidenceDocumentId:body.evidenceDocumentId,status:body.status},actor.userId);}
  async recordCopyReceipt(id:string,body:{recipientType?:string;recipientName?:string;recipientEmail?:string;documentId?:string|null;deliveryReference?:string|null;status?:string}){const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");if(!["ZYTERON","CLIENT"].includes(body.recipientType??"")||!body.recipientName?.trim()||!body.recipientEmail?.includes("@"))throw new BadRequestException("Completa un destinatario válido para la copia íntegra.");return this.repository.recordReceipt(id,{recipientType:body.recipientType!,recipientName:body.recipientName,recipientEmail:body.recipientEmail,documentId:body.documentId,deliveryReference:body.deliveryReference,status:body.status});}
  async verifySignature(id:string,actor:ContractActor){const item=await this.repository.get(id);if(!item)throw new NotFoundException("Contrato no encontrado.");if(!item.signatureRequestId||!this.signatures)throw new ConflictException("No existe una solicitud de firma verificable.");const request=await this.signatures.status(item.signatureRequestId,actor);if(request.status!=="COMPLETED")return{item,request,obligations:[]};const signed=await this.repository.signatureCompleted(id,request.evidence??{}),obligations=await this.repository.createObligationDrafts(signed);await this.events.publish(item.clientId,"CONTRACT_SIGNED","Firma verificada por proveedor; obligaciones creadas solo como borrador",item.contractNumber);return{item:signed,request,obligations};}

  async archive(id:string){const item=await this.repository.archive(id);await this.events.publish(item.clientId,"CONTRACT_CANCELLED","Contrato archivado",item.contractNumber);return item;}
  async transition(id:string,status:ContractStatus){const current=await this.repository.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");if(status==="SIGNED")throw new BadRequestException("El estado SIGNED solo puede provenir de evidencia verificada del proveedor de firma.");if(!transitions[current.status].includes(status))throw new BadRequestException(`No se puede pasar de ${current.status} a ${status}.`);const item=await this.repository.transition(id,status);await this.events.publish(item.clientId,status==="ACTIVE"?"CONTRACT_ACTIVATED":"CONTRACT_UPDATED",`Contrato ${status.toLowerCase()}`,item.contractNumber);return item;}
  activate(id:string){return this.transition(id,"ACTIVE");}
  async uploadUrl(id:string,file:{name:string;type:string}){const contract=await this.repository.get(id);if(!contract)throw new NotFoundException("Contrato no encontrado.");return this.repository.createUploadUrl(contract,file);}
  async completeUpload(id:string,input:{path:string;title:string;mimeType:string;sizeBytes:number;documentHash?:string;versionKind?:"CONTRACT"|"ANNEX"}){const contract=await this.repository.get(id);if(!contract)throw new NotFoundException("Contrato no encontrado.");const version=await this.repository.completeUpload(contract,input);await this.events.publish(contract.clientId,"CONTRACT_DOCUMENT_ADDED","Documento contractual adjuntado",input.title);return version;}
  async documentUrl(id:string,versionId:string){const contract=await this.repository.get(id);if(!contract)throw new NotFoundException("Contrato no encontrado.");const version=(await this.repository.versions(id)).find(item=>item.id===versionId);if(!version?.storagePath)throw new NotFoundException("Documento contractual no encontrado.");return{url:await this.repository.signedDocumentUrl(version.storagePath),expiresIn:300};}

  validateBuilder(item:ClientContract){
    const errors:string[]=[],warnings:string[]=[];const selected=item.templateCodes??[];if(!item.projectId)errors.push("Selecciona un proyecto del mismo cliente.");if(!item.quoteId&&!item.independentReason?.trim())errors.push("Asocia una cotización aceptada o justifica el contrato independiente.");if(!selected.includes("ZT-PROYECTO-CL")||!selected.includes("ZT-CONDICIONES-CL"))errors.push("Faltan el contrato base o las condiciones particulares.");
    const variables=[...new Map(chileanContractTemplates.filter(template=>selected.includes(template.code)).flatMap(template=>template.variables).map(variable=>[variable.key,variable])).values()];for(const variable of variables){const value=variable.key==="contrato.numero"?item.contractNumber:at(item.builderValues??{},variable.key);if(variable.required&&empty(value))errors.push(`Completa ${variable.label}.`);}
    const mode=String(at(item.builderValues??{},"pi.modalidad")??"").toUpperCase();if(!["A","B","C"].includes(mode))errors.push("Selecciona exactamente una modalidad de propiedad intelectual: A, B o C.");if(Math.abs(item.subtotal+item.tax-item.total)>.01)errors.push("Subtotal, impuestos y total no coinciden.");if(!item.startDate)warnings.push("La vigencia contractual aún no tiene fecha o condición de inicio estructurada.");if(selected.includes("ZT-RECURRENTES-CL"))warnings.push("Los servicios recurrentes permanecerán como borrador hasta acreditar su condición de activación.");warnings.push("Las plantillas requieren revisión legal profesional; el sistema no garantiza validez jurídica.");return{valid:errors.length===0,errors,warnings,required:variables.length,completed:variables.length-errors.filter(error=>error.startsWith("Completa ")).length};
  }
  private renderer(){return this.documentRenderer??new ContractDocumentService();}
}
