import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { ClientContract, ContractStatus, ContractVersion } from "@zyteron/contracts";
import { cleanSearch, createServerSupabase, pageBounds } from "../domain/server-supabase.js";
import type { ContractInput } from "./contracts.dto.js";

export const CONTRACT_BUILDER_CONTACT_COLUMNS="id,name,email,position,contact_types,is_primary";

@Injectable()
export class ContractsRepository {
  private readonly supabase=createServerSupabase();
  private readonly memory=new Map<string,ClientContract>();
  private readonly authorityReviews:Array<Record<string,any>>=[];
  private readonly copyReceiptRows:Array<Record<string,any>>=[];
  private readonly obligationRows:Array<Record<string,any>>=[];

  async types(){
    if(!this.supabase)return[{code:"DESARROLLO",name:"Desarrollo"},{code:"MANTENCION",name:"Mantención"},{code:"SOPORTE",name:"Soporte"},{code:"HOSTING",name:"Hosting"},{code:"SEO",name:"SEO"},{code:"SOFTWARE",name:"Software"},{code:"CONSULTORIA",name:"Consultoría"},{code:"SERVICIO_RECURRENTE",name:"Servicio recurrente"},{code:"OTRO",name:"Otro"}];
    const{data,error}=await this.supabase.from("contract_type_catalog").select("code,name").eq("active",true).order("name");if(error)throw error;return data??[];
  }

  async builderContext(clientId?:string){
    if(!this.supabase)return{client:null,company:{company_legal_name:"Zyteron SpA",company_rut:"78.398.774-0",company_address:"Santiago, Chile",company_city:"Santiago"},projects:[],quotes:[],contacts:[]};
    const[client,projects,quotes,contacts,company]=await Promise.all([
      clientId?this.supabase.from("clients").select("*").eq("id",clientId).maybeSingle():Promise.resolve(null),
      clientId?this.supabase.from("projects").select("id,project_number,name,client_id,quote_id,scope,status,planned_start_date,target_date").eq("client_id",clientId).is("archived_at",null).order("updated_at",{ascending:false}):Promise.resolve(null),
      clientId?this.supabase.from("quotes").select("id,quote_number,version,status,client_id,currency,net_amount,tax_amount,total_amount,accepted_at,document_id,document_hash,payment_terms,commercial_terms,notes").eq("client_id",clientId).in("status",["ACCEPTED","CONVERTED"]).order("updated_at",{ascending:false}):Promise.resolve(null),
      clientId?this.supabase.from("client_contacts").select(CONTRACT_BUILDER_CONTACT_COLUMNS).eq("client_id",clientId).is("archived_at",null):Promise.resolve(null),
      this.supabase.from("finance_settings").select("company_legal_name,company_rut,company_address,company_commune,company_city,company_email").eq("id",true).maybeSingle(),
    ]);
    for(const result of [client,projects,quotes,contacts,company])if(result?.error)throw result.error;
    return{client:client?.data??null,company:company?.data??null,projects:projects?.data??[],quotes:quotes?.data??[],contacts:contacts?.data??[]};
  }

  async list(input:Record<string,string|number|undefined>&{page:number;pageSize:number}){
    if(!this.supabase)return this.memoryList(input);
    const {from,to}=pageBounds(input.page,input.pageSize);const search=cleanSearch(String(input.search??""));
    let query=this.supabase.from("client_contracts").select("*,clients!inner(legal_name,trade_name)",{count:"exact"}).is("archived_at",null);
    if(search)query=query.or(`contract_number.ilike.%${search}%,name.ilike.%${search}%,contract_type.ilike.%${search}%`);
    if(input.clientId)query=query.eq("client_id",String(input.clientId));if(input.status)query=query.eq("status",String(input.status));
    if(input.expiringBefore)query=query.lte("end_date",String(input.expiringBefore)).gte("end_date",new Date().toISOString().slice(0,10));
    const {data,error,count}=await query.order(String(input.sort||"updated_at"),{ascending:input.order==="asc"}).range(from,to);if(error)throw error;
    const items=(data??[]).map(row=>this.fromRow(row));return{items,page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize),summary:await this.summary()};
  }

  async get(id:string){if(!this.supabase)return this.memory.get(id);const {data,error}=await this.supabase.from("client_contracts").select("*,clients!inner(legal_name,trade_name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.fromRow(data):undefined;}
  async versions(contractId:string):Promise<ContractVersion[]>{if(!this.supabase)return[];const {data,error}=await this.supabase.from("client_contract_versions").select("*").eq("contract_id",contractId).order("version_number",{ascending:false});if(error)throw error;return(data??[]).map(r=>({id:r.id,contractId:r.contract_id,versionNumber:r.version_number,versionKind:r.version_kind,title:r.title,storagePath:r.storage_path,documentHash:r.document_hash,mimeType:r.mime_type,sizeBytes:r.size_bytes===null?null:Number(r.size_bytes),createdAt:r.created_at}));}

  async create(input:ContractInput){
    const stamp=new Date().toISOString();
    if(!this.supabase){
      const item:ClientContract={id:randomUUID(),contractNumber:`CTR-${new Date().getUTCFullYear()}-${String(this.memory.size+1).padStart(6,"0")}`,clientId:input.clientId,clientName:"Cliente",name:input.name,description:input.description,contractType:input.contractType,status:input.status??"DRAFT",startDate:input.startDate,endDate:input.endDate,renewalType:input.renewalType,renewalNoticeDays:input.renewalNoticeDays,billingFrequency:input.billingFrequency,currency:input.currency,subtotal:input.subtotal,tax:input.tax,total:input.total,signedAt:null,responsibleUserId:input.responsibleUserId,signatureStatus:"NOT_CONFIGURED",signatureProvider:null,signatureRequestId:null,documentHash:null,portalVisible:input.portalVisible,version:1,parentContractId:null,createdAt:stamp,updatedAt:stamp,archivedAt:null,projectId:input.projectId??null,quoteId:input.quoteId??null,quoteVersionId:input.quoteVersionId??null,independentReason:input.independentReason??null,templateCodes:input.templateCodes??[],builderValues:input.builderValues??{},sourceSnapshot:input.sourceSnapshot??{},legalReviewStatus:"REQUIRED",approvalStatus:"DRAFT",effectiveStatus:"NOT_STARTED",complianceStatus:"NOT_ASSESSED",collectionStatus:"NOT_DUE",frozenAt:null,frozenHash:null,originalDocumentId:null,signedDocumentId:null};
      this.memory.set(item.id,item);return item;
    }
    const {data,error}=await this.supabase.from("client_contracts").insert(this.toRow(input)).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);
  }

  async update(id:string,patch:Partial<ContractInput>){
    const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");
    if(current.frozenAt||(["PENDING_SIGNATURE","SIGNED","ACTIVE","EXPIRING","EXPIRED"].includes(current.status)&&Object.keys(patch).some(key=>!["status","portalVisible","responsibleUserId"].includes(key))))throw new BadRequestException("Los contratos congelados, enviados o firmados requieren una nueva versión.");
    if(!this.supabase){const next={...current,...patch,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}
    const {data,error}=await this.supabase.from("client_contracts").update(this.patchRow(patch)).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);
  }

  async builderPatch(id:string,patch:Record<string,unknown>){
    const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");if(current.frozenAt)throw new BadRequestException("La versión contractual está congelada; crea una nueva versión u orden de cambio.");
    if(!this.supabase){const next={...current,...patch,updatedAt:new Date().toISOString()} as ClientContract;this.memory.set(id,next);return next;}
    const map:Record<string,string>={projectId:"project_id",quoteId:"quote_id",quoteVersionId:"quote_version_id",independentReason:"independent_reason",templateCodes:"template_codes",builderValues:"builder_values",sourceSnapshot:"source_snapshot",legalReviewStatus:"legal_review_status",approvalStatus:"approval_status"};const row:Record<string,unknown>={updated_at:new Date().toISOString()};for(const[k,v]of Object.entries(patch))if(map[k])row[map[k]!]=v;
    const{data,error}=await this.supabase.from("client_contracts").update(row).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);
  }

  async approveBuilder(id:string,input:{hash:string;documentId:string;actorId:string|null}){
    const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");const stamp=new Date().toISOString();
    if(!this.supabase){const next={...current,status:"IN_REVIEW" as const,approvalStatus:"APPROVED" as const,legalReviewStatus:"APPROVED" as const,frozenAt:stamp,frozenHash:input.hash,originalDocumentId:input.documentId,documentHash:input.hash,updatedAt:stamp};this.memory.set(id,next);return next;}
    const{data,error}=await this.supabase.from("client_contracts").update({status:"IN_REVIEW",approval_status:"APPROVED",legal_review_status:"APPROVED",approved_by:input.actorId,approved_at:stamp,frozen_at:stamp,frozen_hash:input.hash,original_document_id:input.documentId,document_id:input.documentId,document_hash:input.hash,updated_at:stamp}).eq("id",id).is("frozen_at",null).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);
  }

  async signatureRequested(id:string,request:{id:string;provider:string}){
    const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");
    if(!this.supabase){const next={...current,status:"PENDING_SIGNATURE" as const,signatureStatus:"REQUESTED" as const,signatureRequestId:request.id,signatureProvider:request.provider,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}
    const{data,error}=await this.supabase.from("client_contracts").update({status:"PENDING_SIGNATURE",signature_status:"REQUESTED",signature_request_id:request.id,signature_provider:request.provider,updated_at:new Date().toISOString()}).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);
  }
  async signatureCompleted(id:string,evidence:Record<string,unknown>={}){const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");const stamp=new Date().toISOString(),signedDocumentId=typeof evidence.signedDocumentId==="string"?evidence.signedDocumentId:null,signedDocumentHash=typeof evidence.signedDocumentHash==="string"?evidence.signedDocumentHash:null;if(!this.supabase){const next={...current,status:"SIGNED" as const,signatureStatus:"SIGNED" as const,signedAt:stamp,signedDocumentId,signedDocumentHash,signatureEvidence:evidence,updatedAt:stamp};this.memory.set(id,next);return next;}const{data,error}=await this.supabase.from("client_contracts").update({status:"SIGNED",signature_status:"SIGNED",signed_at:stamp,signed_document_id:signedDocumentId,signed_document_hash:signedDocumentHash,signature_evidence:evidence,updated_at:stamp}).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}

  async reviews(contractId:string){if(!this.supabase)return this.authorityReviews.filter(item=>item.contractId===contractId);const{data,error}=await this.supabase.from("contract_authority_reviews").select("*").eq("contract_id",contractId).order("created_at");if(error)throw error;return(data??[]).map(row=>({id:row.id,contractId:row.contract_id,party:row.party,representativeName:row.representative_name,representativeRut:row.representative_rut,authorityBasis:row.authority_basis,evidenceDocumentId:row.evidence_document_id,reviewedBy:row.reviewed_by,reviewedAt:row.reviewed_at,status:row.status,createdAt:row.created_at}));}
  async recordReview(contractId:string,body:{party:string;representativeName:string;representativeRut?:string|null;authorityBasis:string;evidenceDocumentId?:string|null;status?:string},actorId:string|null){const item={id:randomUUID(),contractId,party:body.party,representativeName:body.representativeName.trim(),representativeRut:body.representativeRut?.trim()||null,authorityBasis:body.authorityBasis.trim(),evidenceDocumentId:body.evidenceDocumentId??null,reviewedBy:actorId,reviewedAt:body.status==="VERIFIED"?new Date().toISOString():null,status:body.status??"PENDING",createdAt:new Date().toISOString()};if(!this.supabase){this.authorityReviews.push(item);return item;}const{data,error}=await this.supabase.from("contract_authority_reviews").insert({contract_id:contractId,party:item.party,representative_name:item.representativeName,representative_rut:item.representativeRut,authority_basis:item.authorityBasis,evidence_document_id:item.evidenceDocumentId,reviewed_by:item.reviewedBy,reviewed_at:item.reviewedAt,status:item.status}).select("*").single();if(error)throw error;return data;}
  async receipts(contractId:string){if(!this.supabase)return this.copyReceiptRows.filter(item=>item.contractId===contractId);const{data,error}=await this.supabase.from("contract_copy_receipts").select("*").eq("contract_id",contractId).order("created_at");if(error)throw error;return data??[];}
  async recordReceipt(contractId:string,body:{recipientType:string;recipientName:string;recipientEmail:string;documentId?:string|null;deliveryReference?:string|null;status?:string}){const item={id:randomUUID(),contractId,recipientType:body.recipientType,recipientName:body.recipientName.trim(),recipientEmail:body.recipientEmail.trim(),documentId:body.documentId??null,deliveryReference:body.deliveryReference??null,deliveredAt:body.status==="DELIVERED"?new Date().toISOString():null,receivedAt:body.status==="RECEIVED"?new Date().toISOString():null,status:body.status??"PENDING",createdAt:new Date().toISOString()};if(!this.supabase){this.copyReceiptRows.push(item);return item;}const{data,error}=await this.supabase.from("contract_copy_receipts").insert({contract_id:contractId,recipient_type:item.recipientType,recipient_name:item.recipientName,recipient_email:item.recipientEmail,document_id:item.documentId,delivery_reference:item.deliveryReference,delivered_at:item.deliveredAt,received_at:item.receivedAt,status:item.status}).select("*").single();if(error)throw error;return data;}
  async createObligationDrafts(contract:ClientContract){const values=contract.builderValues??{},payments=Array.isArray((values.tabla as any)?.pagos)?(values.tabla as any).pagos:[],recurring=Array.isArray((values.tabla as any)?.servicios_recurrentes)?(values.tabla as any).servicios_recurrentes:[],rows=[...payments.map((item:any,index:number)=>({idempotencyKey:`payment:${contract.version}:${index}`,obligationType:"PAYMENT_DRAFT",title:item.title||item.hito||`Hito de pago ${index+1}`,description:item.description||null,amount:item.amount??item.monto??null,currency:item.currency||contract.currency,dueDate:item.dueDate||item.fecha||null,activationCondition:item.condition||item.condicion||"Requiere validación financiera",status:"DRAFT"})),...recurring.map((item:any,index:number)=>({idempotencyKey:`recurring:${contract.version}:${index}`,obligationType:"RECURRING_SERVICE_DRAFT",title:item.title||item.servicio||`Servicio recurrente ${index+1}`,description:item.description||null,amount:item.amount??item.monto??null,currency:item.currency||contract.currency,dueDate:null,activationCondition:item.activationCondition||item.activacion||"Requiere evidencia de activación",status:"DRAFT"}))];if(!this.supabase){for(const row of rows)if(!this.obligationRows.some(item=>item.contractId===contract.id&&item.idempotencyKey===row.idempotencyKey))this.obligationRows.push({id:randomUUID(),contractId:contract.id,...row});return this.obligationRows.filter(item=>item.contractId===contract.id);}for(const row of rows){const{error}=await this.supabase.from("contract_obligations").upsert({contract_id:contract.id,idempotency_key:row.idempotencyKey,obligation_type:row.obligationType,title:row.title,description:row.description,amount:row.amount,currency:row.currency,due_date:row.dueDate,activation_condition:row.activationCondition,status:"DRAFT",source_snapshot_hash:contract.frozenHash},{onConflict:"contract_id,idempotency_key",ignoreDuplicates:true});if(error)throw error;}const{data,error}=await this.supabase.from("contract_obligations").select("*").eq("contract_id",contract.id);if(error)throw error;return data??[];}

  async transition(id:string,status:ContractStatus){const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");if(!this.supabase){const next={...current,status,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}const patch:Record<string,unknown>={status,updated_at:new Date().toISOString()};if(status==="SIGNED")patch.signed_at=new Date().toISOString();const{data,error}=await this.supabase.from("client_contracts").update(patch).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}
  async archive(id:string){const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");if(!this.supabase){const next={...current,archivedAt:new Date().toISOString(),status:"CANCELLED" as const};this.memory.set(id,next);return next;}const{data,error}=await this.supabase.from("client_contracts").update({archived_at:new Date().toISOString(),status:"CANCELLED",updated_at:new Date().toISOString()}).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}
  async createUploadUrl(contract:ClientContract,file:{name:string;type:string}){if(!this.supabase)throw new Error("Supabase Storage no está configurado.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${contract.clientId}/${contract.id}/${Date.now()}-${safe}`;const{data,error}=await this.supabase.storage.from("client-contracts").createSignedUploadUrl(path);if(error)throw error;return{path,token:data.token};}
  async completeUpload(contract:ClientContract,input:{path:string;title:string;mimeType:string;sizeBytes:number;documentHash?:string;versionKind?:"CONTRACT"|"ANNEX"}){if(!this.supabase)throw new Error("Supabase Storage no está configurado.");const versions=await this.versions(contract.id);const versionNumber=Math.max(0,...versions.filter(v=>v.versionKind===(input.versionKind??"CONTRACT")).map(v=>v.versionNumber))+1;const id=randomUUID();const{data,error}=await this.supabase.from("client_contract_versions").insert({id,contract_id:contract.id,version_number:versionNumber,version_kind:input.versionKind??"CONTRACT",title:input.title,storage_path:input.path,document_hash:input.documentHash??null,mime_type:input.mimeType,size_bytes:input.sizeBytes}).select("*").single();if(error)throw error;await this.supabase.from("client_contracts").update({document_id:id,document_hash:input.documentHash??null,updated_at:new Date().toISOString()}).eq("id",contract.id);return{id:data.id,contractId:data.contract_id,versionNumber:data.version_number,versionKind:data.version_kind,title:data.title,storagePath:data.storage_path,documentHash:data.document_hash,mimeType:data.mime_type,sizeBytes:Number(data.size_bytes),createdAt:data.created_at} as ContractVersion;}
  async signedDocumentUrl(path:string){if(!this.supabase)throw new Error("Supabase Storage no está configurado.");const{data,error}=await this.supabase.storage.from("client-contracts").createSignedUrl(path,300);if(error)throw error;return data.signedUrl;}

  private async summary(){if(!this.supabase)return this.summaryFrom([...this.memory.values()]);const{data,error}=await this.supabase.from("client_contracts").select("status,end_date,renewal_type,total,billing_frequency,document_id").is("archived_at",null);if(error)throw error;return this.summaryFrom((data??[]).map(r=>({status:r.status,endDate:r.end_date,renewalType:r.renewal_type,total:Number(r.total),billingFrequency:r.billing_frequency,documentId:r.document_id})));}
  private summaryFrom(all:Array<any>){const today=new Date();const in90=new Date(today);in90.setUTCDate(in90.getUTCDate()+90);const monthly=all.filter(i=>i.status==="ACTIVE").reduce((sum,i)=>sum+(i.billingFrequency==="MONTHLY"?Number(i.total):i.billingFrequency==="ANNUAL"?Number(i.total)/12:0),0);return{active:all.filter(i=>i.status==="ACTIVE").length,pendingSignature:all.filter(i=>i.status==="PENDING_SIGNATURE").length,expiring:all.filter(i=>i.endDate&&new Date(i.endDate)>=today&&new Date(i.endDate)<=in90).length,expired:all.filter(i=>i.status==="EXPIRED"||(i.endDate&&new Date(i.endDate)<today)).length,autoRenew:all.filter(i=>i.renewalType==="AUTOMATIC").length,withoutDocument:all.filter(i=>!i.documentId).length,monthlyValue:monthly,annualValue:monthly*12};}
  private memoryList(input:Record<string,string|number|undefined>&{page:number;pageSize:number}){const search=cleanSearch(String(input.search??""))?.toLowerCase();const all=[...this.memory.values()].filter(i=>!i.archivedAt&&(!search||[i.contractNumber,i.name,i.contractType,i.clientName].some(v=>v?.toLowerCase().includes(search)))&&(!input.status||i.status===input.status)&&(!input.clientId||i.clientId===input.clientId));const start=(input.page-1)*input.pageSize;return{items:all.slice(start,start+input.pageSize),page:input.page,pageSize:input.pageSize,total:all.length,totalPages:Math.ceil(all.length/input.pageSize),summary:this.summaryFrom(all)};}
  private fromRow(r:Record<string,any>):ClientContract{const c=Array.isArray(r.clients)?r.clients[0]:r.clients;return{id:r.id,contractNumber:r.contract_number,clientId:r.client_id,clientName:c?.trade_name||c?.legal_name||null,name:r.name,description:r.description,contractType:r.contract_type,status:r.status,startDate:r.start_date,endDate:r.end_date,renewalType:r.renewal_type,renewalNoticeDays:r.renewal_notice_days,billingFrequency:r.billing_frequency,currency:r.currency,subtotal:Number(r.subtotal),tax:Number(r.tax),total:Number(r.total),signedAt:r.signed_at,responsibleUserId:r.responsible_user_id,signatureStatus:r.signature_status,signatureProvider:r.signature_provider,signatureRequestId:r.signature_request_id,documentHash:r.document_hash,portalVisible:r.portal_visible,version:r.version,parentContractId:r.parent_contract_id,createdAt:r.created_at,updatedAt:r.updated_at,archivedAt:r.archived_at,projectId:r.project_id??null,quoteId:r.quote_id??null,quoteVersionId:r.quote_version_id??null,independentReason:r.independent_reason??null,templateCodes:r.template_codes??[],builderValues:r.builder_values??{},sourceSnapshot:r.source_snapshot??{},legalReviewStatus:r.legal_review_status??"REQUIRED",approvalStatus:r.approval_status??"DRAFT",effectiveStatus:r.effective_status??"NOT_STARTED",complianceStatus:r.compliance_status??"NOT_ASSESSED",collectionStatus:r.collection_status??"NOT_DUE",frozenAt:r.frozen_at??null,frozenHash:r.frozen_hash??null,originalDocumentId:r.original_document_id??null,signedDocumentId:r.signed_document_id??null,signedDocumentHash:r.signed_document_hash??null,signatureEvidence:r.signature_evidence??{}};}
  private toRow(i:ContractInput){return{client_id:i.clientId,name:i.name,description:i.description,contract_type:i.contractType,status:i.status,start_date:i.startDate,end_date:i.endDate,renewal_type:i.renewalType,renewal_notice_days:i.renewalNoticeDays,billing_frequency:i.billingFrequency,currency:i.currency,subtotal:i.subtotal,tax:i.tax,total:i.total,responsible_user_id:i.responsibleUserId,portal_visible:i.portalVisible,project_id:i.projectId??null,quote_id:i.quoteId??null,quote_version_id:i.quoteVersionId??null,independent_reason:i.independentReason??null,template_codes:i.templateCodes??[],builder_values:i.builderValues??{},source_snapshot:i.sourceSnapshot??{}};}
  private patchRow(i:Partial<ContractInput>){const map:Record<string,string>={name:"name",description:"description",contractType:"contract_type",status:"status",startDate:"start_date",endDate:"end_date",renewalType:"renewal_type",renewalNoticeDays:"renewal_notice_days",billingFrequency:"billing_frequency",currency:"currency",subtotal:"subtotal",tax:"tax",total:"total",responsibleUserId:"responsible_user_id",portalVisible:"portal_visible",projectId:"project_id",quoteId:"quote_id",quoteVersionId:"quote_version_id",independentReason:"independent_reason",templateCodes:"template_codes",builderValues:"builder_values",sourceSnapshot:"source_snapshot"};const row:Record<string,unknown>={updated_at:new Date().toISOString()};for(const[k,v]of Object.entries(i))if(map[k])row[map[k]!]=v;return row;}
}
