import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { ClientContract, ContractStatus, ContractVersion } from "@zyteron/contracts";
import { cleanSearch, createServerSupabase, pageBounds } from "../domain/server-supabase.js";
import type { ContractInput } from "./contracts.dto.js";

@Injectable()
export class ContractsRepository {
  private readonly supabase=createServerSupabase();
  private readonly memory=new Map<string,ClientContract>();
  async types(){if(!this.supabase)return[{code:"DESARROLLO",name:"Desarrollo"},{code:"MANTENCION",name:"Mantención"},{code:"SOPORTE",name:"Soporte"},{code:"HOSTING",name:"Hosting"},{code:"SEO",name:"SEO"},{code:"SOFTWARE",name:"Software"},{code:"CONSULTORIA",name:"Consultoría"},{code:"SERVICIO_RECURRENTE",name:"Servicio recurrente"},{code:"OTRO",name:"Otro"}];const{data,error}=await this.supabase.from("contract_type_catalog").select("code,name").eq("active",true).order("name");if(error)throw error;return data??[];}
  async list(input:Record<string,string|number|undefined>&{page:number;pageSize:number}){
    if(!this.supabase)return this.memoryList(input);
    const {from,to}=pageBounds(input.page,input.pageSize);const search=cleanSearch(String(input.search??""));
    let query=this.supabase.from("client_contracts").select("*,clients!inner(legal_name,trade_name)",{count:"exact"}).is("archived_at",null);
    if(search)query=query.or(`contract_number.ilike.%${search}%,name.ilike.%${search}%,contract_type.ilike.%${search}%`);
    if(input.clientId)query=query.eq("client_id",String(input.clientId));if(input.status)query=query.eq("status",String(input.status));
    if(input.expiringBefore)query=query.lte("end_date",String(input.expiringBefore)).gte("end_date",new Date().toISOString().slice(0,10));
    const {data,error,count}=await query.order(String(input.sort||"updated_at"),{ascending:input.order==="asc"}).range(from,to);if(error)throw error;
    const items=(data??[]).map((row)=>this.fromRow(row));const summary=await this.summary();
    return {items,page:input.page,pageSize:input.pageSize,total:count??0,totalPages:Math.ceil((count??0)/input.pageSize),summary};
  }
  async get(id:string){if(!this.supabase)return this.memory.get(id);const {data,error}=await this.supabase.from("client_contracts").select("*,clients!inner(legal_name,trade_name)").eq("id",id).maybeSingle();if(error)throw error;return data?this.fromRow(data):undefined;}
  async versions(contractId:string):Promise<ContractVersion[]>{if(!this.supabase)return[];const {data,error}=await this.supabase.from("client_contract_versions").select("*").eq("contract_id",contractId).order("version_number",{ascending:false});if(error)throw error;return(data??[]).map((r)=>({id:r.id,contractId:r.contract_id,versionNumber:r.version_number,versionKind:r.version_kind,title:r.title,storagePath:r.storage_path,documentHash:r.document_hash,mimeType:r.mime_type,sizeBytes:r.size_bytes===null?null:Number(r.size_bytes),createdAt:r.created_at}));}
  async create(input:ContractInput){const now=new Date().toISOString();if(!this.supabase){const count=this.memory.size+1;const item:ClientContract={id:randomUUID(),contractNumber:`CTR-${new Date().getUTCFullYear()}-${String(count).padStart(6,"0")}`,clientId:input.clientId,clientName:"Cliente",name:input.name,description:input.description,contractType:input.contractType,status:input.status??"DRAFT",startDate:input.startDate,endDate:input.endDate,renewalType:input.renewalType,renewalNoticeDays:input.renewalNoticeDays,billingFrequency:input.billingFrequency,currency:input.currency,subtotal:input.subtotal,tax:input.tax,total:input.total,signedAt:null,responsibleUserId:input.responsibleUserId,signatureStatus:"NOT_CONFIGURED",signatureProvider:null,signatureRequestId:null,documentHash:null,portalVisible:input.portalVisible,version:1,parentContractId:null,createdAt:now,updatedAt:now,archivedAt:null};this.memory.set(item.id,item);return item;}
    const {data,error}=await this.supabase.from("client_contracts").insert(this.toRow(input)).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}
  async update(id:string,patch:Partial<ContractInput>){const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");if(["PENDING_SIGNATURE","SIGNED","ACTIVE","EXPIRING","EXPIRED"].includes(current.status)&&Object.keys(patch).some((key)=>!["status","portalVisible","responsibleUserId"].includes(key)))throw new BadRequestException("Los contratos enviados o firmados requieren una nueva versión.");if(!this.supabase){const next={...current,...patch,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}const row=this.patchRow(patch);const {data,error}=await this.supabase.from("client_contracts").update(row).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}
  async transition(id:string,status:ContractStatus){const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");if(!this.supabase){const next={...current,status,updatedAt:new Date().toISOString()};this.memory.set(id,next);return next;}const patch:Record<string,unknown>={status,updated_at:new Date().toISOString()};if(status==="SIGNED")patch.signed_at=new Date().toISOString();const{data,error}=await this.supabase.from("client_contracts").update(patch).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}
  async archive(id:string){const current=await this.get(id);if(!current)throw new NotFoundException("Contrato no encontrado.");if(!this.supabase){const next={...current,archivedAt:new Date().toISOString(),status:"CANCELLED" as const};this.memory.set(id,next);return next;}const{data,error}=await this.supabase.from("client_contracts").update({archived_at:new Date().toISOString(),status:"CANCELLED",updated_at:new Date().toISOString()}).eq("id",id).select("*,clients!inner(legal_name,trade_name)").single();if(error)throw error;return this.fromRow(data);}
  async createUploadUrl(contract:ClientContract,file:{name:string;type:string}){if(!this.supabase)throw new Error("Supabase Storage no está configurado.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${contract.clientId}/${contract.id}/${Date.now()}-${safe}`;const{data,error}=await this.supabase.storage.from("client-contracts").createSignedUploadUrl(path);if(error)throw error;return{path,token:data.token};}
  async completeUpload(contract:ClientContract,input:{path:string;title:string;mimeType:string;sizeBytes:number;documentHash?:string;versionKind?:"CONTRACT"|"ANNEX"}){if(!this.supabase)throw new Error("Supabase Storage no está configurado.");const versions=await this.versions(contract.id);const versionNumber=Math.max(0,...versions.filter((v)=>v.versionKind===(input.versionKind??"CONTRACT")).map((v)=>v.versionNumber))+1;const id=randomUUID();const{data,error}=await this.supabase.from("client_contract_versions").insert({id,contract_id:contract.id,version_number:versionNumber,version_kind:input.versionKind??"CONTRACT",title:input.title,storage_path:input.path,document_hash:input.documentHash??null,mime_type:input.mimeType,size_bytes:input.sizeBytes}).select("*").single();if(error)throw error;await this.supabase.from("client_contracts").update({document_id:id,document_hash:input.documentHash??null,updated_at:new Date().toISOString()}).eq("id",contract.id);return{id:data.id,contractId:data.contract_id,versionNumber:data.version_number,versionKind:data.version_kind,title:data.title,storagePath:data.storage_path,documentHash:data.document_hash,mimeType:data.mime_type,sizeBytes:Number(data.size_bytes),createdAt:data.created_at} as ContractVersion;}
  async signedDocumentUrl(path:string){if(!this.supabase)throw new Error("Supabase Storage no está configurado.");const{data,error}=await this.supabase.storage.from("client-contracts").createSignedUrl(path,300);if(error)throw error;return data.signedUrl;}
  private async summary(){if(!this.supabase){const all=[...this.memory.values()];return this.summaryFrom(all);}const{data,error}=await this.supabase.from("client_contracts").select("status,end_date,renewal_type,total,billing_frequency,document_id").is("archived_at",null);if(error)throw error;return this.summaryFrom((data??[]).map((r)=>({status:r.status,endDate:r.end_date,renewalType:r.renewal_type,total:Number(r.total),billingFrequency:r.billing_frequency,documentId:r.document_id})));}
  private summaryFrom(all:Array<any>){const today=new Date();const in90=new Date(today);in90.setUTCDate(in90.getUTCDate()+90);const monthly=all.filter((i)=>i.status==="ACTIVE").reduce((sum,i)=>sum+(i.billingFrequency==="MONTHLY"?Number(i.total):i.billingFrequency==="ANNUAL"?Number(i.total)/12:0),0);return{active:all.filter((i)=>i.status==="ACTIVE").length,pendingSignature:all.filter((i)=>i.status==="PENDING_SIGNATURE").length,expiring:all.filter((i)=>i.endDate&&new Date(i.endDate)>=today&&new Date(i.endDate)<=in90).length,expired:all.filter((i)=>i.status==="EXPIRED"||(i.endDate&&new Date(i.endDate)<today)).length,autoRenew:all.filter((i)=>i.renewalType==="AUTOMATIC").length,withoutDocument:all.filter((i)=>!i.documentId).length,monthlyValue:monthly,annualValue:monthly*12};}
  private memoryList(input:Record<string,string|number|undefined>&{page:number;pageSize:number}){const search=cleanSearch(String(input.search??""))?.toLowerCase();const all=[...this.memory.values()].filter((i)=>!i.archivedAt&&(!search||[i.contractNumber,i.name,i.contractType,i.clientName].some((v)=>v?.toLowerCase().includes(search)))&&(!input.status||i.status===input.status)&&(!input.clientId||i.clientId===input.clientId));const start=(input.page-1)*input.pageSize;return{items:all.slice(start,start+input.pageSize),page:input.page,pageSize:input.pageSize,total:all.length,totalPages:Math.ceil(all.length/input.pageSize),summary:this.summaryFrom(all)};}
  private fromRow(r:Record<string,any>):ClientContract{const c=Array.isArray(r.clients)?r.clients[0]:r.clients;return{id:r.id,contractNumber:r.contract_number,clientId:r.client_id,clientName:c?.trade_name||c?.legal_name||null,name:r.name,description:r.description,contractType:r.contract_type,status:r.status,startDate:r.start_date,endDate:r.end_date,renewalType:r.renewal_type,renewalNoticeDays:r.renewal_notice_days,billingFrequency:r.billing_frequency,currency:r.currency,subtotal:Number(r.subtotal),tax:Number(r.tax),total:Number(r.total),signedAt:r.signed_at,responsibleUserId:r.responsible_user_id,signatureStatus:r.signature_status,signatureProvider:r.signature_provider,signatureRequestId:r.signature_request_id,documentHash:r.document_hash,portalVisible:r.portal_visible,version:r.version,parentContractId:r.parent_contract_id,createdAt:r.created_at,updatedAt:r.updated_at,archivedAt:r.archived_at};}
  private toRow(i:ContractInput){return{client_id:i.clientId,name:i.name,description:i.description,contract_type:i.contractType,status:i.status,start_date:i.startDate,end_date:i.endDate,renewal_type:i.renewalType,renewal_notice_days:i.renewalNoticeDays,billing_frequency:i.billingFrequency,currency:i.currency,subtotal:i.subtotal,tax:i.tax,total:i.total,responsible_user_id:i.responsibleUserId,portal_visible:i.portalVisible};}
  private patchRow(i:Partial<ContractInput>){const map:Record<string,string>={name:"name",description:"description",contractType:"contract_type",status:"status",startDate:"start_date",endDate:"end_date",renewalType:"renewal_type",renewalNoticeDays:"renewal_notice_days",billingFrequency:"billing_frequency",currency:"currency",subtotal:"subtotal",tax:"tax",total:"total",responsibleUserId:"responsible_user_id",portalVisible:"portal_visible"};const row:Record<string,unknown>={updated_at:new Date().toISOString()};for(const[k,v]of Object.entries(i))if(map[k])row[map[k]!]=v;return row;}
}
