begin;

create sequence if not exists public.audit_number_seq;
create sequence if not exists public.finding_number_seq;
create or replace function public.next_audit_number() returns text language sql volatile set search_path=public as $$select 'AUD-'||extract(year from now() at time zone 'UTC')::integer||'-'||lpad(nextval('public.audit_number_seq')::text,6,'0')$$;
create or replace function public.next_finding_number() returns text language sql volatile set search_path=public as $$select 'FND-'||extract(year from now() at time zone 'UTC')::integer||'-'||lpad(nextval('public.finding_number_seq')::text,6,'0')$$;

create table if not exists public.audit_templates(
 id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,audit_type text not null check(audit_type in('WEB_GENERAL','SEGURIDAD','SEO','PERFORMANCE','ACCESSIBILITY','INFRASTRUCTURE','INTEGRATIONS','BACKUP','MAINTENANCE','PROJECT_DELIVERY','SERVICE_REVIEW','CUSTOM')),description text,active boolean not null default true,current_version integer not null default 0 check(current_version>=0),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.audit_template_versions(
 id uuid primary key default gen_random_uuid(),template_id uuid not null references public.audit_templates(id) on delete restrict,version integer not null check(version>0),status text not null default 'DRAFT' check(status in('DRAFT','PUBLISHED','RETIRED')),change_summary text,published_at timestamptz,published_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(template_id,version)
);
create table if not exists public.audit_template_sections(
 id uuid primary key default gen_random_uuid(),template_version_id uuid not null references public.audit_template_versions(id) on delete restrict,code text not null,title text not null,description text,weight numeric(8,2) not null default 0 check(weight>=0),sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(template_version_id,code)
);
create table if not exists public.audit_template_checks(
 id uuid primary key default gen_random_uuid(),template_version_id uuid not null references public.audit_template_versions(id) on delete restrict,section_id uuid not null references public.audit_template_sections(id) on delete restrict,code text not null,title text not null,description text,check_type text not null default 'MANUAL' check(check_type in('MANUAL','AUTOMATED','HYBRID')),required boolean not null default true,weight numeric(8,2) not null default 0 check(weight>=0),severity_on_failure text not null default 'MEDIUM' check(severity_on_failure in('INFO','LOW','MEDIUM','HIGH','CRITICAL')),instructions text,automation_key text,auto_create_finding boolean not null default false,evidence_required boolean not null default false,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(template_version_id,code)
);
create table if not exists public.audit_plans(
 id uuid primary key default gen_random_uuid(),client_id uuid not null references public.clients(id) on delete restrict,project_id uuid references public.projects(id) on delete restrict,service_id uuid references public.client_services(id) on delete restrict,name text not null,audit_type text not null check(audit_type in('WEB_GENERAL','SEGURIDAD','SEO','PERFORMANCE','ACCESSIBILITY','INFRASTRUCTURE','INTEGRATIONS','BACKUP','MAINTENANCE','PROJECT_DELIVERY','SERVICE_REVIEW','CUSTOM')),template_id uuid not null references public.audit_templates(id) on delete restrict,frequency text not null check(frequency in('ONE_TIME','WEEKLY','MONTHLY','QUARTERLY','SEMIANNUAL','ANNUAL','CUSTOM')),custom_interval_days integer check(custom_interval_days is null or custom_interval_days>0),responsible_user_id uuid,reviewer_user_id uuid,start_date date not null,next_run_at timestamptz,active boolean not null default true,client_visibility text not null default 'INTERNAL_ONLY' check(client_visibility in('INTERNAL_ONLY','CLIENT_SUMMARY','CLIENT_VISIBLE')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(frequency<>'CUSTOM' or custom_interval_days is not null)
);
create table if not exists public.audit_runs(
 id uuid primary key default gen_random_uuid(),audit_number text not null unique default public.next_audit_number(),plan_id uuid references public.audit_plans(id) on delete restrict,client_id uuid not null references public.clients(id) on delete restrict,project_id uuid references public.projects(id) on delete restrict,service_id uuid references public.client_services(id) on delete restrict,template_version_id uuid not null references public.audit_template_versions(id) on delete restrict,audit_type text not null check(audit_type in('WEB_GENERAL','SEGURIDAD','SEO','PERFORMANCE','ACCESSIBILITY','INFRASTRUCTURE','INTEGRATIONS','BACKUP','MAINTENANCE','PROJECT_DELIVERY','SERVICE_REVIEW','CUSTOM')),status text not null default 'SCHEDULED' check(status in('SCHEDULED','READY','IN_PROGRESS','WAITING_INFORMATION','IN_REVIEW','REMEDIATION_REQUIRED','RETEST_REQUIRED','COMPLETED','CANCELLED')),scheduled_at timestamptz not null,started_at timestamptz,completed_at timestamptz,responsible_user_id uuid,reviewer_user_id uuid,score numeric(5,2) check(score is null or score between 0 and 100),progress numeric(5,2) not null default 0 check(progress between 0 and 100),client_visibility text not null default 'INTERNAL_ONLY' check(client_visibility in('INTERNAL_ONLY','CLIENT_SUMMARY','CLIENT_VISIBLE')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.audit_check_results(
 id uuid primary key default gen_random_uuid(),audit_id uuid not null references public.audit_runs(id) on delete restrict,check_id uuid not null references public.audit_template_checks(id) on delete restrict,section_id uuid not null references public.audit_template_sections(id) on delete restrict,status text not null default 'NOT_STARTED' check(status in('NOT_STARTED','PASS','PASS_WITH_OBSERVATION','FAIL','NOT_APPLICABLE','BLOCKED')),notes text,not_applicable_reason text,evidence_required boolean not null default false,executed_by uuid,executed_at timestamptz,automation_source text,weight numeric(8,2) not null default 0,severity_on_failure text not null default 'MEDIUM' check(severity_on_failure in('INFO','LOW','MEDIUM','HIGH','CRITICAL')),finding_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(audit_id,check_id),check(status<>'NOT_APPLICABLE' or length(trim(coalesce(not_applicable_reason,'')))>0)
);
create table if not exists public.audit_findings(
 id uuid primary key default gen_random_uuid(),finding_number text not null unique default public.next_finding_number(),audit_id uuid not null references public.audit_runs(id) on delete restrict,client_id uuid not null references public.clients(id) on delete restrict,project_id uuid references public.projects(id) on delete restrict,check_result_id uuid references public.audit_check_results(id) on delete restrict,category text not null,title text not null,description text not null,severity text not null check(severity in('INFO','LOW','MEDIUM','HIGH','CRITICAL')),priority text not null default 'NORMAL' check(priority in('LOW','NORMAL','HIGH','URGENT','CRITICAL')),status text not null default 'OPEN' check(status in('OPEN','ACKNOWLEDGED','ASSIGNED','IN_REMEDIATION','READY_FOR_RETEST','RETEST_FAILED','RESOLVED','ACCEPTED_RISK','NOT_APPLICABLE','CLOSED')),responsible_user_id uuid,due_date date,recommendation text,internal_notes text,client_summary text,client_visibility text not null default 'INTERNAL_ONLY' check(client_visibility in('INTERNAL_ONLY','CLIENT_SUMMARY','CLIENT_VISIBLE')),task_id uuid references public.tasks(id) on delete restrict,bug_id uuid references public.bugs(id) on delete restrict,accepted_risk_reason text,accepted_risk_by uuid,risk_review_at date,created_at timestamptz not null default now(),resolved_at timestamptz,updated_at timestamptz not null default now(),check(status<>'ACCEPTED_RISK' or (accepted_risk_reason is not null and accepted_risk_by is not null and risk_review_at is not null))
);
alter table public.audit_check_results drop constraint if exists audit_check_results_finding_id_fkey;
alter table public.audit_check_results add constraint audit_check_results_finding_id_fkey foreign key(finding_id) references public.audit_findings(id) on delete restrict;
create unique index if not exists audit_findings_check_unique on public.audit_findings(check_result_id) where check_result_id is not null;
create table if not exists public.audit_evidence(
 id uuid primary key default gen_random_uuid(),audit_id uuid not null references public.audit_runs(id) on delete restrict,finding_id uuid references public.audit_findings(id) on delete restrict,check_result_id uuid references public.audit_check_results(id) on delete restrict,document_id uuid,storage_path text,evidence_type text not null check(evidence_type in('SCREENSHOT','PDF','IMAGE','SAFE_LOG_EXTRACT','URL','TEXT','REPORT')),title text not null,description text,filename text,mime_type text,size_bytes bigint check(size_bytes is null or size_bytes>=0),sha256 text check(sha256 is null or sha256~'^[a-f0-9]{64}$'),external_url text,text_content text,visibility text not null default 'INTERNAL_ONLY' check(visibility in('INTERNAL_ONLY','CLIENT_VISIBLE')),uploaded_by uuid,uploaded_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.audit_remediations(
 id uuid primary key default gen_random_uuid(),finding_id uuid not null unique references public.audit_findings(id) on delete restrict,owner_id uuid,action_plan text not null,status text not null default 'PLANNED' check(status in('PLANNED','IN_PROGRESS','BLOCKED','READY_FOR_RETEST','COMPLETED','CANCELLED')),target_date date,task_id uuid references public.tasks(id) on delete restrict,bug_id uuid references public.bugs(id) on delete restrict,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.audit_retests(
 id uuid primary key default gen_random_uuid(),finding_id uuid not null references public.audit_findings(id) on delete restrict,performed_by uuid,performed_at timestamptz not null default now(),result text not null check(result in('PASS','FAIL','BLOCKED')),notes text not null,evidence_id uuid references public.audit_evidence(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.audit_reports(
 id uuid primary key default gen_random_uuid(),audit_id uuid not null references public.audit_runs(id) on delete restrict,version integer not null check(version>0),report_type text not null check(report_type in('INTERNAL','CLIENT')),status text not null default 'DRAFT' check(status in('DRAFT','REVIEW','APPROVED','PUBLISHED')),document_id text,sha256 text not null check(sha256~'^[a-f0-9]{64}$'),template_version_id uuid not null references public.audit_template_versions(id) on delete restrict,audit_snapshot jsonb not null,generated_by uuid,generated_at timestamptz not null default now(),approved_by uuid,approved_at timestamptz,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(audit_id,version,report_type)
);
create table if not exists public.audit_events(
 id uuid primary key default gen_random_uuid(),audit_id uuid references public.audit_runs(id) on delete restrict,finding_id uuid references public.audit_findings(id) on delete restrict,aggregate_type text not null,aggregate_id uuid not null,event_type text not null,actor_id uuid,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now()
);
create table if not exists public.audit_notifications(id uuid primary key default gen_random_uuid(),event_key text not null unique,user_id uuid,audience_role text,type text not null,title text not null,body text,entity_type text not null,entity_id uuid not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.audit_idempotency_keys(idempotency_key text not null,operation text not null,resource_id uuid not null,created_at timestamptz not null default now(),primary key(idempotency_key,operation));

create or replace function public.audit_event_to_outbox() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.business_event_outbox(aggregate_type,aggregate_id,event_type,payload) values(new.aggregate_type,new.aggregate_id,new.event_type,jsonb_build_object('auditId',new.audit_id,'findingId',new.finding_id,'auditEventId',new.id)||new.payload);return new;end$$;
drop trigger if exists audit_event_outbox on public.audit_events;create trigger audit_event_outbox after insert on public.audit_events for each row execute function public.audit_event_to_outbox();

create index if not exists audit_plans_client_next_idx on public.audit_plans(client_id,next_run_at) where active;
create index if not exists audit_plans_project_idx on public.audit_plans(project_id) where project_id is not null;
create index if not exists audit_runs_client_status_idx on public.audit_runs(client_id,status,scheduled_at desc);
create index if not exists audit_runs_project_status_idx on public.audit_runs(project_id,status,scheduled_at desc) where project_id is not null;
create index if not exists audit_runs_responsible_idx on public.audit_runs(responsible_user_id,status,scheduled_at);
create index if not exists audit_findings_audit_status_idx on public.audit_findings(audit_id,status,severity);
create index if not exists audit_findings_client_status_idx on public.audit_findings(client_id,status,due_date);
create index if not exists audit_findings_project_idx on public.audit_findings(project_id,status) where project_id is not null;
create index if not exists audit_findings_responsible_idx on public.audit_findings(responsible_user_id,status,due_date);
create index if not exists audit_remediations_due_idx on public.audit_remediations(status,target_date);
create index if not exists audit_events_timeline_idx on public.audit_events(audit_id,occurred_at desc);

create or replace function public.audit_template_version_immutable() returns trigger language plpgsql set search_path=public as $$begin if old.status in('PUBLISHED','RETIRED') then raise exception 'Una versión de plantilla publicada es inmutable';end if;if tg_op='DELETE' then return old;end if;return new;end$$;
drop trigger if exists audit_template_version_immutable on public.audit_template_versions;create trigger audit_template_version_immutable before update or delete on public.audit_template_versions for each row execute function public.audit_template_version_immutable();
create or replace function public.audit_template_child_immutable() returns trigger language plpgsql set search_path=public as $$declare version_id uuid;begin if tg_op='DELETE' then version_id:=old.template_version_id;else version_id:=new.template_version_id;end if;if exists(select 1 from public.audit_template_versions where id=version_id and status in('PUBLISHED','RETIRED')) then raise exception 'Los checks de una versión publicada son inmutables';end if;if tg_op='DELETE' then return old;end if;return new;end$$;
drop trigger if exists audit_template_section_immutable on public.audit_template_sections;create trigger audit_template_section_immutable before insert or update or delete on public.audit_template_sections for each row execute function public.audit_template_child_immutable();
drop trigger if exists audit_template_check_immutable on public.audit_template_checks;create trigger audit_template_check_immutable before insert or update or delete on public.audit_template_checks for each row execute function public.audit_template_child_immutable();

create or replace function private.can_manage_audits() returns boolean language sql stable security definer set search_path=public as $$select private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD')$$;
create or replace function private.can_execute_audits() returns boolean language sql stable security definer set search_path=public as $$select private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD','QA')$$;
create or replace function private.can_read_audit(target_audit_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.audit_runs a where a.id=target_audit_id and (private.can_manage_audits() or a.responsible_user_id=auth.uid() or a.reviewer_user_id=auth.uid() or (a.project_id is not null and private.can_access_project(a.project_id)) or (private.zyteron_role() in('JEFE_VENTAS','EJECUTIVA_VENTAS','COMERCIAL') and a.client_visibility<>'INTERNAL_ONLY') or (private.zyteron_role()='PORTAL_CLIENT' and a.client_visibility='CLIENT_VISIBLE' and a.client_id=nullif(auth.jwt()->'app_metadata'->>'client_id','')::uuid)))$$;

do $$declare t text;begin foreach t in array array['audit_templates','audit_template_versions','audit_template_sections','audit_template_checks','audit_plans','audit_runs','audit_check_results','audit_findings','audit_evidence','audit_remediations','audit_retests','audit_reports','audit_events','audit_notifications','audit_idempotency_keys'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
drop policy if exists audit_templates_read on public.audit_templates;create policy audit_templates_read on public.audit_templates for select to authenticated using(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD','QA','PROGRAMADOR','DESARROLLO','OPERACIONES'));
drop policy if exists audit_templates_manage on public.audit_templates;create policy audit_templates_manage on public.audit_templates for all to authenticated using(private.can_manage_audits()) with check(private.can_manage_audits());
drop policy if exists audit_versions_read on public.audit_template_versions;create policy audit_versions_read on public.audit_template_versions for select to authenticated using(exists(select 1 from public.audit_templates t where t.id=template_id and (t.active or private.can_manage_audits())));
drop policy if exists audit_versions_manage on public.audit_template_versions;create policy audit_versions_manage on public.audit_template_versions for all to authenticated using(private.can_manage_audits()) with check(private.can_manage_audits());
drop policy if exists audit_sections_read on public.audit_template_sections;create policy audit_sections_read on public.audit_template_sections for select to authenticated using(exists(select 1 from public.audit_template_versions v join public.audit_templates t on t.id=v.template_id where v.id=template_version_id and (t.active or private.can_manage_audits())));
drop policy if exists audit_sections_manage on public.audit_template_sections;create policy audit_sections_manage on public.audit_template_sections for all to authenticated using(private.can_manage_audits()) with check(private.can_manage_audits());
drop policy if exists audit_checks_read on public.audit_template_checks;create policy audit_checks_read on public.audit_template_checks for select to authenticated using(exists(select 1 from public.audit_template_versions v join public.audit_templates t on t.id=v.template_id where v.id=template_version_id and (t.active or private.can_manage_audits())));
drop policy if exists audit_checks_manage on public.audit_template_checks;create policy audit_checks_manage on public.audit_template_checks for all to authenticated using(private.can_manage_audits()) with check(private.can_manage_audits());
drop policy if exists audit_plans_scope on public.audit_plans;create policy audit_plans_scope on public.audit_plans for select to authenticated using(private.can_manage_audits() or responsible_user_id=auth.uid() or reviewer_user_id=auth.uid() or (project_id is not null and private.can_access_project(project_id)));
drop policy if exists audit_plans_manage on public.audit_plans;create policy audit_plans_manage on public.audit_plans for all to authenticated using(private.can_manage_audits()) with check(private.can_manage_audits());
drop policy if exists audit_runs_scope on public.audit_runs;create policy audit_runs_scope on public.audit_runs for select to authenticated using(private.can_read_audit(id));
drop policy if exists audit_runs_manage on public.audit_runs;create policy audit_runs_manage on public.audit_runs for all to authenticated using(private.can_manage_audits() or (private.can_execute_audits() and (responsible_user_id=auth.uid() or reviewer_user_id=auth.uid()))) with check(private.can_manage_audits() or (private.can_execute_audits() and (responsible_user_id=auth.uid() or reviewer_user_id=auth.uid())));
drop policy if exists audit_check_results_scope on public.audit_check_results;create policy audit_check_results_scope on public.audit_check_results for all to authenticated using(private.can_read_audit(audit_id)) with check(private.can_read_audit(audit_id) and private.can_execute_audits());
drop policy if exists audit_findings_scope on public.audit_findings;create policy audit_findings_scope on public.audit_findings for select to authenticated using(private.can_read_audit(audit_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or client_visibility='CLIENT_VISIBLE'));
drop policy if exists audit_findings_manage on public.audit_findings;create policy audit_findings_manage on public.audit_findings for all to authenticated using(private.can_manage_audits() or responsible_user_id=auth.uid() or (project_id is not null and private.can_access_project(project_id))) with check(private.can_manage_audits() or private.can_execute_audits() or responsible_user_id=auth.uid());
drop policy if exists audit_evidence_scope on public.audit_evidence;create policy audit_evidence_scope on public.audit_evidence for select to authenticated using(private.can_read_audit(audit_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or visibility='CLIENT_VISIBLE'));
drop policy if exists audit_evidence_manage on public.audit_evidence;create policy audit_evidence_manage on public.audit_evidence for insert to authenticated with check(private.can_read_audit(audit_id) and private.can_execute_audits());
drop policy if exists audit_remediations_scope on public.audit_remediations;create policy audit_remediations_scope on public.audit_remediations for all to authenticated using(exists(select 1 from public.audit_findings f where f.id=finding_id and private.can_read_audit(f.audit_id))) with check(exists(select 1 from public.audit_findings f where f.id=finding_id and private.can_read_audit(f.audit_id)));
drop policy if exists audit_retests_scope on public.audit_retests;create policy audit_retests_scope on public.audit_retests for all to authenticated using(exists(select 1 from public.audit_findings f where f.id=finding_id and private.can_read_audit(f.audit_id))) with check(private.can_execute_audits() and exists(select 1 from public.audit_findings f where f.id=finding_id and private.can_read_audit(f.audit_id)));
drop policy if exists audit_reports_scope on public.audit_reports;create policy audit_reports_scope on public.audit_reports for select to authenticated using(private.can_read_audit(audit_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or (report_type='CLIENT' and status='PUBLISHED')));
drop policy if exists audit_reports_manage on public.audit_reports;create policy audit_reports_manage on public.audit_reports for all to authenticated using(private.can_manage_audits() or private.can_execute_audits()) with check(private.can_manage_audits() or private.can_execute_audits());
drop policy if exists audit_events_scope on public.audit_events;create policy audit_events_scope on public.audit_events for select to authenticated using(audit_id is not null and private.can_read_audit(audit_id));
drop policy if exists audit_notifications_scope on public.audit_notifications;create policy audit_notifications_scope on public.audit_notifications for select to authenticated using(user_id=auth.uid() or audience_role=private.zyteron_role() or private.can_manage_audits());
drop policy if exists audit_idempotency_manage on public.audit_idempotency_keys;create policy audit_idempotency_manage on public.audit_idempotency_keys for all to authenticated using(private.can_manage_audits()) with check(private.can_manage_audits());

insert into public.app_permissions(code,description) values
('audit.dashboard.view','Ver Audit Command Center'),('audit.plan.view','Ver planes de auditoría'),('audit.plan.create','Crear planes de auditoría'),('audit.plan.edit','Editar planes de auditoría'),('audit.plan.disable','Desactivar planes de auditoría'),('audit.view','Ver auditorías'),('audit.create','Crear auditorías'),('audit.assign','Asignar auditorías'),('audit.execute','Ejecutar auditorías'),('audit.review','Revisar auditorías'),('audit.complete','Completar auditorías'),('finding.view','Ver hallazgos'),('finding.create','Crear hallazgos'),('finding.assign','Asignar hallazgos'),('finding.edit','Editar hallazgos'),('finding.resolve','Resolver hallazgos'),('finding.accept_risk','Aceptar riesgos'),('evidence.view','Ver evidencias'),('evidence.upload','Subir evidencias'),('retest.execute','Ejecutar retests'),('audit_report.view','Ver informes de auditoría'),('audit_report.generate','Generar informes de auditoría'),('audit_report.approve','Aprobar informes de auditoría'),('audit_report.publish','Publicar informes de auditoría'),('audit_template.view','Ver plantillas de auditoría'),('audit_template.manage','Gestionar plantillas de auditoría') on conflict(code) do update set description=excluded.description;
insert into public.role_permissions(role,permission_code) select r.role,p.code from(values('GERENTE_GENERAL'),('JEFE_DESARROLLO'),('TECH_LEAD'))r(role) cross join public.app_permissions p where p.code like any(array['audit.%','finding.%','evidence.%','retest.%','audit_report.%','audit_template.%']) on conflict do nothing;
insert into public.role_permissions(role,permission_code) select 'QA',code from public.app_permissions where code in('audit.dashboard.view','audit.plan.view','audit.view','audit.execute','audit.review','finding.view','finding.create','finding.edit','finding.resolve','evidence.view','evidence.upload','retest.execute','audit_report.view','audit_report.generate','audit_template.view') on conflict do nothing;
insert into public.role_permissions(role,permission_code) select r.role,p.code from(values('PROGRAMADOR'),('DESARROLLO'))r(role) cross join public.app_permissions p where p.code in('audit.dashboard.view','audit.view','finding.view','finding.edit','evidence.view') on conflict do nothing;
insert into public.role_permissions(role,permission_code) select r.role,p.code from(values('JEFE_VENTAS'),('EJECUTIVA_VENTAS'),('COMERCIAL'))r(role) cross join public.app_permissions p where p.code in('audit.dashboard.view','audit.view','finding.view','audit_report.view') on conflict do nothing;

insert into public.audit_templates(id,code,name,audit_type,description,active,current_version) values('a0000000-0000-4000-8000-000000000001','WEB-BASE','Revisión web integral','WEB_GENERAL','Base segura para disponibilidad, HTTPS, cabeceras, calidad funcional y backup.',true,1) on conflict(code) do nothing;
insert into public.audit_template_versions(id,template_id,version,status,change_summary,published_at) values('a0000000-0000-4000-8000-000000000002','a0000000-0000-4000-8000-000000000001',1,'DRAFT','Versión inicial controlada',null) on conflict(template_id,version) do nothing;
insert into public.audit_template_sections(id,template_version_id,code,title,weight,sort_order) values
('a0000000-0000-4000-8000-000000000010','a0000000-0000-4000-8000-000000000002','SECURITY','Seguridad defensiva',35,1),('a0000000-0000-4000-8000-000000000011','a0000000-0000-4000-8000-000000000002','PERFORMANCE','Disponibilidad y respuesta',35,2),('a0000000-0000-4000-8000-000000000012','a0000000-0000-4000-8000-000000000002','QUALITY','Calidad funcional',30,3) on conflict(template_version_id,code) do nothing;
insert into public.audit_template_checks(template_version_id,section_id,code,title,check_type,required,weight,severity_on_failure,automation_key,auto_create_finding,evidence_required,sort_order) values
('a0000000-0000-4000-8000-000000000002','a0000000-0000-4000-8000-000000000010','HTTPS','HTTPS activo','AUTOMATED',true,15,'HIGH','SSL',true,false,1),('a0000000-0000-4000-8000-000000000002','a0000000-0000-4000-8000-000000000010','HEADERS','Cabeceras defensivas','AUTOMATED',true,20,'MEDIUM','SECURITY_HEADERS',true,false,2),('a0000000-0000-4000-8000-000000000002','a0000000-0000-4000-8000-000000000011','HTTP','Disponibilidad HTTP','AUTOMATED',true,20,'HIGH','HTTP_AVAILABILITY',true,false,1),('a0000000-0000-4000-8000-000000000002','a0000000-0000-4000-8000-000000000011','LATENCY','Tiempo de respuesta','AUTOMATED',true,15,'MEDIUM','RESPONSE_TIME',true,false,2),('a0000000-0000-4000-8000-000000000002','a0000000-0000-4000-8000-000000000012','FORMS','Formularios y validaciones','MANUAL',true,15,'HIGH',null,true,true,1),('a0000000-0000-4000-8000-000000000002','a0000000-0000-4000-8000-000000000012','BACKUP','Backup reciente y restauración verificada','MANUAL',true,15,'HIGH',null,true,true,2) on conflict(template_version_id,code) do nothing;
update public.audit_template_versions set status='PUBLISHED',published_at=now() where id='a0000000-0000-4000-8000-000000000002' and status='DRAFT';

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('audit-evidence','audit-evidence',false,20971520,array['image/png','image/jpeg','application/pdf','text/plain']),('audit-reports','audit-reports',false,20971520,array['application/pdf']) on conflict(id) do nothing;
drop policy if exists audit_storage_read on storage.objects;create policy audit_storage_read on storage.objects for select to authenticated using(bucket_id in('audit-evidence','audit-reports') and private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD','QA'));
drop policy if exists audit_storage_write on storage.objects;create policy audit_storage_write on storage.objects for insert to authenticated with check(bucket_id in('audit-evidence','audit-reports') and private.can_execute_audits());

do $$declare t text;begin foreach t in array array['audit_runs','audit_check_results','audit_findings','audit_remediations','audit_retests','audit_reports','audit_events'] loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then execute format('alter publication supabase_realtime add table public.%I',t);end if;end loop;end$$;

commit;
