begin;
create extension if not exists pgcrypto;
create schema if not exists private;
create sequence if not exists public.employee_number_seq;
create sequence if not exists public.employment_contract_number_seq;
create or replace function public.next_employee_number()returns text language sql volatile set search_path=public as $$select 'EMP-'||lpad(nextval('public.employee_number_seq')::text,6,'0')$$;
create or replace function public.next_employment_contract_number()returns text language sql volatile set search_path=public as $$select 'CTR-LAB-'||extract(year from now())::integer||'-'||lpad(nextval('public.employment_contract_number_seq')::text,6,'0')$$;

create table if not exists public.employees(id uuid primary key default gen_random_uuid(),user_id uuid unique,employee_number text not null unique default public.next_employee_number(),rut text not null unique,first_name text not null,middle_name text,last_name text not null,second_last_name text,preferred_name text,personal_email text,corporate_email text,phone text,birth_date date,nationality text,address text,region text,commune text,emergency_contact jsonb not null default '{}',status text not null default 'PRE_HIRE' check(status in('PRE_HIRE','ONBOARDING','ACTIVE','LEAVE','SUSPENDED','OFFBOARDING','TERMINATED','ARCHIVED')),hire_date date,termination_date date,privacy_level text not null default 'HR_CONFIDENTIAL',archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(termination_date is null or hire_date is null or termination_date>=hire_date));
create table if not exists public.departments(id uuid primary key default gen_random_uuid(),name text not null,code text not null unique,manager_id uuid references public.employees(id) on delete restrict,parent_department_id uuid references public.departments(id) on delete restrict,cost_center_id uuid,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.teams(id uuid primary key default gen_random_uuid(),department_id uuid not null references public.departments(id) on delete restrict,name text not null,team_lead_id uuid references public.employees(id) on delete restrict,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(department_id,name));
create table if not exists public.job_positions(id uuid primary key default gen_random_uuid(),name text not null,code text not null unique,department_id uuid references public.departments(id) on delete restrict,description text,level text,reports_to_position_id uuid references public.job_positions(id) on delete restrict,default_permissions_profile text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.team_members(id uuid primary key default gen_random_uuid(),team_id uuid not null references public.teams(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,membership_type text not null default 'ADDITIONAL',started_at date not null default current_date,ended_at date,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(team_id,employee_id,started_at));
create table if not exists public.employment_relationships(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,company_entity_id uuid,employment_type text not null check(employment_type in('INDEFINITE','FIXED_TERM','PART_TIME','INTERNSHIP','OTHER_LEGAL_RELATIONSHIP')),start_date date not null,end_date date,status text not null default 'PLANNED' check(status in('PLANNED','ACTIVE','SUSPENDED','ENDED')),job_position_id uuid references public.job_positions(id) on delete restrict,department_id uuid references public.departments(id) on delete restrict,team_id uuid references public.teams(id) on delete restrict,manager_id uuid references public.employees(id) on delete restrict,work_location text,cost_center_id uuid,weekly_hours numeric(6,2) check(weekly_hours is null or weekly_hours>0),schedule_type text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or end_date>=start_date));
create unique index if not exists employment_relationship_active_unique on public.employment_relationships(employee_id)where status='ACTIVE';
create index if not exists employees_status_idx on public.employees(status);create index if not exists employees_rut_idx on public.employees(rut);create index if not exists employment_relationship_org_idx on public.employment_relationships(department_id,team_id,manager_id,status);
create table if not exists public.employee_position_history(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,value_id uuid not null,effective_from date not null,effective_to date,source text not null,source_id uuid,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employee_department_history(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,value_id uuid not null,effective_from date not null,effective_to date,source text not null,source_id uuid,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employee_manager_history(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,value_id uuid not null,effective_from date not null,effective_to date,source text not null,source_id uuid,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.employment_contracts(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,employment_relationship_id uuid not null references public.employment_relationships(id) on delete restrict,contract_number text not null unique default public.next_employment_contract_number(),contract_type text not null,status text not null default 'DRAFT' check(status in('DRAFT','IN_REVIEW','READY_FOR_SIGNATURE','SIGNATURE_REQUESTED','PARTIALLY_SIGNED','SIGNED','PENDING_DT_REGISTRATION','REGISTERED','ACTIVE','EXPIRED','TERMINATED','SUPERSEDED','CANCELLED')),start_date date not null,end_date date,position_id uuid references public.job_positions(id) on delete restrict,department_id uuid references public.departments(id) on delete restrict,work_location text,weekly_hours numeric(6,2),schedule_definition jsonb not null default '{}',base_salary numeric(18,2) check(base_salary is null or base_salary>=0),currency char(3) not null default 'CLP',payment_frequency text not null default 'MONTHLY',document_id uuid references public.documents(id) on delete restrict,signature_status text not null default 'NOT_REQUESTED',signature_provider text,signed_at timestamptz,dt_registration_status text not null default 'NOT_READY',dt_registration_reference text,dt_registered_at timestamptz,dt_receipt_document_id uuid references public.documents(id) on delete restrict,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or end_date>=start_date));
create index if not exists employment_contract_status_idx on public.employment_contracts(status,end_date);create index if not exists employment_contract_employee_idx on public.employment_contracts(employee_id,start_date desc);
create table if not exists public.employment_annexes(id uuid primary key default gen_random_uuid(),employment_contract_id uuid not null references public.employment_contracts(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,document_id uuid references public.documents(id) on delete restrict,annex_type text not null check(annex_type in('SALARY_CHANGE','POSITION_CHANGE','SCHEDULE_CHANGE','REMOTE_WORK','BENEFIT_CHANGE','LOCATION_CHANGE','OTHER')),effective_date date not null,status text not null default 'DRAFT' check(status in('DRAFT','IN_REVIEW','READY_FOR_SIGNATURE','SIGNATURE_REQUESTED','SIGNED','ACTIVE','SUPERSEDED','CANCELLED')),payload jsonb not null default '{}',signature_request_id uuid references public.signature_requests(id) on delete restrict,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.onboarding_templates(id uuid primary key default gen_random_uuid(),name text not null,position_id uuid references public.job_positions(id) on delete restrict,department_id uuid references public.departments(id) on delete restrict,tasks jsonb not null default '[]',active boolean not null default true,version integer not null default 1,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.onboarding_instances(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,template_id uuid references public.onboarding_templates(id) on delete restrict,status text not null default 'NOT_STARTED' check(status in('NOT_STARTED','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED')),target_date date,progress numeric(5,2) not null default 0 check(progress between 0 and 100),started_at timestamptz,completed_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.onboarding_tasks(id uuid primary key default gen_random_uuid(),onboarding_id uuid not null references public.onboarding_instances(id) on delete restrict,title text not null,owner_type text not null check(owner_type in('HR','SECURITY','MANAGER','IT','EMPLOYEE','FINANCE')),owner_id uuid,status text not null default 'PENDING' check(status in('PENDING','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED')),due_date date,critical boolean not null default true,position integer not null,completed_at timestamptz,completed_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.offboarding_instances(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,effective_date date not null,reason_category text not null,status text not null default 'INITIATED' check(status in('INITIATED','APPROVED','IN_PROGRESS','BLOCKED','READY_TO_FINALIZE','COMPLETED','CANCELLED')),critical_blockers integer not null default 0,started_at timestamptz not null default now(),completed_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.offboarding_tasks(id uuid primary key default gen_random_uuid(),offboarding_id uuid not null references public.offboarding_instances(id) on delete restrict,title text not null,owner_type text not null,owner_id uuid,status text not null default 'PENDING' check(status in('PENDING','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED')),critical boolean not null default true,position integer not null,notes text,evidence_document_id uuid references public.documents(id) on delete restrict,completed_at timestamptz,completed_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.leave_policies(id uuid primary key default gen_random_uuid(),code text not null,version integer not null,effective_from date not null,effective_to date,rules jsonb not null,source_reference text,status text not null default 'DRAFT' check(status in('DRAFT','PUBLISHED','RETIRED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(code,version));
create table if not exists public.leave_requests(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,leave_type text not null check(leave_type in('VACATION','ADMINISTRATIVE_LEAVE','UNPAID_LEAVE','MEDICAL_LEAVE','OTHER')),start_date date not null,end_date date not null,requested_units numeric(8,2) not null check(requested_units>0),unit text not null default 'DAYS' check(unit in('DAYS','HOURS','HALF_DAY')),status text not null default 'DRAFT' check(status in('DRAFT','PENDING_MANAGER','PENDING_HR','APPROVED','REJECTED','CANCELLED')),approver_id uuid,submitted_at timestamptz,approved_at timestamptz,reason_category text,decision_reason text,document_id uuid references public.documents(id) on delete restrict,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date));
create index if not exists leave_requests_dates_idx on public.leave_requests(employee_id,start_date,end_date,status);
create table if not exists public.leave_balances(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,policy_id uuid references public.leave_policies(id) on delete restrict,period text not null,accrued numeric(10,2) not null default 0,used numeric(10,2) not null default 0,adjusted numeric(10,2) not null default 0,available numeric(10,2) not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(employee_id,period));
create table if not exists public.leave_ledger(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,leave_request_id uuid references public.leave_requests(id) on delete restrict,entry_type text not null check(entry_type in('ACCRUAL','USED','ADJUSTMENT','CARRYOVER','EXPIRATION')),units numeric(10,2) not null,entry_date date not null,reason text not null,actor_id uuid,balance_after numeric(10,2),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.medical_leave_records(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,start_date date not null,end_date date not null,days integer not null check(days>0),status text not null check(status in('RECEIVED','REVIEW','ACCEPTED','REJECTED','CLOSED')),issuer_reference text,document_id uuid references public.documents(id) on delete restrict,received_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date));

create table if not exists public.work_schedules(id uuid primary key default gen_random_uuid(),name text not null,weekly_hours numeric(6,2) not null,timezone text not null default 'America/Santiago',schedule_type text not null,rules jsonb not null default '{}',active boolean not null default true,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employee_schedules(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,schedule_id uuid not null references public.work_schedules(id) on delete restrict,effective_from date not null,effective_to date,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.shift_assignments(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,work_date date not null,start_time time not null,end_time time not null,cross_midnight boolean not null default false,schedule_id uuid references public.work_schedules(id) on delete restrict,status text not null default 'PLANNED',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(employee_id,work_date));

create table if not exists public.employee_compensation_history(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,effective_from date not null,effective_to date,base_salary numeric(18,2) not null check(base_salary>=0),currency char(3) not null,pay_frequency text not null,contract_reference uuid references public.employment_contracts(id) on delete restrict,annex_id uuid references public.employment_annexes(id) on delete restrict,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.earning_concepts(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,classification jsonb not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.deduction_concepts(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,classification jsonb not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employer_contribution_concepts(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,classification jsonb not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.payroll_rules(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.payroll_rule_versions(id uuid primary key default gen_random_uuid(),payroll_rule_id uuid references public.payroll_rules(id) on delete restrict,version integer not null,effective_from date not null,effective_to date,parameters jsonb not null,source_reference text not null,status text not null default 'DRAFT' check(status in('DRAFT','PUBLISHED','RETIRED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(payroll_rule_id,version));
create table if not exists public.payroll_periods(id uuid primary key default gen_random_uuid(),period text not null unique check(period~'^\d{4}-(0[1-9]|1[0-2])$'),status text not null default 'OPEN' check(status in('OPEN','CALCULATING','REVIEW','APPROVED','PAID','REPORTED','CLOSED')),payment_date date,rule_version_id uuid references public.payroll_rule_versions(id) on delete restrict,totals jsonb not null default '{}',approved_by uuid,approved_at timestamptz,finance_reference text,paid_at timestamptz,created_by uuid,created_at timestamptz not null default now(),closed_at timestamptz,updated_at timestamptz not null default now());
create table if not exists public.payroll_employee_results(id uuid primary key default gen_random_uuid(),payroll_period_id uuid not null references public.payroll_periods(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,gross_total numeric(18,2) not null,deduction_total numeric(18,2) not null,employer_contribution_total numeric(18,2) not null,taxable_total numeric(18,2) not null,net_total numeric(18,2) not null,employer_cost numeric(18,2) not null,currency char(3) not null,calculation_snapshot jsonb not null,status text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(payroll_period_id,employee_id));
create table if not exists public.payroll_lines(id uuid primary key default gen_random_uuid(),payroll_result_id uuid not null references public.payroll_employee_results(id) on delete restrict,concept_type text not null check(concept_type in('EARNING','DEDUCTION','EMPLOYER_CONTRIBUTION')),concept_id uuid,code text not null,description text not null,amount numeric(18,2) not null,calculation_basis jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.pay_slips(id uuid primary key default gen_random_uuid(),payroll_period_id uuid not null references public.payroll_periods(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,payroll_result_id uuid not null references public.payroll_employee_results(id) on delete restrict,document_id uuid not null references public.documents(id) on delete restrict,sha256 text not null,status text not null default 'ISSUED',issued_at timestamptz not null,acknowledged_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(payroll_period_id,employee_id));

create table if not exists public.lre_schema_versions(id uuid primary key default gen_random_uuid(),code text not null,version integer not null,effective_from date not null,effective_to date,delimiter text not null default ';',column_definitions jsonb not null,source_reference text not null,status text not null default 'DRAFT' check(status in('DRAFT','PUBLISHED','RETIRED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(code,version));
create table if not exists public.lre_exports(id uuid primary key default gen_random_uuid(),payroll_period_id uuid not null unique references public.payroll_periods(id) on delete restrict,schema_version_id uuid not null references public.lre_schema_versions(id) on delete restrict,status text not null check(status in('NOT_READY','READY','VALIDATION_ERROR','READY_TO_SUBMIT','SUBMITTED_EXTERNALLY','VALIDATING','DECLARED','RECTIFICATION_REQUIRED','RECTIFIED')),document_id uuid references public.documents(id) on delete restrict,receipt_document_id uuid references public.documents(id) on delete restrict,sha256 text,validation_errors text[] not null default '{}',external_reference text,generated_at timestamptz,submitted_at timestamptz,declared_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.compliance_rules(id uuid primary key default gen_random_uuid(),rule_type text not null,version integer not null,effective_from date not null,effective_to date,parameters jsonb not null,source_reference text not null,active boolean not null default false,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(rule_type,version));
create table if not exists public.labor_compliance_tasks(id uuid primary key default gen_random_uuid(),employee_id uuid references public.employees(id) on delete restrict,contract_id uuid references public.employment_contracts(id) on delete restrict,task_type text not null,due_date date,status text not null,responsible_id uuid,evidence_document_id uuid references public.documents(id) on delete restrict,source_reference text,compliance_rule_id uuid references public.compliance_rules(id) on delete restrict,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.company_assets(id uuid primary key default gen_random_uuid(),asset_code text not null unique,name text not null,asset_type text not null,serial_number text,status text not null default 'AVAILABLE',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.asset_assignments(id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.company_assets(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,assigned_at timestamptz not null,condition_out text,evidence_document_id uuid references public.documents(id) on delete restrict,returned_at timestamptz,condition_return text,return_evidence_document_id uuid references public.documents(id) on delete restrict,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists asset_assignment_open_unique on public.asset_assignments(asset_id)where returned_at is null;
create table if not exists public.performance_cycles(id uuid primary key default gen_random_uuid(),name text not null,start_date date not null,end_date date not null,status text not null,configuration jsonb not null default '{}',created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.performance_reviews(id uuid primary key default gen_random_uuid(),cycle_id uuid not null references public.performance_cycles(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,reviewer_id uuid,review_type text not null check(review_type in('MANAGER','SELF','PEER_360','PROBATION')),status text not null,answers jsonb not null default '{}',submitted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employee_goals(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete restrict,title text not null,description text,period text not null,owner_id uuid,status text not null check(status in('DRAFT','ACTIVE','AT_RISK','COMPLETED','CANCELLED')),progress numeric(5,2) not null default 0 check(progress between 0 and 100),evidence jsonb not null default '{}',created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.competencies(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.training_courses(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text,required_for_role text,validity_days integer,active boolean not null default true,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.training_assignments(id uuid primary key default gen_random_uuid(),course_id uuid not null references public.training_courses(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,status text not null check(status in('ASSIGNED','IN_PROGRESS','COMPLETED','EXPIRED')),assigned_at timestamptz not null,due_date date,completed_at timestamptz,certificate_document_id uuid references public.documents(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.training_records(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.training_assignments(id) on delete restrict,event_type text not null,payload jsonb not null default '{}',occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.hr_events(id uuid primary key default gen_random_uuid(),employee_id uuid references public.employees(id) on delete restrict,aggregate_type text not null,aggregate_id uuid not null,event_type text not null,actor_id uuid,payload jsonb not null default '{}',occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create or replace function public.prevent_closed_payroll_mutation()returns trigger language plpgsql as $$begin if old.status='CLOSED'and row(new.period,new.rule_version_id,new.totals)is distinct from row(old.period,old.rule_version_id,old.totals)then raise exception 'Un período cerrado es inmutable';end if;return new;end$$;
drop trigger if exists payroll_period_closed_immutable on public.payroll_periods;create trigger payroll_period_closed_immutable before update on public.payroll_periods for each row execute function public.prevent_closed_payroll_mutation();
create or replace function public.hr_event_to_outbox()returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.business_event_outbox(aggregate_type,aggregate_id,event_type,payload)values(new.aggregate_type,new.aggregate_id,new.event_type,jsonb_build_object('employeeId',new.employee_id,'hrEventId',new.id)||new.payload);return new;end$$;
drop trigger if exists hr_events_outbox on public.hr_events;create trigger hr_events_outbox after insert on public.hr_events for each row execute function public.hr_event_to_outbox();

create or replace function private.hr_employee_id()returns uuid language sql stable security definer set search_path=public as $$select id from public.employees where user_id=auth.uid()limit 1$$;
create or replace function private.hr_is_hr()returns boolean language sql stable as $$select private.zyteron_role()='RRHH'$$;
create or replace function private.hr_can_view_employee(target uuid)returns boolean language sql stable security definer set search_path=public as $$select private.hr_is_hr()or(private.zyteron_role()='GERENTE_GENERAL')or target=private.hr_employee_id()or exists(select 1 from public.employment_relationships r where r.employee_id=target and r.status='ACTIVE'and r.manager_id=private.hr_employee_id())$$;
create or replace function private.hr_can_manage()returns boolean language sql stable as $$select private.hr_is_hr()$$;

do $$declare t text;begin foreach t in array array['employees','departments','teams','job_positions','team_members','employment_relationships','employee_position_history','employee_department_history','employee_manager_history','employment_contracts','employment_annexes','onboarding_templates','onboarding_instances','onboarding_tasks','offboarding_instances','offboarding_tasks','leave_policies','leave_requests','leave_balances','leave_ledger','medical_leave_records','work_schedules','employee_schedules','shift_assignments','employee_compensation_history','earning_concepts','deduction_concepts','employer_contribution_concepts','payroll_rules','payroll_rule_versions','payroll_periods','payroll_employee_results','payroll_lines','pay_slips','lre_schema_versions','lre_exports','compliance_rules','labor_compliance_tasks','company_assets','asset_assignments','performance_cycles','performance_reviews','employee_goals','competencies','training_courses','training_assignments','training_records','hr_events']loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
drop policy if exists employees_read on public.employees;create policy employees_read on public.employees for select to authenticated using(private.hr_is_hr()or id=private.hr_employee_id());drop policy if exists employees_manage on public.employees;create policy employees_manage on public.employees for all to authenticated using(private.hr_can_manage())with check(private.hr_can_manage());
do $$declare t text;begin foreach t in array array['employment_relationships','employee_position_history','employee_department_history','employee_manager_history','employment_contracts','employment_annexes','onboarding_instances','offboarding_instances','leave_requests','leave_balances','leave_ledger','employee_schedules','shift_assignments','asset_assignments','performance_reviews','employee_goals','training_assignments']loop execute format('drop policy if exists %I on public.%I',t||'_read',t);execute format('create policy %I on public.%I for select to authenticated using(private.hr_can_view_employee(employee_id))',t||'_read',t);execute format('drop policy if exists %I on public.%I',t||'_manage',t);execute format('create policy %I on public.%I for all to authenticated using(private.hr_can_manage())with check(private.hr_can_manage())',t||'_manage',t);end loop;end$$;
drop policy if exists employment_contracts_read on public.employment_contracts;create policy employment_contracts_read on public.employment_contracts for select to authenticated using(private.hr_is_hr()or employee_id=private.hr_employee_id());
drop policy if exists employment_annexes_read on public.employment_annexes;create policy employment_annexes_read on public.employment_annexes for select to authenticated using(private.hr_is_hr()or employee_id=private.hr_employee_id());
drop policy if exists compensation_read on public.employee_compensation_history;create policy compensation_read on public.employee_compensation_history for select to authenticated using(private.hr_is_hr()or employee_id=private.hr_employee_id());drop policy if exists compensation_manage on public.employee_compensation_history;create policy compensation_manage on public.employee_compensation_history for all to authenticated using(private.hr_is_hr())with check(private.hr_is_hr());
drop policy if exists medical_leave_read on public.medical_leave_records;create policy medical_leave_read on public.medical_leave_records for select to authenticated using(private.hr_is_hr()or employee_id=private.hr_employee_id());drop policy if exists medical_leave_manage on public.medical_leave_records;create policy medical_leave_manage on public.medical_leave_records for all to authenticated using(private.hr_is_hr())with check(private.hr_is_hr());
drop policy if exists payroll_period_read on public.payroll_periods;create policy payroll_period_read on public.payroll_periods for select to authenticated using(private.zyteron_role()in('RRHH','FINANZAS'));drop policy if exists payroll_period_manage on public.payroll_periods;create policy payroll_period_manage on public.payroll_periods for all to authenticated using(private.hr_is_hr())with check(private.hr_is_hr());
drop policy if exists payroll_result_read on public.payroll_employee_results;create policy payroll_result_read on public.payroll_employee_results for select to authenticated using(private.hr_is_hr()or employee_id=private.hr_employee_id());drop policy if exists payroll_result_manage on public.payroll_employee_results;create policy payroll_result_manage on public.payroll_employee_results for all to authenticated using(private.hr_is_hr())with check(private.hr_is_hr());
drop policy if exists pay_slip_read on public.pay_slips;create policy pay_slip_read on public.pay_slips for select to authenticated using(private.hr_is_hr()or employee_id=private.hr_employee_id());drop policy if exists pay_slip_manage on public.pay_slips;create policy pay_slip_manage on public.pay_slips for all to authenticated using(private.hr_is_hr())with check(private.hr_is_hr());
do $$declare t text;begin foreach t in array array['departments','teams','job_positions','onboarding_templates','leave_policies','work_schedules','earning_concepts','deduction_concepts','employer_contribution_concepts','payroll_rules','payroll_rule_versions','lre_schema_versions','compliance_rules','company_assets','performance_cycles','competencies','training_courses']loop execute format('drop policy if exists %I on public.%I',t||'_read',t);execute format('create policy %I on public.%I for select to authenticated using(private.zyteron_role() is not null)',t||'_read',t);execute format('drop policy if exists %I on public.%I',t||'_manage',t);execute format('create policy %I on public.%I for all to authenticated using(private.hr_can_manage())with check(private.hr_can_manage())',t||'_manage',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['onboarding_tasks','offboarding_tasks','payroll_lines','training_records']loop execute format('drop policy if exists %I on public.%I',t||'_hr',t);execute format('create policy %I on public.%I for all to authenticated using(private.hr_is_hr())with check(private.hr_is_hr())',t||'_hr',t);end loop;end$$;
drop policy if exists lre_exports_scope on public.lre_exports;create policy lre_exports_scope on public.lre_exports for all to authenticated using(private.zyteron_role()in('RRHH','FINANZAS'))with check(private.hr_is_hr());drop policy if exists compliance_tasks_scope on public.labor_compliance_tasks;create policy compliance_tasks_scope on public.labor_compliance_tasks for all to authenticated using(private.hr_is_hr())with check(private.hr_is_hr());drop policy if exists hr_events_read on public.hr_events;create policy hr_events_read on public.hr_events for select to authenticated using(employee_id is null and private.hr_is_hr()or employee_id is not null and private.hr_can_view_employee(employee_id));drop policy if exists hr_events_write on public.hr_events;create policy hr_events_write on public.hr_events for insert to authenticated with check(private.hr_can_manage());

insert into public.app_permissions(code,description)values('hr.dashboard.view','Ver People Command Center'),('employee.view','Ver colaboradores'),('employee.create','Crear colaboradores'),('employee.edit','Editar colaboradores'),('employee.archive','Archivar colaboradores'),('employee.compensation.view','Ver remuneración'),('employee.compensation.manage','Gestionar remuneración'),('org.view','Ver organización'),('org.manage','Gestionar organización'),('contract.view','Ver contratos laborales'),('contract.create','Crear contratos laborales'),('contract.edit','Editar contratos laborales'),('contract.review','Revisar contratos laborales'),('contract.request_signature','Solicitar firma contractual'),('contract.register_external','Registrar evidencia REL externa'),('annex.view','Ver anexos'),('annex.create','Crear anexos'),('annex.request_signature','Solicitar firma de anexos'),('employee_documents.view','Ver expediente laboral'),('employee_documents.manage','Gestionar expediente laboral'),('onboarding.view','Ver onboarding'),('onboarding.manage','Gestionar onboarding'),('offboarding.view','Ver offboarding'),('offboarding.manage','Gestionar offboarding'),('leave.view','Ver ausencias'),('leave.request','Solicitar ausencia'),('leave.approve','Aprobar ausencia'),('leave.adjust_balance','Ajustar saldo'),('medical_leave.view','Ver licencias médicas'),('medical_leave.manage','Gestionar licencias médicas'),('attendance.view','Ver asistencia'),('attendance.manage','Gestionar asistencia'),('payroll.view','Ver payroll'),('payroll.calculate','Calcular payroll'),('payroll.review','Revisar payroll'),('payroll.approve','Aprobar payroll'),('payroll.close','Cerrar payroll'),('lre.view','Ver LRE'),('lre.generate','Generar LRE'),('lre.mark_submitted','Registrar presentación LRE'),('performance.view','Ver desempeño'),('performance.manage','Gestionar desempeño'),('training.view','Ver capacitación'),('training.manage','Gestionar capacitación'),('hr_reports.view','Ver informes RR.HH.'),('hr_reports.export','Exportar informes RR.HH.'),('hr_settings.manage','Configurar RR.HH.')on conflict(code)do update set description=excluded.description;
insert into public.role_permissions(role,permission_code)select'RRHH',code from public.app_permissions where code like'hr.%'or code like'employee.%'or code like'org.%'or code like'contract.%'or code like'annex.%'or code like'onboarding.%'or code like'offboarding.%'or code like'leave.%'or code like'medical_leave.%'or code like'attendance.%'or code like'payroll.%'or code like'lre.%'or code like'performance.%'or code like'training.%'on conflict do nothing;
insert into public.role_permissions(role,permission_code)select r.role,p.code from(values('GERENTE_GENERAL'),('JEFE_DESARROLLO'),('TECH_LEAD'),('OPERACIONES'),('JEFE_VENTAS'))r(role)cross join public.app_permissions p where p.code in('hr.dashboard.view','employee.view','org.view','onboarding.view','offboarding.view','leave.view','leave.approve','performance.view','training.view')on conflict do nothing;
insert into public.role_permissions(role,permission_code)select'FINANZAS',code from public.app_permissions where code in('payroll.view','lre.view')on conflict do nothing;

do $$declare t text;begin foreach t in array array['employees','employment_relationships','employment_contracts','employment_annexes','onboarding_instances','onboarding_tasks','offboarding_instances','offboarding_tasks','leave_requests','leave_balances','medical_leave_records','payroll_periods','payroll_employee_results','pay_slips','lre_exports','labor_compliance_tasks','asset_assignments','performance_reviews','employee_goals','training_assignments','hr_events']loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename=t)then execute format('alter publication supabase_realtime add table public.%I',t);end if;end loop;end$$;
commit;
