begin;
create extension if not exists pgcrypto;
create schema if not exists private;
create sequence if not exists public.document_number_seq;
create or replace function public.next_document_number() returns text language sql volatile set search_path=public as $$select 'DOC-'||extract(year from now())::integer||'-'||lpad(nextval('public.document_number_seq')::text,6,'0')$$;

create table if not exists public.document_retention_policies(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,retention_days integer not null check(retention_days>=0),trash_grace_days integer not null default 30 check(trash_grace_days>=1),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.document_types(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text,max_size_bytes bigint not null default 52428800 check(max_size_bytes>0),allowed_mime_types text[] not null default '{}',requires_approval boolean not null default false,allows_client_sharing boolean not null default true,retention_policy_id uuid references public.document_retention_policies(id) on delete restrict,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.documents(id uuid primary key default gen_random_uuid(),document_number text unique,title text not null,description text,type_id uuid not null references public.document_types(id) on delete restrict,classification text not null default 'INTERNAL' check(classification in('PUBLIC','CLIENT','INTERNAL','CONFIDENTIAL','RESTRICTED','CRITICAL')),status text not null default 'DRAFT' check(status in('DRAFT','IN_REVIEW','CHANGES_REQUESTED','APPROVED','READY_FOR_SIGNATURE','SIGNING','SIGNED','PUBLISHED','SUPERSEDED','ARCHIVED','REJECTED','TRASHED')),owner_id uuid,current_version_id uuid,current_version_number integer not null default 0 check(current_version_number>=0),client_visible boolean not null default false,expires_at timestamptz,retention_policy_id uuid references public.document_retention_policies(id) on delete restrict,legal_hold boolean not null default false,archived_at timestamptz,trashed_at timestamptz,purge_after timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(not client_visible or classification in('PUBLIC','CLIENT')));
create table if not exists public.document_versions(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,version_number integer not null check(version_number>0),filename text not null,storage_path text not null,mime_type text not null,detected_mime_type text,size_bytes bigint not null check(size_bytes>0),sha256 text not null check(sha256~'^[0-9a-f]{64}$'),malware_status text not null default 'PENDING' check(malware_status in('PENDING','CLEAN','SUSPICIOUS','INFECTED','SCAN_FAILED','NOT_CONFIGURED')),status text not null default 'AVAILABLE' check(status in('AVAILABLE','LOCKED','QUARANTINED','REJECTED')),change_summary text,locked_at timestamptz,signed_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(document_id,version_number));
alter table public.documents drop constraint if exists documents_current_version_fk;
alter table public.documents add constraint documents_current_version_fk foreign key(current_version_id) references public.document_versions(id) on delete restrict not valid;
create index if not exists documents_search_idx on public.documents using gin(to_tsvector('spanish',coalesce(title,'')||' '||coalesce(description,'')||' '||coalesce(document_number,'')));
create index if not exists documents_attention_idx on public.documents(status,expires_at) where trashed_at is null;
create index if not exists document_versions_hash_idx on public.document_versions(sha256);

create table if not exists public.document_links(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,link_type text not null check(link_type in('CLIENT','PROJECT','CONTRACT','QUOTE','WORK_ORDER','FINANCE','AUDIT','SUPPORT','DEVELOPMENT','MONITORING','HR','OTHER')),linked_id uuid not null,label text,primary_link boolean not null default false,created_by uuid,created_at timestamptz not null default now(),unique(document_id,link_type,linked_id));
create index if not exists document_links_entity_idx on public.document_links(link_type,linked_id,document_id);
create table if not exists public.document_relationships(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,related_document_id uuid not null references public.documents(id) on delete restrict,relationship_type text not null check(relationship_type in('ANNEX','REPLACES','REFERENCES','EVIDENCE_FOR','DERIVED_FROM','RELATED')),created_by uuid,created_at timestamptz not null default now(),check(document_id<>related_document_id),unique(document_id,related_document_id,relationship_type));
create table if not exists public.document_tags(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,tag text not null,created_by uuid,created_at timestamptz not null default now(),unique(document_id,tag));
create table if not exists public.document_assignments(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,user_id uuid not null,assignment_type text not null check(assignment_type in('OWNER','EDITOR','REVIEWER','APPROVER','OBSERVER')),created_at timestamptz not null default now(),unique(document_id,user_id,assignment_type));
create table if not exists public.document_permissions(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,subject_type text not null check(subject_type in('USER','ROLE','CLIENT_CONTACT')),subject_id text not null,permission text not null check(permission in('VIEW','DOWNLOAD','EDIT','REVIEW','APPROVE','SHARE','MANAGE')),granted_by uuid,created_at timestamptz not null default now(),unique(document_id,subject_type,subject_id,permission));
create table if not exists public.document_reviews(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,version_id uuid not null references public.document_versions(id) on delete restrict,reviewer_id uuid not null,sequence integer not null default 1 check(sequence>0),mode text not null default 'SEQUENTIAL' check(mode in('SEQUENTIAL','PARALLEL')),status text not null default 'PENDING' check(status in('PENDING','APPROVED','CHANGES_REQUESTED','REJECTED','CANCELLED')),comment text,decided_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(version_id,reviewer_id));
create table if not exists public.document_approvals(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,version_id uuid not null references public.document_versions(id) on delete restrict,approver_id uuid not null,status text not null default 'PENDING' check(status in('PENDING','APPROVED','REJECTED','CANCELLED')),comment text,decided_at timestamptz,created_at timestamptz not null default now(),unique(version_id,approver_id));

create table if not exists public.signature_requests(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,version_id uuid not null references public.document_versions(id) on delete restrict,provider text not null,provider_request_id text,status text not null check(status in('NOT_CONFIGURED','DRAFT','SENT','IN_PROGRESS','COMPLETED','DECLINED','CANCELLED','EXPIRED','FAILED')),frozen_sha256 text not null,evidence jsonb not null default '{}',created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider,provider_request_id));
create table if not exists public.signature_signers(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.signature_requests(id) on delete restrict,name text not null,email text not null,signing_order integer not null default 1,status text not null default 'PENDING' check(status in('PENDING','SENT','VIEWED','SIGNED','DECLINED','FAILED')),signed_at timestamptz,evidence jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists public.signature_events(id uuid primary key default gen_random_uuid(),provider text not null,event_id text not null,provider_request_id text,event_type text not null,payload jsonb not null default '{}',occurred_at timestamptz not null default now(),unique(provider,event_id));

alter table public.document_templates add column if not exists description text;
alter table public.document_templates add column if not exists classification text not null default 'INTERNAL';
alter table public.document_templates add column if not exists created_by uuid;
alter table public.document_templates drop constraint if exists document_templates_classification_check;
alter table public.document_templates add constraint document_templates_classification_check check(classification in('PUBLIC','CLIENT','INTERNAL','CONFIDENTIAL','RESTRICTED','CRITICAL'));
create table if not exists public.document_template_versions(id uuid primary key default gen_random_uuid(),template_id uuid not null references public.document_templates(id) on delete restrict,version integer not null check(version>0),body_html text not null,variables jsonb not null default '[]',change_summary text,status text not null default 'DRAFT' check(status in('DRAFT','PUBLISHED','RETIRED')),created_by uuid,created_at timestamptz not null default now(),unique(template_id,version));
create table if not exists public.document_comments(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,body text not null,author_id uuid,client_visible boolean not null default false,mentions uuid[] not null default '{}',created_at timestamptz not null default now());
create table if not exists public.document_share_links(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,token_hash text not null unique,expires_at timestamptz not null,max_uses integer not null default 10 check(max_uses>0),use_count integer not null default 0 check(use_count>=0),password_hash text,revoked_at timestamptz,created_by uuid,created_at timestamptz not null default now());
create table if not exists public.document_access_events(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,version_id uuid references public.document_versions(id) on delete restrict,actor_id uuid,actor_role text,event_type text not null,classification text not null,ip inet,user_agent text,occurred_at timestamptz not null default now());
create table if not exists public.document_events(id uuid primary key default gen_random_uuid(),document_id uuid references public.documents(id) on delete restrict,event_type text not null,actor_id uuid,payload jsonb not null default '{}',occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.document_integrity_checks(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,version_id uuid not null references public.document_versions(id) on delete restrict,expected_sha256 text not null,actual_sha256 text not null,matches boolean not null,verified_by uuid,verified_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.document_search_content(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete restrict,version_id uuid not null references public.document_versions(id) on delete restrict,content text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(version_id));
create index if not exists document_search_content_idx on public.document_search_content using gin(to_tsvector('spanish',content));
do $$declare t text;begin foreach t in array array['document_retention_policies','document_types','documents','document_versions','document_links','document_relationships','document_tags','document_assignments','document_permissions','document_reviews','document_approvals','signature_requests','signature_signers','signature_events','document_templates','document_template_versions','document_comments','document_share_links','document_access_events','document_events','document_integrity_checks','document_search_content']loop execute format('alter table public.%I add column if not exists updated_at timestamptz not null default now()',t);end loop;end$$;

create or replace function public.create_document_version(target_document_id uuid,version_payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare d public.documents%rowtype;new_id uuid;next_version integer;begin select * into d from public.documents where id=target_document_id for update;if not found then raise exception 'Documento no encontrado';end if;if d.status in('ARCHIVED','TRASHED')then raise exception 'Documento no versionable';end if;select coalesce(max(version_number),0)+1 into next_version from public.document_versions where document_id=target_document_id;insert into public.document_versions(document_id,version_number,filename,storage_path,mime_type,detected_mime_type,size_bytes,sha256,malware_status,status,change_summary,created_by)values(target_document_id,next_version,version_payload->>'filename',version_payload->>'storage_path',version_payload->>'mime_type',version_payload->>'detected_mime_type',(version_payload->>'size_bytes')::bigint,version_payload->>'sha256',version_payload->>'malware_status',version_payload->>'status',version_payload->>'change_summary',(version_payload->>'created_by')::uuid)returning id into new_id;update public.document_reviews set status='CANCELLED',updated_at=now() where document_id=target_document_id and status='PENDING';return new_id;end$$;
create or replace function public.prevent_document_version_mutation() returns trigger language plpgsql as $$begin if old.status='LOCKED' or old.signed_at is not null then if row(new.filename,new.storage_path,new.mime_type,new.size_bytes,new.sha256,new.document_id,new.version_number)is distinct from row(old.filename,old.storage_path,old.mime_type,old.size_bytes,old.sha256,old.document_id,old.version_number)then raise exception 'Las versiones bloqueadas o firmadas son inmutables';end if;end if;return new;end$$;
drop trigger if exists document_versions_immutable on public.document_versions;create trigger document_versions_immutable before update on public.document_versions for each row execute function public.prevent_document_version_mutation();
create or replace function public.document_event_outbox() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.business_event_outbox(aggregate_type,aggregate_id,event_type,payload)values('DOCUMENT',coalesce(new.document_id,new.id),new.event_type,new.payload);return new;end$$;
drop trigger if exists document_events_outbox on public.document_events;create trigger document_events_outbox after insert on public.document_events for each row execute function public.document_event_outbox();

create or replace function private.document_portal_client_id() returns uuid language sql stable security definer set search_path=public as $$select client_id from public.client_portal_users where auth_user_id=auth.uid() and status='ACTIVE' limit 1$$;
create or replace function private.document_internal_role() returns boolean language sql stable as $$select private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD','QA','SOPORTE_TECNICO','OPERACIONES','PROGRAMADOR','DESARROLLO','FINANZAS','RRHH','JEFE_VENTAS','EJECUTIVA_VENTAS','COMERCIAL')$$;
create or replace function private.document_can_read(target uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.documents d where d.id=target and((private.document_internal_role() and(d.classification not in('RESTRICTED','CRITICAL')or d.owner_id=auth.uid()or private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO')))or(private.zyteron_role()='PORTAL_CLIENT' and d.client_visible and d.classification in('PUBLIC','CLIENT')and exists(select 1 from public.document_links l where l.document_id=d.id and l.link_type='CLIENT' and l.linked_id=private.document_portal_client_id()))or exists(select 1 from public.document_permissions p where p.document_id=d.id and((p.subject_type='USER' and p.subject_id=auth.uid()::text)or(p.subject_type='ROLE' and p.subject_id=private.zyteron_role()))and p.permission in('VIEW','DOWNLOAD','EDIT','REVIEW','APPROVE','SHARE','MANAGE'))))$$;
create or replace function private.document_can_write(target uuid) returns boolean language sql stable security definer set search_path=public as $$select private.document_internal_role()and private.zyteron_role()<>'PORTAL_CLIENT'and exists(select 1 from public.documents d where d.id=target and(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD')or d.owner_id=auth.uid()or d.created_by=auth.uid()or exists(select 1 from public.document_permissions p where p.document_id=d.id and((p.subject_type='USER'and p.subject_id=auth.uid()::text)or(p.subject_type='ROLE'and p.subject_id=private.zyteron_role()))and p.permission in('EDIT','REVIEW','APPROVE','SHARE','MANAGE'))))$$;

do $$declare t text;begin foreach t in array array['document_retention_policies','document_types','documents','document_versions','document_links','document_relationships','document_tags','document_assignments','document_permissions','document_reviews','document_approvals','signature_requests','signature_signers','signature_events','document_template_versions','document_comments','document_share_links','document_access_events','document_events','document_integrity_checks','document_search_content']loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
drop policy if exists documents_read on public.documents;create policy documents_read on public.documents for select to authenticated using(private.document_can_read(id));
drop policy if exists documents_create on public.documents;create policy documents_create on public.documents for insert to authenticated with check(private.document_internal_role()and created_by=auth.uid());
drop policy if exists documents_update on public.documents;create policy documents_update on public.documents for update to authenticated using(private.document_can_write(id))with check(private.document_can_write(id));
do $$declare t text;begin foreach t in array array['document_versions','document_links','document_relationships','document_tags','document_assignments','document_permissions','document_reviews','document_approvals','signature_requests','document_comments','document_share_links','document_integrity_checks','document_search_content']loop execute format('drop policy if exists %I on public.%I',t||'_read',t);execute format('create policy %I on public.%I for select to authenticated using(private.document_can_read(document_id))',t||'_read',t);execute format('drop policy if exists %I on public.%I',t||'_write',t);execute format('create policy %I on public.%I for all to authenticated using(private.document_can_write(document_id))with check(private.document_can_write(document_id))',t||'_write',t);end loop;end$$;
drop policy if exists document_template_versions_read on public.document_template_versions;create policy document_template_versions_read on public.document_template_versions for select to authenticated using(private.document_internal_role());
drop policy if exists document_template_versions_manage on public.document_template_versions;create policy document_template_versions_manage on public.document_template_versions for all to authenticated using(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD'))with check(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD'));
drop policy if exists document_templates_read on public.document_templates;create policy document_templates_read on public.document_templates for select to authenticated using(private.document_internal_role()and active);
drop policy if exists document_templates_manage on public.document_templates;create policy document_templates_manage on public.document_templates for all to authenticated using(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD'))with check(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD'));
drop policy if exists document_access_events_read on public.document_access_events;create policy document_access_events_read on public.document_access_events for select to authenticated using(private.document_can_read(document_id)and private.zyteron_role()<>'PORTAL_CLIENT');
drop policy if exists document_access_events_insert on public.document_access_events;create policy document_access_events_insert on public.document_access_events for insert to authenticated with check(private.document_can_read(document_id));
drop policy if exists document_events_read on public.document_events;create policy document_events_read on public.document_events for select to authenticated using(document_id is null or private.document_can_read(document_id));
drop policy if exists document_events_write on public.document_events;create policy document_events_write on public.document_events for insert to authenticated with check(document_id is null or private.document_can_write(document_id));
drop policy if exists document_catalog_read on public.document_types;create policy document_catalog_read on public.document_types for select to authenticated using(active);
drop policy if exists document_catalog_manage on public.document_types;create policy document_catalog_manage on public.document_types for all to authenticated using(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO'))with check(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO'));
drop policy if exists retention_catalog_read on public.document_retention_policies;create policy retention_catalog_read on public.document_retention_policies for select to authenticated using(active);
drop policy if exists retention_catalog_manage on public.document_retention_policies;create policy retention_catalog_manage on public.document_retention_policies for all to authenticated using(private.zyteron_role()='GERENTE_GENERAL')with check(private.zyteron_role()='GERENTE_GENERAL');
drop policy if exists signature_signers_scope on public.signature_signers;create policy signature_signers_scope on public.signature_signers for all to authenticated using(exists(select 1 from public.signature_requests r where r.id=request_id and private.document_can_read(r.document_id)))with check(exists(select 1 from public.signature_requests r where r.id=request_id and private.document_can_write(r.document_id)));
drop policy if exists signature_events_manage on public.signature_events;create policy signature_events_manage on public.signature_events for select to authenticated using(private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO'));

insert into public.document_retention_policies(id,code,name,retention_days,trash_grace_days)values('d0000000-0000-4000-8000-000000000001','GENERAL-5Y','General · 5 años',1825,30),('d0000000-0000-4000-8000-000000000002','CONTRACT-10Y','Contratos · 10 años',3650,60),('d0000000-0000-4000-8000-000000000003','EVIDENCE-7Y','Evidencia · 7 años',2555,60)on conflict(code)do nothing;
insert into public.document_types(id,code,name,description,max_size_bytes,allowed_mime_types,requires_approval,allows_client_sharing,retention_policy_id)values
('d1000000-0000-4000-8000-000000000001','GENERAL','Documento general','Archivo empresarial transversal',52428800,array['application/pdf','image/png','image/jpeg','text/plain','text/csv','video/mp4','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],false,true,'d0000000-0000-4000-8000-000000000001'),
('d1000000-0000-4000-8000-000000000002','CONTRACT','Contrato / anexo','Expediente contractual versionado',52428800,array['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],true,true,'d0000000-0000-4000-8000-000000000002'),
('d1000000-0000-4000-8000-000000000003','QUOTE','Cotización / propuesta','Documento comercial emitido',26214400,array['application/pdf'],true,true,'d0000000-0000-4000-8000-000000000001'),
('d1000000-0000-4000-8000-000000000004','REPORT','Informe','Informe técnico o ejecutivo',52428800,array['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],true,true,'d0000000-0000-4000-8000-000000000001'),
('d1000000-0000-4000-8000-000000000005','EVIDENCE','Evidencia','Evidencia operativa o de auditoría',104857600,array['application/pdf','image/png','image/jpeg','text/plain','text/csv'],false,false,'d0000000-0000-4000-8000-000000000003')on conflict(code)do update set name=excluded.name,description=excluded.description;
insert into public.app_permissions(code,description)values('documents.dashboard.view','Ver Document Command Center'),('document.view','Ver documentos'),('document.create','Crear documentos'),('document.edit','Editar metadatos'),('document.upload_version','Subir versiones'),('document.review','Revisar documentos'),('document.approve','Aprobar documentos'),('document.sign','Solicitar firma'),('document.share','Compartir documentos'),('document.archive','Archivar documentos'),('document.purge','Purgar documentos'),('document.audit.view','Ver trazabilidad documental'),('document.template.manage','Gestionar plantillas'),('document.retention.manage','Gestionar retención')on conflict(code)do update set description=excluded.description;
insert into public.role_permissions(role,permission_code)select r.role,p.code from(values('GERENTE_GENERAL'),('JEFE_DESARROLLO'),('TECH_LEAD'))r(role)cross join public.app_permissions p where p.code like'document%'on conflict do nothing;
insert into public.role_permissions(role,permission_code)select r.role,p.code from(values('QA'),('SOPORTE_TECNICO'),('OPERACIONES'),('PROGRAMADOR'),('DESARROLLO'),('FINANZAS'),('RRHH'),('JEFE_VENTAS'),('EJECUTIVA_VENTAS'),('COMERCIAL'))r(role)cross join public.app_permissions p where p.code in('documents.dashboard.view','document.view','document.create','document.edit','document.upload_version','document.review','document.archive')on conflict do nothing;
insert into public.role_permissions(role,permission_code)values('PORTAL_CLIENT','document.view')on conflict do nothing;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('enterprise-documents','enterprise-documents',false,104857600,array['application/pdf','image/png','image/jpeg','text/plain','text/csv','video/mp4','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists enterprise_documents_storage_read on storage.objects;create policy enterprise_documents_storage_read on storage.objects for select to authenticated using(bucket_id='enterprise-documents'and private.document_can_read((storage.foldername(name))[1]::uuid));
drop policy if exists enterprise_documents_storage_write on storage.objects;create policy enterprise_documents_storage_write on storage.objects for insert to authenticated with check(bucket_id='enterprise-documents'and private.document_can_write((storage.foldername(name))[1]::uuid));
do $$declare t text;begin foreach t in array array['documents','document_versions','document_links','document_reviews','signature_requests','document_comments','document_events']loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename=t)then execute format('alter publication supabase_realtime add table public.%I',t);end if;end loop;end$$;
commit;
