begin;

create schema if not exists private;
create sequence if not exists public.security_incident_number_seq;
create or replace function public.next_security_incident_number() returns text language sql security definer set search_path=public as $$select 'SEC-'||to_char(now(),'YYYY')||'-'||lpad(nextval('public.security_incident_number_seq')::text,6,'0')$$;
revoke all on function public.next_security_incident_number() from public,anon,authenticated;
grant execute on function public.next_security_incident_number() to service_role;

create table if not exists public.security_settings(key text primary key,value jsonb not null,classification text not null default 'INTERNAL' check(classification in('INTERNAL','RESTRICTED')),description text,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.security_session_metadata(id uuid primary key default gen_random_uuid(),session_id text not null unique,user_id uuid not null,role text,device_id text,browser text,os text,ip_masked text,region text,aal text not null default 'aal1' check(aal in('aal1','aal2')),status text not null default 'ACTIVE' check(status in('ACTIVE','REVOKED','EXPIRED')),created_at timestamptz not null default now(),last_activity_at timestamptz not null default now(),revoked_at timestamptz,revoked_by uuid,updated_at timestamptz not null default now());
create index if not exists security_sessions_user_status_idx on public.security_session_metadata(user_id,status,last_activity_at desc);
create table if not exists public.registered_devices(id uuid primary key default gen_random_uuid(),user_id uuid not null,device_id text not null,device_name text,device_type text,browser text,os text,first_seen timestamptz not null default now(),last_seen timestamptz not null default now(),trust_status text not null default 'NEW' check(trust_status in('NEW','TRUSTED','UNTRUSTED','BLOCKED','REVOKED')),corporate_managed boolean,security_compliant boolean,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,device_id));
create index if not exists registered_devices_user_status_idx on public.registered_devices(user_id,trust_status,last_seen desc);

create table if not exists public.access_requests(id uuid primary key default gen_random_uuid(),requester_id uuid not null,resource_type text not null,resource_id text not null,permission_code text not null,reason text not null,requested_minutes integer not null check(requested_minutes>0),status text not null default 'REQUESTED' check(status in('REQUESTED','UNDER_REVIEW','APPROVED','REJECTED','CANCELLED')),reviewed_by uuid,review_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists access_requests_queue_idx on public.access_requests(status,created_at);
create table if not exists public.access_grants(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.access_requests(id) on delete restrict,user_id uuid not null,resource_type text not null,resource_id text not null,permission_code text not null,starts_at timestamptz not null,expires_at timestamptz not null,status text not null default 'ACTIVE' check(status in('ACTIVE','EXPIRING','EXPIRED','REVOKED')),granted_by uuid not null,revoked_by uuid,revoked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(expires_at>starts_at));
create index if not exists access_grants_active_idx on public.access_grants(user_id,resource_type,resource_id,permission_code,expires_at) where status='ACTIVE';
create table if not exists public.access_reviews(id uuid primary key default gen_random_uuid(),name text not null,scope jsonb not null default '{}',reviewer_id uuid,status text not null default 'PLANNED' check(status in('PLANNED','IN_PROGRESS','COMPLETED','CANCELLED')),due_at timestamptz,completed_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.access_review_decisions(id uuid primary key default gen_random_uuid(),review_id uuid not null references public.access_reviews(id) on delete restrict,user_id uuid not null,resource_type text not null,resource_id text,decision text not null check(decision in('KEEP','REMOVE','CHANGE','REVIEW_REQUIRED')),reason text,decided_by uuid,decided_at timestamptz,created_at timestamptz not null default now());

create table if not exists public.secret_rotation_policies(id uuid primary key default gen_random_uuid(),name text not null unique,rotation_days integer not null check(rotation_days>0),warning_days integer[] not null default '{30,15,7,3,1}',active boolean not null default true,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.vault_items(id uuid primary key default gen_random_uuid(),name text not null,secret_type text not null,provider text not null,encrypted_reference text not null check(length(encrypted_reference)>=8),client_id uuid references public.clients(id) on delete restrict,project_id uuid references public.projects(id) on delete restrict,environment text,owner_id uuid,classification text not null default 'CRITICAL' check(classification in('RESTRICTED','CRITICAL')),rotation_policy_id uuid references public.secret_rotation_policies(id) on delete restrict,rotated_at timestamptz,expires_at timestamptz,status text not null default 'ACTIVE' check(status in('ACTIVE','ROTATION_DUE','EXPIRED','REVOKED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists vault_items_scope_idx on public.vault_items(client_id,project_id,environment,status);
create table if not exists public.vault_access_events(id uuid primary key default gen_random_uuid(),vault_item_id uuid not null references public.vault_items(id) on delete restrict,actor_user_id uuid,action text not null check(action in('REQUEST','REVEAL','COPY','ROTATE','REVOKE')),reason text,session_id text,result text not null check(result in('ALLOWED','DENIED','PROVIDER_UNAVAILABLE')),occurred_at timestamptz not null default now());

create table if not exists public.security_events(id uuid primary key default gen_random_uuid(),event_type text not null,severity text not null check(severity in('INFO','LOW','MEDIUM','HIGH','CRITICAL')),actor_user_id uuid,session_id text,ip_masked text,device_id text,resource_type text,resource_id text,description text not null,metadata_safe jsonb not null default '{}',detected_at timestamptz not null default now(),status text not null default 'OPEN' check(status in('OPEN','ACKNOWLEDGED','INVESTIGATING','FALSE_POSITIVE','ESCALATED','CLOSED')),acknowledged_by uuid,acknowledged_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists security_events_queue_idx on public.security_events(status,severity,detected_at desc);
create table if not exists public.security_incidents(id uuid primary key default gen_random_uuid(),incident_number text not null unique,title text not null,description text,incident_type text not null,severity text not null check(severity in('SEV4','SEV3','SEV2','SEV1')),status text not null default 'DETECTED' check(status in('DETECTED','TRIAGE','CONFIRMED','CONTAINING','INVESTIGATING','ERADICATING','RECOVERING','MONITORING','RESOLVED','POSTMORTEM','CLOSED')),commander_id uuid,privacy_breach boolean not null default false,detected_at timestamptz not null default now(),resolved_at timestamptz,closed_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.security_incident_events(id uuid primary key default gen_random_uuid(),incident_id uuid not null references public.security_incidents(id) on delete restrict,event_type text not null,description text not null,actor_id uuid,evidence_document_id uuid references public.documents(id) on delete restrict,occurred_at timestamptz not null default now());
create table if not exists public.security_playbooks(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,incident_type text not null,steps jsonb not null,status text not null default 'DRAFT' check(status in('DRAFT','APPROVED','RETIRED')),version integer not null default 1,owner_id uuid,approved_by uuid,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.privacy_breach_assessments(id uuid primary key default gen_random_uuid(),incident_id uuid not null references public.security_incidents(id) on delete restrict,data_categories text[] not null default '{}',approx_subjects integer,scope text,confidentiality_impact text,integrity_impact text,availability_impact text,risk_to_individuals text,notification_required_assessment text,decision text,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.security_vulnerabilities(id uuid primary key default gen_random_uuid(),source text not null,external_id text,cve text,cwe text,title text not null,description text,severity text not null check(severity in('LOW','MEDIUM','HIGH','CRITICAL')),affected_component text not null,status text not null default 'OPEN' check(status in('OPEN','TRIAGED','MITIGATING','FIX_READY','FIXED','VERIFIED','ACCEPTED_RISK','FALSE_POSITIVE')),owner_id uuid,detected_at timestamptz not null default now(),due_date date,fixed_at timestamptz,verified_at timestamptz,accepted_risk_expires_at timestamptz,evidence_document_id uuid references public.documents(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists security_vulnerabilities_queue_idx on public.security_vulnerabilities(status,severity,detected_at desc);
create table if not exists public.security_scans(id uuid primary key default gen_random_uuid(),scan_type text not null check(scan_type in('SAST','SCA','SECRET_SCAN','AUTHORIZATION','RLS','DAST','PENTEST','RESTORE')),provider text not null,status text not null default 'NOT_CONFIGURED' check(status in('NOT_CONFIGURED','QUEUED','RUNNING','PASSED','FAILED','ERROR')),commit_sha text,started_at timestamptz,completed_at timestamptz,critical_findings integer not null default 0,high_findings integer not null default 0,report_document_id uuid references public.documents(id) on delete restrict,metadata_safe jsonb not null default '{}',created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.security_scans add column if not exists created_by uuid;
create table if not exists public.security_scan_findings(id uuid primary key default gen_random_uuid(),scan_id uuid not null references public.security_scans(id) on delete restrict,fingerprint text not null,title text not null,severity text not null check(severity in('LOW','MEDIUM','HIGH','CRITICAL')),component text,status text not null default 'OPEN' check(status in('OPEN','FIXED','FALSE_POSITIVE','ACCEPTED_RISK')),evidence_safe jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(scan_id,fingerprint));

create table if not exists public.security_controls(id uuid primary key default gen_random_uuid(),control_code text not null unique,framework text not null,title text not null,description text,owner_id uuid,status text not null default 'NOT_IMPLEMENTED' check(status in('NOT_IMPLEMENTED','IMPLEMENTED','VERIFIED','FAILED','EXCEPTION')),evidence_summary text,last_tested_at timestamptz,next_test_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.security_control_evidence(id uuid primary key default gen_random_uuid(),control_id uuid not null references public.security_controls(id) on delete restrict,document_id uuid references public.documents(id) on delete restrict,evidence_type text not null,reference text,summary text not null,verified_by uuid,verified_at timestamptz,created_by uuid,created_at timestamptz not null default now());
create table if not exists public.security_exceptions(id uuid primary key default gen_random_uuid(),control_code text not null,risk text not null,justification text not null,compensating_control text not null,owner_id uuid not null,approved_by uuid not null,expires_at timestamptz not null,status text not null default 'ACTIVE' check(status in('ACTIVE','EXPIRED','REVOKED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.production_security_gates(id uuid primary key default gen_random_uuid(),release_reference text not null,status text not null check(status in('PASS','PASS_WITH_EXCEPTION','FAIL')),evaluated_at timestamptz not null default now(),evaluated_by uuid,blockers jsonb not null default '[]',warnings jsonb not null default '[]',evidence_snapshot jsonb not null default '{}',created_at timestamptz not null default now());

create table if not exists public.data_categories(code text primary key,name text not null,sensitive boolean not null default false,special_category boolean not null default false,description text,created_at timestamptz not null default now());
create table if not exists public.retention_policies(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,module text,data_category_code text references public.data_categories(code) on delete restrict,document_type text,retention_period text not null,action text not null check(action in('REVIEW','ARCHIVE','ANONYMIZE','DELETE')),legal_hold_overrides boolean not null default true,status text not null default 'DRAFT' check(status in('DRAFT','APPROVED','RETIRED')),source_reference text,approved_by uuid,approved_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.data_assets(id uuid primary key default gen_random_uuid(),module text not null,system text not null,table_name text,field_name text,name text not null,category_code text not null references public.data_categories(code) on delete restrict,classification text not null check(classification in('PUBLIC','CLIENT','INTERNAL','CONFIDENTIAL','RESTRICTED','CRITICAL')),purpose text,retention_policy_id uuid references public.retention_policies(id) on delete restrict,owner_id uuid,processor text,access_roles text[] not null default '{}',encrypted_at_rest boolean,location text,status text not null default 'INVENTORIED' check(status in('INVENTORIED','REVIEW_REQUIRED','RETIRED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.processing_activities(id uuid primary key default gen_random_uuid(),name text not null,purpose text not null,data_subjects text[] not null,data_categories text[] not null,source text,recipients text[] not null default '{}',retention text,security_measures text[] not null default '{}',international_transfer text,legal_basis_metadata text,owner_id uuid,status text not null default 'DRAFT' check(status in('DRAFT','REVIEW','APPROVED','RETIRED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create sequence if not exists public.data_subject_request_number_seq;
create table if not exists public.data_subject_requests(id uuid primary key default gen_random_uuid(),request_number text not null unique default('DSR-'||to_char(now(),'YYYY')||'-'||lpad(nextval('public.data_subject_request_number_seq')::text,6,'0')),request_type text not null check(request_type in('ACCESS','RECTIFICATION','DELETION','OPPOSITION','RESTRICTION','PORTABILITY')),subject_reference text not null,status text not null default 'RECEIVED' check(status in('RECEIVED','IDENTITY_VERIFICATION','ASSESSMENT','DATA_DISCOVERY','REVIEW','FULFILLED','REJECTED_WITH_REASON')),identity_verified_at timestamptz,due_at timestamptz,owner_id uuid,decision_reason text,legal_hold_conflict boolean not null default false,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.privacy_impact_assessments(id uuid primary key default gen_random_uuid(),name text not null,trigger text not null,purpose text not null,scope text not null,data_description text not null,necessity text,risk text,impact text,controls text[] not null default '{}',residual_risk text,owner_id uuid,reviewer_id uuid,status text not null default 'DRAFT' check(status in('DRAFT','REVIEW','APPROVED','REJECTED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.data_export_events(id uuid primary key default gen_random_uuid(),actor_user_id uuid,module text not null,filters_safe jsonb not null default '{}',row_count integer not null check(row_count>=0),classification text not null,reason text,client_id uuid references public.clients(id) on delete restrict,request_id text,occurred_at timestamptz not null default now());
create table if not exists public.vendor_security_registry(id uuid primary key default gen_random_uuid(),vendor_name text not null,service text not null,data_shared boolean not null default false,data_categories text[] not null default '{}',purpose text,region text,subprocessors_known boolean,security_docs_url text,contract_document_id uuid references public.documents(id) on delete restrict,dpa_status text not null default 'UNKNOWN' check(dpa_status in('NOT_REQUIRED','PENDING','SIGNED','EXPIRED','UNKNOWN')),review_date date,next_review_date date,risk text not null default 'NOT_ASSESSED' check(risk in('LOW','MEDIUM','HIGH','CRITICAL','NOT_ASSESSED')),status text not null default 'UNDER_REVIEW' check(status in('ACTIVE','UNDER_REVIEW','SUSPENDED','ENDED')),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.vendor_security_reviews(id uuid primary key default gen_random_uuid(),vendor_id uuid not null references public.vendor_security_registry(id) on delete restrict,review_type text not null,assessment jsonb not null default '{}',risk text not null,decision text,status text not null default 'DRAFT',reviewed_by uuid,reviewed_at timestamptz,next_review_at timestamptz,evidence_document_id uuid references public.documents(id) on delete restrict,created_at timestamptz not null default now());

create table if not exists public.backup_targets(id uuid primary key default gen_random_uuid(),name text not null unique,system text not null,provider text not null,rpo_minutes integer,rto_minutes integer,retention text,encryption_status text not null default 'UNKNOWN',last_backup_at timestamptz,next_backup_at timestamptz,status text not null default 'NOT_CONFIGURED' check(status in('NOT_CONFIGURED','HEALTHY','DEGRADED','FAILED','UNKNOWN')),evidence_reference text,checked_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.recovery_tests(id uuid primary key default gen_random_uuid(),target_id uuid references public.backup_targets(id) on delete restrict,name text not null,scope text not null,backup_reference text,started_at timestamptz,completed_at timestamptz,result text not null default 'PLANNED' check(result in('PLANNED','RUNNING','PASSED','FAILED','PARTIAL')),actual_rto_minutes integer,data_validation text,evidence_document_id uuid references public.documents(id) on delete restrict,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.disaster_recovery_plans(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,scenario text not null,rpo_minutes integer,rto_minutes integer,steps jsonb not null default '[]',owner_id uuid,status text not null default 'DRAFT' check(status in('DRAFT','APPROVED','TESTED','RETIRED')),last_tested_at timestamptz,evidence_document_id uuid references public.documents(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.threat_models(id uuid primary key default gen_random_uuid(),module text not null,version integer not null default 1,assets jsonb not null default '[]',trust_boundaries jsonb not null default '[]',threats jsonb not null default '[]',controls jsonb not null default '[]',residual_risk text,status text not null default 'DRAFT' check(status in('DRAFT','REVIEW','APPROVED','RETIRED')),owner_id uuid,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(module,version));
create table if not exists public.security_training_records(id uuid primary key default gen_random_uuid(),user_id uuid not null,topic text not null,assigned_at timestamptz not null default now(),completed_at timestamptz,expires_at timestamptz,evidence_document_id uuid references public.documents(id) on delete restrict,status text not null default 'ASSIGNED' check(status in('ASSIGNED','IN_PROGRESS','COMPLETED','EXPIRED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.external_security_reports(id uuid primary key default gen_random_uuid(),report_type text not null,provider text,title text not null,document_id uuid references public.documents(id) on delete restrict,scope text,status text not null default 'RECEIVED',received_at timestamptz not null default now(),created_by uuid,created_at timestamptz not null default now());
create table if not exists public.security_audit_events(id uuid primary key default gen_random_uuid(),actor_user_id uuid,actor_role text,action text not null,resource_type text not null,resource_id text,before_safe jsonb,after_safe jsonb,reason text,request_id text,result text not null,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());

create or replace function private.security_is_admin()returns boolean language sql stable as $$select private.zyteron_role() in('GERENTE_GENERAL','SECURITY_ADMIN')$$;
create or replace function private.security_aal()returns text language sql stable as $$select coalesce(auth.jwt()->>'aal','aal1')$$;
create or replace function private.security_is_aal2()returns boolean language sql stable as $$select private.security_aal()='aal2'$$;
create or replace function private.security_has_permission(target text)returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.role_permissions where role=private.zyteron_role() and permission_code=target)$$;
revoke all on function private.security_is_admin() from public;revoke all on function private.security_aal() from public;revoke all on function private.security_is_aal2() from public;revoke all on function private.security_has_permission(text) from public;
grant execute on function private.security_is_admin() to authenticated,service_role;grant execute on function private.security_aal() to authenticated,service_role;grant execute on function private.security_is_aal2() to authenticated,service_role;grant execute on function private.security_has_permission(text) to authenticated,service_role;
drop policy if exists app_permissions_authenticated_read on public.app_permissions;drop policy if exists app_permissions_security_read on public.app_permissions;create policy app_permissions_security_read on public.app_permissions for select to authenticated using(private.security_is_admin());
drop policy if exists role_permissions_authenticated_read on public.role_permissions;drop policy if exists role_permissions_security_read on public.role_permissions;create policy role_permissions_security_read on public.role_permissions for select to authenticated using(private.security_is_admin());

create or replace function public.expire_security_access_grants()returns integer language plpgsql security definer set search_path=public as $$declare affected integer;begin update public.access_grants set status='EXPIRED',updated_at=now() where status in('ACTIVE','EXPIRING')and expires_at<=now();get diagnostics affected=row_count;return affected;end$$;
revoke all on function public.expire_security_access_grants() from public,anon,authenticated;grant execute on function public.expire_security_access_grants() to service_role;
create or replace function private.prevent_security_evidence_mutation()returns trigger language plpgsql as $$begin raise exception 'La evidencia de seguridad es append-only';end$$;
drop trigger if exists security_audit_immutable on public.security_audit_events;create trigger security_audit_immutable before update or delete on public.security_audit_events for each row execute function private.prevent_security_evidence_mutation();
drop trigger if exists vault_access_immutable on public.vault_access_events;create trigger vault_access_immutable before update or delete on public.vault_access_events for each row execute function private.prevent_security_evidence_mutation();
drop trigger if exists incident_events_immutable on public.security_incident_events;create trigger incident_events_immutable before update or delete on public.security_incident_events for each row execute function private.prevent_security_evidence_mutation();
create or replace function private.security_event_to_outbox()returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.business_event_outbox(aggregate_type,aggregate_id,event_type,payload)values('SECURITY_EVENT',new.id,new.event_type,jsonb_build_object('securityEventId',new.id,'severity',new.severity,'resourceType',new.resource_type,'resourceId',new.resource_id));return new;end$$;
drop trigger if exists security_event_outbox on public.security_events;create trigger security_event_outbox after insert on public.security_events for each row execute function private.security_event_to_outbox();

do $$declare t text;begin foreach t in array array['security_settings','security_session_metadata','registered_devices','access_requests','access_grants','access_reviews','access_review_decisions','secret_rotation_policies','vault_items','vault_access_events','security_events','security_incidents','security_incident_events','security_playbooks','privacy_breach_assessments','security_vulnerabilities','security_scans','security_scan_findings','security_controls','security_control_evidence','security_exceptions','production_security_gates','data_categories','retention_policies','data_assets','processing_activities','data_subject_requests','privacy_impact_assessments','data_export_events','vendor_security_registry','vendor_security_reviews','backup_targets','recovery_tests','disaster_recovery_plans','threat_models','security_training_records','external_security_reports','security_audit_events']loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['security_settings','access_reviews','access_review_decisions','secret_rotation_policies','vault_items','vault_access_events','security_events','security_incidents','security_incident_events','security_playbooks','privacy_breach_assessments','security_vulnerabilities','security_scans','security_scan_findings','security_controls','security_control_evidence','security_exceptions','production_security_gates','data_categories','retention_policies','data_assets','processing_activities','data_subject_requests','privacy_impact_assessments','data_export_events','vendor_security_registry','vendor_security_reviews','backup_targets','recovery_tests','disaster_recovery_plans','threat_models','security_training_records','external_security_reports','security_audit_events']loop execute format('drop policy if exists security_admin_scope on public.%I',t);execute format('create policy security_admin_scope on public.%I for all to authenticated using(private.security_is_admin())with check(private.security_is_admin())',t);end loop;end$$;
drop policy if exists security_sessions_scope on public.security_session_metadata;create policy security_sessions_scope on public.security_session_metadata for select to authenticated using(user_id=auth.uid()or private.security_is_admin());
drop policy if exists security_devices_scope on public.registered_devices;create policy security_devices_scope on public.registered_devices for select to authenticated using(user_id=auth.uid()or private.security_is_admin());
drop policy if exists access_requests_read on public.access_requests;create policy access_requests_read on public.access_requests for select to authenticated using(requester_id=auth.uid()or private.security_is_admin());
drop policy if exists access_requests_create on public.access_requests;create policy access_requests_create on public.access_requests for insert to authenticated with check(requester_id=auth.uid());
drop policy if exists access_requests_admin on public.access_requests;create policy access_requests_admin on public.access_requests for all to authenticated using(private.security_is_admin())with check(private.security_is_admin());
drop policy if exists access_grants_read on public.access_grants;create policy access_grants_read on public.access_grants for select to authenticated using(user_id=auth.uid()or private.security_is_admin());
drop policy if exists access_grants_admin on public.access_grants;create policy access_grants_admin on public.access_grants for all to authenticated using(private.security_is_admin())with check(private.security_is_admin());
grant select on public.security_session_metadata,public.registered_devices,public.access_requests,public.access_grants to authenticated;
grant insert on public.access_requests to authenticated;

insert into public.security_settings(key,value,classification,description)values
('privileged_roles','["GERENTE_GENERAL","SECURITY_ADMIN","FINANZAS","RRHH"]','INTERNAL','Roles sujetos a MFA y controles reforzados.'),
('jit_max_minutes','1440','INTERNAL','Duración máxima configurable de un grant temporal.'),
('account_lock_duration','"24h"','INTERNAL','Duración de bloqueo aplicada por Supabase Auth Admin.'),
('export_alert_threshold','1000','INTERNAL','Filas que generan señal de exportación masiva.'),
('security_event_retention_days','730','INTERNAL','Retención operativa; requiere revisión legal y de capacidad.'),
('critical_action_requires_aal2','true','INTERNAL','Política de step-up para operaciones críticas.')
on conflict(key)do nothing;

insert into public.data_categories(code,name,sensitive,special_category)values('IDENTIFICATION','Identificación',true,false),('CONTACT','Contacto',true,false),('COMMERCIAL','Comercial',false,false),('FINANCIAL','Financiera',true,false),('EMPLOYMENT','Laboral',true,false),('PAYROLL','Remuneraciones',true,false),('HEALTH','Salud',true,true),('AUTHENTICATION','Autenticación',true,false),('TECHNICAL','Técnica',false,false),('BEHAVIORAL','Conductual',true,false),('SECURITY','Seguridad',true,false),('SPECIAL_CATEGORY','Categoría especial',true,true)on conflict(code)do nothing;
insert into public.security_controls(control_code,framework,title,status,evidence_summary)values
('AUTH-ROLE-SOURCE','OWASP ASVS','Roles solo desde app_metadata','IMPLEMENTED','El guard ignora user_metadata para autorización.'),
('AUTH-AAL2','OWASP ASVS','Step-up para acciones críticas','IMPLEMENTED','Decorador backend AAL2 y validación de claim verificado.'),
('RLS-SECURITY-TABLES','OWASP ASVS','RLS deny-by-default del dominio Security','IMPLEMENTED','Migración habilita RLS y políticas explícitas.'),
('VAULT-NO-PLAINTEXT','OWASP ASVS','Vault sin secretos plaintext','IMPLEMENTED','Solo metadata y encrypted_reference; proveedor externo requerido.'),
('BACKUP-RESTORE','Internal','Restauración probada','NOT_IMPLEMENTED','Sin evidencia hasta registrar un recovery test PASSED.'),
('PRIVACY-LEGAL-REVIEW','Ley 21.719 readiness','Validación jurídica de privacidad','NOT_IMPLEMENTED','Requiere revisión de asesoría jurídica/DPO.'),
('CYBERSECURITY-REGULATORY-SCOPE','Ley 21.663 assessment','Evaluación de alcance regulatorio','NOT_IMPLEMENTED','No se concluye aplicabilidad automáticamente.')
on conflict(control_code)do nothing;
insert into public.security_scans(scan_type,provider,status)values('SAST','NOT_CONFIGURED','NOT_CONFIGURED'),('SCA','NOT_CONFIGURED','NOT_CONFIGURED'),('SECRET_SCAN','NOT_CONFIGURED','NOT_CONFIGURED'),('AUTHORIZATION','ZYTERON_TESTS','NOT_CONFIGURED'),('RLS','ZYTERON_TESTS','NOT_CONFIGURED'),('DAST','NOT_CONFIGURED','NOT_CONFIGURED'),('RESTORE','NOT_CONFIGURED','NOT_CONFIGURED');
insert into public.security_playbooks(code,name,incident_type,steps,status)values
('EXPOSED_SECRET','Secreto expuesto','SECRET_EXPOSURE','["revoke","rotate","inspect_logs","assess_usage","validate_rls","redeploy","postmortem"]','APPROVED'),
('ACCOUNT_COMPROMISE','Cuenta comprometida','ACCOUNT_COMPROMISE','["contain_sessions","lock_identity","preserve_evidence","reset_credentials","review_access","recover","postmortem"]','APPROVED'),
('DATA_BREACH','Brecha de datos','DATA_BREACH','["contain","preserve_evidence","assess_data","privacy_assessment","authorized_notification_review","recover","postmortem"]','APPROVED')
on conflict(code)do nothing;

insert into public.app_permissions(code,description)values
('security.dashboard.view','Ver Security Command Center'),('identity.view','Ver identidades'),('identity.role.manage','Gestionar roles de identidad'),('identity.lock','Bloquear identidades'),('mfa.view','Ver postura MFA'),('role.view','Ver roles'),('permission.view','Ver permisos'),('session.view','Ver sesiones'),('session.revoke','Revocar sesiones'),('device.view','Ver dispositivos'),('device.manage','Gestionar confianza de dispositivos'),('jit.view','Ver accesos temporales'),('jit.request','Solicitar acceso temporal'),('jit.approve','Aprobar acceso temporal'),('jit.revoke','Revocar acceso temporal'),('vault.metadata.view','Ver metadata Vault'),('vault.manage','Gestionar metadata Vault'),('vault.reveal','Revelar secreto con JIT y AAL2'),('vault.rotate','Registrar rotación de secreto'),('security.event.view','Ver eventos de seguridad'),('security.event.triage','Gestionar eventos de seguridad'),('incident.view','Ver incidentes de seguridad'),('incident.create','Crear incidentes'),('incident.manage','Gestionar incidentes'),('incident.close','Cerrar incidentes'),('vulnerability.view','Ver vulnerabilidades'),('vulnerability.manage','Gestionar vulnerabilidades'),('vulnerability.verify','Verificar correcciones'),('rls.audit.view','Ver auditoría RLS'),('privacy.view','Ver Privacy Center'),('privacy.manage','Gestionar inventario y tratamientos'),('privacy.subject_request.view','Ver solicitudes de titulares'),('privacy.subject_request.manage','Gestionar solicitudes de titulares'),('privacy.dpia.manage','Gestionar DPIA'),('dlp.view','Ver eventos DLP'),('vendor_security.view','Ver proveedores'),('vendor_security.manage','Gestionar riesgo de proveedores'),('backup.view','Ver backups y DR'),('backup.test.manage','Registrar pruebas de restauración'),('security.testing.view','Ver pruebas de seguridad'),('security.testing.manage','Registrar pruebas de seguridad'),('compliance.view','Ver controles de cumplimiento'),('compliance.manage','Gestionar controles y evidencia'),('security.gate.view','Ver Security Gate'),('security.gate.evaluate','Evaluar Security Gate'),('security.config.view','Ver configuración no secreta'),('security.config.manage','Gestionar configuración de seguridad'),('security.report.view','Ver reportes de seguridad'),('security.report.export','Exportar reportes restringidos')
on conflict(code)do update set description=excluded.description;
insert into public.role_permissions(role,permission_code)select r.role,p.code from(values('GERENTE_GENERAL'),('SECURITY_ADMIN'))r(role)cross join public.app_permissions p where p.code like'security.%'or p.code like'identity.%'or p.code like'mfa.%'or p.code like'role.%'or p.code like'permission.%'or p.code like'session.%'or p.code like'device.%'or p.code like'jit.%'or p.code like'vault.%'or p.code like'incident.%'or p.code like'vulnerability.%'or p.code like'rls.%'or p.code like'privacy.%'or p.code like'dlp.%'or p.code like'vendor_security.%'or p.code like'backup.%'or p.code like'compliance.%'on conflict do nothing;
insert into public.role_permissions(role,permission_code)values('JEFE_DESARROLLO','vault.metadata.view'),('JEFE_DESARROLLO','jit.request'),('TECH_LEAD','vault.metadata.view'),('TECH_LEAD','jit.request'),('PROGRAMADOR','vault.metadata.view'),('PROGRAMADOR','jit.request'),('RRHH','privacy.subject_request.view'),('FINANZAS','security.dashboard.view')on conflict do nothing;

do $$declare t text;begin foreach t in array array['security_events','security_incidents','security_incident_events','security_session_metadata','registered_devices','access_requests','access_grants','security_vulnerabilities','production_security_gates']loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename=t)then execute format('alter publication supabase_realtime add table public.%I',t);end if;end loop;end$$;

commit;
