begin;

create sequence if not exists public.support_ticket_number_seq;
create or replace function public.next_support_ticket_number() returns text language sql volatile set search_path=public as $$select 'SUP-'||extract(year from now() at time zone 'UTC')::integer||'-'||lpad(nextval('public.support_ticket_number_seq')::text,6,'0')$$;

create table if not exists public.support_ticket_types(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.support_categories(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.support_subcategories(id uuid primary key default gen_random_uuid(),category_id uuid not null references public.support_categories(id) on delete restrict,code text not null,name text not null,active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(category_id,code));
create table if not exists public.support_queues(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text,team_id uuid,privacy_scope text not null default 'NORMAL' check(privacy_scope in('NORMAL','CONFIDENTIAL','RESTRICTED')),assignment_strategy text not null default 'MANUAL' check(assignment_strategy in('ROUND_ROBIN','LEAST_LOADED','PROJECT_OWNER','SERVICE_OWNER','MANUAL')),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.support_queue_members(id uuid primary key default gen_random_uuid(),queue_id uuid not null references public.support_queues(id) on delete restrict,user_id uuid not null,role text not null default 'AGENT' check(role in('AGENT','LEAD','OBSERVER')),active boolean not null default true,created_at timestamptz not null default now(),unique(queue_id,user_id));
create table if not exists public.business_calendars(id uuid primary key default gen_random_uuid(),name text not null,timezone text not null default 'America/Santiago',mode text not null check(mode in('TWENTY_FOUR_SEVEN','BUSINESS_HOURS','CUSTOM')),working_days integer[] not null default '{1,2,3,4,5}',working_hours jsonb not null default '{"start":"09:00","end":"18:00"}'::jsonb,holidays date[] not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.sla_policies(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,scope_type text not null check(scope_type in('GLOBAL','CLIENT','SERVICE','CONTRACT')),scope_id uuid,calendar_id uuid not null references public.business_calendars(id) on delete restrict,pause_statuses text[] not null default '{WAITING_CLIENT}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists sla_policies_scope_unique on public.sla_policies(scope_type,coalesce(scope_id,'00000000-0000-0000-0000-000000000000'::uuid)) where active;
create table if not exists public.sla_targets(id uuid primary key default gen_random_uuid(),policy_id uuid not null references public.sla_policies(id) on delete restrict,priority text not null check(priority in('LOW','NORMAL','HIGH','URGENT')),first_response_minutes integer not null check(first_response_minutes>0),resolution_minutes integer not null check(resolution_minutes>0),update_frequency_minutes integer check(update_frequency_minutes is null or update_frequency_minutes>0),warning_percent integer not null default 80 check(warning_percent between 1 and 99),escalation_percent integer not null default 90 check(escalation_percent between warning_percent and 100),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(policy_id,priority));

create table if not exists public.support_tickets(
 id uuid primary key default gen_random_uuid(),ticket_number text not null unique default public.next_support_ticket_number(),requester_type text not null check(requester_type in('CLIENT','INTERNAL_USER','SYSTEM','MONITORING','EMAIL','PORTAL')),client_id uuid references public.clients(id) on delete restrict,client_contact_id uuid references public.client_contacts(id) on delete restrict,requester_user_id uuid,project_id uuid references public.projects(id) on delete restrict,service_id uuid references public.client_services(id) on delete restrict,subject text not null,description text not null,ticket_type text not null references public.support_ticket_types(code) on delete restrict,category_id uuid references public.support_categories(id) on delete restrict,subcategory_id uuid references public.support_subcategories(id) on delete restrict,channel text not null check(channel in('PORTAL','EMAIL','PHONE','WHATSAPP','INTERNAL','MONITORING','API')),priority text not null default 'NORMAL' check(priority in('LOW','NORMAL','HIGH','URGENT')),severity text not null default 'INFO' check(severity in('INFO','LOW','MEDIUM','HIGH','CRITICAL')),status text not null default 'NEW' check(status in('NEW','TRIAGE','OPEN','ASSIGNED','IN_PROGRESS','WAITING_CLIENT','WAITING_INTERNAL','WAITING_THIRD_PARTY','RESOLVED','CLOSED','CANCELLED','REOPENED')),queue_id uuid references public.support_queues(id) on delete restrict,assigned_to uuid,team_id uuid,sla_policy_id uuid references public.sla_policies(id) on delete restrict,first_response_due_at timestamptz,resolution_due_at timestamptz,first_responded_at timestamptz,resolved_at timestamptz,closed_at timestamptz,resolution_code text check(resolution_code is null or resolution_code in('FIXED','INFORMATION_PROVIDED','CONFIGURATION_CHANGED','DUPLICATE','NOT_REPRODUCIBLE','USER_ERROR','THIRD_PARTY','WONT_FIX','OTHER')),resolution_summary text,root_cause text,client_visibility text not null default 'INTERNAL_ONLY' check(client_visibility in('INTERNAL_ONLY','CLIENT_VISIBLE')),privacy text not null default 'NORMAL' check(privacy in('NORMAL','CONFIDENTIAL','RESTRICTED')),reopened_count integer not null default 0 check(reopened_count>=0),sla_paused_at timestamptz,sla_first_response_remaining_minutes integer,sla_resolution_remaining_minutes integer,archived_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(requester_type not in('CLIENT','PORTAL') or client_id is not null),check(status not in('RESOLVED','CLOSED') or (resolution_code is not null and length(trim(coalesce(resolution_summary,'')))>0))
);
create table if not exists public.support_routing_rules(id uuid primary key default gen_random_uuid(),name text not null,ticket_type text references public.support_ticket_types(code) on delete restrict,category_id uuid references public.support_categories(id) on delete restrict,channel text check(channel is null or channel in('PORTAL','EMAIL','PHONE','WHATSAPP','INTERNAL','MONITORING','API')),client_id uuid references public.clients(id) on delete restrict,queue_id uuid not null references public.support_queues(id) on delete restrict,priority text check(priority is null or priority in('LOW','NORMAL','HIGH','URGENT')),active boolean not null default true,position integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ticket_messages(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,author_type text not null check(author_type in('AGENT','CLIENT','INTERNAL_USER','SYSTEM')),author_user_id uuid,author_contact_id uuid references public.client_contacts(id) on delete restrict,message_type text not null default 'MESSAGE' check(message_type in('MESSAGE','CALL_NOTE','EMAIL','PORTAL_REPLY')),body text not null,visibility text not null check(visibility in('PUBLIC_REPLY','INTERNAL_NOTE','SYSTEM_EVENT')),provider_message_id text,delivery_status text not null default 'NOT_REQUIRED' check(delivery_status in('NOT_REQUIRED','PENDING','SENT','DELIVERY_FAILED')),call_duration_minutes integer check(call_duration_minutes is null or call_duration_minutes>=0),call_outcome text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),edited_at timestamptz);
create table if not exists public.ticket_status_history(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,from_status text,to_status text not null,actor_id uuid,reason text,client_visible boolean not null default false,occurred_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ticket_assignments(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,from_user_id uuid,to_user_id uuid not null,assigned_by uuid,reason text,assigned_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ticket_relations(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,relation_type text not null check(relation_type in('TASK','BUG','INCIDENT','AUDIT_FINDING','CHANGE_REQUEST','FINANCE','PARENT_TICKET','CHILD_TICKET','MERGED_TICKET')),related_id uuid not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(ticket_id,relation_type,related_id));
create table if not exists public.ticket_watchers(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,user_id uuid not null,created_at timestamptz not null default now(),unique(ticket_id,user_id));
create table if not exists public.support_tags(id uuid primary key default gen_random_uuid(),name text not null unique,color text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ticket_tag_assignments(ticket_id uuid not null references public.support_tickets(id) on delete restrict,tag_id uuid not null references public.support_tags(id) on delete restrict,assigned_by uuid,created_at timestamptz not null default now(),primary key(ticket_id,tag_id));
create table if not exists public.support_saved_views(id uuid primary key default gen_random_uuid(),user_id uuid not null,name text not null,filters jsonb not null default '{}'::jsonb,shared boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ticket_attachments(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,message_id uuid references public.ticket_messages(id) on delete restrict,document_id uuid,storage_path text not null,filename text not null,mime_type text not null,size_bytes bigint not null check(size_bytes>0 and size_bytes<=20971520),sha256 text not null check(sha256~'^[a-f0-9]{64}$'),visibility text not null default 'INTERNAL_ONLY' check(visibility in('INTERNAL_ONLY','CLIENT_VISIBLE')),uploaded_by uuid,malware_status text not null default 'NOT_SCANNED' check(malware_status in('NOT_SCANNED','CLEAN','QUARANTINED','FAILED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.sla_events(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,target_type text not null check(target_type in('FIRST_RESPONSE','RESOLUTION','UPDATE_FREQUENCY','ALL')),event_type text not null check(event_type in('STARTED','PAUSED','RESUMED','WARNING','BREACHED','COMPLETED')),occurred_at timestamptz not null default now(),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists public.support_macros(id uuid primary key default gen_random_uuid(),name text not null,body text not null,status text,category_id uuid references public.support_categories(id) on delete restrict,tags text[] not null default '{}',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.knowledge_categories(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,visibility text not null default 'INTERNAL' check(visibility in('INTERNAL','CLIENT','PUBLIC')),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.knowledge_articles(id uuid primary key default gen_random_uuid(),category_id uuid references public.knowledge_categories(id) on delete restrict,title text not null,slug text not null unique,summary text not null,status text not null default 'DRAFT' check(status in('DRAFT','REVIEW','PUBLISHED','ARCHIVED')),visibility text not null default 'INTERNAL' check(visibility in('INTERNAL','CLIENT','PUBLIC')),current_version integer not null default 1 check(current_version>0),author_id uuid,reviewer_id uuid,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.knowledge_versions(id uuid primary key default gen_random_uuid(),article_id uuid not null references public.knowledge_articles(id) on delete restrict,version integer not null check(version>0),content text not null,change_summary text,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(article_id,version));
create table if not exists public.support_channel_connections(id uuid primary key default gen_random_uuid(),provider text not null,display_name text not null,status text not null default 'NOT_CONFIGURED' check(status in('NOT_CONFIGURED','CONNECTED','ERROR','DISCONNECTED')),external_reference text,last_sync_at timestamptz,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.support_email_threads(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete restrict,provider text not null,provider_thread_id text,provider_message_id text not null,in_reply_to text,from_address text not null,received_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider,provider_message_id));
create table if not exists public.csat_surveys(id uuid primary key default gen_random_uuid(),ticket_id uuid not null unique references public.support_tickets(id) on delete restrict,status text not null default 'PENDING' check(status in('PENDING','SENT','COMPLETED','EXPIRED')),invited_at timestamptz,expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.csat_responses(id uuid primary key default gen_random_uuid(),ticket_id uuid not null unique references public.support_tickets(id) on delete restrict,rating integer not null check(rating between 1 and 5),comment text,submitted_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.support_events(id uuid primary key default gen_random_uuid(),ticket_id uuid references public.support_tickets(id) on delete restrict,event_type text not null,actor_id uuid,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());

create index if not exists support_tickets_client_idx on public.support_tickets(client_id,status,updated_at desc);
create index if not exists support_tickets_contact_idx on public.support_tickets(client_contact_id,created_at desc);
create index if not exists support_tickets_project_idx on public.support_tickets(project_id,status) where project_id is not null;
create index if not exists support_tickets_service_idx on public.support_tickets(service_id,status) where service_id is not null;
create index if not exists support_tickets_assigned_idx on public.support_tickets(assigned_to,status,priority);
create index if not exists support_tickets_queue_idx on public.support_tickets(queue_id,status,priority,updated_at);
create index if not exists support_tickets_sla_response_idx on public.support_tickets(first_response_due_at) where first_responded_at is null and archived_at is null;
create index if not exists support_tickets_sla_resolution_idx on public.support_tickets(resolution_due_at) where resolved_at is null and archived_at is null;
create index if not exists support_tickets_search_idx on public.support_tickets using gin(to_tsvector('spanish',ticket_number||' '||subject||' '||description));
create index if not exists ticket_messages_timeline_idx on public.ticket_messages(ticket_id,created_at desc);
create index if not exists support_events_ticket_idx on public.support_events(ticket_id,occurred_at desc);

create or replace function public.support_status_transition_guard() returns trigger language plpgsql set search_path=public as $$declare allowed text[];begin if new.status=old.status then return new;end if;allowed:=case old.status when 'NEW' then array['TRIAGE','ASSIGNED','CANCELLED'] when 'TRIAGE' then array['OPEN','ASSIGNED','WAITING_INTERNAL','CANCELLED'] when 'OPEN' then array['ASSIGNED','IN_PROGRESS','WAITING_CLIENT','WAITING_INTERNAL','WAITING_THIRD_PARTY','RESOLVED','CANCELLED'] when 'ASSIGNED' then array['IN_PROGRESS','WAITING_CLIENT','WAITING_INTERNAL','WAITING_THIRD_PARTY','RESOLVED','CANCELLED'] when 'IN_PROGRESS' then array['WAITING_CLIENT','WAITING_INTERNAL','WAITING_THIRD_PARTY','RESOLVED','CANCELLED'] when 'WAITING_CLIENT' then array['IN_PROGRESS','RESOLVED','CANCELLED'] when 'WAITING_INTERNAL' then array['TRIAGE','ASSIGNED','IN_PROGRESS','RESOLVED','CANCELLED'] when 'WAITING_THIRD_PARTY' then array['IN_PROGRESS','RESOLVED','CANCELLED'] when 'RESOLVED' then array['CLOSED','REOPENED'] when 'CLOSED' then array['REOPENED'] when 'CANCELLED' then array['REOPENED'] when 'REOPENED' then array['TRIAGE','ASSIGNED','IN_PROGRESS'] else array[]::text[] end;if not(new.status=any(allowed))then raise exception 'Transición de ticket % → % no permitida',old.status,new.status;end if;return new;end$$;
drop trigger if exists support_ticket_status_guard on public.support_tickets;create trigger support_ticket_status_guard before update of status on public.support_tickets for each row execute function public.support_status_transition_guard();
create or replace function public.knowledge_version_immutable() returns trigger language plpgsql set search_path=public as $$begin raise exception 'Las versiones de conocimiento son inmutables; crea una nueva versión';end$$;
drop trigger if exists knowledge_version_immutable on public.knowledge_versions;create trigger knowledge_version_immutable before update or delete on public.knowledge_versions for each row execute function public.knowledge_version_immutable();
create or replace function public.support_event_to_outbox() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.business_event_outbox(aggregate_type,aggregate_id,event_type,payload) values('SUPPORT_TICKET',coalesce(new.ticket_id,new.id),new.event_type,jsonb_build_object('ticketId',new.ticket_id,'supportEventId',new.id)||new.payload);return new;end$$;
drop trigger if exists support_event_outbox on public.support_events;create trigger support_event_outbox after insert on public.support_events for each row execute function public.support_event_to_outbox();

create or replace function private.support_portal_client_id() returns uuid language sql stable security definer set search_path=public as $$select client_id from public.client_portal_users where auth_user_id=auth.uid() and status='ACTIVE' limit 1$$;
create or replace function private.support_can_manage() returns boolean language sql stable security definer set search_path=public as $$select private.zyteron_role() in('GERENTE_GENERAL','JEFE_DESARROLLO','TECH_LEAD','SOPORTE_TECNICO')$$;
create or replace function private.support_can_read(target_ticket_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.support_tickets t where t.id=target_ticket_id and (private.support_can_manage() or t.assigned_to=auth.uid() or exists(select 1 from public.support_queue_members qm where qm.queue_id=t.queue_id and qm.user_id=auth.uid() and qm.active) or (t.project_id is not null and private.can_access_project(t.project_id)) or (private.zyteron_role()='FINANZAS' and t.ticket_type='BILLING_QUERY') or (private.zyteron_role()='RRHH' and t.requester_type='INTERNAL_USER' and (t.privacy='RESTRICTED' or exists(select 1 from public.support_queues q where q.id=t.queue_id and q.code='HR'))) or (private.zyteron_role() in('JEFE_VENTAS','EJECUTIVA_VENTAS','COMERCIAL') and t.client_id is not null and private.can_access_client(t.client_id)) or (private.zyteron_role()='PORTAL_CLIENT' and t.client_id=private.support_portal_client_id() and t.client_visibility='CLIENT_VISIBLE')))$$;

do $$declare t text;begin foreach t in array array['support_ticket_types','support_categories','support_subcategories','support_queues','support_queue_members','business_calendars','sla_policies','sla_targets','support_tickets','support_routing_rules','ticket_messages','ticket_status_history','ticket_assignments','ticket_relations','ticket_watchers','support_tags','ticket_tag_assignments','support_saved_views','ticket_attachments','sla_events','support_macros','knowledge_categories','knowledge_articles','knowledge_versions','support_channel_connections','support_email_threads','csat_surveys','csat_responses','support_events'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['support_ticket_types','support_categories','support_subcategories','support_queues','business_calendars','sla_policies','sla_targets','support_routing_rules','support_macros','knowledge_categories','knowledge_articles','knowledge_versions'] loop execute format('drop policy if exists support_config_read on public.%I',t);execute format('create policy support_config_read on public.%I for select to authenticated using (private.zyteron_role()<>''PORTAL_CLIENT'')',t);execute format('drop policy if exists support_config_manage on public.%I',t);execute format('create policy support_config_manage on public.%I for all to authenticated using (private.support_can_manage()) with check (private.support_can_manage())',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['support_ticket_types','support_categories','support_subcategories'] loop execute format('drop policy if exists support_catalog_portal_read on public.%I',t);execute format('create policy support_catalog_portal_read on public.%I for select to authenticated using (active)',t);end loop;end$$;
drop policy if exists support_knowledge_categories_portal_read on public.knowledge_categories;create policy support_knowledge_categories_portal_read on public.knowledge_categories for select to authenticated using(active and visibility in('CLIENT','PUBLIC'));
drop policy if exists support_knowledge_articles_portal_read on public.knowledge_articles;create policy support_knowledge_articles_portal_read on public.knowledge_articles for select to authenticated using(status='PUBLISHED' and visibility in('CLIENT','PUBLIC'));
drop policy if exists support_knowledge_versions_portal_read on public.knowledge_versions;create policy support_knowledge_versions_portal_read on public.knowledge_versions for select to authenticated using(exists(select 1 from public.knowledge_articles a where a.id=article_id and a.status='PUBLISHED' and a.visibility in('CLIENT','PUBLIC') and a.current_version=version));
drop policy if exists support_tickets_scope on public.support_tickets;create policy support_tickets_scope on public.support_tickets for select to authenticated using(private.support_can_read(id));
drop policy if exists support_tickets_create on public.support_tickets;create policy support_tickets_create on public.support_tickets for insert to authenticated with check(private.zyteron_role()<>'PORTAL_CLIENT' and (private.support_can_manage() or created_by=auth.uid() or requester_user_id=auth.uid()));
drop policy if exists support_tickets_update on public.support_tickets;create policy support_tickets_update on public.support_tickets for update to authenticated using(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(id)) with check(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(id));
drop policy if exists ticket_messages_read on public.ticket_messages;create policy ticket_messages_read on public.ticket_messages for select to authenticated using(private.support_can_read(ticket_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or visibility in('PUBLIC_REPLY','SYSTEM_EVENT')));
drop policy if exists ticket_messages_write on public.ticket_messages;create policy ticket_messages_write on public.ticket_messages for insert to authenticated with check(private.support_can_read(ticket_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or (visibility='PUBLIC_REPLY' and author_type='CLIENT')));
do $$declare t text;begin foreach t in array array['ticket_assignments','ticket_relations','ticket_watchers','sla_events','support_email_threads','support_events'] loop execute format('drop policy if exists support_ticket_child_scope on public.%I',t);execute format('create policy support_ticket_child_scope on public.%I for all to authenticated using (private.zyteron_role()<>''PORTAL_CLIENT'' and private.support_can_read(ticket_id)) with check (private.zyteron_role()<>''PORTAL_CLIENT'' and private.support_can_read(ticket_id))',t);end loop;end$$;
drop policy if exists support_status_history_read on public.ticket_status_history;create policy support_status_history_read on public.ticket_status_history for select to authenticated using(private.support_can_read(ticket_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or client_visible));
drop policy if exists support_status_history_write on public.ticket_status_history;create policy support_status_history_write on public.ticket_status_history for all to authenticated using(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(ticket_id)) with check(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(ticket_id));
drop policy if exists support_attachments_read on public.ticket_attachments;create policy support_attachments_read on public.ticket_attachments for select to authenticated using(private.support_can_read(ticket_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or visibility='CLIENT_VISIBLE'));
drop policy if exists support_attachments_write on public.ticket_attachments;create policy support_attachments_write on public.ticket_attachments for all to authenticated using(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(ticket_id)) with check(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(ticket_id));
drop policy if exists support_csat_surveys_read on public.csat_surveys;create policy support_csat_surveys_read on public.csat_surveys for select to authenticated using(private.support_can_read(ticket_id));
drop policy if exists support_csat_surveys_write on public.csat_surveys;create policy support_csat_surveys_write on public.csat_surveys for all to authenticated using(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(ticket_id)) with check(private.zyteron_role()<>'PORTAL_CLIENT' and private.support_can_read(ticket_id));
drop policy if exists support_csat_responses_scope on public.csat_responses;create policy support_csat_responses_scope on public.csat_responses for select to authenticated using(private.support_can_read(ticket_id));
drop policy if exists support_csat_responses_create on public.csat_responses;create policy support_csat_responses_create on public.csat_responses for insert to authenticated with check(private.support_can_read(ticket_id) and exists(select 1 from public.support_tickets t where t.id=ticket_id and t.status='CLOSED'));
drop policy if exists support_queue_members_scope on public.support_queue_members;create policy support_queue_members_scope on public.support_queue_members for select to authenticated using(user_id=auth.uid() or private.support_can_manage());
drop policy if exists support_queue_members_manage on public.support_queue_members;create policy support_queue_members_manage on public.support_queue_members for all to authenticated using(private.support_can_manage()) with check(private.support_can_manage());
drop policy if exists support_tags_read on public.support_tags;create policy support_tags_read on public.support_tags for select to authenticated using(true);
drop policy if exists support_tags_manage on public.support_tags;create policy support_tags_manage on public.support_tags for all to authenticated using(private.support_can_manage()) with check(private.support_can_manage());
drop policy if exists ticket_tags_scope on public.ticket_tag_assignments;create policy ticket_tags_scope on public.ticket_tag_assignments for all to authenticated using(private.support_can_read(ticket_id)) with check(private.support_can_read(ticket_id));
drop policy if exists support_saved_views_own on public.support_saved_views;create policy support_saved_views_own on public.support_saved_views for all to authenticated using(user_id=auth.uid() or shared or private.support_can_manage()) with check(user_id=auth.uid() or private.support_can_manage());
drop policy if exists support_channels_manage on public.support_channel_connections;create policy support_channels_manage on public.support_channel_connections for all to authenticated using(private.support_can_manage()) with check(private.support_can_manage());

insert into public.app_permissions(code,description) values
('support.dashboard.view','Ver Support Command Center'),('ticket.view','Ver tickets'),('ticket.create','Crear tickets'),('ticket.edit','Editar tickets'),('ticket.assign','Asignar tickets'),('ticket.reassign','Reasignar tickets'),('ticket.change_priority','Cambiar prioridad'),('ticket.change_status','Cambiar estado'),('ticket.resolve','Resolver tickets'),('ticket.close','Cerrar tickets'),('ticket.reopen','Reabrir tickets'),('ticket.merge','Fusionar tickets'),('ticket.split','Separar tickets'),('ticket.reply','Responder tickets'),('ticket.internal_note','Crear notas internas'),('sla.view','Ver SLA'),('sla.manage','Gestionar SLA'),('queue.view','Ver colas'),('queue.manage','Gestionar colas'),('support_macro.view','Ver respuestas rápidas'),('support_macro.manage','Gestionar respuestas rápidas'),('knowledge.view','Ver conocimiento'),('knowledge.manage','Gestionar conocimiento'),('csat.view','Ver CSAT'),('support.report.view','Ver informes de soporte'),('support.export','Exportar soporte'),('internal_request.view','Ver solicitudes internas'),('internal_request.manage','Gestionar solicitudes internas') on conflict(code) do update set description=excluded.description;
insert into public.role_permissions(role,permission_code) select r.role,p.code from(values('GERENTE_GENERAL'),('SOPORTE_TECNICO'))r(role) cross join public.app_permissions p where p.code like any(array['support.%','ticket.%','sla.%','queue.%','support_macro.%','knowledge.%','csat.%','internal_request.%']) on conflict do nothing;
insert into public.role_permissions(role,permission_code) select r.role,p.code from(values('JEFE_DESARROLLO'),('TECH_LEAD'),('OPERACIONES'))r(role) cross join public.app_permissions p where p.code in('support.dashboard.view','ticket.view','ticket.create','ticket.edit','ticket.assign','ticket.change_priority','ticket.change_status','ticket.resolve','ticket.reply','ticket.internal_note','sla.view','queue.view','support_macro.view','knowledge.view','internal_request.view') on conflict do nothing;
insert into public.role_permissions(role,permission_code) select r.role,p.code from(values('PROGRAMADOR'),('DESARROLLO'),('QA'),('FINANZAS'),('RRHH'),('JEFE_VENTAS'),('EJECUTIVA_VENTAS'),('COMERCIAL'))r(role) cross join public.app_permissions p where p.code in('support.dashboard.view','ticket.view','ticket.create','ticket.reply','sla.view','knowledge.view','internal_request.view') on conflict do nothing;
insert into public.role_permissions(role,permission_code) values('PORTAL_CLIENT','ticket.view'),('PORTAL_CLIENT','ticket.create'),('PORTAL_CLIENT','ticket.reply'),('PORTAL_CLIENT','ticket.reopen'),('PORTAL_CLIENT','knowledge.view') on conflict do nothing;

insert into public.support_ticket_types(code,name,sort_order) values('INCIDENT','Incidente',10),('SERVICE_REQUEST','Solicitud de servicio',20),('TECHNICAL_SUPPORT','Soporte técnico',30),('BUG_REPORT','Reporte de error',40),('FEATURE_REQUEST','Solicitud de funcionalidad',50),('CHANGE_REQUEST','Solicitud de cambio',60),('ACCESS_REQUEST','Solicitud de acceso',70),('BILLING_QUERY','Consulta de facturación',80),('DOCUMENT_REQUEST','Solicitud documental',90),('CONSULTATION','Consulta',100),('COMPLAINT','Reclamo',110),('OTHER','Otro',120) on conflict(code) do nothing;
insert into public.support_categories(id,code,name,sort_order) values('b0000000-0000-4000-8000-000000000001','WEB','Web',10),('b0000000-0000-4000-8000-000000000002','SOFTWARE','Software',20),('b0000000-0000-4000-8000-000000000003','HOSTING','Hosting',30),('b0000000-0000-4000-8000-000000000004','EMAIL','Correo',40),('b0000000-0000-4000-8000-000000000005','DOMAIN','Dominio',50),('b0000000-0000-4000-8000-000000000006','BILLING','Facturación',60),('b0000000-0000-4000-8000-000000000007','ACCESS','Accesos',70),('b0000000-0000-4000-8000-000000000008','ADVICE','Asesoría',80) on conflict(code) do nothing;
insert into public.support_queues(id,code,name,privacy_scope,assignment_strategy) values('b1000000-0000-4000-8000-000000000001','GENERAL','Soporte General','NORMAL','MANUAL'),('b1000000-0000-4000-8000-000000000002','DEVELOPMENT','Desarrollo','NORMAL','LEAST_LOADED'),('b1000000-0000-4000-8000-000000000003','BILLING','Facturación','CONFIDENTIAL','MANUAL'),('b1000000-0000-4000-8000-000000000004','INFRA','Infraestructura','NORMAL','MANUAL'),('b1000000-0000-4000-8000-000000000005','HR','RR.HH. Interno','RESTRICTED','MANUAL'),('b1000000-0000-4000-8000-000000000006','IT','TI Interno','CONFIDENTIAL','MANUAL') on conflict(code) do nothing;
insert into public.business_calendars(id,name,timezone,mode,working_days,working_hours) values('b2000000-0000-4000-8000-000000000001','Horario Zyteron','America/Santiago','BUSINESS_HOURS','{1,2,3,4,5}','{"start":"09:00","end":"18:00"}') on conflict(id) do nothing;
insert into public.sla_policies(id,code,name,scope_type,scope_id,calendar_id,pause_statuses) values('b3000000-0000-4000-8000-000000000001','GLOBAL-BH','SLA Global Horario Hábil','GLOBAL',null,'b2000000-0000-4000-8000-000000000001','{WAITING_CLIENT}') on conflict(code) do nothing;
insert into public.sla_targets(policy_id,priority,first_response_minutes,resolution_minutes,warning_percent,escalation_percent) values('b3000000-0000-4000-8000-000000000001','LOW',480,2880,80,90),('b3000000-0000-4000-8000-000000000001','NORMAL',240,1440,80,90),('b3000000-0000-4000-8000-000000000001','HIGH',60,480,80,90),('b3000000-0000-4000-8000-000000000001','URGENT',15,120,70,85) on conflict(policy_id,priority) do nothing;
insert into public.support_routing_rules(name,ticket_type,queue_id,priority,position) values('Consultas de facturación','BILLING_QUERY','b1000000-0000-4000-8000-000000000003','NORMAL',10),('Bugs a Desarrollo','BUG_REPORT','b1000000-0000-4000-8000-000000000002','HIGH',20) on conflict do nothing;
insert into public.support_macros(name,body,tags) select 'Solicitud recibida','Hola {{contact.name}}, recibimos {{ticket.number}} y estamos revisando tu solicitud.','{}' where not exists(select 1 from public.support_macros where name='Solicitud recibida');
insert into public.knowledge_categories(id,name,slug,visibility) values('b4000000-0000-4000-8000-000000000001','Uso de soporte','uso-soporte','CLIENT') on conflict(slug) do nothing;
insert into public.knowledge_articles(id,category_id,title,slug,summary,status,visibility,current_version,published_at) values('b5000000-0000-4000-8000-000000000001','b4000000-0000-4000-8000-000000000001','Cómo enviar evidencia segura','evidencia-segura','Guía para adjuntar información útil sin credenciales ni secretos.','PUBLISHED','CLIENT',1,now()) on conflict(slug) do nothing;
insert into public.knowledge_versions(article_id,version,content,change_summary) values('b5000000-0000-4000-8000-000000000001',1,'Describe el resultado esperado, adjunta capturas sin credenciales y nunca compartas contraseñas, tokens o cookies.','Versión inicial') on conflict(article_id,version) do nothing;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('support-attachments','support-attachments',false,20971520,array['image/png','image/jpeg','application/pdf','text/plain','video/mp4','application/vnd.openxmlformats-officedocument.wordprocessingml.document']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists support_attachment_storage_read on storage.objects;create policy support_attachment_storage_read on storage.objects for select to authenticated using(bucket_id='support-attachments' and exists(select 1 from public.ticket_attachments a where a.storage_path=name and private.support_can_read(a.ticket_id) and (private.zyteron_role()<>'PORTAL_CLIENT' or a.visibility='CLIENT_VISIBLE')));
drop policy if exists support_attachment_storage_write on storage.objects;create policy support_attachment_storage_write on storage.objects for insert to authenticated with check(bucket_id='support-attachments' and private.zyteron_role()<>'PORTAL_CLIENT');
do $$declare t text;begin foreach t in array array['support_tickets','ticket_messages','ticket_status_history','ticket_assignments','ticket_relations','ticket_attachments','sla_events','support_events','csat_responses'] loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t)then execute format('alter publication supabase_realtime add table public.%I',t);end if;end loop;end$$;

commit;
