begin;

create extension if not exists pgcrypto;
create sequence if not exists public.sales_quote_number_seq;

create or replace function public.next_sales_quote_number()
returns text language sql volatile set search_path=public
as $$ select 'COT-' || extract(year from now())::integer || '-' || lpad(nextval('public.sales_quote_number_seq')::text,6,'0') $$;

create table if not exists public.lead_sources(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,position integer not null default 0,active boolean not null default true,created_at timestamptz not null default now());
insert into public.lead_sources(code,name,position) values ('WEB','Web',10),('GOOGLE','Google',20),('EMAIL','Email',30),('LINKEDIN','LinkedIn',40),('INSTAGRAM','Instagram',50),('REFERIDO','Referido',60),('PRESENCIAL','Presencial',70),('OUTBOUND','Outbound',80),('PARTNER','Partner',90),('OTRO','Otro',100) on conflict(code) do nothing;

create table if not exists public.sales_pipelines(id uuid primary key default gen_random_uuid(),name text not null,is_default boolean not null default false,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists sales_pipelines_one_default on public.sales_pipelines(is_default) where is_default;
insert into public.sales_pipelines(id,name,is_default) values('20000000-0000-4000-8000-000000000001','Pipeline Comercial',true) on conflict(id) do nothing;
create table if not exists public.pipeline_stages(id uuid primary key default gen_random_uuid(),pipeline_id uuid not null references public.sales_pipelines(id) on delete restrict,code text not null,name text not null,position integer not null,probability numeric(5,2) not null check(probability between 0 and 100),kind text not null default 'OPEN' check(kind in('OPEN','WON','LOST')),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(pipeline_id,code),unique(pipeline_id,position));
insert into public.pipeline_stages(id,pipeline_id,code,name,position,probability,kind) values
('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','NEW','Nuevo',1,10,'OPEN'),
('10000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000001','CONTACTED','Contactado',2,20,'OPEN'),
('10000000-0000-4000-8000-000000000003','20000000-0000-4000-8000-000000000001','QUALIFICATION','Calificación',3,35,'OPEN'),
('10000000-0000-4000-8000-000000000004','20000000-0000-4000-8000-000000000001','DISCOVERY','Levantamiento',4,50,'OPEN'),
('10000000-0000-4000-8000-000000000005','20000000-0000-4000-8000-000000000001','PROPOSAL','Propuesta',5,65,'OPEN'),
('10000000-0000-4000-8000-000000000006','20000000-0000-4000-8000-000000000001','NEGOTIATION','Negociación',6,80,'OPEN'),
('10000000-0000-4000-8000-000000000007','20000000-0000-4000-8000-000000000001','WON','Ganado',7,100,'WON'),
('10000000-0000-4000-8000-000000000008','20000000-0000-4000-8000-000000000001','LOST','Perdido',8,0,'LOST') on conflict(id) do nothing;

create table if not exists public.lost_reason_catalog(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,explanation_required boolean not null default false,active boolean not null default true,created_at timestamptz not null default now());
insert into public.lost_reason_catalog(code,name,explanation_required) values('PRICE','Precio',false),('NO_RESPONSE','Sin respuesta',false),('COMPETITION','Competencia',false),('BUDGET','Presupuesto',false),('POSTPONED','Postergado',false),('NOT_QUALIFIED','No califica',false),('OTHER','Otro',true) on conflict(code) do nothing;

create table if not exists public.leads(
 id uuid primary key default gen_random_uuid(),company_name text not null,contact_name text not null,email text,phone text,whatsapp text,website text,rut text,source_id uuid references public.lead_sources(id) on delete restrict,campaign text,interest text,notes text,assigned_to uuid,status text not null default 'NEW' check(status in('NEW','ASSIGNED','CONTACT_PENDING','CONTACTED','QUALIFYING','QUALIFIED','DISQUALIFIED','CONVERTED')),score numeric(5,2) check(score is null or score between 0 and 100),score_reason text not null default 'Información insuficiente',next_action_at timestamptz,client_id uuid references public.clients(id) on delete restrict,assigned_by uuid,assigned_at timestamptz,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,check(email is not null or phone is not null or whatsapp is not null));
create index if not exists leads_status_owner_idx on public.leads(status,assigned_to) where archived_at is null;
create index if not exists leads_next_action_idx on public.leads(next_action_at) where archived_at is null;
create index if not exists leads_email_lower_idx on public.leads(lower(email)) where email is not null and archived_at is null;
create table if not exists public.lead_assignments(id uuid primary key default gen_random_uuid(),lead_id uuid not null references public.leads(id) on delete restrict,assigned_to uuid not null,assigned_by uuid,assigned_at timestamptz not null default now(),unassigned_at timestamptz,reason text);

create table if not exists public.opportunities(
 id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete restrict,lead_id uuid references public.leads(id) on delete restrict,company text not null,name text not null,description text,service_category text,owner_id uuid,estimated_value numeric(16,2) not null default 0 check(estimated_value>=0),currency char(3) not null default 'CLP' check(currency in('CLP','UF','USD')),probability numeric(5,2) not null check(probability between 0 and 100),pipeline_id uuid not null references public.sales_pipelines(id) on delete restrict,stage_id uuid not null references public.pipeline_stages(id) on delete restrict,expected_close_date date,next_action_at timestamptz,status text not null default 'OPEN' check(status in('OPEN','WON','LOST','ARCHIVED')),lost_reason_id uuid references public.lost_reason_catalog(id) on delete restrict,lost_explanation text,stage_entered_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(client_id is not null or lead_id is not null));
create index if not exists opportunities_stage_owner_idx on public.opportunities(stage_id,owner_id,status);
create index if not exists opportunities_close_idx on public.opportunities(expected_close_date) where status='OPEN';
create table if not exists public.opportunity_stage_history(id uuid primary key default gen_random_uuid(),opportunity_id uuid not null references public.opportunities(id) on delete restrict,from_stage_id uuid references public.pipeline_stages(id) on delete restrict,to_stage_id uuid not null references public.pipeline_stages(id) on delete restrict,changed_by uuid,changed_at timestamptz not null default now(),duration_previous_stage_seconds bigint check(duration_previous_stage_seconds is null or duration_previous_stage_seconds>=0),reason text);

create table if not exists public.follow_ups(id uuid primary key default gen_random_uuid(),lead_id uuid references public.leads(id) on delete restrict,opportunity_id uuid references public.opportunities(id) on delete restrict,client_id uuid references public.clients(id) on delete restrict,assigned_to uuid,type text not null check(type in('CALL','EMAIL','WHATSAPP','MEETING','PROPOSAL','FOLLOW_UP','OTHER')),title text not null,description text,scheduled_at timestamptz not null,completed_at timestamptz,status text not null default 'PENDING' check(status in('PENDING','COMPLETED','CANCELLED')),outcome text,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(lead_id is not null or opportunity_id is not null or client_id is not null));
create index if not exists follow_ups_schedule_owner_idx on public.follow_ups(scheduled_at,assigned_to,status);

create table if not exists public.discount_policies(id uuid primary key default gen_random_uuid(),role text not null,service_category text not null default '*',maximum_percent numeric(5,2) not null check(maximum_percent between 0 and 100),active boolean not null default true,created_at timestamptz not null default now(),unique(role,service_category));
insert into public.discount_policies(role,service_category,maximum_percent) values('EJECUTIVA_VENTAS','*',10),('JEFE_VENTAS','*',25),('COMERCIAL','*',25),('GERENTE_GENERAL','*',100) on conflict(role,service_category) do nothing;

create table if not exists public.document_templates(id uuid primary key default gen_random_uuid(),code text not null,version integer not null,name text not null,body_html text not null,active boolean not null default true,created_at timestamptz not null default now(),unique(code,version));
insert into public.document_templates(code,version,name,body_html) values('SALES_QUOTE',1,'Cotización Zyteron V1','Plantilla server-side administrada por QuoteDocumentService') on conflict(code,version) do nothing;

create table if not exists public.quotes(
 id uuid primary key default gen_random_uuid(),quote_number text not null unique default public.next_sales_quote_number(),version integer not null default 1 check(version>0),client_id uuid references public.clients(id) on delete restrict,lead_id uuid references public.leads(id) on delete restrict,opportunity_id uuid references public.opportunities(id) on delete restrict,company_name text not null,contact_name text,contact_email text,owner_id uuid,status text not null default 'DRAFT' check(status in('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','READY_TO_SEND','SENT','NEGOTIATING','ACCEPTED','DECLINED','EXPIRED','CONVERTED','CANCELLED')),currency char(3) not null default 'CLP' check(currency in('CLP','UF','USD')),uf_value numeric(16,4),uf_value_date date,subtotal numeric(16,2) not null default 0 check(subtotal>=0),discount_total numeric(16,2) not null default 0 check(discount_total>=0),net_amount numeric(16,2) not null default 0 check(net_amount>=0),tax_rate numeric(5,2) not null default 19 check(tax_rate between 0 and 100),tax_amount numeric(16,2) not null default 0 check(tax_amount>=0),total_amount numeric(16,2) not null default 0 check(total_amount>=0),valid_until date,payment_terms text,commercial_terms text,notes text,document_id uuid,document_hash text,sent_at timestamptz,accepted_at timestamptz,sale_id uuid,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(client_id is not null or lead_id is not null or opportunity_id is not null));
create index if not exists quotes_status_owner_idx on public.quotes(status,owner_id);
create index if not exists quotes_valid_until_idx on public.quotes(valid_until) where status in('SENT','NEGOTIATING');
create table if not exists public.quote_items(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,catalog_service_id uuid references public.service_catalog(id) on delete restrict,description text not null,quantity numeric(12,3) not null check(quantity>0),unit_price numeric(16,2) not null check(unit_price>=0),discount_percent numeric(5,2) not null default 0 check(discount_percent between 0 and 100),taxable boolean not null default true,subtotal numeric(16,2) not null check(subtotal>=0),position integer not null default 0);
create table if not exists public.quote_versions(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,version_number integer not null check(version_number>0),snapshot jsonb not null,document_id uuid,document_hash text,storage_path text,created_by uuid,created_at timestamptz not null default now(),unique(quote_id,version_number));
create table if not exists public.quote_approvals(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,quote_version integer not null,requested_by uuid,approver_id uuid,status text not null default 'PENDING' check(status in('PENDING','APPROVED','REJECTED','CANCELLED')),reason text,decided_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.quote_recipients(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,contact_id uuid references public.client_contacts(id) on delete restrict,name text,email text not null,recipient_type text not null default 'TO' check(recipient_type in('TO','CC','BCC')),created_at timestamptz not null default now());
create table if not exists public.quote_events(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,event_type text not null,actor_id uuid,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());
create table if not exists public.commercial_documents(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,quote_version_id uuid references public.quote_versions(id) on delete restrict,storage_path text not null,document_hash text not null,generated_by uuid,template_version text not null,mime_type text not null default 'application/pdf',generated_at timestamptz not null default now(),unique(document_hash));
create table if not exists public.quote_email_deliveries(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,document_id uuid references public.commercial_documents(id) on delete restrict,to_addresses text[] not null,cc_addresses text[] not null default '{}',bcc_addresses text[] not null default '{}',subject text not null,sent_by uuid,provider text not null,provider_message_id text not null,delivery_status text not null,sent_at timestamptz not null,created_at timestamptz not null default now(),unique(provider,provider_message_id));
create table if not exists public.quote_proposal_links(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,quote_version_id uuid not null references public.quote_versions(id) on delete restrict,token_hash text not null unique,expires_at timestamptz not null,max_uses integer not null default 10 check(max_uses>0),use_count integer not null default 0,revoked_at timestamptz,created_by uuid,created_at timestamptz not null default now());
create table if not exists public.quote_acceptance_evidence(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete restrict,quote_version_id uuid not null references public.quote_versions(id) on delete restrict,action text not null check(action in('ACCEPTED','DECLINED','CHANGE_REQUESTED')),contact_identity jsonb not null,ip inet,user_agent text,evidence jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());

create table if not exists public.work_orders(id uuid primary key default gen_random_uuid(),work_order_number text not null unique default('OT-'||extract(year from now())::integer||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),client_id uuid references public.clients(id) on delete restrict,quote_id uuid not null unique references public.quotes(id) on delete restrict,quote_version integer not null,scope text not null,priority text not null default 'NORMAL' check(priority in('LOW','NORMAL','HIGH','URGENT')),deadline date,commercial_owner_id uuid,development_owner_id uuid,status text not null default 'PENDING_HANDOFF' check(status in('PENDING_HANDOFF','READY','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED')),commercial_notes text,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.sales(id uuid primary key default gen_random_uuid(),quote_id uuid not null unique references public.quotes(id) on delete restrict,quote_version_id uuid references public.quote_versions(id) on delete restrict,opportunity_id uuid references public.opportunities(id) on delete restrict,client_id uuid references public.clients(id) on delete restrict,amount numeric(16,2) not null check(amount>=0),currency char(3) not null,owner_id uuid,closed_at timestamptz not null default now(),contract_id uuid references public.client_contracts(id) on delete restrict,work_order_id uuid references public.work_orders(id) on delete restrict,status text not null default 'WON' check(status in('WON','CANCELLED')),created_at timestamptz not null default now());
alter table public.quotes drop constraint if exists quotes_sale_fk;
alter table public.quotes add constraint quotes_sale_fk foreign key(sale_id) references public.sales(id) on delete restrict not valid;

create table if not exists public.sales_goals(id uuid primary key default gen_random_uuid(),user_id uuid,team_id uuid,period_type text not null check(period_type in('MONTH','QUARTER','YEAR')),period_start date not null,period_end date not null,goal_type text not null check(goal_type in('AMOUNT','SALES','NEW_CLIENTS','QUOTES','CONVERSION')),target numeric(16,2) not null check(target>0),actual numeric(16,2) not null default 0 check(actual>=0),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(period_end>=period_start));
create table if not exists public.commission_rules(id uuid primary key default gen_random_uuid(),name text not null,calculation_type text not null check(calculation_type in('PERCENTAGE','FIXED','SERVICE','SELLER','CAMPAIGN')),percentage numeric(7,4),fixed_amount numeric(16,2),currency char(3) not null default 'CLP',service_catalog_id uuid references public.service_catalog(id) on delete restrict,user_id uuid,campaign text,active boolean not null default true,valid_from date,valid_until date,created_at timestamptz not null default now(),check(percentage is null or percentage between 0 and 100));
create table if not exists public.commissions(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.sales(id) on delete restrict,user_id uuid not null,rule_id uuid references public.commission_rules(id) on delete restrict,base_amount numeric(16,2) not null check(base_amount>=0),amount numeric(16,2) not null check(amount>=0),currency char(3) not null,status text not null default 'PENDING' check(status in('PENDING','ELIGIBLE','APPROVED','PAYABLE','PAID','CANCELLED')),approved_by uuid,approved_at timestamptz,paid_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(sale_id,user_id,rule_id));
create table if not exists public.sales_handoffs(id uuid primary key default gen_random_uuid(),sale_id uuid not null unique references public.sales(id) on delete restrict,client_id uuid references public.clients(id) on delete restrict,quote_id uuid not null references public.quotes(id) on delete restrict,work_order_id uuid references public.work_orders(id) on delete restrict,status text not null default 'DRAFT' check(status in('DRAFT','READY','ACKNOWLEDGED')),scope text not null,committed_deadline date,risks text,dependencies text,commercial_owner_id uuid,development_owner_id uuid,override_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.commercial_events(id uuid primary key default gen_random_uuid(),aggregate_type text not null,aggregate_id uuid not null,event_type text not null,actor_id uuid,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());
create index if not exists commercial_events_aggregate_idx on public.commercial_events(aggregate_type,aggregate_id,occurred_at desc);
create table if not exists public.commercial_notifications(id uuid primary key default gen_random_uuid(),event_key text not null unique,user_id uuid,audience_role text,type text not null,title text not null,body text,entity_type text,entity_id uuid,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.commercial_idempotency_keys(idempotency_key text primary key,operation text not null,resource_id uuid,created_at timestamptz not null default now());

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now();return new;end $$;
do $$ declare table_name text;begin foreach table_name in array array['sales_pipelines','pipeline_stages','leads','opportunities','follow_ups','quotes','work_orders','sales_goals','commissions','sales_handoffs'] loop execute format('drop trigger if exists %I on public.%I',table_name||'_touch_updated_at',table_name);execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()',table_name||'_touch_updated_at',table_name);end loop;end $$;

create or replace function public.change_opportunity_stage(target_opportunity_id uuid,target_stage_id uuid,actor_user_id uuid,change_reason text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare current_row public.opportunities%rowtype;target_stage public.pipeline_stages%rowtype;new_status text;begin
 select * into current_row from public.opportunities where id=target_opportunity_id for update;if not found then raise exception 'Oportunidad no encontrada';end if;
 select * into target_stage from public.pipeline_stages where id=target_stage_id and active;if not found or target_stage.pipeline_id<>current_row.pipeline_id then raise exception 'Etapa inválida';end if;
 if target_stage.kind='LOST' and nullif(trim(change_reason),'') is null then raise exception 'El motivo de pérdida es obligatorio';end if;
 if target_stage.kind='WON' and (current_row.estimated_value<=0 or(current_row.client_id is null and current_row.lead_id is null)) then raise exception 'Faltan datos para ganar la oportunidad';end if;
 new_status:=case target_stage.kind when 'WON' then 'WON' when 'LOST' then 'LOST' else 'OPEN' end;
 insert into public.opportunity_stage_history(opportunity_id,from_stage_id,to_stage_id,changed_by,duration_previous_stage_seconds,reason) values(current_row.id,current_row.stage_id,target_stage.id,actor_user_id,greatest(0,extract(epoch from(now()-current_row.stage_entered_at))::bigint),change_reason);
 update public.opportunities set stage_id=target_stage.id,probability=target_stage.probability,status=new_status,lost_explanation=case when target_stage.kind='LOST' then change_reason else null end,stage_entered_at=now() where id=current_row.id;
 return current_row.id;end $$;

create or replace function public.create_quote_version(target_quote_id uuid,actor_user_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$ declare q public.quotes%rowtype;begin select * into q from public.quotes where id=target_quote_id for update;if not found then raise exception 'Cotización no encontrada';end if;insert into public.quote_versions(quote_id,version_number,snapshot,document_id,document_hash,created_by) values(q.id,q.version,to_jsonb(q),q.document_id,q.document_hash,actor_user_id) on conflict(quote_id,version_number) do nothing;update public.quotes set version=version+1,status='DRAFT',document_id=null,document_hash=null,sent_at=null,accepted_at=null where id=q.id;return q.id;end $$;

create or replace function public.create_sales_quote(quote_payload jsonb,item_payload jsonb)
returns uuid language plpgsql security definer set search_path=public as $$
declare new_quote_id uuid;begin
 insert into public.quotes(id,client_id,lead_id,opportunity_id,company_name,contact_name,contact_email,owner_id,status,currency,subtotal,discount_total,net_amount,tax_rate,tax_amount,total_amount,valid_until,payment_terms,commercial_terms,notes)
 values((quote_payload->>'id')::uuid,(quote_payload->>'client_id')::uuid,(quote_payload->>'lead_id')::uuid,(quote_payload->>'opportunity_id')::uuid,quote_payload->>'company_name',quote_payload->>'contact_name',quote_payload->>'contact_email',(quote_payload->>'owner_id')::uuid,quote_payload->>'status',quote_payload->>'currency',(quote_payload->>'subtotal')::numeric,(quote_payload->>'discount_total')::numeric,(quote_payload->>'net_amount')::numeric,(quote_payload->>'tax_rate')::numeric,(quote_payload->>'tax_amount')::numeric,(quote_payload->>'total_amount')::numeric,(quote_payload->>'valid_until')::date,quote_payload->>'payment_terms',quote_payload->>'commercial_terms',quote_payload->>'notes') returning id into new_quote_id;
 insert into public.quote_items(id,quote_id,catalog_service_id,description,quantity,unit_price,discount_percent,taxable,subtotal,position)
 select (entry.value->>'id')::uuid,new_quote_id,(entry.value->>'catalog_service_id')::uuid,entry.value->>'description',(entry.value->>'quantity')::numeric,(entry.value->>'unit_price')::numeric,(entry.value->>'discount_percent')::numeric,(entry.value->>'taxable')::boolean,(entry.value->>'subtotal')::numeric,(entry.ordinality-1)::integer from jsonb_array_elements(item_payload) with ordinality as entry(value,ordinality);
 return new_quote_id;
end $$;

create or replace function public.accept_sales_quote(target_quote_id uuid,actor_user_id uuid,idempotency_key text)
returns uuid language plpgsql security definer set search_path=public as $$
declare q public.quotes%rowtype;new_sale_id uuid;existing uuid;won_stage uuid;begin
 if nullif(trim(idempotency_key),'') is null then raise exception 'Idempotency-Key obligatorio';end if;
 select resource_id into existing from public.commercial_idempotency_keys where commercial_idempotency_keys.idempotency_key=$3 and operation='ACCEPT_QUOTE';if existing is not null then return existing;end if;
 select * into q from public.quotes where id=target_quote_id for update;if not found then raise exception 'Cotización no encontrada';end if;if q.status not in('SENT','NEGOTIATING','ACCEPTED') then raise exception 'Cotización no aceptable';end if;
 select id into new_sale_id from public.sales where quote_id=q.id;if new_sale_id is null then insert into public.sales(quote_id,opportunity_id,client_id,amount,currency,owner_id) values(q.id,q.opportunity_id,q.client_id,q.total_amount,q.currency,q.owner_id) returning id into new_sale_id;end if;
 update public.quotes set status='ACCEPTED',accepted_at=coalesce(accepted_at,now()),sale_id=new_sale_id where id=q.id;
 if q.opportunity_id is not null then select id into won_stage from public.pipeline_stages where pipeline_id=(select pipeline_id from public.opportunities where id=q.opportunity_id) and kind='WON' limit 1;if won_stage is not null then perform public.change_opportunity_stage(q.opportunity_id,won_stage,actor_user_id,'Cotización aceptada');end if;end if;
 if q.lead_id is not null then update public.leads set status='CONVERTED' where id=q.lead_id;end if;
 insert into public.commercial_events(aggregate_type,aggregate_id,event_type,actor_id,payload) values('QUOTE',q.id,'QUOTE_ACCEPTED',actor_user_id,jsonb_build_object('saleId',new_sale_id,'version',q.version)),('SALE',new_sale_id,'SALE_WON',actor_user_id,jsonb_build_object('quoteId',q.id,'clientId',q.client_id));
 insert into public.business_event_outbox(aggregate_type,aggregate_id,event_type,payload) values('SALE',new_sale_id,'SALE_WON',jsonb_build_object('quoteId',q.id,'clientId',q.client_id));
 insert into public.commercial_idempotency_keys(idempotency_key,operation,resource_id) values($3,'ACCEPT_QUOTE',new_sale_id) on conflict do nothing;return new_sale_id;end $$;

create or replace function public.convert_quote_to_work_order(target_quote_id uuid,actor_user_id uuid,idempotency_key text,override_reason text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare q public.quotes%rowtype;s public.sales%rowtype;work_id uuid;existing uuid;begin
 if nullif(trim(idempotency_key),'') is null then raise exception 'Idempotency-Key obligatorio';end if;
 select resource_id into existing from public.commercial_idempotency_keys where commercial_idempotency_keys.idempotency_key=$3 and operation='QUOTE_TO_OT';if existing is not null then return jsonb_build_object('workOrderId',existing,'created',false);end if;
 select * into q from public.quotes where id=target_quote_id for update;select * into s from public.sales where quote_id=q.id for update;if not found then raise exception 'La cotización debe estar aceptada';end if;if s.work_order_id is not null then return jsonb_build_object('workOrderId',s.work_order_id,'created',false);end if;
 insert into public.work_orders(client_id,quote_id,quote_version,scope,deadline,commercial_owner_id,commercial_notes,created_by) values(q.client_id,q.id,q.version,(select string_agg(description,E'\n') from public.quote_items where quote_id=q.id),q.valid_until,q.owner_id,q.notes,actor_user_id) returning id into work_id;
 update public.sales set work_order_id=work_id where id=s.id;update public.quotes set status='CONVERTED' where id=q.id;
 insert into public.commercial_idempotency_keys(idempotency_key,operation,resource_id) values($3,'QUOTE_TO_OT',work_id) on conflict do nothing;
 insert into public.commercial_events(aggregate_type,aggregate_id,event_type,actor_id,payload) values('WORK_ORDER',work_id,'WORK_ORDER_CREATED',actor_user_id,jsonb_build_object('quoteId',q.id,'overrideReason',override_reason));
 insert into public.business_event_outbox(aggregate_type,aggregate_id,event_type,payload) values('WORK_ORDER',work_id,'WORK_ORDER_CREATED',jsonb_build_object('quoteId',q.id,'clientId',q.client_id));return jsonb_build_object('workOrderId',work_id,'created',true);end $$;

create or replace function public.process_commercial_due_notifications(reference_time timestamptz default now()) returns integer language plpgsql security definer set search_path=public as $$ declare inserted_count integer;begin
 insert into public.commercial_notifications(event_key,user_id,type,title,body,entity_type,entity_id)
 select 'FOLLOW_UP_OVERDUE:'||f.id,f.assigned_to,'FOLLOW_UP_OVERDUE','Seguimiento vencido',f.title,'FOLLOW_UP',f.id from public.follow_ups f where f.status='PENDING' and f.scheduled_at<reference_time on conflict(event_key) do nothing;
 get diagnostics inserted_count=row_count;
 insert into public.commercial_notifications(event_key,user_id,type,title,body,entity_type,entity_id)
 select 'QUOTE_EXPIRING:'||q.id||':'||d.days,q.owner_id,'QUOTE_EXPIRING','Cotización próxima a vencer',q.quote_number,'QUOTE',q.id from public.quotes q cross join(values(7),(3),(1))d(days) where q.status in('SENT','NEGOTIATING') and q.valid_until=current_date+d.days on conflict(event_key) do nothing;
 return inserted_count;end $$;

create or replace function public.project_commercial_event_notification() returns trigger language plpgsql security definer set search_path=public as $$
declare owner_user uuid;recipient_role text;begin
 if new.event_type='LEAD_ASSIGNED' then
  insert into public.commercial_notifications(event_key,user_id,type,title,body,entity_type,entity_id) values('LEAD_ASSIGNED:'||new.aggregate_id,nullif(new.payload->>'assignedTo','')::uuid,'LEAD_ASSIGNED','Nuevo lead asignado','Revisa el Lead Inbox','LEAD',new.aggregate_id) on conflict(event_key) do nothing;
 elsif new.event_type='QUOTE_APPROVAL_REQUIRED' then
  insert into public.commercial_notifications(event_key,audience_role,type,title,body,entity_type,entity_id) values('QUOTE_APPROVAL_REQUIRED:'||new.aggregate_id,'JEFE_VENTAS','QUOTE_APPROVAL_REQUIRED','Cotización requiere aprobación','El descuento excede la política del rol creador','QUOTE',new.aggregate_id) on conflict(event_key) do nothing;
 elsif new.event_type in('QUOTE_APPROVED','QUOTE_REJECTED') then
  select owner_id into owner_user from public.quotes where id=new.aggregate_id;
  insert into public.commercial_notifications(event_key,user_id,type,title,body,entity_type,entity_id) values(new.event_type||':'||new.aggregate_id,owner_user,new.event_type,case when new.event_type='QUOTE_APPROVED' then 'Cotización aprobada' else 'Cotización rechazada' end,null,'QUOTE',new.aggregate_id) on conflict(event_key) do nothing;
 elsif new.event_type in('QUOTE_ACCEPTED','SALE_WON') then
  foreach recipient_role in array array['GERENTE_GENERAL','JEFE_DESARROLLO'] loop
   insert into public.commercial_notifications(event_key,audience_role,type,title,body,entity_type,entity_id) values(new.event_type||':'||new.aggregate_id||':'||recipient_role,recipient_role,new.event_type,case when new.event_type='QUOTE_ACCEPTED' then 'Cotización aceptada' else 'Venta ganada' end,null,new.aggregate_type,new.aggregate_id) on conflict(event_key) do nothing;
  end loop;
 elsif new.event_type='HANDOFF_READY' then
  foreach recipient_role in array array['GERENTE_GENERAL','JEFE_DESARROLLO'] loop
   insert into public.commercial_notifications(event_key,audience_role,type,title,body,entity_type,entity_id) values('HANDOFF_READY:'||new.aggregate_id||':'||recipient_role,recipient_role,'HANDOFF_READY','Handoff comercial listo',null,'HANDOFF',new.aggregate_id) on conflict(event_key) do nothing;
  end loop;
 end if;
 return new;
end $$;
drop trigger if exists commercial_event_notification_projection on public.commercial_events;
create trigger commercial_event_notification_projection after insert on public.commercial_events for each row execute function public.project_commercial_event_notification();

revoke all on function public.change_opportunity_stage(uuid,uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.create_quote_version(uuid,uuid) from public,anon,authenticated;
revoke all on function public.create_sales_quote(jsonb,jsonb) from public,anon,authenticated;
revoke all on function public.accept_sales_quote(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.convert_quote_to_work_order(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.change_opportunity_stage(uuid,uuid,uuid,text) to service_role;
grant execute on function public.create_quote_version(uuid,uuid) to service_role;
grant execute on function public.create_sales_quote(jsonb,jsonb) to service_role;
grant execute on function public.accept_sales_quote(uuid,uuid,text) to service_role;
grant execute on function public.convert_quote_to_work_order(uuid,uuid,text,text) to service_role;

insert into public.app_permissions(code,description) values
('sales.dashboard.view','Ver Sales Command Center'),('lead.view','Ver leads'),('lead.create','Crear leads'),('lead.edit','Editar leads'),('lead.assign','Asignar leads'),('lead.archive','Archivar leads'),('opportunity.view','Ver oportunidades'),('opportunity.create','Crear oportunidades'),('opportunity.edit','Editar oportunidades'),('opportunity.assign','Asignar oportunidades'),('opportunity.close','Cerrar oportunidades'),('followup.view','Ver seguimientos'),('followup.create','Crear seguimientos'),('followup.complete','Completar seguimientos'),('quote.view','Ver cotizaciones'),('quote.create','Crear cotizaciones'),('quote.edit','Versionar cotizaciones'),('quote.approve','Aprobar cotizaciones'),('quote.send','Enviar cotizaciones'),('quote.convert','Convertir cotizaciones'),('quote.discount.override','Autorizar descuentos'),('sale.view','Ver ventas'),('sale.manage','Gestionar ventas'),('goal.view','Ver metas'),('goal.manage','Gestionar metas'),('commission.view_own','Ver comisiones propias'),('commission.view_team','Ver comisiones del equipo'),('commission.manage','Gestionar comisiones'),('handoff.create','Crear handoff'),('handoff.manage','Gestionar handoff') on conflict(code) do nothing;
insert into public.role_permissions(role,permission_code) select role,code from(values('GERENTE_GENERAL'),('JEFE_VENTAS'),('COMERCIAL'))r(role) cross join public.app_permissions where code like any(array['sales.%','lead.%','opportunity.%','followup.%','quote.%','sale.%','goal.%','commission.%','handoff.%']) on conflict do nothing;
insert into public.role_permissions(role,permission_code) select 'EJECUTIVA_VENTAS',code from public.app_permissions where code in('sales.dashboard.view','lead.view','lead.create','lead.edit','opportunity.view','opportunity.create','opportunity.edit','followup.view','followup.create','followup.complete','quote.view','quote.create','quote.edit','quote.send','sale.view','goal.view','commission.view_own','handoff.create') on conflict do nothing;
insert into public.role_permissions(role,permission_code) values('JEFE_DESARROLLO','handoff.manage'),('JEFE_DESARROLLO','quote.convert'),('FINANZAS','sale.view'),('FINANZAS','commission.manage'),('FINANZAS','commission.view_team') on conflict do nothing;

create or replace function private.can_manage_sales() returns boolean language sql stable security definer set search_path=public as $$select private.zyteron_role() in('GERENTE_GENERAL','JEFE_VENTAS','COMERCIAL')$$;
create or replace function private.can_access_sales_owner(owner_id uuid) returns boolean language sql stable security definer set search_path=public as $$select private.can_manage_sales() or owner_id=auth.uid()$$;

do $$ declare table_name text;begin foreach table_name in array array['lead_sources','sales_pipelines','pipeline_stages','lost_reason_catalog','leads','lead_assignments','opportunities','opportunity_stage_history','follow_ups','discount_policies','document_templates','quotes','quote_items','quote_versions','quote_approvals','quote_recipients','quote_events','commercial_documents','quote_email_deliveries','quote_proposal_links','quote_acceptance_evidence','work_orders','sales','sales_goals','commission_rules','commissions','sales_handoffs','commercial_events','commercial_notifications','commercial_idempotency_keys'] loop execute format('alter table public.%I enable row level security',table_name);end loop;end $$;

do $$ begin
 drop policy if exists commercial_config_read on public.lead_sources;create policy commercial_config_read on public.lead_sources for select to authenticated using(active);
 drop policy if exists commercial_pipeline_read on public.sales_pipelines;create policy commercial_pipeline_read on public.sales_pipelines for select to authenticated using(active);
 drop policy if exists commercial_stage_read on public.pipeline_stages;create policy commercial_stage_read on public.pipeline_stages for select to authenticated using(active);
 drop policy if exists commercial_lost_reason_read on public.lost_reason_catalog;create policy commercial_lost_reason_read on public.lost_reason_catalog for select to authenticated using(active);
 drop policy if exists commercial_leads_scope on public.leads;create policy commercial_leads_scope on public.leads for all to authenticated using(private.can_access_sales_owner(assigned_to) or created_by=auth.uid()) with check(private.can_access_sales_owner(assigned_to) or created_by=auth.uid());
 drop policy if exists commercial_opportunities_scope on public.opportunities;create policy commercial_opportunities_scope on public.opportunities for all to authenticated using(private.can_access_sales_owner(owner_id)) with check(private.can_access_sales_owner(owner_id));
 drop policy if exists commercial_followups_scope on public.follow_ups;create policy commercial_followups_scope on public.follow_ups for all to authenticated using(private.can_access_sales_owner(assigned_to) or created_by=auth.uid()) with check(private.can_access_sales_owner(assigned_to) or created_by=auth.uid());
 drop policy if exists commercial_quotes_scope on public.quotes;create policy commercial_quotes_scope on public.quotes for all to authenticated using(private.can_access_sales_owner(owner_id)) with check(private.can_access_sales_owner(owner_id));
 drop policy if exists commercial_sales_scope on public.sales;create policy commercial_sales_scope on public.sales for select to authenticated using(private.can_access_sales_owner(owner_id) or private.zyteron_role()='FINANZAS');
 drop policy if exists commercial_goals_scope on public.sales_goals;create policy commercial_goals_scope on public.sales_goals for select to authenticated using(private.can_manage_sales() or user_id=auth.uid());
 drop policy if exists commercial_commissions_scope on public.commissions;create policy commercial_commissions_scope on public.commissions for select to authenticated using(private.can_manage_sales() or private.zyteron_role()='FINANZAS' or user_id=auth.uid());
 drop policy if exists commercial_handoffs_scope on public.sales_handoffs;create policy commercial_handoffs_scope on public.sales_handoffs for select to authenticated using(private.can_manage_sales() or private.zyteron_role() in('JEFE_DESARROLLO','DESARROLLO','OPERACIONES') or commercial_owner_id=auth.uid() or development_owner_id=auth.uid());
 drop policy if exists commercial_work_orders_scope on public.work_orders;create policy commercial_work_orders_scope on public.work_orders for select to authenticated using(private.can_manage_sales() or private.zyteron_role() in('JEFE_DESARROLLO','DESARROLLO','OPERACIONES') or commercial_owner_id=auth.uid() or development_owner_id=auth.uid());
 drop policy if exists commercial_notifications_own on public.commercial_notifications;create policy commercial_notifications_own on public.commercial_notifications for select to authenticated using(user_id=auth.uid() or audience_role=private.zyteron_role() or private.can_manage_sales());
end $$;

do $$ declare table_name text;begin foreach table_name in array array['leads','opportunities','follow_ups','quotes','sales','sales_handoffs'] loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=table_name)then execute format('alter publication supabase_realtime add table public.%I',table_name);end if;end loop;end $$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('commercial-documents','commercial-documents',false,20971520,array['application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

commit;
