import { Injectable } from "@nestjs/common";
import type { SupportBusinessCalendar, SupportSlaClock, SupportSlaPolicy, SupportSlaSnapshot, SupportSlaTarget, SupportTicket } from "@zyteron/contracts";

const dayIndex:Record<string,number>={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
const parts=(date:Date,timezone:string)=>Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:timezone,weekday:"short",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date).filter(item=>item.type!=="literal").map(item=>[item.type,item.value]));
const activeMinute=(date:Date,calendar:SupportBusinessCalendar)=>{if(calendar.mode==="TWENTY_FOUR_SEVEN")return true;const value=parts(date,calendar.timezone),dateKey=`${value.year}-${value.month}-${value.day}`,minute=Number(value.hour)*60+Number(value.minute),[startHour,startMinute]=calendar.workingHours.start.split(":").map(Number),[endHour,endMinute]=calendar.workingHours.end.split(":").map(Number);return calendar.workingDays.includes(dayIndex[String(value.weekday)]??-1)&&!calendar.holidays.includes(dateKey)&&minute>=(startHour!*60+startMinute!)&&minute<(endHour!*60+endMinute!);};

@Injectable()
export class SupportSlaEngine{
  add(start:string,minutes:number,calendar:SupportBusinessCalendar){const cursor=new Date(start);if(calendar.mode==="TWENTY_FOUR_SEVEN"){cursor.setUTCMinutes(cursor.getUTCMinutes()+minutes);return cursor.toISOString();}let remaining=Math.max(0,Math.ceil(minutes)),guard=0;while(remaining>0&&guard<600_000){cursor.setUTCMinutes(cursor.getUTCMinutes()+1);if(activeMinute(cursor,calendar))remaining--;guard++;}return cursor.toISOString();}
  remaining(from:string,due:string|null,calendar:SupportBusinessCalendar){if(!due)return null;const start=new Date(from),end=new Date(due),direction=start<=end?1:-1,cursor=new Date(direction===1?start:end),limit=new Date(direction===1?end:start);let total=0,guard=0;while(cursor<limit&&guard<600_000){cursor.setUTCMinutes(cursor.getUTCMinutes()+1);if(activeMinute(cursor,calendar))total++;guard++;}return total*direction;}
  snapshot(ticket:SupportTicket,policy:SupportSlaPolicy|null,calendar:SupportBusinessCalendar|null,target:SupportSlaTarget|null,at=new Date().toISOString()):SupportSlaSnapshot{const build=(kind:"FIRST_RESPONSE"|"RESOLUTION",dueAt:string|null,completedAt:string|null,total:number|null):SupportSlaClock=>{const remaining=calendar?this.remaining(at,dueAt,calendar):dueAt?Math.ceil((Date.parse(dueAt)-Date.parse(at))/60000):null;const elapsed=total===null||remaining===null?null:Math.max(0,total-remaining);return{target:kind,dueAt,completedAt,paused:policy?.pauseStatuses.includes(ticket.status)??false,remainingMinutes:completedAt?0:remaining,breached:!completedAt&&remaining!==null&&remaining<0,consumptionPercent:total&&elapsed!==null?Math.max(0,Math.round(elapsed/total*100)):null};};return{ticketId:ticket.id,policy,firstResponse:build("FIRST_RESPONSE",ticket.firstResponseDueAt,ticket.firstRespondedAt,target?.firstResponseMinutes??null),resolution:build("RESOLUTION",ticket.resolutionDueAt,ticket.resolvedAt,target?.resolutionMinutes??null)};}
}
