import { Injectable, NotFoundException } from "@nestjs/common";
import { createHash, randomUUID } from "node:crypto";
import type { SupportTicket } from "@zyteron/contracts";
import { createServerSupabase, pageBounds } from "../domain/server-supabase.js";

type Row=Record<string,any>;
type Filters=Record<string,string|number|boolean|null|undefined>;
export interface SupportPage { page:number;pageSize:number;search?:string;status?:string;priority?:string;severity?:string;queueId?:string;assignedTo?:string;clientId?:string;projectId?:string;serviceId?:string;channel?:string;requesterType?:string;clientVisibility?:string;slaBreach?:boolean;createdFrom?:string;createdTo?:string; }
export interface SupportIdempotencyClaim { idempotencyKey:string;operation:string;requestHash:string;resourceId:string;completedAt:string|null;createdAt:string; }
const now=()=>new Date().toISOString();
const snake=(key:string)=>key.replace(/[A-Z]/g,letter=>`_${letter.toLowerCase()}`);
const camel=(key:string)=>key.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase());
const virtual=new Set(["clientName","contactName","projectName","queueName","categoryName"]);
const toRow=(value:Row)=>Object.fromEntries(Object.entries(value).filter(([key,item])=>!virtual.has(key)&&item!==undefined).map(([key,item])=>[snake(key),item]));
const relation=(value:unknown,...keys:string[])=>{const item=Array.isArray(value)?value[0]:value;if(!item||typeof item!=="object")return null;for(const key of keys){const found=(item as Row)[key];if(found)return String(found);}return null;};
const fromRow=<T>(value:Row):T=>{const result:Row={};for(const[key,item]of Object.entries(value)){if(key==="clients")result.clientName=relation(item,"trade_name","legal_name");else if(key==="client_contacts")result.contactName=relation(item,"name");else if(key==="projects")result.projectName=relation(item,"name");else if(key==="support_queues")result.queueName=relation(item,"name");else if(key==="support_categories")result.categoryName=relation(item,"name");else result[camel(key)]=item;}return result as T;};
const selectFor=(table:string)=>table==="support_tickets"?"*,clients(legal_name,trade_name),client_contacts(name),projects(name),support_queues(name),support_categories(name)":"*";
export const supportClientContextSelects={
  client:"id,legal_name,trade_name,health_status,account_executive_id,development_lead_id",
  contacts:"id,name,email,phone,is_primary,technical_contact",
  services:"id,service_name,status",
  tickets:"id,ticket_number,subject,status,created_at",
  projects:"id,name,status,health",
} as const;

@Injectable()
export class SupportRepository{
  private readonly supabase=createServerSupabase();
  private readonly memory=new Map<string,Map<string,Row>>();
  private readonly idempotency=new Map<string,SupportIdempotencyClaim>();
  private ticketSequence=0;
  private store(table:string){let value=this.memory.get(table);if(!value){value=new Map();this.memory.set(table,value);}return value;}
  configured(){return Boolean(this.supabase);}
  async list<T>(table:string,filters:Filters={},order="created_at",ascending=false):Promise<T[]>{if(!this.supabase)return[...this.store(table).values()].filter(row=>Object.entries(filters).every(([key,value])=>value===undefined||row[key]===value)).sort((a,b)=>String(ascending?a[camel(order)]??"":b[camel(order)]??"").localeCompare(String(ascending?b[camel(order)]??"":a[camel(order)]??""))) as T[];let query=(this.supabase.from(table) as any).select(selectFor(table));for(const[key,value]of Object.entries(filters))if(value!==undefined)query=value===null?query.is(snake(key),null):query.eq(snake(key),value);const{data,error}=await query.order(order,{ascending});if(error)throw error;return(data??[]).map((row:Row)=>fromRow<T>(row));}
  async page<T>(table:string,q:SupportPage){if(!this.supabase){let items=[...this.store(table).values()];const search=q.search?.toLocaleLowerCase("es-CL");items=items.filter(item=>(!q.status||item.status===q.status)&&(!q.priority||item.priority===q.priority)&&(!q.severity||item.severity===q.severity)&&(!q.queueId||item.queueId===q.queueId)&&(!q.assignedTo||item.assignedTo===q.assignedTo)&&(!q.clientId||item.clientId===q.clientId)&&(!q.projectId||item.projectId===q.projectId)&&(!q.serviceId||item.serviceId===q.serviceId)&&(!q.channel||item.channel===q.channel)&&(!q.requesterType||item.requesterType===q.requesterType)&&(!q.clientVisibility||item.clientVisibility===q.clientVisibility)&&(!q.slaBreach||Boolean((item.firstResponseDueAt&&!item.firstRespondedAt&&item.firstResponseDueAt<now())||(item.resolutionDueAt&&!item.resolvedAt&&item.resolutionDueAt<now())))&&(!search||Object.values(item).some(value=>typeof value==="string"&&value.toLocaleLowerCase("es-CL").includes(search))));items.sort((a,b)=>String(b.updatedAt??b.createdAt??"").localeCompare(String(a.updatedAt??a.createdAt??"")));const start=(q.page-1)*q.pageSize;return{items:items.slice(start,start+q.pageSize) as T[],page:q.page,pageSize:q.pageSize,total:items.length,totalPages:Math.ceil(items.length/q.pageSize)};}const{from,to}=pageBounds(q.page,q.pageSize);let query=(this.supabase.from(table) as any).select(selectFor(table),{count:"exact"});if(q.search){const term=q.search.replace(/[,()]/g," ");query=query.or(`ticket_number.ilike.%${term}%,subject.ilike.%${term}%,description.ilike.%${term}%`);}for(const[key,value]of Object.entries({status:q.status,priority:q.priority,severity:q.severity,queueId:q.queueId,assignedTo:q.assignedTo,clientId:q.clientId,projectId:q.projectId,serviceId:q.serviceId,channel:q.channel,requesterType:q.requesterType,clientVisibility:q.clientVisibility}))if(value)query=query.eq(snake(key),value);if(q.slaBreach)query=query.or(`and(first_response_due_at.lt.${now()},first_responded_at.is.null),and(resolution_due_at.lt.${now()},resolved_at.is.null)`);if(q.createdFrom)query=query.gte("created_at",q.createdFrom);if(q.createdTo)query=query.lte("created_at",q.createdTo);const{data,error,count}=await query.order("updated_at",{ascending:false}).range(from,to);if(error)throw error;return{items:(data??[]).map((row:Row)=>fromRow<T>(row)),page:q.page,pageSize:q.pageSize,total:count??0,totalPages:Math.ceil((count??0)/q.pageSize)};}
  async get<T>(table:string,id:string):Promise<T|undefined>{if(!this.supabase)return this.store(table).get(id) as T|undefined;const{data,error}=await(this.supabase.from(table) as any).select(selectFor(table)).eq("id",id).maybeSingle();if(error)throw error;return data?fromRow<T>(data as Row):undefined;}
  async create<T extends Row>(table:string,input:T):Promise<T>{const stamp=now();const item={id:randomUUID(),...input,createdAt:input.createdAt??stamp,updatedAt:input.updatedAt??stamp} as T;if(!this.supabase){this.store(table).set(String(item.id),item);return item;}const{data,error}=await(this.supabase.from(table) as any).insert(toRow(item)).select(selectFor(table)).single();if(error)throw error;return fromRow<T>(data as Row);}
  async update<T extends Row>(table:string,id:string,patch:Partial<T>):Promise<T>{if(!this.supabase){const current=this.store(table).get(id);if(!current)throw new NotFoundException("Registro de soporte no encontrado.");const clean=Object.fromEntries(Object.entries(patch).filter(([,value])=>value!==undefined));const item={...current,...clean,updatedAt:now()} as unknown as T;this.store(table).set(id,item);return item;}const{data,error}=await(this.supabase.from(table) as any).update(toRow({...patch,updatedAt:now()})).eq("id",id).select(selectFor(table)).single();if(error)throw error;return fromRow<T>(data as Row);}
  async nextTicketNumber(){if(!this.supabase)return`SUP-${new Date().getUTCFullYear()}-${String(++this.ticketSequence).padStart(6,"0")}`;const{data,error}=await this.supabase.rpc("next_support_ticket_number");if(error)throw error;return String(data);}
  async claimIdempotency(idempotencyKey:string,operation:string,requestHash:string,resourceId:string){const token=`${operation}:${idempotencyKey}`,claim:SupportIdempotencyClaim={idempotencyKey,operation,requestHash,resourceId,completedAt:null,createdAt:now()};if(!this.supabase){const existing=this.idempotency.get(token);if(existing)return{claimed:false,claim:existing};this.idempotency.set(token,claim);return{claimed:true,claim};}const{error}=await this.supabase.from("support_idempotency_keys").insert(toRow(claim));if(!error)return{claimed:true,claim};if(error.code!=="23505")throw error;const existing=await this.getIdempotency(idempotencyKey,operation);if(!existing)throw error;return{claimed:false,claim:existing};}
  async getIdempotency(idempotencyKey:string,operation:string):Promise<SupportIdempotencyClaim|null>{const token=`${operation}:${idempotencyKey}`;if(!this.supabase)return this.idempotency.get(token)??null;const{data,error}=await this.supabase.from("support_idempotency_keys").select("idempotency_key,operation,request_hash,resource_id,completed_at,created_at").eq("idempotency_key",idempotencyKey).eq("operation",operation).maybeSingle();if(error)throw error;return data?fromRow<SupportIdempotencyClaim>(data as Row):null;}
  async completeIdempotency(idempotencyKey:string,operation:string,resourceId:string){const token=`${operation}:${idempotencyKey}`,completedAt=now();if(!this.supabase){const current=this.idempotency.get(token);if(current&&current.resourceId===resourceId)this.idempotency.set(token,{...current,completedAt});return;}const{error}=await this.supabase.from("support_idempotency_keys").update({completed_at:completedAt}).eq("idempotency_key",idempotencyKey).eq("operation",operation).eq("resource_id",resourceId);if(error)throw error;}
  async releaseIdempotency(idempotencyKey:string,operation:string,resourceId:string){const token=`${operation}:${idempotencyKey}`;if(!this.supabase){const current=this.idempotency.get(token);if(current?.resourceId===resourceId&&!current.completedAt)this.idempotency.delete(token);return;}const{error}=await this.supabase.from("support_idempotency_keys").delete().eq("idempotency_key",idempotencyKey).eq("operation",operation).eq("resource_id",resourceId).is("completed_at",null);if(error)throw error;}
  async publish(ticketId:string|null,eventType:string,actorId:string|null,payload:Row={}){const event={id:randomUUID(),ticketId,eventType,actorId,payload,occurredAt:now()};if(!this.supabase){this.store("support_events").set(event.id,event);return event;}const{error}=await this.supabase.from("support_events").insert(toRow(event));if(error)throw error;return event;}
  async contactBelongs(clientId:string,contactId:string){if(!this.supabase){const item=this.store("client_contacts").get(contactId);return !item||item.clientId===clientId;}const{data,error}=await this.supabase.from("client_contacts").select("id").eq("id",contactId).eq("client_id",clientId).is("archived_at",null).maybeSingle();if(error)throw error;return Boolean(data);}
  async contactByEmail(email:string){if(!this.supabase){return[...this.store("client_contacts").values()].find(item=>String(item.email).toLowerCase()===email.toLowerCase())??null;}const{data,error}=await this.supabase.from("client_contacts").select("id,client_id,name,email").ilike("email",email).is("archived_at",null).limit(1).maybeSingle();if(error)throw error;return data?{id:String(data.id),clientId:String(data.client_id),name:String(data.name),email:String(data.email)}:null;}
  async portalIdentity(userId:string){if(!this.supabase)return null;const{data,error}=await this.supabase.from("client_portal_users").select("client_id,contact_id").eq("auth_user_id",userId).eq("status","ACTIVE").maybeSingle();if(error)throw error;return data?{clientId:String(data.client_id),contactId:String(data.contact_id)}:null;}
  async clientContext(clientId:string){if(!this.supabase)return null;const[client,contacts,services,tickets,projects]=await Promise.all([this.supabase.from("clients").select(supportClientContextSelects.client).eq("id",clientId).maybeSingle(),this.supabase.from("client_contacts").select(supportClientContextSelects.contacts).eq("client_id",clientId).is("archived_at",null),this.supabase.from("client_services").select(supportClientContextSelects.services).eq("client_id",clientId).limit(20),this.supabase.from("support_tickets").select(supportClientContextSelects.tickets).eq("client_id",clientId).order("created_at",{ascending:false}).limit(5),this.supabase.from("projects").select(supportClientContextSelects.projects).eq("client_id",clientId).limit(20)]);const error=[client,contacts,services,tickets,projects].find(result=>result.error)?.error;if(error)throw error;return{client:client.data,contacts:contacts.data??[],services:services.data??[],recentTickets:tickets.data??[],projects:projects.data??[]};}
  async saveAttachment(ticketId:string,filename:string,mimeType:string,bytes:Buffer){const sha256=createHash("sha256").update(bytes).digest("hex"),path=`${ticketId}/${randomUUID()}-${filename.replace(/[^a-zA-Z0-9._-]/g,"-")}`;if(this.supabase){const{error}=await this.supabase.storage.from("support-attachments").upload(path,bytes,{contentType:mimeType,upsert:false});if(error)throw error;}return{path,sha256,sizeBytes:bytes.byteLength};}
  async signedAttachment(path:string){if(!this.supabase)return null;const{data,error}=await this.supabase.storage.from("support-attachments").createSignedUrl(path,300);if(error)throw error;return data.signedUrl;}
  async emailThread(provider:string,messageId:string){const current=(await this.list<any>("support_email_threads",{providerMessageId:messageId}))[0];return current;}
  async ticketByNumber(number:string){const all=await this.list<SupportTicket>("support_tickets",{ticketNumber:number});return all[0];}
}
