import type { ClientContract, ClientContactDirectoryItem, ClientRenewal, ClientService, ContactDirectorySummary, ContactMutationResult, PagedResponse, Role, ServiceCatalogItem, UserDirectoryItem } from "@zyteron/contracts";
import { apiHeaders } from "./api-auth";

const apiUrl=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api";
async function request<T>(path:string,role:Role,init?:RequestInit):Promise<T>{const response=await fetch(`${apiUrl}${path}`,{...init,headers:await apiHeaders(role,init?.headers)});if(!response.ok){const payload=await response.json().catch(()=>({}))as{message?:string|string[];errors?:string[]};throw new Error(payload.errors?.join(" ")||(Array.isArray(payload.message)?payload.message.join(" "):payload.message)||"No fue posible completar la operación.");}return response.json()as Promise<T>;}
const body=(value:unknown):RequestInit=>({method:"POST",body:JSON.stringify(value)});
export const usersDirectoryApi={list:(role:Role)=>request<UserDirectoryItem[]>("/users/directory",role)};
export const contactsDirectoryApi={list:(role:Role,params:URLSearchParams)=>request<PagedResponse<ClientContactDirectoryItem,ContactDirectorySummary>>(`/contacts?${params}`,role),create:(role:Role,input:Record<string,unknown>)=>request<ContactMutationResult>("/contacts",role,body(input)),update:(role:Role,id:string,input:Record<string,unknown>)=>request<ClientContactDirectoryItem>(`/contacts/${id}`,role,{method:"PATCH",body:JSON.stringify(input)}),archive:(role:Role,id:string)=>request<ClientContactDirectoryItem>(`/contacts/${id}/archive`,role,body({})),setPrimary:(role:Role,id:string)=>request<ClientContactDirectoryItem>(`/contacts/${id}/set-primary`,role,body({}))};
export interface ContractSummary{active:number;pendingSignature:number;expiring:number;expired:number;autoRenew:number;withoutDocument:number;monthlyValue:number;annualValue:number}
export const contractsApi={types:(role:Role)=>request<Array<{code:string;name:string}>>("/contracts/types/catalog",role),list:(role:Role,params:URLSearchParams)=>request<PagedResponse<ClientContract,ContractSummary>>(`/contracts?${params}`,role),get:(role:Role,id:string)=>request<ClientContract&{versions:Array<Record<string,unknown>>;signatureConfigured:boolean}>(`/contracts/${id}`,role),create:(role:Role,input:Record<string,unknown>)=>request<ClientContract>("/contracts",role,body(input)),update:(role:Role,id:string,input:Record<string,unknown>)=>request<ClientContract>(`/contracts/${id}`,role,{method:"PATCH",body:JSON.stringify(input)}),transition:(role:Role,id:string,status:string)=>request<ClientContract>(`/contracts/${id}/transition`,role,body({status})),archive:(role:Role,id:string)=>request<ClientContract>(`/contracts/${id}/archive`,role,body({})),uploadUrl:(role:Role,id:string,file:{name:string;type:string})=>request<{path:string;token:string}>(`/contracts/${id}/documents/upload-url`,role,body(file)),completeUpload:(role:Role,id:string,input:Record<string,unknown>)=>request<Record<string,unknown>>(`/contracts/${id}/documents/complete`,role,body(input)),documentUrl:(role:Role,id:string,versionId:string)=>request<{url:string;expiresIn:number}>(`/contracts/${id}/documents/${versionId}/url`,role)};
export interface ServiceSummary{active:number;pending:number;suspended:number;renewing:number;withoutResponsible:number;withSla:number;estimatedMonthlyRecurring:number}
export type ServiceOperationsItem=ClientService&{clientName?:string;category?:string;requirements?:Record<string,boolean>};
export const serviceOperationsApi={catalog:(role:Role)=>request<ServiceCatalogItem[]>("/services/catalog",role),list:(role:Role,params:URLSearchParams)=>request<PagedResponse<ServiceOperationsItem,ServiceSummary>>(`/client-services?${params}`,role),get:(role:Role,id:string)=>request<ServiceOperationsItem>(`/client-services/${id}`,role),create:(role:Role,input:Record<string,unknown>)=>request<ServiceOperationsItem>("/client-services",role,body(input)),update:(role:Role,id:string,input:Record<string,unknown>)=>request<ServiceOperationsItem>(`/client-services/${id}`,role,{method:"PATCH",body:JSON.stringify(input)}),activate:(role:Role,id:string)=>request<ServiceOperationsItem>(`/client-services/${id}/activate`,role,body({})),suspend:(role:Role,id:string)=>request<ServiceOperationsItem>(`/client-services/${id}/suspend`,role,body({}))};
export interface RenewalSummary{upcoming:number;contactRequired:number;negotiating:number;renewed:number;expired:number;next30Value:number;next90Value:number}
export const renewalsApi={list:(role:Role,params:URLSearchParams)=>request<PagedResponse<ClientRenewal,RenewalSummary>>(`/renewals?${params}`,role),create:(role:Role,input:Record<string,unknown>)=>request<ClientRenewal>("/renewals",role,body(input)),update:(role:Role,id:string,input:Record<string,unknown>)=>request<ClientRenewal>(`/renewals/${id}`,role,{method:"PATCH",body:JSON.stringify(input)}),contact:(role:Role,id:string)=>request<ClientRenewal>(`/renewals/${id}/contact`,role,body({})),opportunity:(role:Role,id:string)=>request<ClientRenewal>(`/renewals/${id}/create-opportunity`,role,body({})),renew:(role:Role,id:string,input:{nextRenewalDate:string;notes?:string})=>request<ClientRenewal>(`/renewals/${id}/renew`,role,body(input)),decline:(role:Role,id:string,notes?:string)=>request<ClientRenewal>(`/renewals/${id}/decline`,role,body({notes}))};
