import type { DevelopmentAssignment, DevelopmentAttentionItem, DevelopmentBug, DevelopmentEvent, DevelopmentProjectSnapshot, DevelopmentRelease, DevelopmentSummary, DevelopmentTeamMember, DeveloperSkill, OperationsProject, ProjectDeployment, ProjectEnvironment, ProjectRepository, ProjectTechnology, PullRequest, QaRun, QaTestCase, Role, TechnicalDebtItem } from "@zyteron/contracts";
import { apiHeaders } from "./api-auth";

const base=()=>process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api";
async function request<T>(role:Role,path:string,init:RequestInit={}){const response=await fetch(`${base()}${path}`,{...init,headers:await apiHeaders(role,init.headers),cache:"no-store"});if(!response.ok){let message=`Error ${response.status}`;try{const data=await response.json() as{message?:string|string[]};message=Array.isArray(data.message)?data.message.join(" "):data.message||message;}catch{/* non-json */}throw new Error(message);}return response.json() as Promise<T>;}
const body=(method:string,value:unknown):RequestInit=>({method,body:JSON.stringify(value)});
type Page<T>={items:T[];page:number;pageSize:number;total:number;totalPages:number};

export const developmentApi={
  summary:(role:Role)=>request<DevelopmentSummary>(role,"/development/summary"),attention:(role:Role)=>request<DevelopmentAttentionItem[]>(role,"/development/attention"),assignments:(role:Role)=>request<DevelopmentAssignment[]>(role,"/development/assignments"),team:(role:Role)=>request<DevelopmentTeamMember[]>(role,"/development/team"),workload:(role:Role)=>request<DevelopmentTeamMember[]>(role,"/development/workload"),myProjects:(role:Role)=>request<Page<OperationsProject>>(role,"/development/my-projects"),
  repositories:(role:Role)=>request<ProjectRepository[]>(role,"/development/repositories"),pullRequests:(role:Role)=>request<PullRequest[]>(role,"/development/pull-requests"),environments:(role:Role)=>request<ProjectEnvironment[]>(role,"/development/environments"),skills:(role:Role)=>request<DeveloperSkill[]>(role,"/development/skills"),technologies:(role:Role)=>request<ProjectTechnology[]>(role,"/development/technologies"),qa:(role:Role)=>request<QaRun[]>(role,"/qa/runs"),testCases:(role:Role)=>request<QaTestCase[]>(role,"/qa/test-cases"),bugs:(role:Role)=>request<DevelopmentBug[]>(role,"/bugs"),releases:(role:Role)=>request<DevelopmentRelease[]>(role,"/releases"),debt:(role:Role)=>request<TechnicalDebtItem[]>(role,"/technical-debt"),activity:(role:Role)=>request<DevelopmentEvent[]>(role,"/development/activity"),integrations:(role:Role)=>request<{provider:string;status:string;message:string}[]>(role,"/development/integrations"),deployments:(role:Role)=>request<Page<ProjectDeployment>>(role,"/deployments?pageSize=100"),projects:(role:Role)=>request<Page<OperationsProject>>(role,"/projects?pageSize=100"),snapshot:(role:Role,id:string)=>request<DevelopmentProjectSnapshot>(role,`/projects/${id}/development`),
  assign:(role:Role,id:string,value:unknown)=>request(role,`/projects/${id}/development/assign`,body("POST",value)),addSkill:(role:Role,value:unknown)=>request(role,"/development/skills",body("POST",value)),connectRepo:(role:Role,id:string,value:unknown)=>request(role,`/projects/${id}/repositories`,body("POST",value)),createEnvironment:(role:Role,id:string,value:unknown)=>request(role,`/projects/${id}/environments`,body("POST",value)),addTechnology:(role:Role,id:string,value:unknown)=>request(role,`/projects/${id}/technologies`,body("POST",value)),
  createQa:(role:Role,value:unknown)=>request<QaRun>(role,"/qa/runs",body("POST",value)),startQa:(role:Role,id:string)=>request<QaRun>(role,`/qa/runs/${id}/start`,body("POST",{})),completeQa:(role:Role,id:string,value:unknown)=>request<QaRun>(role,`/qa/runs/${id}/complete`,body("POST",value)),createTestCase:(role:Role,value:unknown)=>request(role,"/qa/test-cases",body("POST",value)),
  createBug:(role:Role,value:unknown)=>request<DevelopmentBug>(role,"/bugs",body("POST",value)),bugStatus:(role:Role,id:string,status:string,reason?:string)=>request<DevelopmentBug>(role,`/bugs/${id}/change-status`,body("POST",{status,reason})),
  createRelease:(role:Role,value:unknown)=>request<DevelopmentRelease>(role,"/releases",body("POST",value)),approveRelease:(role:Role,id:string)=>request(role,`/releases/${id}/approve`,body("POST",{})),deployRelease:(role:Role,id:string,value:unknown={})=>request(role,`/releases/${id}/deploy`,body("POST",value)),rollbackRelease:(role:Role,id:string,reason:string)=>request(role,`/releases/${id}/rollback`,body("POST",{reason})),
  updateRelease:(role:Role,id:string,value:unknown)=>request<DevelopmentRelease>(role,`/releases/${id}`,body("PATCH",value)),
  createDebt:(role:Role,value:unknown)=>request<TechnicalDebtItem>(role,"/technical-debt",body("POST",value)),updateDebt:(role:Role,id:string,value:unknown)=>request(role,`/technical-debt/${id}`,body("PATCH",value)),
};
