import type { DocumentDetail,DocumentWorkspace,EnterpriseDocument,Role,UserDirectoryItem } from "@zyteron/contracts";
import { apiHeaders } from "./api-auth";
const base=()=>process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api";
async function request<T>(role:Role,path:string,init:RequestInit={}){const response=await fetch(`${base()}${path}`,{...init,headers:await apiHeaders(role,init.headers),cache:"no-store"});if(!response.ok){let message=`Error ${response.status}`;try{const data=await response.json() as{message?:string|string[]};message=Array.isArray(data.message)?data.message.join(" "):data.message||message;}catch{/* non-json */}throw new Error(message);}return response.json() as Promise<T>;}
const body=(method:string,value:unknown):RequestInit=>({method,body:JSON.stringify(value)});
export const documentsApi={
 workspace:(role:Role)=>request<DocumentWorkspace>(role,"/documents/workspace"),list:(role:Role,q="")=>request<{items:EnterpriseDocument[];total:number}>(role,`/documents${q?`?${q}`:""}`),detail:(role:Role,id:string)=>request<DocumentDetail>(role,`/documents/${id}`),users:(role:Role)=>request<UserDirectoryItem[]>(role,"/users/directory"),
 create:(role:Role,value:unknown)=>request<EnterpriseDocument>(role,"/documents",body("POST",value)),update:(role:Role,id:string,value:unknown)=>request(role,`/documents/${id}`,body("PATCH",value)),version:(role:Role,id:string,value:unknown)=>request(role,`/documents/${id}/versions`,body("POST",value)),download:(role:Role,id:string)=>request<{url:string|null;filename:string}>(role,`/documents/${id}/download`),verify:(role:Role,id:string)=>request<{matches:boolean;actualSha256:string}>(role,`/documents/${id}/verify-hash`,body("POST",{})),archive:(role:Role,id:string)=>request(role,`/documents/${id}/archive`,body("POST",{})),restore:(role:Role,id:string)=>request(role,`/documents/${id}/restore`,body("POST",{})),trash:(role:Role,id:string)=>request(role,`/documents/${id}/trash`,body("POST",{})),link:(role:Role,id:string,value:unknown)=>request(role,`/documents/${id}/links`,body("POST",value)),review:(role:Role,id:string,reviewerIds:string[])=>request(role,`/documents/${id}/reviews`,body("POST",{reviewerIds,mode:"SEQUENTIAL"})),approve:(role:Role,id:string)=>request(role,`/document-reviews/${id}/approve`,body("POST",{})),changes:(role:Role,id:string,comment:string)=>request(role,`/document-reviews/${id}/request-changes`,body("POST",{comment})),share:(role:Role,id:string)=>request(role,`/documents/${id}/share/client`,body("POST",{})),unshare:(role:Role,id:string)=>request(role,`/documents/${id}/unshare/client`,body("POST",{})),shareLink:(role:Role,id:string)=>request<{url:string;token:string}>(role,`/documents/${id}/share-link`,body("POST",{})),signature:(role:Role,id:string,signers:unknown[])=>request(role,`/documents/${id}/signatures`,body("POST",{signers})),comment:(role:Role,id:string,value:unknown)=>request(role,`/documents/${id}/comments`,body("POST",value)),templates:(role:Role)=>request<any[]>(role,"/document-templates"),preview:(role:Role,id:string,variables:Record<string,unknown>)=>request<{html:string;watermark:string;renderer:string}>(role,`/document-templates/${id}/render-preview`,body("POST",{variables})),
};
