import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  CircleGauge,
  Code2,
  FileStack,
  Headphones,
  Landmark,
  Settings,
  ShieldCheck,
  Users,
} from "lucide-react";

export interface NavigationItem {
  label: string;
  href: string;
  badge?: string;
}

export interface NavigationGroup {
  id: string;
  label: string;
  icon: LucideIcon;
  items: NavigationItem[];
}

export const enterpriseNavigation: NavigationGroup[] = [
  {
    id: "control",
    label: "Centro de control",
    icon: CircleGauge,
    items: [
      { label: "Resumen ejecutivo", href: "/dashboard" },
      { label: "Command Center", href: "/command-center" },
      { label: "Actividad", href: "/activity" },
      { label: "Notificaciones", href: "/notifications" },
    ],
  },
  {
    id: "commercial",
    label: "Comercial",
    icon: ChartNoAxesCombined,
    items: [
      { label: "Sales Command Center", href: "/commercial" },
      { label: "CRM", href: "/commercial/crm" },
      { label: "Leads", href: "/commercial/leads" },
      { label: "Oportunidades", href: "/commercial/opportunities" },
      { label: "Pipeline", href: "/commercial/pipeline" },
      { label: "Seguimientos", href: "/commercial/follow-ups" },
      { label: "Cotizaciones", href: "/commercial/quotes" },
      { label: "Ventas", href: "/commercial/sales" },
      { label: "Metas", href: "/commercial/goals" },
      { label: "Comisiones", href: "/commercial/commissions" },
      { label: "Handoff", href: "/commercial/handoffs" },
    ],
  },
  {
    id: "clients",
    label: "Clientes",
    icon: Building2,
    items: [
      { label: "Todos los clientes", href: "/clients" },
      { label: "Cliente 360°", href: "/clients/360" },
      { label: "Contactos", href: "/clients/contacts" },
      { label: "Contratos", href: "/clients/contracts" },
      { label: "Servicios contratados", href: "/clients/services" },
      { label: "Renovaciones", href: "/clients/renewals" },
    ],
  },
  {
    id: "operations",
    label: "Operaciones",
    icon: BriefcaseBusiness,
    items: [
      { label: "Centro de operaciones", href: "/operations" },
      { label: "Órdenes de trabajo", href: "/work-orders" },
      { label: "Proyectos", href: "/projects" },
      { label: "Tareas", href: "/tasks" },
      { label: "Hitos", href: "/milestones" },
      { label: "Worklogs", href: "/worklogs" },
      { label: "Entregables", href: "/deliverables" },
      { label: "Deployments", href: "/deployments" },
    ],
  },
  {
    id: "development",
    label: "Desarrollo",
    icon: Code2,
    items: [
      { label: "Dev Command Center", href: "/development" },
      { label: "Proyectos por asignar", href: "/development/assignments" },
      { label: "Equipo", href: "/development/team" },
      { label: "Carga de trabajo", href: "/development/workload" },
      { label: "Mis proyectos", href: "/development/my-projects" },
      { label: "Repositorios", href: "/development/repositories" },
      { label: "Pull Requests", href: "/development/pull-requests" },
      { label: "QA", href: "/development/qa" },
      { label: "Bugs", href: "/development/bugs" },
      { label: "Releases", href: "/development/releases" },
      { label: "Ambientes", href: "/development/environments" },
      { label: "Deployments", href: "/development/deployments" },
      { label: "Documentación técnica", href: "/development/docs" },
      { label: "Deuda técnica", href: "/development/technical-debt" },
    ],
  },
  {
    id: "monitoring",
    label: "Monitoreo",
    icon: Activity,
    items: [
      { label: "Sitios monitoreados", href: "/monitoring/websites" },
      { label: "Estado en tiempo real", href: "/monitoring/realtime" },
      { label: "Uptime", href: "/monitoring/uptime" },
      { label: "Incidentes", href: "/monitoring/incidents" },
      { label: "Certificados SSL", href: "/monitoring/ssl" },
      { label: "Ventanas mantenimiento", href: "/monitoring/maintenance" },
    ],
  },
  {
    id: "audits",
    label: "Auditorías",
    icon: ShieldCheck,
    items: [
      { label: "Audit Command Center", href: "/audits" },
      { label: "Planes de auditoría", href: "/audits/plans" },
      { label: "Auditorías programadas", href: "/audits/scheduled" },
      { label: "En ejecución", href: "/audits/in-progress" },
      { label: "Auditorías realizadas", href: "/audits/completed" },
      { label: "Hallazgos", href: "/audits/findings" },
      { label: "Remediaciones", href: "/audits/remediations" },
      { label: "Evidencias", href: "/audits/evidence" },
      { label: "Plantillas", href: "/audits/templates" },
      { label: "Informes", href: "/audits/reports" },
      { label: "Configuración", href: "/audits/settings" },
    ],
  },
  {
    id: "support",
    label: "Soporte",
    icon: Headphones,
    items: [
      { label: "Support Command Center", href: "/support" },
      { label: "Bandeja de entrada", href: "/support/inbox" },
      { label: "Mis tickets", href: "/support/mine" },
      { label: "Todos los tickets", href: "/support/all" },
      { label: "Clientes", href: "/support/clients" },
      { label: "Solicitudes internas", href: "/support/internal" },
      { label: "Incidencias", href: "/support/incidents" },
      { label: "Problemas", href: "/support/problems" },
      { label: "Cambios", href: "/support/changes" },
      { label: "SLA", href: "/support/sla" },
      { label: "Colas", href: "/support/queues" },
      { label: "Base de conocimiento", href: "/support/knowledge" },
      { label: "Respuestas rápidas", href: "/support/macros" },
      { label: "Satisfacción", href: "/support/satisfaction" },
      { label: "Informes", href: "/support/reports" },
      { label: "Configuración", href: "/support/settings" },
    ],
  },
  {
    id: "documents",
    label: "Documentos",
    icon: FileStack,
    items: [
      { label: "Document Command Center", href: "/documents" },
      { label: "Todos los documentos", href: "/documents/all" },
      { label: "Mis documentos", href: "/documents/mine" },
      { label: "Compartidos conmigo", href: "/documents/shared" },
      { label: "Clientes", href: "/documents/clients" },
      { label: "Proyectos", href: "/documents/projects" },
      { label: "Contratos", href: "/documents/contracts" },
      { label: "Cotizaciones", href: "/documents/quotes" },
      { label: "Órdenes de trabajo", href: "/documents/work-orders" },
      { label: "Finanzas", href: "/documents/finance" },
      { label: "Auditorías", href: "/documents/audits" },
      { label: "Soporte", href: "/documents/support" },
      { label: "Plantillas", href: "/documents/templates" },
      { label: "Pendientes de revisión", href: "/documents/reviews" },
      { label: "Pendientes de firma", href: "/documents/signatures" },
      { label: "Archivados", href: "/documents/archived" },
      { label: "Papelera controlada", href: "/documents/trash" },
      { label: "Configuración", href: "/documents/settings" },
    ],
  },
  {
    id: "hr",
    label: "RR.HH.",
    icon: Users,
    items: [
      { label: "People Command Center", href: "/hr" },
      { label: "Personal", href: "/hr/employees" },
      { label: "Organigrama", href: "/hr/org-chart" },
      { label: "Departamentos", href: "/hr/departments" },
      { label: "Equipos", href: "/hr/teams" },
      { label: "Cargos", href: "/hr/positions" },
      { label: "Contratos", href: "/hr/contracts" },
      { label: "Anexos", href: "/hr/annexes" },
      { label: "Expedientes", href: "/hr/files" },
      { label: "Onboarding", href: "/hr/onboarding" },
      { label: "Offboarding", href: "/hr/offboarding" },
      { label: "Vacaciones", href: "/hr/vacations" },
      { label: "Permisos", href: "/hr/permissions" },
      { label: "Licencias", href: "/hr/medical-leave" },
      { label: "Ausencias", href: "/hr/absences" },
      { label: "Jornadas y turnos", href: "/hr/schedules" },
      { label: "Asistencia", href: "/hr/attendance" },
      { label: "Remuneraciones", href: "/hr/payroll" },
      { label: "LRE / DT", href: "/hr/lre" },
      { label: "Activos asignados", href: "/hr/assets" },
      { label: "Evaluaciones", href: "/hr/performance" },
      { label: "Objetivos", href: "/hr/goals" },
      { label: "Capacitación", href: "/hr/training" },
      { label: "Solicitudes", href: "/hr/requests" },
      { label: "Vencimientos", href: "/hr/expirations" },
      { label: "Informes", href: "/hr/reports" },
      { label: "Configuración RR.HH.", href: "/hr/settings" },
    ],
  },
  {
    id: "finance",
    label: "Finanzas",
    icon: Landmark,
    items: [
      { label: "Financial Command Center", href: "/finance" },
      { label: "Facturación", href: "/finance/invoices" },
      { label: "Documentos tributarios", href: "/finance/tax-documents" },
      { label: "Cuentas por cobrar", href: "/finance/receivables" },
      { label: "Cobranza", href: "/finance/collections" },
      { label: "Pagos recibidos", href: "/finance/payments" },
      { label: "Pagos de cotizaciones", href: "/finance/quote-payments" },
      { label: "Cuentas por pagar", href: "/finance/payables" },
      { label: "Proveedores", href: "/finance/vendors" },
      { label: "Gastos", href: "/finance/expenses" },
      { label: "Bancos y cajas", href: "/finance/banks" },
      { label: "Conciliación", href: "/finance/reconciliation" },
      { label: "Contabilidad", href: "/finance/accounting" },
      { label: "Libro Diario", href: "/finance/journal" },
      { label: "Libro Mayor", href: "/finance/general-ledger" },
      { label: "Plan de cuentas", href: "/finance/chart-of-accounts" },
      { label: "Centros de costo", href: "/finance/cost-centers" },
      { label: "Presupuestos", href: "/finance/budgets" },
      { label: "IVA / Impuestos", href: "/finance/taxes" },
      { label: "Comisiones", href: "/finance/commissions" },
      { label: "Cierres contables", href: "/finance/closing" },
      { label: "Informes financieros", href: "/finance/reports" },
      { label: "Configuración contable", href: "/finance/settings" },
    ],
  },
  {
    id: "security",
    label: "Seguridad",
    icon: ShieldCheck,
    items: [
      { label: "Security Command Center", href: "/security" },
      { label: "Usuarios", href: "/security/users" },
      { label: "Identidades", href: "/security/identities" },
      { label: "MFA", href: "/security/mfa" },
      { label: "Roles", href: "/security/roles" },
      { label: "Permisos", href: "/security/permissions" },
      { label: "Sesiones", href: "/security/sessions" },
      { label: "Dispositivos", href: "/security/devices" },
      { label: "Accesos temporales", href: "/security/access-requests" },
      { label: "Vault", href: "/security/vault" },
      { label: "Secretos", href: "/security/secrets" },
      { label: "Eventos de seguridad", href: "/security/events" },
      { label: "Incidentes", href: "/security/incidents" },
      { label: "Vulnerabilidades", href: "/security/vulnerabilities" },
      { label: "RLS & Data Access", href: "/security/rls" },
      { label: "Privacy Center", href: "/security/privacy" },
      { label: "Data Inventory", href: "/security/data-inventory" },
      { label: "Retención", href: "/security/retention" },
      { label: "Derechos de titulares", href: "/security/subject-rights" },
      { label: "Evaluaciones de impacto", href: "/security/dpia" },
      { label: "DLP", href: "/security/dlp" },
      { label: "Proveedores", href: "/security/vendors" },
      { label: "Backups", href: "/security/backups" },
      { label: "Disaster Recovery", href: "/security/disaster-recovery" },
      { label: "Security Testing", href: "/security/testing" },
      { label: "CI/CD Security", href: "/security/cicd" },
      { label: "Compliance", href: "/security/compliance" },
      { label: "Security Gate", href: "/security/gate" },
      { label: "Informes", href: "/security/reports" },
      { label: "Configuración", href: "/security/configuration" },
    ],
  },
  {
    id: "reports",
    label: "Informes",
    icon: BarChart3,
    items: [
      { label: "Comercial", href: "/reports/commercial" },
      { label: "Clientes", href: "/reports/clients" },
      { label: "Proyectos", href: "/reports/projects" },
      { label: "Desarrollo", href: "/reports/development" },
      { label: "Uptime", href: "/reports/uptime" },
      { label: "Auditorías", href: "/reports/audits" },
      { label: "RR.HH.", href: "/reports/hr" },
      { label: "Finanzas", href: "/reports/finance" },
      { label: "Seguridad", href: "/reports/security" },
    ],
  },
  {
    id: "settings",
    label: "Configuración",
    icon: Settings,
    items: [
      { label: "Control Center", href: "/settings" },
      { label: "Empresa", href: "/settings/company" },
      { label: "Organización", href: "/settings/organization" },
      { label: "Departamentos", href: "/settings/departments" },
      { label: "Equipos", href: "/settings/teams" },
      { label: "Cargos", href: "/settings/organization" },
      { label: "Sedes", href: "/settings/organization" },
      { label: "Roles", href: "/settings/roles" },
      { label: "Permisos", href: "/settings/permissions" },
      { label: "Numeraciones", href: "/settings/numbering" },
      { label: "Calendarios", href: "/settings/calendars" },
      { label: "Automatizaciones", href: "/settings/automations" },
      { label: "Alertas", href: "/settings/alerts" },
      { label: "Notificaciones", href: "/settings/notifications" },
      { label: "Workflows", href: "/settings/workflows" },
      { label: "Aprobaciones", href: "/settings/approvals" },
      { label: "Plantillas", href: "/settings/templates" },
      { label: "Integraciones", href: "/settings/integrations" },
      { label: "Webhooks", href: "/settings/webhooks" },
      { label: "Feature Flags", href: "/settings/features" },
      { label: "Módulos", href: "/settings/modules" },
      { label: "IA", href: "/settings/ai" },
      { label: "Seguridad", href: "/settings/security" },
      { label: "Privacidad", href: "/settings/privacy" },
      { label: "Retención", href: "/settings/retention" },
      { label: "Portal Cliente", href: "/settings/client-portal" },
      { label: "Sistema", href: "/settings/system" },
      { label: "Jobs", href: "/settings/jobs" },
      { label: "Diagnósticos", href: "/settings/diagnostics" },
      { label: "Historial", href: "/settings/history" },
    ],
  },
];
