import type { KnowledgeArticle, Role, SupportCategory, SupportMacro, SupportQueue, SupportSlaPolicy, SupportTicket, SupportTicketDetail, SupportWorkspace, UserDirectoryItem } from "@zyteron/contracts";
import { apiHeaders } from "./api-auth";

const base=()=>process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api";
async function request<T>(role:Role,path:string,init:RequestInit={}){const response=await fetch(`${base()}${path}`,{...init,headers:await apiHeaders(role,init.headers),cache:"no-store"});if(!response.ok){let message=`Error ${response.status}`;try{const data=await response.json() as{message?:string|string[]};message=Array.isArray(data.message)?data.message.join(" "):data.message||message;}catch{/* non-json */}throw new Error(message);}return response.json() as Promise<T>;}
const body=(method:string,value:unknown):RequestInit=>({method,body:JSON.stringify(value)});
type Page<T>={items:T[];page:number;pageSize:number;total:number;totalPages:number};
export const supportApi={
  workspace:(role:Role)=>request<SupportWorkspace>(role,"/support/workspace"),search:(role:Role,q:string)=>request<SupportTicket[]>(role,`/support/search?q=${encodeURIComponent(q)}`),tickets:(role:Role,q="")=>request<Page<SupportTicket>>(role,`/support/tickets${q?`?${q}`:""}`),detail:(role:Role,id:string)=>request<SupportTicketDetail>(role,`/support/tickets/${id}`),users:(role:Role)=>request<UserDirectoryItem[]>(role,"/users/directory"),
  create:(role:Role,value:unknown)=>request<SupportTicket>(role,"/support/tickets",body("POST",value)),update:(role:Role,id:string,value:unknown)=>request<SupportTicket>(role,`/support/tickets/${id}`,body("PATCH",value)),assign:(role:Role,id:string,userId:string)=>request<SupportTicket>(role,`/support/tickets/${id}/assign`,body("POST",{userId})),priority:(role:Role,id:string,priority:string)=>request<SupportTicket>(role,`/support/tickets/${id}/change-priority`,body("POST",{priority})),status:(role:Role,id:string,status:string,reason?:string)=>request<SupportTicket>(role,`/support/tickets/${id}/change-status`,body("POST",{status,reason})),reply:(role:Role,id:string,message:string)=>request(role,`/support/tickets/${id}/reply`,body("POST",{body:message})),note:(role:Role,id:string,message:string)=>request(role,`/support/tickets/${id}/internal-note`,body("POST",{body:message})),resolve:(role:Role,id:string,value:unknown)=>request(role,`/support/tickets/${id}/resolve`,body("POST",value)),close:(role:Role,id:string)=>request(role,`/support/tickets/${id}/close`,body("POST",{})),reopen:(role:Role,id:string,reason:string)=>request(role,`/support/tickets/${id}/reopen`,body("POST",{reason})),createTask:(role:Role,id:string)=>request(role,`/support/tickets/${id}/create-task`,body("POST",{})),createBug:(role:Role,id:string)=>request(role,`/support/tickets/${id}/create-bug`,body("POST",{})),createChange:(role:Role,id:string)=>request(role,`/support/tickets/${id}/create-change-request`,body("POST",{})),copilot:(role:Role,id:string)=>request<{draft:string;sources:string[];warning:string}>(role,`/support/tickets/${id}/copilot`,body("POST",{})),
  queues:(role:Role)=>request<SupportQueue[]>(role,"/support/queues"),createQueue:(role:Role,value:unknown)=>request<SupportQueue>(role,"/support/queues",body("POST",value)),policies:(role:Role)=>request<SupportSlaPolicy[]>(role,"/support/sla/policies"),categories:(role:Role)=>request<SupportCategory[]>(role,"/support/categories"),macros:(role:Role)=>request<SupportMacro[]>(role,"/support/macros"),createMacro:(role:Role,value:unknown)=>request<SupportMacro>(role,"/support/macros",body("POST",value)),knowledge:(role:Role)=>request<KnowledgeArticle[]>(role,"/support/knowledge"),createKnowledge:(role:Role,value:unknown)=>request<KnowledgeArticle>(role,"/support/knowledge",body("POST",value)),publishKnowledge:(role:Role,id:string)=>request<KnowledgeArticle>(role,`/support/knowledge/${id}/publish`,body("POST",{})),
};
